### ISSUE TITLE
Sticky navbar disapears when the alert opens while scrolled down

### ISSUE THREAD

**Issue by angrykoala** [sweetalert2/sweetalert2#1002]
I have a top navbar that is always shown at the top when scrolling, if, scrolled down, an alert appears, the navbar dissapears (snaps back to the top) until the alert is closed.

I expected it to stay in the same place

* FIddle: https://jsfiddle.net/ad3quksn/767/

Thanks

**Comment by glendonyeo** [comment]
@limonte 

the only thing i could figure of is to set top css to sum of (window.pageYOffset + sticky element css top attribute) during modal show

but it will be infinite fixing progress and might causing other unexpected issues

maybe is it better to use onOpen / onBeforeOpen to handle?

**Comment by limonte** [comment]
thanks for investigating this issue, @glendonyeo! 

> maybe is it better to use onOpen / onBeforeOpen to handle?

Could you please elaborate a bit on this question?

**Comment by glendonyeo** [comment]
@limonte 

I believe is due to css position sticky behavior.
when overflow-y set to hidden, the element will stick to parent element starting position

This could fix the issues.
https://jsfiddle.net/n0jtbeq4/

**Comment by limonte** [comment]
@gaugejosh works nicely, thanks! I changed `onClose` to `onAfterClose` to prevent navbar flickering: https://jsfiddle.net/n0jtbeq4/1/

Let's think how we can apply this internally so users will not bother themselves with `onBeforeOpen` and `onAfterClose` callbacks.

**Comment by glendonyeo** [comment]
@limonte 

if the support is necessary, 
maybe you can try by getting all child element of body and check for sticky position,
below is my draft fiddle of making it happen with vanilla js 
https://jsfiddle.net/5gf2kyLw/

**Comment by limonte** [comment]
@glendonyeo great work, many thanks!

do you maybe know the reason of this jumpiness: https://jsfiddle.net/5gf2kyLw/1/ ?

**Comment by limonte** [comment]
Fixed by https://github.com/sweetalert2/sweetalert2/commit/e2d81de0c73edf93cf58bfd05365e46e24266e58 in v7.21.1
