### ISSUE TITLE
sweetalert closed by last target (about params.timer)

### ISSUE THREAD

**Issue by Skypow2012** [sweetalert2/sweetalert2#1003]
在 sweetalert2.js的140行，建议增加一个参数，叫做是否把上一次的timer去掉

我现在碰到了一个问题，我用swal创建了一个带timer的弹框A后，又在另一个地方新建了一个弹框B，新的弹框B会被A的这个timer给关掉
srcCodePosition:
sweetalert2.js 140,XX
if (params.timer) {
   domCache.popup.timeout = setTimeout(() => dismissWith('timer'), params.timer)
}

example:
swal({
  title: `A`,
  html: ``,
  timer: 5000
});
setTimeout(()=>{
  swal({
    title: `B`,
    html: ``
  })
}, 2000)
B will closed by A

**Comment by limonte** [comment]
> For bug reports, please include:
> - a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
> - expected behavior of the plugin
> - actual behavior
>
> JSFiddle template: https://jsfiddle.net/ad3quksn/663/
> 
> IE11 JSFiddle template: https://jsfiddle.net/ad3quksn/664/
> 
> See [ISSUE_TEMPLATE.md](https://github.com/limonte/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md)

And use English, please.

**Comment by Skypow2012** [comment]
OK, i find swal.close() for fix my issue, thank you for your time
