### ISSUE TITLE
Implement onAfterClose

### ISSUE THREAD

**Issue by Baune8D** [sweetalert2/sweetalert2#1004]
I have a script which compensates for the background moving when opening and closing a modal.

To get this working i need to run some code onBeforeOpen and onAfterClose (the latter function is not available right now).

Would it be possible to implement this? I would be happy to provide a Pull Request.

**Comment by toverux** [comment]
Would be nice to have and good for API symmetry.

**Comment by limonte** [comment]
Nice request, please go ahead with the PR @Baune8D :rocket:

**Comment by Baune8D** [comment]
@limonte PR created
