### ISSUE TITLE
Multiple Input Field Validation

### ISSUE THREAD

**Issue by jethro-yard8** [sweetalert2/sweetalert2#1012]
This may be a stupid question but how do you add validation for multiple html fields to check if they are empty before submitting? I can retrieve the values of the fields but they need validation.

```
        title: 'Details',
        html:
            '<p style="float: left;" autofocus>Name:</p>' +
            '<input id="swal-input1" class="swal2-input">' +
            '<p style="float: left;">Email:</p>' +
            '<input id="swal-input2" class="swal2-input">' +
            '<p style="float: left;">Description:</p>'+
            '<input id="swal-input3" class="swal2-input">' +
            '<p style="float: left;">Notes:</p>' +
            '<input id="swal-input4" class="swal2-input">',

        preConfirm: function () {
            return new Promise(function (resolve) {
                resolve([
                    $('#swal-input1').val(),
                    $('#swal-input2').val(),
                    $('#swal-input3').val(),
                    $('#swal-input4').val()
                ])
            })
        }
```

**Comment by limonte** [comment]
Validation of multiple fields isn't supported, you should implement it by yourself depending on your project.

**Comment by jesusaugusto0x2** [comment]
And how would be this implemented? I have a queue swal and have no idea on doing it :( please help!

**Comment by mhpm** [comment]
same here

**Comment by gverni** [comment]
@jesusaugusto0x2 @nhpm have a look to [this example](https://sweetalert2.github.io/sweetalert2-examples/forms/login/). Here we are validating that both username and password are not empty. You can replace that with whatever check you want to implement. The code for the example can be found  [here](https://github.com/sweetalert2/sweetalert2-examples/tree/master/src/forms/login)

**Comment by fannyhasbi** [comment]
Thank in advance @gverni

**Comment by fannyhasbi** [comment]
Thanks in advance @gverni

**Comment by obejashaundev** [comment]
I implemented a solution that might work...
`const { value: formValues } = await Swal.fire({
				title: 'Title',
				html: `
					<div class="form-group">
						<input type="text" class="form-control" id="input1" placeholder="Input something">
					</div>
					<div class="form-group">
						<input type="text" class="form-control" id="input2" placeholder="Input something">
					</div>
				`,
				focusConfirm: false,
				preConfirm: () => {
					let resultObject = {
						input1: document.getElementById('input1').value,
						inpu2: document.getElementById('input2').value
					}
					if (!resultObject.input1 || !resultObject.input2) {
						Swal.fire({
							title: 'Debes completar todos los campos para aplicar un descuento',
							icon: 'error'
						})
						return null
					}
					return resultObject
				},
				showConfirmButton: true,
				showCancelButton: true,
				confirmButtonText: 'Accept',
				cancelButtonText: 'Cancel'
			})

			if (formValues) {
				Swal.fire(JSON.stringify(formValues))
			}`

**Comment by obejashaundev** [comment]
I implemented a solution that might work...

```Javascript
const { value: formValues } = await Swal.fire({
				title: 'Title',
				html: '
					<div class="form-group">
						<input type="text" class="form-control" id="input1" placeholder="Type something">
					</div>
					<div class="form-group">
						<input type="text" class="form-control" id="input2" placeholder="Type something">
					</div>
				',
				focusConfirm: false,
				preConfirm: () => {
					let resultObject = {
						input1: document.getElementById('input1').value,
						input2: document.getElementById('inpu2').value
					}
					if (!resultObject.input1 || !resultObject.input2) {
						Swal.fire({
							title: 'You must complete all the fields to perform this operation.',
							icon: 'error'
						})
						return null
					}
					return resultObject
				},
				showConfirmButton: true,
				showCancelButton: true,
				confirmButtonText: 'Accept',
				cancelButtonText: 'Cancel'
			})

if (formValues) {
    Swal.fire(JSON.stringify(formValues))
}`
