### ISSUE TITLE
Modal buttons inherit background image CSS property

### ISSUE THREAD

**Issue by gverni** [sweetalert2/sweetalert2#1021]
If the main CSS has a button with background property set to an image, this is inherited in the modal button. Example: 

https://jsfiddle.net/ad3quksn/841/

If the image is not transparent (like in the JSFiddle) it can actually change the color of the buttons.

**Comment by limonte** [comment]
Done in https://github.com/sweetalert2/sweetalert2/pull/1022 and release in https://github.com/sweetalert2/sweetalert2/releases/tag/v7.16.0
