### ISSUE TITLE
sw2 get white screen on some devices

### ISSUE THREAD

**Issue by jasonz1987** [sweetalert2/sweetalert2#1038]
i used sw2 into my ionic project

it's worked for chrome,

but when i make an app ,

it's got white sceen when show sw2 alert,

100% on ios devices and some android devices

i can't see any erros on console,please give me some advices ...

**Comment by limonte** [comment]
> For bug reports, please include:
> - a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
> - expected behavior of the plugin
> - actual behavior
>
> JSFiddle template: https://jsfiddle.net/ad3quksn/663/
> 
> See [ISSUE_TEMPLATE.md](https://github.com/limonte/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md)
