### ISSUE TITLE
Incorrect question mark layout

### ISSUE THREAD

**Issue by tapz** [sweetalert2/sweetalert2#1039]
The question mark is not displayed in the correct position. Works in 7.12.16, but in some version after that not. See the screenshot. Using Chrome 65.0.3325.162.

<img width="324" alt="screen shot 2018-03-23 at 14 02 16" src="https://user-images.githubusercontent.com/11726387/37828474-0d65288a-2ea4-11e8-9545-bce4a71a840f.png">

**Comment by limonte** [comment]
> For bug reports, please include:
> - a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
> - expected behavior of the plugin
> - actual behavior
>
> JSFiddle template: https://jsfiddle.net/ad3quksn/663/
> 
> See [ISSUE_TEMPLATE.md](https://github.com/limonte/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by tapz** [comment]
This is causing it:

span {
    font: normal 14px/18px 'Montserrat', helvetica, sans-serif;
}

https://jsfiddle.net/ad3quksn/931/

**Comment by limonte** [comment]
You don't need to change the font-size and line-height of the icon: https://jsfiddle.net/ad3quksn/966/
