### ISSUE TITLE
Didn't transpile correctly with Parcel because incorrect jsnext:main

### ISSUE THREAD

**Issue by item4** [sweetalert2/sweetalert2#1049]
## What is the problem...

Can not use Parcel + sweetalert2 + IE 9. because transpile result contain arrow function.
[the official demo with Parcel also contain arrow function.](https://github.com/sweetalert2/sweetalert2-parcel-demo/blob/master/dist/46c7fdd3fcb347b46798ee5bb1d5a960.js) You can find arrow function from build dist easily.

## It's not bug of Parcel. The full story is here.

https://github.com/parcel-bundler/parcel/issues/1037

## Please fix it correctly

Please fix `jsnext:main` correctly. It must be ES6-module entry point.

**Comment by limonte** [comment]
Thanks for reporting, `jsnext:main` will be removed in the next major release.

**Comment by gverni** [comment]
Hi @limonte sorry for the delay with this change (I was researching on this topic), but I was wondering if we should replace the deprecated `jsnext:main` with [`pkg.module`](https://github.com/rollup/rollup/wiki/pkg.module) or get rid of that entirely. What do you think?

**Comment by limonte** [comment]
@gverni `:%s/jsnext:main/module/` will close this issue and #1376

**Comment by gverni** [comment]
Just for the record, at the time of this comment, the issue reported here wasn't reproducible anymore (the output of parcel command did not have any arrows functions in it).

**Comment by limonte** [comment]
> Just for the record, at the time of this comment, the issue reported here wasn't reproducible anymore (the output of parcel command did not have any arrows functions in it).

https://github.com/parcel-bundler/parcel/commit/f75941c3cfeb189578e3f2f9579dc9909da1d7c0
