### ISSUE TITLE
IE 11 Placeholder breaks input validator text on validation failure

### ISSUE THREAD

**Issue by Ianpwest** [sweetalert2/sweetalert2#1050]
If you have an inputPlaceholder specified on your alert then input validation failure messages will not show up. Removing the inputPlaceholder will cause the control to function properly.

Please repro by opening this fiddle in IE11 and clicking submit. No validation failure message should appear. Remove the inputPlaceholder line and try again. The validation message should now appear

http://jsfiddle.net/pdxg1xo9/4/

Thanks!

**Comment by limonte** [comment]
Confirming the issue. IE11 :expressionless:

**Comment by Ianpwest** [comment]
Haha, IE11 strikes again! It's not a huge deal for me as I can just use the text as a label instead of placeholders for a workaround.

**Comment by limonte** [comment]
I just released [v7.20.9](https://github.com/sweetalert2/sweetalert2/releases/tag/v7.20.9) which contains the fix for this issue :tada:
