### ISSUE TITLE
queue behaves unexpectedly for non-input types

### ISSUE THREAD

**Issue by jlsjonas** [sweetalert2/sweetalert2#1055]
For bug reports, please include:

- [a jsfiddle](https://jsfiddle.net/t83bm5a6/4/) in order for us to be able to reproduce the issue
- expected behavior of the plugin:
have some output indicating which steps were agreed with (likely without a cancel button named "cancel"; but there are no other means of adding extra buttons either so this looks like the way to go)

- actual behavior
value: undefined unless all steps were answered with "yes"(confirmed)

**Comment by limonte** [comment]
This is how built-in queue functionality works, we will not change its behavior.

To achieve your expected behavior please use async/await, jefiddle: https://jsfiddle.net/ad3quksn/1092/
