### ISSUE TITLE
Toast is not responsive

### ISSUE THREAD

**Issue by gauraviitr** [sweetalert2/sweetalert2#1056]
On setting toast:true, the sweetalert is of a toast type. However its not shrinking in width on a mobile device. 

Note: for some ideas around this, check out: http://codeseven.github.io/toastr/demo.html

**Comment by limonte** [comment]
Can't reproduce:

![peek 2018-04-15 14-35](https://user-images.githubusercontent.com/6059356/38777999-4f373398-40ba-11e8-818d-d6f553508bc7.gif)

In future, please do not ignore https://github.com/sweetalert2/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md - it's there for a reason.

**Comment by zenflow** [comment]
@gauraviitr Please open another issue following the requirements detailed in the issue template, and we'll be happy to investigate
