### ISSUE TITLE
Why does the AJAX example not contain any AJAX?

### ISSUE THREAD

**Issue by legionio** [sweetalert2/sweetalert2#1064]
Simple question really.

How come the AJAX example contains no AJAX, but a Promise? I'm trying to setup an AJAX call and I can't find any examples of an actual AJAX call in the docs nor online for SweetAlert2.

Could any one provide a clear POST example script using the FetchAPI or even a link to a post? 

```
swal({
  title: 'Submit email to run ajax request',
  input: 'email',
  showCancelButton: true,
  confirmButtonText: 'Submit',
  showLoaderOnConfirm: true,
  preConfirm: (email) => {
    return new Promise((resolve) => {
      setTimeout(() => {
        if (email === 'taken@example.com') {
          swal.showValidationError(
            'This email is already taken.'
          )
        }
        resolve()
      }, 2000)
    })
  },
  allowOutsideClick: () => !swal.isLoading()
}).then((result) => {
  if (result.value) {
    swal({
      type: 'success',
      title: 'Ajax request finished!',
      html: 'Submitted email: ' + result.value
    })
  }
```

**Comment by Niladri24dutta** [comment]
@legionio  you can replace the value of `preConfirm` property like the below `fetch` api call for making an Ajax call. Check the example for Dynamic queue.

    preConfirm: () => {

        return fetch("api_URL")

          .then(response => response.json())

          .then(data => console.log(data)),

          .catch(() => {

            swal({

              type: 'error',

              title: 'Unable to get data'

            })

       )}

**Comment by legionio** [comment]
@Niladri24dutta Hey, thanks for the example!

I finally figured it out in the end but what I found confusing was regarding errors. 

More specifically when working with Laravel. Laravel has a Validator() function that sends back a response as `status:422` for an error. The Fetch API doesn't consider it an `error` so the `catch()` wouldn't pick it up. 

Since `catch()` wouldn't run naturally, I had to `throw error()` to trigger it. The problem was to get the actual validation error messages and use those as the error parameter. 

You need to run `response => response.json()` to get the messages so I posted on SO and got this 

fetch(...)
  .then((response) => {
    return response.json()
      .then((json) => {
        if (response.ok) {
          return Promise.resolve(json)
        }
        return Promise.reject(json)
      })
  })

Do you think that is the most efficient and _proper_ way of doing it?

**Comment by limonte** [comment]
The AJAX example was updated to use the Fetch API: https://sweetalert2.github.io/#ajax-request

**Comment by limonte** [comment]
Thanks for the request, @legionio

**Comment by legionio** [comment]
@limonte  Thank you for SweetAlert!

**Comment by limonte** [comment]
> @limonte Thank you for SweetAlert!

SweetAlert**2** :) Thanks for using it!
