### ISSUE TITLE
Sweet Alert 2 scrolling to top of page after firing Over Pop Up

### ISSUE THREAD

**Issue by fhariano** [sweetalert2/sweetalert2#1066]
I'm using the version 7.19.1 and when clicked on OK button is scrolling to top of page.
I resolved removing the called of the function I() inside JS file: sweetalert2.all.min.js

**Comment by limonte** [comment]
> For bug reports, please include:
> - a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
> - expected behavior of the plugin
> - actual behavior
>
> JSFiddle template: https://jsfiddle.net/ad3quksn/663/
> 
> IE11 JSFiddle template: https://jsfiddle.net/ad3quksn/664/
> 
> See [ISSUE_TEMPLATE.md](https://github.com/limonte/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md)
