### ISSUE TITLE
Android 4.4 WeakMap is not defined

### ISSUE THREAD

**Issue by lazaronixon** [sweetalert2/sweetalert2#1071]
Uncaught ReferenceError: WeakMap is not defined.

I included polyfill, without success

**Comment by lazaronixon** [comment]
Working on 7.1.1

**Comment by lazaronixon** [comment]
Yes it worked with https://unpkg.com/babel-polyfill@6.26.0/browser.js. Thanks

**Comment by limonte** [comment]
> we could change our requirement from "promise polyfill" to "babel-polyfill" and there would still be only 1 polyfill that users need to load in order to support older browsers.. and we would be able to use all of these modern js types.

- https://checkgzipcompression.com/?url=https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fpromise-polyfill%407.1.0%2Fdist%2Fpromise.min.js
- https://checkgzipcompression.com/?url=https%3A%2F%2Funpkg.com%2Fbabel-polyfill%406.26.0%2Fbrowser.js

I'm not sure that requiring our users to load 30 times more heavier polyfill is the acceptable solution :/

According to https://developer.android.com/about/dashboards/ Android 4.4 is still widely used (10.5%) and we can't just drop KitKat support.

So, for now, I think that this is what we need to think about:

> we may need to find another approach for storing the newly introduced instance properties

**Comment by zenflow** [comment]
@limonte please reconsider the cost.. it's 100kb.. compare that to the lost effort trying to solve this kind of problem that keeps popping up.. and the how the solutions usually involve avoiding using modern js features. Also keep in mind that many projects using babel already require this. I think it's hard to deny that what I proposed (use babel-polyfill) is the **simplest** approach, correct? I mean code compiled with babel seems to expect the new types to be present. Include this file and everything just works.. we don't need to stay on es5, and we don't need to worry if our code ([compiled](https://github.com/sweetalert2/sweetalert2/issues/942) or not) uses new object types (actually WeakMap is pretty old now). Do you think the cacheable (i.e. http 304) 100kb is not worth that benefit?

**Comment by zenflow** [comment]
> we may need to find another approach for storing the newly introduced instance properties

probably there is no way clean way to achieve the private properties without WeakMap. maybe just return to traditional `_privateProperties` which are not really private.

**Comment by limonte** [comment]
> please reconsider the cost.. it's 100kb..

100 kB is a lot. It  

> Also keep in mind that many projects using babel already require this.

There's also a lot of old-school projects which are using Bower/CDN/zip.

> I think it's hard to deny that what I proposed (use babel-polyfill) is the simplest approach, correct?

Absolutely correct, but I feel bad about asking people to include additional 100kB for showing popups.  

> probably there is no way clean way to achieve the private properties without WeakMap. maybe just return to traditional _privateProperties which are not really private

What do you think about #1072?

**Comment by zenflow** [comment]
> 100 kB is a lot. I don't know how to argue here, from first-world countries it's difficult to understand how it feels for people with the 2G/3G connection to use the modern Internet.

with a good connection it's nothing/negligible .. with a bad connection, well, using the internet will be slow, but the file is equal to one medium sized image, which I think is reasonable in order for things to "just work" for us developers

> There's also a lot of old-school projects which are using Bower/CDN/zip

I know that, my point was just that for many projects the whole 100-extra-kb issue does not apply because it's already being used. Some (not all) users will benefit from our sacrifice of simplicity, which counts when you weigh it out, i think.

> What do you think about #1072?

Yeah I guess including a WeakMap ourselves is probably not too much overhead, though I don't think that nor testing against one more browser gets to the root of the problem. I left some comments on that PR btw.

**Comment by limonte** [comment]
> but the file is equal to one medium sized image, which I think is reasonable in order for things to "just work" for us developers

Sounds like jQuery to me :D

**Comment by zenflow** [comment]
> Sounds like jQuery to me :D

jQuery back in the day when browser apis were missing and inconsistent across different browsers, yes I agree. And that's when it was really useful, and most devs agreed it was worth the bulk.

**Comment by limonte** [comment]
> And that's when it was really useful, and most devs agreed it was usually worth the bulk.

Agree, but jQuery-like "just-work" solutions are **temporary**. In one or two years we might drop old browsers supports (IE11, Android 4.4). After that it would be easy to say "Dear users, now you can drop Promise polyfill". But, if we include all polyfills, it won't be so easy for our users is we say "Dear users, now you can drop all polyfills" - they will break something for sure.

At least but not last, changing polyfill requirements is the breaking change, we can't do it in the current major range.

**Comment by mockdeep** [comment]
Seems to be related to this, we saw errors about `setPrototypeOf`. Unfortunately, `core-js`, which `babel-polyfill` uses under the hood, [doesn't cover this](https://github.com/zloirock/core-js/issues/391). Version `7.19.3` resolved this issue for us as well.

**Comment by limonte** [comment]
> Seems to be related to this, we saw errors about setPrototypeOf.

Not directly, but yes `setPrototypeOf` usage was fixed in the same PR: https://github.com/sweetalert2/sweetalert2/pull/1072/files#diff-b98ce4f7ccf3d234b478bc4348b0e468

Thanks for your feedback @mockdeep!

**Comment by mockdeep** [comment]
Ah, I see. FWIW, we saw this on IE10, which are still, unfortunately, > 2% of our users. Thanks for the fix!

**Comment by limonte** [comment]
> we saw this on IE10

Is SweetAlert2 working on IE10? :astonished:

**Comment by mockdeep** [comment]
With polyfills it is! At least for our use case.

**Comment by limonte** [comment]
Well, that's unexpected :)

I just ran unit tests against IE10, 19 of 85 FAILED. Please be careful, we do not provide IE10 support.

**Comment by mockdeep** [comment]
We'll keep that in mind. We don't use it extensively, and are in the process of shifting more towards bootstrap modals, anyway.

**Comment by limonte** [comment]
@zenflow 

Just discovered this tiny repo: https://github.com/mknichel/web-performance-anecdotes

> Etsy.com discovered that 160KB of additional images caused their bounce rate to increase 12% on mobile devices.

and this article from the beginning of 2016 which is even more relevant today: https://www.sitepoint.com/average-page-weight-increased-another-16-2015/

> **Users never complain about overweight pages**
> …because they abandon them. Analytics record those who successfully access a site. They won’t highlight those who couldn’t load obese pages or never returned again.

**Comment by mockdeep** [comment]
FWIW, anecdotally, I have an excellent mobile connection in the bay area, and I still regularly abandon web sites that are loading too slowly.
