### ISSUE TITLE
Incorrect types in typescript .d.ts

### ISSUE THREAD

**Issue by proProbe** [sweetalert2/sweetalert2#1075]
The types and docs in the current project doesnt reflect what actually exists on the Swal object.
Looking at the docs in:
https://sweetalert2.github.io/
We are not able to find anything that says anything about `fire` that is on the object:
![types](https://user-images.githubusercontent.com/3802899/39576551-cc2e59d0-4ede-11e8-8d7d-35c90a414a1d.png)

The `fire` is also used in the example of react-content that extends this library:
https://github.com/sweetalert2/sweetalert2-react-content

The types does not reflect this either
https://github.com/sweetalert2/sweetalert2/blob/master/sweetalert2.d.ts

**Comment by limonte** [comment]
@zenflow would you mind to take a look?

**Comment by proProbe** [comment]
@zenflow I could look into it a bit further. Unfortunately, I do not have the time right now. The `fire` typing is quite trivial though.

**Comment by zenflow** [comment]
@proProbe I'm not sure how to do it without just copying and pasting the types from the main function.

**Comment by limonte** [comment]
@toverux please take a look at this issue when you have time, thanks!

**Comment by limonte** [comment]
This is fixed starting from [v8.0.0](https://github.com/sweetalert2/sweetalert2/releases/v8.0.0)
