### ISSUE TITLE
Reminder：when you would change confirmButton‘s styles，be careful loading’ style

### ISSUE THREAD

**Issue by Evanna51** [sweetalert2/sweetalert2#1076]
Today I found my swal ‘s loading was undispalyed， then I noticed  ： ConfirmButton and loading in the same button DOM.
If you would change confirmButton's style， you can write like this：

`.swal2-actions:not(.swal2-loading) {
        button.swal2-confirm.swal2-styled{
...
}`

**Comment by limonte** [comment]
Thanks for this reminder @Evanna51 :)
