### ISSUE TITLE
Method mixin as setDefaults not working

### ISSUE THREAD

**Issue by projct1** [sweetalert2/sweetalert2#1078]
### Description
All settings from `mixin` not apply in further calling swal.
```js
window.swal = require('sweetalert2');

swal.mixin({
    showCancelButton: true
});

swal('Are u sure?', 'All data will be lost!', 'warning'); //without cancel button
```

**Comment by limonte** [comment]
Hello @projct1 and thank you for this question. `mixin()` method returns a new instance of `swal` which you should use:

```
window.swaWithCancelButton = swal.mixin({
    showCancelButton: true
});

swaWithCancelButton('Are u sure?', 'All data will be lost!', 'warning'); //without cancel button
```

I also added the example to docs site: https://sweetalert2.github.io/#mixin

**Comment by projct1** [comment]
@limonte Ok thanks, example was not quite clear :)
