### ISSUE TITLE
Allow l10n for validation messages of default validators

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1081]
The question from our [Gitter channel](https://gitter.im/sweetalert2/Lobby)

> Glauco Morais @glaucomorais May 05 02:28
> Anyone knows how to translate the validation messages of email input?

---

Currently, in order to localize validation messages, users need to override default validators because validation messages are hardcoded into them:

- https://github.com/sweetalert2/sweetalert2/blob/master/src/utils/defaultInputValidators.js#L5
- https://github.com/sweetalert2/sweetalert2/blob/master/src/utils/defaultInputValidators.js#L11

---

## Proposal

Introduce `validationMessage` string parameter. It will be used in default validators if set. If not set, the default validation message in English will be used.

Thoughts? objections?

**Comment by limonte** [comment]
Done in https://github.com/sweetalert2/sweetalert2/releases/tag/v7.20.0

```
Swal({
  input: 'email',
  extraParams: {
    validationMessage: 'Adresse e-mail invalide'
  }
})
```

https://jsfiddle.net/ad3quksn/1180/

**Comment by limonte** [comment]
UPD, `validationMessage` param was added in `7.28.0`, `extraParams` was deprecated :warning:

Now it's as simple as

```js
Swal({
  input: 'email',
  validationMessage: 'Adresse e-mail invalide'
})
```

**Comment by glaucomorais** [comment]
Thanks, @limonte .
