### ISSUE TITLE
Sweet alert - method mixin css issue!

### ISSUE THREAD

**Issue by harishankards** [sweetalert2/sweetalert2#1085]
Hi,

I'm trying to use sweet alert mixin(toast) as below:
```js
const toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 3000
      })

      toast({
        type: 'success',
        title: 'Signed in successfully'
      })
    }
```

[Here](https://sweetalert2.github.io/#mixin), it is looking great. But when I import it, it has less top and bottom padding and looks ugly(have a look below). What could be the reason?
![2018-05-12-053218_1360x768_scrot](https://user-images.githubusercontent.com/5006693/39951322-61379d02-55a6-11e8-929d-9f0de6f96b07.png)

**Comment by limonte** [comment]
You're probably overriding some styles.

Inspecting the toast might help: https://developer.chrome.com/devtools
