### ISSUE TITLE
Resposive mobile - inputValidator icon is deformed  

### ISSUE THREAD

**Issue by yehr59** [sweetalert2/sweetalert2#1091]
Hey, 

Have a little bug in mobile case : 

![sweetalert2 github io_ iphone 6_7_8](https://user-images.githubusercontent.com/22531451/40069368-61b40ca8-586b-11e8-96de-0934a2b82af2.png)

## solution possible

```
.swal2-popup .swal2-validationerror::before {
    width: 100%;
    height: 100%;
    max-width: 1.5em;
    max-height: 1.5em;
}
```

**Comment by limonte** [comment]
Fixed in v7.20.4

thanks for reporting @yehr59 !
