### ISSUE TITLE
dev mode (`yarn start`) is crashing in case of syntax error in js files

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1092]
Steps to reproduse:

1. `yarn start`
2. make syntax error in any `src/**/*.js` file, e.g. `_main.js`, e.g. the closing curly bracket from the very first line:

![image](https://user-images.githubusercontent.com/6059356/40075188-59aadea6-5884-11e8-82d8-2bc94dec6c63.png)

The watcher will crash:

![image](https://user-images.githubusercontent.com/6059356/40075684-93289898-5885-11e8-8ac9-f38afe3293b1.png)

**Comment by limonte** [comment]
@zenflow I wasn't able to figure out how to fix this, will you have time to take a look?

**Comment by zenflow** [comment]
Hey @limonte my laptop has died so until I buy a new one it would be hard to make a PR.. but I've taken a look.. I suggest changing the `--continue-on-lint-error` switch to `--continue-on-error` and find a way to (conditionally) catch and just report errors in the build tasks.. not sure how to catch errors in a gulp stream but it must be possible
