### ISSUE TITLE
Bug of export

### ISSUE THREAD

**Issue by wangbang0218** [sweetalert2/sweetalert2#1106]
npm install sweetalert2

node_modules/sweetalert2/dist/sweetalert2.all.js:5

`typeof exports === 'object' && typeof module !== 'undefined'` is wrong

it should be `typeof module === 'object' && typeof module.exports !== 'undefined'`

/*!
* sweetalert2 v7.20.8
* Released under the MIT License.
*/
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global.Sweetalert2 = factory());
}(this, (function () { 'use strict';

**Comment by limonte** [comment]
> typeof exports === 'object' && typeof module !== 'undefined' is wrong

Why? Is there any issue caused by this line?

**Comment by limonte** [comment]
> it should be typeof module === 'object' && typeof module.exports !== 'undefined'

Why? Any reasoning for that? Or just because you're saying so? :)

---

Here's the UMD template for the reference: https://github.com/chilts/umd-template/blob/master/template.js

**Comment by limonte** [comment]
Anyway, we're using rollup for bundling, here's the right place to report any issues about the umd template: https://github.com/rollup/rollup/issues

**Comment by wangbang0218** [comment]
it make `const swal = require('sweetalert2')` be `const sweetalert = require('sweetalert2').Sweetalert2`

because `typeof exports === 'object' && typeof module !== 'undefined'` false

**Comment by wangbang0218** [comment]
Rollup use `output: {
    file: 'bundle.es.js',
    format: 'es'
  }` for bundling another es bundle

Rollup submit the 'module' proposal, webpack is already supported 'module' in bundling

Config package.json like `{
  "main": "dist/dist.js",
  "module": "dist/dist.es.js"
}`

Two supports in one package maybe better
