### ISSUE TITLE
Property 'mixin' does not exist on type 'typeof swal'

### ISSUE THREAD

**Issue by kimmanwky** [sweetalert2/sweetalert2#1110]
I'm working on Angular 6 Project, using vscode IDE.

`
"dependencies": {
    "sweetalert2": "^7.20.9"
  }
`
<br>
I have run `npm i sweetalert2` and `import swal from 'sweetalert2';` in my code.

When I tried to use `swal.mixin({ .. })`, I'm getting the mixin error:

`Property 'mixin' does not exist on type 'typeof swal'`

Do I missed out anything?

**Comment by toverux** [comment]
No, the definition file does not contain this method yet.
It has to be updated, I'll try to have a look soon, but for the moment you can do this:

```ts
// @todo swal.mixin() is not in SweetAlert's .d.ts for now (see sweetalert2/sweetalert2/issues/1110)
(swal as any).mixin({ .. });
```

**Comment by darron1217** [comment]
The "moment" is quite long ...

It might be quite simple work isn't it?

**Comment by limonte** [comment]
@darron1217 we are opened for your contributions :)
