### ISSUE TITLE
Range selector is broken

### ISSUE THREAD

**Issue by alexismoreau** [sweetalert2/sweetalert2#1116]
Hello,
The range selector is broken.
The error is : 
```
sweetalert2:549 Uncaught TypeError: Cannot read property 'target' of undefined
    at resetValidationError (sweetalert2:549)
    at HTMLInputElement.range.oninput (sweetalert2:562)
```

Simple repro: On your website https://sweetalert2.github.io, The range selector doesn't work.

**Comment by limonte** [comment]
Fixed in the latest release :tada:

Thanks for reporting @alexismoreau!

**Comment by alexismoreau** [comment]
Thank you for your speed ! Amazing job
