### ISSUE TITLE
`animation` parameter causes focus bug

### ISSUE THREAD

**Issue by redochka** [sweetalert2/sweetalert2#1122]
See this screencast http://nimb.ws/3SYyic where the `animation` parameter causes the focus to be lost in the 2nd popup. In fact the `click me` button keep the focus. This is annoying because when using the keyboard to interact with the popup we find ourselves clicking again on the button instead of closing the 2nd popup.

See this screencast http://nimb.ws/3SYyic where the `animation` parameter is removed, and the bug is not reproduced.

Here is the JSFIDDLE : https://jsfiddle.net/redochka/7bow3tdj/3/

**Comment by limonte** [comment]
Fixed in v7.22.2, jsfiddle: https://jsfiddle.net/7bow3tdj/4/

Thanks for reporting @redochka :beers:
