### ISSUE TITLE
retrieve selected value of custom select option with html param

### ISSUE THREAD

**Issue by zb2oby** [sweetalert2/sweetalert2#1123]
hello, 
i can't figure out this issue,
i inserted a custom select element in my swal object with html parameter. but when i try to retrieve the selected value, this value is always the first value of options in it. It doesn't catch the selected value.

swal seems to disable the change event on the select element.

here my code 

```
$('#myButton').click(function(e) {
       e.preventDefault();
        let that = $(this);
        let html = $('.myDivWhichHasSelect').html();
        swal({
            title: 'title',
            html: html,
            showConfirmButton: true,
            showCancelButton: true,
        }).then(function(result){
            if(result.value) {
                let mySelectedValue = $('#MySelect option:selected').val();
                console.log(mySelectedValue);
              ===> here some code ...
              }
```

**Comment by limonte** [comment]
https://sweetalert2.github.io/#multiple-inputs

**Comment by zb2oby** [comment]
i could not figure it out with preConfirm but by selecting the selected option adding #swal2-content like this : $('#swal2-content #mySelect option:selected').val()
now i have the correct value
