### ISSUE TITLE
Parameter buttons not working

### ISSUE THREAD

**Issue by inesEl** [sweetalert2/sweetalert2#1126]
Hi,

I was trying sweetalert2 intending to migrate from version 1. However when I used the "buttons" parameter, it doesn't work (the cancel button doesn't appear) and I have this warning in the consol **"SweetAlert2: Unknown parameter "buttons""**.
Based on this wiki : https://sweetalert.js.org/guides/#upgrading-from-1x buttons parameter should be used instead of confirmButtonText and cancelButtonText.
 Could you please advise ?
Thank you.

Ines

**Comment by limonte** [comment]
You're using [SweetAlert2](https://sweetalert2.github.io/) but reading the documentation of [SweetAlert](https://sweetalert.js.org/). Those are different projects nowadays.

**Comment by acupajoe** [comment]
@inesEl the link mentioned in our migration pages is to compare our API version (SweetAlert2) with the original project's API (Sweetalert 2.x).

SweetAlert2 uses different button config options (found (here)[https://sweetalert2.github.io/] under *Configuration*).

You're probably looking for: `showCancelButton: true` and `cancelButtonText: 'Cancel'`

**Comment by inesEl** [comment]
@acupajoe ok thank you.
