### ISSUE TITLE
"TypeError: Cannot assign to read only property" since v7.19

### ISSUE THREAD

**Issue by aphofstede** [sweetalert2/sweetalert2#1129]
Since https://github.com/sweetalert2/sweetalert2/releases/tag/v7.19.0 we are getting an exception when running our test set.
Apparently more people do: http://joecaps.com/blog/2018/06/03/fixing-enzyme-unit-test-error-due-to-sweet-alert-2/

I tried to make a repro on codesandbox.io but can't get it to spit out the exception.

>  RUNTIME EXCEPTION  Exception occurred while loading your tests
> 
> TypeError: Cannot assign to read only property 'iterator' of function 'function Symbol() { [native code] }'
>     at /Users/alex/src/oris/node_modules/sweetalert2/dist/sweetalert2.all.js:1117:1
>     at _typeof (/Users/alex/src/oris/node_modules/sweetalert2/dist/sweetalert2.all.js:6:1)
>     at Object.defineProperty.value (/Users/alex/src/oris/node_modules/sweetalert2/dist/sweetalert2.all.js:9:1)
>     at __webpack_require__ (/Users/alex/src/oris/.tmp/mocha-webpack/1529507142402/webpack/bootstrap 0db65f9d7b9c9449e9c4:19:1)
>     at Object.<anonymous> (/Users/alex/src/oris/.tmp/mocha-webpack/1529507142402/frontend/test/app.spec.js:4:1)
>     at __webpack_require__ (/Users/alex/src/oris/.tmp/mocha-webpack/1529507142402/webpack/bootstrap 0db65f9d7b9c9449e9c4:19:1)
>     at run (/Users/alex/src/oris/node_modules/mocha-webpack/lib/entry.js:3:1)
>     at Array.forEach (<anonymous>)    at Object.<anonymous> (/Users/alex/src/oris/node_modules/mocha-webpack/lib/entry.js:10:1)
>     at Object.<anonymous> (/Users/alex/src/oris/.tmp/mocha-webpack/1529507142402/bundle.js:86507:30)
>     at __webpack_require__ (/Users/alex/src/oris/.tmp/mocha-webpack/1529507142402/webpack/bootstrap 0db65f9d7b9c9449e9c4:19:1)
>     at /Users/alex/src/oris/.tmp/mocha-webpack/1529507142402/webpack/bootstrap 0db65f9d7b9c9449e9c4:62:1
>     at Object.<anonymous> (/Users/alex/src/oris/.tmp/mocha-webpack/1529507142402/bundle.js:66:10)
>     at Module._compile (internal/modules/cjs/loader.js:654:30)
>     at Object._module2.default._extensions.(anonymous function) [as .js] (/Users/alex/src/oris/node_modules/mocha-webpack/lib/util/registerRequireHook.js:147:12)
>     at Module.load (internal/modules/cjs/loader.js:566:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
>     at Module.require (internal/modules/cjs/loader.js:598:17)
>     at require (internal/modules/cjs/helpers.js:11:18)
>     at /Users/alex/src/oris/node_modules/mocha/lib/mocha.js:250:27
>     at Array.forEach (<anonymous>)
>     at Mocha.loadFiles (/Users/alex/src/oris/node_modules/mocha/lib/mocha.js:247:14)
>     at Mocha.run (/Users/alex/src/oris/node_modules/mocha/lib/mocha.js:576:10)
>     at /Users/alex/src/oris/node_modules/mocha-webpack/lib/runner/TestRunner.js:196:25
>     at Compiler.<anonymous> (/Users/alex/src/oris/node_modules/mocha-webpack/lib/webpack/compiler/registerReadyCallback.js:26:7)
>     at Compiler.applyPlugins (/Users/alex/src/oris/node_modules/tapable/lib/Tapable.js:61:14)
>     at emitRecords.err (/Users/alex/src/oris/node_modules/webpack/lib/Compiler.js:264:11)
>     at Compiler.emitRecords (/Users/alex/src/oris/node_modules/webpack/lib/Compiler.js:371:38)
>     at emitAssets.err (/Users/alex/src/oris/node_modules/webpack/lib/Compiler.js:258:10)
>     at applyPluginsAsyncSeries1.err (/Users/alex/src/oris/node_modules/webpack/lib/Compiler.js:364:12)
>     at next (/Users/alex/src/oris/node_modules/tapable/lib/Tapable.js:218:11)
>     at Compiler.compiler.plugin (/Users/alex/src/oris/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
>     at Compiler.applyPluginsAsyncSeries1 (/Users/alex/src/oris/node_modules/tapable/lib/Tapable.js:222:13)
>     at Compiler.afterEmit (/Users/alex/src/oris/node_modules/webpack/lib/Compiler.js:361:9)
>     at require.forEach.err (/Users/alex/src/oris/node_modules/webpack/lib/Compiler.js:350:15)
>     at /Users/alex/src/oris/node_modules/webpack/node_modules/async/dist/async.js:473:16
>     at iteratorCallback (/Users/alex/src/oris/node_modules/webpack/node_modules/async/dist/async.js:1064:13)
>     at /Users/alex/src/oris/node_modules/webpack/node_modules/async/dist/async.js:969:16
>     at MemoryFileSystem.writeFile (/Users/alex/src/oris/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
>     at writeOut (/Users/alex/src/oris/node_modules/webpack/lib/Compiler.js:339:28)
>     at Immediate._onImmediate (/Users/alex/src/oris/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
>     at runCallback (timers.js:763:18)
>     at tryOnImmediate (timers.js:734:5)
>     at processImmediate (timers.js:716:5)
> 
> error Command failed with exit code 1.

**Comment by limonte** [comment]
Hello @aphofstede and thanks for reporting this issue!

I made a small change, but not 100% sure if it's a proper fix. Could you please try the latest release (v7.23.1) and let me know if the issue has been fixed? Thanks in advance!

**Comment by aphofstede** [comment]
Seems to work 👍

**Comment by limonte** [comment]
Great! I'm closing this issue then.

Thank again for reporting and have a nice day!

**Comment by zenflow** [comment]
@limonte I thought you were going to change this so that the Symbol and WeakMap implementations are only defined for internal use, i.e. not monkey patched onto the global/window object. There's no need to mess with the global environment, and it can cause users more confusing issues.

**Comment by zenflow** [comment]
This commit message (db291a3172259489ac41804998a5d87fa96cdeaa) doesn't fully make sense: 

> check and define window.Symbol, not global Symbol

The global `Symbol` *is* `window.Symbol`.

**Comment by limonte** [comment]
> I thought you were going to change this so that the Symbol and WeakMap implementations are only defined for internal use, i.e. not monkey patched onto the global/window object. There's no need to mess with the global environment, and it can cause users more confusing issues.

Theoretically, you're right, but I didn't succeed to make it work for Android 4.4 without using `window.`. Feel free to submit a PR.

**Comment by zenflow** [comment]
> Feel free to submit a PR.

Opened #1133

**Comment by limonte** [comment]
Thanks @zenflow merged and released in v7.24.1. @aphofstede sorry to bother you again, but could you please verify that v7.24.1 works for your project as well as v7.23.1?

**Comment by aphofstede** [comment]
Still works
