### ISSUE TITLE
Proper way to override scss variables on angular

### ISSUE THREAD

**Issue by darron1217** [sweetalert2/sweetalert2#1136]
On angular, I use `style.scss` file to customie plugins

I thought the code below would work, but it didn't
```scss
$swal2-font-size: 1.5rem;
@import '~sweetalert2/src/sweetalert2';
```
Only with `!important` worked.
```scss
$swal2-font-size: 1.5rem !important;
@import '~sweetalert2/src/sweetalert2';
```

Is it a proper way to override scss variable?

**Comment by limonte** [comment]
```scss
$swal2-font-size: 1.5rem;
@import '~sweetalert2/src/sweetalert2';
```

Should work, proof: https://github.com/sweetalert2/sweetalert2-parcel-demo
