### ISSUE TITLE
Unpkg cannot find module "dist/sweetalert2.all.js"

### ISSUE THREAD

**Issue by TrendyTim** [sweetalert2/sweetalert2#1138]
I just noticed that
https://unpkg.com/sweetalert2
yeilds
Cannot find module "dist/sweetalert2.all.js" in package sweetalert2@7.24.1

But https://unpkg.com/sweetalert2@7.24.0 
works

So examples the on the home page don't work (and neither does anyone else who uses the most up to date version)

**Comment by limonte** [comment]
Fixed, thanks for investigating and reporting @TrendyTim!

**Comment by limonte** [comment]
Seems to be the unpkg issue, reported: https://github.com/unpkg/unpkg.com/issues/115

**Comment by TrendyTim** [comment]
you're welcome, lucky i was looking to see if this suited my needs better than the original swal when i did :)
