### ISSUE TITLE
https://sweetalert2.github.io/#examples not working

### ISSUE THREAD

**Issue by AmitGuptaMT** [sweetalert2/sweetalert2#1139]
I have been trying to use https://sweetalert2.github.io/#examples but it is throwing errors in console.
Error: 

> Refused to execute script from 'https://unpkg.com/sweetalert2@7.24.1' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Please look into this ASAP.

**Comment by limonte** [comment]
Fixed, thanks for reporting @AmitGuptaMT!

**Comment by AmitGuptaMT** [comment]
I confirm that it is working now. Thanks @limonte :)
