### ISSUE TITLE
Bower can't resolve sweetalert2

### ISSUE THREAD

**Issue by lucasumberto** [sweetalert2/sweetalert2#1140]
Hi, 
Somehow sweetalert2 directory on bower_components disappeared, naturally the first thing i tried was
`$ bower install --save sweetalert2` 
and i got this:
`bower                          EINVRES Request to https://bower.herokuapp.com/packages/sweetalert2 failed with 502`

Tried on another machine and same error, i didn't tested npm because it was on the other machine bower_components directory so i just copy and paste...
But seems that sweetalert2 repository on bower is having problems.

Thanks!

**Comment by limonte** [comment]
The issue is on your side, or on Bower's side.

PS. Bower is deprecated, outdated and buggy dependency manager, consider not to use it.
