### ISSUE TITLE
textContent and html content

### ISSUE THREAD

**Issue by Hydro8** [sweetalert2/sweetalert2#1151]
Hi

I use sweetalert2 with ajax and SSE. I update my sweetalert with message from my server.

Now I try to use html instead of juste text.

With text, I used swal.getContent().textContent to change my modal text. But for html, it isn't working.

Is there a function to dynamically change html content ?

Thank for your project !

**Comment by limonte** [comment]
> swal.getContent().textContent to change my modal text. But for html, it isn't working.

https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML
