### ISSUE TITLE
Custom foreground color option?

### ISSUE THREAD

**Issue by hacknug** [sweetalert2/sweetalert2#1153]
I've been looking on the docs and the codebase and I think there no way to change the text color on a swal popup.

Am I missing something or is there any reason why such option doesn't exist? Default text color is too dark for my popup with a custom background color and I'd need it to be white instead of this dark-gray sass-produced color it has right now.

I can open a PR if you'd like me to. Just let me know.

**Comment by limonte** [comment]
No additional JS params for styling will be added in new releases.

The foreground color could be changed either with pure CSS https://jsfiddle.net/ad3quksn/1594/ or by overriding SASS variables: https://github.com/sweetalert2/sweetalert2-parcel-demo/blob/master/styles.scss

**Comment by Olfeix** [comment]
Pure css technique does not work in react
