### ISSUE TITLE
Unable use swal with src/sweetalert2.js for use in ES6

### ISSUE THREAD

**Issue by altbdoor** [sweetalert2/sweetalert2#1160]
To quote the [usage instructions](https://sweetalert2.github.io/#usage):

> It's possible to import JS and CSS separately, e.g. if you need to customize styles:
> ```js
> import swal from 'sweetalert2/src/sweetalert2.js'
> import 'sweetalert2/src/sweetalert2.scss'
> ```

However, after importing `sweetalert2/src/sweetalert2.js`, any calls to `swal` throws up an error of:
- Firefox 61: `TypeError: class constructors must be invoked with |new|`.
- Chrome 67: `Class constructor SwalWithGlobalDefaults cannot be invoked without 'new'`

As per required for a bug report:

- a JS Bin in order for us to be able to reproduce the issue
    I used CodeSandbox since it allows a `npm install`-like environment. https://codesandbox.io/s/n0mx3jn7nm

- expected behavior of the plugin
    A SweetAlert2 popup should appear.

- actual behavior
    An error occurs when attempting to call `swal`.

**Comment by limonte** [comment]
Thanks for the report @altbdoor!

Confirming the issue, the temp solution could be 

```js
import swal from 'sweetalert2/dist/sweetalert2.js'
```

But we need to figure out what's happening here. @zenflow do you have any quick guess?

I wonder how the same working in [sweetalert2-parcel-demo](https://github.com/sweetalert2/sweetalert2-parcel-demo).

**Comment by altbdoor** [comment]
@limonte yeah, I am using the same temporary solution as well 😄 thanks!

To test things out, I have forked the [sweetalert2-parcel-demo](https://github.com/altbdoor/sweetalert2-parcel-demo) repo, and did a fresh `npm install`. It seems to be getting the same issue as reported.

https://altbdoor.github.io/sweetalert2-parcel-demo/dist/

**Comment by limonte** [comment]
> To test things out, I have forked the sweetalert2-parcel-demo repo, and did a fresh npm install and npm build. It seems to be getting the same issue as reported.

Oops, thanks for pointing that out! It's a regression after https://github.com/sweetalert2/sweetalert2/pull/1045 

`v7.18.0` works fine, the issue appears in `v7.19.0` which contains #1045

**Comment by limonte** [comment]
@zenflow I need your help on this issue.

**Comment by limonte** [comment]
@zenflow did you maybe have a chance to take a look at this issue?

**Comment by zenflow** [comment]
@limonte no, i lost this issue, so thanks for the reminder.. i'm having a look now

**Comment by zenflow** [comment]
@altbdoor what is your use-case? why do you need to use the source instead of the compiled build?

**Comment by altbdoor** [comment]
Hi @zenflow 

Nope, there was no particular use-case. I was only trying to import the `src` since that was how it was documented on the site to import sweetalert before this.

**Comment by limonte** [comment]
> Nope, there was no particular use-case. I was only trying to import the src since that was how it was documented on the site to import sweetalert before this.

In that case, we can consider this as a documentation issue which is fixed now both for https://sweetalert2.github.io/ and the README.md

Thanks again, @altbdoor!

**Comment by zenflow** [comment]
@limonte We could also remove the src folder from the published package.. what do you think?
