### ISSUE TITLE
input not focus.

### ISSUE THREAD

**Issue by MansoorJafari** [sweetalert2/sweetalert2#1161]
Hello
I'm using below code in typescript file but input text not focus

> 

      
        swal({
            title: 'Submit your Github username',
            input: 'text',
            inputAttributes: {
                autocapitalize: 'on'
            },
            showCancelButton: true,
            confirmButtonText: 'Look up',
            showLoaderOnConfirm: true,
            preConfirm: (login) => {
                return fetch(`//api.github.com/users/${login}`)
                .then(response => {
                    if (!response.ok) {
                    throw new Error(response.statusText)
                    }
                    return response.json()
                })
                .catch(error => {
                    swal.showValidationError(
                    `Request failed: ${error}`
                    )
                })
            },
            allowOutsideClick: () => !swal.isLoading()
            }).then((result) => {
            if (result.value) {
                swal({
                title: `${result.value.login}'s avatar`,
                imageUrl: result.value.avatar_url
                })
            }
            })
        

> 

please direct me

**Comment by limonte** [comment]
> please direct me

here's your initial direction: https://github.com/sweetalert2/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Fenkols** [comment]
My cousin suggested I try betting online, so I searched for a local-friendly site. kheli bet Bangladesh [https://bet-kheli.com](https://bet-kheli.com) offered cricket and football bets with free bets weekly. They also have crypto bonuses for Indian players. I liked the simple interface and the way I could use the same account for casino and sports. The live casino section was surprisingly smooth, which made it more exciting than I expected.
