### ISSUE TITLE
is progress-steps.js dead code? 

### ISSUE THREAD

**Issue by webbiesdk** [sweetalert2/sweetalert2#1164]
I'm talking about `src/instanceMethods/progress-steps.js`. 

I don't see `progress-steps.js` referenced anywhere. And sweetalert2 builds just fine if you delete the file (unlike deleting any other file in the `instanceMethods` folder). 

So. Dead code? 
If that is the case you should probably also delete the progress-steps related methods from `sweetalert2.d.ts`. 

I can make a pull-request for both if you want.

**Comment by limonte** [comment]
Fixed in v7.25.1 

Thanks again for reporting!
