### ISSUE TITLE
third button (altActionButton) hover color issue

### ISSUE THREAD

**Issue by lithos-g** [sweetalert2/sweetalert2#1167]
I am using swetalert2 with the latest update for the third button (altActionButton).
But when I hover over the altActionButton it takes the color of confirmButton
```
swal({
type: 'warning',
title: 'numbers',
showCancelButton: true,
showAltActionButton: true,
confirmButtonColor: '#d33333',
cancelButtonColor: '#00417f',
altActionButtonColor: '#23c1c1',
altActionButtonText: 'One',
confirmButtonText: 'Two',
cancelButtonText: 'Three'
})
```
Have you any idea why this is happening?

**Comment by limonte** [comment]
Wrong repo, https://github.com/t4t5/sweetalert/issues
