### ISSUE TITLE
Why is the script adding a right Padding and dont remove it after showing a alert

### ISSUE THREAD

**Issue by Snickbrack** [sweetalert2/sweetalert2#1168]
this code:

`document.body.style.paddingRight = d.previousBodyPadding`

adds a padding to the body-element if a sweetalert element is active but doesn't remove it afterwards.

The Source for the sweetalert-script is this:
https://cdn.jsdelivr.net/npm/sweetalert2@7.25.0/dist/sweetalert2.all.min.js

I have commented this section out because it destroys my layout.

**Comment by limonte** [comment]
> For bug reports, please include:
>
> - a JS Bin in order for us to be able to reproduce the issue
> - expected behavior of the plugin
> - actual behavior
> 
> JS Bin template: https://jsbin.com/gutesej/edit?html,js,output
>
> JS Bin template for IE11 and other old browsers: https://jsbin.com/hirinit/edit?html,js,output
> 
> See [ISSUE_TEMPLATE.md](https://github.com/limonte/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by anish-techpro** [comment]
is this issue fixed??

**Comment by gverni** [comment]
Hi @anish-techpro we haven't had a feed-back from @Snickbrack as to how to reproduce it. If you have the same issue, can you share with us the code? You may want to follow [these instructions](https://github.com/sweetalert2/sweetalert2/wiki/How-to-provide-live-example-for-issue) to provide us the code sample.

**Comment by gverni** [comment]
@anish-techpro I had another look at this issue. The code reported by @Snickbrack in his report is actually part of the `undoScrollbar` function which is executed when the modal closes. This is the counterpart of `fixScrollbar` which is executed before the modal is shown, and his job is to put the padding back in the page. So the statement: 

> adds a padding to the body-element if a sweetalert element is active but doesn't remove it afterwards.

doesn't really stand. I cannot think of a use case where this is failing, but if you have one please do submit it and we'll have a look.

**Comment by anish-techpro** [comment]
https://jsfiddle.net/5jrf7cLy/27/

in this fiddle,
1. launch the modal
2. click "Save Changes" button
3. click 'ok' in the swal

repeat steps 2 & 3 for more than once or twice and you will see that the padding in the body getting increased, but on clicking 'ok' in the swal the padding is not removed.

please check.

**Comment by gverni** [comment]
Thanks @anish-techpro for the reproduction steps. I raised #1409 to track this. You can subscribe to that issue to get update on the fix.
