### ISSUE TITLE
sweetalert2 error alert on invalid credentials

### ISSUE THREAD

**Issue by nueldev** [sweetalert2/sweetalert2#1169]
Hi, i'm using express for my backend and I was wondering how to use this repo and display error alert when the credentials are wrong on authentication? I couldn't find anything on google about this.

**Comment by limonte** [comment]
> If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then submit it to StackOverflow https://stackoverflow.com/questions/ask instead of GitHub, and make sure you add the `sweetalert2` tag to the question.

See [ISSUE_TEMPLATE.md](https://github.com/sweetalert2/sweetalert2/edit/master/.github/ISSUE_TEMPLATE.md)
