### ISSUE TITLE
Place the input element outside the label

### ISSUE THREAD

**Issue by ChazyTheBest** [sweetalert2/sweetalert2#1170]
I've noticed that sweetalert2 is placing the input element inside the label. While this is irrelevant for text boxes and such, it is not acceptable for radios and checkboxes, as in this case, the label cannot be styled based on the checked attribute.

Would it be ok to make this happen? This is such a simple change that I'd be able to do it myself (open a pull request), or maybe someone from the dev team or a contributor prefers to do this in a particular way? I'm not that experienced in js.

Thanks.

**Comment by limonte** [comment]
What exactly is the expected behavior?

**Comment by ChazyTheBest** [comment]
The expected behavior is the label having a different style depending on the checked attribute. For this, the input needs to be outside the label, as there's no way to select parent element (the label is the input's parent).

**Comment by limonte** [comment]
I added the `.swal2-label` class so you should be able to do this:

```css
input[type="radio"]:checked + .swal2-label {
  background: orange;
}
```

Live demo: https://jsfiddle.net/ad3quksn/1748/

**Comment by ChazyTheBest** [comment]
Hmm, thanks really, but that may not be necessary after all, sorry i'm slow... I just realized I can put html tags inside the `inputOptions`:

```javascript
swal({
    title: 'Input something',
    type: 'question',
    input: 'radio',
    inputOptions: {
        'one': '<span class="swal2-label">one</span>',
        'two': '<span class="swal2-label">two</span>'
    }
})
```

I can't believe I didn't try this sooner...

Now, not that I'm an expert, but I would use something like this for more consistency:

```javascript
case 'radio':
    var num = 1
    const radio = dom.getChildByClass(domCache.content, swalClasses.radio)
    radio.innerHTML = ''
    populateInputOptions = (inputOptions) => {
        inputOptions.forEach(([radioValue, radioLabel]) => {
            const radioDiv = document.createElement('div')
            const radioInput = document.createElement('input')
            const radioLabelElement = document.createElement('label')
            radioDiv.className = swalClasses.radio + num
            radioInput.id = swalClasses.radio + num
            radioInput.type = 'radio'
            radioInput.name = swalClasses.radio
            radioInput.value = radioValue
            if (innerParams.inputValue.toString() === radioValue.toString()) {
                radioInput.checked = true
            }
            radioLabelElement.innerHTML = radioLabel
            radioLabelElement.className = swalClasses.label
            radioLabelElement.htmlFor = swalClasses.radio + num
            radioDiv.appendChild(radioInput)
            radioDiv.appendChild(radioLabelElement)
            radio.appendChild(radioDiv)
            num++
        })
        dom.show(radio)
        const radios = radio.querySelectorAll('input')
        if (radios.length) {
            radios[0].focus()
        }
    }
    break
```

It's just a suggestion, this way users can directly style the label.
