### ISSUE TITLE
PHP Builder For SweetAlert2

### ISSUE THREAD

**Issue by varunsridharan** [sweetalert2/sweetalert2#1179]
Hi,
I am a big fan of SweetAlert2 and its been my fav js lib for almost since 2016
I always wanted to support this project. so i decided to create a php builder for it

https://github.com/varunsridharan/sweetalert2-php

Hope you guys could enjoy it.

**Comment by limonte** [comment]
Thanks @varunsridharan for building this tool and sharing it with us!
