### ISSUE TITLE
background displacement

### ISSUE THREAD

**Issue by nicolasvahidzein** [sweetalert2/sweetalert2#1190]
Hello, i am seeing this weird bug that didn't use to happen with sweetalert1.

Any clue as to what i am doing wrong?

I know i use flexbox a lot but could this be causing it?

Thanks and I love your module by the way.

![003](https://user-images.githubusercontent.com/29876108/43492593-a52e98de-9521-11e8-8044-8be7510b71eb.jpg)

**Comment by limonte** [comment]
Thanks for reporting @nicolasvahidzein !

Which version of Bulma are you using? Can you provide the simple jsfiddle with the issue repro?

**Comment by nicolasvahidzein** [comment]
Hello, i'm using the version 0.7.1 of bulma and your latest build of sweetalert2.

I don't even know where to begin with jsfiddle. I have never used it before and loading all the packages i have on my ERP seems like an insane amount of work.

what do you suggest?

**Comment by nicolasvahidzein** [comment]
I was curious to see if it was working ok when i walked the versions back.

7.0.9 works great
7.20.9 is broken as well.
I'm trying 7.13.0 now and will revert back.

**Comment by limonte** [comment]
@nicolasvahidzein did you try setting the `heightAuto` param to `false`?

**Comment by nicolasvahidzein** [comment]
Nope, will try that now, i never even saw that variable. I'll test it ASAP. Thanks!!

**Comment by nicolasvahidzein** [comment]
You are brilliant sir. Thank you. That seems to have solved it.

**Comment by limonte** [comment]
Glad to help!
