### ISSUE TITLE
Warning on toast for "backdrop" and "allowOutsideClick" 

### ISSUE THREAD

**Issue by kimmanwky** [sweetalert2/sweetalert2#1191]
I'm using the following sweet alert configuration for sweetalert2 toast.
`
{ ...
toast: true,
backdrop: false,
allowOutsideClick: false,
... }
`

The sweetalert2 toast did show me what I wanted, but with the following warning.

> SweetAlert2: The parameter "backdrop" is incompatible with toasts

>  SweetAlert2: The parameter "allowOutsideClick" is incompatible with toasts

If I set "backdrop" to true (or remove it), the toast did show but with dark backdrop, which I don't want. 

Is this should be an issue? or there is a way to solve this?

I'm using sweet alert version:
`"sweetalert2": "^7.26.9"`

![image](https://user-images.githubusercontent.com/19542037/43561053-d56af0b6-9647-11e8-8cf8-edfe25d356c9.png)

**Comment by limonte** [comment]
Fixed in `v7.26.10`, thanks for reporting @kimmanwky!

The backdrop should not be shown for toasts, no need in `backdrop: false, allowOutsideClick: false`, just `toast: true` is enough.

**Comment by eafarooqi** [comment]
This issue exists in the latest release as well, can we reopen this?
