### ISSUE TITLE
Swal2 adds some commas at the beggining of the alert

### ISSUE THREAD

**Issue by pabloleban** [sweetalert2/sweetalert2#1194]
Here you can clearly see that some commas are added multiple times above the title.

https://jsbin.com/donerahaka/edit?js,output

![image](https://user-images.githubusercontent.com/13904174/43669308-5e63fad2-9758-11e8-9232-5b7b60b1ccdc.png)

It has something to do with the mapping I think, cause if I remove the map, it doesn't put those commas.

**Comment by acupajoe** [comment]
It just needs to have a `.join('')` at the end of the function call

See Example: https://jsbin.com/fuzibuzowa/edit?js,output

Closing as this doesn't pertain to the plugin, hope it helps!

**Comment by pabloleban** [comment]
@acupajoe Thank you! But is this a bug or what?
