### ISSUE TITLE
Docs for `text` argument may mislead people to write XSS vulnerabilities

### ISSUE THREAD

**Issue by jbarrieault** [sweetalert2/sweetalert2#1195]
The [docs for the `text` argument](https://sweetalert2.github.io/#configuration) state
> ... It can either be added to the object under the key "text" or passed as the second parameter of the function.

That however is innacurate (or misleading at the least) in that the second parameter is treated as HTML (or the `html` object argument key). This is subtle but it may lead to XSS vulnerabilities being created, under the assumption that the second argument syntax behaves the same as the object key syntax. (Ask me how I know 😜) 

[JS Bin example](https://jsbin.com/munugivebi/edit?html,js,output)

A solution may be as simple as rewording the docs, or a version bump in which the 2nd argument is treated the same way as `text`. Happy to work on a PR for either!

**Comment by limonte** [comment]
Hello @jbarrieault and sorry it took so long for me to respond here.

The issue is fixed in https://github.com/sweetalert2/sweetalert2.github.io/commit/9d0cac2b1d49ad53a4061862bcaf92f1603c0b6b

Thanks for reporting!
