### ISSUE TITLE
SweetAlert2: Unknown parameter "showConfirmButtom"

### ISSUE THREAD

**Issue by enbermudez** [sweetalert2/sweetalert2#1196]
Hi! I am integrating SweetAlert2 with Laravel 5.6 (and Vuejs) but even thought it has been working great, i am facing a problem that I simply don't understand. While creating a new notification, SweetAlerts throws the next error on console: 

`SweetAlert2: Unknown parameter "showConfirmButtom"`

But this is, as the documentations says: "a key that i can use if I pass an object into sweetAlert2"

Now, this is my "alert handling" function:

```
sweetAlert(title, text, type, showConfirmButtom) {
      showConfirmButtom = showConfirmButtom || true
      swal({
        title,
        text,
        type,
        confirmButtonText: 'Ok',
        showConfirmButtom
      })
    }
```

I am passing the next params:

```
title = 'Intento fallido';
text = 'Las credenciales no coinciden con nuestros registros.';
type = 'error';
confirm = 'true';
```

Is there anything wrong with my logic?

**Comment by limonte** [comment]
showConfirmButtoN

**Comment by enbermudez** [comment]
Thanks a lot, that happens when english is not your native language (?)

**Comment by enbermudez** [comment]
Thanks a lot, that happens when english is not your native language (?)
