### ISSUE TITLE
sweetalert.min.js:1 SweetAlert2: Unknown parameter "closeOnConfirm"

### ISSUE THREAD

**Issue by jlwgeneral** [sweetalert2/sweetalert2#1203]
laravel-admin   delete operation，in chrome Consele show
“sweetalert.min.js:1 SweetAlert2: Unknown parameter "closeOnConfirm"”

**Comment by limonte** [comment]
My PR was merged and the new version of `laravel-admin` was released. Upgrade `laravel-admin` and the issue should be gone.
