### ISSUE TITLE
Long Content in swal not optimized for print

### ISSUE THREAD

**Issue by molerat619** [sweetalert2/sweetalert2#1217]
When I print a long sweet alert with a lot of content (so inside swal you have to scroll) it will only print the first page. I'm not sure if that should be considered a bug.

Example: https://jsbin.com/muwudoxowa/1/edit?html,js,output

I would expect the whole content to be printed out on several pages.

Right now:
![image](https://user-images.githubusercontent.com/3458576/45306248-7adfd000-b51c-11e8-971a-f65fa8adaebf.png)

Print (note: only 1 page!): 
![image](https://user-images.githubusercontent.com/3458576/45306265-892dec00-b51c-11e8-8e44-cc9aed79a4d6.png)

**Comment by limonte** [comment]
Thanks for reporting @molerat619 and apologies for not responding promptly!

I'll try to figure out how to fix this, but I need to admit that I have the lack of knowledge here.

Any help would be highly appreciated here!

**Comment by molerat619** [comment]
Thanks for you response @limonte .

I am also not an expert. I don't know how you made it so the rest of the content is ignored and only your alert is printed, but that's already a start. I would guess you just need to have different css settings for the modal using `@media print` - e.g. different overflow behavior. Just some guesses.

**Comment by limonte** [comment]
Done, proof: https://dandy-closet.glitch.me/

Thanks for reporitng @molerat619!

**Comment by molerat619** [comment]
@limonte awesome, thank you for the quick fix! I will test it for my case next week and let you know.

**Comment by molerat619** [comment]
Update: It worked fine, thank you @limonte !

**Comment by limonte** [comment]
Thank you for your feedback @molerat619!
