### ISSUE TITLE
CDN is links are broken

### ISSUE THREAD

**Issue by gilbertoalbino** [sweetalert2/sweetalert2#1220]
When I try to run the examples in https://sweetalert2.github.io/#examples page the CDN links are broken and errors are triggered in console.
I accessed some cdn.jsdelivr.net libraries and they are all down too.
Just notifying!

**Comment by limonte** [comment]
Thanks for reporting @gilbertoalbino!

Looks like this issue: https://github.com/jsdelivr/jsdelivr/issues/18093
