### ISSUE TITLE
Input swal with password creates chrome alert and triggers password manager

### ISSUE THREAD

**Issue by nicolasvahidzein** [sweetalert2/sweetalert2#1222]
Hello,

how can i disable the swal when i set the input form to password?

it triggers this warning in chrome:

[DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) 

I usually use autocomplete=false but i do not see where i can attach this on the swal2 module.

Thanks.

**Comment by limonte** [comment]
1. https://sweetalert2.github.io/
2. ctrl + f
3. autocomplete

**Comment by nicolasvahidzein** [comment]
Hello Limonte, same here.

**Comment by diegodovalle** [comment]
autocomplete: 'none'
