### ISSUE TITLE
Provide ability to go back on a Chaining Modal.

### ISSUE THREAD

**Issue by SantiagoCityFlag** [sweetalert2/sweetalert2#1226]
On chained modals there is a very convenient next button.

However I would also like to go back and see previous modals not only cancel my progress.

Thank you!

**Comment by limonte** [comment]
Going back isn't in the core, but can be achived with `async/await`

Live demo: https://flowery-slime-1.glitch.me/
Source: https://glitch.com/edit/#!/flowery-slime-1

**Comment by minoblue** [comment]
@limonte Your answer perfectly working with version 7 but it's not working with version 8.
Give error: sweetalert2@8:1 Uncaught (in promise) TypeError: Cannot call a class as a function

**Comment by limonte** [comment]
@minoblue https://github.com/sweetalert2/sweetalert2/releases/tag/v8.0.0
