### ISSUE TITLE
Is it possible to change Sweet Alert window location ?

### ISSUE THREAD

**Issue by pandelis** [sweetalert2/sweetalert2#1237]
Hi,

I'd like to change the sweetalert window location, do you know if this is possible, please ?

Best regards

**Comment by limonte** [comment]
1. https://sweetalert2.github.io/
2. ctrl + f
3. position

**Comment by pandelis** [comment]
Thank you !
It works but now it moves all my window (not only the Sweet alert one).
Would you have any idea why ?
[Image1](https://postimg.cc/1f4k5tDF)
[Image2](https://postimg.cc/vg3KGFBX) 

Best

**Comment by limonte** [comment]
Not sure, in order to get proper help please provide a jsbin with the replication of your use-case.

> For bug reports, please include:
>
> - a JS Bin in order for us to be able to reproduce the issue
> - expected behavior of the plugin
> - actual behavior
> 
> JS Bin template: https://jsbin.com/gutesej/edit?html,js,output
>
> See [ISSUE_TEMPLATE.md](https://github.com/limonte/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md)
