### ISSUE TITLE
Feature Suggestion: Multiple Content Objects

### ISSUE THREAD

**Issue by darrena092** [sweetalert2/sweetalert2#1238]
The `html` option has now been replaced by `content`, which is a nice improvement, but it might make sense to allow multiple content objects to be specified as an array here.

At present, content must be specified in the following way:
```
swal({
    content: {
        element: "p",
        attributes: {
            innerText: "Test element"
        }
    }
});
```

It would be nice to be able to do this:

```
swal({
    content: [
        {
            element: "p",
            attributes: {
                innerText: "Enter your password below"
            }
        },
        {
            element: "input",
            attributes: {
                placeholder: "Password"
            }
        }
    ]
});
```
Happy to submit a PR, just wanted to get a feel for what the opinion on this suggestion is before doing anything.

**Comment by limonte** [comment]
Wrong repo :) Here's the right one: https://github.com/t4t5/sweetalert

**Comment by darrena092** [comment]
Oops, thanks!
