### ISSUE TITLE
Modal closing itself automatically because of the "I don't care about cookies" extension

### ISSUE THREAD

**Issue by lvrnls** [sweetalert2/sweetalert2#1240]
Hello everyone,

I've come to an issue described below, do you know any way to get around this issue ?

## Current behavior

When I open a sweetalert modal, it confirm itself without me doing anything.
I think it comes from **I don't care about cookies extension** (I've tested on chrome and firefox) which close the modal, I suppose there is something related to cookie usage warning in the code of sweetalert modal or something.

## Expected behavior

The modal should not close itself without any click

## Live demo

https://sweetalert2.github.io/ -> when clicking on show success message (with I don't care about cookie extension enabled)

Thanks in advance !

**Comment by limonte** [comment]
The issue is on the extension side, you need to ask them to stop breaking the Internet.

**Comment by YardGnomeNinja** [comment]
Thank you SO much for figuring out what was causing this! I've been banging my head against it for a few days now.

**Comment by lvrnls** [comment]
Haha you are welcome ! I was trying to figure out myself wtf was the issue since friday !
Ok, it seems that the solution to get around this is to contact the plugin creators and I will
Thanks

**Comment by limonte** [comment]
Fixed in the latest release (2.9.3) of the "I don't care about cookie" extension 🎉
