### ISSUE TITLE
Cannot countdown whole seconds

### ISSUE THREAD

**Issue by Martinnord** [sweetalert2/sweetalert2#1241]
## Current behavior

I was looking at this example about a self closing sweetalert with a timer, https://codepen.io/anon/pen/XxNPdB. This counts down by `100`, which looks good, but I want it to count down every once second. So I tried change this:
```    
timerInterval = setInterval(() => {
      swal.getContent().querySelector('strong')
      .textContent = swal.getTimerLeft()
}, 100)
```
to this:
```    
timerInterval = setInterval(() => {
      swal.getContent().querySelector('strong')
      .textContent = swal.getTimerLeft()
}, 1000)
```
But when doing that it started acting weird, it doesn't show the time at first, then it shows `96x`. By `x` I mean it's a random number.
## Expected behavior

To have the timer to tick down once for every whole second. 10, 9, 8...

## Live demo

https://codepen.io/anon/pen/XxNPdB

**Comment by limonte** [comment]
You probably want to achieve this: https://jsfiddle.net/htf3sdw7/

**Comment by Martinnord** [comment]
Ah smart! Thank you mister.
