### ISSUE TITLE
Add option to show password for password input

### ISSUE THREAD

**Issue by antoninadert** [sweetalert2/sweetalert2#1243]
Current best practice is to allow user to check if the password is correct by allowing them to look at it.

It would be nice if we had an accessible toggle button (aria-pressed) that would let us show/hide the password

Please tell me if you need other information

**Comment by limonte** [comment]
This is a great UX feature, but I believe it should not be added to SweetAlert2. It's a custom input, custom inputs are out of scope of this plugin.

Here's the example with `hideShowPassword`: https://jsfiddle.net/m347aqc9/1/

`hideShowPassword` is accessible and themable. It's quite old though and depends on jQuery. If you a better plugin for password field, please share in this thread.

Thanks for the request and have a great day!
