### ISSUE TITLE
ajax doesn't send the request using XMLHttpRequest

### ISSUE THREAD

**Issue by foxmedo** [sweetalert2/sweetalert2#1245]
Hello,

i have check the feature using the fetch function doesn''t send the request using XMLHttpRequest which will cause some problem with the API which allow only XMLHttpRequest request 

can you show us how can we enabled this option if it exist ?

waiting for your feedback 

B.R

**Comment by zenflow** [comment]
This has nothing to do with SweetAlert2

**Comment by foxmedo** [comment]
are you sure ?? 

it's all about it sweetalert is sending ajax request to the server side and you are using fetch function this one doesn't send the request using XMLHttpRequest 

if you compare the request send by SweetAlert1 and 2 you will see that the SweetAlert2 doesn't send the request using XMLHttpRequest  are you using GET ???

**Comment by foxmedo** [comment]
this example using SweetAlert 
`HTTP_ACCEPT: "*/*"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,ar;q=0.6"
HTTP_ALEXATOOLBAR_ALX_NS_PH: "AlexaToolbar/alx-4.0.3"
HTTP_CACHE_CONTROL: "no-cache"
HTTP_CONNECTION: "keep-alive"
HTTP_COOKIE: "user=1-it7KY6IeAmPSdl0b; arp_scroll_position=1096; SE_session=ea7c9bf2df27128a2bbf65a527c84ead3803cbfc"
HTTP_HOST: "sengine.dz"
HTTP_PRAGMA: "no-cache"
HTTP_REFERER: "http://sengine.dz/pneus/marques"
HTTP_USER_AGENT: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
HTTP_X_REQUESTED_WITH: "XMLHttpRequest"`

and this using SweetAlert2
`HTTP_ACCEPT: "*/*"
HTTP_ACCEPT_ENCODING: "gzip, deflate"
HTTP_ACCEPT_LANGUAGE: "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,ar;q=0.6"
HTTP_ALEXATOOLBAR_ALX_NS_PH: "AlexaToolbar/alx-4.0.3"
HTTP_CACHE_CONTROL: "no-cache"
HTTP_CONNECTION: "keep-alive"
HTTP_COOKIE: "user=1-it7KY6IeAmPSdl0b; arp_scroll_position=1096; SE_session=2819718d3caa5cd81e33fb01742b0123f4ea9d83"
HTTP_HOST: "sengine.dz"
HTTP_PRAGMA: "no-cache"
HTTP_REFERER: "http://sengine.dz/pneus/marques"
HTTP_USER_AGENT: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"`

**Comment by zenflow** [comment]
SweetAlert2 does not make any network calls, using XMLHttpRequest or otherwise. 

As the issue template says, we want a reproduction for issues. Ignoring that does **not** earn you the good will of maintainers to help you with your problem free of charge.

Try to make a **minimal** reproduction of your issue and I think you will find that that minimal reproduction doesn't involve SweetAlert2.
