### ISSUE TITLE
iOS, Safari: document scrolling isn't prevented when a modal is shown

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1246]
Actual: It's possible to scroll the document under the modal backdrop

Expected: the scrolling isn't possible, because `overflow-y: hidden` on `<body>`

**Comment by limonte** [comment]
https://stackoverflow.com/q/52786341/1331425

**Comment by limonte** [comment]
Unfortunately, this didn't fix iOS :(

**Comment by atomiks** [comment]
See this lib for implementation, it locks body scroll for a scrolling modal container on iOS etc, cross-browser: https://github.com/willmcpo/body-scroll-lock

**Comment by limonte** [comment]
> See this lib for implementation, it locks body scroll for a scrolling modal container on iOS etc, cross-browser: https://github.com/willmcpo/body-scroll-lock

Not really, https://github.com/willmcpo/body-scroll-lock/issues/39

**Comment by kwagdy** [comment]
I'm using version 7.33.1 on chrome, and still able to scroll body behind the swal modal

**Comment by gverni** [comment]
Hi @kwagdy, is your problem with Chrome on IOS?

**Comment by kwagdy** [comment]
> Hi @kwagdy, is your problem with Chrome on IOS?

Hello @gverni, yeah, Chrome 72 on MacBook laptop

**Comment by gverni** [comment]
Thanks @kwagdy, I tried with the examples on https://sweetalert2.github.io/ on Chrome 72 on a macbook, but I wasn't able to scroll the body (I used the mouse's scroll wheel). Do you have a live example that shows that? Or maybe a screen recording? (you can use extension like [this](https://www.useloom.com/) for that)

**Comment by kwagdy** [comment]
sure... 
![bg_scroll](https://user-images.githubusercontent.com/15840617/54299816-51375c80-45c4-11e9-92e9-9b7caa58a8c2.gif)

**Comment by limonte** [comment]
Hello @kwagdy and thank you for proving the screen recording!

I have the offtopic question regarding the screen recording above. As I understand correctly, it's the Arabic language there which is RTL. Should the `question` icon contain `؟` instead of `?` for Arabic language?

**Comment by kwagdy** [comment]
> Hello @kwagdy and thank you for proving the screen recording!
> 
> I have the offtopic question regarding the screen recording above. As I understand correctly, it's the Arabic language there which is RTL. Should the `question` icon contain `؟` instead of `?` for Arabic language?

You're right on both your notes, this is an Arabic RTL web app, and yes, I should find a way to flip the question mark!

**Comment by gverni** [comment]
@kwagdy can you confirm whether you see the same on any of the example on https://sweetalert2.github.io/? If not, any chance you can share a live example of your page (or an extract of that)?

**Comment by kwagdy** [comment]
Is there a way to message you a link to the test page?

**Comment by gverni** [comment]
Thanks @kwagdy, let me do some test with the `position` and get back to you

**Comment by gverni** [comment]
Hi @kwagdy I tried setting the body `position` to `absolute` but I cannot see that. I created this _gltich_: 

https://swal2-body-absolute.glitch.me/

Feel free to _remix_ this glitch until it reproduces the issue for you.

**Comment by limonte** [comment]
> Hi @limonte , you're right on both your notes, this is an Arabic RTL web app, and yes, I should find a way to flip the question mark!

The proper way to flip the question mark is upcoming, see #1443 for the details.

**Comment by kwagdy** [comment]
@limonte Found the problem! See here [](https://beautiful-notebook.glitch.me/) for some reason I added this class
```
body.swal2-height-auto {
  overflow-y: visible !important;
  height: 100% !important;
}
```
I am not quite sure what was the reason behind this, but this combined with position absolute in the containing div, made the background page scrollable.

Thank you the flip question mark link 👍

**Comment by limonte** [comment]
Hm, the fix looks "dirty" to me. @kwagdy Did you try setting `heightAuto` parameter to `false`?

**Comment by kwagdy** [comment]
@limonte I'm almost certain I added it to fix an interim issue, just can't remember what :thinking: ! Anyway, I removed it, along with position absolute for the main area. Things seems to be in order now. Thanks a lot for following up on this :smiley:
