### ISSUE TITLE
main entry file is unminified js file

### ISSUE THREAD

**Issue by roopeshreddy** [sweetalert2/sweetalert2#1249]
## Current behavior
In the package.json, the below line
"main": "dist/sweetalert2.all.js",
which is causing the module bundler to pick the unminified version of the file.
## Expected behavior

It should pick the minified vesion of the file. May be - 

"main": "dist/sweetalert2.all.min.js",

**Comment by zenflow** [comment]
@roopeshreddy why is this a problem? don't you minify after bundling?

You can safely import 'sweetalert2/dist/sweetalert2.all.min.js'

**Comment by limonte** [comment]
@roopeshreddy you can find all answer you need in @zenflow's questions :D

**Comment by roopeshreddy** [comment]
@zenflow @limonte We're using SweetAlert2 in Angular 6 app. When we did the analysis the final AOT build generated it's picking the unminified file from the SweetAlert2 dist file instead of the minified one.

**Comment by roopeshreddy** [comment]
I've done more analysis and found that -  Angular Webpack through CLI is not minifying the CSS present in the JS files. May be this is issue with the Angular ngWebpack. 

Meawhile, I just want to know, is there any harm to set the min file in the package.json instead of the souce file.

Thanks!
