### ISSUE TITLE
disable body scrolling when swal modal active

### ISSUE THREAD

**Issue by sreyes87** [sweetalert2/sweetalert2#1252]
Hi, i need to disable the body scroll when the modal is active, can anyone help me? With bootstrap modal is easier, because it adds a class to the body when it's active. In this case the class is added to the modal swal div.

**Comment by sreyes87** [comment]
Hi, i need to disable the body scroll when the modal is active, can anyone help me? With bootstrap modal is easier, because it adds a class to the body when it's active. In this case the class is added to the modal swal div.

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/47063090-690bdf80-d1e2-11e8-952e-c769b4487932.png)

Duplicate of #1246
