### ISSUE TITLE
Spell mistake

### ISSUE THREAD

**Issue by mikeycrostar** [sweetalert2/sweetalert2#1263]
Hello guys,

the key "validationMesage" is miss spell on the documentation and the interface, so it's doesn't work, it give me some compilation error (angular 6)
`swal({
      title: 'Inscrivez-vous à la newsletter',
      input: 'email',
      inputPlaceholder: 'Votre email',
      validationMesage: "Ceci n'est pas une adresse e-mail"
  })`

I figure out a way to bypass it, time to you to fix it:

`swal(<any>{
      title: 'Inscrivez-vous à la newsletter',
      input: 'email',
      inputPlaceholder: 'Votre email',
      validationMessage: "Ceci n'est pas une adresse e-mail"
    })`

Swal version: 7.28.8

**Comment by limonte** [comment]
Fixed in 7.28.9, thanks for reporting @mikeycrostar!
