### ISSUE TITLE
First toast disappear instantly

### ISSUE THREAD

**Issue by Nsbx** [sweetalert2/sweetalert2#1269]
## Current behavior
I have created a project with Angular 6 and i use toast on form, but actually if i hit the submit button the first toast disappear instanly.

![2018-10-29_17-04-41](https://user-images.githubusercontent.com/8930930/47664363-2d3c2700-db9f-11e8-87a1-e0fcbc487f66.gif)

To use Swal i have added the script in the import script of angular.json and i import swal like this in my component :

import Swal from 'sweetalert2';

What is wrong ?

Thank (and sorry if an issue about that already exist)

Edit :
oh i forgot i get this error in console with the first toast only

![image](https://user-images.githubusercontent.com/8930930/47664722-f9153600-db9f-11e8-82aa-de7adbaf6f5c.png)

**Comment by Nsbx** [comment]
https://codesandbox.io/s/81xo2yj180

I don't know why but it work well in preview but if you use this link : 

https://81xo2yj180.codesandbox.io/

The bug is here

**Comment by limonte** [comment]
I can not see any issues here: https://81xo2yj180.codesandbox.io/

What are the steps to reproduce the issue?

**Comment by Nsbx** [comment]
I only click on save :(

Edit : i just tested on firefox dev and yeah no problem
The problem is present on Chrome 65.0.3325.181 (my company manage the version so i can't update :( )
So sorry about that, if you think you can't fix it you can close the issue.

**Comment by Nsbx** [comment]
Ok i found the problem i'm so stupid ...
After look step by step the execution i haved see a strange behavior 
I have the extension "I don't care about cookie" and the extension broke your librarie ...
The only strange thing is if i use your lib with a cdn and not a compiler they work fine.
So i'm aware for the futur

**Comment by limonte** [comment]
> Ok i found the problem i'm so stupid ...

This is not you fault. 

> I have the extension "I don't care about cookie" and the extension broke your librarie ...

I'm starting to think that we should make a workaround for that extension. This is already the third issue about it.

Previous two:

 - https://github.com/sweetalert2/sweetalert2/issues/1240
 - https://github.com/sweetalert2/sweetalert2/issues/1257

**Comment by gverni** [comment]
Hi @limonte i had a quick look to the source code of that extension. The author is using a `querySleectorAll` to search for the classes (among many others) `.swal2-shown .swal2-confirm`. This code is executed every 500ms interval until a popup is detected and closed. Once the popup is closed, a `clearInterval()` is called. That is why only the first popup (and not the subsequent) gets closed by the extension.

A workaround could be to check if the popup is still on after 500+ ms and if not we can log something on console. At least we can help developers to figure out what's happening (if we cannot help the end user)

**Comment by zenflow** [comment]
@gverni So the extension author is targetting sweetalert2 modals.. very interesting. 

Maybe we could reach out to them and get their thoughts on how sweetalert2 can work with their extension for the use cases that have nothing to do with cookies... Breaking all kinds of other things seems like a high price for not being bothered about cookies.

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/47896566-cb1d4380-de76-11e8-8a7a-158ef0fd4972.png)

**Comment by limonte** [comment]
Fixed in the latest release (2.9.3) of the "I don't care about cookie" extension 🎉 

![image](https://user-images.githubusercontent.com/6059356/47917156-43a0f600-deb1-11e8-80f6-1d46dc3cb4e7.png)
