### ISSUE TITLE
How do I get the SweetAlert-Variable to php?

### ISSUE THREAD

**Issue by mk304** [sweetalert2/sweetalert2#1270]
Hello everybody, I am very very new to PHP/JavaScript. So this question will be most probably very simple for most of you guys :) (Hopefully). 

I have this standard Sweetalert2 Textbox and it looks amazing and opens like a treat. Now... I don't know how I could get the Variable "text" into a PHP- Variable, I need it in PHP, so that I can add it to my Database .... I know that I need to use AJAX ( something along these lines)

` $.ajax({
        type: "POST",
        url: "sweetalerttext.php",
        data: { 'text': text})` 

but I don't know where exactly I have to add this AJAX code to my SweetAlert Code, nor do I know how I could set up my PHP File..... 

I googled the last couple of days and I can't find a foolproof tutorial anywhere. 

Would be super grateful if someone could help me out. 
I added the JQUERY to my header and the SweetAlert Files

Cheers 

Moritz 

Sweet-Alert Code ` $(document).ready(function () {
        $('#new-btn').click(function () {

            (async function getText () {
                const {value: text} = await swal({
                    input: 'textarea',
                    inputPlaceholder: 'Type your message here...',
                    showCancelButton: true
                });

                if (text) {
                    swal(text)
                }

            })()

        });

    })`

**Comment by gverni** [comment]
Hi @mk304, if i understood correctly what you want to do is to post to a php page the value returned by sweetalert. If this is the case, then you can add your ajax call inside the `if (text)` statement, something like: 

if (text) {
  $.ajax({ type: "POST", url: "sweetalerttext.php", data: { 'text': text})
}

Does that answer your question?

**Comment by mk304** [comment]
Hi @gverni, thank you so much for answering me! As you can see I added your lines of code, but they sadly don't run... (the button won't open), 
do you know what the problem could be...?
![image](https://user-images.githubusercontent.com/44285391/47876475-b2327500-de19-11e8-99d6-f7e54f9b4693.png)

 I also added a brace since I think one was missing, then the window opens but the chrome console tells me "Uncaught (in promise) TypeError: $.ajax is not a function
    at getText"


Thank you so so much for your help!

Kind regards 

Moritz

**Comment by gverni** [comment]
Hi @mk304 do you have the page available anywhere (e.g. codepen or similar) so i can have a look at the full page. 

> then the window opens but the chrome console tells me "Uncaught (in promise) TypeError: $.ajax is not a function
> at getText"

What do you mean exactly with "the window opens"? 

The error in console is pointing to an issue with jquery (not loaded properly?), but it would be helpful to have the full page.

**Comment by mk304** [comment]
hey @gverni, 
I am running the program on this server:
https://mars.iuk.hdm-stuttgart.de/~mk304/Web_Projekt/webpage/ui/sweetalert/sweetalert_eingabe.php

>What do you mean exactly with "the window opens"?<

When I click the button, the SweatAlert Textfield pops up and I can enter a text :) One again, I can't thank you enough for helping me! 👍

**Comment by gverni** [comment]
Hi @mk304, as suspected the error is due to the version of jquery you are using. You imported the slim version (which doesn't contain ajax). You can find more info [here](https://jquery.com/download/). You should replace the script tag for jquery with: 

```
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
```

With this one it should work fine.

**Comment by mk304** [comment]
I cannot thank you enough! I Think it worked!! In the Chrome inspector, I can see that AJAX started and that it sent the correct information. My very last question, because I think, that my ajax.php code is wrong... 
`<?php
echo $_POST['text'];


?>`
On the server: https://mars.iuk.hdm-stuttgart.de/~mk304/Web_Projekt/webpage/ui/sweetalert/ajax.php

what else do I need to add, to see the text, that I added in my original textbox?

Once again, I am very very grateful, thank you so much!

**Comment by gverni** [comment]
Hi @mk304 glad it worked. Since your question is not related to sweetalert2, I'm going to close this issue and we can follow-up on stackoverflow.
