### ISSUE TITLE
Backdrop Blur

### ISSUE THREAD

**Issue by 4dv0c47** [sweetalert2/sweetalert2#1278]
## New feature motivation

As an alternative to the current fade that appears when the alert is called, it'd be nice to have the option to blur the backdrop.

## New feature description

An effect that blurs the backdrop when the alert is called.

## New feature implementation

This can be done by applying the CSS rule `filter: blur(5px);` to it to a wrapper element.

**Comment by limonte** [comment]
Answered in https://github.com/sweetalert2/sweetalert2/issues/1205#issuecomment-415997185
