### ISSUE TITLE
Add @gverni to the list of collaborators

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1280]
Recently @gverni was added to collaborators of the `sweetalert2` repo and he already shown his great communication and good coding skills 🥇 

I will be more than happy to have him in the list of collaborators in the `README.md`, `package.json` and `bower.json` files.

PS. I just added @gverni to the `sweetalert2` organization, the similar PR is needed for https://github.com/sweetalert2/sweetalert2.github.io (https://sweetalert2.github.io/#collaborators)

**Comment by limonte** [comment]
@gverni would you mind to implement this issue? :)

**Comment by gverni** [comment]
It will be my pleasure :-) Thank you so much @limonte for your trust!
