### ISSUE TITLE
Drop down appear in allert with Materialize CSS

### ISSUE THREAD

**Issue by cheesemarathon** [sweetalert2/sweetalert2#1282]
## Current behavior

A drop down menu appears in alerts when the materialize css framwork is used and drop downs initialised. This occurs even if no input is specified

![image](https://user-images.githubusercontent.com/16329132/48146503-096a9680-e2ad-11e8-9e55-9fac74e1ba9c.png)

## Expected behavior

No dropdown to appear if it is not required as an input
![image](https://user-images.githubusercontent.com/16329132/48146529-1b4c3980-e2ad-11e8-8263-b72870943d5c.png)

## Live demo
https://jsbin.com/peqatexaze/edit?html,js,output

You will notice the dropdown appear. Remove:
```
$(document).ready(function(){
    $('select').formSelect();
});
```
and the dropdown will no longer appear.

**Comment by gverni** [comment]
Hi @cheesemarathon what happens here is the the call to `formSelect()` is  removing the `style="display: none;"` from the input select in swal. I'm not familiar with the materilize framework, so I was wondering what's the purpose of calling the `formSelect()`. Could you clarify?

**Comment by cheesemarathon** [comment]
According to the [materialize css documentation](https://materializecss.com/select.html#initialization) it is required to initialize the select element. I'm not sure myself exactly what it does so ill look into that some more. I'll also open an issue with the materialize css creators regarding this.

**Comment by cheesemarathon** [comment]
Im very unfamiliar with JavaScript but perhaps [this](https://github.com/Dogfalo/materialize/blob/v1-dev/js/select.js) script is the one causing conflicts. You may be able to understand it a little better than me.

**Comment by gverni** [comment]
Hi @cheesemarathon I think this has not much to do with sweetalert specifically. If you look at the example [here](https://jsbin.com/jegawomuqu/1/edit?html,js,output) where there is a simple html page with a `select` tag with `display: none;` you will see that this style is overwritten by the `formSelect()`. This shouldn't happen.

**Comment by cheesemarathon** [comment]
Thanks for your help @gverni I see exactly what you mean. I'll continue the conversation with materialize

**Comment by gverni** [comment]
Thanks @cheesemarathon. I'll close this issue for now. I subscribed to the issue on materialize and I'll be monitoring it in case there is anything to do on sweetalert.

**Comment by eduard182** [comment]
en el css colocar:

.swal2-container .select-wrapper{
	display: none !important;
}

**Comment by Behram-Khattak** [comment]
@cheesemarathon @gverni @eduard182 @nixta @pomartel Thanks's all of you guys this helped me, I was in a critical situation.

**Comment by andernunes** [comment]
Simple CSS rule works to me:

.swal2-popup .swal2-modal .swal2-icon-warning .swal2-show>.select-wrapper.input-field {
    display: none !important;
}
