### ISSUE TITLE
How to use AJAX for File transfer 

### ISSUE THREAD

**Issue by mk304** [sweetalert2/sweetalert2#1288]
Hello everybody, I really don't know if this is the right place to ask this question so pardon me if its the wrong place... 
I am really really desperate about this question.

I have a sweetalert/javascript function and I want my users to upload two images and one text to my database. I only found out how to upload images using basic HTML "file" boxes. But not how to do it with sweetalert.... so thats why I am posting this question here

This is my sweetalert/Javascript code
`<script>

    $(document).ready(function () {
        $('#new-btn').click(function () {

            swal.mixin({
                input: 'text',
                confirmButtonText: 'Next &rarr;',
                showCancelButton: true,
                progressSteps: ['1', '2', '3']
            }).queue([
                {
                    input: 'file',
                    inputAttributes: {
                        name:"image",
                        class:"image",

                    },
                    title: 'Profilbild hochladen',
                    text: 'Empfohlen wird 1X1'
                },
                {
                    input: 'file',
                    title: 'Hintergrundbild hochladen',
                    text: 'Empfohlen wird 16X9'
                },
                {

                    title: 'Über mich',
                    text: ''
                },

            ]).then((result) => {
                if (result.value) {

                    var kuerzeltest = "mk304";

                    $.ajax({ type: "POST",  url: "../../register/profil_update.php",
                        data: {"post":result.value[2], "kuerzel": kuerzeltest },

                    });  $.ajax({ type: "POST",  url: "../../register/profil_update.php",
                        data: {"bild":new FormData(this),"bild2":result.value[1], "kuerzel": kuerzeltest },
                        contentType: false,
                        processData: false,

                    });
                    swal(
                        "Super!",
                        "Dein Profil wurde erfolgreich aktualisiert ",
                        "success"

                    )
                }
            })
        });
    })'

My server where I run this code on https://mars.iuk.hdm-stuttgart.de/~mk304/Web_Projekt/webpage/ui/sweetalert/sweetalert_eingabe.php
I really don't know where my error is, would be super thankful for any tips or solutions.

Thanks so much!

Kind regards 

Moritz

**Comment by gverni** [comment]
Hi @mk304 I saw you raised the same question on stackoverflow. That is the right place for that. The issue you are having now doesn’t have much to do with sweetalert.
