### ISSUE TITLE
Cannot read property 'contains' of undefined 

### ISSUE THREAD

**Issue by VSKerberos** [sweetalert2/sweetalert2#1289]
## Current behavior

Hi I have Angular project which version is 5.2.0 I try to use ngsweetalert2 in my project.

I have defined in my module and call the simple page but got an error "Cannot read property 'contains' of undefined" what would be the problem ?

Thanks.
`
@NgModule({
imports: [
DashBoardModule,
routing,
PageNotFoundModule,
SweetAlert2Module.forRoot()

<button [swal]="deleteSwal">Delete 
<swal #deleteSwal
title="Delete "
text="This cannot be undone"
type="question"
[showCancelButton]="true"
[focusCancel]="true"
(confirm)="deleteFile(file)">
ng:///DashBoardModule/DashBoardComponent.ngfactory.js:775 ERROR TypeError: Cannot read property 'contains' of undefined
at hasClass (:8181/scripts/sweetalert2.js:332)
at getChildByClass (:8181/scripts/sweetalert2.js:373)
at init (:8181/scripts/sweetalert2.js:515)
at setParameters (:8181/scripts/sweetalert2.js:1653)
at NoNewKeywordSwal._main (:8181/scripts/sweetalert2.js:1831)
at NoNewKeywordSwal._main (:8181/scripts/sweetalert2.js:1140)
at NoNewKeywordSwal.SweetAlert (:8181/scripts/sweetalert2.js:2508)
at NoNewKeywordSwal.SwalWithGlobalDefaults (:8181/scripts/sweetalert2.js:1134)
at new NoNewKeywordSwal (:8181/scripts/sweetalert2.js:1000)
at _construct (:8181/scripts/sweetalert2.js:123)`

**Comment by limonte** [comment]
Hi, please provide the live demo and specify the browsers/OS

**Comment by jfcherng** [comment]
@limonte

I just have the same error message on *IE 11* too. The problem I encounter is that in the following function,

https://github.com/sweetalert2/sweetalert2/blob/eac143acbe35555bbe13d09c6f97597d8cf2cc76/src/utils/aria.js#L9-L13

my first `el` in `bodyChildren` is a `SVGSVGElement` object which has no `contains` method. And that causes an exception as shown in the following screenshot from IE 11's dev tool.

![2018-12-09_10-19-30](https://user-images.githubusercontent.com/6594915/49692734-a8302e80-fb9c-11e8-8762-18cd73e515a9.png)

My temporarily ugly fix is adding a useless `contains` method for `SVGSVGElement`.

```js
if (typeof global.SVGSVGElement.prototype.contains === 'undefined') {
  global.SVGSVGElement.prototype.contains = () => false;
}
```

But it would be good to fix this in sweetalert2 :)

**Comment by limonte** [comment]
Thanks @jfcherng for the investigation! The fix is coming today 🚀
