### ISSUE TITLE
create custom buttons with url

### ISSUE THREAD

**Issue by mohamadhs** [sweetalert2/sweetalert2#1291]
## New feature motivation

create custom buttons with url next to the confirm button

## New feature description

How to create custom buttons with custom url that appear next to the Confirm button and Cancel button?

**Comment by gverni** [comment]
Hi @mohamadhs could you explain more what you mean by “buttons with url”? Do you mean a button that is opening a new url in the browser? If you could provide a detailed use case, that would help me understand better your request

**Comment by gverni** [comment]
Hi again @mohamadhs, I saw you raised a question on stackoverflow for the same thing. I’ll support you there, but please provide more info on what you want to achieve on the stackoverflow question

**Comment by mohamadhs** [comment]
@gverni here is image that shows better details:
https://imgur.com/a/VfgxNig

**Comment by limonte** [comment]
https://petal-interest.glitch.me/

**Comment by mohamadhs** [comment]
@limonte tnx...but I use sweetalert2 in laravel application ..How to set then.function in Laravel controller

this is an example of use sw2 in laravel controller:

SWAL::message('sry','your balance is not enough','error',['html'=> 'you can charge your aacount ' , 'showConfirmButton'=>false]);
