### ISSUE TITLE
Trying to upgrade from sweetalert to sweetalert2

### ISSUE THREAD

**Issue by vamsits** [sweetalert2/sweetalert2#1295]
We have sweetalert in our application and now trying to implement sweetalert 2. Mainly we are going for sweetaler2 to swap the YES and NO buttons. I followed below steps:
```
bower install --save sweetalert2
"angular-sweetalert": "latest" {added in the bower.json}
bower install swangular
```
Commented the older sweetalert parameters in the index.html
```
<!-- <link rel="stylesheet" type="text/css" href="components/bootstrap-sweetalert/lib/sweet-alert.css"> -->
 <!-- <script src="components/bootstrap-sweetalert/lib/sweet-alert.js"></script> -->
<!-- <script src="components/angular-sweetalert/SweetAlert.js"></script> -->
```
And added following in the index.html
```
<link rel="stylesheet" type="text/css" href="components/sweetalert2/dist/sweetalert2.min.css">
<script src="components/sweetalert2/dist/sweetalert2.all.min.js"></script>
<script src="components/swangular/swangular.js"></script>
```
After these changes the new sweetalert2 started working.
But it is not appearing normally. Attached is the screenshot. Please let me know on how to show it as a sweetalert 1 like white background and blue YES button and Grey cancel button. 

![](https://user-images.githubusercontent.com/40022472/48611520-74eaed00-e9ac-11e8-8a41-6e10c660d341.png)

**Comment by vamsits** [comment]
![image](https://user-images.githubusercontent.com/40022472/48611520-74eaed00-e9ac-11e8-8a41-6e10c660d341.png)

**Comment by gverni** [comment]
Hello @vamsits would you be able to share your sweetalert code using http://sweetalert2.glitch.me/? You need to click on `Remix on glitch` then add your `swal` code and then paste here the new url you are given by glitch.

**Comment by vamsits** [comment]
Hi,
Please find the code in the below url
https://glitch.com/edit/#!/woozy-spaghetti?path=cool-file.js:14:25

**Comment by gverni** [comment]
Hi @vamsits your confirm button is red because you changed the color using: 

`confirmButtonColor: '#DD6B55',`

Just remove / comment that line and it will show it in blue. You can see my remix at https://debonair-cephalopod.glitch.me/

**Comment by vamsits** [comment]
I need also the size also should appear in the same as earlier sweetalert. Please tell me how to get the same size alerts

**Comment by gverni** [comment]
Hi @vamsits are you talking about the size of the popup or the size of the buttons? Sweetalert 2 is responsive so the size is adapting to the size of the screen / window. Could you send us a screenshot of your sweetalert 1.x pop-up compared to the sweetalert 2?

**Comment by vamsits** [comment]
Hi I commented confirmButtonColor: '#DD6B55', still I am getting in red color YES instead of blue. 
Also attached is the sweetaler1 popu-up
![image](https://user-images.githubusercontent.com/40022472/48616998-3b6dae00-e9bb-11e8-8aea-b1494c29cac7.png)
and given below is the sweetaler2 pop-up
![image](https://user-images.githubusercontent.com/40022472/48617053-58a27c80-e9bb-11e8-8b32-88f1ea3e3283.png)

**Comment by gverni** [comment]
Hi @vamsits you can change the size of the font using the `confirmButtonClass`, `cancelButtonClass` properties. You can also change the width of the modal using the `width` property.  

Regarding the color, please refer to my implementation at https://debonair-cephalopod.glitch.me/. You can clearly see that the button is the right color. You can check the source code of that at https://glitch.com/edit/#!/debonair-cephalopod?path=index.html:22:10
