### ISSUE TITLE
How to listen to confirm or cancel in R shiny with sweetalert2

### ISSUE THREAD

**Issue by madmark81** [sweetalert2/sweetalert2#1304]
Would you guys be able to help me how to make it work to listen to the confirm of cancel button in sweetalert2? My code that worked for sweetalert 1 doesn't work with the package. 

I used to add this to the javascript function 
 evalFunction = function(isConfirm){
if (isConfirm === true) {
var val1= 1;
Shiny.onInputChange('option1', [val1, Math.random()]);
}
else  {  
var val2= 2;
Shiny.onInputChange('option2'', [val2, Math.random()]);
}
}

see full app and code on this Stackoverflow page: 

https://stackoverflow.com/questions/53450161/observe-sweetalert2-confirm-with-javascript-in-r-shiny

Thanks a lot for making this nice package even better! 

Mark

**Comment by limonte** [comment]
StackOverflow is the right place for all how-to questions.
