### ISSUE TITLE
Queue progression absent in conjunction with timer close

### ISSUE THREAD

**Issue by Orbling** [sweetalert2/sweetalert2#1308]
## Current behavior

Queued items do not progress when using a timer to close.

## Expected behavior

When the timer setting causes the closure of a modal/toast, then the queue should advance.

Possibly related issue to closing not necessarily producing a dismiss reason.

## Live demo

https://glitch.com/edit/#!/join/e698d1e1-901d-42d6-8db0-78525e7296af

**Comment by gverni** [comment]
Hi @Orbling when the timer expires it trigger a dismiss event on the swal. The behavior you are seeing is consistent with what happen in a standard swal queue: if you click cancel button (or click outside the modal) then the modal closes and the queue is interrupted. Does that make sense?

**Comment by Orbling** [comment]
@gverni It does make sense indeed, though in many cases you might want a sequence of messages displayed on timers, particularly when used in conjunction with the toast option.  Perhaps timers need an option that corresponds to timeout, that could be generally useful.  I don't think 'cancel' is necessarily always the intended state of a timer expiring - again especially for toaster popups.

**Comment by gverni** [comment]
@Orbling what you want to do can be achieved with what's already available without changing the inner behaviour of swal and making it inconsistent.  

You can see a running example here: https://evanescent-meteorology.glitch.me/

Let me know if this is what you wanted to achieve.

**Comment by Orbling** [comment]
@gverni An interesting approach, I have not come by the `async`/`await` primitives before, I wonder what their browser support is like.  (Had a look, [85.6%](https://caniuse.com/#feat=async-functions) currently overall, only introduced to most major browser 2017 Q1.)

My use case requires a fair bit of adding to an active queue using `insertQueueStep()`, I could adapt the async function you generated in your example to view the array as a queue easily enough.  Though I'm not sure using async/wait has sufficient universality, though I am grateful for the introduction to them.

I still think there is a good case for a defined dismiss event on timer expiry.  Think of a shutdown/logout like command that asks "Are you sure?" and defaults to yes.  Essentially the concept is whether the timer expiry corresponds to the default option, cancel or another value.

NB. Slightly unrelated, but related to my use case, adding to a queue seems to require an initial call to queue.  I initially wanted to add normally and specify `queue: true` or some sort to not replace the existing swal call.  That's not a bug though, additional functionality.

**Comment by gverni** [comment]
> I wonder what their browser support is like

You can implement the same mechanism using `promises`. These are already used extensively in sweetalert2 so you should not be concerned about coverage. 

>I still think there is a good case for a defined dismiss event on timer expiry. Think of a shutdown/logout like command that asks "Are you sure?" and defaults to yes. Essentially the concept is whether the timer expiry corresponds to the default option, cancel or another value.

In the design of sweetalert2 a timeout expire is considered as dismissal because it doesn't return any value and it's not triggered by user intervention. IMHO, changing the swal behavior for the case of `toast` means complicating the internal logic of sweetalert and making it less flexible. And since there is already a way of achieving the same result (e.g. checking ` result.dismiss` object) , this loss of flexibility doesn't bring any additional value. 

> NB. Slightly unrelated, but related to my use case, adding to a queue seems to require an initial call to queue. I initially wanted to add normally and specify queue: true or some sort to not replace the existing swal call. That's not a bug though, additional functionality.

Maybe you can post this question on stackoverflow with a code example, and we can try to support you there.
