### ISSUE TITLE
Swal not working in androids themeablebrowser 

### ISSUE THREAD

**Issue by sweetalertquestion** [sweetalert2/sweetalert2#1310]
Hello im using swal in my android angular typescript app

But when i open the android themeablebrowser inside of my app, then i cant open swal() anymore.

I want to use it like

Browser.executeScript({ code: " swal(..) "}):

//With execute script i can inject javascript //into my browser. But it doesnt open at //all...  but i realy need it

I can use the usual alert() instead of swal() that would work but its not what i want sadly.

If u have any idea on how to get swal sorking inside themeable browser. I would realy be glad!

**Comment by gverni** [comment]
Hi @sweetalertquestion this doesn’t seem an issue with sweetalert. Can you raise a question on stackoverflow with tag `sweetalert2` (and any other relevant tags) sharing your code and possibly any log?

**Comment by sweetalertquestion** [comment]
Its not a problem with my project sadly.

I can use swal inside of any page inside of my app, but when i open the android browser inside my app(themeablebrowser or inappbrowser) then swal does not open anymore, no matter what i tried.

I think there are 2 possibilitys:

1. Swal is not made for those 2 android browsers(themeable/inapp) and maybe there is a way to change it. They dont log or open swal at all at the moment. But without opening the browsers i can open swal.

2. I have to include anything which allows me to swal inside those browsers


Thanks if anyone knows anything

**Comment by limonte** [comment]
> Its not a problem with my project sadly.
> I can use swal inside of any page inside of my app, but when i open the android browser inside my app(themeablebrowser or inappbrowser) then swal does not open anymore, no matter what i tried.

This isn't the right place to ask Cordova-related questions. This is the right one: Its not a problem with my project sadly.
