### ISSUE TITLE
sweetalert2 cancelable timer problem

### ISSUE THREAD

**Issue by teodorsandu** [sweetalert2/sweetalert2#1321]
Hi, I posted the question in https://stackoverflow.com/questions/53622723/sweetalert2-cancel-timer-timeout,
also created a pen:
https://codepen.io/teoui/pen/MzdzWy

Thank you.

**Comment by gverni** [comment]
Hi @teodorsandu, sweetalert2 doesn't expose any API to cancel the timer. If you want to implement a cancellable timer, it's simpler if you create one yourself in the `onOpen` function and then handle it the way you'd like. You can use the `swal.clickCancel()` to dismiss the swal, but in this case keep in mind that you will have to create your own dismissal reason check since the `swal.DismissReason.timer` will not be set in this case.

**Comment by limonte** [comment]
Hey @teodorsandu and thanks for the effort you've put into your question and codepen!

Will https://github.com/sweetalert2/sweetalert2/pull/1322 help with your use-case?

**Comment by teodorsandu** [comment]
Hi @gverni, I'm not that good as javascript to do this :D - anyway @khrismuc gave me a solution in stackoverflow via [jsfiddle](https://jsfiddle.net/khrismuc/njpL4dsz/) which I explain in a new [codepen](https://codepen.io/teoui/pen/xQNMvL) in the code's comments.

Basically is not setting `timer` altogether and instead calling `swal.close();` by a `setInterval()` function.

Hi @limonte - great library by the way and thanks! - yes, a `.stopTimer()` #1322 method will help!

(should I close this issue?..)

**Comment by limonte** [comment]
Live demo of `Swal.stopTimer()`: https://codepen.io/anon/pen/zMVYKz

**Comment by teodorsandu** [comment]
This is awesome :heartpulse: !! Thank you @limonte !! :pray: 
while I'm at this it crossed my mind that it would be useful the following methods:

.resumeTimer() - resume timer from where it was when .stopTimer() was called
.increaseTimer(x) - increase (postpone) with x ms the time when the modal will close.
.toggleTimer() - toggle between .stopTimer()  and  .resumeTimer() ?

**Comment by limonte** [comment]
@teodorsandu all requested methods were added, here's the live demo: https://shrouded-request.glitch.me/

**Comment by teodorsandu** [comment]
That is simply perfect. Thank you! :) :pray:
