### ISSUE TITLE
when {animation: false, onOpen: () => swal.showLoading()}, confirm button shows for a split-sec

### ISSUE THREAD

**Issue by davalapar** [sweetalert2/sweetalert2#1335]
## Current behavior

OK button shows for a split second.

## Expected behavior

OK button should not for a split second, loader must be what's show instantly.

the flicker gets more noticeable when the users are running on low-tier devices, or in complex apps on mid-tier devices.

## Live demo

@ console of  https://sweetalert2.github.io/ paste and run:

```js
swal({
        text: 'something',
        allowOutsideClick: false,
        allowEscapeKey: false,
         animation: false,
        onOpen: () => swal.showLoading(),
      })
```

Could there be an alternative way to pass loading state within the object, instead of a function to be called once it's opened?

**Comment by limonte** [comment]
`onOpen` is fired **after** a modal is open, try to use `onBeforeOpen` instead:

```js
swal({
  ...
  onBeforeOpen: () => swal.showLoading(),
})
```

**Comment by davalapar** [comment]
That's fucking gangsta, thanks a lot!
