### ISSUE TITLE
Who the fuck accepted Adverts on the doc page for atlassion? ATLASSION....

### ISSUE THREAD

**Issue by antoninadert** [sweetalert2/sweetalert2#1338]
Why just why ? Are you selling the project ? can't wait for spywares to come

**Comment by antoninadert** [comment]
If you need money tell us how much to remove it

**Comment by limonte** [comment]
What's wrong with Atlassian? IMO it's a very respectful company with talented people.

Ads are helping this project to live and evolve. I think that OSS should be paid and ads are now the most stable way to generate some income. We are using [Carbon Ads](https://www.carbonads.net/) which serves only technical ads for developers and designers. I personally find them quite useful and not annoying at all.

You can hide ads for free by using the ad blocker, e.g. https://github.com/gorhill/uBlock

Have a nice day and try not to use the profanity in public conversations :)
