### ISSUE TITLE
Icon round bug

### ISSUE THREAD

**Issue by KeinWeb** [sweetalert2/sweetalert2#1345]
My issue is, that the alerts perfectly load with php echo and script `echo '<script>swal({
        title: "Good job!",
        text: "You clicked the button!",
        icon: "success",
        button: "Aww yiss!",
      });</script>';`

But the icon looks like bugy.

http://prntscr.com/lvddjo

**Comment by limonte** [comment]
Should be round:

![image](https://user-images.githubusercontent.com/6059356/50046439-fddc6d80-00ab-11e9-809c-40f5678df053.png)

Could you inspect `.swal2-success-ring` and reply to us what's blocking `border-radius`?

**Comment by KeinWeb** [comment]
http://prntscr.com/lvebrm look at this the border-radius is missing why it dit it missing?

**Comment by KeinWeb** [comment]
What i mean it is still there but an unown argument block this statement with the border-radius

**Comment by limonte** [comment]
https://www.youtube.com/watch?v=x4q86IjJFag

**Comment by KeinWeb** [comment]
okay i just fix it. Thank you soooo much for you idear with the border-radius. I write behind the icon css classes the tag !important and now it works. closed.
