### ISSUE TITLE
Swal not working in android

### ISSUE THREAD

**Issue by GerardMetal** [sweetalert2/sweetalert2#1357]
(Sorry for my english, i still learning)
## Current behavior
I have a simple Swal function and a Swal confirm function
```
swal({
  type: 'success',
  allowOutsideClick: false,
  title: 'Success!',
  text: 'You are welcome!',
})

swal({
    title: 'Are you sure?',
    text: "This news will be inactive!",
    type: 'warning',
    showCancelButton: true,
    confirmButtonColor: '#3085d6',
    cancelButtonColor: '#d33',
    confirmButtonText: 'Yes, inactive it!'
}).then((result) => {
    if (result.value) {
        $.ajax({
            url: "/news/inactive",
            type: 'POST',
            dataType: 'json',
            data: {_news: _news},
        }).done(function(response) {
            if (response.msg == "Error") {
                // error
            } else {
                // success
            }
        }).fail(function(responseXHR) {
            // fail
        }).always(function() {
            // always
        });
    }
});
```
But none works, they do not open, they do not do anything.
I've tried embedding the links in the documentation, the links are as follows:
```
<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.js"></script>
<script src="https://cdn.jsdelivr.net/es6-promise/latest/es6-promise.auto.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
```
## Environment (of the bug or issue)
Smartphone: Xiaomi Mi A2 lite (example).
Browsers: Google Chrome and Opera Touch.
System: Android 8.1

**Comment by gverni** [comment]
Hi @GerardMetal did you include the link to the sweetalert code as well? Does the same page work on a desktop computer browser?

**Comment by zenflow** [comment]
I can see a syntax error here:

```js
        }).done(function(response) {
            if (response.msg == "Error") {
                // error
            } else {
                // success
        }).fail(function(responseXHR) {
```

please test and debug on desktop before opening issues saying it doesn't work on some mobile browser

**Comment by GerardMetal** [comment]
Hi @gverni, yes, i did. It working on desktop computer browser (browsers used: Google Chrome, Opera, and Safari).

Hi @zenflow i'm sorry, i edited the code on this page, but the code in the project is correct.

In the desktop computer browser does works perfectly.

**Comment by gverni** [comment]
Hi @GerardMetal could you share the full code using glitch (see [here](https://github.com/sweetalert2/sweetalert2/wiki/How-to-provide-live-example-for-issue) on how to use it) so we can try to debug what's going on?

**Comment by gverni** [comment]
Hi @GerardMetal I _remixed_ your code for you on: 

https://ossified-tarp.glitch.me/

This is what I see on my Android phone using Google Chrome 71.0.xxx:

![screenshot_20190107-131029](https://user-images.githubusercontent.com/17089396/50770261-95357a80-127e-11e9-955f-8be37520383f.png)

So it looks like everything is working....
