### ISSUE TITLE
Drop withNoNewKeyword in coming major release

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2#1368]
The coming major release gives us the opportunity to drop this complexity and source of issue #1281 (so users can import uncompiled code from the `src/` directory again).

This would mean a breaking change as users would need to change their usage from `Swal({...options})` to `new Swal({...options})`, or if nothing is done with the result, and the [eslint no-new rule](https://eslint.org/docs/rules/no-new) is in effect, `Swal.fire({...options})`. I think for the sake of simplicity it might be best to only use the latter `Swal.fire()` in documentation, tests, issue descriptions, etc.

**Comment by zenflow** [comment]
Sorry, I've been really busy with work and personal life, so I wouldn't be able to handle this myself right away.

**Comment by limonte** [comment]
Will do :+1:

**Comment by gverni** [comment]
@limonte let me know if i can help with that. It looks beyond my skills... but, as usual, I’m happy to learn!

**Comment by limonte** [comment]
@gverni thank you! I will assign you to some tasks for the upcoming major!

**Comment by limonte** [comment]
:tada: This has been shipped in version 8.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/sweetalert2)
- [GitHub release](https://github.com/sweetalert2/sweetalert2/releases/tag/v8.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
