### ISSUE TITLE
mixin not work as setDefaults work before

### ISSUE THREAD

**Issue by circuitmamu** [sweetalert2/sweetalert2#1380]
`var MY_Custom = function() {
	
	var _componentSweetAlert = function() {
        if (typeof swal == 'undefined') {
            console.warn('Warning - sweetalert.min.js is not loaded.');
            return;
        }
        // Defaults
        var setCustomDefaults = function() {
            return const swalWithBootstrapButtons = swal.mixin({
                buttonsStyling: false,
                confirmButtonClass: 'btn btn-primary',
                cancelButtonClass: 'btn btn-danger'
            });
        };
        setCustomDefaults();
    };
	
	return {
		initBeforeLoad: function() {
            _componentSweetAlert();
        }
	}
}();

document.addEventListener('DOMContentLoaded', function() {
    MY_Custom.initBeforeLoad();
});`

I use this code a js file and attach to html at footer or header but when I use mixin inside any class with variable return of instance as default mixin it can't be re use and have to define everytime

If any answer or solution please reply fast. I use swal as total alternative like if I go for delete record i show for confirmation after that ajax with loading and then either delete complete swal or something error swal

**Comment by limonte** [comment]
https://stackoverflow.com/questions/ask
