### ISSUE TITLE
Bug showing alert

### ISSUE THREAD

**Issue by EfraimLA** [sweetalert2/sweetalert2#1381]
![image](https://user-images.githubusercontent.com/46459026/51083167-15266f00-16db-11e9-919f-1bd0ee8e910b.png)

Showing an alert in my login i lost my designs of the page, it shows but i can't see the design, and when i close it returns normally, does not reload and nothing thus but only cannot see them showing the alert

**Comment by limonte** [comment]
Welcome to GitHub, @EfraimLA 

I will close this issue without the answer because it's impossible to help with the information you've provided.

Please create a new one and follow the **bug report template**.
