### ISSUE TITLE
Chaining modals (queue) button text progression

### ISSUE THREAD

**Issue by MiXT4PE** [sweetalert2/sweetalert2#1382]
## New feature motivation

If there is something _next_ it makes sense to have a next-button. If the modal closes and the information gets processed, it doesn't. That's why I propose the following:

## New feature description 

Instead of a single `confirmButtonText` string you can also give an array with as many elements as there are `progressSteps` so every step gets the appropriate button.

## Example
```
Swal.mixin({
  input: 'text',
  confirmButtonText: ['Next &rarr;', 'Next &rarr;', 'Finish'],        <-----------
  showCancelButton: true,
  progressSteps: ['1', '2', '3']
}).queue([
  {
    title: 'Question 1',
    text: 'Chaining swal2 modals is easy'
  },
  'Question 2',
  'Question 3'
]).then((result) => {})
```

**Comment by limonte** [comment]
Thank for the feature request, but I personally don't like it too much. Imagine 5 steps queue:

```js
confirmButtonText: ['Next &rarr;', 'Next &rarr;', 'Next &rarr;', 'Next &rarr;', 'Finish'],        <-----------
progressSteps: ['1', '2', '3', '4', '5']
```

This code smells, it's hardly maintainable and it violates the DRY principle as `'Next &rarr;', ` is copy-pasted 4 times.

Would this be much better:

```js
Swal.mixin({
  input: 'text',
  confirmButtonText: 'Next &rarr;',
  progressSteps: ['1', '2', '3']
}).queue([
  {
    title: 'Question 1',
    text: 'Chaining swal2 modals is easy'
  },
  'Question 2',
  {
    title: 'Question 3'
    confirmButtonText: 'Finish'
  }
]).then((result) => {})
```

No copy-paste and easy to change/maintain (`progressSteps` could contain 3 or 30 steps, it doesn't matter).

**Comment by MiXT4PE** [comment]
Oh I didn't know you could do it this way. Thanks!
