### ISSUE TITLE
3M+ downloads, the hottest post on r/webdev, the 8th most popular JS repo on GitHub 🎉 🎉 🎉

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1388]
> The previous part of SweetAlert2's success story: #906 

Last weekend the [new major release](https://github.com/sweetalert2/sweetalert2/releases/tag/v8.0.0) of SweetAlert2 was shipped 🎉  and I decided to post about it on r/webdev: https://www.reddit.com/r/webdev/comments/aiobj0/sweetalert2_a_beautiful_responsive_highly/

The post ended up being the hottest in r/webdev and that brought a lot of new eyes on the project:

<img src="https://user-images.githubusercontent.com/6059356/51596382-84813780-1f01-11e9-8c23-d3ce53bb6ab0.png" width="450">

---

I wanted to thank @zenflow who took the most significant part in making the fundamental OO changes to the package. We had some disagreements about the release, but in the end, I extremely grateful to him and I call him "SweetAlert2 architect" in public discussions. He's truly the most skillful person I was co-working with in OSS.

Also, we recently got the new collaborator @gverni and he showed himself as the extremely fast-learner and his contributions to the new release were significant. Can't thank you enough @gverni for your participation in discussions, being pro-active in the package development and being kind and supportive to people on GitHub and StackOverflow.

I sent to both of you @zenflow and @gverni PayPal donations, feel good about yourself, you guys rock!

---

We are getting closer to 10k stars on GitHub, [5M npm downloads](https://limonte.github.io/total-npm-downloads/?package=sweetalert2) and being [TOP 20 jsdelivr package](https://jsdelivr.com/package/npm/sweetalert2). Currently we are here:

![image](https://user-images.githubusercontent.com/6059356/51594864-0d966f80-1efe-11e9-9795-91bf5bcf5331.png)

![image](https://user-images.githubusercontent.com/6059356/51594875-18510480-1efe-11e9-8165-4cc810ed24cc.png)

![image](https://user-images.githubusercontent.com/6059356/51594897-26068a00-1efe-11e9-9b87-640105865bc8.png)

---

Great job everyone! 🍻 🍻 🍻 

I wish a pleasant day to everybody who is creating or using SweetAlert2 in production. We care about avoiding any breaking changes, so developers can feel safe when running `yarn upgrade sweetalert2`.

**Comment by limonte** [comment]
One more today's achievement, SweetAlert2 is the WhiteSource’s Open Source Project of the Month: https://resources.whitesourcesoftware.com/blog-whitesource/sweetalert2-open-source-project-of-the-month-january-2019 🎉

**Comment by gverni** [comment]
Congratulations @limonte! This is a testimony to your skills, dedication and hard work on this project. I feel really privileged to have been accepted as collaborator of this amazing project and to have the opportunity to work with you, @zenflow and all the other collaborators. Looking forward to more successes in the future... 

p.s. Turbo Pascal.... good old days of getting excited for being able to draw a circle on a CRT monitor :smile:

**Comment by toverux** [comment]
This is quite impressive. Seems like sweetalert answers a real use case :smile: And people like it! 
Congrats to the team! And thanks to @gverni and @zenflow, I admire your commitment!

**Comment by zenflow** [comment]
Congratulations everyone! We can be truly proud of our accomplishments!
