### ISSUE TITLE
Google Maps disappears behind modal

### ISSUE THREAD

**Issue by produktive** [sweetalert2/sweetalert2#1389]
When I display a Swal over my Google Maps app the map disappears behind it. It reappears when the modal is closed. Shouldn't the map still be visible in the background? Pics attached. I've tried changing the target to the maps container but the result was the same.
![screen shot 2019-01-23 at 9 43 12 pm](https://user-images.githubusercontent.com/21110476/51651359-90004d00-1f59-11e9-922c-0ccfc51e062f.png)
![screen shot 2019-01-23 at 9 43 31 pm](https://user-images.githubusercontent.com/21110476/51651367-968ec480-1f59-11e9-8a38-daad568fd1f6.png)

**Comment by limonte** [comment]
Hi @produktive

Give a try for `heightAuto: false`.

If that doesn't work, please create a new issue and follow the **bug report template**.

**Comment by produktive** [comment]
Excellent, thank you for the tip.
