### ISSUE TITLE
Swal 8.x.x doesn't show correctly (styles are missing)

### ISSUE THREAD

**Issue by obrassard** [sweetalert2/sweetalert2#1390]
## Current behavior
Hi !  We're trying to fire a swal in an angular app.  
I've just downloaded the latest version of sweetalert2 (8.0.1) from npm and imported it in my angular componenent (angular 6 with typescript). Then i tried to fire the swal in `ngOnInit()` with a code snippet taken from sweetalert2 website, however, the swal doesnt popup, swal's html elements are rather added to the DOM, without being styled : 

![image](https://user-images.githubusercontent.com/17227551/51770389-973b6e00-20b3-11e9-8d41-a81dde2e2210.png)

**We are using the standard sweetalert2 library, not ngx-sweetalert2, and it seems to be a problem with version 8 only, because rolling back to version 7.33.1 fix this issue.**

Note that, I've not tested v8.0.1 without using angular or using ngx-sweetalert2.

## Expected behavior

The sweetalert should appear normaly, as it's demonstrated on sweetalert's website.

## Live demo

Here's the code of my component : 
```ts
import { Component, OnInit } from '@angular/core';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  ngOnInit(): void {
    Swal.fire(
      'Good job!',
      'You clicked the button!',
      'success'
    )
  }
}

```

**Comment by obrassard** [comment]
Hello @limonte ! 
The thing is that we're  not using ngx-sweetalert2, only sweetalert2 :)

**Comment by limonte** [comment]
Oops, I misread your issue-report, apologies!

Is is possible to provide a live demo of this issue? (e.g. using https://stackblitz.com/)

**Comment by obrassard** [comment]
Hello, I tried to reproduce the issue on stackblitz this morning, but the sweetalert shows up as expected.. It's strange taught because, when I download the exact same project from stackblitz and run it locally on my computer, the problem persist... 


Yesterday, I tried in 2 different angular project on windows, and today in a fresh new angular project on my macbook and the problem is always present. So I have difficulty to understand what make it work on stackblitz..

Heres the stackblitz project : https://stackblitz.com/edit/angular-z3wex8?file=src%2Fapp%2Fapp.component.ts 

Maybe you could try to download it + the node modules, and check if you face this problem locally too..

Here's a screenshot form the stackblitz project : 

<img width="1280" alt="capture d ecran le 2019-01-26 a 10 11 37" src="https://user-images.githubusercontent.com/17227551/51789039-d076eb00-2152-11e9-85ef-1a00589e96ed.png">

And the same project, executed locally with `ng serve`: 

<img width="338" alt="capture d ecran le 2019-01-26 a 10 12 33" src="https://user-images.githubusercontent.com/17227551/51789135-fb157380-2153-11e9-8d75-3c35fdc27c4e.png">

Since it work on stackblitz, this might be a problem with the dependencies ?
However, I have no error in the console.

Have a nice day !

**Comment by limonte** [comment]
Thanks for the live demo @obrassard 

> Maybe you could try to download it + the node modules, and check if you face this problem locally too..

Yup, facing it locally too. 

This helped:

```diff
-import Swal from 'sweetalert2';
+import Swal from 'sweetalert2/dist/sweetalert2.all.js';
```

Which leads me to conclusion that angular bundling process is for some reason taking the [module field from package.json](https://github.com/sweetalert2/sweetalert2/blob/master/package.json#L8) instead of [main field](https://github.com/sweetalert2/sweetalert2/blob/master/package.json#L7).

We made changes in package.json https://github.com/sweetalert2/sweetalert2/pull/1378 cc @gverni 

I have no idea why angular prefers `module` over `main`. Maybe @toverux have any clue about this behavior?

**Comment by gverni** [comment]
oops @limonte our comments crossed 😄

**Comment by limonte** [comment]
I just upgraded all alngualr dev-deps to latest and the issue is still there.

> I have no idea why Angular uses module over main

This is the problem, please report it to the according Angular repository.

As a workaround you can either

```js
import Swal from 'sweetalert2/dist/sweetalert2.all.js';
```

Or import styles separately:

```js
import Swal from 'sweetalert2'
import 'sweetalert2/src/sweetalert2.scss'
```

**Comment by limonte** [comment]
https://github.com/sweetalert2/sweetalert2-webpack-demo has the same issue, reopening.

Looks like the a webpack issue/feature.

**Comment by limonte** [comment]
It's a feature :/ https://github.com/webpack/webpack/issues/6796

**Comment by limonte** [comment]
Here's how I solved it for `sweetalert2-webpack-demo`:

`webpack.config.babel.js`:

```js
  resolve: {
    mainFields: [
      'main',
      'module'
    ]
  },
```

**Comment by gverni** [comment]
> Here's how I solved it for sweetalert2-webpack-demo

How did you figure this out @limonte??? You need to tell me your secret 😃 

BTW, for the record, I tried setting manually `mainFields` in `./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js` as: 

```
            mainFields: [
                ...(wco.supportES2015 ? ['es2015'] : []),
                'browser', 'main', 'module'
            ],
```
And the project shared by @obrassard works locally as well. I'm not sure this is the best to configure `build-angular` (and that's one of the main reason why I don't like frameworks) but that may explains why the project works fine on stackblitz.  Hope it helps...

**Comment by codebycliff** [comment]
I'm experiencing this issue as well with just a basic Webpack setup. Specifying the `mainFields` fixes the issue for me. Is that the desired work-around for now?

**Comment by limonte** [comment]
> Is that the desired work-around for now?

Good question. It's ugly and I don't like it to be honest. It's unexpected that webpack prefers `module` over `main`.

Does anyone maybe have any idea how to make ES module (`src/sweetalert2.js`) automatically include styles in case of webpack processing?

**Comment by limonte** [comment]
I am going to remove the `module` field from `package.json`, so the webpack workaround suggested above won't be needed: https://github.com/sweetalert2/sweetalert2/pull/1392

**Comment by limonte** [comment]
Thanks everybody for reporting and investigating

The issue should be fixed in the latest release (8.0.2), no webpack workarounds needed.

Apologies about this inconvenience!

**Comment by christiand0r** [comment]
Hello! I am using SweetAlert v11.4.4 with Vite and React on the latest version and the styles are not added to the header. I had to use import as Limote suggests and it worked

`import Swal from 'sweetalert2/dist/sweetalert2.all.js';`

**Comment by christiand0r** [comment]
> Hello! I am using SweetAlert v11.4.4 with Vite and React on the latest version and the styles are not added to the header. I had to use import as Limote suggests and it worked
> 
> `import Swal from 'sweetalert2/dist/sweetalert2.all.js';`

I uploaded the code here: https://github.com/christiand0r/redux-crud using the normal import

**Comment by limonte** [comment]
> Hello! I am using SweetAlert v11.4.4 with Vite and React on the latest version and the styles are not added to the header. I had to use import as Limote suggests and it worked
> 
> `import Swal from 'sweetalert2/dist/sweetalert2.all.js';`

This would work, but here's a slightly better solution:

```js
import Swal from 'sweetalert2'
import 'sweetalert2/dist/sweetalert2.css'
```

**Comment by developer-junaid** [comment]
> 

Thanks Man ! It works like a charm !
