### ISSUE TITLE
Dropdown wrongly appears in alert when there are jQuery calls present in surrounding code

### ISSUE THREAD

**Issue by rsryanstephen** [sweetalert2/sweetalert2#1406]
## Current behavior
```javascript
swal.fire(
                'Date range updated',
                'Date range has been updated',
                'success'
              );
```

produces:

![image](https://user-images.githubusercontent.com/30828027/52401268-f2189080-2ac9-11e9-9874-75322657c90f.png)

## Expected behavior
No dropdown apeearing

## Live demo

---

Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:
- https://www.paypal.me/limonte

**Comment by limonte** [comment]
This issue is poorly reported, therefore I'm closing it. If you want help (our effort), make sure you put enough of your effort in reporting an issue.

Report another one, follow the issue template and add live demo as described in the issue template.
