### ISSUE TITLE
[Dynamic Queues] close() doesn't show next step

### ISSUE THREAD

**Issue by Herz3h** [sweetalert2/sweetalert2#1407]
## Current behavior

I'm on version 7.18 (can't really update to 8 with the all the breaking changes)
Using swal.close() with a dynamic queue doesn't bring next step. 

## Expected behavior

Upon clicking next button, the next step should show up. Instead I have to call clickConfirm().

## Working example

https://jsfiddle.net/oyx9afwt/1/

> Uncomment the clickConfirm() to get the expected behavior...This took me 3 hours to figure out, trying different things :/

Thanks.

**Comment by limonte** [comment]
> I'm on version 7.18 (can't really update to 8 with the all the breaking changes)

What stops you from upgrading to `7.33.1`?

> Using swal.close() with a dynamic queue doesn't bring next step.

It works like expected, the `close()` method will **dismiss** the current popup, and therefore the next one will not be shown.

> Uncomment the clickConfirm() to get the expected behavior...

Yup, `clickConfirm()` is the right way if you want to get to the next step programmatically.
