### ISSUE TITLE
Backdrop not rendering correctly in Chrome

### ISSUE THREAD

**Issue by aliogaili** [sweetalert2/sweetalert2#1408]
The backdrop is not being rendered correctly in chrome and sometimes it shows some flicker. That has recently been noticed in the latest version of chrome. The issue can be observed on the Sweetalert2 website, please see attached image.

Chrome version: Version 73.0.3683.27 (Official Build) beta (64-bit)

<img width="1440" alt="screen shot 2019-02-10 at 1 58 27 am" src="https://user-images.githubusercontent.com/1675307/52526788-e69ab480-2cd7-11e9-8c30-8db46ef07f98.png">

**Comment by limonte** [comment]
Can't reproduce (Windows 10)

Version 73.0.3683.27 (Official Build) beta (64-bit)

**Comment by aliogaili** [comment]
I reinstalled chrome and it's back to normal! sorry for the false alarm.
