### ISSUE TITLE
modal adding unwanted padding-right on body

### ISSUE THREAD

**Issue by tomholub** [sweetalert2/sweetalert2#1412]
Thanks for otherwise awesome work!

## Current behavior

Modal is adding a `padding-right: 15px` style on `body` tag. I understand this is to compensate for possible scrollbars, but in our case it messes with our design. Our body elements are meant to stretch all the way to the right edge, and the body padding makes it look broken.

Happens here:
```js
  if (document.body.scrollHeight > window.innerHeight) {
    // add padding so the content doesn't shift after removal of scrollbar
    states.previousBodyPadding = parseInt(window.getComputedStyle(document.body).getPropertyValue('padding-right'));
    document.body.style.paddingRight = states.previousBodyPadding + measureScrollbar() + 'px';
  }
```

## Expected behavior

Don't change padding of html body.

(Alternatively, allow me to turn this feature off through config)

## Demo

https://tin-bar.glitch.me/

**Comment by limonte** [comment]
Thank you for the perfectly made feature request, @tomholub!

We will add the config option for disabling this feature. Do you maybe have a good name for that config on your mind?

**Comment by tomholub** [comment]
`bodyScrollbarPadding` (default true)

It's a horrible name but at least I can find it in the docs when I search for `body`, `padding` and `scrollbar`.

`fixBodyScrollbarPadding`
`compensateBodyScrollbar`
`scrollbarPadding`

They all sound about equally bad.

Thanks!

**Comment by tomholub** [comment]
Or more general,

`adjustBodyStyle` with default true. Later other possible style updates could be lumped under that flag. If I set it to false, I know my `<body>` tag would stay the same.

**Comment by gverni** [comment]
How about a _negative_ such as `disableBodyStyleAdjustment`, with the default value set to `false`?

**Comment by tomholub** [comment]
Either is good

**Comment by limonte** [comment]
> How about a _negative_ such as `disableBodyStyleAdjustment`, with the default value set to `false`?

I'm more in favor of positive with default `true` for two reasons:

- the name is 7 chars shorter (no need in `disable` prefix)
- double negatives are more difficult to understand for human beings

`scrollbarPadding` (default `true`) is the best option so far IMO, it's short and search-friendly.

**Comment by tomholub** [comment]
Thank you!

Would you take donations in cryptocurrency? Was trying to donate $150 over PayPal but it's giving us trouble. BTC or ETH would be a lot easier.

**Comment by limonte** [comment]
Thank you @tomholub for your appreciation of our work! I guess it's time for me to step into the bright future with cryptocurrencies. I'm planning to spend your generous donation on https://gitcoin.co whenever we will need additional attention to some feature(s) or issue(s) from the community.

Here are available wallets:

- Bitcoin: `12BxefvPMtHePgfPRDL1SaZYSG4GwQmWoP`
- Ether: `0x36e2b10666e2c0dc343901895ba3697b5d3214d1`
- Bitcoin Cash: `qqxs402qszgwuue00gwxw996lzhpa8up2unqm0y46g`
- Stellar: `GBRS5KGFJO4OBUGW3TRQBIVXTM5YDS53DOSHGA3LKVE2YXKVKNVDONBP`

Thank you once again for requesting the way to donate in cryptocurrencies, I will also update the README with the information above.

**Comment by tomholub** [comment]
Noted, will do!
