### ISSUE TITLE
Unable to scroll to the top of the modal when using a long text + position: 'bottom-end'

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1416]
Hi guys,

I still have the issue if I'm using any bottom positioning. 

Tested with the last release (8.2.0) on different browsers (like FF, Chrome, Safari): 
https://jsfiddle.net/1sLmb7j2/

_Originally posted by @SchoppAx in https://github.com/sweetalert2/sweetalert2/issues/679#issuecomment-464709016_

**Comment by SchoppAx** [comment]
A fix could be:

``.swal2-container.swal2-bottom-end, .swal2-container.swal2-bottom-right {
    align-items: flex-start;
    justify-content: flex-end;
}

.swal2-container.swal2-bottom-end > :first-child {
    margin-top: auto;
}``

**Comment by limonte** [comment]
Thank you for the suggested solution @SchoppAx! Would you mind to create a PR with it?

**Comment by SchoppAx** [comment]
Of course. Ii will create it later :-)

**Comment by limonte** [comment]
Thank you, here's the contributing guide: https://github.com/sweetalert2/sweetalert2#contributing
