### ISSUE TITLE
Cannot add swal2 css class in the html parameter

### ISSUE THREAD

**Issue by ChristianCruiz** [sweetalert2/sweetalert2#1419]
## Current behavior
I tried to fire a swal using the html paramter because i needed more than 2 buttons in the floating window.

I wanted the window to look exactly like a 2 buttons swal without html,
so in the html parameters i put three buttons and then placed the class of one of the buttons to be "swal2-cancel" and "swal2-confirm" for the two other buttons
and unfortunately whenever i try to fire the swal i get an error:

Failed to execute 'InsertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Is there any other way to inject the swal2 css classes into the html parameter ?

**Comment by limonte** [comment]
Welcome to GitHub, @ChristianCruiz 

Would you mind sharing the code you're trying to use? Or even better, provide a glitch, here's how: https://github.com/sweetalert2/sweetalert2/wiki/How-to-provide-live-example-for-issue

**Comment by ChristianCruiz** [comment]
> Welcome to GitHub, @ChristianCruiz
> 
> Would you mind sharing the code you're trying to use? Or even better, provide a glitch, here's how: https://github.com/sweetalert2/sweetalert2/wiki/How-to-provide-live-example-for-issue

ok i added 
here is the project and the output link:
output : https://boiling-output.glitch.me
code : https://glitch.com/edit/#!/boiling-output

pay attention that the glitch appears only when the classes "swal2-cancel" and "swal2-confirm" are added to the buttons

**Comment by limonte** [comment]
Thanks @ChristianCruiz 

Looks like a bug

```js
Swal.fire({
  html: '<span class="swal2-cancel"></span>'
})
```

**Comment by ChristianCruiz** [comment]
Thank you very much ! 
Helped me alot
