### ISSUE TITLE
close icon not showing correctly

### ISSUE THREAD

**Issue by simon1tan** [sweetalert2/sweetalert2#1427]
I'm having the weirdest problem here. Code is simple:

    <!DOCTYPE html>
    <html lang=en>
    <script src="../sweetalert2.all.min.js"></script>
    <body></body>
    </html>
    <script>
	Swal.fire({
		text: 'Save is disabled in Demo Mode',
		position: 'top-end',
		type: 'warning',
		showConfirmButton: false,
		showCloseButton: true,
		timer: 30000
	})
    </script>

This code shows the letter A with a tilde on top instead of an x icon on the top right corner. When I use this instead:
  
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>

the x icon shows up fine. I downloaded the file straight from the link so should be same file yet the close icon is different. I've never seen this happen before. Any idea what is causing this?

**Comment by gverni** [comment]
Hi @simon1tan i remember seeing that once, but I don't remember what the problem was. To help us debugging can you: 

* Check the browser console for any error
* Take a screenshot of the `button` element from dev console (to show it, you can right click on the close button and  select "Inspect element")
* Provide browser (with version) used in your test 
* Also, how are you serving your page? Is it on your own server? Any chance you can share the url? 

Finally, you may want to refactor your HTML page. The `script` that fire the swal should be inside the `body` and the `script` tag that include swal should be in the `head` tag. I don't think this will solve the issue, but better be compliant.

**Comment by simon1tan** [comment]
Chrome Version 72.0.3626.109  (it's updating, will update this if problem resolves)
No errors in the log. 
Serving via file:// and http://localhost with Apache on Windows. Same issue.
![swal-close2](https://user-images.githubusercontent.com/1250858/53378112-58e6d800-3919-11e9-8194-813d26167ce6.png)

The working version shows:
`    <button type="button" class="swal2-close" aria-label="Close this dialog" style="display: flex;">×</button>`

The computed CSS are identical so not CSS. Somewhere there is javascript code that creates the button.

**Comment by gverni** [comment]
Thanks @simon1tan. The `x` is set in this line:

https://github.com/sweetalert2/sweetalert2/blob/5be77b65ecee1bebe78df01e7a2de01d8bb612f0/src/utils/dom/init.js#L32

As I said, I remember seeing this one in one of my test, but i cannot recall what was the problem. Can you confirm that you are not importing any other script/framework?

**Comment by gverni** [comment]
Hi @simon1tan i found the problem. The `x` in the is encoded in UTF-8. If you convert the UTF-8 ` x` into ANSI, it becomes ....  `Ã—`. You need to make sure that when you serve the sweetalert script, the content type is set to `charset=utf-8`.

**Comment by gverni** [comment]
Alternatively, you can set the encoding using the script tag: 

```html
<script src="sweetalert2.all.min.js" charset="UTF-8"></script>
```

**Comment by limonte** [comment]
Hm, this is interesting. I would not assume that some users will use something else from UTF-8, but since it's the case sometimes, should we replace `×` with `&times;`? @gverni wdyt?

**Comment by gverni** [comment]
> should we replace `×` with `&times;`?

Yes, I think so. It's definitely adding robustness and improve accessibility...

**Comment by limonte** [comment]
> Yes, I think so. It's definitely adding robustness and improve accessibility...

Agree, I'll take care of creating a PR 👍
