### ISSUE TITLE
Drop down list behind buttons

### ISSUE THREAD

**Issue by WillGoldstein** [sweetalert2/sweetalert2#1433]
Hi,

I'm seeing this css issue:

![image](https://user-images.githubusercontent.com/20759342/53507489-0414a000-3a86-11e9-9400-030c4c63b3a7.png)

Where the buttons are in front of the drop down list which is a select object using selectize.js.

Has anyone seen this before? It's probably a css conflict but I wasn't sure if it's been seen or solved already by someone else?

**Comment by limonte** [comment]
You probably need to apply `z-index` to selectize dropdown. For more help please follow the issue template.

**Comment by hn-tma** [comment]
I am having the same issue with SweetAlert2 and Bootstrap 5.  Setting z-index for the dropdown menu or buttons doesn't work.  How did you get it fixed?
