### ISSUE TITLE
Confirm and Cancel buttons are stacking

### ISSUE THREAD

**Issue by hajududat** [sweetalert2/sweetalert2#1437]
We have a cancel button that displays the alert. When the alert first displays, the Confirm and Cancel buttons appear stacked. When the alert is canceled and the page is refreshed, and then the cancel button is clicked to display the alert, the Confirm and Cancel buttons will now appear inline. It doesn't matter if the reverseButtons is set to true or false, either way it stacks.

Stacked:
<img width="506" alt="swal-buttons-stacked" src="https://user-images.githubusercontent.com/9950358/53846237-27ee4f00-3f7a-11e9-97bf-5953650723cd.png">

Inline:
<img width="499" alt="swal-buttons-inline" src="https://user-images.githubusercontent.com/9950358/53846243-2de43000-3f7a-11e9-9245-73f138a100cb.png">

Any ideas why?

**Comment by limonte** [comment]
There's some custom styling applied to those confirmation dialogs, it's quite impossible to answer your question without any code.

Please follow the issue template and provide the live demo.

**Comment by hajududat** [comment]
Unfortunately no live demo available as it's not public facing. The only styling is CSS using the ButtonClass feature for color minor padding. So this is an issue that should not be closed.

**Comment by gverni** [comment]
@hajududat if the only styling you apply is the `confirmButtonClass` and `cancelButtonClass` then it should be easy for your to re-create a live example (e.g. remixing https://sweetalert2.glitch.me/). The issue was definitely never seen with the default configuration and if you need our help debugging, we need a live example to wok on. Hope you understand.

**Comment by hajududat** [comment]
@gverni I edited my answer above. Even without styling it does this.

**Comment by hajududat** [comment]
@gverni Since the app is in development, it will only load while logged into the client's VPN. So I don't know how I can create a live example due to security.

**Comment by gverni** [comment]
@hajududat can you not just extract the relevant code from the page? We don't need the full page, just the simplest version of your page that shows the issue

**Comment by hajududat** [comment]
@gverni First, my apologies for coming off irritable. I've been fighting this and do not understand why it's happening. I'm not sure how to extract the code on an Angular app, or how to get you a demo to recreate. My process for this project was to create all the HTML and CSS files that were then handed off to a dev team building the Angular app. My role now is going in and fixing mostly styling bugs. This is one bug that I just don't know how to correct.

**Comment by limonte** [comment]
> This is one bug that I just don't know how to correct.

You might want to learn how to use Google Chrome dev tools: https://www.youtube.com/watch?v=x4q86IjJFag

**Comment by hajududat** [comment]
I do. flex-direction: column !important; was getting adding to .swal2-actions on first load. After a page refresh, it was no longer there.

**Comment by hajududat** [comment]
flex-direction: column !important; was getting adding to .swal2-actions on first load. After a page refresh, it was no longer there.

**Comment by gverni** [comment]
Thanks @hajududat for the follow-up. Interesting finding. 

>  After a page refresh, it was no longer there.

I'm not sure I understand that. If you reload the page the initial configuration should always be the same, unless you are keeping a kind of history.

**Comment by hajududat** [comment]
When visiting the page the first time and the button was click to display the alert, the flex-direction CSS would appear in the Elements tab as being applied to .swal2-actions.

But when I would just refresh the page and click the button again, the alert would display but the flex-direction CSS would not appear in the Elements tab as being applied to .swal2-actions.
