### ISSUE TITLE
CDNJS version outdated

### ISSUE THREAD

**Issue by pedro-lb** [sweetalert2/sweetalert2#1442]
Hello,

It seems that the CDNJS version is outdated. The latest version there is 7.33.1, while the actual version here is 8.3.0. This seems to be a problem at CDNJS's side, but I'm  not sure.

Link: https://cdnjs.com/libraries/limonte-sweetalert2.

**Comment by gverni** [comment]
Hi @pedro-lb the official CDN is https://cdn.jsdelivr.net/npm/sweetalert2

**Comment by limonte** [comment]
I would **strongly recommend** using the specific major version by adding `@8`: https://cdn.jsdelivr.net/npm/sweetalert2@8

This will save you from unexpected breaking changes when a new major will be released.

**Comment by ciaran036** [comment]
I'm a little confused. 
Microsoft's latest tooling for managing client-side packages includes only 3 providers for packages, and one of them is from cdnjs.com. The 'jsdelivr' provider mentioned above isn't one of those providers, effectively leaving me stuck with whatever is available on cdnjs. Any idea what the cdnjs provider isn't up to date? Thanks.

**Comment by pedro-lb** [comment]
Hey @ciaran036 , you can actually use other providers than cdnjs. I'm currently using ASP.NET Core 2.2 and there are these providers available (on Visual Studio 2017 / 2019, right-click Add > Client Side Library):

![image](https://user-images.githubusercontent.com/22061051/54387188-82be2f80-4679-11e9-9f63-0497dcdafb2a.png)

However, in order to use other providers such as jsdelivr, you have to first select which package you want to add, press enter, type '@' after the name and then select the version:

![image](https://user-images.githubusercontent.com/22061051/54387246-a1bcc180-4679-11e9-861e-f32dc3a25fe5.png)

And thus you can install SweetAlert2 using jsdelivr.

Cheers!
