### ISSUE TITLE
Typescript: Cannot invoke an expression whose type lacks a call signature. Type 'typeof Swal' has no compatible call signatures

### ISSUE THREAD

**Issue by francovp** [sweetalert2/sweetalert2#1445]
## Current behavior

I'm using sweetalert2 with Angular and have this error when I try to compile something like `swal("Some text")`on Angular 7.2.9:

```
error TS2349: Cannot invoke an expression whose type lacks a call signature. 
Type 'typeof Swal' has no compatible call signatures.
```
before in Angular 6.0.3 it was working right.

I'm importing it like this:

`import swal from "sweetalert2";`

## Expected behavior

It should compile.

**Comment by limonte** [comment]
Could you please specify the version of `sweetalert2` you're using on that project?

**Comment by gverni** [comment]
Hi @francovp the API to call swal changed recently in version 8.x. You now need to use `swal.fire()`. If you are using latest version, then can you try with that?

**Comment by francovp** [comment]
Oh ok, right, sorry. I forgot that I also update sweetalert2 package to `8.3.0`, so Swal.fire() should do the trick :)

**Comment by limonte** [comment]
Never upgrade dependencies to new major versions without checking the release notes :)

https://github.com/sweetalert2/sweetalert2/releases/v8.0.0

**Comment by francovp** [comment]
Thanks for the advice :)

**Comment by sanket0685** [comment]
> ## Current behavior
> I'm using sweetalert2 with Angular and have this error when I try to compile something like `swal("Some text")`on Angular 7.2.9:
> 
> ```
> error TS2349: Cannot invoke an expression whose type lacks a call signature. 
> Type 'typeof Swal' has no compatible call signatures.
> ```
> 
> before in Angular 6.0.3 it was working right.
> 
> I'm importing it like this:
> 
> `import swal from "sweetalert2";`
> 
> ## Expected behavior
> It should compile.

Could you let me know the resolution steps. I am having the same issue.

**Comment by limonte** [comment]
The resolution step is reading comments above :) In particular, [this one](https://github.com/sweetalert2/sweetalert2/issues/1445#issuecomment-472814774) :)

**Comment by tanmay0685** [comment]
> The resolution step is reading comments above :) In particular, [this one](https://github.com/sweetalert2/sweetalert2/issues/1445#issuecomment-472814774) :)
> 
> `swal("Some text") -> Swal.fire("Some text")`

Which version of sweetalert2  you have installed, as fire method is not populating for me in 8.3 version. May i have to downgrade it from 8.x to 7.x. Please let me know the npm command for it. I am using this command.   npm i sweetalert2
