### ISSUE TITLE
Reach the maintainability rate A 🚀

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1493]
The current maintainability rate is C:

![image](https://user-images.githubusercontent.com/6059356/55003282-c7828880-4fe0-11e9-9193-4e400d5fa8ae.png)

https://codeclimate.com/github/sweetalert2/sweetalert2

I created all issues for refactoring: https://github.com/sweetalert2/sweetalert2/issues?q=is%3Aopen+is%3Aissue+label%3Acodeclimate

The community effort is very welcome! This is a quite nice exercise in refactoring code :muscle: 

Some examples of already fixed similar issues: https://github.com/sweetalert2/sweetalert2/issues?q=is%3Aissue+is%3Aclosed+label%3Acodeclimate

:warning: Assign yourself or leave the comment when you decide to work on any of those issues.

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/55288203-ae9d1d00-53bc-11e9-81a3-582bce69a422.png)

Maintainability rate B achieved :tada:  Let's reach A :muscle:

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/55330540-f5147980-5499-11e9-8784-6642874ef774.png)

6 days to go :rocket:

**Comment by gverni** [comment]
@limonte is there a way to trigger a _codeclimate build_ on a branch other than master to check if the refactoring improved the issue? I tried looking around on codeclimate but couldn't find anything. I can look further, but I thought to ask in case you found already.

**Comment by gverni** [comment]
>  is there a way to trigger a codeclimate build on a branch other than master to check if the refactoring improved the issue?

@limonte should we enable [the code climate PR integration](https://docs.codeclimate.com/docs/github-pull-requests)? It looks quite effective

**Comment by limonte** [comment]
> @limonte should we enable the code climate PR integration? It looks quite effective

Loogs great indeed! Should be installed now :rocket:

**Comment by limonte** [comment]
Hm, for some reason I can't turn these switches on

![image](https://user-images.githubusercontent.com/6059356/55405305-70d9f900-5562-11e9-85e4-0dc03f133978.png)

When I turn them on, click the "Save" button, everything seems fine. But after a refresh, they are off again. I'll contact their support.

**Comment by gverni** [comment]
> Hm, for some reason I can't turn these switches on

I can confirm it works fine on my project (have a look at [this PR](https://github.com/gverni/kairoi/pull/4)). I also enabled codeclimate app in the _checks_ but i'm not sure I like it. At least I'd suggest to enable it only once we reached a better maintainability score.

**Comment by limonte** [comment]
Got the response already

> Hi Limon,
>
> Thanks for reaching out! Happy to help with this.
>
> It looks like there were 2 instances of sweetalert2/sweetalert2 here at Code Climate, which might have been causing the switches to reset.
> 
> I've just deleted the extra copy and enabled the comments. The settings now persist. 👌

The codeclimate integration works nicely now which can be seen here: https://github.com/sweetalert2/sweetalert2/pull/1518

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/55435424-85d67c80-55a2-11e9-91f5-6d443059d06c.png)

5 days to go :rocket:

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/56078796-cd57d680-5df4-11e9-8bcf-4339a9733760.png)

4 days :rocket:

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/56081046-6dbbf400-5e11-11e9-8fcc-f9754abc1ace.png)

Done :rocket: 

There are still some issues, the biggest one is https://github.com/sweetalert2/sweetalert2/issues/1540 I'll take care of it, the rest should be straightforward to fix.

**Comment by gverni** [comment]
Great job, well done @limonte! Should we add the codeclimate badge to the readme? 

<a href="https://codeclimate.com/github/sweetalert2/sweetalert2/maintainability"><img src="https://api.codeclimate.com/v1/badges/eba34bb80477933854d4/maintainability" /></a>
