### ISSUE TITLE
I need "swal.disableCancelButton()/swal.enableCancelButton()" functions

### ISSUE THREAD

**Issue by EmirCanSANCAR** [sweetalert2/sweetalert2#1494]
I need a structure that sends an ajax request when the swal is opened. works for now, but I want to cancel this post when I need a cancel button and the cancel button is coming clickable.

I've solved this problem in the following way and it is better to add these functions in the next update. or a different proposal?

I want the cancel button to be active.

I solved my problem by adding this line code.
```
onOpen: function () {
                        Swal.enableButtons();
                        Swal.disableConfirmButton();
                    },
```

There is an `swal.disableConfirmButton()`/`swal.enableConfirmButton()` function but the `swal.disableCancelButton()`/`swal.enableCancelButton()` function is better if it is added in the next update.

```
Swal.fire({
    showCancelButton: true,
    cancelButtonText: 'İptal',
    imageUrl: new QRious({
        value: (window.location.origin + '/odeme/' + response.transaction_id),
        size: 256
    }).toDataURL(),
    imageAlt: "qrcode",
    html: true,
    title: ('<span style="font-size:2.5rem;">' + response.transaction_id + '</span>'),
    html: ('QR kodu taratarak yada  <a href="' + window.location.origin + '/odeme"><u>' + window.location.origin + '/odeme</u></a> adresine giderek yukarıdaki numerik kodu ilgili alana girip ödeme yapabilirsiniz.<br><strong>Ödeme Bekleniyor. . .</strong>'),
    onBeforeOpen: () => {
        ajaxManager.run();
        Swal.showLoading();
        paymentRestListenerInterval = setInterval(function () {
            ajaxManager.addReq({
                global: false,
                url: `/applications/${$('#application_id').val()}/payment-rest`,
                success: function (response) {
                    if (response.success == true) {
                        clearInterval(paymentRestListenerInterval);
                        ajaxManager.stop();
                        Swal.fire({
                            title: 'İşlem Başarılı!',
                            html: 'Ödeme Alındı! Anasayfaya yönlendirileceksiniz.',
                            type: 'success',
                            onClose: function () {
                                $('#page-content-section').remove();
                                window.location.replace("/");
                            }
                        });
                    } else if (response.success == false) {
                        clearInterval(paymentRestListenerInterval);
                        ajaxManager.stop();
                        Swal.fire({
                            title: 'İşlem Başarısız!',
                            html: 'Ödeme alınamadı!',
                            type: 'error'
                        });
                    }
                }
            });
        }, 1000);
    },
    onClose: () => {
        clearInterval(paymentRestListenerInterval);
        ajaxManager.stop();
    }
});
```

![gaVmy6IctCKgzlgEN5XqTgKKchYQy7laeaJxbc3U](https://user-images.githubusercontent.com/16269350/55065457-e8a0b300-508c-11e9-9420-b9b3c5824e1c.gif)

```<button type="button" class="swal2-cancel swal2-styled" aria-label="" style="display: inline-block;" disabled="">İptal</button>```

**Comment by limonte** [comment]
Good day @EmirCanSANCAR and that you for a good feature request!

Adding `swal.disableCancelButton()/swal.enableCancelButton()` is as easy as copy-pasting the similar fucntionality of `swal.disableConfirmButton()/swal.enableConfirmButton()`

Would you like to submit a PR? It should be quite straightforward, search for `enableConfirmButton` https://github.com/sweetalert2/sweetalert2/search?q=enableConfirmButton&unscoped_q=enableConfirmButton

**Comment by gverni** [comment]
> Adding swal.disableCancelButton()/swal.enableCancelButton() is as easy as copy-pasting the similar fucntionality of swal.disableConfirmButton()/swal.enableConfirmButton()

@EmirCanSANCAR alternatively you can always use: 

```javascript
Swal.getCancelButton().removeAttribute('disabled')
```

@limonte should we hide the cancel button when the swal is loading (i.e. replace both buttons with a spinner)? I understand the rationale behind replacing the confirm button with the spinner, but it looks a bit odd like that.

**Comment by limonte** [comment]
> should we hide the cancel button when the swal is loading (i.e. replace both buttons with a spinner)? 

That would be a breaking change, but I'm opened for discussion. My reasoning behind leaving it was that users will always be able to close the modal if AJAX request is taking a lot of time. 

Please submit an issue if you think that behavior is incorrect, so we can discuss that separately.

**Comment by EmirCanSANCAR** [comment]
`Swal.getCancelButton().removeAttribute('disabled')` this code solved my work.

According to my opinion. Optionally, the shutdown button must be switched on when modal loading.
The default should be hidden but optional.

because, for example, I'm listening to a service from this application when the user presses the button and I need to inform the user when the return is successful. but the user may want to interrupt and cancel this. In such cases, you need the cancel button.

Thank you very much for your interest. good work. :+1:
