### ISSUE TITLE
Define status of Swal's elements when the Swal is loading (`Swal.isLoading()` is true)

### ISSUE THREAD

**Issue by gverni** [sweetalert2/sweetalert2#1495]
> should we hide the cancel button when the swal is loading (i.e. replace both buttons with a spinner)? 

That would be a breaking change, but I'm opened for discussion. My reasoning behind leaving it was that users will always be able to close the modal if AJAX request is taking a lot of time. 

Please submit an issue if you think that behavior is incorrect, so we can discuss that separately.

_Originally posted by @limonte in https://github.com/sweetalert2/sweetalert2/issues/1494#issuecomment-477067696_

**Comment by limonte** [comment]
I was expecting some reasoning here :) Why the cancel button should be hidden automatically?

For me personally, it would be unexpected if it would be hidden despite `showCancelButton: true` I specified in `Swal.fire()`.

**Comment by gverni** [comment]
> My reasoning behind leaving it was that users will always be able to close the modal if AJAX request is taking a lot of time.

The problem is that the `Swal.showLoading()` actually disables the cancel button, so this is not currently possible. 

https://github.com/sweetalert2/sweetalert2/blob/57c63035d54ca771e5c7bb66a2431ef0d5c13b2c/src/staticMethods/showLoading.js#L21-L22

A couple of options: 

* Change default behavior to have cancel button enabled by default 
* Re-enable cancel button after some time

**Comment by gverni** [comment]
> I was expecting some reasoning here :) 

Sorry... I was still reviewing my comment :smile:

**Comment by limonte** [comment]
> The problem is that the Swal.showLoading() actually disables the cancel button, so this is not currently possible.

Good point, I forgot that!

> Change default behavior to have cancel button enabled by default

My vote goes for this option, user can always disable cancel button manually if desired:

```js
Swal.showLoading()
Swal.getCancelButton().setAttribute('disabled', '')
```

**Comment by limonte** [comment]
> Change default behavior to have cancel button enabled by default

@EmirCanSANCAR also for this option https://github.com/sweetalert2/sweetalert2/issues/1494#issuecomment-477076551

**Comment by gverni** [comment]
> Maybe we should better define what to do with the modal and the controls in it when the modal is in _loading_ state. 

@limonte let me follow-up here on this statement from #1499. 

There are 5 elements the user can interact with in a swal: 
* Confirm button
* Cancel button
* Input
* Close button 
* Click-to-dismiss backdrop

Currently the `showLoading()` is only setting status (i.e. `disabled`) for the buttons and adding specific classes to the `popup` and `actions`. What I think we should add is defining default status for the other elements above listed. For example we may want: 

* Disable the close button (if we disable the cancel button)
* Disable the _click-to-dismiss_ backdrop (i.e. the user won't be able to cancel the modal is in loading)
* Disable input (see #1499) 

I think the most important thing is to define a consistent status (either _enabled_ or _disabled_) for all the elements above. Optionally (if it doesn't complicate the swal design) we can add properties for changing this default status.

What do you think? 

P.S. I'm changing the title of the issue to reflect this widening of the scope

**Comment by limonte** [comment]
As previously, I vote to stop adding opinionated features and start doing absolutely nothing to controls when a popup is in the loading state, e.g. do not disable the Cancel button when in loading state: https://github.com/sweetalert2/sweetalert2/issues/1501 

Devs have different requirements and use-cases, we can fit everyone's needs by not being intrusive with our guesses + providing all necessary getters.

They can do whatever they want in `preConfirm`, all getters are there:

- `Swal.getConfirmButton()`
- `Swal.getCancelButton()`
- `Swal.getInput()`
- `Swal.getCloseButton()`
- `Swal.getContainer()` (which is curently undocumented https://github.com/sweetalert2/sweetalert2.github.io/issues/71)

**Comment by limonte** [comment]
No opinionated features = no opinionated code = easier maintanance = no useless discussions = smaller bundle.

Win-win from all sides :)

**Comment by gverni** [comment]
> No opinionated features = no opinionated code = easier maintanance = no useless discussions = smaller bundle.

I love that! As a user of sweetalert I always liked that it never got _in the way_ and forced me to find a workaround. I agree we should embrace that...

**Comment by gverni** [comment]
@limonte I'm closing this in favor of #1501. Feel free to reopen if you would like to discuss more...
