### ISSUE TITLE
Should we deprecate enableConfirmButton()/disableConfirmButton()?

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1496]
These legacy methods were here before `Swal.getConfirmButton()` was added.

Since devs can enable/disable the Confirm button as simple as:

```js
Swal.getConfirmButton().setAttribute('disabled', '')
Swal.getConfirmButton().removeAttribute('disabled')
```

I don't think there's a need for additional complexity in API.

@gverni what do you think?

**Comment by gverni** [comment]
@limonte I fully agree. When I was looking for a possible workaround for #1494, the use of `Swal.getCancelButton()` came to me quite naturally. Mainly because it allows any kind of changes to the button element (i.e. not only enable/disable)

**Comment by rbatty19** [comment]
I think this should be documented in the main page
