### ISSUE TITLE
Popup without Img first

### ISSUE THREAD

**Issue by Hinrick** [sweetalert2/sweetalert2#1498]
##Current behavior

I made an alert with Img(which is .gif)
The alert popup with no image first, the jump to the normal one(alert with image).

## Expected behavior

Popup with images immediately!

## Live demo
https://www.youtube.com/watch?v=EP97CYB5pcg&feature=youtu.be

I'm using React.
After onClick the button, the function called LineLogOut() will be exected.

Then jump into lineLogOut:

lineLogOut = () => {
     Swal.fire({
      text:"系統偵測目前使用「私密瀏覽」視窗，無法使用 LINE 登入，請改用一般視窗即可順利登入。",
      imageUrl: icognito,   // import icognito from '../../....'
      button: "好!我瞭解了!",
    });
}

I tried several ways, setTimeout, use the sweetAlert V.1, save img url as variable first..

Still didn't work.

Needs help, tons of thanks~

**Comment by limonte** [comment]
You need to preload image before using it in modal:

```html
<link rel="preload" href="[image_url]" as="image">
```

Read more about preloading content: https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by Hinrick** [comment]
@limonte  
Thanks for your prompt reply.
I tried, but, still not popup with images first.
I became faster, but not immediately.

`<link rel="preload" href="/statics/images/icognito_line.gif" as="image">`
