### ISSUE TITLE
Disable input during preConfirm

### ISSUE THREAD

**Issue by gRoberts84** [sweetalert2/sweetalert2#1499]
## New feature motivation

Although it doesn't appear to affect the value returned, it is possible for users to modify the input value during a long `preConfirm`. 

https://jsfiddle.net/gRoberts/7grLqtzd/10/

In my above example, if you click on the button and enter a value. During the 10 second timeout, the input is still accessible and modifiable. However upon completion, the returned value is obviously still the same as the initial.

https://jsfiddle.net/gRoberts/7grLqtzd/12/

If an inputValidator is defined, the inputs are disabled as expected but this appears to ignore the `showLoaderOnConfirm` option.

## New feature description

To improve user experience, it would be useful if you could disable the input during the `preConfirm` process.

## New feature implementation

Could potentially move the `this.disableInput()` call outside of the `if (innerParams.inputValidator) {` statement?

**Comment by gverni** [comment]
thanks @gRoberts84 for the detailed new feature. 

@limonte I can start to see a pattern here (see also #1495). Maybe we should better define what to do with the modal and the controls in it when the modal is in _loading_ state. What do you think?

**Comment by gverni** [comment]
> Maybe we should better define what to do with the modal and the controls in it when the modal is in loading state. What do you think?

I added a new comment in #1495 to explain what I mean (so I don't pollute this issue)

**Comment by limonte** [comment]
```js
preConfirm: () => {
  Swal.getInput().setAttribute('disabled', '')
  ...
}
```
