### ISSUE TITLE
Stop disabling the Cancel button when in loading state 

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1501]
This is the follow-up from https://github.com/sweetalert2/sweetalert2/issues/1494#issuecomment-477076551

Disabling the Cancel button automatically is too opinionated, devs can always do it (if needed) in the `preConfirm` function:

```js
preConfirm: () => {
  Swal.getCancelButton().setAttribute('disabled', '')
  ...
}
```

**Comment by yasawibu** [comment]
> tada This issue has been resolved in version 9.0.0 tada
> 
> The release is available on:
> 
>     * [npm package (@latest dist-tag)](https://www.npmjs.com/package/sweetalert2)
> 
>     * [GitHub release](https://github.com/sweetalert2/sweetalert2/releases/tag/v9.0.0)
> 
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot packagerocket

I use version 9.15.1 installed from npm and this issue still exist.

**Comment by iwasherefirst2** [comment]
I use version 11.6.8 and still have the same issue.

I think default should be that the `cancel` button should be hidden. 
![image](https://user-images.githubusercontent.com/1765602/214240278-cb3f40fa-b2f1-4187-a895-ae1b8204ed5f.png)

Is there any option to do this?

``` Swal.fire({
                        title: 'Are you sure?',
                        showCancelButton: true,
                        html: 'Are you sure you want to change email from ' + this.formData.old_email + ' to ' + this.formData.new_email + ' in all systems?',
                        icon: 'question',
                        confirmButtonText: 'YES PLEASE',
                        showLoaderOnConfirm: true,
                        preConfirm: () => {
                            Swal.getCancelButton.addAttribute('hidden');
`` `

does not exactly work.

**Comment by jsdeveloperr** [comment]
You should add it like this. -> Swal.getCancelButton().setAttribute('hidden', true)
