### ISSUE TITLE
A more precise description of "target" argument or even a sample in documentation page

### ISSUE THREAD

**Issue by jczerosb** [sweetalert2/sweetalert2#1528]
This is not an library issue.
Documentation page just mention "The container element for adding modal into.", this drive me to think that I can use element ID, and it not work this way.
After searching on issues found a sample showing correct syntax:
"target: document.querySelector('#toast-container')"

I´m suggesting just to include the syntax on description when target choosed will not be body

**Comment by gverni** [comment]
@jczerosb you can have a look to https://sweetalert2.github.io/sweetalert2-examples/parameters/toast-target/. We are building up a library of advanced examples [here](https://sweetalert2.github.io/sweetalert2-examples/) and we may link them from the main page at some point. Feel free to propose any example or to contribute yourself ;-)

Does this answer your question?

**Comment by limonte** [comment]
> his drive me to think that I can use element ID, and it not work this way.

Strings should work as expected.

- https://github.com/sweetalert2/sweetalert2/blob/master/sweetalert2.d.ts#L428
- https://github.com/sweetalert2/sweetalert2/blob/master/test/qunit/params/target.js#L13

**Comment by jczerosb** [comment]
@limonte, you right, but have to string should be preceeded by "#".
My first try was using ID as plain string, then later found an old sample made by you, where I borrow "target: document.querySelector('#toast-container')"

**Comment by jczerosb** [comment]
@gverni, Yes.
As a new user, my contribution, is limited to suggest, very small and simple notes on main page, like this simple char "#" or "target: document.querySelector('#<use id of element>')"
