### ISSUE TITLE
Remove deprecated gulp-util@3.0.8

### ISSUE THREAD

**Issue by gverni** [sweetalert2/sweetalert2#1535]
When running `npm install` the following warning message is printed: 

```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
```

**Comment by limonte** [comment]
`gulp-util` is the dependency of `gulp-css2js`.

It's an old package and doesn't seem to be maintained anymore nor used by a lot of people.

We might want to replace `gulp-css2js` or don't do anything here and follow the first rule of system administrators: "If It Works, Don't Touch It".

**Comment by gverni** [comment]
> gulp-css2js is an old package and doesn't seem to be maintained anymore nor used by a lot of people.

I’m a bit worried with unmaintained packages. As we know, they can always go rogue. I want to have a look around to see if there something more updated, more used and more secure. If not, I’m happy to follow the admins rule :wink:

**Comment by limonte** [comment]
I would be happy to replace `gulp-css2js` with something more maintained, popular and battle-tested. If you feel like researching the alternatives, please do so :pray:

**Comment by gverni** [comment]
While I keep looking for alternatives, I raised https://github.com/tests-always-included/gulp-css2js/issues/9

**Comment by gverni** [comment]
I did a PR on `gulp-css2js` to get rid of the dependencies, and ne version is now released. Unfortunately I didn't notice we actually import `gulp-util` directly. I'm closing this issue in favor of #1548
