### ISSUE TITLE
How can i use external components like react-h5-audio-player in html 

### ISSUE THREAD

**Issue by abhiram5** [sweetalert2/sweetalert2#1552]
Here i want to show audio preview in the sweet alert so that user can listen to the audio before taking any actions 

[Here my sample code](https://codesandbox.io/embed/10knw7nmwj)

When we click on the button it showing like [object object] in the sweet alert instead of audio preview how can I achieve this using sweet alert

**Comment by limonte** [comment]
There's the official SweetAlert2 enhancer adding support for React elements as content: https://github.com/sweetalert2/sweetalert2-react-content

```js
import Swal from "sweetalert2";
import withReactContent from 'sweetalert2-react-content'

const Alert = withReactContent(Swal)

Alert.fire({
  html: <AudioPlayer src="http://business.vobo.ai/voice_samples/about_company.mp3" />
})
```

**Comment by abhiram5** [comment]
hi @limonte, Thanks for the speedy response.
I just tried your steps, it's working fine when 

`Alert.fire({
  html: <AudioPlayer src="http://business.vobo.ai/voice_samples/about_company.mp3" />
})`

But when i tried to use external component with some html still showing like object object
[can you please check this case once](https://codesandbox.io/s/llp6qymrxm)

Let me know if missed anything.

**Comment by limonte** [comment]
You're missing some basic knowledge about JS and the framework you're using.

Here's your homerowk:

```js
      html:
        <div class="table-responsive">
        <table class="table">
        <tbody>
        <tr >
        <td>Title</td>
        <td><strong>
        am sweetAlert
        </strong></td>
        </tr>
        <tr >
        <td>Start Time</td>
        <td><strong>
        Some date
        </strong></td>
        </tr>
        <tr >
        <td>Audio File</td>
        <td> <div>
        <AudioPlayer src="http://www.noiseaddicts.com/samples_1w72b820/271.mp3" />
        </div></td>
        </tr>
        </tbody>
        </table>
        </div>,
```

Read more: https://reactjs.org/docs/introducing-jsx.html
