### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier 'sweetalert2'. Relative references must start with either “/”, “./”, or “../”

### ISSUE THREAD

**Issue by eliasskogevall** [sweetalert2/sweetalert2#1554]
## Current behavior

(Using TypeScript in VS Code)
When I import sweetalert2 like this:

```typescript
import Swal from 'sweetalert2'
```

I get the error and my site stops loading

## Expected behavior

The expected behavior is simple; work as any other module does.

## Live demo

![Screenshot (93)](https://user-images.githubusercontent.com/47453366/56454332-3f796f80-634f-11e9-9491-5c10b44257ad.png)

**Comment by eliasskogevall** [comment]
TypeScript doesn't seem to work very well with sweetalert/sweetalert2...

**Comment by limonte** [comment]
Good day @eliasskogevall and welcome to GitHub.

You're most probably trying to use SweetAlert2 as ES module in browser. Here's the correct way to use SweetAlert2 as  ES module in a browser:

```html
<link rel="stylesheet" href="/path/to/node_modules/sweetalert2/dist/sweetalert2.css">

<script type="module">
  import Swal from '/path/to/node_modules/sweetalert2/src/sweetalert2.js'
  Swal.fire('hi')
</script>
```
Live demo: https://important-hall.glitch.me/

---

Useful reading about ES modules: https://flaviocopes.com/es-modules/

**Comment by limonte** [comment]
> TypeScript doesn't seem to work very well with sweetalert/sweetalert2...

Works perfectly:

![image](https://user-images.githubusercontent.com/6059356/56476034-a3a84a80-6499-11e9-8130-8a45581d1694.png)

**Comment by najram99** [comment]
I have the same issue. Problem seem to be that js file that is generated from ts, does not have path to sweetalert2.js.
For example:

**index.html:** 
<script type="module" src="./node_modules/sweetalert2/src/sweetalert2.js"></script> 
<script type="module" src="./src/test.js"></script>

**test.ts:**
```
import swal from 'sweetalert2';
swal.fire("Hello");
```

After executing tsc command, you get generated **test.js**, which is practically the same. 
Now you get:

> Uncaught TypeError: Failed to resolve module specifier "sweetalert". Relative references must start with either "/", "./", or "../".

Yes, If I change import path in generated js manually, it works. But howto change path in ts file? If I use the same path (import swal from '../node_modules/sweetalert2/src/sweetalert2.js'),  I get: 

> Could not find a declaration file for module '../node_modules/sweetalert2/src/sweetalert2.js'. 'c:/work/testSweetAlert/node_modules/sweetalert2/src/sweetalert2.js' implicitly has an 'any' type.ts(7016)
