### ISSUE TITLE
Timer showing the text "seconds"

### ISSUE THREAD

**Issue by vitordesousa** [sweetalert2/sweetalert2#1558]
## New feature motivation

In docs, the timer show "I will close in <strong></strong> seconds.", but the time counts in milliseconds. 

## New feature description

Please, change text to "milliseconds", or:

```
.textContent = (Swal.getTimerLeft() / 1000).toFixed()
```
to show correctly the seconds.

**Comment by limonte** [comment]
Thanks for reporting @vitordesousa 

This will be fixed in https://github.com/sweetalert2/sweetalert2.github.io/pull/76
