### ISSUE TITLE
SweetAlert2 Integration with Laravel 5.7

### ISSUE THREAD

**Issue by fredochieng** [sweetalert2/sweetalert2#1561]
Hello, how can I integrate sweetalert2 with Laravel 5.7? Thank you

**Comment by gverni** [comment]
Hi @fredochieng, Sweetalert2 is provided as is to be used in _VanillaJS_ projects. My advice is to use StackOverflow for questions on Laravel integration.

**Comment by limonte** [comment]
https://github.com/realrashid/sweet-alert

**Comment by limonte** [comment]
https://github.com/sweetalert2/sweetalert2-laravel
