### ISSUE TITLE
Memory management: references not detached 

### ISSUE THREAD

**Issue by jf-m** [sweetalert2/sweetalert2#1569]
## Context

I am using swal2 in a heavy SPA that uses VueJs. I am currently busting all of the potential memory leakages in the application, and I believe I've found a potential threat coming from sweetalert2.  

## Current behavior

This problem occurs when you fire an alert using either a `preConfirm` or by just attaching a function through `.then()`, like so:

```
var baz = 4;
Swal.fire({
  title: 'Test',
  preConfirm: () => this.foo(baz)
}).then((d) => {
  if (d.value) {
    this.bar(baz)
  }
})
```

It is important to note that this `fire` method has been called inside a **vuejs** component, therefore the `this` context of both `foo` and `bar` includes a whole bunch of data/properties/methods that may consumes a lot of memory.

If this swal modal is fired and the user cancel it (e.g. by clicking outside), the swal closes itself and everything works like a charm, except when you move out of the current `vuejs` component, and take a quick look at a Chrome heap snapshot. Here is what I see :

![image](https://user-images.githubusercontent.com/9339799/57031981-10150d80-6c41-11e9-907f-fb9055883fa7.png)

We can clearly see that a `WeakMap` inside sweetalert is retaining a Promise (I'm using bluebird promises btw, but it also happens without bluebird).
This promise seems to have all my `vuejs` component attached as its context, preventing the GC from collecting the memory.

It is **not** an actual memory leak because the memory does not stack. It's just an annoying reference that prevent the GC from collecting the underlying context.

## Proposed solution

When going deeper using the debugger, I've identified the source of this behavior:

`privateMethods` and `privateProps`

- `privateProps.promise` is retaining a promise with my `vuejs` context.
- `privateMethods.swalPromiseResolve` seems to retain a `vuejs` context as well.
- `privateProps.innerParams` is retaining my `preConfirm` and therefore the `vuejs` context attached to the function.
- `privateProps.domCache` is retaining references a DetachedHtmlElement that can be seen in the heap snapshot. (less harmful but still)

### Code

Here is my proposed solution : https://github.com/jf-m/sweetalert2/commit/b2a77c6639c8d5f7b18bc24d5a58c85b41bd5218

I have not made any pull-request because I am not sure wether `removePopupAndResetState` is the right place to dispose of  `privateProps.innerParams`, `privateProps.domCache` and `privateMethods.swalPromiseResolve`...

However, I've tried my commit and the GC collects my vue components, is seems to work in my test case.

By the way, thank you for this amazing project, it's saving me a huge amount of time in all my projects ;) !

Cheers 🍺

**Comment by gverni** [comment]
Hi @jf-m, yours is one of the best raised issues I’ve ever come across. Thanks for all the details. Unless @limonte has already a solution for you, I’m going to look into that in the next few days an get back to you! Thanks again...

**Comment by jf-m** [comment]
Hi @gverni , I'm glad if I can help !

I'm still working on this issue, and it appears that `privateMethods` and `privateProps` are not the only ones that retains references to `preConfirm` param.

Here is what I've found:

![image](https://user-images.githubusercontent.com/9339799/57063751-27dda780-6cbc-11e9-9b82-6e561db86bf6.png)

This one seems to mean that the `preConfirm` is retained in `innerParams` inside the `keydownHandler` of `_main.js`.

And here is another one:

![image](https://user-images.githubusercontent.com/9339799/57063768-35932d00-6cbc-11e9-9bd2-ba35f2cdcfb2.png)

This one seems to mean that `preConfirm` is also retained in a `params` property somewhere in `SweetAlert`.


I will try to dispose of these properties in my fork and see what happens.

It is important to say that I am not a Chrome Heap Snapshot expert 8)! So.., I may be wrong in the interpretation. I'm just trying hard :)!

Cheers 🍻

**Comment by jf-m** [comment]
Ok, after some tests, it looks like after my commit, all the references are correctly disposed and the GC collects them, solving this issue.

Just for the record, I've encountered this last one during my tests:
![image](https://user-images.githubusercontent.com/9339799/57067881-19958880-6cc8-11e9-8a77-2e70f68b6dc8.png)

That's the reason why I've set `globalState.keydownTarget` to null as well in my commit.

I let you guys check on my branch https://github.com/jf-m/sweetalert2/tree/fix/memory if everything looks fine to you.

👍

**Comment by gverni** [comment]
Thanks you so much @jf-m for the hard work! Sorry if I didn't get to look at your changes yet, but I was a bit busy. I'll try to review them as soon as possible!

**Comment by jf-m** [comment]
Dont worry, nothing urges! I've changed my dependencies to use my fork for the moment.

I'm happy to help ! And once again, I thank you back for this amazing work on sweetalert2, it's a really well developed and designed plugin, very very handy, reliable and full of smart features!

🍻

**Comment by gverni** [comment]
@limonte thanks for the PR! While trying to reproduce this, I was doing some other profiling and I could see that in some cases there are some [_detached_](https://developers.google.com/web/tools/chrome-devtools/memory-problems/#discover_detached_dom_tree_memory_leaks_with_heap_snapshots) DOM elements left by Swal (about 60 of them). I'll double check with this PR as well and if my investigations confirm that I'll open a new issue.

**Comment by limonte** [comment]
@gverni please feel free to continue your research on detached DOM elements. Even though this particular issue is fixed, there still might be some details preventing GC to dispose things.
