### ISSUE TITLE
Allow passing HTML with positional parameters

### ISSUE THREAD

**Issue by alexherbo2** [sweetalert2/sweetalert2#1574]
**Prototype**

``` javascript
Swal.fire(title, description)
```

HTML is accepted as a description, but only as a string.

A workaround is to pass the description with [outerHTML].

[outerHTML]: https://developer.mozilla.org/en-US/docs/Web/API/Element/outerHTML

**Comment by limonte** [comment]
Won't change, please use `outerHTML` or an object for params.

**Comment by alexherbo2** [comment]
@limonte Why allowing but enforcing HTML as a string?
