### ISSUE TITLE
Trying to use version 8

### ISSUE THREAD

**Issue by DiegoASG** [sweetalert2/sweetalert2#1577]
Hello, I was trying to use the version 8 but I cannot find the "dist" folder, where the min.css and min.js are supposed to be. If someone could instruct me as to where to find them, thanks

**Comment by limonte** [comment]
> I was trying to use the version 8

How exactly?

**Comment by DiegoASG** [comment]
Well with the version 7 I was able to download the archives and inside the "dist" folder I used the (sweetalert2.min.js) and the (sweetalert2.min.css), and I was able to ass them to my project, however when I get all the version 8 files I cannot find those archives.

**Comment by limonte** [comment]
I see, you're probably downloading them manually from https://github.com/sweetalert2/sweetalert2/releases which isn't the official way to download SweetAlert2.

Please follow the installation instructions from README: https://github.com/sweetalert2/sweetalert2#installation
