### ISSUE TITLE
problem in displaying alert popup

### ISSUE THREAD

**Issue by AnandanRajkumar** [sweetalert2/sweetalert2#1580]
## Current behavior
i am not able to show alert pop up when the browser video full screen is on .for your reference  i had attached the screenshot of current and expected behavior .

![image](https://user-images.githubusercontent.com/27425369/57292520-82716c00-70df-11e9-83ea-d47ba03f8cf6.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/27425369/57292796-7afe9280-70e0-11e9-8110-80b9fe3172b7.png)

**Comment by limonte** [comment]
https://stackoverflow.com/questions/ask

**Comment by AnandanRajkumar** [comment]
why you closed this issue .
