### ISSUE TITLE
document scrolling is prevented AFTER modal is shown 

### ISSUE THREAD

**Issue by OlofT** [sweetalert2/sweetalert2#1581]
All I've done is to take a page, import it 
`<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>`
then shown it:
```
Swal.fire({
				title: "A title",
				type: 'question',
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: 'Yes!'
			}).then(function(result)
			{
				if (result.value)
				{
					someFunction()
				}
			})
```

After clicking buttons, there are still lots of CSS-stuff. Among others this one, which prevents scrolling:

body.swal2-shown:not(.swal2-no-backdrop):not(.swal2-toast-shown) {
    overflow: hidden;
}

**Comment by gverni** [comment]
Hi @OlofT that shouldn't happen. I just tried your code, and scrolling is correctly enabled. Maybe something goes wrong in the close phase with your ```someFunction()``` code. Can you provide a live example that show this behavior using the instructions [here](https://github.com/sweetalert2/sweetalert2/wiki/How-to-provide-live-example-for-issue)?

**Comment by limonte** [comment]
A modal window is a graphical control element which creates a mode that _disables_ the main window but keeps it visible, with the modal window as a child window in front of it. 

Set the `backdrop` parameter to `false` to have a regular modeless popup.

**Comment by gverni** [comment]
@OlofT can you clarify if you issue is after the modal is closed? (in your comment you wrote "After clicking buttons", so I assumed after the swal was closed)

**Comment by OlofT** [comment]
Yes, it was my fault...  In the "someFunction()" the DOM is updated and the div with the alert is removed. This seems to be the cause of the problem. As if the code to clean up is kept inside the HTML (or cannot run if the div is gone).

With a setTimeout of 400, fixes the issue (the animation needs to complete first). Like this:
```
if (result.value)
{
	setTimeout(function ()
	{
		someFunction();
	}, 400)
}
```
 Would be great if this could be fixed somehow (I mean cleaning up without depending on the state of the DOM), in the meantime I will just tuck it away inside a div that does not get removed by "someFunction()".

Also: Thanks so much for the responses, which gave me the clues to figure this out. I mean wow, 3 good responses in just a few hours!

**Comment by gverni** [comment]
@OlofT don’t know if that can help in your use case, but you can always use the `onAfterClose` property to execute a callback once the swal is disposed.

**Comment by OlofT** [comment]
Thanks! It will help!
