### ISSUE TITLE
The success icon in toast is glitchy in Brave Browser and Chromium-based Microsoft Edge 

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1583]
Live demo: https://sweetalert2.github.io/#mixin

![image](https://user-images.githubusercontent.com/6059356/56974068-ce1f9500-6b76-11e9-8f7a-45a5c9d77916.png)

Brave version:

![image](https://user-images.githubusercontent.com/6059356/57057949-55732280-6cb5-11e9-9ff2-02387d46b17b.png)

**Comment by gverni** [comment]
Just to track the last bit of investigation. Setting the `overflow-y` to `visible`  for the `swal2-toast` makes the glitch disappear (but obviously the artifacts used in the animation overflow outside the toast). To test this, just add this to the live sample page above: 

```css
.swal2-popup.swal2-toast {
  overflow-y: visible;
}
```
