### ISSUE TITLE
Release a new major - v9.0.0

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1587]
TODO:

- [x] https://github.com/sweetalert2/sweetalert2/projects/2
- [ ] https://github.com/sweetalert2/sweetalert2-themes/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
- [x] https://github.com/sweetalert2/sweetalert2.github.io/pull/76
- [ ] https://github.com/sweetalert2/sweetalert2.github.io/issues/77
- [ ] https://github.com/sweetalert2/sweetalert2.github.io/issues/79
- [X] https://github.com/sweetalert2/sweetalert2/pull/1592

**Comment by limonte** [comment]
@gverni @zenflow please feel free to add anything you think should be included to the upcoming major release (v9)

The main focus of v9 is **SASS variables and themes**.

Please go through https://github.com/sweetalert2/sweetalert2/blob/master/src/variables.scss and let me know if some variables should be renamed for the upcoming major.

I'm planning to document SASS variables and make them the part of public API for v9.

**Comment by gverni** [comment]
@limonte that's a great idea! Let me review the variables and get back to you.

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/58046938-6b0a9800-7b4f-11e9-8701-966699151792.png)

:cowboy_hat_face: :dart: :sunglasses: 

With v9 we'll hit 10k :rocket:

**Comment by limonte** [comment]
Done: https://github.com/sweetalert2/sweetalert2/releases/tag/v9.0.0
