### ISSUE TITLE
input | checkbox | if inputValue is 1 the checkbox is checked | wrong behavior

### ISSUE THREAD

**Issue by fas3r** [sweetalert2/sweetalert2#1594]
## Current behavior

using `input` type `checkbox` if inputValue is 1 the checkbox is checked. This is not the default  behavior when creating a `input` type `checkbox` in plain `html`

## Expected behavior

The initial state of the `input` type `checkbox` should not be affected by the value define in `inputValue`. 

The checkbox state should be reflected in `inputAttributes` with the attribute `checked` as follow : 

```
inputAttributes: {
   checked: true|false
}
```

 it should create a new `input` type `checkbox` as follow : 

- when in `inputAttributes` checked is `true`:
```
<input type="checkbox" value="1" id="swal2-checkbox" checked>
```

- when in `inputAttributes` checked is `false`:
```
<input type="checkbox" value="1" id="swal2-checkbox">
``` 

## Live demo 

[link to the demo](https://glitch.com/edit/#!/join/df178911-e635-4c5e-9e54-ff105ba2cec8)

additionally, I posted question oon [stackoverflow](https://stackoverflow.com/questions/56177389/sweetalert2-inputattributes-required-false-not-working) on the same topic.

Thank you.

**Comment by gverni** [comment]
Thanks @fas3r, this is actually a good point. As you guessed, in Swal2 we use the the `inputValue` to set the `checked` attribute: 

https://github.com/sweetalert2/sweetalert2/blob/cf4453171986186e147771f3d0ef624fabd4e60e/src/utils/dom/renderers/renderInput.js#L144

This approach can be debatable, but I believe it's a design choice to keep consistency across all input type (@limonte do you agree?). On the other hand I agree we can do better in terms of documentation adding some more information in https://sweetalert2.github.io/#configuration (even though the example for checkbox in the same page should be self explanatory of this parameter). 

Changing the behavior now it's also considered a breaking change, so I'm reluctant to do it. 

@limonte what do you think? I'm happy to improve the documentation rather than making the change.

**Comment by fas3r** [comment]
Hello @gverni , 

No problem, I thought it could be good to raise it in case other user face the same issue. 

I also understand if that's not possible to change it, but then it breaks a bit the logic when using form with steps. 

Even if you moved forward and uncheck the checkbox, this one will be checked again when you click back as it will use the value set in "inputValue".

For now, I use `onOpen` to check the value which was selected previously by the user and set the appropriate state.

fas3r.

**Comment by fas3r** [comment]
Hello @gverni , @limonte , 

A small fix, if you are `OK` with it.

Thanks.

Fas3r.

**Comment by gverni** [comment]
@fas3r thanks for the proposal. I had a look to it and I'm still a bit puzzled on the need for that. I agree that it may be useful to set a value for the checkbox, but keep in mind that in Sweetalert2 you can have only one checkbox if you are using the `input: 'checkbox'` (you can have multiple checkboxes using the `html` properties). Given that, what's the point of setting the value? At the end you only need to check whether the checkbox is checked or not, and depending on that you take the action needed. 

Could you send me a live example where there is the need to set a value for the checkbox so I can better understand your reason for that?

**Comment by fas3r** [comment]
Hello @gverni,

Yes I agree and it will not bring any value. 

However would you consider implement in [src/utils/dom/init.js](https://github.com/fas3r/sweetalert2/pull/1) as below 

```
let oldInputVal = {}// IE11 workaround, see #1109 for details
const resetValidationMessage = (e) => {
  if (sweetAlert.isVisible() && oldInputVal.data !== e.target.value) {
    sweetAlert.resetValidationMessage()
  }
  // fix checkbox, see #1594 for details. This allow to keep track of the checkbox state in "step" mode
  oldInputVal.data = e.target.value
  if(e.target.type === 'checkbox') {
    oldInputVal.checked = !!e.target.checked
  }
}
```

Currently, as inputValue is used to set the state of the checkbox,  the checkbox will never get the state that the user selected when this one will go backward when using `queues`, in the same way that it's done for the input "text", "radio" and "select". 

Let me know and I can commit a new change and revert the modification in `src/utils/dom/renderers/renderInput.js`

Thanks for your time

Fas3r.

**Comment by gverni** [comment]
> Currently, as inputValue is used to set the state of the checkbox, the checkbox will never get the state that the user selected when this one will go backward when using queues

@fas3r I actually don't see this bheavior. I created a live demo [here](https://swal2-queue-checkboxes.glitch.me/) where you can see that the checkbox status is kept going back and forth in the queue. If this is not what you meant, can you provide a live example?

**Comment by limonte** [comment]
> This approach can be debatable, but I believe it's a design choice to keep consistency across all input type (@limonte do you agree?).

Correct.

> On the other hand I agree we can do better in terms of documentation adding some more information in https://sweetalert2.github.io/#configuration (even though the example for checkbox in the same page should be self explanatory of this parameter).

Agree, done in https://github.com/sweetalert2/sweetalert2.github.io/commit/0d435d17da2371ddbacf4f980190d4e911868d99
