### ISSUE TITLE
inputName option to separate input from confirm

### ISSUE THREAD

**Issue by aw-creative** [sweetalert2/sweetalert2#1597]
## New feature motivation

When creating a Sweet Alert to confirm a user wants to delete something, I wanted to optionally ask the user why they were deleting it

## New feature description

Add a new option for the name of the value to be set by inputs.
inputName : string,
When the confirm button is clicked it you can access the values of the confirm button, and input value sepratly.

return.value = 'confirm'
return.*whatevername* = 'The value of the input field'.

You can then access these variables in the then function to perform separate tasks if the input is empty or not.

**Comment by limonte** [comment]
Thanks for the feature request @aw-creative but it doesn't make much sense to me :)

Input + confirm button will result into `{ result: { value: '<input-value>' } }`. When an input is empty `result.value` will be `''`.

Input + cancel button will result into `{ result: { dismiss: 'cancel' } }`

All scenarios are easily distinguishable.
