### ISSUE TITLE
Range slider not working on iPhone

### ISSUE THREAD

**Issue by ledzgio** [sweetalert2/sweetalert2#1603]
Sweetalert range slider not working on iPhone both with Safari and Chrome, I am not able to move the slider in any direction, it's not possible to move the slider left and/or right with the phone.

This is the code I am using in my project:

```javascript
Swal.fire({
  title: 'Lease',
  html: '<small>Lease value</small>',
  input: 'range',
  confirmButtonText: 'Confirm',
  showCancelButton: true,
  cancelButtonColor: '#aaa',
  inputAttributes: {
    min: 0.001,
    max: 5,
    step: 0.001
  },
  inputValue: 0.001,
  preConfirm: (value) => {
    alert(vaue);
  }
});
```

Tried also at the demo link https://sweetalert2.github.io/#input-range but it doesn't work. Using iPhone X device and Safari 12 (same result using Chrome).

Thank you

**Comment by gverni** [comment]
Thanks @ledzgio. I don't have an IOS device at the moment. I'll try that later and get back to you. In the meantime, can you confirm that the `range` demos [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range) works for you? I expect so, but just worth double checking.

**Comment by ledzgio** [comment]
@gverni yes I confirm that demos on link you provided works properly for me.

**Comment by gverni** [comment]
Thanks @ledzgio for trying. I thought so but better try it. I'll get hold of an IOS device later and check what's going wrong.

**Comment by ledzgio** [comment]
Thank you @gverni, I believe this is a critical issue, since iphone owners are a considerable amount of the total users.

**Comment by limonte** [comment]
Oops, that's a regression from https://github.com/sweetalert2/sweetalert2/pull/1596

Thanks @ledzgio for reporting, the fix is coming in a couple of minutes

**Comment by ledzgio** [comment]
You are welcome @limonte, when are you going to release a new version with the fix?

**Comment by limonte** [comment]
@gverni would you be able to review the #1605 today?

**Comment by gverni** [comment]
Yes @limonte, I should be able to do it in about 4 hours
