### ISSUE TITLE
Can't focus to some input element after closing sweetAlert

### ISSUE THREAD

**Issue by TonnTamerlan** [sweetalert2/sweetalert2#1604]
## Current behavior
I try to focus on some input element after closing sweetAlert but it doesn't happen: the focus appears and immediately disappear.
I use swetAlert (v. "8.11.6") and React (v. "16.5.2")
```javascript
await MySwal.fire({
                title: "Empty account name",
                type: "warning",
                text: "Enter account name please",
                confirmButtonColor: "#009616",
                confirmButtonText: "Ok",
                width: "850px",
            });
this.inputAccNameRef.current.focus();
```

## Expected behavior

After closing sweetAlert specific element should be focused

## Live demo

```javascript
await MySwal.fire({
                title: "Empty account name",
                type: "warning",
                text: "Enter account name please",
                confirmButtonColor: "#009616",
                confirmButtonText: "Ok",
                width: "850px",
            });
this.inputAccNameRef.current.focus();
```

**Comment by limonte** [comment]
```js
Swal.fire({
  onAfterClose: () => {
    // focus your element
  }
})
```

**Comment by TonnTamerlan** [comment]
> ```js
> Swal.fire({
>   onAfterClose: () => {
>     // focus your element
>   }
> })
> ```

this doesn't work too

**Comment by TonnTamerlan** [comment]
@limonte 
Thanks

**Comment by franciscoarnaldog** [comment]
SweetAlert2: Unknown parameter "onAfterClose"

**Comment by limonte** [comment]
> SweetAlert2: Unknown parameter "onAfterClose"

`onAfterClose` was removed in [v11.0.0](https://github.com/sweetalert2/sweetalert2/releases/tag/v11.0.0), use `didClose` instead.
