### ISSUE TITLE
GitHub releases missing built files ("./dist" folder)

### ISSUE THREAD

**Issue by david-peter-smith** [sweetalert2/sweetalert2#1606]
## Current behavior
The current release [v8.11.7](https://github.com/sweetalert2/sweetalert2/releases) is missing the built files ("./dist" folder) that contains the final production code.

## Expected behavior
The final built files should be included in tagged full releases for the greatest accessibility of users. Many people do not use CDNs or Package Managers to fetch libraries which is why a ./dist folder is typically present for all releases. Looking at the documentation of this awesome library the dist folder is present within the [Readme documentation](https://github.com/sweetalert2/sweetalert2/blob/master/README.md) itself under usage, so it's exclusion can confuse people in addition to making it harder for them to get and use the library.

## Live demo 
https://github.com/sweetalert2/sweetalert2/archive/v8.11.7.zip

**Comment by limonte** [comment]
Thank you for the request @david-peter-smith 

IMO it's the wrong way to grab JS packages from GitHub releases, but I agree with you that some people are doing that for different reasons, therefore I'd like to fix this issue.

As per discussion in #820

> Built files have no place in version-control (aka source-control, as in source, not build-control).
>
> Package managers are our build-control; they are what we use to distribute/share build-code.

That's the reason why we don't have the `dist` folder in the repo anymore.

The good news is that we can do a small trick: 

- add the `dist` folder into the release commit
- make a GitHub release
- remove the `dist` folder and amend the release commit

I guess that'll do the work, @gverni @zenflow could you please review #1610 and tell what do you think about it? Thanks!

**Comment by limonte** [comment]
I unpublished #1610 - that trick didn't work. After overriding the commit history semantic-release is having troubles in detecting the latest version: https://travis-ci.org/sweetalert2/sweetalert2/builds/542853434

**Comment by limonte** [comment]
I decided not to complicate the releasing process for adding the `dist` folder to GitHub releases.

If for some weird reason you can't use package managers or CDN, please do this:

Step 1: follow the CDN link from the installation guide:

![image](https://user-images.githubusercontent.com/6059356/59146480-843c9100-89f7-11e9-9412-6d98e35d1c86.png)

Step 2: click the "Download" button

![image](https://user-images.githubusercontent.com/6059356/59146491-a2a28c80-89f7-11e9-80d9-446158239027.png)

**Comment by limonte** [comment]
🎉 All files from the `dist` folder are available on GitHub releases starting from  https://github.com/sweetalert2/sweetalert2/releases/tag/v10.16.3
