### ISSUE TITLE
 Multiple SweatAlert2 With Different Themes.

### ISSUE THREAD

**Issue by varunsridharan** [sweetalert2/sweetalert2#1611]
## New feature motivation

I just checked the demo on how the themes works from here : https://sweetalert2.github.io/

And found that we need to load css file for each theme which is good. but if i do that then all popup gets replaced with that theme. in which some case its not good. what if i need 2 different theme for 3 different popups ?

## New feature implementation
So my idea for it is to create something like below
### Javascript
```javascript
swal.fire({
   type:'success',
   title:"Hello World",
   theme:'dark'
})
```
### HTML
```html
<div class="swal2-container ... swal2-theme-dark">...</div>
```
--- OR ---
```html
<div class="swal2-theme-dark">
    <div class="swal2-container swal2-center swal2-fade swal2-shown">
        ...
    </div>
</div>
```

**Comment by limonte** [comment]
Since SweetAlert2 designed to show one popup at the time, therefore I believe the theme-switching logic should be on app-level, not on plugin-level.

Here's how I'd implement the requested use-case:

```html
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8/dist/sweetalert2.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@8/dist/sweetalert2.min.css" id="swal2-theme-styles">
```

```js
const enableSweetAlert2Theme = (theme) => {
  document.head.querySelector('#swal2-theme-styles').setAttribute('href', `https://cdn.jsdelivr.net/npm/@sweetalert2/theme-${theme}/${theme}.css`)
}

const runDarkThenDefaultSwal = async () => {
  await Swal.fire({
    title: `I'm dark`,
    onBeforeOpen: () => enableSweetAlert2Theme('dark')
  })

  await Swal.fire({
    title: `I'm default`,
    onBeforeOpen: () => enableSweetAlert2Theme('default')
  })
}

runDarkThenDefaultSwal()
```

Live demo: https://befitting-astronaut.glitch.me/
Source: https://glitch.com/edit/#!/befitting-astronaut?path=index.html:28:0

Will this work for your app @varunsridharan ?

**Comment by varunsridharan** [comment]
@limonte thanks for your faster reply. well this dose not work for me. 
as i am using `SweetAlert2` in my wordpress settings framework called `WPOnion`http://github.com/wponion/wponion
even tho single popup is shown. but each framework user may require different theme in that case loading theme css on request in a big wp site is not good. so i would prefer the way i have said.

**Comment by limonte** [comment]
I don't see how 

```js
Swal.fire({
   theme:'dark'
})
```

would be any different from

```js
Swal.fire({
   onBeforeOpen: () => enableSweetAlert2Theme('dark')
})
```

Anyways, I am quite sure on this statement

> the theme-switching logic should be on the app-level, not on the plugin-level.

therefore I'm declining this feature-request.

**Comment by varunsridharan** [comment]
@limonte ok thanks for your reply quick question. with the current theme system 
if i load all the css files at once will it work properly ?

**Comment by limonte** [comment]
> with the current theme system if i load all the css files at once will it work properly ?

No, you need to dynamically switch the theme styles, e.g. remove the current one and add the desired one before showing a popup.
