### ISSUE TITLE
Cool feature... hash tags

### ISSUE THREAD

**Issue by rajan77** [sweetalert2/sweetalert2#1622]
## New feature motivation
How about supporting hashtags, in a text input field, similar to https://goodies.pixabay.com/jquery/tag-editor/demo.html ?

I tried including the textfield within sweetalerts HTML option but it didn't work :-(

**Comment by gverni** [comment]
@rajan77 adding it to the existing Sweetalert2 is pretty easy: https://jquery-tageditor.glitch.me/

**Comment by rajan77** [comment]
Thank you so much

Would it be difficult to add it inside the HTML options? I tried something like 

html: '<form><input type="text" id="demo1"></input></form>',

**Comment by rajan77** [comment]
Also, sorry for a basic newbie question... in order to read the value of the field containing the hashtags, do I have to do what is mentioned at https://sweetalert2.github.io/#input-types for text with the above or is there a simpler way?

Thanks again, So Much!!!!

**Comment by limonte** [comment]
> in order to read the value of the field containing the hashtags, do I have to do what is mentioned at https://sweetalert2.github.io/#input-types ?

Yes.

```js
preConfirm: () => {
  return $('.swal2-input').tagEditor('getTags')[0].tags
}
```

Live demo: https://rowan-quit.glitch.me/

**Comment by gverni** [comment]
> Would it be difficult to add it inside the HTML options?

Not at all @rajan77: https://swal2-jquery-tageditor2.glitch.me/

**Comment by rajan77** [comment]
Thank you very very much!!!!
You have several nice days!!!!
