### ISSUE TITLE
What am i doing wrong please?

### ISSUE THREAD

**Issue by rajan77** [sweetalert2/sweetalert2#1630]
I followed the Doc... see the following example:

`Swal.fire({ //start of cube size
title: 'blah',
titleText: 'blah blah',
                        width: '100%',
                        background: '#fff url(/images/mypic.jpg)',
                        animation: false,                        showCloseButton: false,
                        showCancelButton: false,
                        confirmButtonText: 'Continue',
                        allowOutsideClick: false,
                        focusConfirm: false,
                        allowEscapeKey: false,
                        

 html: '<p>blah blah </p>',
footer: 'blah blah',

  input: 'select',
  inputOptions: {
    'none': 'Please select an option:',
    'option1': 'First Option',
    'option2': 'Second Option'
  },
  inputValidator: function (value) {
    return new Promise(function (resolve, reject) {
      if (value != 'none') {
        resolve();
      } else {
        reject('You need to select an option');
      }
    });
  }
}).then(function (theoption) {

etc etc
`

On selecting "none", there is a javascript error. On firefox console, for example, I get 
`"uncaught exception: You need to select an option"`

I realise that I am probably la hopeless Newbee

Thanks in advance... and SweetAlerts ROCKS! Love the guys & gals who put it together

**Comment by limonte** [comment]
This question is unrelated to SweetAlert2, please use StackOveflow for that http://stackoverflow.com/questions/ask
