### ISSUE TITLE
Yet another newbie question....sorry, waiting for ajax

### ISSUE THREAD

**Issue by rajan77** [sweetalert2/sweetalert2#1631]
Hello folks

I do several ajax calls and would like to do the final swal fire once all ajax calls are done.
I tried that in the code below, but obviously, it doesn't have the desired effect. Basically, what I would like is that, after the text are displayed "All Done.... Success!", I would like to have the `showLoaderOnConfirm: true` option while the ajaxStop function is running

my present crappy code:

`Swal.fire(
      'All done!',
      'I will now analyse your answers. Just give me a second',
      'success',
).then(function() {

$( document ).ajaxStop(function() {
	//do other stuff here like... form submit, etc. once all Ajax calls are done
	$('#myform_id').submit();
});
  })
`

Many thanks in advance, to help a newbie out!

Regards
Rajan

**Comment by zenflow** [comment]
Sorry, we don't use issues for this sort of "help me figure out what I'm doing wrong" thing in this project. Use StackOverflow.
