### ISSUE TITLE
Just only source? Need a dist/sweetalert2.min.js Who can help?

### ISSUE THREAD

**Issue by leogitpro** [sweetalert2/sweetalert2#1635]
The project only was source? 
Can i direct use the sweetalert2.min.js in simple h5 website.
Just like jquery. 
don't let me use npm, just simple code. it's too hard for use. 
SweetAlert2 is a pretty project. but support disted source, like jquery. we can directly use it.
Thanks so much!

**Comment by gverni** [comment]
@leogitpro as stated in the [README](https://github.com/sweetalert2/sweetalert2#installation) you can grab Sweetalert from CDN adding the following  to your HTML: 

```html
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
```
