### ISSUE TITLE
Propriedade "textColor" e "iconColor"

### ISSUE THREAD

**Issue by gilvannfilho** [sweetalert2/sweetalert2#1638]
## New feature motivation

Ter a possibilidade de modificar a cor conforme a necessidade de uso.

---

Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:
- PayPal: https://www.paypal.me/limonte
- Bitcoin: `12BxefvPMtHePgfPRDL1SaZYSG4GwQmWoP`
- Ether: `0x36e2b10666e2c0dc343901895ba3697b5d3214d1`
- Bitcoin Cash: `qqxs402qszgwuue00gwxw996lzhpa8up2unqm0y46g`
- Stellar: `GBRS5KGFJO4OBUGW3TRQBIVXTM5YDS53DOSHGA3LKVE2YXKVKNVDONBP`

**Comment by gverni** [comment]
@gilvannfilho it would be very helpful if you create your question in english. Having said that, If I understand your question correctly, you can customize the color (and the rest of the style) using the `customClass` properties of Swal2. More info about that at https://sweetalert2.github.io/.
