### ISSUE TITLE
Can't import 'Swal'

### ISSUE THREAD

**Issue by mumvock** [sweetalert2/sweetalert2#1644]
## Current behavior
app.module.ts [Angular version 8.1.0.]
Module '"sweetalert2"' has no exported member 'Swal'.

## Expected behavior
Swal member

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/60739332-30778600-9f6a-11e9-9496-25aeeb9e4bc4.png)

**Comment by Lizard-King101** [comment]
in any component
```
// imports go here
import {Swal} from 'sweetalert2';
// sweatalet2 has no export member from Swal
export class WhatEverComponent{
    constructor() {
    }
}
```

**Comment by toverux** [comment]
```ts
import Swal from 'sweetalert2';
```
