### ISSUE TITLE
Failed response when quick operation

### ISSUE THREAD

**Issue by Freppex** [sweetalert2/sweetalert2#1646]
![Screenshot_2](https://user-images.githubusercontent.com/42165949/60831911-fa7d1080-a1ba-11e9-9571-55580d9e7e88.png)

Uncaught TypeError: Vt.swalCloseEventFinishedCallback is not a function

**Comment by limonte** [comment]
Thanks for reporting @Freppex!

Could you please provide a bit more info on what is "quick operation", e.g. how to reproduce the issue?

**Comment by Freppex** [comment]
Hey, @limonte!
Keypress: Enter,
if you keep it connected, you will get an error.

**Comment by gverni** [comment]
> if you keep it connected, you will get an error.

What you mean with "keep it connected" @Freppex?

**Comment by Freppex** [comment]
@gverni,
Press and hold the Enter key.

**Comment by gverni** [comment]
@Freppex could you share an example that gives this issue? I tried on several examples of swal holding the enter key and I haven't reproduced it. Also, if you can provide me which browser and OS yoy are using, it could help debugging further.

**Comment by gverni** [comment]
Also @Freppex, are you using it with a framework (react, vue, etc...)?

**Comment by Freppex** [comment]
@gverni node.js
![image](https://user-images.githubusercontent.com/42165949/60835747-39fc2a80-a1c4-11e9-932f-e5a9e5155e3b.png)

**Comment by Freppex** [comment]
![image](https://user-images.githubusercontent.com/42165949/60835855-7596f480-a1c4-11e9-9509-80b744d2b3a7.png)

**Comment by gverni** [comment]
@Freppex can you share the code where you are firing the Swal?

**Comment by Freppex** [comment]
view enginer swig
Chrome 75 on Windows 10

**Comment by Freppex** [comment]
@gverni
`            Swal.fire({
                type: 'error',
                title: 'Boş Alan!',
                text: 'Boş alan bırakamazsın.'
            });`

**Comment by gverni** [comment]
I think I reproduced it @Freppex: https://swal2-press-enter-issue.glitch.me/

* Focus on button with tab
* Press enter and hold it down
* Swal opens and close immediately and the error is shown in console

Let me work on a fix straight away....

**Comment by gverni** [comment]
Found the issue... my bad. Making a PR shortly...

**Comment by Freppex** [comment]
Glad you found it.

**Comment by Freppex** [comment]
@gverni close issue?

**Comment by Freppex** [comment]
![image](https://user-images.githubusercontent.com/42165949/60840452-d0821900-a1cf-11e9-813e-cdc8e61f8ae6.png)

![image](https://user-images.githubusercontent.com/42165949/60840478-e0016200-a1cf-11e9-99fe-46f09f3dcace.png)
 
Good.

**Comment by gverni** [comment]
Let's keep it open until we make the release...

**Comment by chandrasekharu** [comment]
this issue is still there in the version

"sweetalert2": "9.5.3"

![image](https://user-images.githubusercontent.com/26438079/109550660-d0155080-7a8c-11eb-8acc-b1850eb42135.png)
