### ISSUE TITLE
Aria-hidden is removed from all direct children

### ISSUE THREAD

**Issue by lakesare** [sweetalert2/sweetalert2#1648]
## Current behavior

https://github.com/sweetalert2/sweetalert2/blob/60dd1e7634fecb23d397041fab8fab3b37ed75f4/src/utils/aria.js#L24
This line removes all `aria-hidden`s from all direct children of the body.

## Expected behavior

We expect elements that are not connected to sweetalert to not be touched.

## Live demo 

https://gist.githack.com/epexa/110e28db117bed6a9b1ce8df6a2e7cd3/raw/4f503c7fc7dd244b62a46e8241d883abbf49ccae/uppy_sweetalert2_bug.html

Here Uppy instance is getting shown when we click on the SweetAlert (this happens solely because `aria-hidden` is removed from the `div.uppy-Root.uppy-Dashboard`).

**Comment by limonte** [comment]
Thank you @lakesare for reporting this issue! I'll handle it :+1:
