### ISSUE TITLE
cssmin error when minized sweetalert2.css file

### ISSUE THREAD

**Issue by andryshok** [sweetalert2/sweetalert2#1650]
I use google cssmin  for minimize my css project files. I have error when sweetalert2.css file include for minimize and styles after then minimize with errors

**Comment by limonte** [comment]
Thank you @andryshok for reporting this. google's cssmin seem to be outdated and unmaintained (surprise-surprise, abandoned google's product :laughing:).

Please use some up-to-date plugin for CSS minification, e.g. https://www.npmjs.com/package/clean-css
