### ISSUE TITLE
🎉🎉 Who uses SweetAlert2? 🎉🎉

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1653]
Hi All!
We are really keen to collect your feedback, and to start with, we'd like to know who is using **SweetAlert2**. We would really appreciate if you:

- Share your company name
- Share your logo (in which case it might be used in the readme / frontpage etc)
- What kind of project? How large? (code base size or team size)
- If your project is open source or public, please share a link!
- What do you like most about SweetAlert2, what could be done better?

And of course, you can show your :heart: and [support my work](https://github.com/sponsors/limonte) :)

**Comment by zenichanin** [comment]
We use SweetAlert2 for our back-end administration panel. It makes our alerts and confirmation boxes look nice and tidy.

Company name is PriceListo. (Logo if needed: https://www.pricelisto.com/assets/images/logo-blue.png)

We organize and categorize pricing information for all major business establishments such as restaurants, fitness gyms, beauty salons, etc...

The project is not open source, however, the website is public and is free to use for any consumers.

Hope that helps! 👍

**Comment by GLuchtenberg** [comment]
![image](https://user-images.githubusercontent.com/28123879/60985552-0f20ec00-a314-11e9-9e70-bd58b6077dc1.png)

We're using sweetalert2 as our main feedback component on [Genebra](http://genebraquality.com), we're not opensource but you can take a look at our public website

sweetalert2 helped us to give much better feedback to our customers, and helped us to guide customers by the flow we were expecting

**Comment by limonte** [comment]
I'd like to publish here the list of most popular repositories on GitHub which have **SweetAlert2** as a dependency:

 - https://github.com/RocketChat/Rocket.Chat (🟊 23359)
 - https://github.com/CachetHQ/Cachet (🟊 9979)
 - https://github.com/reactioncommerce/reaction (🟊 8974)
 - https://github.com/prisma/graphql-playground (🟊 4709)
 - https://github.com/kitze/JSUI (🟊 3818)
 - https://github.com/rappasoft/laravel-5-boilerplate (🟊 3539)
 - https://github.com/HVF/franchise (🟊 3461)
 - https://github.com/ng-alain/ng-alain (🟊 3103)
 - https://github.com/buttercup/buttercup-desktop (🟊 2874)
 - https://github.com/mifi/lossless-cut (🟊 2442)
 - https://github.com/jcc/blog (🟊 2409)
 - https://github.com/gilbitron/Raneto (🟊 2026)
 - https://github.com/Vuedo/vuedo (🟊 1981)
 - https://github.com/ladjs/lad (🟊 1608)
 - https://github.com/cretueusebiu/laravel-vue-spa (🟊 1472)
 - https://github.com/rodrigo-brito/gocity (🟊 1389)
 - https://github.com/snibox/snibox (🟊 986)
 - https://github.com/HDInnovations/UNIT3D (🟊 790)
 - https://github.com/SharePoint/sp-dev-fx-webparts (🟊 777)
 - https://github.com/brunofacca/zen-rails-base-app (🟊 608)
 - https://github.com/LaravelRUS/SleepingOwlAdmin (🟊 560)
 - https://github.com/fy0/Icarus (🟊 557)
 - https://github.com/Urigo/graphql-modules (🟊 536)
 - https://github.com/holidaypirates/nucleus (🟊 476)
 - https://github.com/kevinpapst/kimai2 (🟊 450)
 - https://github.com/natsu90/dial2verify-twilio (🟊 430)
 - https://github.com/cretueusebiu/laravel-nuxt (🟊 411)
 - https://github.com/ng-alain/delon (🟊 403)
 - https://github.com/codebuddies/codebuddies (🟊 403)
 - https://github.com/protonmail-desktop/application (🟊 387)
 - https://github.com/poanetwork/token-wizard (🟊 355)
 - https://github.com/sweetalert2/ngx-sweetalert2 (🟊 353)
 - https://github.com/tchiotludo/kafkahq (🟊 339)
 - https://github.com/Suwings/MCSManager (🟊 281)
 - https://github.com/codeitlikemiley/vuetified (🟊 279)
 - https://github.com/facebookincubator/magma (🟊 276)
 - https://github.com/apache/incubator-spot (🟊 275)
 - https://github.com/wanglian/workbase-server (🟊 262)
 - https://github.com/rogeraabbccdd/Fadacai-Generator (🟊 260)
 - https://github.com/adr1enbe4udou1n/laravel-boilerplate (🟊 235)
 - https://github.com/printempw/blessing-skin-server (🟊 232)
 - https://github.com/FlowCrypt/flowcrypt-browser (🟊 230)
 - https://github.com/globeandmail/chart-tool (🟊 228)
 - https://github.com/hrshadhin/school-management-system (🟊 225)
 - https://github.com/avil13/vue-sweetalert2 (🟊 219)
 - https://github.com/mroote/factorio-server-manager (🟊 217)
 - https://github.com/duo-labs/isthislegit (🟊 213)
 - https://github.com/habitlab/habitlab (🟊 212)
 - https://github.com/AiursoftWeb/Kahla.App (🟊 212)
 - https://github.com/getspooky/laravelDash (🟊 204)
 - https://github.com/Hujjat/laravStart (🟊 199)
 - https://github.com/zhuowenli/vue-clipboards (🟊 180)
 - https://github.com/orgmanager/orgmanager (🟊 172)
 - https://github.com/skycoin/skywire (🟊 168)
 - https://github.com/rdehnhardt/skeleton (🟊 160)
 - https://github.com/nodebeats/nodebeats (🟊 159)
 - https://github.com/JKHeadley/appy (🟊 159)
 - https://github.com/chrisleekr/yii2-angular-boilerplate (🟊 148)
 - https://github.com/popcodeorg/popcode (🟊 135)
 - https://github.com/gitcoinco/codefund (🟊 135)
 - https://github.com/sweetalert2/sweetalert2-react-content (🟊 129)
 - https://github.com/bknds/ng-pi-admin (🟊 117)
 - https://github.com/bigcommerce/cornerstone (🟊 116)
 - https://github.com/Zaid-Ajaj/tabula-rasa (🟊 114)
 - https://github.com/herusdianto/laravel-vue-crud (🟊 109)
 - https://github.com/obiwankenoobi/react-express-boilerplate (🟊 109)
 - https://github.com/alirizaadiyahsi/Nucleus (🟊 101)

Such a small plugin is helping to build UIs for so many projects. Isn't this amazing?

**Comment by varunsridharan** [comment]
This library used by **WPOnion** A Light Weight WordPress Development Kit

## So what is WPOnion , exactly?
WPOnion is a simple yet powerful framework that helps developers build custom meta boxes and custom fields in WordPress fast and easily.

The framework lets you define custom meta boxes and custom fields via arrays and handles everything behind the scene automatically. It has a wide range of field types, field settings and supports not only post meta but also term meta, user meta, comment meta, settings pages and custom tables.

## What do you like most about SweetAlert2, what could be done better?
Using SweetAlert2 in my project has really made easy in shows quick popup. for example showing ajax request status. and more 

See Here on How SweetAlert2 is used other than showing ajax response popup
https://vsp.ams3.cdn.digitaloceanspaces.com/sshots/i/2019/Jul/09/1562690440-163.mp4
For sure this really helped me a lot in development.

### what could be done better
Nothing major. but i would be happy if the upcoming version has multiple theme support instead of singleton theme support. 😄 
Other than that i am very happy that i choose the right library to use in my project 😄 😃 

---

This i project is created by a single developer and idea are contributed by @EnterpriseBranding 

https://github.com/wponion/wponion

**Comment by tomholub** [comment]
[![image](https://user-images.githubusercontent.com/6306961/62825994-efdfdd80-bba3-11e9-9355-03da0a8fcf0f.png)](https://flowcrypt.com/)

We added SweetAlert2 because browser alerts were a major pain for our automated testing. A nice side effect is that it greatly improved user experience. SweetAlert2 is one of the best web libraries we used - does exactly what it says, and does it well.

We do [email encryption](https://flowcrypt.com/).

**Comment by amiceli** [comment]
![letsignit](https://www.letsignit.io/wp-content/themes/letsignit/static/img/logo.svg)

I work in Letsignit company, we build : 

> A simple and super effective tool for harmonizing your signatures and transforming them into a powerful communication asset.

We use SweetAlert2 almost in all our projects small and large projects.
Because it's easy to customize and fully support Typescript.
And our designers like sweetalert style ! (Nice work guys !)

Our projects are not open source, however, the website is public : https://letsignit.io

**Comment by cerw** [comment]
![nano_logo_croped](https://user-images.githubusercontent.com/16146/70020990-00401c00-15ca-11ea-8848-e89a2b553b43.png)

We are [Nano Solutions](https://nanosolutions.io/), small tech company in Fremantle, Australia. 

We use SweetAlert2 in most of our projects based on Vue.js. 

> What kind of project? How large? (code base size or team size)

We make PWA App(s) for Surf Life Saving Australia, which is used nationwide by Lifeguards on Beaches! Its build using Laravel + Vue.js, Sweetalert is used as Alert, Prompt, Progress Widget.  Team size: 5

> What do you like most about SweetAlert2, what could be done better?

Loving integration via [vue-sweetalert2](https://www.npmjs.com/package/vue-sweetalert2) , flexibility, new mixin feature! Be nice if we can specify structure of inputOptions.

Thank you for great work 👍

**Comment by epica888** [comment]
![Uploading YOURDOLL_LOGO_JPG-460x302.jpg…]()

We are [YourDoll](https://www.yourdoll.com), sex dolls company in CA, USA.

Our projects are not open source, however, the website is public : [https://www.yourdoll.com](https://www.yourdoll.com)

**Comment by epica888** [comment]
We are [YourDoll](https://www.yourdoll.com), sex dolls company in CA, USA.

Our projects are not open source, however, the website is public : [https://www.yourdoll.com](https://www.yourdoll.com)

**Comment by epica888** [comment]
![YOURDOLL_LOGO_JPG-302x302](https://user-images.githubusercontent.com/59558940/71815872-ca57f100-30bb-11ea-96bd-9c75cf1f287f.jpg)


We are [YourDoll](https://www.yourdoll.com), sex dolls company in CA, USA.

Our projects are not open source, however, the website is public : [https://www.yourdoll.com](https://www.yourdoll.com)

**Comment by lofcz** [comment]
![lclogotransblack (1)](https://user-images.githubusercontent.com/10260230/72690056-a1524a00-3b18-11ea-9ee7-731e58a871be.png)

We are [LanCraft](https://www.lancraft.cz/), competitive e-sports tournaments provider and gamers oriented social network, located in Czechia, founded in 2003.

SweetAlert has been our popup solution since the major website rework in 2018 and we are very grateful for this amazing library. **Thanks a million Limonte!** ❤️ 

https://www.lancraft.cz/

**Comment by nainardev** [comment]
## *Ministry of Road Transport, India*

**Description:** We allow citizens to pay fine online for traffic violations

**Team Size:** Medium

**Feedback:** Reduced bundle size. We serve low speed regions so size is important

[https://echallan.parivahan.gov.in](https://echallan.parivahan.gov.in/index/accused-challan)

**Comment by tomas-wrobel** [comment]
Me! I use SweetAlert2! I think, your library is EXCELLENT:
* more themes
* timer option
* show loading option
* user can select html input type, `"select" & "textarea"` include (`<select>` and `<textarea>` are another HTML tags)
* user can customize input (placeholder, value and any other attribute)
* icons (error, success, info, warning, question) – also customizable (html)
* pop-up also can contain header, text and footer
Built-in pop-ups: for noobs
SweetAlert2 pop-ups: for professionals

Questions:
1. Will newer versions support multiple input?
2. Where can I download non minified version?

**Comment by tomas-wrobel** [comment]
> ![lclogotransblack (1)](https://user-images.githubusercontent.com/10260230/72690056-a1524a00-3b18-11ea-9ee7-731e58a871be.png)
> 
> We are [LanCraft](https://www.lancraft.cz/), competitive e-sports tournaments provider and gamers oriented social network, located in Czechia, founded in 2003.
> 
> SweetAlert has been our popup solution since the major website rework in 2018 and we are very grateful for this amazing library. **Thanks a million Limonte!** ❤️
> 
> https://www.lancraft.cz/

Are you Czechs? I am also Czech.

**Comment by Dreller** [comment]
I use it for my backend administration console !  Not a big website but I really appreciate how simple and easy Sweet Alert 2 is!!  Thank you for your work!

**Comment by MirzayevFarid** [comment]
- We’re using SweetAlert at [Radity](https://radity.com/)

- ![logo-midnight@3x](https://user-images.githubusercontent.com/29518613/91811146-173a9a00-ec40-11ea-9d20-981cfcf59877.png)

- https://radity.com
- Radity develops digital products and build web and mobile applications (20 Team members)

Thanks for such an amazing work!

**Comment by tolunayakbulut** [comment]
We use SweetAlert at [Global CTO Forum](https://www.globalctoforum.org)

The Global CTO Forum (GCF) is a global independent organisation for Technology leaders and executives including CTOs, CIOs and Architects around the globe to come together and help its members succeed as well as give back to the society.

![global-cto-forum](https://user-images.githubusercontent.com/31761883/101293064-57537f00-3824-11eb-87d0-18e5857c9375.png)

**Comment by miroslavpejic85** [comment]
#mirotalak

`Mirotalk` is a `open source` project, that allow you to do video calls, chat, screen sharing and many more. Powered by `WebRTC` entirely browser based. Simple, Secure & Fast.

https://github.com/miroslavpejic85/mirotalk

IMHO `sweetalert2` it's ease to configure, and is one of the `best solution` for `alerts`.

Many thanks to @limonte, keep it up! ❤️

**Comment by martinmorenoc** [comment]
![](https://github.com/martinmorenoc/mr-meet/blob/master/public/images/128.png?raw=true)

I use SweetAlert at Mr Meet.

Mr Meet is an open google chrome extension that adds new functionalities to Google Meet.

https://github.com/martinmorenoc/mr-meet

**Comment by afkvido** [comment]
<h1 align=center>
ProdigyPNP
&nbsp;&nbsp;

<img src="https://user-images.githubusercontent.com/69060894/185815523-6d6e37a7-669c-42d8-bbc6-48c9fcd9a223.png" width=100 height=100>

</h1>


@ProdigyPNP is an organization dedicated to hacking Prodigy, the math game. ProdigyPNP uses SweetAlert2 to well, make nice alerts and inputs in the GUI.

**Comment by LeTraceurSnork** [comment]
Hopefully, nobody anymore now

**Comment by getthit** [comment]
![WbX3g7jH_400x400 (1)](https://user-images.githubusercontent.com/104521729/209474311-df6e92fc-486c-47a7-98cf-bb2cc959f240.jpg)

At [Getthit](https://www.getthit.com/get-organic-website-traffic), we use SweetAlert.

SweetAlert has been our popup solution for over a year, and we are quite appreciative for this incredible package.

We offer completely free traffic to websites and blogs.

Thank you @limonte team.
