### ISSUE TITLE
Can we show Loader without on confirm through the thml directly?

### ISSUE THREAD

**Issue by Estevete** [sweetalert2/sweetalert2#1657]
I want to show the loading spinner just when the alert is displayed, without clicking the confirm button. I want to do it using html only. I can make it through typescript, with `Swal.showLoading()` function. The only approximately thing we can do with html is `showLoaderOnConfirm=true` , which shows a loading spinner after we click the confirm button. Is there any other way doing it from the html?

Thanks for everything

**Comment by limonte** [comment]
StackOverflow is the right place for such kind of questions, I can see that you already asked there :+1:
