### ISSUE TITLE
Toast styling issue with confirm button

### ISSUE THREAD

**Issue by KevinBatdorf** [sweetalert2/sweetalert2#1662]
## Current behavior

<img width="549" alt="Screen Shot 2019-07-14 at 12 54 51 PM" src="https://user-images.githubusercontent.com/1478421/61180052-36402c00-a63a-11e9-93b4-d36e5e1d0edb.png">

## Expected behavior

<img width="825" alt="Screen Shot 2019-07-14 at 12 54 36 PM" src="https://user-images.githubusercontent.com/1478421/61180054-435d1b00-a63a-11e9-935f-7669d16d57e5.png">

## Live demo 

https://glitch.com/~imported-chanter-1
---

Works as expected as far as I can tell with the `width: auto` added

**Comment by limonte** [comment]
Thank you @KevinBatdorf for reporting!

**Comment by jongbonga** [comment]
![localhost_8200_](https://user-images.githubusercontent.com/12111716/108069955-a01d8480-706c-11eb-91d8-6fda9c82a761.png)
`width: '100%'` doesn't apply to `swal2-container`

I'm not sure if this should be a new issue or it's fine to comment here

**Comment by limonte** [comment]
> ![localhost_8200_](https://user-images.githubusercontent.com/12111716/108069955-a01d8480-706c-11eb-91d8-6fda9c82a761.png)
> `width: '100%'` doesn't apply to `swal2-container`
> 
> I'm not sure if this should be a new issue or it's fine to comment here

Please report the new issue. Thanks!
