### ISSUE TITLE
Request: Provide option to change icon close modal

### ISSUE THREAD

**Issue by manmath** [sweetalert2/sweetalert2#1663]
![swal-option-to-chage-close-icon](https://user-images.githubusercontent.com/2101163/61194392-524fd600-a6eb-11e9-80ce-194f3872cd91.png)

UI/UX might design a fancy close icon on top-right or top-left in svg or png format. Sometimes, we would need to replace the default icon with any type of font icon (fontawesome, ...). Real example:

![new-svg-close-icon](https://user-images.githubusercontent.com/2101163/61194518-208b3f00-a6ec-11e9-983f-2b647768867b.gif)

I suggest to add one more option named as `closeIcon` or `closeIconPath` or `closeIconHtml` to allow developer override the default icon with HTML code. For example:

`<i class="fas fa-times"></i>` or `<i class="icon icon-close-circle"></i>` or `<svg>...</svg>`

Currently, I used the `html` as the workaround to override the close icon. However, it is not such a nice code because we have to write some codes in `onBeforeOpen` function.

**Comment by limonte** [comment]
@manmath thank you for the nice feature-request, starting from `v8.14.0` you can customize the close button:

```js
Swal.fire({
  ...
  closeButtonHtml: '<i class="fas fa-times"></i>'
})
```

**Comment by manmath** [comment]
@limonte Thanks you very much. Appreciate your valuable time for this helpful release.
