### ISSUE TITLE
Uncaught ReferenceError: module is not defined when importing polyfill script

### ISSUE THREAD

**Issue by dytra** [sweetalert2/sweetalert2#1669]
## Current behavior

Hi, I'm using sweet alert 2 in my project
I use plain javascript
I imported the library like this

```html
<script src="sweetalert2.all.min.js"></script>
```

It just works fine in my browser.
But I realized, that sweet alert 2 is a promise based library so I had to polyfil it.
So I imported the polyfill script just like in the documentation

```html
<script src="sweetalert2.all.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
```

But I got this error in my console

```javascript
index.js:274 Uncaught ReferenceError: module is not defined
    at index.js:274
```

The library works fine, but I'm just wondering if this error cause the polyfill script doesn't work so the older browser can't use the Promise feature that this library use

## Expected behavior

No errors, works fine for older browsers

## Live demo 

https://jsfiddle.net/dytra/Lep7rdfw/2/#save

---

Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:
- PayPal: https://www.paypal.me/limonte
- Bitcoin: `12BxefvPMtHePgfPRDL1SaZYSG4GwQmWoP`
- Ether: `0x36e2b10666e2c0dc343901895ba3697b5d3214d1`
- Bitcoin Cash: `qqxs402qszgwuue00gwxw996lzhpa8up2unqm0y46g`
- Stellar: `GBRS5KGFJO4OBUGW3TRQBIVXTM5YDS53DOSHGA3LKVE2YXKVKNVDONBP`

**Comment by gverni** [comment]
@dytra you are importing the wrong file from the polyfill. As per the README, you need to use: 

```html
<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.js"></script>
```

**Comment by dytra** [comment]
Thanks , it works 👍

**Comment by ugurkaragoz** [comment]
Thanks. 👍

**Comment by josiahking** [comment]
This works. I think the doc has to be updated with this new solution.

**Comment by Abel7x** [comment]
This still happening
