### ISSUE TITLE
Missing closeButtonHtml option

### ISSUE THREAD

**Issue by jameset1024** [sweetalert2/sweetalert2#1671]
## Current behavior

In the documentation there is an option closeButtonHtml that should allow you to replace the standard button text with your own. However, when looking through the code base that option is not implemented.

## Expected behavior

Is there any plan to add this option back to the library?

**Comment by gverni** [comment]
Hi @jameset1024 that feature is released in [v8.14.0](https://github.com/sweetalert2/sweetalert2/releases/tag/v8.14.0)
