### ISSUE TITLE
Action buttons are not centred in 8.14.1

### ISSUE THREAD

**Issue by gn-dframe** [sweetalert2/sweetalert2#1694]
Today's 8.14.1 release appears to have broken the swal2-actions styling. `display: flex` is no longer applied to the element, so buttons are now aligned to the left.

**Comment by limonte** [comment]
Thanks for reporting @gn-dframe and apologies about this issue!

Fixed in https://github.com/sweetalert2/sweetalert2/releases/tag/v8.15.0
