### ISSUE TITLE
Issue using showConfirmButton with showLoading

### ISSUE THREAD

**Issue by Daniel4Digital** [sweetalert2/sweetalert2#1696]
## Current behavior

As we can see on the image below, the buttons are showing:
![Image of Current behavior](https://i.imgur.com/kO8hx1U.png)

## Expected behavior

I was expecting this result:
![Image of Expected behavior](https://i.imgur.com/muafqIg.png)

## Live demo

You can see here a live demo: https://jsfiddle.net/57ere34a/
Basically with showConfirmButton: false, this bug rises up. If I delete that line all is good. The strange thing is that this wasn't happening and last friday, from sudden, it begun to happen. Couldnt figure out why yet, maybe you guys have some idea.

best regards

**Comment by limonte** [comment]
Live demo isn't matching screenshots, there's nothing about loader in the provided live demo.

**Comment by limonte** [comment]
Please provide the correct live demo.

**Comment by Leinad4Mind** [comment]
You're right, I forgot to save, sorry about that: https://jsfiddle.net/50g4p98e/

**Comment by Daniel4Digital** [comment]
You're right, I forgot to save, sorry about that: https://jsfiddle.net/50g4p98e/
