### ISSUE TITLE
Toastr onClick

### ISSUE THREAD

**Issue by demirmusa** [sweetalert2/sweetalert2#1700]
I am using sweetalert toastr. When user click to toastr I want to run some function. But i could not find any options like onClick.
What i want is: 
```javascript
const Toast = Swal.mixin({
  toast: true,
  position: 'top-end',
  showConfirmButton: false,
  timer: 3000,
  onClick: function () { //i want to detect tostr click with something like that.
      //do something.
  }
});
Toast.fire({
  type: 'success',
  title: 'Signed in successfully'
})
```

Do you have any options to it ?

--------
I made some research and as I understand you dont trigger any click function cames from options.

https://github.com/sweetalert2/sweetalert2/blob/6a3c75937727845d917f44589e63cd91702c4607/src/instanceMethods/popup-click-handler.js#L21-L31

Is there any option to detect onClick ?

**Comment by demirmusa** [comment]
Ok i found solution 
```javascript
.then((result) => {
  if ( result.dismiss === Swal.DismissReason.close) {
   //do something
  }
```
So, it is not an issue

**Comment by limonte** [comment]
You can also do something like

```js
onOpen: (toast) => {
  toast.addEventListener('click', () => {
    ... 
  })
}
```

**Comment by demirmusa** [comment]
Thank you so much @limonte. Actually, that's what I was looking for. 👍
