### ISSUE TITLE
Ability to add radio input icons

### ISSUE THREAD

**Issue by kwagdy** [sweetalert2/sweetalert2#1701]
## New feature motivation

Would be nice when representing radio inputs to user to add icons for each option, for example from font awesome. Maybe ability to add custom classes or add another inline span element.

## New feature implementation

Example:
```
swal({
      title: 'Payment methods',
      input: 'radio',
      inputOptions:{
        'credit_card': 'Credit Card',
        'cash': 'Cash on delivery',
      },
      //New section
      inputIcons:{
        'credit_card': 'fa fa-credit-card',
        'cash':'fa fa-money',
      },
      inputValidator: function(value){
        if (!value) {
          return 'Please choose an option first!',
        }
      },
})
```
![image](https://user-images.githubusercontent.com/15840617/62793571-23eace00-bad2-11e9-867f-0601dd99edb0.png)

I know in some cases one can use **html** and **preConfirm**, but I believe you lose a bit of the nice inherited features of supported inputs. Example the embedded input validator.

**Comment by limonte** [comment]
Just use HTML in `inputOptions`:

```js
inputOptions:{
  'credit_card': '<i class="fa fa-credit-card"></i> Credit Card',
  'cash': '<i class="fa fa-money"></i> Cash on delivery',
},
```

**Comment by kwagdy** [comment]
That's awesome, thank you :D
