### ISSUE TITLE
SweetAlert2 - Start with showLoading () and close after executing a function

### ISSUE THREAD

**Issue by polianomartini** [sweetalert2/sweetalert2#1703]
I need to open SweetAlert with a loading, execute a JS function "myFunc()" and close SweetAlert.

I invoke SweetAlert with a loading:

```
Swal.fire ({
   title: 'Wait ...',
   onBeforeOpen: () => {
     Swal.showLoading ()
   }
})
```

Where should I put myFunc () in the code?

**Comment by limonte** [comment]
Please post your question to StackOverflow: https://stackoverflow.com/questions/ask
Make sure to add the `sweetalert2` tag to the question.

Thank you.

**Comment by polianomartini** [comment]
Ok!

[https://stackoverflow.com/questions/57436230/sweetalert2-start-with-showloading-and-close-after-executing-a-function](url)

**Comment by AnNajib** [comment]
iit doesnt found

**Comment by mhmdeve** [comment]
Swal.fire({
    title: "Title",
    allowOutsideClick: false,
    willOpen: () => {
        Swal.showLoading();
    },
    didOpen: () => {
        // Call your function here
        myFunction();
    },
    didClose: () => {
        Swal.hideLoading();
    }
});

function myFunction() {
    // Your function logic here
    console.log("Dialog has opened");
}
