### ISSUE TITLE
Overflow with many inputOptions for radio input

### ISSUE THREAD

**Issue by singpolyma** [sweetalert2/sweetalert2#1710]
## Current behavior

Sending many inputOptions with input set to `radio` causes overflow off both sides of the dialog

## Expected behavior

The radio buttons would wrap or the dialog would grow to accommodate them.

## Live demo

https://ahead-paranthodon.glitch.me

**Comment by limonte** [comment]
```css
.my-input {
  flex-direction: column;
}
```

```js
Swal.fire({
  ...
  customClass: {
    input: 'my-input'
  }
})
```

https://chlorinated-panda.glitch.me/
