### ISSUE TITLE
Does not open with dark background in Chrome

### ISSUE THREAD

**Issue by polianomartini** [sweetalert2/sweetalert2#1714]
I made the call:
```javascript
Swal.fire({
  title: 'Wait ...',
  onBeforeOpen: () => {
    parent.Swal.showLoading();
  },
  onOpen: () => {
    myFunction();
    parent.Swal.close();
  }
})
```
My idea is to show loading while processing myFunction (), but the SweetAlert window doesn't have a dark background when opening in Chrome.

I attached a demo video:
[demo.zip](https://github.com/sweetalert2/sweetalert2/files/3518043/demo.zip)

**Comment by limonte** [comment]
Please follow the issue-report template when reporting.

> My idea is to show loading while processing myFunction (),

This would be something like

```js
Swal.fire('Wait ...')
Swal.showLoading()
myFunction()
Swal.close()
```
