### ISSUE TITLE
Open cascading Toast

### ISSUE THREAD

**Issue by polianomartini** [sweetalert2/sweetalert2#1716]
It would be interesting for the notification window (Toast) to have a property that opens more than one cascading message. Currently in SweetAlert2 one notification overlaps another.

**Comment by limonte** [comment]
Duplicate of #808

**Comment by gverni** [comment]
@polianomartini for your reference you can find an example of how to implement a series of toasts [here](https://sweetalert2.github.io/sweetalert2-examples/parameters/toast-sequence/).

**Comment by polianomartini** [comment]
@gverni  I would like it to look like this, like lib AlertifyJS:

![example_notification](https://user-images.githubusercontent.com/13044849/63467036-ede70b80-c43a-11e9-9337-7e32fc6f56d5.png)


But @limonte replied that it's not currently possible.

**Comment by gverni** [comment]
Got it now! Yes that's not possible because Sweetalert2 is designed to have always only one modal / toast displayed on screen.

**Comment by polianomartini** [comment]
@gverni, is a feather! It would be a very interesting feature if it had. Thx!
