### ISSUE TITLE
Keep consistency in modal backdrop

### ISSUE THREAD

**Issue by lnneth** [sweetalert2/sweetalert2#1717]
I think it'd be nice if you could configure it so that if a modal is already being displayed, instead of redrawing the backdrop (that makes it look like its flickering), just keep it
Preferably just the backdrop only, the animation of the new modals entering is fine, and I specifically mention modals b/c of toasts

**Comment by gverni** [comment]
@lnneth I see what you mean, but how would you implement that? I think your assumption here is that you can `fire` a new modal when the previous one is still shown. Technically this is not what's happening. You always need to _resolve_ a modal before opening a new one. Resolving a modal implies that you are disposing it (hence you remove the backdrop). The modal doesn't have any way of detecting that another modal is about to open and it needs to keep the backdrop on. FYI< this is where we remove the backdrop, and as you can see is one of the last operations: 

https://github.com/sweetalert2/sweetalert2/blob/88d7055ae1be2c1853a4cb46cee947919da9194f/src/instanceMethods/close.js#L25

Potentially this can be achieved adding an argument to keep the backdrop even after the modal closes and leaving the responsibility to the developer, but before going down this path, I'd like @limonte to pitch in on this idea.

As an alternative @lnneth, you can try putting your own backdrop before showing the modal and removing it on the last modal (I haven't tried that)
