### ISSUE TITLE
Keep showing loader after preConfirm returned false

### ISSUE THREAD

**Issue by harawata** [sweetalert2/sweetalert2#1718]
Here is what I am trying to achieve.

1. When 'confirm' is clicked, displays loader and sends a command to a device while keeping the dialog open.
2. Eventually, the device calls another already-registered callback function and this function ...
   1. closes the dialog if the command was successful.
   2. hides the loader and waits for a user action if the command was not successful.

Currently, the loader is hidden when `false` is returned from `preConfirm`.
I tried both setting `showLoaderOnConfirm: true` and calling `showLoading()` in `preConfirm`.
https://jsfiddle.net/gohey20t/

**Comment by limonte** [comment]
Please follow the issue-report template. Or, if it's more a question than an issue-report, use StackOverflow: http://stackoverflow.com/questions/ask

**Comment by harawata** [comment]
Well, this was actually a feature request and I wrote the only required section 'New feature motivation'.
