### ISSUE TITLE
New onUpdate or onRender lifecycle hooks

### ISSUE THREAD

**Issue by toverux** [sweetalert2/sweetalert2#1728]
## New feature motivation

This is needed for [Ngx-SweetAlert2 Next](https://github.com/sweetalert2/ngx-sweetalert2/tree/next) to reinstall the [*swal partials*](https://github.com/sweetalert2/ngx-sweetalert2/tree/next#swalpartialdirective) (doc not up to date) after a modal has been re-rendered (ie. after a call to `Swal.update()`).
Indeed, SweetAlert2 erases the content set by the Angular integration, and the latter has to be aware of that to reinject the swal partials into the modal's DOM, all of that synchronously so the content doesn't blinks.

Previously, neither the Angular integration or SweetAlert2 supported updates of the modal options while the modal was shown, so the use case didn't exist.

After some research, I managed to support updates with both `Swal.update()` and swal partials running at the same time. For this, I needed to [mimick an `onUpdate` hook](https://github.com/sweetalert2/ngx-sweetalert2/blob/next/projects/ngx-sweetalert2/src/lib/swal.component.ts#L331), called after I call `Swal.update()`.
This works great, but it feels like a workaround (it _is_ one) and I think that a new hook could benefit to all users that need to perform changes in the modal DOM after render.

## New feature description

We currently have 4 lifecycle hooks `onBeforeOpen`, `onOpen`, `onClose`, `onAfterClose`, I suggest to add a new one, either :
- `onUpdate`: calls back when `Swal.update()` has been called and **after** the modal DOM has been updated.
- `onRender`: more generic, it calls back each time the modal DOM has been updated, ie. when the modal is `fire()`ed or `update()`ed.

Both would, like the other hooks, pass the modal main DOM element as the first argument.
Like the other hooks, it also needs to be synchronous.

**Comment by limonte** [comment]
Yay! Great news about the next version of Ngx-SweetAlert2! Thank you for keeping it great @toverux!

I'm fine with any suggested option, would you mind to submit a PR with the hook you feel is better?
