### ISSUE TITLE
Property inputClass, sweetalert2 v7.30.0, doesn't apply on select

### ISSUE THREAD

**Issue by nicolomonili** [sweetalert2/sweetalert2#1731]
Use the property **inputClass** to add a custom class on the **select**

## Current behavior

`<select class="swal2-select" style="display: flex;">....</select>` (custom class is not add, only on the select)

![image](https://user-images.githubusercontent.com/2778813/64332043-2ad30680-cfd4-11e9-8464-be980a38f46d.png)

## Expected behavior

`<select class="swal2-select MYCUSTOMCLASS" style="display: flex;">....</select>`

## Live demo
https://jsfiddle.net/5c4tzhrm/

The JSFIDDLE add the property correctly so i know it might not help, but maybe someone has already had this kind of problem.. It's an old project where i can't upgrade sweetalert.

**Comment by limonte** [comment]
Please upgrade to the latest version and use the `customClass` parameter https://sweetalert2.github.io/#custom-class

**Comment by nicolomonili** [comment]
> It's an old project where i can't upgrade sweetalert.

**Comment by nicolomonili** [comment]
I updated the library to the latest version and used the new property `customClass :  { input : 'form-control' }`.

The problem is the same, my custom class is not added to the select element, but if try with another input type (like email) the custom class (the same class) is added correctly. 

In my css i had properties that modify sweetalert's select, i also removed these properties from the css but nothing changes.

**Comment by nicolomonili** [comment]
Update: the problem seems to be due to another javascript library

**Comment by nicolomonili** [comment]
JSFiddle updated with a real example of the problem (try to remove the library simplebar.min.js)

[JSFIDDLE](https://jsfiddle.net/e4gb9ahp/5/)

**Comment by nicolomonili** [comment]
If i try to comment `HTMLSelectElement:0` in the library **simplebar.min.js**, the problem disappears

**Comment by gverni** [comment]
I don't know what's the problem with your JSFiddle. It works perfectly fine for me on using swal 7.30.0 (see https://coal-double.glitch.me/)

![image](https://user-images.githubusercontent.com/17089396/66046207-30f9cb80-e51d-11e9-8ca3-6fcfe012a065.png)

**Comment by nicolomonili** [comment]
@gverni did you read my latest comments?

**Comment by gverni** [comment]
> @gverni did you read my latest comments?

Sorry, but I'm not going to debug why the other library is messing up with Sweetalert. If you open the developer console on your JSfiddle is pretty clear that Swal is behaving correctly because the class `MYCUSTOMCLASS` is applied to all the inputs. So very likely the other library is removing it from the select tag: 

![image](https://user-images.githubusercontent.com/17089396/66046856-85517b00-e51e-11e9-9b61-f39571f537b4.png)

**Comment by nicolomonili** [comment]
In fact i wrote that the problem is caused by the other library
