### ISSUE TITLE
Add <label> to input

### ISSUE THREAD

**Issue by hajududat** [sweetalert2/sweetalert2#1732]
Hello! 

I've searched and have not found anything that can answer my question. Is it possible to add a label to a SweetAlert input field? Maybe something like 'inputLabel'?

Thanks!
Justin

**Comment by limonte** [comment]
```js
Swal.fire({
  html: '<label for="my-input">Enter your name</label>',
  input: 'text',
  inputAttributes: {
    id: 'my-input'
  }
})
```
