### ISSUE TITLE
Custom Color title

### ISSUE THREAD

**Issue by vando97** [sweetalert2/sweetalert2#1733]
I can't custom color title.
 Toast.fire({
    type: 'success',
    title: mess,
    customClass: {
      title: 'comment-success',
    },
});

and in css file

.comment-success {
     color: white
}

but the result is color: #595959; in style-title

**Comment by limonte** [comment]
Can't reproduce: https://same-eater.glitch.me/
https://glitch.com/edit/#!/same-eater?path=index.html:22:0
