### ISSUE TITLE
Multiple customClass.element sounds not working

### ISSUE THREAD

**Issue by Seaclick** [sweetalert2/sweetalert2#1735]
Hello,

First of all, thanks for this gorgeous and beautiful replacement for Javascript's popup boxes!

## Current behavior
Adding multiple classes tu customClass.cancelButton and others, returning a console error 

> Uncaught (in promise) TypeError: classList.forEach is not a function

## Expected behavior

Applying multiple class to elements (buttons in my case).

## Live demo 

```javascript
swal.fire({
			type: 'info',
			backdrop: false,
			title: 'My title',
			text: 'My text...',
			confirmButtonText: OK',
			buttonsStyling: false,
			customClass: {
				confirmButton: 'btn btn-lg btn-primary'
			}
		});
```

**Comment by limonte** [comment]
Please provide the live demo, the code you've pasted works without any errors on https://sweetalert2.github.io/
