### ISSUE TITLE
possible superfluous arguments

### ISSUE THREAD

**Issue by tomholub** [sweetalert2/sweetalert2#1741]
I ran lgtm.com through our codebase and it noticed SweetAlert2 lib as well, and here's what it found. I don't know if it has merit or not:

![image](https://user-images.githubusercontent.com/6306961/65184410-05e09800-da98-11e9-92ee-170c8da923d0.png)

**Comment by limonte** [comment]
Thanks @tomholub!

LGTM.com is also enabled for this project, but apparently, it's not smart enough to detect superfluous arguments in cases when the definition is in one file and the calls are in another file.

**Comment by tomholub** [comment]
Here it was operating on the built library, that's probably why it noticed.
