### ISSUE TITLE
customClass on buttons doesn't work

### ISSUE THREAD

**Issue by gvnt** [sweetalert2/sweetalert2#1744]
Hello, found a bug on 'customClass' with lastest version (8.17.6)

## Current behavior
When i set : 
```
customClass:{
     confirmButton: 'btn btn-primary'
 }
```
My class  'btn btn-primary' is set behind 'swal2-confirm' : 
`class="swal2-confirm btn btn-primary swal2-styled"`

## Expected behavior
My class 'btn btn-primary' shouldn't need '!important' to work.

**Comment by limonte** [comment]
Expected behavior isn't clean, which CSS propetry needs `!important` in your case?

**Comment by gvnt** [comment]
I will clarify my case, my issue seems to look like this one : #1525 
```
Swal.fire({
            html: html,
            showCloseButton: true,
            showConfirmButton: true,
            closeOnConfirm: false,
            customClass:{
                confirmButton: 'btn btn-primary'
            }
})
```
I got : 
![image](https://user-images.githubusercontent.com/25453472/65304355-b7f38f00-db80-11e9-8bd2-c1e641188532.png)

![image](https://user-images.githubusercontent.com/25453472/65304551-3e0fd580-db81-11e9-9845-e2ff3bbe6d6b.png)

So i need to use !important in my CSS to apply my style : 
![image](https://user-images.githubusercontent.com/25453472/65304651-77e0dc00-db81-11e9-8935-2f78bc5a83ac.png)

![image](https://user-images.githubusercontent.com/25453472/65304639-6ef00a80-db81-11e9-8372-19c79553e37d.png)

**Comment by limonte** [comment]
This is the expected behavior. For buttons, use either `buttonsStyling: false` as per [example](https://sweetalert2.github.io/#dismiss-handle) to disable the default styling or `!important` to override the default styling.
