### ISSUE TITLE
Swal.fire().catch is not a function

### ISSUE THREAD

**Issue by roblav96** [sweetalert2/sweetalert2#1745]
## `sweetalert2@8.17.4`
<img width="814" alt="Screen Shot 2019-09-20 at 2 10 33 PM" src="https://user-images.githubusercontent.com/1457327/65349641-f5244500-dbb1-11e9-9469-0a202d745b9d.png">
Every `Promise` method except catch is defined.

**Comment by zenflow** [comment]
Culprit: https://github.com/sweetalert2/sweetalert2/commit/fc70cf908d1e133fed638eaf121e3ad5ec588989

PRs welcome!

**Comment by limonte** [comment]
Promise returned by `Swal.fire()` will never be rejected, so it doesn't make sense to have `catch()` implemented.

As per docs https://sweetalert2.github.io/#handling-dismissals

> When an alert is dismissed by the user, the Promise returned by `Swal.fire()` will be resolved with an object { dismiss: reason } documenting the reason it was dismissed

---

@roblav96 why do you need `.catch()`?
