### ISSUE TITLE
Mystery Checkboxes After Update

### ISSUE THREAD

**Issue by HDVinnie** [sweetalert2/sweetalert2#1747]
## Current behavior
I updated from `"sweetalert2": "^8.13.5"` to ` "sweetalert2": "^8.17.6"` and now in my toasts and alerts I have these checkboxes. Any ideas?

## Expected behavior

To not have random checkboxes.

## Live demo

Here is where a demo can be seen. 
https://unit3d.org/torrents/the-institute.83

Username and Pass is UNIT3D. You can see both in the toast when clicking quick comment or making a manual comment with no input for the error popup. 

The codebase:
https://github.com/HDInnovations/UNIT3D

Sweetalert is installed via npm and compiled with Laravel Mix. 

The code is simple. 
```
        @foreach (['warning', 'success', 'info'] as $key)
        @if (Session::has($key))
            <script nonce="{{ Bepsvpt\SecureHeaders\SecureHeaders::nonce() }}">
              const Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000
              });
              Toast.fire({
                type: '{{ $key }}',
                title: '{{ Session::get($key) }}'
              })
            </script>
        @endif
        @endforeach
```

No custom changes to css or anything. Direct import. Only changed after updating.

Some Pics:
https://imgur.com/a/KQmJ9dw

**Comment by gverni** [comment]
Hi @HDVinnie in your css you are overriding the style of all labels with: 

![image](https://user-images.githubusercontent.com/17089396/65453683-983bbf80-de3b-11e9-9fa7-92690035d9a4.png)

Since you are using `!important` this is overriding the style of the swal2 label for checkbox which should normally be hidden. Any chance you can avoid using the `!important` or make it less generic?

**Comment by HDVinnie** [comment]
Ah! My apologies. I forgot I added that same time I updated. Thanks so much!
