### ISSUE TITLE
New Community Project: Razor.SweetAlert2

### ISSUE THREAD

**Issue by Basaingeal** [sweetalert2/sweetalert2#1749]
## New feature motivation
Microsoft just released .NET Core 3.0, and with it, a new front-end framework called Blazor. I created a Razor Class Library that wraps SweetAlert2 and allows people to use it inside a Blazor application. [Razor.SweetAlert2](https://github.com/Basaingeal/Razor.SweetAlert2)

## New feature description

I wanted to ask to have it listed under the `Related community projects` section in the README.

## New feature implementation

* [Basaingeal/Razor.SweetAlert2](https://github.com/Basaingeal/Razor.SweetAlert2) - Blazor Wrapper

**Comment by zenflow** [comment]
Repo for the documentation website is at https://github.com/sweetalert2/sweetalert2.github.io

**Comment by Basaingeal** [comment]
I didn't see anything for `Related community projects` on the documentation site. Only on the README for this project.

**Comment by zenflow** [comment]
Repo for the README for this project is at https://github.com/sweetalert2/sweetalert2

**Comment by Basaingeal** [comment]
Right. That's why I opened the issue here. Are you saying I should open a PR?

**Comment by limonte** [comment]
@Basaingeal yes, please go ahead with the PR and add the link to https://github.com/sweetalert2/sweetalert2#related-community-projects :tada:
