### ISSUE TITLE
Trying to encapsulate sweetalert2 in my web component

### ISSUE THREAD

**Issue by JulLeuverink** [sweetalert2/sweetalert2#1750]
I work on a Web Component that renders dynamic forms based on a database table or a list (sharepoint list in my case). 

Now I want my Web Component to have a .showModalDialog() function that uses sweetalert2 to render the forms content in a Pop-Up. The sweetalert2.js is referenced inside the ShadowRoot in a script-tag.

In the connectedCallback function of my Web Component neither this.Swal nor this.shadowRoot.Swal nor document.Swal is defined.

Am I missing something?

**Comment by gverni** [comment]
@JulLeuverink it's going to be very difficult to support you without seeing the source code of your app / web page. My advice is to [post your question to StackOverflow](https://stackoverflow.com/questions/ask) making sure to add the `sweetalert2` tag to the question. To increase the chance of getting an answer, provide as many information / source code you can in your questions on StackOverflow.
