### ISSUE TITLE
Missing Information about the Advertising / Sponsor

### ISSUE THREAD

**Issue by muescha** [sweetalert2/sweetalert2#1751]
## Current behavior

- i see advertising in the footer of the examples
- nowhere is this mentioned in the documents
- nowhere is an info that if i have this advertising also injected in my pages if i use this library

## Expected behavior

- if there is an advertising it should be noted in documents
- or no advertising

## Live demo 

goto https://sweetalert2.github.io/#examples

try out different examples

![Bildschirmfoto 2019-09-26 um 16 54 18](https://user-images.githubusercontent.com/184316/65700031-42575980-e07f-11e9-8e1a-e1ddcf74cd51.png)
![Bildschirmfoto 2019-09-26 um 16 54 30](https://user-images.githubusercontent.com/184316/65700038-45eae080-e07f-11e9-8b59-d5f9b869500d.png)

**Comment by gverni** [comment]
@muescha rest assured there are no advertisement in the component itself (feel free to check out the source code in this repo). The advertisement is added manually in the documentation page.

**Comment by muescha** [comment]
i checked the repo and not found any place - so i was more scared about "magic tricks" injecting later ads in my page

then you should do: 
a) it should be documented somewhere that is not there - otherwise you scare people who think they get ads injected
b) remove the ads in footer in the documentation page for the examples

**Comment by limonte** [comment]
Thank you @muescha for your request. Even thought for most of people it's obvious, you're right that we should clearly describe that ads are shown only on the docs page and they are not the part of SweetAlert2's codebase.

What you see on docs page is the part of docs page, proof: https://github.com/sweetalert2/sweetalert2.github.io/blob/master/src/app.js#L186-L192

We do not and will not do something unethical like showing 3rd-party ads for our users.

I added the clarification here: https://github.com/sweetalert2/sweetalert2.github.io/commit/f41d17efdb174b339ed0eb4d68acb176129170d1

![image](https://user-images.githubusercontent.com/6059356/65769808-3205b400-e13d-11e9-8487-1d0df4fea12f.png)

**Comment by muescha** [comment]
thanks for the clearification. 

But it is hard to fidn the explanation at the end of the page.


as i see it is included in every dialog where no `footer:` is defined.

an other suggestion: put the advertising `Swal.mixin` also into the example code snippets, then it is very clear on each example that it is an setup by you:

```javascript
var advertisingNode = $('body > .bsa-cpc')
Swal.mixin({
      footer: advertisingNode
})
```


or 

```javascript
var advertisingNode = $('body > .bsa-cpc')

Swal.fire({
  title: 'Sweet!',
  text: 'Modal with a custom image.',
  imageUrl: 'https://unsplash.it/400/200',
  imageWidth: 400,
  imageHeight: 200,
  imageAlt: 'Custom image',
  animation: false,
  footer: advertisingNode
})
```

**Comment by limonte** [comment]
Thank you for the suggestion, but I think it's too much to have something like that in examples.

First of all, many people have ad-blockers and the issue isn't relevant for them at all.

Secondly, people quite often copy-pasting examples and `footer: advertisingNode` will be counter-productive for them. 

To conclude, it's obvious for the majority of users that no ads will be injected. Based on that, I'm not going to complicate examples for everybody just because some users have some unreasonable fears.

**Comment by muescha** [comment]
or if you put this hint on top above the examples and maybe also a blogpost how you done this ala "How to set default values of Swal" and there are some examples of CSS defaults and the footer defaults ;)

```markdown
[Ads injected](/blog/how-to-set-default-to-all-Swal) into examples are 
only shown on this page, they are not the part of SweetAlert2's 
codebase and you will not have them when using SweetAlert2 
for your projects. [read more...](/blog/how-to-set-default-to-all-Swal)
```
