### ISSUE TITLE
Progress bar for toastr option

### ISSUE THREAD

**Issue by manukieli** [sweetalert2/sweetalert2#1754]
Hi,
Can you add a progress bar to toastr option, like this:
![toastr_progressbar](https://user-images.githubusercontent.com/14294794/65903152-34c20c80-e3bc-11e9-8483-45bb2249efa5.gif)

I'm using your script and other (https://codeseven.github.io/toastr/demo.html) and I would like use only one.

Thank you.

**Comment by limonte** [comment]
Sounds like a nice feature-request, thank you @manukieli!

Proposal: add the `timerProgressBar?: boolean` (`@default false`)

I'll try to implement this during the weekend :+1:

**Comment by manukieli** [comment]
Thank you.

**Comment by limonte** [comment]
@manukieli done, see the example: https://sweetalert2.github.io/#mixin

Also, please check out the v9.0.0 release notes to see breaking changes before upgrading to v9.3.0
