### ISSUE TITLE
Input select with empty value

### ISSUE THREAD

**Issue by polianomartini** [sweetalert2/sweetalert2#1756]
I'm creating an input of type select informing the following options:

`
inputOptions: {
  '': '',
  '1': 'a',
  '2': 'b'
}
`

But the empty value option is being rendered at the end and not at the beginning.

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/66021083-11997900-e4f2-11e9-99f6-23d47065e7da.png)
