### ISSUE TITLE
prevent auto scroll to top in mobile

### ISSUE THREAD

**Issue by chiqui3d** [sweetalert2/sweetalert2#1758]
Every time I show an alert with Swal everything goes top.

 I've tried with CSS as some people have said and it doesn't work
```
html.swal2-shown,
body.swal2-shown{
  overflow-y: hidden !important;
  height: auto!important;
}
```

Is there any way to fix this?

**Comment by limonte** [comment]
It's impossible to help with your case without any live demo. Please follow the issue template when reporting issues.
