### ISSUE TITLE
The requested module 'sweetalert2/dist/sweetalert2.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by blackstormx** [sweetalert2/sweetalert2#1760]
Seems like version 2 does not provide a default export.
Installed latest version using npm install, as provided on npm.

Just like you provided on npm, I did this:
`import Swal from 'sweetalert2/dist/sweetalert2.js'`

Title is the error I am getting when importing Swal as module. It works if Import it using script tag though. But that's not what I want.

**Comment by limonte** [comment]
Works as expected for me.

Please provide the repo where we can reproduce the issue.

**Comment by blackstormx** [comment]
This was literally all the code.

Does "Works as expected" mean, it doesn't work as module in a webpage without a webpack? Seems like the only way to make it work is importing it as a script. Anyways, thank you for rewieving, and  I hope you will implement this feature.

**Comment by limonte** [comment]
Oops, sorry, misread your report. For ES modules please import from `src` folder.

Live demo with ES modules: https://jsfiddle.net/bhe7vq9d/

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@8/dist/sweetalert2.css">

<script type="module">
  import Swal from 'https://cdn.jsdelivr.net/npm/sweetalert2@8/src/sweetalert2.js'
  Swal.fire('hi')
</script>
```

**Comment by blackstormx** [comment]
Oh thank you more now, would be even nicer if you provided that in npm guide too. Thanks.

**Comment by Ericonaldo** [comment]
But it seems that version 11.x also has this issue?

**Comment by limonte** [comment]
> But it seems that version 11.x also has this issue? @limonte

Nope, v11 is fine.

**Comment by shtalinberg** [comment]
"sweetalert2": "^11.3.8",  issue exists
    WARNING in ../src/components/SweetAlert.js 5:33-37
export 'default' (imported as 'Swal') was not found in 'sweetalert2' (module has no exports)

**Comment by avrevic** [comment]
Yeah looks like it broke the install in the new version.

**Comment by adao789** [comment]
I've already tried the solutions suggested here and other ways to use sweetalert2(v11.6.16) in Rails 7.0.4 (using importmap), but the only way I could make it work was by putting the CDN in the import, but I don't want to work this way, because it gets dependent on another site.
The error I get is does not provide an export named default.
I do not know what else to do.
