### ISSUE TITLE
SUPRESS_SUPPORT doesnt work

### ISSUE THREAD

**Issue by pavelloz** [sweetalert2/sweetalert2#1768]
https://github.com/sweetalert2/sweetalert2/blob/master/bin/postinstall.js#L3

<img width="819" alt="image" src="https://user-images.githubusercontent.com/546845/66567487-937b4900-eb67-11e9-916a-fb0e3f6d4cfa.png">

**Comment by limonte** [comment]
You're missing the `export` keyword which will make the value of an environment variable available to child processes.

```sh
export SUPPRESS_SUPPORT=1; npm i
```

**Comment by pavelloz** [comment]
Turned out i had typos all over the place.
Where i exported i has `SUPPOR` and inline i had `SUPRESS` ;-)
