### ISSUE TITLE
In ionic show a grey background color

### ISSUE THREAD

**Issue by pookdeveloper** [sweetalert2/sweetalert2#1770]
It looks like this.

![image](https://user-images.githubusercontent.com/3384734/66701150-6199ec00-ecf9-11e9-8bc1-f22bf4ea5081.png)

any solution?
Thanks

**Comment by limonte** [comment]
The fisrt step to the solution is following the issue-template :)

![image](https://user-images.githubusercontent.com/6059356/66712368-649de680-eda4-11e9-8b61-bcb510e9c1db.png)
