### ISSUE TITLE
In ionic show a grey background color

### ISSUE THREAD

**Issue by pookdeveloper** [sweetalert2/sweetalert2#1771]
## Current behavior

The modal show with a grey background color:
![image](https://user-images.githubusercontent.com/3384734/66713271-d8da8900-eda8-11e9-8629-537f864a25f0.png)

## Expected behavior
The modal show with a transparent background color:
![image](https://user-images.githubusercontent.com/3384734/66713382-81d5b380-edaa-11e9-9330-0ab71561c5a1.png)

## Live demo

````typescript
import { Component, OnInit } from '@angular/core';

import Swal from 'sweetalert2'


@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage implements OnInit {

  constructor() { }


  ngOnInit() {
  }

  ver() {
    Swal.fire('Hello world!');
  }
}

````

````html
<ion-header>
  <ion-toolbar>
    <ion-title>
      Ionic Blank
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>

  <button (click)="v
[Ionic sweetalert.zip](https://github.com/sweetalert2/sweetalert2/files/3721576/Ionic.sweetalert.zip)
er()"> view sweetalert </button>
  <div class="ion-padding">
    The world is your oyster.
    <p>If you get lost, the <a target="_blank" rel="noopener" href="https://ionicframework.com/docs/">docs</a> will be
      your guide.</p>
  </div>
</ion-content>
````

In glitch it looks gray but a bit transparent
https://glitch.com/edit/#!/join/7a4b0bdc-a426-4dfd-9a72-e78116f3ae94

I add a zip  run inside:
````
npm i 
````
````
ionic serve
````

**Comment by limonte** [comment]
> I add a zip run inside:

So, where is that zip? :)

**Comment by pookdeveloper** [comment]
This is the zip, sorry :)
[Ionic sweetalert.zip](https://github.com/sweetalert2/sweetalert2/files/3721589/Ionic.sweetalert.zip)

**Comment by limonte** [comment]
There's some conflict with the app styles, use `heightAuto: false`

**Comment by pookdeveloper** [comment]
Ok @limonte where I put heightAuto:false ?
Thanks

**Comment by limonte** [comment]
RTFM please :) 
https://sweetalert2.github.io/
