### ISSUE TITLE
error TS8020: JSDoc types can only be used inside documentation comments.

### ISSUE THREAD

**Issue by Tharinduyasarathna27** [sweetalert2/sweetalert2#1773]
node_modules/sweetalert2/sweetalert2.d.ts(361,41): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/sweetalert2/sweetalert2.d.ts(361,50): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/sweetalert2/sweetalert2.d.ts(361,59): error TS8020: JSDoc types can only be used inside documentation comments.

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by Rabiarasheed** [comment]
Were you able to resolve this? @Tharinduyasarathna27

**Comment by Tharinduyasarathna27** [comment]
I changed SweetAlertArrayOptions = [string?, string?, SweetAlertType?] >>to>> SweetAlertArrayOptions = [string, string, SweetAlertType]; in line 361 sweetalert2.d.ts file (in node module folder).It works for me. but I don't know it is a proper solution.

**Comment by jpcorona** [comment]
@Tharinduyasarathna27 Thanks!! This work for me!!!

**Comment by DeepakDhakar** [comment]
> @Rabiarasheed I changed SweetAlertArrayOptions = [string?, string?, SweetAlertType?] >>to>> SweetAlertArrayOptions = [string, string, SweetAlertType]; in line 361 sweetalert2.d.ts file (in node module folder).It works for me. but I don't know it is a proper solution.

yes it workes for me also

**Comment by ClaudioNunes** [comment]
Modify files in node folder does not seem to be a proper solution.
Can  this be solved in a "official version"?

**Comment by limonte** [comment]
It can be solved if anybody will report the issue **properly** as per issue template.

Solving the issue we can't reproduce isn't possible.

**Comment by limonte** [comment]
I added some arrows so whoever will be reporting the issue won't miss it :)

![image](https://user-images.githubusercontent.com/6059356/71289012-acc52080-2374-11ea-92a2-ead8be609808.png)

**Comment by MattHirdler** [comment]
dupe of #1861

**Comment by 01yoon** [comment]
not ? but | null will work

**Comment by YesicaMacias14** [comment]
@Tharinduyasarathna27 it works for me too!!

**Comment by ikiugu** [comment]
Thanks @Tharinduyasarathna27 this works for me as well...it would help if we got a fix for this instead of changing the node_modules folder content

**Comment by surendradev-code** [comment]
Thanks for the help. It work for me.
