### ISSUE TITLE
Ht.swalCloseEventFinishedCallback when closing after a swal update.

### ISSUE THREAD

**Issue by giannisepp** [sweetalert2/sweetalert2#1778]
When closing a Swal.update after a Swal.fire, there is an error triggered
[error: **Ht.swalCloseEventFinishedCallback is not a function**]

## Live demo
      Swal.fire({
            type: "question",
            title: "Are you sure?",
            showCancelButton: true,
            showLoaderOnConfirm: true,
            preConfirm: () => {
                return true;
            }
        }).then((result) => {
            if(result.value){
                Swal.update({
                    type: 'success',
                    title: 'Success!',
                    showConfirmButton : false,
                    showCancelButton  : false,
                });
                setTimeout(function(){ Swal.close();  }, 1000);
            }
        });

In my case, there is no script/process disruption except the console warning.

**Comment by limonte** [comment]
You're trying to update the closed or closing popup, that won't work. Use the `update()` method in `preConfirm` parameter:

```
  Swal.fire({
      type: "question",
      title: "Are you sure?",
      showCancelButton: true,
      showLoaderOnConfirm: true,
      preConfirm: (result) => {
        console.log(result)
        Swal.update({
            type: 'success',
            title: 'Success!',
            showConfirmButton : false,
            showCancelButton  : false,
        });
        setTimeout(function(){ Swal.close();  }, 1000);
        return false;
      }
  })
```

**Comment by giannisepp** [comment]
The preConfirm have a ajax response like: (full script)


    Swal.fire({type: "question",
        title: "Are you sure?",
        showCancelButton: true,
        showLoaderOnConfirm: true,
        preConfirm: () => {
            return $.post($that.attr('href'), null, null, 'json').catch(function() {return false;});
        }
    }).then((result) => {
        if(result.value){
            Swal.update({
                type: 'success',
                title: 'Success!',
                showConfirmButton : false,
                showCancelButton  : false,
            });
            setTimeout(function(){ Swal.close();  }, 1000);
        }
    });

and if there is no Swal.close(). the dialog stays opened.
I might miss something and detach the whole ajax response into preConfirm as suggested.
(the warning is triggered for both scripts provided)
Thank you for your time!
`
