### ISSUE TITLE
SweetAlert shows behind pdf viewer

### ISSUE THREAD

**Issue by ShimaaHussein** [sweetalert2/sweetalert2#1781]
I'm simply using the default Swal function to show success message after code has done processing on the pdf doc.
Here's the swal function
 swal("", msg, "success");

![Uploading image.png…]()

How can i force the alert show on top of the page.

**Comment by Augani** [comment]
> I'm simply using the default Swal function to show success message after code has done processing on the pdf doc.
> Here's the swal function
> swal("", msg, "success");
> 
> 
> 
> How can i force the alert show on top of the page.



customClass: {
  container: 'container-class',
  popup: 'popup-class',
  header: 'header-class',
  title: 'title-class',
  closeButton: 'close-button-class',
  icon: 'icon-class',
  image: 'image-class',
  content: 'content-class',
  input: 'input-class',
  actions: 'actions-class',
  confirmButton: 'confirm-button-class',
  cancelButton: 'cancel-button-class',
  footer: 'footer-class'
}

Use this custom class in the configuration then use css to overwrite the z-index of the alert modal by placing it on top of everything so i suggest giving it a huge value. That will do the trick.

**Comment by gverni** [comment]
@ShimaaHussein, if @Augani suggestion doesn't work, could you share a live example code as requested when opening a bug? 

```
## Current behavior

<!-- Describe how the issue manifests. -->

## Expected behavior

<!-- Describe what the desired behavior would be. -->

## Live demo <!-- !!! THIS SECTION IS REQUIRED !!! -->

<!--
Provide a working example in order for us to be able to reproduce the issue.
ISSUE-REPORTS WITHOUT A LIVE DEMO OR A WORKING EXAMPLE WILL BE CLOSED!
-->
<!--
The live demo template: https://sweetalert2.glitch.me/
Instructions: https://github.com/sweetalert2/sweetalert2/wiki/How-to-provide-live-example-for-issue
-->
```

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by HemanthGali** [comment]
<style type="text/css">
.swal-height {
            min-width: 400px;
            min-height: 300px;
            font-size: 15px;
            z-index: 999999 !important;
        }   
</style>
 <asp:Panel ID="pnlPopup" runat="server" CssClass="modalPopup" Style="display: none;">
        <div class="header">
            <asp:LinkButton runat="server" Text="Close" ID="btnClose" CssClass="pull-right" Style="font-weight: bold; background-color: #119298; color: white; padding-right: 10px; padding-top: 5px; border-top-right-radius: 10px;"></asp:LinkButton>
        </div>
        <div class="body">
            <asp:UpdatePanel runat="server" ID="upnlPdfrender" UpdateMode="Conditional">
                <ContentTemplate>
                    <div id="divContainer" runat="server" style="width: 100%; height: 630px; overflow-x: hidden; overflow-y: hidden;">
                        <iframe id="pdfIframe" src="../../Test.pdf" width="100%" height="95%" runat="server" scrolling="no"></iframe>
                    </div>
                </ContentTemplate>
            </asp:UpdatePanel>
        </div>
        <div style="text-align: center; align-content: center; padding-bottom: 10px;">
            <asp:CheckBox runat="server" ID="chkTC" Text="Terms's and Conditions" TextAlign="Right" ValidationGroup="chkSubmit" />
            <asp:Button runat="server" ID="btnSubmit" Text="Submit" CssClass="btn btn-success" OnClick="btnSubmit_Click" OnClientClick="return checkTC();" ValidationGroup="chkSubmit" />
        </div>
    </asp:Panel>
    <script type="text/javascript" language="javascript">
        function checkTC() {
            var chkbox = document.getElementById('<% =chkTC.ClientID %>');
            if (chkbox.checked != true) {
                Swal.fire({
                    icon: 'warning',
                    title: 'Oops...',
                    text: 'Please agree T&C !',
                    allowOutsideClick: false,
                    customClass: {
                        popup: 'swal-height',
                    }
                })
                return false;
            }
        };
</script>

Please find the above code (its in ASP.NET, maybe you can try in plain HTML)
After loading modal popup, on click on submit button I'm showing a simple alert asking user to "check" T&C.
But it's loading behind modalpopup.

Please help me on this issue @limonte
