### ISSUE TITLE
Eventemitter doesnt work in Swal (Angular)

### ISSUE THREAD

**Issue by lowzijian** [sweetalert2/sweetalert2#1784]
If u break in debug mode, u could actually see it runs the emit function in the child component. The process gets terminated after it without calling the function in the parent component.

eg:
````
async editTag(file) {
   // there is only one element in file.tags array
    let tags = file.tags

    const  res = await swal({
      title: 'Customise tags',
      text : file.fileName,
      input: 'text',
      inputValue: tags[0],
      showCancelButton: true
      confirmButtonText: 'Submit',
    })
     if (res.value){
       this.Tag.emit(file)
    }
}

**Comment by gverni** [comment]
@lowzijian can you provide a live example? Are you using https://github.com/sweetalert2/ngx-sweetalert2 for your angular integration?

**Comment by gverni** [comment]
@lowzijian I'm closing this issue for lack of feed-back. Feel free to reopen to provide more input.
