### ISSUE TITLE
Image and Text ordering in Alerts

### ISSUE THREAD

**Issue by gota1993** [sweetalert2/sweetalert2#1785]
![Capture](https://user-images.githubusercontent.com/38917779/67479714-b5002880-f66f-11e9-9453-40b80e47d565.PNG)

can I order text and image in this alert? For example, image to be first and texts second. It would be great.

**Comment by gverni** [comment]
@gota1993 you can achieve that using the `html` property of SweetAlert2. More info [here](https://sweetalert2.github.io/#configuration). If you need more help, raise a ticket on StackOverflow tagging Sweetalert2 to leverage the community knowledge.

**Comment by limonte** [comment]
Alternatively, you can use `customClass` and `order` CSS properties: https://radial-feast.glitch.me/

```css
.order-1 {
  order: 1;
}
```

```js
Swal.fire({
  customClass: {
    image: 'order-1'
  }
})
```
