### ISSUE TITLE
Sweetalert in fullscreen not scrolling in IOS

### ISSUE THREAD

**Issue by Shivam2498** [sweetalert2/sweetalert2#1788]
## Current behavior
Sweetalert in fullscreen not scrolling in IOS

Sweetalert in fullscreen not scrolling in IOS
## Expected behavior
Sweetalert in fullscreen should have same behaviour for scroll as in android

**Comment by limonte** [comment]
Thanks for reporting, scrolling isn't disabled in Safari on iOS 13.2 indeed.

Seems that https://github.com/sweetalert2/sweetalert2/pull/1596 isn't working anymore

**Comment by Shivam2498** [comment]
How to fix this issue?
I am in middle of a project

**Comment by Shivam2498** [comment]
Still facing issue on it

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by Shivam2498** [comment]
https://codepen.io/ajayeswar/pen/QWWaqzJ

**Comment by Shivam2498** [comment]
A live demo

**Comment by Shivam2498** [comment]
Okay will post it soon
