### ISSUE TITLE
Broken height on sweetalert buttons on Bootstrap site

### ISSUE THREAD

**Issue by lRoberth** [sweetalert2/sweetalert2#1792]
I'm using swal on my site that uses bootstrap (It's a template).
All buttons height seems to be messed up, for some reason.
[This is how it looks when I'm using my CSS](https://i.imgur.com/WFNbTke.png)
[And here when I comment my CSS](https://i.imgur.com/GiKp22l.png)
[Here's my CSS](https://playtech.gq/assets/css/main.css)

Thank you

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by kYasinAblay** [comment]
i have same Problem.
