### ISSUE TITLE
Broken height on sweetalert buttons on Bootstrap site

### ISSUE THREAD

**Issue by lRoberth** [sweetalert2/sweetalert2#1793]
## Current behavior

Buttons height are messed up
[Screenshot](https://i.imgur.com/WFNbTke.png)

## Expected behavior

It should look like this
[Screenshot](https://i.imgur.com/GiKp22l.png)

## Live demo 

[Website](https://playtech.gq/login.php)

---

Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:

- GitHub Sponsors: https://github.com/sponsors/limonte
- PayPal: https://www.paypal.me/limonte
- Bitcoin: `16Z7RvFv7PsV3XzFvchYwPnRfw9KeLTZQJ`
- Ether: `0x192096161eB2273f12b1cB4E31aBB09Bfc03a7F3`
- Bitcoin Cash: `qz28x66hrljtdz3052p8ya3cmkwwva5avy0msz2ej3`
- Stellar: `GDUM4VJZYDNRHBTKUQBOPC374AP6MMMVOJDMSHIPEJPEMBCY4ZHH6NDY`

**Comment by limonte** [comment]
Remove `padding: 10px 24px`.

In future, please do your homework by yourself. https://www.youtube.com/watch?v=x4q86IjJFag
