### ISSUE TITLE
Can't get inputOptions populated dynamically

### ISSUE THREAD

**Issue by sgmartin18** [sweetalert2/sweetalert2#1794]
## Current behavior

I'm returning exactly the correct information from my Ajax call, but when I attempt to populate the Select dropdown in SweetAlert2, I get nothing.  This works hard-coded:
inputOptions: {
    'b297b4bc4f56fe00a4d3650f0310c7ee': 'AcctMgmtTeam',
    'f21298cd4f2e7200a4d3650f0310c735': 'ACRCRApproval',
    '57e02d131b96fbc0ec68db1dcd4bcb36': 'ALTOCloudRelativityTeam'
},

## Live demo 

---

Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:

- GitHub Sponsors: https://github.com/sponsors/limonte
- PayPal: https://www.paypal.me/limonte
- Bitcoin: `16Z7RvFv7PsV3XzFvchYwPnRfw9KeLTZQJ`
- Ether: `0x192096161eB2273f12b1cB4E31aBB09Bfc03a7F3`
- Bitcoin Cash: `qz28x66hrljtdz3052p8ya3cmkwwva5avy0msz2ej3`
- Stellar: `GDUM4VJZYDNRHBTKUQBOPC374AP6MMMVOJDMSHIPEJPEMBCY4ZHH6NDY`

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
