### ISSUE TITLE
Introducing SweetAlert Laravel package

### ISSUE THREAD

**Issue by AmjadIqbal** [sweetalert2/sweetalert2#1802]
Hi,

I have  create a sweetAlert laravel package , which is very simple to use,

Documentation : [https://amjadiqbal.github.io/sweetalert/](https://amjadiqbal.github.io/sweetalert/)

**Why Choose Me?**

- you can call any kind of sweetAlert , toast Notification using only 1 function alert()
- Custom froms support , means you can now make alert box to model boxes.

**Example for Alert Boxes**

alert([
    'Title' => 'Simple Title',
    'Text'  => 'A simple description',
    'type'  => 'success'  // you can add supported type here
])

**Example for Toast Notification**

alert([ 
    'title'    => 'A sample title', 
    'toast'    => 'true',
    'type'     => 'success',
    'position' => 'top-end' // here you can add supported position
]);

**Example for Forms/Model Boxes**

alert([ 
    'title' => 'Login Form', 
    'html'  => (string)View::make('vendor.sweetalert.template.login'), // here you defined the path of the blade file , it can be sign in / signup or any kind of html
    'showCloseButton' => true,
    'allowOutsideClick' =>false
]);

**Does I provide Support**
yes i have added live chat support , you can talk to me on chat if you have any issue.

Documentation : [https://amjadiqbal.github.io/sweetalert/](https://amjadiqbal.github.io/sweetalert/)

**Comment by limonte** [comment]
Thanks @AmjadIqbal for building this plugin and sharing it with us!
