### ISSUE TITLE
Support native "back" buttons on mobile as "cancel" triggers.

### ISSUE THREAD

**Issue by studioramix** [sweetalert2/sweetalert2#1814]
## New feature motivation

Make this lib more mobile friendly

## New feature description

Intuitively, many users that are inside a modal window through their mobile browsers, click the "back" button on the device, expecting it to close the modal. 
What happens is that it takes them back to the previous page, and this is uncomfortable in many cases.

## New feature implementation

This would probably be done with 1 of 2 approaches:
1. Use URL hashing (like Facebook when you go into an image).
2. use an event that traps the "Back" clicking, prevents the navigation and closes the modal.

**Comment by limonte** [comment]
This sounds like an app-logic, not the logic which should be in the popup plugin.

It'd be too intrusive for such a small plugin to use [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API).

**Comment by studioramix** [comment]
Thanks, I may have not expressed it clearly, the bottom line is that a modal has a few triggers for closing: Esc key, X button, Clicking outside the form etc.
So my request is that also hitting "back" on the browser will trigger the closing of the modal, especially on mobile devices, as the modal takes the space on the entire screen and feels like a "separate" page. at the moment, the intuitive action of clicking "back" - follows the browsers history, while the modal might be an important prompt

**Comment by gverni** [comment]
@studioramix the modal by definition does not add an entry into the browser history. What you are proposing is breaking the browser history logic and it would be conceptually wrong. A modal is a window that overlay on the page and is supposed to capture the attention of the user.
