### ISSUE TITLE
Support transparent background.

### ISSUE THREAD

**Issue by hv0905** [sweetalert2/sweetalert2#1827]
## New feature motivation

As most of major broswers support `backdrop-filter`, it would be nice if sweetalert can support transparent background.

## New feature implementation

I can set `background` and `backdrop-filter` for `.swal2-popup` in css manually, in most case, this works very nice.  
However, when the alert type is `success`, there are a large 🚫 with background color filled at the background (see the image below). It would be nice if swal2 can fix this issue.  
![image](https://user-images.githubusercontent.com/29349119/69437865-068af880-0d7f-11ea-8c57-5af88c46d555.png)

**Comment by limonte** [comment]
Unfortunately, the animated icon is not technically possible with the (semi)transparent popup.

You can always fallback with unanimated icon:

```html
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
```

```css
.custom {
  background: rgba(255,255,255,.8);
  backdrop-filter: blur(2px);
}
```

```js
Swal.fire({
  icon: 'success',
  iconHtml: '<i class="fa fa-check"></i>',
  customClass: {
    popup: 'my-swal'
  },
})
```
