### ISSUE TITLE
Blazor Wrapper

### ISSUE THREAD

**Issue by pjebs** [sweetalert2/sweetalert2#1831]
@limonte 
I was curious if there was a change in policy regarding getting projects listed as "related community projects".

The Blazor Wrapper has 12 stars (and minimal usage) and no tests:

https://github.com/sweetalert2/sweetalert2/issues/1749
https://github.com/sweetalert2/sweetalert2/pull/1764

**Comment by limonte** [comment]
There's no policy about that, it's just me filtering out projects which were made in a couple of hours and will be abandoned by their authors.

I just merged #1737 :rocket:
