### ISSUE TITLE
Progress steps always full

### ISSUE THREAD

**Issue by Basaingeal** [sweetalert2/sweetalert2#1835]
## Current behavior

All progress steps are dark blue all the time.

## Expected behavior

Progress steps should start with the first step dark blue, and the rest light blue, with each step becoming dark blue as it's completed.

## Live demo

This is just the result of hitting `Try it in CodePen` on the `Chaining modals (queue) example` section from https://sweetalert2.github.io (Note, it still works as expected on the documentation site)
https://codepen.io/michael-j-currie/pen/YzPzYGm

**Comment by limonte** [comment]
Thank you for reporting @Basaingeal 

Fixed and added tests to prevent the same issue in future!
