### ISSUE TITLE
hi , Android 4.4 support

### ISSUE THREAD

**Issue by MajidSafari** [sweetalert2/sweetalert2#1840]
Hi ,sweetalert2 not woking in  Android 4.4 support

i thing this for you use" lamda =>"

**Comment by limonte** [comment]
The latest version with Android 4.4 support is https://github.com/sweetalert2/sweetalert2/releases/tag/v8.19.0

Starting from v9.0.0 we dropped Andorid 4.4 support and that change is mentioned in release notes: https://github.com/sweetalert2/sweetalert2/releases/tag/v9.0.0
