### ISSUE TITLE
Typescript definitions for customClass in the fire method

### ISSUE THREAD

**Issue by doug-shontz** [sweetalert2/sweetalert2#1846]
## Current behavior

Typescript in Visual Studio Code displays an error when passing a string value into customClass within the fire method.

## Expected behavior

The types definitions should accept a string value for customClass.

## Live demo 

```
Swal.fire({
                animation: false,
                customClass: "myClassName",
                title: "Hello",
                text: "World"
            });
```

The above code block will generate an error in Visual Studio Code.  I believe this is due to the change in the types file from the December 1 checkin "fix: default values null -> undefined (#1834)".  In that checkin, the type of customClass was changed from "customClass?: string | SweetAlertCustomClass;" to "customClass?: SweetAlertCustomClass;".  Unless I am missing something, the string definition should have stayed?

![image](https://user-images.githubusercontent.com/5281922/70648962-314bcc80-1c1a-11ea-8b6e-d5c92a2123eb.png)

**Comment by limonte** [comment]
Use `customClass` as per documentation: https://sweetalert2.github.io/#custom-class

**Comment by limonte** [comment]
Oops, now I see that the documentation is outdated, sorry about that.

**Comment by doug-shontz** [comment]
No worries!  I just changed my code from 

```customClass: "string"```

to 

```customClass: { popup: "string" }```

and good to go!
