### ISSUE TITLE
use Persian for rtl example

### ISSUE THREAD

**Issue by mahdimehrabi** [sweetalert2/sweetalert2#1847]
Iranians love sweet alert2  
according to [Alexa](https://www.alexa.com/siteinfo/sweetalert2.github.io#trafficstats) most of the visitors of https://sweetalert2.github.io/ are Iranians
I suggest using these codes for RTL example in  https://sweetalert2.github.io/ 
```
Swal.fire({
  title: 'سوییت آلرت فوق العاده نیست ؟',
  icon: 'question',
  iconHtml: '؟',
  confirmButtonText: 'آره فوق العاده است',
  cancelButtonText: 'نه خیلی عالیه',
  showCancelButton: true,
  showCloseButton: true
})
```
translate 
سوییت آلرت فوق العاده نیست ؟
is sweet alert awesome? 

آره فوق العاده است'
yes, it's awesome!

نه خیلی عالیه
no, it's very good!

**Comment by zenflow** [comment]
@mahdimehrabi I think this is a great idea! If you want to make it into a PR @ https://github.com/sweetalert2/sweetalert2.github.io I think it will be accepted, and you will be shown as a contributor :)

**Comment by limonte** [comment]
Here's what Google Analytics shows for the previous month:

![image](https://user-images.githubusercontent.com/6059356/70703226-4e46d500-1cd8-11ea-9306-1b84de7d6a03.png)

(number of sessions) Iran = Egypt + Algeria

And there are more Arabic-speaking countries, Arabic is the 5th most popular language in the world: https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers and it's spoken in 18 countries as major language.

At the end of the day, we're demonstrating technical possibilities there, not language/location preferences :)
So, I'd like to leave the example in Arabic. Thank you for raising this request!

PS. I added the note about the Persian language to docs:

![image](https://user-images.githubusercontent.com/6059356/70703855-974b5900-1cd9-11ea-9076-c4d4d1727316.png)
