### ISSUE TITLE
how to disable click/interaction when backdrop is true

### ISSUE THREAD

**Issue by jongbonga** [sweetalert2/sweetalert2#1848]
Hi 

I'm using Swal2 with ionic 4 and I have these options when I fire my alert 
```
 {
     backdrop: false,
     allowOutsideClick: false
 }
```

the good news is the modal doesn't close when I click outside.
the bad news is that I can still scroll and click on other components behind the alert.

when I set `backdrop:true` the background is blank, which I don't want.

How can I have set the backdrop to transparent and not allow interaction with other components?

**Comment by limonte** [comment]
https://stackoverflow.com/questions/ask

**Comment by jongbonga** [comment]
That’s pretty mean ! 
if we can’t ask questions here, you should remove the ability to do so. 

I wish your personality was as beautiful as this plugin.

Thanks tho :)

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

**Comment by jongbonga** [comment]
I didn’t read that. Sorry
