### ISSUE TITLE
Text behind close button

### ISSUE THREAD

**Issue by irstaskolan** [sweetalert2/sweetalert2#1851]
## Current behavior

When `showCloseButton: true` and the text is long enough the text goes behind the close button.

## Expected behavior

The text should avoid the button.

## Live demo

https://jsfiddle.net/jn4pozu0/1/

**Comment by gverni** [comment]
![image](https://user-images.githubusercontent.com/17089396/71243321-05aa9f80-2308-11ea-8a78-ab57b878806b.png)

@irstaskolan couldn't reproduce this on Chrome 79 om MacOs. Could you tell us which browser/ OS you are using?

**Comment by limonte** [comment]
I can reproduce the issue, but I'm not sure how should we fix it.

@irstaskolan could you please tell us what'd you expect to be a solution?

**Comment by gverni** [comment]
@limonte @irstaskolan  on which browser / OS did you reproduce it? If I can see how it looks like I can make a proposal for fixing it.

**Comment by limonte** [comment]
> @limonte @irstaskolan on which browser / OS did you reproduce it? If I can see how it looks like I can make a proposal for fixing it.

@gverni you can reproduce it in all browsers by using many 1-letter words instead of looooooong words

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/75609516-f61eb280-5b11-11ea-8fd8-46c4bfe64b5a.png)

**Comment by gverni** [comment]
Thanks @limonte! Indeed not nice: 

```javascript
Swal.fire({
  text: 'This is a r e e e e e e e e e e e e e e e e e e e a a l l y l o n g  t e x t  T h i s is a reeeeeeeeeeeeeeeeeeeally long text.',
  showCloseButton: true,
});
```

![image](https://user-images.githubusercontent.com/17089396/75610650-f9fb0680-5b0a-11ea-8ff9-546251f1e0dd.png)

Let me see if i can do something...

**Comment by IsaacHub** [comment]
The default width of the close button is `48px`, 
so,
```
.swal2-popup{
  padding: 1.25em 48px !important;
}
```
will solve this issue.
![Screenshot_63](https://user-images.githubusercontent.com/20126441/82239838-0eef7500-9957-11ea-8973-01cbc40f4598.png)
