### ISSUE TITLE
Using fetch without preConfirm function

### ISSUE THREAD

**Issue by DSBRBrasil** [sweetalert2/sweetalert2#1853]
Hi Guys,
I not found nothing about my question on stack over, so, can you help me?
I'd like no press confirm button to process.

![image](https://user-images.githubusercontent.com/7658282/71289971-5a243e00-234d-11ea-8806-a0d38208a9b0.png)
That's It my intention
![Untitled-1](https://user-images.githubusercontent.com/7658282/71290497-c0f62700-234e-11ea-93fe-2bbb595217da.gif)

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask

**Comment by DSBRBrasil** [comment]
but I not found on stackOver ....

**Comment by gverni** [comment]
@DSBRBrasil if you haven't found the answer in stackoverflow already, you need to create a new question
