### ISSUE TITLE
multiple dynamic chaining alerts

### ISSUE THREAD

**Issue by mbunal** [sweetalert2/sweetalert2#1856]
hi
i want to chained alerts via json. i have this:
```
[{"mes":"there are <strong>2<\/strong> messages.","ico":"info"},{"mes":"message1","ico":"error"},{"mes":"message2","ico":"success"}]
```
i want to generate 3 alerts for this json. i tried but no success. please help.

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
