### ISSUE TITLE
focusConfirm is not working as usual

### ISSUE THREAD

**Issue by Jamyth** [sweetalert2/sweetalert2#1858]
## Current behavior

I am using the latest version of Swal in my react project. (React version: ^16.7.0)
I call Swal.fire() in a componentDidUpdate which it is working, however the confirm button is not initially focused. All I did for now to fix this is using setTimeout function, but is there any other concrete way to do this ?

I tried focusConfirm: true, still not working.

## Expected behavior

Focus the confirm button when shown.

## Live demo 

I cannot reproduce this problem in codepen.

I tried console.log(document.activeElement) 5 second after the Swal.fire fires.
it return body tag.

i also tried put the log function in onOpen, it return the 
'div class="modal fade" id="uploadDocumentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="z-index: 5000; display: none;".../div'

or this

'div role='dialog' tabindex='-1' class='fade modal' style='display:block''''/div''

---

Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:

- GitHub Sponsors: https://github.com/sponsors/limonte
- PayPal: https://www.paypal.me/limonte
- Bitcoin: `16Z7RvFv7PsV3XzFvchYwPnRfw9KeLTZQJ`
- Ether: `0x192096161eB2273f12b1cB4E31aBB09Bfc03a7F3`
- Bitcoin Cash: `qz28x66hrljtdz3052p8ya3cmkwwva5avy0msz2ej3`
- Stellar: `GDUM4VJZYDNRHBTKUQBOPC374AP6MMMVOJDMSHIPEJPEMBCY4ZHH6NDY`

**Comment by limonte** [comment]
> I cannot reproduce this problem in codepen.

In this case, the issue is on the side of your app, we can't help.
