### ISSUE TITLE
Documentation: version 8

### ISSUE THREAD

**Issue by pjebs** [sweetalert2/sweetalert2#1860]
Version 9 (released Nov) has many breaking changes.
It would be good if we can view the version 9 documentation.

**Comment by limonte** [comment]
![Uploading image.png…]()

**Comment by pjebs** [comment]
On my screen, you can't see the theme and version drop down.
I had to zoom out to 80% to see it.

The html template should be adjusted to be able to scroll down.

**Comment by limonte** [comment]
Sorry to hear that, I recommend using a bigger screen for web dev.
