### ISSUE TITLE
error TS8020: JSDoc types can only be used inside documentation comments. with certail versions of `build-angular` (proper repro steps included)...

### ISSUE THREAD

**Issue by mattemoore** [sweetalert2/sweetalert2#1861]
## Current behavior

If you have a dependency in your `package.json` for "@angular-devkit/build-angular": "^0.13.2" you will get a compile error:
```
ERROR in node_modules/sweetalert2/sweetalert2.d.ts(361,41): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/sweetalert2/sweetalert2.d.ts(361,50): error TS8020: JSDoc types can only be used inside documentation comments.
node_modules/sweetalert2/sweetalert2.d.ts(361,59): error TS8020: JSDoc types can only be used inside documentation comments.
```
## Expected behavior

Compiles properly etc. etc.

## Live demo 

The codepen URL results in a 404 so I will try to do my best without a template.

`package.json`:
```
...
"dependencies": {
...
"sweetalert2": "8.14.0",
...
}
"devDependencies": {
...
    "@angular-devkit/build-angular": "^0.13.2",
    "typescript": "^2.9.2"
...
}
```

`app.component.ts`:
```
...
import swal from 'sweetalert2';
....
export class AppComponent {
swal.fire({
          title: 'Foo',
          text: 'Bar',
          type: 'error',
          confirmButtonText: 'Continue',
          confirmButtonColor: '#20A6C3',
          allowOutsideClick: false
        })
...
```
`npm install`
`ng serve`
Notice that the app compiles successfully.
Now change `"sweetalert2": "8.14.0"` in `package.json` to `""sweetalert2": "8.19.0"`
Delete `package-lock.json`
`npm install`
`ng serve`
Notice that the app fails compilation as mentioned above and in title.

---

Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:

- GitHub Sponsors: https://github.com/sponsors/limonte
- PayPal: https://www.paypal.me/limonte
- Bitcoin: `16Z7RvFv7PsV3XzFvchYwPnRfw9KeLTZQJ`
- Ether: `0x192096161eB2273f12b1cB4E31aBB09Bfc03a7F3`
- Bitcoin Cash: `qz28x66hrljtdz3052p8ya3cmkwwva5avy0msz2ej3`
- Stellar: `GDUM4VJZYDNRHBTKUQBOPC374AP6MMMVOJDMSHIPEJPEMBCY4ZHH6NDY`

**Comment by limonte** [comment]
Finally, someone reported this issue properly! :)

You're sticking to the legacy version of `typescript`, so it kinda makes sense to stick to the legacy version of `sweetalert2` as well.

`package.json`:
```js
"dependencies": {
  "sweetalert2": "8.14.0",
}
"devDependencies": {
  "typescript": "^2.9.2"
}
```

**Comment by mattemoore** [comment]
Understood and that's how we are managing this.

**Comment by alaminshakeel** [comment]
@limonte 
i am using 
`"dependencies": {
  "sweetalert2": "^9.10.9",
}
"devDependencies": {
  "typescript": "~2.5.3"
}`

what combination will fix it for me?
