### ISSUE TITLE
Searchable Select not working..

### ISSUE THREAD

**Issue by nlahiry** [sweetalert2/sweetalert2#1863]
As my select options are over 100 options long i am trying to find a way to add search box to the select option in swal, but i can't find any in documentation about live search, when i try to create my own html with bootstrap select plugin it does not showup in the modal, when i try to insert input box in the swal2-select it breaks the selectbox and options come as non clickable text with input in top of them and a blank selectbox on top. i found a working search in the github ... but issue with that is that in uses a different input box and button to search rather than a data live search inside the selectbox... is it possible ?

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
