### ISSUE TITLE
Is there some way to disable just the confirm button?

### ISSUE THREAD

**Issue by lourenci** [sweetalert2/sweetalert2#1864]
Hi, thanks for the lib.

Is there some way to disable just the confirm button?

[I've found solved related issue on earlier versions of the lib](https://github.com/sweetalert2/sweetalert2/issues/226#issuecomment-234681724), but this seems to not work anymore.

Is there some another way to achieve that?

**Comment by limonte** [comment]
```js
Swal.getConfirmButton().setAttribute('disabled', '')
```
