### ISSUE TITLE
onChange on a sweetalert containing an input field

### ISSUE THREAD

**Issue by AbreezaSaleem** [sweetalert2/sweetalert2#1868]
I have a textfield in my alert box. I want to call validation on it as I am typing in something. I need to call an `onChange` function for that. How I listen to a change event on my input field?

**Comment by limonte** [comment]
```js
Swal.fire({
  input: 'text',
  onOpen: () => {
    const input = swal.getInput()
    input.oninput = () => {
      // perform validation here
    }
  }
})
```

**Comment by AbreezaSaleem** [comment]
@limonte thank you for the response. Is there any way I can also show an error message?

**Comment by limonte** [comment]
> @limonte thank you for the response. Is there any way I can also show an error message?

https://sweetalert2.github.io/#showValidationMessage
