### ISSUE TITLE
Uncaught (in promise) TypeError: elem.cloneNode is not a function

### ISSUE THREAD

**Issue by Daniel4Digital** [sweetalert2/sweetalert2#1870]
## Current behavior

When I submit any kind of "post" with axios, I've an simple catch, and if I put there the sweetalert call, it gives this error. If I put directly the swal code it works. But for the sake of reusability, I've created a common file where I call the swal I want. And this way it gives the error "elem.cloneNode is not a function"

## Expected behavior

I was expecting it to work. Dunno if I should call it other way.

## Live demo

https://codesandbox.io/s/sweetalert2-hxbnx

**Comment by limonte** [comment]
Thanks a lot @Daniel4Digital for the well-reported issue!
