### ISSUE TITLE
Typescript: Could not find a declaration file for module 'sweetalert2/dist/sweetalert2.js'.

### ISSUE THREAD

**Issue by purplecandle** [sweetalert2/sweetalert2#1878]
## Current behavior

TS giving that message above.

My TS config
```
{
    "compilerOptions": {
        "target": "esnext",
        "strict": true,
        "noEmit": true,
        "module": "esnext",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "baseUrl": ".",
        "typeRoots": [
            "./node_modules/@types",
            "./js/types"
        ]
    },
    "exclude": ["node_modules", "**/*.spec.ts"]
}
```

SweetAlert version: 9.7.1
Typescript version: 3.7.5

## Expected behavior

Module shoud find declaration file even in dist and src folders

**Comment by limonte** [comment]
Expected behavior should work: https://github.com/sweetalert2/sweetalert2/blob/master/sweetalert2.d.ts#L916

Further assistance only with the simple repo where we can reproduce the issue.

**Comment by purplecandle** [comment]
> Expected behavior should work: https://github.com/sweetalert2/sweetalert2/blob/master/sweetalert2.d.ts#L916
> 
> Further assistance only with the simple repo where we can reproduce the issue.

Here
https://github.com/purplecandle/sweetalert2ts

**Comment by limonte** [comment]
The reason is that you're setting `"strict": true` in your `tsconfig`. Add `"noImplicitAny": false` or any other solution from https://github.com/microsoft/TypeScript/issues/15031

**Comment by purplecandle** [comment]
> Thanks for the repo @nixta purplecandle!
> 
> The reason is that you're setting `"strict": true` in your `tsconfig`. Add `"noImplicitAny": false` or any other solution from [microsoft/TypeScript#15031](https://github.com/microsoft/TypeScript/issues/15031)
> 
> The behavior doesn't make much sense to me as well as to many commenters from [microsoft/TypeScript#15031](https://github.com/microsoft/TypeScript/issues/15031) but it is what it is

I just wanted to be able to use only lib logic without styles and get types definitions at the same time. Is there really no other ways to separate styles from logic?

**Comment by purplecandle** [comment]
I've found solution. I added `mainFields: ['module', 'browser', 'main']` field in my webpack config, because in your lib's package.json you have this line - `module": "src/sweetalert2.js"`
