### ISSUE TITLE
Horizontal overflow

### ISSUE THREAD

**Issue by maicol07** [sweetalert2/sweetalert2#1879]
_Note: This issue may be related to #1699 but this case is more general_

## Current behavior

If an element overflows horizontally (it exceedes the width of the SweetAlert2 modal) it goes beyond the modal

## Expected behavior

Element that overflows fits automatically to the modal

## Live demo 
https://codepen.io/maicol07/pen/RwNmJZR (I know I used the `!important` keyword but is only used for showing the issue)

**Comment by limonte** [comment]
Setting the `width` parameter to `'auto'` should do it.
