### ISSUE TITLE
Body padding is conflict with Bootstrap modal

### ISSUE THREAD

**Issue by dihak** [sweetalert2/sweetalert2#1880]
## Current behavior

![image](https://user-images.githubusercontent.com/10445482/73412642-d2faba80-433b-11ea-8ee5-e7a894e7bbd4.png)

## Expected behavior

The padding right must still 15px

**Comment by gverni** [comment]
@dihak i'm having trouble understanding what you are trying to report. Can you share a live example?

**Comment by dihak** [comment]
The issue is the padding.

I have bootstrap modal, when it open, it will add a padding-right: 15px;

And after click the OK button, i added a sweetalert and then close the modal. then the padding-right is 30px;

and after i close the sweetalert, the padding right is 15px.

-----------------------------------------

Solved using setTimeout, i close the modal and then using setTimeout to show sweetalert
