### ISSUE TITLE
broken success icon in chrome post 9.7.1

### ISSUE THREAD

**Issue by lofcz** [sweetalert2/sweetalert2#1882]
## Current behavior
toast mode:
![image](https://user-images.githubusercontent.com/10260230/73839255-d26b9380-4815-11ea-91d6-7d0f7d0822ba.png)

classic popup mode:
![image](https://user-images.githubusercontent.com/10260230/73839445-4efe7200-4816-11ea-97d0-b81dcb2b1db4.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/10260230/73839286-e6af9080-4815-11ea-89a0-c803aa81b5fb.png)

This should be obvious. Tested on Chrome 80 and 81, only happening after 9.7.1
My best guess is that polishing of the svg for Safari broke it for other browsers. Other built-in icons are working fine.

**Comment by limonte** [comment]
Are you able to reproduce the descirbed issue on https://sweetalert2.github.io/ ?

**Comment by lofcz** [comment]
I can't, sorry. Good point to test in against main site.
