### ISSUE TITLE
Body background appears at the bottom

### ISSUE THREAD

**Issue by purplecandle** [sweetalert2/sweetalert2#1886]
## Current behavior

Body background appears at the bottom when scrolling modal with long content up or down and address bar shows up/hides.  [Screenshot](https://ibb.co/Nm7t7vQ)

## Expected behavior

It would be better avoid this glitch. I thinks it's related to [this](https://developers.google.com/web/updates/2016/12/url-bar-resizing)

## Live demo

Open [modal ](https://sweetalert2.github.io/#examples )with long content in Chrome Android

**Comment by gverni** [comment]
Thanks @purplecandle. I'm able to reproduce it **only** when scrolling up (on Chrome 80 on Android 10). It doesn't appear when scrolling down and as soon as I stop scrolling the grey bar disappears. Can you confirm you see the same behavior? 

I'll look into how to patch it, but it may require complicating the code too much to fix a small artifact.

**Comment by purplecandle** [comment]
> Thanks @purplecandle. I'm able to reproduce it **only** when scrolling up (on Chrome 80 on Android 10). It doesn't appear when scrolling down and as soon as I stop scrolling the grey bar disappears. Can you confirm you see the same behavior?
> 
> I'll look into how to patch it, but it may require complicating the code too much to fix a small artifact.

Yes, I can confirm it

**Comment by limonte** [comment]
I don't think we can do anything here.
