### ISSUE TITLE
Swal.stopTimer() in onOpen function doesn't stop the timerProgressBar

### ISSUE THREAD

**Issue by AlbertMN** [sweetalert2/sweetalert2#1894]
## Current behavior
When executing `Swal.stopTimer()` in the `onOpen` function of the Sweetalert, it does stop the timer, but the timer animation from `timerProgressBar` still runs.

This is currently "fixed" by executing `Swal.stopTimer()` 10ms after the `onOpen` function runs; 
```
setTimeout(Swal.stopTimer, 10);
```

## Expected behavior
The `timerProgressBar` should stop / be paused as well.

## Live demo 
https://codepen.io/iversen/pen/ZEGpvZK

**Comment by limonte** [comment]
Thank you for reporting @AlbertMN!

**Comment by AlbertMN** [comment]
@limonte I just tried v9.10.0, and this is still an issue.

**Comment by limonte** [comment]
Strange, the test I added is passing, I'll check that.

**Comment by AlbertMN** [comment]
Thanks for the swift fix! Will check it out when it's released :)

**Comment by AlbertMN** [comment]
The main issue has been fixed, but an issue still persists; when inserting a queue step, setting a new timer and showing the timer progress bar whilst doing `Swal.stopTimer();` on `onOpen` of the swal, the progress bar starts going down as well, even though the "real" timer is actually stopped. So about halfway there! :D

**Comment by limonte** [comment]
> 
> 
> The main issue has been fixed, but an issue still persists; when inserting a queue step, setting a new timer and showing the timer progress bar whilst doing `Swal.stopTimer();` on `onOpen` of the swal, the progress bar starts going down as well, even though the "real" timer is actually stopped. So about halfway there! :D
> 
> Edit; even if `timerProgressBar` is set to false in the newly inserted step, the progress bar is still showing as well.

could you please create another issue with the minimal code to reproduce?

**Comment by AlbertMN** [comment]
I sure can :)
