### ISSUE TITLE
horizontal aligment of content

### ISSUE THREAD

**Issue by AtiqGauri** [sweetalert2/sweetalert2#1895]
## New feature motivation
like toast can we get horizontal alignment of content in normal alert popup

## New feature description
Toast have it but toast comes with limitation like you can click outside of toast when it is displaying with a timer.  On the other side there is no straight forward way to align content horizontally in an alert.

---

Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:

- GitHub Sponsors: https://github.com/sponsors/limonte
- PayPal: https://www.paypal.me/limonte
- Bitcoin: `16Z7RvFv7PsV3XzFvchYwPnRfw9KeLTZQJ`
- Ether: `0x192096161eB2273f12b1cB4E31aBB09Bfc03a7F3`
- Bitcoin Cash: `qz28x66hrljtdz3052p8ya3cmkwwva5avy0msz2ej3`
- Stellar: `GDUM4VJZYDNRHBTKUQBOPC374AP6MMMVOJDMSHIPEJPEMBCY4ZHH6NDY`

**Comment by limonte** [comment]
Not convinced by the described motivation. Take a look at the `customClass` param.
