### ISSUE TITLE
Prevent Flashing When Transitioning Between Modals

### ISSUE THREAD

**Issue by Souleste** [sweetalert2/sweetalert2#1899]
Currently when transitioning between modals the backdrop flashes, which I would understand to happen when "firing" a new sweet alert, but I think it should at least not do this when queuing modals.

**Comment by gverni** [comment]
We can probably use the `data-swal2-queue-step` or the `data-queue-step` attributes to detect we are rendering a queue and prevent the removal of the backdrop. I'll check we are not messing up with other corner cases and get back to you..

**Comment by limonte** [comment]
Thank you for reporting @Souleste!

This was bothering me as well, but since nobody reported the issue it was never addressed :)
