### ISSUE TITLE
Multiple entries

### ISSUE THREAD

**Issue by Rishgod** [sweetalert2/sweetalert2#1902]
Can you please functionality for multiple inputs, like entry one, entry 2 and also add a checkbox feature,
something like this, I was wondering can you create this with SWAL

![67167601-93b7e780-f3a4-11e9-99ee-76a9c5c54a3c](https://user-images.githubusercontent.com/54576074/75438446-f423ea80-597d-11ea-927b-b9d1129cea25.jpg)

**Comment by gverni** [comment]
@Rishgod you can achieve that using the `html` property of `swal`. You can find an example of that [here](https://sweetalert2.github.io/sweetalert2-examples/forms/login/)
