### ISSUE TITLE
Do not change focus when both focus options are disabled

### ISSUE THREAD

**Issue by dserv-nh** [sweetalert2/sweetalert2#1913]
You enable the cancel button and set focusConfirm and focusCancel to false

## Current behavior
The confirm button is focused

## Expected behavior
Sweetalert2 does not change the focus. If this is intended please treat this as a feature request to add an option for not changing focus

## Live demo
https://codepen.io/dservnh/pen/oNXEWza

---

Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:

- GitHub Sponsors: https://github.com/sponsors/limonte
- PayPal: https://www.paypal.me/limonte
- Bitcoin: `16Z7RvFv7PsV3XzFvchYwPnRfw9KeLTZQJ`
- Ether: `0x192096161eB2273f12b1cB4E31aBB09Bfc03a7F3`
- Bitcoin Cash: `qz28x66hrljtdz3052p8ya3cmkwwva5avy0msz2ej3`
- Stellar: `GDUM4VJZYDNRHBTKUQBOPC374AP6MMMVOJDMSHIPEJPEMBCY4ZHH6NDY`

**Comment by limonte** [comment]
The expected behavior is invalid. Sweetalert2 is for modal windows and modal windows should change focus by definition.
