### ISSUE TITLE
File Dates When npm install --save sweetalert2 are wrong

### ISSUE THREAD

**Issue by wilecoyte78** [sweetalert2/sweetalert2#1914]
I am trying to update my sweetalert2, but when I run npm install --save sweetalert2 all the file dates are 10/26/1985 1:15 am.

I would like these dates to be the dates they were changed.

**Comment by wilecoyte78** [comment]
So apparently NPM since 6 Has changed this: 

This is intentional. The website needs to be updated to stop using the published tarballs, but as of npm@6, we're locking tarball dates to a single date. This makes it so tarballs generated off the same code will have consistent shasums, enabling reproducible-builds.org https://github.com/npm/npm/issues/20439#issuecomment-385121133

**Comment by limonte** [comment]
Use Yarn and you'll be alright :+1:
