### ISSUE TITLE
Swal focused on other bootstrap button instead of the confirm or cancel button

### ISSUE THREAD

**Issue by Jamyth** [sweetalert2/sweetalert2#1920]
## Current behavior

![image](https://user-images.githubusercontent.com/56388637/76838114-b45e6d80-686e-11ea-9ed4-5181b1411258.png)

the confirm button lost focus and switch to the caller button

## Expected behavior

focus on the confirm button

## Live demo 
![image](https://user-images.githubusercontent.com/56388637/76838114-b45e6d80-686e-11ea-9ed4-5181b1411258.png)

---

Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:

- GitHub Sponsors: https://github.com/sponsors/limonte
- PayPal: https://www.paypal.me/limonte
- Bitcoin: `16Z7RvFv7PsV3XzFvchYwPnRfw9KeLTZQJ`
- Ether: `0x192096161eB2273f12b1cB4E31aBB09Bfc03a7F3`
- Bitcoin Cash: `qz28x66hrljtdz3052p8ya3cmkwwva5avy0msz2ej3`
- Stellar: `GDUM4VJZYDNRHBTKUQBOPC374AP6MMMVOJDMSHIPEJPEMBCY4ZHH6NDY`

**Comment by limonte** [comment]
The issue is somewhere in your app logic, since the live demo isn't provided we can't help.
