### ISSUE TITLE
Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by blueWhalei** [sweetalert2/sweetalert2#1924]
I introduced
①https://cdn.bootcss.com/limonte-sweetalert2/8.11.8/sweetalert2.all.min.js
②https://cdn.bootcss.com/limonte-sweetalert2/8.11.8/sweetalert2.min.js
③https://cdn.bootcss.com/limonte-sweetalert2/8.11.8/sweetalert2.min.css
when i used this,like 

swal.fire({
		title : title,
		text : "",
		type : "warning",
		showCancelButton : true,
		cancelButtonText : "cancel",
		confirmButtonColor : "#DD6B55",
		confirmButtonText : "yes"
	}).then(function() {
		callback();
	});

An error has occurred
Uncaught TypeError: Cannot read property 'constructor' of undefined
    at ue (sweetalert2.min.js:1)

**Comment by limonte** [comment]
Don't hesitate to read the docs: https://sweetalert2.github.io/#download
