### ISSUE TITLE
SweetAlert2: SweetAlert2 requires document to initialize

### ISSUE THREAD

**Issue by sneubert-dev** [sweetalert2/sweetalert2#1927]
We develop an application in electron and we see after upgrade to SweetAlert2 (9.10.3) now errors like this:
node_modules/sweetalert2/dist/sweetalert2.all.js:231 SweetAlert2: SweetAlert2 requires document to initialize

Code:
const Swal = require('sweetalert2');
Swal.fire({
                    title: 'Title',
                    text: "text",
                    icon: 'warning',
                    showCancelButton: true,
                    showConfirmButton: true,
                    confirmButtonColor: '#d33',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'OK'
                });

SweetAlert2 changes:
9.10.3 (errors as mentioned above):
export const isNodeEnv = () => typeof global !== 'undefined' && {}.toString.call(global) === '[object global]'
9.10.2 (code works fine):
export const isNodeEnv = () => typeof window === 'undefined' || typeof document === 'undefined'

We would appreciate feedback on what we need to change.

**Comment by limonte** [comment]
Unforeseen regression from #1922 and #1923

Apologies for that! I will roll back that change.

**Comment by sneubert-dev** [comment]
Kudos :dancer:

**Comment by syedadeel2** [comment]
It still the same for me  9.10.6 and same error and if I downgrade to  9.10.2 it works.

**Comment by limonte** [comment]
> It still the same for me 9.10.6 and same error and if I downgrade to 9.10.2 it works.

That's very interesting because 9.10.2 and 9.10.6 should be the same. Could you please provide a repo where we can reproduce your issue?

**Comment by syedadeel2** [comment]
> > It still the same for me 9.10.6 and same error and if I downgrade to 9.10.2 it works.
> 
> That's very interesting because 9.10.2 and 9.10.6 should be the same. Could you please provide a repo where we can reproduce your issue?

I will do that soon, as I cant share the one I'm working because its official work but I'll create new one for your testing.

**Comment by syedadeel2** [comment]
Hello, 

I have created the new repo but with the clean repo, I'm not able to reproduce that. Maybe it was npm cache.

Here is repo URL this might help you in future for your testing for new versions.

[https://github.com/syedadeel2/sweetalert2-with-angular-with-electron-test](https://github.com/syedadeel2/sweetalert2-with-angular-with-electron-test)

**Comment by limonte** [comment]
Thank you @syedadeel2

**Comment by pjebs** [comment]
For using sweetalert2 via the main process: https://github.com/rocketlaunchr/electron-alert
