### ISSUE TITLE
Null element stack trace in applynumericalstyles

### ISSUE THREAD

**Issue by JolivetteSax** [sweetalert2/sweetalert2#1929]
Upgrading from SA2 v.7 and this package v.1 to the latest in npm gives a stack error

"TypeError: Cannot read property 'style' of null"  
applyNumericalStyle  
node_modules/sweetalert2/dist/sweetalert2.all.js:564  

The stack trace points to this line of code:
       elem.style.removeProperty(property);
 
Latest from npm install gives:
    "sweetalert2": "^9.10.5",
    "sweetalert2-react-content": "^3.0.1",

There must be some regression because going back to the old version works without any problem. Even cutting and pasting the simplest code from the readme doesn't work. Other deps I'm mixing with this include:
   "react": "^16.8.6",
    "react-bootstrap": "^1.0.0-beta.17",
    "react-dom": "^16.8.6",

**Comment by limonte** [comment]
I can't reproduce. We need the repo/codepen with the demonstration of this issue.

**Comment by JolivetteSax** [comment]
Ding ding ding! Yeah it's electron. I'm not sure why the old version works ok, but it does. Sorry I've been slammed this week. If I can find time to try to figure out what difference killed it I'll report back.
