### ISSUE TITLE
Request error: undefined,  But data got inserted

### ISSUE THREAD

**Issue by Aqeelkhadim** [sweetalert2/sweetalert2#1939]
**Here is my code its perform validation as well as insertions of new password but the issue is even password successfully change but this gave an error "request error: undefined"
Can anyone figure out what is the issue in my code?**

`$('.changep').click(function () {
            var id = $(this).data('change');
            var name = $(this).data('name');
            Swal.fire({
                title: 'Enter New Password of ' + name,
                input: 'text',
                inputPlaceholder: 'new password',
                inputAttributes: {
                    autocapitalize: 'off'
                },
                showCancelButton: true,
                confirmButtonText: 'Change Password',
                showLoaderOnConfirm: true,
                preConfirm: function (password) {
                    return $.ajax({
                        url: "user/" + id + "/change-password",
                        type: 'get',
                        data: {
                            "_token": "{{csrf_token()}}",
                            "id": id,
                            "password": password
                        },
                        dataType: "json",
                        success: function (response) {

                        },
                    }).then(response => {
                        if (!response.ok) {
                            throw response.errors
                        }
                        return response.json()
                    }).catch(error => {
                        Swal.showValidationMessage(
                            `Request failed: ${error}`
                        )
                    });

                },
                allowOutsideClick: () => !Swal.isLoading()
            }).then((response) => {
                if (response.password) {
                    Swal.fire({
                        title: `Password Changed Successfully`,
                        text: `new password is ${response.password}`
                    })
                }
            })
        })`

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
