### ISSUE TITLE
Setting html to `<svg><use xlink:href=...></svg>` produces empty SVG in Chrome

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1940]
## Current behavior

In Chrome, setting `html` parameter to

```
<svg viewBox="0 0 30 10" xmlns="http://www.w3.org/2000/svg">
  <use xlink:href="/test/icons.svg#account"></use>
</svg>
```

where `icons.svg` is

```
<svg xmlns="http://www.w3.org/2000/svg">
  <symbol id="account" viewBox="0 0 24 24">
    <path d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z" />
  </symbol>
</svg>
```

produces empty icon:

![image](https://user-images.githubusercontent.com/6059356/78510606-2efc1800-779f-11ea-98b9-f3e8a5f18fc1.png)

## Expected behavior

There should be an icon, Firefox works as expected. Most probably the issue is related to https://github.com/sweetalert2/sweetalert2/pull/1930

## Live demo 

https://cerulean-secret-hip.glitch.me/

**Comment by limonte** [comment]
@gverni would you be interested checking this one? Might be interesting to investigate to learn why DOMParser is having troubles with `<use>`'s [shadow root](https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot).

**Comment by gverni** [comment]
@limonte I spent quite a lot of hours trying to debug it, but I haven't found anything that can fix it. The only workaround I found is to force chrome to re-render the `<use>` _resetting_ the link after the element has been attached to the destination: 

```
let useHref = useElem.getAttribute("xlink:href")
useElem.setAttributeNS("http://www.w3.org/1999/xlink", "xlink:href", "")
useElem.setAttributeNS("http://www.w3.org/1999/xlink", "xlink:href", useHref)
```

I'll keep doing some more investigation and experiment because I don't really like this solution...

**Comment by limonte** [comment]
Thanks a lot @gverni  for your time and effort to resolve this issue. Now, I'm thinking if that's an actual bug in Chromium. If so, then the issue should be resolved there.

I just reported the issue to Chromium issue-tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1070038

Let's see what will be their response.

**Comment by limonte** [comment]
@gverni so far, it does seem like a bug in Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1070038#c2

I'll unassign you from this issue for now because I think we shouldn't do anything in case the issue is in the browser.

In case someone will face this issue, we can recommend a workaround:

```diff
- html: '<svg>...</svg>'
+ onOpen: () => { Swal.getContent().innerHTML = '<svg>...</svg>' }
```

**Comment by gverni** [comment]
That's great. Thanks @limonte for closing on this issue!

**Comment by limonte** [comment]
Should be fixed in one of upcoming releases (not sure which one though): https://bugs.chromium.org/p/chromium/issues/detail?id=1070076

**Comment by gverni** [comment]
Quick update, I tested it on Canary 85.0.x and works fine:

![image](https://user-images.githubusercontent.com/17089396/84641991-c4303100-aef3-11ea-9e65-865aba566137.png)

**Comment by limonte** [comment]
Tested in Chrome Beta (v84 atm), all is well.

Closing the issue, thank you @gverni for helping out with it!
