### ISSUE TITLE
showLoaderOnConfirm issues when used with customClass

### ISSUE THREAD

**Issue by jongbonga** [sweetalert2/sweetalert2#1941]
When the options are

```
showloaderonconfirm: true,
 customclass: {
  confirmbutton: "swal-confirm-button-anyColor"
}
```
the loader spins with text displayed inside

<img width="436" alt="Screenshot 2020-04-09 at 17 41 31" src="https://user-images.githubusercontent.com/12111716/78913645-9a890280-7a89-11ea-8fb8-c979c49f2c73.png">

## Expected behavior

the loader should spin clean

## Live demo 

 live demo: https://jsfiddle.net/dgubav27/1/

**Comment by limonte** [comment]
The proper fix should be the separation of the loader and the confirm button. That'll be done in the next major release.

Until then, please use this:

```
customClass: {
  confirmButton: 'swal2-confirm swal-confirm-button-dark '
}
```

and please update your `sweetalert2` dependency, I just published a new release (`v9.10.10`) so the suggested workaround would work.

**Comment by jongbonga** [comment]
updated to `v9.10.10` working fine.

noticed another issue with `width: 100%` in `<my-custom-classes>`.  Text is not displayed but spinner also get 100% width and spins out of bound

**Comment by limonte** [comment]
> noticed another issue with `width: 100%` in `<my-custom-classes>`. Text is not displayed but spinner also get 100% width and spins out of boun

Can't reproduce, please provide live demo.

**Comment by jongbonga** [comment]
I updated the [jsfiddle](https://jsfiddle.net/63vf97wa/)

**Comment by limonte** [comment]
> noticed another issue with `width: 100%` in `<my-custom-classes>`. Text is not displayed but spinner also get 100% width and spins out of bound

`width: 100%` and `width: 100% !important;` are different things ;)

Use `width: 100%` and you'll be fine.

**Comment by jongbonga** [comment]
we good to go, thank you for the workaround release
