### ISSUE TITLE
Modal doesn't respond on small phones

### ISSUE THREAD

**Issue by janiorjimenezh** [sweetalert2/sweetalert2#1943]
## Current behavior

On the mobile phone, when you call sweetalert2 when you press any of the modal buttons, it does not respond and takes a few seconds to disappear, then the page does not respond for up to 1 minute.

The device that has been checked is an LG K10 with  Android 7.0

**Comment by limonte** [comment]
Hey @janiorjimenezh and thank you for reporting this issue!

Can you specify the browser? Also, if you can make a video of what is happening that'd be very useful!

**Comment by janiorjimenezh** [comment]
I use Google Chrome.
In the video it is shown that you enter your official page from the mobile device you have to press the "Try me" button, the modal message appears but it remains static and does not respond, when I click on "OK" it is again waiting .


Video link

[https://youtu.be/eSWM8_vycLc](url)

https://youtu.be/eSWM8_vycLc

**Comment by limonte** [comment]
Thanks a lot for recording the video @janiorjimenezh!

The issue is very strange, can anybody else confirm this on Android/Chrome?

@janiorjimenezh could you please try on the same device (LG K10) with the alternative Chromium-based browser Brave: https://play.google.com/store/apps/details?id=com.brave.browser&hl=en

**Comment by janiorjimenezh** [comment]
I checked it with Brave and the behavior is the same.

**Comment by limonte** [comment]
Thank you again @janiorjimenezh 

I guess I need to purchase LG K10 for debugging purposes :laughing: 

Before I do that, could you please do me one more favor and test on the same device in Firefox so we can be sure that the issue is the device-related.

Many thanks for you help here!!

**Comment by janiorjimenezh** [comment]
I did tests with Firefox and it works wonderfully, then I tried Microsoft edge and the same problem happened it freezes and responds after a few seconds, both when calling and accepting

**Comment by limonte** [comment]
> then I tried Microsoft edge and the same problem happened it freezes and responds after a few seconds

Apparently, the issue is related to Chromium-based browsers on that device. I'm ordering the device now :laughing:

**Comment by gverni** [comment]
@limonte @janiorjimenezh, for your information I tried on a Pixel 4 (android 9.0) with Chrome and it works fine. Also, Android 7.0 seems a bit old (released end of August 2016). Android ages quite fast (especially for the storage) so I'm wondering if the issue has something to do with the phone / OS itself?

**Comment by janiorjimenezh** [comment]
I hope you don't get mad, reset the phone and only with chrome check that it already works correctly, in edge there are a few seconds of delay but it no longer freezes everything.
I am sorry I wasted your time.
I did not think it would be necessary to reset the phone to correct the problem

**Comment by limonte** [comment]
I would never expect that the device reset would affect this. @gverni it was insightful of you to bring it up!
