### ISSUE TITLE
content scroll in ios not working

### ISSUE THREAD

**Issue by Griffin23** [sweetalert2/sweetalert2#1944]
## Current behavior

Use ios safari or chrome ios app, content scroll not working. PC or Android is OK.

## Expected behavior

Scroll in ios browser

## Live demo 

Open https://codepen.io/griffin23/full/RwWPLLX in ios safari. Try to scroll the content. It won't work.

Source code see: https://codepen.io/griffin23/pen/RwWPLLX

Thanks!

**Comment by limonte** [comment]
Thank you @Griffin23 for reporting this issue!

I believe that it should be addressed here: https://github.com/sweetalert2/sweetalert2/blob/63946d57b5c43506597b7cecfbb7212b189e4e4c/src/utils/iosFix.js#L17

**Comment by Griffin23** [comment]
Confirmed. Nice work! Thanks a lot!
