### ISSUE TITLE
Unable to click the confirm/cancel button of tall popup in iOS

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1948]
## Current behavior

![ezgif-2-fb1e4b30b117](https://user-images.githubusercontent.com/6059356/79369308-6a45d600-7f59-11ea-9e1a-725507bcdc82.gif)

Instead of button being clicked, the bottom panel appears. It'll be possible to click the button after additional scrolling.

## Expected behavior

Users should be able to click the button

### Live demo

https://sweetalert2.github.io/#long-text

**Comment by limonte** [comment]
@gverni will you have time to take a look at this issue? I don't have iPhone at my working place atm, and the issue is not reproducible in iPad which I do have for testing purposes.

**Comment by gverni** [comment]
sure @limonte. I reproduced it on iPhone, and for completeness, it happens only with Safari. Chrome doesn't have that bottom bar, so the issue is not reproducible there.

**Comment by limonte** [comment]
Again, if that seems to be the browser issue, we have no choice than report the issue to https://bugs.webkit.org/ , recommend workarounds for our users and wait for the fixed release of Safari.

**Comment by gverni** [comment]
Let me correct the statement. Chrome does have the bar, but doesn't get in the way. 

Also, I've noticed that I'm able to scroll the page behind the modal with the long content modal. Was there any change to that recently @limonte ? 

One final observation (that can explain this behaviour). If you scroll a page to put a button at the very bottom of the screen, when you try to click it, the bottom bar appears, the button gets pushed up, but the `onclick` event is not fired. So the only different with the modal is that the button doesn't get pushed up and remain behind the bar. I need to do some more experiments, but it doesn't seem to be strictly related to the modal itself.

**Comment by limonte** [comment]
> Let me correct the statement. Chrome does have the bar, but doesn't get in the way.

Roger, thanks!

> Also, I've noticed that I'm able to scroll the page behind the modal with the long content modal. Was there any change to that recently @limonte ?

Nope, should be blocked. If not, please report the issue. Thank you!

> One final observation (that can explain this behaviour). If you scroll a page to put a button at the very bottom of the screen, when you try to click it, the bottom bar appears, the button gets pushed up, but the `onclick` event is not fired. So the only different with the modal is that the button doesn't get pushed up and remain behind the bar. I need to do some more experiments, but it doesn't seem to be strictly related to the modal itself.

That's weird and does seem like an issue in Safari :/

**Comment by wilecoyte78** [comment]
I do not know if this helps because it is Bootstrap, but it might get you headed in the correct direction to fix the content scrolling behind the SweetAlert,:

I had this exact issue with the Bootstrap model.

I had to do this:

JavaScript:

	var scolltop = $(document).scrollTop();
	$(document).on('show.bs.modal', function() {
		$(this).find('.modal.show').css({padding:0});
		scolltop = $(document).scrollTop();
		$('html').addClass('modal-open').css({
			overflow: 'hidden',
			left: 0,
			right: 0,
			top: 0,
			bottom: 0,
			position: 'fixed',
		});
	}).on('hide.bs.modal', function() {
		$('html').removeAttr('class').removeAttr('style');
		$(document).scrollTop(scolltop);
	});

**Comment by limonte** [comment]
**:moneybag: Money for code! :moneybag:**

I will donate $10 for the PR with the fix for this issue (donation will be done after approval and merge).

**Comment by limonte** [comment]
@gverni let's see if the community will be able to help us with this issue. It's bothering me and I have no idea how to fix this iOS "feature" :)

**Comment by wilecoyte78** [comment]
> One final observation (that can explain this behaviour). If you scroll a page to put a button at the very bottom of the screen, when you try to click it, the bottom bar appears, the button gets pushed up, but the onclick event is not fired. So the only different with the modal is that the button doesn't get pushed up and remain behind the bar. I need to do some more experiments, but it doesn't seem to be strictly related to the modal itself.


This happens to all buttons that need to be clicked on a a web page that is close to the bottom of the iPhone. It is not modal related it iOS related. iOS developed this way because they wanted to give the user a faster way to get back to the bottom tool bar without scrolling back up first.

**Comment by wilecoyte78** [comment]
I have test the button clicking on iOS Chrome and it does not do what Safari does. So, my statement about it being iOS Safari building their app to make the bottom toolbar appear when clicking close to the bottom is built into their app.

**Comment by wilecoyte78** [comment]
> Also, I've noticed that I'm able to scroll the page behind the modal with the long content modal

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1266992/81421109-cb4e6d00-9105-11ea-8070-b262d225b3b9.gif)


In the video it is hard to see but the content behind the model can be scrolled only when the SweetAlert Modal is longer than the device height. Watch for the darker scroll bar moving in the top right.

**Comment by wilecoyte78** [comment]
If you watch this video you will see after scrolling to the bottom the content in the background can be scrolled. Look at the top right hand corner for the darker scroll bar to move.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/1266992/81422052-4fedbb00-9107-11ea-9047-b62a2eac3371.gif)

**Comment by wilecoyte78** [comment]
I forgot to mention it does this on all browsers on iOS.

**Comment by limonte** [comment]
Thank you @wilecoyte78 for your input!

**Comment by tiagostutz** [comment]
Just for the record, this issue is reproducible using iPhone simulator on MacOS:

<img src="https://user-images.githubusercontent.com/3986989/83351347-73c4ab00-a319-11ea-82ed-28386e608cee.gif" width="300"/>

**Comment by tiagostutz** [comment]
I think I found a way to fix it. Here's the demo:

![sweet-long-modal](https://user-images.githubusercontent.com/3986989/83914250-4461d400-a747-11ea-9d1b-bd8c9b4c5a69.gif)

```
padding-bottom: env(safe-area-inset-bottom);
```

I'm working on the PR now... I have to check wether it introduces any side effects on other browsers.

**Comment by wilecoyte78** [comment]
https://medium.com/@draganeror/iphone-x-layout-features-with-css-environment-variables-d57423433dec

    // Older browsers (do now support CSS Environment variables).
    .selector {
       height: 100%;
    }
     // Browsers which partially support CSS Environment variables (iOS 11.0-11.2).
     @supports (padding-top: constant(safe-area-inset-top)) {
       .selector {
         --safe-area-inset-top: constant(safe-area-inset-top);
         height: calc(100% + var(--safe-area-inset-top));
       }
     }
     // Browsers which fully support CSS Environment variables (iOS 11.2+).
     @supports (padding-top: env(safe-area-inset-top)) {
       .selector {
         --safe-area-inset-top: env(safe-area-inset-top);
         height: calc(100% + var(--safe-area-inset-top));
       }
     }
