### ISSUE TITLE
Best way to pick up the data entered with php?

### ISSUE THREAD

**Issue by jamminjames** [sweetalert2/sweetalert2#1949]
What's the best way to pick up the data entered in the swal form via php?

I know it should be simple, but I can't get anything to work that I've seen googling around.

Thanks for any help.

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
