### ISSUE TITLE
'timerProgressBar' does not exist in type 'SweetAlertOptions

### ISSUE THREAD

**Issue by StevRoger** [sweetalert2/sweetalert2#1953]
## Current behavior

timerProgressBar doesn't work for me and I'm not sure I'm missing something or what.

See the error below.
Object literal may only specify known properties, and 'timerProgressBar' does not exist in type 'SweetAlertOptions & { useRejections: true; }'.ts(2769)

Full Error.
No overload matches this call.
  Overload 1 of 3, '(title: string, message?: string, type?: SweetAlertType): Promise<SweetAlertResult>', gave the following error.
    Argument of type '{ title: string; html: string; timer: number; confirmButtonText: string; allowOutsideClick: boolean; timerProgressBar: boolean; onBeforeOpen: () => void; onClose: () => void; }' is not assignable to parameter of type 'string'.
  Overload 2 of 3, '(settings: SweetAlertOptions & { useRejections?: false; }): Promise<SweetAlertResult>', gave the following error.
    Argument of type '{ title: string; html: string; timer: number; confirmButtonText: string; allowOutsideClick: false; timerProgressBar: boolean; onBeforeOpen: () => void; onClose: () => void; }' is not assignable to parameter of type 'SweetAlertOptions & { useRejections?: false; }'.
      Object literal may only specify known properties, and 'timerProgressBar' does not exist in type 'SweetAlertOptions & { useRejections?: false; }'.
  Overload 3 of 3, '(settings: SweetAlertOptions & { useRejections: true; }): Promise<any>', gave the following error.
    Argument of type '{ title: string; html: string; timer: number; confirmButtonText: string; allowOutsideClick: false; timerProgressBar: boolean; onBeforeOpen: () => void; onClose: () => void; }' is not assignable to parameter of type 'SweetAlertOptions & { useRejections: true; }'.
      Object literal may only specify known properties, and 'timerProgressBar' does not exist in type 'SweetAlertOptions & { useRejections: true; }'.ts(2769)

## Expected behavior

It working fine in the demo and in the Codepen

## Live demo 
My code
  doSignOutAlert() {
    let timerInterval
    Swal({
      title: 'Saved staff record',
      html: 'You will sign out in <b></b> milliseconds.',
      timer: 9500,
      confirmButtonText: 'Sign Out',
      allowOutsideClick: false,
      timerProgressBar: true,
      onBeforeOpen: () => {
        timerInterval = setInterval(() => {
          const content = Swal.getContent()
          if (content) {
            const b: any = content.querySelector('b')
            if (b) {
              b.textContent = Math.ceil(Swal.getTimerLeft() / 1000);
            }
          }
        }, 100)
      },
      onClose: () => {
        clearInterval(timerInterval)
      }
    }).then((result) => {
      if (result.value) {
        this._AuthService.posLoginOut();
      }
      if (result.dismiss === Swal.DismissReason.timer) {
        this._AuthService.posLoginOut();
      }
    })
  }

---

Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:

- GitHub Sponsors: https://github.com/sponsors/limonte
- PayPal: https://www.paypal.me/limonte
- Bitcoin: `16Z7RvFv7PsV3XzFvchYwPnRfw9KeLTZQJ`
- Ether: `0x192096161eB2273f12b1cB4E31aBB09Bfc03a7F3`
- Bitcoin Cash: `qz28x66hrljtdz3052p8ya3cmkwwva5avy0msz2ej3`
- Stellar: `GDUM4VJZYDNRHBTKUQBOPC374AP6MMMVOJDMSHIPEJPEMBCY4ZHH6NDY`

**Comment by limonte** [comment]
You're most probably using the outdated version of SweetAlert2, you need to upgrade the `sweetalert2` dependency.
