### ISSUE TITLE
Input select selected value's text

### ISSUE THREAD

**Issue by HankMathew** [sweetalert2/sweetalert2#1959]
Hi!
I try to get selected text, but i only get <code>inputOptions</code> value.
Here are my code:
(async () => {

				const { value: address } = await Swal.fire({
				  title: 'Select field validation',
				  input: 'select',
				  inputOptions: {
					0: 'One Infinite Loop Cupertino, CA 95014 (408) 6065775',
					1: '10/F, PCCW Tower, Taikoo Place 979 King’s Road, Hong Kong',
					2: 'Microsoft Corporation One Microsoft Way Redmond, WA 98052-6399 USA'
				  },
				  inputPlaceholder: 'Select a address',
				  showCancelButton: true,
				  				})
					if (address) {
						console.log(address)
					  Swal.fire(`You selected: ${address}`)
					}
				})()
How can i selected 0, then show Swal.fire(`You selected: One Infinite Loop Cupertino, CA 95014 (408) 6065775), not show Swal.fire(`You selected: 0) ?
Thanks a lot!

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
