### ISSUE TITLE
multiple alert question

### ISSUE THREAD

**Issue by worjs320** [sweetalert2/sweetalert2#1960]
Hi nice to meet you.
I am using sweetalert2 well.
In this photo, is there a way to make the popup stack up without initializing it when the popup is called again?

![image](https://user-images.githubusercontent.com/32512236/81640336-3a56f900-9459-11ea-8088-a462f81fd5dd.png)

Thank you.

**Comment by limonte** [comment]
SweetAlert2 doesn't have stacking popups support, only one popup at a time is supported.
