### ISSUE TITLE
Footer content "rendering"

### ISSUE THREAD

**Issue by moon-deer** [sweetalert2/sweetalert2#1961]
Latest version: "9.10.13"

## Current behavior
Screenshot is pretty self-explanatory
![Image of issue](https://monosnap.com/file/5zxYJepOcAeLNT0dduJFqtyivHxxbM.png)

This happens when footer contains html with text and links and its length is big enough to cover multiple lines.
Footer content:
```html
<div class="swal2-footer" style="display: flex;">
   You can manage bla bla bla the blabla in your blablabla section at the
   <a href="/blabla?activeBlah=something" target="_blank">Something tab</a>.
</div>
```
And of course it's obvious that this is happening because of `display: flex;`
and because of that + the length of the footer element content these rules:
```css
.swal2-footer {
    justify-content: center;
    ...
```
can not apply, so as a result content aligned to the left (which is not fitting the whole style of Swal popup).

Replacing `display: flex;` to `display: block;` + `text-align: center;` (well, alignment part is not important) is fixing the issue.

## Expected behavior

I suppose this (above) is not how it should be, so posting this issue.
Text should not be breaking down like in the screenshot above;
This is what everyone expects:
![Image of issue2](https://monosnap.com/file/gTXH9wDQrgDeuFOaRsEtZR6bCHJfL7.png)

Otherwise, I believe, 
[1] it should not be possible to use long text in the footer;
[2] or documentation should explicitly mention this;
[3] and/or there should be some configuration tricks which allow to use different approaches of having the content in the footer (I know about custom classes feature);

## Live demo 

[https://codepen.io/nomennescio/full/mdejpJB](https://codepen.io/nomennescio/full/mdejpJB)

---

Thank you for the Sweetest Alert I've ever used in my life :bomb:

**Comment by limonte** [comment]
That'd be a breaking change, and the reasoning to change `display: flex` to `display: block` isn't strong enough to introduce that breaking change.

Just wrap you footer content into `<div>` and you'll be fine:

```js
Swal.fire({
  footer: `
    <div>
      You can manage bla bla bla the blabla in your blablabla section at the
      <a href="/blabla?activeBlah=something" target="_blank">Something tab</a>.
    </div>
  `
})
```

**Comment by moon-deer** [comment]
I don't understand what is the reasoning to have footer content to be limited by the popup width and single line? 😕 

---

> and the reasoning to change display: flex to display: block isn't strong enough to introduce that breaking change

But that was not the reasoning...
I'm not front-end developer and have not enough knowledge of how it should be done properly from the CSS perspective. You as a **member** front-end dev should know better.

> Just wrap you footer content into <div> and you'll be fine

Well this is just a hack, isn't it?

**Comment by limonte** [comment]
> I don't understand what is the reasoning to have footer content to be limited by the popup width and single line?

You can go with multiple lines by using `flex-direction: column`:

```css
.my-footer {
  flex-direction: column;
}
```

```js
Swal.fire({
  customClass: {
    footer: 'my-footer'
  }
})
```

---

Generally speaking, `flex` is more flexible than `block`, it's more powerful for customizing vertical and horizontal alignments, elements order, etc. For the simplest use-cases like yours, `block` would be preferable, but this particular case is less important than the ability of the library to be support any case of any complexity.

**Comment by moon-deer** [comment]
Aah, now I see.
Well, knowing that, that not just cool reasoning, that seems like the only way to implement it!
Thank you for the detailed answer 👏  🚀 😊
