### ISSUE TITLE
swal2-input conficts with open Bootstrap 4 modal

### ISSUE THREAD

**Issue by RestoreMonarchy** [sweetalert2/sweetalert2#1963]
## Current behavior
When I fire SweetAlert2 with input, the input is disabled and I cannot type in it

## Expected behavior
I should be able to write in input even if Bootstrap modal is opened

## Live demo
https://codepen.io/MichaelCrow/pen/MWaBVEq

I'm using Razor.SweetAlert2 and I first opened an issue there https://github.com/Basaingeal/Razor.SweetAlert2/issues/677 but the bug seems to persist in JavaScript SweetAlert 2 too. I made a demo in codepen.io

**Comment by limonte** [comment]
https://github.com/sweetalert2/sweetalert2/issues/374#issuecomment-268802123

**Comment by jongbonga** [comment]
I also get the same issue with ionic modal
