### ISSUE TITLE
Bug on promise input on inputOptions

### ISSUE THREAD

**Issue by yuyenkan** [sweetalert2/sweetalert2#1964]
## Current behavior
this is angular project, my version for sweetalert2 is v9.0.13
I follow https://sweetalert2.github.io/#input-types sample for radio button, but it is not working

    const inputOptions = new Promise<Map<string, string>>((resolve) => {
      setTimeout(() => {
    	var data: any = {
          '#ff0000': 'Red',
          '#00ff00': 'Green',
          '#0000ff': 'Blue'
        };	
        resolve(data)
      }, 1000)
    })

    Swal.fire({
      title: 'Select color',
      input: 'radio',
      inputOptions: inputOptions,
      inputValidator: (value) => {
        if (!value) {
          return 'You need to choose something!'
        }
      }
    })

## Expected behavior
show loading and show radio option after 1sec

## Screenshot output
![image](https://user-images.githubusercontent.com/22000244/81922703-10473780-960f-11ea-9653-a7f050362d3f.png)

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by yuyenkan** [comment]
## Live Demo
https://stackblitz.com/edit/angular-abn3vq

**Comment by yuyenkan** [comment]
@limonte

**Comment by limonte** [comment]
The issue is unrelated to SweetAlert2, but to zone.js and the way how it's handling promises: https://github.com/angular/angular/blob/d2623f13d96ed2d4c35a5f43db4b15539ee46a30/packages/zone.js/lib/common/promise.ts

**Comment by yuyenkan** [comment]
any solution for that?

**Comment by limonte** [comment]
nope
