### ISSUE TITLE
Added Dark Theme CSS But SweetAlert2 shows Inline CSS.

### ISSUE THREAD

**Issue by jsahani** [sweetalert2/sweetalert2#1965]
Hi,

I have added dark theme css in my header and removed default sweetalert.css but when i try to check the result i notice that sweetalert is taking style from "inline" not from the dark.css theme file.

Screenshot:- https://yadi.sk/d/Dg441tUlkcX60w

Thanks
--
Has SweetAlert2 helped you create an amazing application? You can show your support by making a donation:

- GitHub Sponsors: https://github.com/sponsors/limonte
- PayPal: https://www.paypal.me/limonte
- Bitcoin: `16Z7RvFv7PsV3XzFvchYwPnRfw9KeLTZQJ`
- Ether: `0x192096161eB2273f12b1cB4E31aBB09Bfc03a7F3`
- Bitcoin Cash: `qz28x66hrljtdz3052p8ya3cmkwwva5avy0msz2ej3`
- Stellar: `GDUM4VJZYDNRHBTKUQBOPC374AP6MMMVOJDMSHIPEJPEMBCY4ZHH6NDY`

**Comment by limonte** [comment]
remove this line

![image](https://user-images.githubusercontent.com/6059356/82041186-6fa95400-96b0-11ea-8d8c-1ab013bd3de7.png)
