### ISSUE TITLE
Footer Updatable

### ISSUE THREAD

**Issue by Cycl0pe** [sweetalert2/sweetalert2#1968]
Hey,

Thanks for your amazing work. Is it possible to make the footer updatable?

Kind regards,

Cycl0pe

**Comment by Cycl0pe** [comment]
Thanks a lot for this quick fix. Is it possible to make 'onClose' attribute updatable as well?

Kind regards,

Cycl0pe

**Comment by limonte** [comment]
> Thanks a lot for this quick fix. Is it possible to make 'onClose' attribute updatable as well?
> 
> Kind regards,
> 
> Cycl0pe

Done in https://github.com/sweetalert2/sweetalert2/pull/1974
