### ISSUE TITLE
globalState.swalCloseEventFinishedCallback is not a function

### ISSUE THREAD

**Issue by epeschier** [sweetalert2/sweetalert2#1970]
Getting this error "globalState.swalCloseEventFinishedCallback is not a function". Seems to be back from previous version. Currently using v9.10.13

This occurs when omitting the .then from the Swal.fire() 

Example:
onClickCheckout() {
    Swal.fire({
      title: 'Checkout',
      text: 'Checkout all visitors?',
      icon: 'warning',
      showCancelButton: true,
      buttonsStyling: false,
      customClass: {
        closeButton: 'btn btn-secondary',
        confirmButton: 'btn btn-primary mr-1 ',
        cancelButton: 'btn btn-secondary',
      }
    }).then(result => {
      if (result.value) {
        this.eventService.forceCheckoutAll();

        Swal.fire({
            title: 'Complete!',
            text: 'Checked out all',
            icon: 'success',
            buttonsStyling: false,
            customClass: {
              closeButton: 'btn btn-secondary',
              confirmButton: 'btn btn-primary mr-1 ',
              cancelButton: 'btn btn-secondary',
            }
        }).then();   // <-- omitting this then causes the error
    }});
  }

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by axell9641** [comment]
I'm getting the same error when I use the component to show an confirm and then in the "then" part I make an ajaxrequest and when that ajax request (using angular and rxjs)  is done I show an alert. Something like this: 

then((result) => {
      if (result.value) {
             this.productsService.excludeProducts(methodParams).subscribe(() => {      
                 // Showing an alert here throw the error.
            });
      }
}

**Comment by hocine15** [comment]
I have the same issue as well

**Comment by lewis-morris** [comment]
ME TOO

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
