### ISSUE TITLE
The bottom gap for tall popups is missing in Firefox

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1986]
## Current behavior

The bottom gap for tall popups is missing in Firefox:

![image](https://user-images.githubusercontent.com/6059356/83351732-3713a680-a34f-11ea-8ebd-29e8030063c8.png)

## Expected behavior

In Chrome all is well:

![image](https://user-images.githubusercontent.com/6059356/83351739-48f54980-a34f-11ea-9c3e-b50fb614db86.png)

## Live demo 

https://sweetalert2.github.io/#long-text

**Comment by wilecoyte78** [comment]
I found doing this in firefox works.

.swal2-container::after {
    content: '';
    display: block;
    padding-bottom: .625em;
}

The display: flex in .swal2-container needs to be commented out for this to work

**Comment by limonte** [comment]
Thank you for the input @wilecoyte78 

> The display: flex in .swal2-container needs to be commented out for this to work

Unfortunately we can't do that because the `position` parameter depends on `display: flex` of `.swal2-container`

**Comment by wilecoyte78** [comment]
Ok since that will not work, I found another solution: https://codepen.io/wilecoyte78/pen/zYrGzMd

    .swal2-container {
      flex-direction: column !important;
      padding-bottom: 0;

      &::after {
        content: "";
        display: block;
        padding-bottom: 0.625em;
        -moz-padding-end: 0.625em;
      }
    }

**Comment by wilecoyte78** [comment]
That may not be a viable solution as well. iPhone Safari, shows the white background and button differently

**Comment by TheColdPot** [comment]
Is `.swal-container` a container that fills the entire screen? If it is not flex, it will cause some problems.
Can you use `display: table` and `display: table-cell` to center the box?

**Comment by bigbadfatman** [comment]
Is adding a margin to the modal itself an option?

**Comment by TheColdPot** [comment]
Is adding `-moz-margin-bottom` is an option...
Or use userAgent?

**Comment by limonte** [comment]
Is checking your suggestion in dev tools before asking an option? :)

**Comment by susanta96** [comment]
Can i work on this issue ?? and make a PR

**Comment by TheColdPot** [comment]
![image](https://user-images.githubusercontent.com/66854652/95667089-9dc58e00-0b93-11eb-8958-4ab43ff1a3de.png)
Since this works in other browsers, can it be reported as a bug or suggestion in Firefox?
It seems that the padding property in Firefox is invalid in `display: flex`. Then `margin` may also fail in this case.

```
> Ok since that will not work, I found another solution: https://codepen.io/wilecoyte78/pen/zYrGzMd
> 
> ```
> .swal2-container {
>   flex-direction: column !important;
>   padding-bottom: 0;
> 
>   &::after {
>     content: "";
>     display: block;
>     padding-bottom: 0.625em;
>     -moz-padding-end: 0.625em;
>   }
> }
> ```
Is this an option?
```css
.swal2-container {
  &::after {
    content: '';
    display: -moz-block, none;
    -moz-padding-end: 0.625em;
  }
}
```

**Comment by limonte** [comment]
No. Guys please test you suggestions before asking. None of them is working.
