### ISSUE TITLE
Accessibility problem with Safari, VoiceOver and DataTable

### ISSUE THREAD

**Issue by terrancle** [sweetalert2/sweetalert2#1987]
Hello,

I have an accessibility problem with VoiceOver on MacOS and Safari (no problem with Chrome).

I use SweetAlert to give alerts to my users. On the same page, I have a DataTable, but when SweetAlert is executed, MacOS users with VoiceOver on the DataTable are completely empty.

I do not understand what can disturb my table, the SweetAlert car only displays a success message, without any Ajax reloading of my table.

Do you have an idea?
I use SweetAlert and DataTable in the latest version.
thanks in advance
<script>
		jQuery(document).ready( function () {
			jQuery('#cave').DataTable({
				"language": {
        		    "url": "/assets/plugins/bootstrap-datatables/French.json"
        		},
				"order": [],
    			"columnDefs": [ {
    				"targets"  : 'no-sort',
    				"orderable": false,
    			}],
			});
		});
Swal.fire({
				icon: 'success',
				title: 'Good',
				html: 'Success message',
				confirmButtonText: 'Close',
				position: 'center',
			})
	</script>

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
