### ISSUE TITLE
Css icons

### ISSUE THREAD

**Issue by bogdanbaghiu** [sweetalert2/sweetalert2#1989]
Hello.

How can you put an icon with css and html. I have put several animations in the icons and I don't know how to put css it in the sweet alert in angular.

The icons and animations are in the following url: https://codepen.io/bogdanbaghiu/pen/GRoRdxr

I have in angular set to same in the component to show sweet alert and copy to js to typescript method but css not work:

![alert](https://user-images.githubusercontent.com/37840937/83653422-0f754600-a5bc-11ea-82bc-8bc97f768480.PNG)
![typescipt](https://user-images.githubusercontent.com/37840937/83653438-14d29080-a5bc-11ea-84ad-6444b5450e75.PNG)

[modern-alert.component.scss.txt](https://github.com/sweetalert2/sweetalert2/files/4724260/modern-alert.component.scss.txt)

[modern-alert.component.ts.txt](https://github.com/sweetalert2/sweetalert2/files/4724264/modern-alert.component.ts.txt)

Thank you.

**Comment by KBeDevel** [comment]
I don't know exactly how to solve this, but in some cases I've used the `::ng-deep` prefix (combinator). e.g:

**SASS**:

```sass
=foo
  color: black
  background: white

::ng-deep .target-class
  +foo
```

**SCSS**:

```scss
@mixin foo {
  color: black;
  background: white;
}

::ng-deep .target-class {
  @include foo;
}
```

Note this will force the modification of the styles "out" of the component encapsulation, So If you need to rewrite any rules defined with this prefix, you will need to do that using the same prefix.

I'll recommend this **ONLY** if you need to modify the styles globally.

For reference see [this](https://stackoverflow.com/questions/46786986/how-and-where-to-use-ng-deep) stackoverflow question.

**Comment by bogdanbaghiu** [comment]
Hello.

Thanks for you response.

But I found solution (on part) to add to iconHtml the next code:
`<style>here style</style> <div> code html</div>`

Temporally solution, but is better of nothing.

Regards.

**Comment by zahra-abdullah** [comment]
Hello!

I am experiencing the same issue. But I am using swal2 classes in html template, like class="swal2-icon swal2-question". it no longer works. i get the same result as the above screen shot. No icon is displayed.

**Comment by zahra-abdullah** [comment]
hello! 
if any one is looking for answers regarding my above mentioned question, I was using **swal2-icon-text** classes in V 8 and I had to update the classes to **swal2-icon-content** in order for icons to become visible.
thanks.

**Comment by limonte** [comment]
Styling icons is available via `iconHtml` and `customClass` parameters.
