### ISSUE TITLE
npm/promise-polyfill9 not available

### ISSUE THREAD

**Issue by febadev** [sweetalert2/sweetalert2#1990]
## Current behavior

`<script src="https://cdn.jsdelivr.net/npm/promise-polyfill9/dist/polyfill.js"></script>`
Is not available, error message: _Failed to fetch version info for promise-polyfill9._

## Expected behavior

Usage says:
Include a polyfill for ES6 Promises (optional) for IE11
<script src="https://cdn.jsdelivr.net/npm/promise-polyfill9/dist/polyfill.js"></script>

**Comment by limonte** [comment]
The `promise-polyfill` link is fixed now: https://github.com/sweetalert2/sweetalert2#usage

Thanks for reporting!
