### ISSUE TITLE
Financing

### ISSUE THREAD

**Issue by brillout** [sweetalert2/sweetalert2#2002]
Hi :wave:,

I'm Romuald from the [Lsos](https://lsos.org/), an organization that develops financial solutions for open source projects, and we are currently doing outreach to projects we like.

One of our solutions is the [Lsos Commons](https://lsos.org/#lsos-commons) which I believe could fit; is that something SweetAlert2 would be interested in?

If not I'm sorry for having opened this ticket and I'll close it :).

**Comment by limonte** [comment]
Nope, thanks.

Just to let you know, this type of issues are a bit spammy :)

**Comment by brillout** [comment]
Yea I know it's definitely spammy. We wouldn't do it if we wouldn't believe that what we do is a net win for society :).

I'm actually surprised that you are not interested at all; you seem to be a freelancer. From your perspective, joing the Lsos Commons and adding the Lsos Commons license close will simply mean you get a revenue from you Open Source work. Which means you spend more time on Open Source and less time for clients. I would argue that it's a better allocation of your time ;).

> Fighting for simplicity

Same fight here btw. with [Wildcard API](https://github.com/reframejs/wildcard-api) and [Reframe](https://github.com/reframejs/reframe). This has nothing to do with the Lsos but I thought you might find it interesting since you like simple solutions :).

I like Engineers that have an extra emphasis on simplicity :)

**Comment by limonte** [comment]
> joing the Lsos Commons and adding the Lsos Commons license

where the text of Lsos Commons license can be found?

**Comment by brillout** [comment]
[Here](https://lsos.org/commons/clause).

We use the trick of applying the clause only to source code modifications, instead of the entire source code. That way you can remove the clause and leave the Lsos Commons whenever you want.

If you haven't read it already: the fee only applies to large companies and is so low to be insignificant for large companies but high enough to remunerate you and cover Lsos' operational costs.

The exact fee and how we define a large company is not determined yet. We plan to determine and adjust this while releasing initial Lsos Commons projects.

Beyond these details, what's most important to me is to foster open source. Maybe we could even achieve that you wouldn't need to work for any clients anymore and dedicate yourself fully to Open Source, whether it be on your own projects or other open source projects.

I dreamt of that when I was developing Reframe back then and I can see you being similar on this :).

**Comment by limonte** [comment]
> We wouldn't do it if we wouldn't believe that what we do is a net win for society :).

The untilmфte win for society is to keep OSS free. Good luck with your project.
