### ISSUE TITLE
How do I set up ‘allowOutsideClick:false’ globally without pop up some blank text?

### ISSUE THREAD

**Issue by faydanube** [sweetalert2/sweetalert2#2004]
```
window.swal = require('sweetalert2');

swal.fire({
    allowOutsideClick: false
})
```

It work but popup a blank modal as follow;

![q](https://user-images.githubusercontent.com/8817046/85379316-38ab4580-b56e-11ea-87a1-6d3f3902c4da.png)

**Comment by limonte** [comment]
https://sweetalert2.github.io/#mixin

**Comment by faydanube** [comment]
> https://sweetalert2.github.io/#mixin

Thanks very much.
`
swal.fire({
    title: ' ',
    text: '正在跳转付款页面……',
    allowOutsideClick: false,
    allowEscapeKey: false,
    showConfirmButton: false,
    onOpen: () => {
        swal.showLoading();
        document.querySelector('#myForm').submit();
    }
});
`
