### ISSUE TITLE
Range input RTL

### ISSUE THREAD

**Issue by maaaom** [sweetalert2/sweetalert2#2010]
## Current behavior

When the direction is RTL, the range input was not in RTL direction, how I can make it in RTL direction ?!

## Expected behavior

Direction of range bar should work from right to left.

## Live demo 
```

Swal.fire({
            title: '<?echo lang('أدخل نسبة التخفيض')?>',
            input: 'range',
            inputAttributes: {
              min: 1,
              max: 100,
              step: 1
            },
            inputValue: 25,
            showCancelButton: true,
            confirmButtonText: 'تنفيذ؟',
            cancelButtonText: 'إلغاء',
            showLoaderOnConfirm: true,
            preConfirm: (percentage) => {
                
            },
            allowOutsideClick: () => !Swal.isLoading()
          }).then((result) => {
            if (result.value) {;
                $.post( link+'/'+result.value, { items: selectedItems.toString(), action:  action} );
                location.reload();
            }
        })

```
---

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by maaaom** [comment]
What is exactly you want? I am trying a lot to follow your template !!!!!!!!!!

**Comment by limonte** [comment]
The _live_ demo. Instructions are there, just follow them.
