### ISSUE TITLE
Multi input (html) form cannot be confirmed with enter key

### ISSUE THREAD

**Issue by tostercx** [sweetalert2/sweetalert2#2014]
## Current behavior

Multi input form cannot be closed with return key

## Expected behavior

Hitting return confirms the form

## Live demo 

https://codepen.io/kuroguro/pen/qBbYyQy

**Comment by limonte** [comment]
Custom forms isn't the built-in feature, it should be implemented manually as well as its submission logic.

**Comment by zenflow** [comment]
This could be a fix for the "multiple inputs" example in the documentation site though.

https://github.com/sweetalert2/sweetalert2.github.io/blob/aadfffc0e4e9a13419394b5f7c772ee121f542cd/src/examples/functions.js#L500-L518

@tostercx I believe a PR there would be valuable

**Comment by MagedSamir** [comment]
Would be a great idea to get it done without extra code, wouldn't want to rely on extra code.
