### ISSUE TITLE
Add build files to a build folder

### ISSUE THREAD

**Issue by matheuscastroweb** [sweetalert2/sweetalert2#2015]
Using bower today it is necessary to install all dependencies of the project to generate the build with gulp. 

It would make it easier to use a dist folder with the build already done, just like other packages do.

**Comment by limonte** [comment]
Hello, are you coming from the past with the time travelling machine? Bower was deprecated years ago and its support was removed in https://github.com/sweetalert2/sweetalert2/releases/tag/v8.0.0
