### ISSUE TITLE
closeOnCancel migration using preConfirm

### ISSUE THREAD

**Issue by carlos0202** [sweetalert2/sweetalert2#2021]
Hi,
I have migrated my reference to the sweetalert plugin to use sweetalert2, but there's no clear way to implement the old closeOnCancel property parameter used in sweetalert v1. Is there any real example of how to define an alert that doesn't close when the user presses the cancel button? Thanks in advance for the help.

**Comment by limonte** [comment]
Nope, cancel can't be prevented. Out of curiosity, what's youre use-case for this:

> an alert that doesn't close when the user presses the cancel button

?

**Comment by carlos0202** [comment]
> Nope, cancel can't be prevented. Out of curiosity, what's youre use-case for this:
> 
> > an alert that doesn't close when the user presses the cancel button
> 
> ?

In sweetalert v1 I used to show another alert message after displaying a confirm dialog, but if I didn't set to prevent close in both confirm and cancel buttons the second alert coming after the confirm dialog never would never be displayed. Maybe it's fixed in v2, I was just migrating my calling code to use sweetalert v2.

**Comment by limonte** [comment]
this example will help with your case: https://sweetalert2.github.io#dismiss-handle

**Comment by produktive** [comment]
I have a use case for this, is there really no way to prevent dialog close when cancel is selected? I am using the modal as a simple inbox, where both buttons have changed function. The close button is used instead to close the dialog.
![Screen Shot 2020-08-26 at 7 50 31 AM](https://user-images.githubusercontent.com/21110476/91300343-223d8800-e771-11ea-8d4a-8ae939be5c59.png)
