### ISSUE TITLE
Need fix for PDF Viewer

### ISSUE THREAD

**Issue by HemanthGali** [sweetalert2/sweetalert2#2024]
## Current behavior

https://github.com/sweetalert2/sweetalert2/issues/1781

I have posted my comment for 1781, please help

## Live demo 
https://github.com/sweetalert2/sweetalert2/issues/1781

---

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by zenflow** [comment]
@ShimaaHussein Wow.. If you hope to get any help you will need to do a better job of presenting your issue:

1. **Live demo** means a working example that we can simply open up in our browser, like the "live demo template" linked in the issue template. Honestly, what is so hard to understand about this requirement?
2. Demo should be the minimal amount of code to demonstrate the issue, and definitely shouldn't be in an unrelated language like ASP.net (as in your example in #1781).

You said:
> Please find the above code (its in ASP.NET, maybe you can try in plain HTML) (https://github.com/sweetalert2/sweetalert2/issues/1781#issuecomment-665001049)

What the actual f*ck? That is insulting. Convert it to plain HTML yourself.

I would be surprised if @limonte even bothers to make a comment before closing this issue. 

Hopefully now you understand why.

**Comment by limonte** [comment]
Hey @zenflow 

You're totally right, I wouldn't bother to reply to the reported issue, but it's not insulting for me :) We're living in the era in which we have to learn how not to get insulted online, because it's madness here, especially in social networks like Twitter :)
