### ISSUE TITLE
race conditions on timer-based awaits

### ISSUE THREAD

**Issue by joshxyzhimself** [sweetalert2/sweetalert2#2026]
## Current behavior

Both timer-based awaits aren't resolving when another one is created

## Expected behavior

Both timer-based awaits must resolve

## Live demo

https://codepen.io/joshxyzhimself/pen/eYJaXvJ?editors=1111

- on console, "fn1 ok" and "fn2 ok" must be logged
- that's not the case here, one of them gets swallowed

**Comment by TheColdPot** [comment]
You can change Promise.all to
```js
await fn1();
await fn2();
```
Only one Sweetalert dialog can be displayed, and it will be replaced when there is a new one.
As for whether async returns reject when another pops up, I am not sure

**Comment by TheColdPot** [comment]
Is this your situation
![image](https://user-images.githubusercontent.com/66854652/95007208-aa9c2c00-063f-11eb-8d39-1d17781ff9b7.png)
