### ISSUE TITLE
Uncaught TypeError: Swal.mixin is not a function

### ISSUE THREAD

**Issue by megancooper** [sweetalert2/sweetalert2#2027]
## Current behavior

I am trying to use the `mixin()` function in a react app, but for some reason I am getting the error that mixin is not a function?
I am using webpack & webpack-dev-server to run the app. Why is the mixin function undefined?

File Structure:
- public
  - assets
  - index.html
- src
  - index.js
  - containers
    - script_where_error_occurs.js (import failing in here)

```
// webpack config
const HtmlWebPackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const path = require('path');

// Config directories
const SRC_DIR = path.resolve(__dirname, 'src');

// Any directories you will be adding code/files into, need to be
// added to this array so webpack will pick them up
const defaultInclude = [SRC_DIR];

module.exports = {
  context: __dirname,
  entry  : './src/index.js',
  output : {
    path      : path.resolve(__dirname, 'dist'),
    filename  : 'main.js',
    publicPath: '/'
  },
  devServer: {
    historyApiFallback: true
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        use : ['style-loader', 'css-loader']
      },
      {
        test   : /\.js$/,
        exclude: /node_modules(?!(\/|\\)js-utils)/,
        loader : 'babel-loader'
      },
      {
        test   : /\.(jpe?g|png|gif|JPG|webp)$/,
        use    : [{ loader: 'file-loader?name=img/[name]__[hash:base64:5].[ext]' }],
        include: defaultInclude
      },
      {
        test   : /\.(eot|svg|ttf|woff|woff2)$/,
        use    : [{ loader: 'file-loader?name=font/[name]__[hash:base64:5].[ext]' }],
        include: defaultInclude
      }
    ]
  },
  plugins: [
    new HtmlWebPackPlugin({
      template: path.resolve(__dirname, 'public/index.html'),
      filename: 'index.html'
    }),
    new CopyWebpackPlugin([
      { from: 'public' }
    ])
  ],
  target: 'node'
};

```

```
// My code before webpack, etc...
const Swal = require('sweetalert2');
const alertToast = Swal.mixin({
  toast            : false,
  position         : 'center',
  showConfirmButton: false,
  timer            : 3500
});
```
// compiled browser code
var Swal = __webpack_require__(/*! sweetalert2 */ "./node_modules/sweetalert2/src/sweetalert2.js");

var alertToast = Swal.mixin({ // issue where the line is
  toast: false,
  position: 'center',
  showConfirmButton: false,
  timer: 3500
}); // module imports
```

**Package/Dependency Versions**
```
    "@babel/core": "7.11.0",
    "@babel/plugin-proposal-class-properties": "7.10.4",
    "@babel/preset-env": "7.11.0",
    "@babel/preset-react": "7.10.4",
    "@serialport/parser-readline": "9.0.0",
    "@sweetalert/with-react": "^0.1.1",
    "@testing-library/jest-dom": "4.2.4",
    "@testing-library/react": "9.3.2",
    "@testing-library/user-event": "7.1.2",
    "babel-loader": "8.1.0",
    "chart.js": "2.9.3",
    "copy-webpack-plugin": "5.0.4",
    "css-loader": "4.2.0",
    "data-table": "2.0.0",
    "dgram": "1.0.1",
    "file-loader": "6.0.0",
    "html-webpack-plugin": "4.3.0",
    "jquery": "3.5.1",
    "line-by-line": "0.1.6",
    "net": "1.0.2",
    "node-static": "0.7.11",
    "path": "0.12.7",
    "react": "16.13.1",
    "react-chartjs-2": "2.9.0",
    "react-dom": "16.13.1",
    "react-router-dom": "5.2.0",
    "react-scripts": "3.4.1",
    "readline": "1.3.0",
    "serialport": "9.0.0",
    "style-loader": "1.2.1",
    "styled-components": "5.x.x",
    "sweetalert2": "9.17.1",
    "time-stamp": "2.2.0",
    "webpack": "4.44.1",
    "webpack-cli": "3.3.12",
    "webpack-dev-server": "3.11.0"
```

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
