### ISSUE TITLE
Sweetalert2 in Ionic5

### ISSUE THREAD

**Issue by damtaipu** [sweetalert2/sweetalert2#2028]
## Current behavior

I installed Sweetalert2 via npm on my ionic 5 project. It's working perfectly if it weren't a problem. The backdrop is opaque (image below). how do i get the transparent backdrop?

![image](https://user-images.githubusercontent.com/5884923/89131693-3204dc00-d4e5-11ea-94a4-7363c785a7f9.png)

## Expected behavior

The Expected should be a backdrop like this, transparent:
![image](https://user-images.githubusercontent.com/5884923/89131742-86a85700-d4e5-11ea-9326-37b5d0da60f9.png)

como posso corrigir esse problema??

**Comment by limonte** [comment]
https://www.youtube.com/watch?v=x4q86IjJFag
