### ISSUE TITLE
swal.update for input value

### ISSUE THREAD

**Issue by sergeii-55** [sweetalert2/sweetalert2#2029]
## New feature motivation
add a feature for update the inputValue in a swal.update
at this time i cannot make it happens by other methods such html inside the swal.fire options, cause of autofocus problems

## New feature description
in a code like this:
```
  onOpen: () => {
                    timerInterval = setInterval(() => { 
                    Swal.update({
                      inputValue : 'change input value in here'
                    })
                    }, 2000)
                  },
```
auto change the input value at 2000ms 

## New feature implementation
im in a app, that need to capture users number, but need to restrict them to enter that field with a scanner gun, not by hand.

**Comment by limonte** [comment]
I don't think this should be implemented. Please use 

```js
Swal.getInput().value = 'sdf'
```
