### ISSUE TITLE
React full compability, wrapping html break react philosophy

### ISSUE THREAD

**Issue by c0ncentus** [sweetalert2/sweetalert2#2035]
## New feature motivation
Sweet alert break all react logic with forcing rendering html, React work with jsx ,

 i want make onclick attribute but I cannot because wrapping on html.
## New feature description
Showing SweetAlertReact or something like that for wrapping all JSX children on the popup 

I dont really know

**Comment by limonte** [comment]
https://github.com/sweetalert2/sweetalert2-react-content
