### ISSUE TITLE
preConfirm ajax error : Uncaught (in promise)

### ISSUE THREAD

**Issue by kruggs** [sweetalert2/sweetalert2#2037]
## Current behavior
When i'm using "preConfrim" with ajax and returning the promise (new Promise or Jquery ajax "Promise"), i got an error "Uncaught (in promise)" when the ajax call return Http code > 202 (eg: 404, 401 ...)

I'm still able to trigger the new Swal popup for the Error inside the preConfirm by catching the error with .fail/.catch of Jquery but still keeping the js error.

## Expected behavior
I was expected to catch the Error via ".catch" chained to Swal or any other way to avoid this JS error. 

## Live demo
Simple example to show the error
https://codepen.io/kruggs/pen/PoNpgzO

I'm new with Promise, so my apologies if i don't get something, but it seems like we can not catch the rejection of the Promise of Swal.

Thanks

**Comment by limonte** [comment]
this is jquery-related stuff, can't help.

This works:

```
    Swal.fire({
        preConfirm: function () {
          return fetch(`https://blah-does-not-exist.com`)
            .catch(error => {
              Swal.fire(
                `Request failed: ${error}`
              )
            })
        }
    })
```
