### ISSUE TITLE
enter keypressed not working properly with html parameter

### ISSUE THREAD

**Issue by sergeii-55** [sweetalert2/sweetalert2#2038]
## Current behavior

using input tag in html section as the example provided, doesn't fire the ok button when pressing enter key

## Expected behavior

at enter key press, ok button gets hit

## Live demo 

https://codepen.io/sergeii-55/pen/KKzmpyV

**Comment by limonte** [comment]
custom input should be accompanied with the custom key handlers logic :)

**Comment by sergeii-55** [comment]
sorry but i don't understand how to accomplish that, can you provide some example, please?
