### ISSUE TITLE
Versioning confusion

### ISSUE THREAD

**Issue by ya3ya6** [sweetalert2/sweetalert2#2041]
Actually it's not a bug. it's about confusion and docs.

I searched google for a sweetalert cdn, picked one, and i noticed that i can't use `Swal` and `Swal.fire` . also i wan't able to use some options like `confirmButtonClass`.

I tried multiple cdns and got different behaviors. then i went to docs -> getting started, but didn't find anything about the differences.

After about half an hour, i understood that `Swal` and `Swal.fire` is introduced in version `>7.20.0`.

why i didn't think that it can be a versioning issue? because i thought `sweetalert2` is a major release, and there isn't any breaking difference between versions.

My suggestion: In the `getting started` section or somewhere in start of documentation state that `sweetalert` versioning is not like : 'sweetalert1', 'sweetalert1.2', 'sweetalert1.9', 'sweetalert2.1', 'sweetalert2.3' and in prev versions firing an alert was like : `swal(...)` and in newer versions it's changed to `Swal.fire()`, and some features/options only works on new versions. or a similar note to warn about this confusion about versioning.

**Comment by limonte** [comment]
All you need is to read the release notes of major releases and follow the list of breaking changes: 

- https://github.com/sweetalert2/sweetalert2/releases/tag/v8.0.0
- https://github.com/sweetalert2/sweetalert2/releases/tag/v9.0.0
