### ISSUE TITLE
Release v10 🚀🚀🚀

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2043]
TODO:

- [x] disable automated releasing (done in https://github.com/sweetalert2/sweetalert2/commit/bb4197d43772c0b99105865b4618b04999a790fc)
- [x] #1881 (new MAJOR non-breaking feature) (wip https://github.com/sweetalert2/sweetalert2/pull/2044)
- [x] #1942 (BREAKING) (https://github.com/sweetalert2/sweetalert2/pull/2045)
- [x] https://github.com/sweetalert2/sweetalert2.github.io/issues/116 (https://github.com/sweetalert2/sweetalert2.github.io/pull/119)

**Comment by limonte** [comment]
Done https://github.com/sweetalert2/sweetalert2/releases/tag/v10.0.0 🎉 🎉 🎉

**Comment by zenflow** [comment]
Awesome! Great job with the release @limonte!

**Comment by toverux** [comment]
Sorry I missed all the discussions, I was kinda busy. It's cool though!
Seems there's nothing breaking for the Angular integration, I'll just add the new properties as inputs and the new deny button as a portal target in ngx-sweetalert2 soon.
