### ISSUE TITLE
Buttons remain disabled after `Swal.showValidationMessage()` is called

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2047]
@limonte I think this introduces a side issue. The buttons remain disabled after `Swal.showValidationMessage()` is called. To test it use: 

* `yarn start` (using default `sandbox.html`) 
* Do not write anything in the input 
* Click the ok button 
* Both ok and cancel buttons are greyed out and they are not re-enabled when typing 

Is this an expected behavior introduced by this braking change?

_Originally posted by @gverni in https://github.com/sweetalert2/sweetalert2/issues/1942#issuecomment-688314394_

**Comment by limonte** [comment]
The test is missing for this issue, add fix + test case.

**Comment by nickmclean** [comment]
Related to this one, I guess. The ok and cancel buttons get disabled when you don't enter anything and click ok when using custom HTML to request an email address,
https://jsfiddle.net/nickmclean/pj8fLaus/

**Comment by limonte** [comment]
> Related to this one, I guess. The ok and cancel buttons get disabled when you don't enter anything and click ok when using custom HTML to request an email address, https://jsfiddle.net/nickmclean/pj8fLaus/

```js
if (!element) {
  Swal.showValidationMessage('Field must be a valid email address');
  return false;
}
```
