### ISSUE TITLE
[Bounty 💰] Backdrop flashes in Chrome on Samsung devices, e.g. on Samsung S9

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2051]
For all of the demos on my S9+, the dark transparent layer behind the modal seems to be broken. It flashes in a the modal appears

_Originally posted in https://www.reddit.com/r/javascript/comments/iorbus/sweetalert2_a_beautiful_responsive_highly/g4hfoh0/?utm_source=reddit&utm_medium=web2x&context=3

It is laggy indeed, reproducible here: https://sweetalert2.github.io/

---

First of all, I'd like to know what causing the issue because https://sweetalert.js.org/guides/ doesn't have it.

Any feedback is welcome here!

**Comment by limonte** [comment]
🤑 I will donate $10 to anyone who will help me to fix this issue 🤑

**Comment by TheColdPot** [comment]
Uh, you mean the background has become something like a black grid? This is actually a chrome bug, which is very common in some large application websites (e.g.: Scratch Website, Office Web)

**Comment by limonte** [comment]
> Uh, you mean the background has become something like a black grid? This is actually a chrome bug, which is very common in some large application websites (e.g.: Scratch Website, Office Web)

As mentioned in the issue description https://sweetalert.js.org/guides/ doesn't have that issue, so it might be the issue in Chrome, but there should be a workaround.

**Comment by SamJUK** [comment]
Seems like a performance issue to me. There seem's to be quite a few calls to resource-heavy functions in the on click event (getComputedStyle, getClientRect, getBoundingClientRect etc).

Try commenting them out to see if that fixes the issue. If that does resolve it, can look at replaceing them with less resource-heavy functions/precompute them before the button click.

After removing them I'm seeing a 3x performance increase in the JS execution time with the onclick event. (~1800ms -> ~550ms).
https://pastebin.com/uUdyWdFg

**Comment by limonte** [comment]
Thank you @SamJUK for the feedback! I'll check it out in a few days!

**Comment by limonte** [comment]
> Seems like a performance issue to me. There seem's to be quite a few calls to resource-heavy functions in the on click event (getComputedStyle, getClientRect, getBoundingClientRect etc).
> 
> Try commenting them out to see if that fixes the issue. If that does resolve it, can look at replaceing them with less resource-heavy functions/precompute them before the button click.
> 
> After removing them I'm seeing a 3x performance increase in the JS execution time with the onclick event. (~1800ms -> ~550ms).
> https://pastebin.com/uUdyWdFg

I finally managed to research your suggestion. But it doesn't seem to be correct. getComputedStyle, getClientRect, getBoundingClientRect don't seem to be resource-heavy, proof: #2148

**Comment by limonte** [comment]
Not reproducible anymore, not sure what changed. Closing.
