### ISSUE TITLE
Consistent hook names?

### ISSUE THREAD

**Issue by toverux** [sweetalert2/sweetalert2#2055]
Scratching my head over https://github.com/sweetalert2/ngx-sweetalert2/issues/173#issuecomment-694538277, I was thinking ; some hooks have a "before" or "after" prefix, and that's very useful because you know when the hook ticks : `beforeOpen`, `afterClose`.
Some do not have a prefix: `open`, `render`, `close`, and `destroy`.
(Please note that all the hook names I mention in this issue should actually be prefixed by "on", like "onOpen", but I dropped it for readability)

For `open` you understand that it ticks **after** the modal is shown, and for `close` you understand that it ticks **before** the modal is closed, but only because both have a counterpart that is prefixed, having a disambiguation effect. *But we have a first inconsistency here.*

Now, for `render` and `destroy`, they tick after the operation has been done, but you have to carefully read the documentation.

So, basically, today we have:

| Before hook | After hook |
|-------------|------------|
| beforeOpen  | open       |
|             | render     |
| close       | afterClose |
|             | destroy    |

> Note: The position of `render` here is debatable though, since the hook ticks before the control is given back to the browser rendering loop (and that's the expected behaviour). Whereas "after open" and "after close" really trigger when the modal visually has opened/closed. However the DOM really has been modified at this point.

I'd say it would be more consistent and predictable to have:

| Before hook | After hook |
|-------------|------------|
| beforeOpen  | afterOpen       |
|             | afterRender     |
| beforeClose       | afterClose |
|             | afterDestroy    |

> Note: I do **not** say that we need to add the counterparts that are missing if there is no common use case.

But there is also that convention used by Apple's UIKit, that would give:

| Before hook | After hook |
|-------------|------------|
| willOpen  | didOpen       |
|             | didRender     |
| willClose       | didClose |
|             | didDestroy    |

The advantage here, is that:
 - we use a known convention that I find very intuitive,
 - we could eventually drop the "on" prefix, since "will" and "did" already fill the semantic meaning this prefix has.

Now, that would be an important breaking change (maybe ? but less than changing `type` to `icon` though :D) but we could go through a deprecation phase first.

Incidentally, that would fix my problem in the issue I mentioned above, so that's for my conflict of interest =)

I'd be happy to have your opinion on this @limonte @zenflow

**Comment by limonte** [comment]
GitHub would turn into paradise on Earth if every feature request would be described like this one 🚀 

I like the idea of renaming hooks, that'll make the more explicit and improve the readability. My vote goes for the convention used by Apple's UIKit. It seems to be more popular on GitHub and will be more friendly for React developers who are the majority now.

@toverux would you mind creating the PR which will deprecate current hooks and add the new ones?

**Comment by toverux** [comment]
Awesome! Thanks!

> and will be more friendly for React developers
Oh that's right, I didn't think about React but it's a good sign that this pattern is becoming more widely used.

> @toverux would you mind creating the PR which will deprecate current hooks and add the new ones?
Sure!

**Comment by limonte** [comment]
:tada: This issue is fixed in version 10.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/sweetalert2/v/10.3.0)
- [GitHub release](https://github.com/sweetalert2/sweetalert2/releases/tag/v10.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
