### ISSUE TITLE
[TypeScript] Swal namespace isn't recognized when importing from 'sweetalert2/src/sweetalert2.js'

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2056]
### Steps to reproduce

1. clone https://github.com/sweetalert2/sweetalert2-parcel-demo
2. open `app.ts`

## Current behavior

![image](https://user-images.githubusercontent.com/6059356/93664942-5576ec80-fa7b-11ea-964a-51e65f27f949.png)

## Expected behavior

The same as when importing `Swal 'sweetalert2'`:

![image](https://user-images.githubusercontent.com/6059356/93664960-61fb4500-fa7b-11ea-9304-2a8301ce2764.png)

**Comment by limonte** [comment]
This is weird. As soon as I open `node_modules/sweetalert2/sweetalert2.d.ts` in another tab it works as expected:

![aq4fSQ8YZW](https://user-images.githubusercontent.com/6059356/93665455-442fdf00-fa7f-11ea-859c-3cb95f094c75.gif)

I guess this the the issue in VS Code, not in SweetAlert2's types.

**Comment by limonte** [comment]
Reported here: https://github.com/microsoft/vscode/issues/107061

**Comment by limonte** [comment]
🤑 I will donate $10 to anyone who will help me to fix this issue 🤑

**Comment by TheColdPot** [comment]
Does `Swal` still have the expected effect after you close sweetalert.d.ts?
Whether the workspace or folder of the file is open?

If one of your answers is **yes**, then you can basically determine that it is a vscode problem

*I'm not sure this will help you*

**Comment by limonte** [comment]
Thank you for participating in this issue @TheColdPot!

> Does Swal still have the expected effect after you close sweetalert.d.ts?

No.

> Whether the workspace or folder of the file is open?

Yes. The issue is happening with both cases: workspace is open and folder is open.

**Comment by TheColdPot** [comment]
I think it may be caused by VSCode not loading the data tag file `sweetalert2.d.ts`, but Javascript also clearly stipulates that `Swal` is a class and a local file, which makes no sense.

**Comment by TheColdPot** [comment]
Wait, I found a problem, even if I hover the mouse directly in `.d.ts`, the color is not cyan which represents `namespace`.

The chance of vscode glitch is greater

**Comment by TheColdPot** [comment]
![image](https://user-images.githubusercontent.com/66854652/94678513-387ecb00-0351-11eb-93e1-05554f4190be.png)

**Comment by limonte** [comment]
Thanks a lot for the further investigation @TheColdPot!

Another proof that it's the VS Code issue is that in WebStorm all works as expected:

![image](https://user-images.githubusercontent.com/6059356/94679092-33f1ec80-0328-11eb-9e88-d9cf9b826d13.png)

**Comment by TheColdPot** [comment]
Okay. My module also has this glitch. It also resolves my repo!
So, the next step is to wait for Microsoft to resolve this bug.

**Comment by limonte** [comment]
> 
> 
> Okay. My module also has this glitch. It also resolves my repo!
> So, the next step is to wait for Microsoft to resolve this bug.

The issue has been added to the October milestone!

![image](https://user-images.githubusercontent.com/6059356/94680806-08bccc80-032b-11eb-8d6d-9aca2834077b.png)

**Comment by TheColdPot** [comment]
Wait, in my project, VSCode prompts
```js
import { peb } from 'peb'
```
This is even more strange, because I am `peb` instead of an object regardless of AMD's export or module.exports
![bandicam 2020-10-03 08-51-00-461](https://user-images.githubusercontent.com/66854652/94979537-df33b900-0555-11eb-9570-8f19852788a9.gif)  (I installed the Chinese plugin, but the point is not this)
This may help you, but I'm not sure that your situation is the same

![image](https://user-images.githubusercontent.com/66854652/94979590-2d48bc80-0556-11eb-9b13-1ad8448ed667.png)

**Comment by TheColdPot** [comment]
Wait, you can try this
```js
import Swal from 'sweetalert2'
```
Will this problem occur with your package on NPM?

**Comment by limonte** [comment]
```js
import Swal from 'sweetalert2'
```

and 

```js
import from 'sweetalert2/src/sweetalert2.js'
```

are different. The first `import` will import `sweetalert2/src/sweetalert2.all.js` (which is JS + CSS), the second one will import only JS. This might needed in cases devs want to import SCSS separately, e.g. for changing some SCSS variables.

**Comment by TheColdPot** [comment]
> The first `import` will import `sweetalert2/src/sweetalert2.all.js` (which is JS + CSS), the second one will import only JS. This might be needed in cases devs want to import SCSS separately, e.g. for changing some SCSS variables.

Hmm... understood. If you confirm that the whole package can be run by directly importing it, then this must be the reason:
The key to this problem should be that VSCode cannot detect `.d.ts` correctly.

**Comment by limonte** [comment]
`tsconfig.json` was missing in that project:

```json
{
  "include": [
    "app.ts",
    "node_modules/sweetalert2/sweetalert2.d.ts"
  ]
}
```

https://github.com/sweetalert2/sweetalert2-parcel-demo/commit/ea7846d216fe2eb152e0b98df4dc059f200ba765

**Comment by mlbonniec** [comment]
Hi, I've the same issue. I want as well, import SweetAlert JS without CSS.  
I red your issue on VSCode repository https://github.com/microsoft/vscode/issues/107061, but it didn't resolve mine. 😕

https://user-images.githubusercontent.com/29955402/114052670-8808fb00-988e-11eb-92c9-3ee1ee58ec77.mov

Yet, I've a `tsconfig.json` like this
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": ["es2017", "es7", "es6", "dom"],
    "declaration": true,
    "outDir": "dist",
    "strict": true,
    "esModuleInterop": true,
		"experimentalDecorators": true,
  },
  "exclude": [
    "dist"
  ],
  "include": [
    "./node_modules/sweetalert2/sweetalert2.d.ts"
  ]
}
```
Do you know how to fix?

Here are my VSCode and others, versions.

![Capture d’écran 2021-04-08 à 17 20 38](https://user-images.githubusercontent.com/29955402/114052947-c999a600-988e-11eb-8152-2b6b259a5a37.png)

**Comment by limonte** [comment]
@mlbonniec please create another issue with the simple repo to reproduce the issue.
