### ISSUE TITLE
Strange animation when paired with fadeInRight

### ISSUE THREAD

**Issue by produktive** [sweetalert2/sweetalert2#2059]
I tried reproducing the menu sidebar code, except changing fadeInLeft with fadeInRight. You get a weird bouncing animation and not really a fade in. Is this a problem with Sweet alert or animate.css?

Here is a minimally reproducible example: https://codepen.io/Produkt/pen/vYGVRqP

**Comment by limonte** [comment]
https://sweetalert2.github.io/recipe-gallery/sidebars-drawers.html
