### ISSUE TITLE
The 'showDenyButton' button breaks things?

### ISSUE THREAD

**Issue by ShirinShirinak** [sweetalert2/sweetalert2#2061]
I've been using sweetalert2 in my Angular  9 project and everything has been working fine. I noticed there are some new things or things that I didn't know I could do. I grabbed the piece of code from https://sweetalert2.github.io/ which contains 3 different buttons. 

`Swal.fire({`
 ` title: 'Do you want to save the changes?',`
  `showDenyButton: true,`
  `showCancelButton: true,`
 ` confirmButtonText: 'Save',`
 ` denyButtonText: 'Don't save',`
`}).then((result) => {`
 ` /* Read more about isConfirmed, isDenied below */`
  `if (result.isConfirmed) {`
   ` Swal.fire('Saved!', '', 'success')`
 ` } else if (result.isDenied) {`
  `  Swal.fire('Changes are not saved', '', 'info')`
 ` }`
`})`

But when I try to use this, my code freaks out, it doesn't like the 'showDenyButton' and 'denyButtonText'. It says 'No overload matches this call. I updated my sweetalert2 version to '^9.17.2' but I still have the same issue. How can I get this working? Is this  a bug? 

Thank you!

**Comment by toverux** [comment]
Hi, you need sweetalert2 `^10.0.0` at least to have the deny button feature set.

**Comment by ShirinShirinak** [comment]
> Hi, you need sweetalert2 `^10.0.0` at least to have the deny button feature set.

I updated it but I still have the same issue

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by ShirinShirinak** [comment]
It's fixed now. So I opened up the sweetalert code to see if the deny button was in there, I copied the 'showDenyButton' from the code instead of the website and things started working. Thank you guys!
