### ISSUE TITLE
input type File, placeholder is not working

### ISSUE THREAD

**Issue by JSulzberger** [sweetalert2/sweetalert2#2064]
## Current behavior

inputPlaceholder: "Select File",

## Expected behavior

Should see in the input box?

## Live demo 

---

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by limonte** [comment]
That's impossible to achive with `input[type="file"]`, you have to use the custom file uploader for that.
