### ISSUE TITLE
Regression overflow-y toast with title and text

### ISSUE THREAD

**Issue by markusramsak** [sweetalert2/sweetalert2#2065]
## Current behavior
After updating to Sweetalert 10.3.2 (from 9.17.2):
animation not smooth because of vertical scroll bar appearing during animation (Firefox 80.0.1, Mac OS 10.15.6).
When the animation is done, the scroll bar disappears.

## Expected behavior

smooth animation without scrollbar.

## Example code
```
Swal.fire({
            title: 'Text copied',
            text: 'Lorem ipsum, Lorem ipsum, Lorem ipsum, Lorem ipsum, Lorem ipsum',
            icon: 'success',
            timer: 4000,
            toast: true,
            position: 'bottom-start',
            showConfirmButton: false,
        });
```
When I use only "title" and no "text", then there is no issue.

## Temporary solution
```
body.swal2-toast-shown .swal2-container.swal2-bottom-left,
body.swal2-toast-shown .swal2-container.swal2-bottom-start {
  overflow-y: hidden !important;
}
```

**Comment by limonte** [comment]
This is the regression after my yesterdays PR: #2063

**Comment by limonte** [comment]
Thank you for reporting this issue @markusramsak!
