### ISSUE TITLE
React/Gatsby build error - Unexpected token (109:55)

### ISSUE THREAD

**Issue by luchoster** [sweetalert2/sweetalert2#2067]
## Current behavior

When building the project using version 10.0+ the build fails with error:

![issue](https://user-images.githubusercontent.com/694367/94212707-c3f7e800-fe89-11ea-81f4-0eabac79172d.png)

## Expected behavior

SSR fails because of the `??` here (`sweetalert2/src/instanceMethods/close.js:109:55`)
![issue-code](https://user-images.githubusercontent.com/694367/94214145-a3ca2800-fe8d-11ea-977c-09d2aacadbb5.png)

## Live demo 

my issue isn't a visual one, it's the code:

![issue](https://user-images.githubusercontent.com/694367/94212707-c3f7e800-fe89-11ea-81f4-0eabac79172d.png)

---

Any ideas or solutions to fix the SSR build?

**Comment by limonte** [comment]
Thank you for reporting @luchoster! The issue is fixed now.

Which tool were you using to create these beautiful screenshots?

**Comment by luchoster** [comment]
woohoo thanks sooo much, that was quick.

https://carbon.now.sh/

for the screenshots :)
