### ISSUE TITLE
[Bounty 💰] The success icon animation is broken in iOS

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2070]
## Current behavior

The `swal2-rotate-success-circular-line` is well-noticable delayed in iOS for the unknown reasons:

![video-2020-09-28-12-08-22](https://user-images.githubusercontent.com/6059356/94413253-80e88e00-0183-11eb-8b31-313caffcbfa6.gif)

The original sweetalert is broken as well so I believe there's something going on with the latest iOS 14.

## Expected behavior

The animation in iOS should be the same as in all browsers:

![Na9gDie4x6](https://user-images.githubusercontent.com/6059356/94413508-da50bd00-0183-11eb-8409-da7fb15d17e0.gif)

## Live demo 

Reproducible with the very first example at https://sweetalert2.github.io/

**Comment by limonte** [comment]
🤑 I will donate $10 to anyone who will help me to fix this issue 🤑

**Comment by limonte** [comment]
@gverni if you have time please take a look at this issue.

**Comment by Jadhielv** [comment]
Hey! @limonte trying to create test escenario (iOS 14.2 beta), in some browsers: Safari, Firefox and Chrome. I don't identify any delay, view details:

| Safari  | Firefox  | Chrome |
|---|---|---|
| ![Safari](https://user-images.githubusercontent.com/24376900/94485069-5f9b9800-01ab-11eb-93fe-f45bf10d2dbe.gif) | ![Firefox](https://user-images.githubusercontent.com/24376900/94485122-7215d180-01ab-11eb-949a-c79ed95bfd9c.gif) | ![Chrome](https://user-images.githubusercontent.com/24376900/94485181-8954bf00-01ab-11eb-852e-0c60b5abb8a8.gif) |

NOTE: ¿Will it be OK in this version?

**Comment by limonte** [comment]
> 
> 
> Hey! @limonte trying to create test escenario (**iOS 14.2 beta**), in some browsers: **Safari**, **Firefox** and **Chrome**. I don't identify any delay, view details:
> Safari 	Firefox 	Chrome
> ![Safari](https://user-images.githubusercontent.com/24376900/94485069-5f9b9800-01ab-11eb-93fe-f45bf10d2dbe.gif) 	![Firefox](https://user-images.githubusercontent.com/24376900/94485122-7215d180-01ab-11eb-949a-c79ed95bfd9c.gif) 	![Chrome](https://user-images.githubusercontent.com/24376900/94485181-8954bf00-01ab-11eb-852e-0c60b5abb8a8.gif)
> 
> **NOTE**: ¿Will it be OK in this version?

Thanks a lot for your feedback @Jadhielv Let's wait for the 14.2 stable then and hopefully the issue will be gone. If so, I'll send you the promised bounty 💰

**Comment by limonte** [comment]
My iphone just got the 14.2 update and animations are working fine in it! Thank you @Jadhielv for your feedback here, it saved my time from debugging! Please send your paypal email to limon.monte@gmail.com so I can send the promised bounty!

**Comment by Jadhielv** [comment]
Done @limonte. Check your email

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/98481518-7e0d9e00-2203-11eb-90b1-c36136d1f36d.png)

Thank you @Jadhielv!
