### ISSUE TITLE
Trojan Alert in your script. ( Trojan:HTML/Phish.PH!MTB )

### ISSUE THREAD

**Issue by MinerProfitDevelopment** [sweetalert2/sweetalert2#2072]
Hi. My server firewall deleted some html files. We did examine in logs and see Trojan:HTML/Phish.PH!MTB in `https://cdn.jsdelivr.net/npm/sweetalert2@9` line. We did search in google and we see subject in here. https://stackoverflow.com/questions/64161220/windows-defender-detects-trojanhtml-phish-phmtb-in-a-simple-html-file 

We removed your script for resolve. We love and need your script. Thnks...

**Comment by Reivaj810** [comment]
Hi, We have the same problem, if we change the sweetalert2@9 to 2@10 and now look that work, but our build server still continue whit the problem, any option to this problem?

**Comment by iKlsR** [comment]
Let's keep this under one issue. #2071

**Comment by limonte** [comment]
Duplicate of #2071
