### ISSUE TITLE
Too many steps

### ISSUE THREAD

**Issue by Lucasmoreno2** [sweetalert2/sweetalert2#2073]
I have an alert with many steps, with that high number of steps, steps come out of the alert

## Live demo 

https://jsfiddle.net/lucasmoreno2/v14dxyua/5/

**Comment by limonte** [comment]
what'd be the expected behavior?

**Comment by limonte** [comment]
Fixed: https://jsfiddle.net/6kcv2qhb/

Thanks for reporting!
