### ISSUE TITLE
Change Validation Message icon

### ISSUE THREAD

**Issue by produktive** [sweetalert2/sweetalert2#2076]
## New feature motivation

Using Sweetalert as a menu, I want to be able to use the Validation Message for other types of alerts, such as success, using the already existing icons.

## New feature implementation

https://imgur.com/a/ArSHJcl
Example of where I would want to use another type of icon.

**Comment by rohya8** [comment]
You can use custom messages by using "inputValidator". (Check the first example)
[Example](https://sweetalert2.github.io/#handling-buttons)

**Comment by produktive** [comment]
> 
> 
> You can use custom messages by using "inputValidator". (Check the first example)
> [Example](https://sweetalert2.github.io/#handling-buttons)

That does not answer the question, please re-read the original post.

**Comment by rohya8** [comment]
@produktive Sorry i misread the question.

You can change the icon by changing the **imageUrl** property. [Docs](https://sweetalert2.github.io/#icons) 

```
Swal.fire({
  title: 'Sweet!',
  text: 'Modal with a custom image.',
  imageUrl: 'https://unsplash.it/400/200',
  imageWidth: 400,
  imageHeight: 200,
  imageAlt: 'Custom image',
})
```

**Comment by produktive** [comment]
@rohya8 You are still not understanding the question. I want to change the icon in the ValidationMessage box. Please read the question carefully.

**Comment by limonte** [comment]
Here's the example: https://sweetalert2.github.io/recipe-gallery/validation-message-custom-icon.html

Thank you @produktive for the good question!
