### ISSUE TITLE
something is wrong with validation message or pre-confirm

### ISSUE THREAD

**Issue by sergeii-55** [sweetalert2/sweetalert2#2080]
## Current behavior

when press the customized OK button, validation appear but it change the element.style property of the button's display to flex

## Expected behavior

click OK, display the validation message with no change of other object

## Live demo 

https://codepen.io/sergeii-55/pen/abZOgVz

**Comment by rohya8** [comment]
The styling was getting added after click (display: flex;). Please add "display: inline-block !important;"

```
.btnLOG{
    border: none;
    background-color: #FEBA13;
    color: white;
    font-family: Albertus;
    font-size: 25px;
    font-weight: bold;
    width: 300px;
    height: 40px;
    border-radius: 30px;
    margin: 1vw;
  **display: inline-block !important;**
}
```

**Comment by sergeii-55** [comment]
Well, that definitively do the trick, but isn't the validation message supposed to change it?
btw its working fine

**Comment by limonte** [comment]
@rohya8 you've been giving misleading answers in two issues already, this is actually a bug and your suggestion is nothing but a low-quality hack. You're blocked now.
