### ISSUE TITLE
Option to pass value on Deny button click

### ISSUE THREAD

**Issue by ThreeDfish** [sweetalert2/sweetalert2#2082]
## New feature motivation

Having the option of a third button would be really useful if we were able to pass back the value of the input on clicking the Deny button instead of passing back false.  The Deny button is presented as a customizable third button, but without being able to pass back the input value, it is not that useful.

In my application, I want to use the Deny button for "Make Default", but I need the value of the input when it is clicked.

## New feature description

A flag could be added to the config, say, "setValueOnDeny: true" which could default to false, and when it is set, clicking the Deny button would pass the value instead of returning false.

**Comment by limonte** [comment]
Out of curiosity: what's your use-case, e.g. what are other buttons?

**Comment by limonte** [comment]
Thank you for the feedback @ThreeDfish 

Could you please review #2084 and let me know if it'll resolve all your use-cases.

**Comment by ThreeDfish** [comment]
Yes, that looks like it will solve the problem.
