### ISSUE TITLE
passing value from didOpen to the  .then() part

### ISSUE THREAD

**Issue by sergeii-55** [sweetalert2/sweetalert2#2087]
I already have the didOpen parameter built and implemented a JSON object with values inside of it.
The question is... How can I pass that JSON object to the then part of the Swal.fire({ }) .then arrow function

```
Swal.fire({
  html: ` HERE IS ALL THE ID's STUFF `,
  didOpen() {
    let itemPOST = {  /* the json i trying to catch */  }

    // do bunch of stuff and save it into itemPOST

                             }      //==>end of didOpen
}).then(() => {
  //console.log/use for itemPOST here 
})
```
i try to resolve it using the localstorage.set... then localstorage.get, but i think is not the best way.
any help is appreciated

posted at:
https://stackoverflow.com/questions/64378624/passing-a-value-from-didopen-sweetalert2-parameter-to-the-then
but no luck having a response

**Comment by limonte** [comment]
```js
let itemPOST
Swal.fire({
  html: ` HERE IS ALL THE ID's STUFF `,
  didOpen: () => {
    itemPOST = 'a'
  }
}).then(() => {
  console.log(itemPOST)
})
```
