### ISSUE TITLE
Close sweetalert2 seem not working 

### ISSUE THREAD

**Issue by thewebartisan7** [sweetalert2/sweetalert2#2089]
I am not sure if I missed something but I can't close sweetalert2, I found a workaround by manually removing from DOM.

Because with turbolinks when an alert toast is open, and I switch page, and return back, for a second I can still see sweetalert2, from turbolinks cache.

So I am trying to close sweetalert before turbolinks cache page using event:

```js
document.addEventListener("turbolinks:before-cache", function() {
    Swal.close();
})
```

But this doesn't work, I can still see sweetalert cached.

I found below workaround which works fine:

```js
document.addEventListener("turbolinks:before-cache", function() {
    document.documentElement.classList.remove('swal2-toast-shown', 'swal2-shown')
    document.querySelector('.swal2-container').remove()
})
```

**Comment by limonte** [comment]
Thanks for reporting @thewebartisan7!

> Because with turbolinks when an alert toast is open, and I switch page,

I think that you should observe the `turbolinks:before-visit` event and run `Swal.close()` in it. Let me know if that works.

**Comment by thewebartisan7** [comment]
No doesn't work with any event, I try them all. Event is fired and when using before-visit or before-cache the toast is shown less time compared without listeners, so seem that is closed by Swal but seem still being cached.

**Comment by limonte** [comment]
I think I understand the issue. The closing isn't happening instantly because there's the closing animation which is `0.2s` long.

What if you unset the animation and then close a toast? Something like this:

```js
Swal.update({
  hideClass: {
    popup: '',
    backdrop: ''
  }
})
Swal.close()
```

**Comment by thewebartisan7** [comment]
Yes, that works fine! Good catch. Thank You.

**Comment by thewebartisan7** [comment]
@limonte I notice a warning in console:

```
SweetAlert2: You're trying to update the closed or closing popup, that won't work. Use the update() method in preConfirm parameter or show a new popup.
```

It's just a warning so maybe I could ignore it? But this happen when using above solution with Turbolinks.
