### ISSUE TITLE
Update docs to discuss xss mitigation and other security precautions

### ISSUE THREAD

**Issue by djeikyb** [sweetalert2/sweetalert2#2090]
Could the docs be updated to mention the user's security responsibilities when using the html option? As in:

```
const unescapedText = ...
Swal.fire({
  title: '<strong>HTML <u>example</u></strong>',
  icon: 'info',
  html:
    'You can use <b>bold text</b>, ' +
    '<a href="//sweetalert2.github.io">links</a> ' +
    'and other HTML tags ' +
    unescapedText,
})
```

The user's responsibility when using the html option is to escape any user input, to mitigate xss attacks. I ctrl-f'd the docs for mention of "security" and "xss" and found nothing. This came up at a security review recently, where it was discovered our code base had some insecure uses of sweetalert2.

**Comment by limonte** [comment]
Thank you for reporting @djeikyb! I agree that it should be mentioned in docs. Would you mind to submit a PR to https://github.com/sweetalert2/sweetalert2.github.io ?

**Comment by limonte** [comment]
Done in https://github.com/sweetalert2/sweetalert2.github.io/commit/52e89b6bb5751225049749eb32e4a8f482da4aa2
