### ISSUE TITLE
Wrong result object when using deny botton with returnInputValueOnDeny

### ISSUE THREAD

**Issue by pmahdavii** [sweetalert2/sweetalert2#2091]
when I click on deny button and returnInputValueOnDeny is true, in result object isConfirmed is true and isDenied is false!
this is my swal code:
`Swal.fire({
            title: 'price validation',
            html: '<content id="content">fetching...</content>',
            showCancelButton: true,
            confirmButtonText:'acceptable',
            cancelButtonText: 'cancel',
            showLoaderOnConfirm: true,
            showDenyButton: true,
            denyButtonText: "not acceptable",
            denyButtonColor: '#f2f2f2',
            returnInputValueOnDeny:true,
            input: 'text',
            inputLabel: 'your price',
            inputValue: 'fetching...',
            inputValidator: (value) => {
                if (isNaN(value)) {
                  return 'invalid number';
                }
            },
            willOpen: () => {
                Swal.showLoading();
                const content = Swal.getContent();
                if (content) {
                content.querySelector(".swal2-input-label").style="display:none";
                content.querySelector("#swal2-input").style="display:none";
                fetch(api).then(response => response.text()).then(data=>{
                        content.style="width:100%;";
                        content.querySelector("#content").innerHTML = data;
                        content.querySelector("#swal2-input").value = content.querySelector("#buyPrice").innerHTML;
                        content.querySelector("#swal2-input").style="margin: 0px !important;text-align:center;";
                        content.querySelector(".swal2-input-label").style="";
                        //content
                        Swal.hideLoading();
                })
                }else location.reload();
            },
            preConfirm: () => {
                price=document.getElementById('buyPrice').value;
                return fetch(setPriceAPI+'?price='+price)
                .then(response => {
                    if (!response.ok) {
                    throw new Error(response.statusText)
                    }
                    return response.json()
                })
                .catch(error => {
                    Swal.showValidationMessage(
                    "submittion fault: ${error}"
                    )
                })
            },
            allowOutsideClick: () => !Swal.isLoading()
            }).then((result) => {
                console.log(result);
                if (result.isConfirmed) {
                    if (result.value.result=="successful"){
                        Swal.fire({
                            icon: 'success',
                            title: `done`,
                            confirmButtonText:'thanks',
                        })
                    }
                    else
                    Swal.fire({
                        icon: 'error',
                        title: `change error`,
                        text: result.value.result,
                        confirmButtonText:'ok',
                    })
                }
                else if (result.isDenied){
                    //do sth
                }
        });`

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
