### ISSUE TITLE
Incorrect formatting when using "Input" in html 

### ISSUE THREAD

**Issue by xnetdude** [sweetalert2/sweetalert2#2094]
When an html Input tag is used in the SA2 "html" property and has it's "value" property set within the same line, the SA2 dialog box partially renders incorrectly.  Instead of the "value" being displayed within the INPUT tag, it partially displays outside.

## Expected behavior

The dialog box to render correctly with values shown in correct <input> tags.

Call editStuff function passing "<script>alert("hello world")</script> into the "description" variable.

*** SORRY - TRY AS I MAY, I CAN'T GET THE CODE FORMATTING TO RENDER CORRECTLY ***

`function editStuff(id, name, description) {`
`    swal.fire({`
`        title: '<h4><strong>Edit Stuff</strong></h4>',`
`        html: '<h5 class="mb-2 small">Name</h5><input maxlength="50" id="swal-name" class="swal2-input mt-0" value="' + name + '">' +`
`            '<h5 class="mb-2 small">Description</h5><input maxlength="250" id="swal-description" class="swal2-input mt-0" value="' + description + '">',`
`        animation: false,`
`        customClass: {`
`            popup: 'animate__animated animate__fadeIn'`
`        },`
`        inputAttributes: {`
`            autocapitalize: 'off'`
`        },`
`        showCancelButton: true,`
`        confirmButtonText: 'Save',`
`        showLoaderOnConfirm: true,`
`        preConfirm: (name) => {`
`            return fetch('?handler=EditStuff&id=' + id + '&name=' + document.getElementById('swal-name').value + '&description=' + document.getElementById('swal-description').value + '')`
`                .then(response => {`
`                    if (!response.ok) {`
`                        throw new Error(response.statusText)`
`                    }`
`                    return response.json()`
`                })`
`                .catch(error => {`
`                    Swal.showValidationMessage(`
`                        'Error editing stuff ${error}'`
`                    )`
`                })`
`        },`
`        allowOutsideClick: () => !Swal.isLoading()`
`    }).then((result) => {`
`    })`
`}`

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
