### ISSUE TITLE
Can not find name 'ReadonlyMap'.

### ISSUE THREAD

**Issue by miladashrafi** [sweetalert2/sweetalert2#2095]
https://github.com/sweetalert2/sweetalert2/blob/03a6c5a5ded31af5b8f3c9bba454c7d8fde0df28/sweetalert2.d.ts#L955

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
