### ISSUE TITLE
Timer is not working

### ISSUE THREAD

**Issue by tdbsoft** [sweetalert2/sweetalert2#2096]
## Current behavior

The message dialog is not wait when called within a button click
i.e. I click the save button and want to display for a few seconds a information dialog.
here is a snippet of the code.
	success: function(data) {
		Swal.fire({title: 'SAVING', text: 'Saving CSD data to the Forms server', icon: 'info', confirmButtonText: 'OK', timer: 5000});

It is in an success function of an Ajax call but I have try before the ajax call and the same thing happens.
I have also placed as the first item in the button click function i.e.
$("#save").click(function(event) {
	Swal.fire("CSD data records has been saved to file");

Same thing happens the dialog box shows for a brief moment then then gone.

## Expected behavior

Display the dialog box wait for 5 secs then continue.

In the case of the Swal.fire("CSD data records has been saved to file");
Wait until the button is clicked.

## Live demo 

---

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
