### ISSUE TITLE
cant Disable focus button after close modal alert

### ISSUE THREAD

**Issue by arezascarlet** [sweetalert2/sweetalert2#2097]
## Current behavior

still focus after modal alert show, and not showing focus for required field form, i set with function **didClose** still not working.

## Expected behavior

i hope next update can have function disable focus for button sweetalert

## Live demo 
still focus after deny, submit, or dismiss modal
[https://projectscarlet.web.id/img/ddd.jpg](https://projectscarlet.web.id/img/ddd.jpg)

---

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by limonte** [comment]
```js
Swal.fire({
  didOpen: function (modal) {
    Swal.getConfirmButton().blur()
  },
})
```

**Comment by arezascarlet** [comment]
> 
> 
> ```js
> Swal.fire({
>   didOpen: function () {
>     Swal.getConfirmButton().blur()
>   },
> })
> ```

still not working, button sweetalert still focus, and not going focus to input field required

**Comment by limonte** [comment]
```js
Swal.fire({
  focusConfirm: false,
})
```

**Comment by arezascarlet** [comment]
still not working again

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
