### ISSUE TITLE
Property 'then' does not exist on type 'Promise<SweetAlertResult<any>>' angular10

### ISSUE THREAD

**Issue by shakalya195** [sweetalert2/sweetalert2#2098]
## Current behavior

Property 'then' does not exist on type 'Promise<SweetAlertResult<any>>' angular10

## Expected behavior

there should be then method available for handling decisions. 

![Screenshot from 2020-10-27 22-49-45](https://user-images.githubusercontent.com/25704747/97338919-f2f9e300-18a7-11eb-9cdb-9069a2a3d34c.png)

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
