### ISSUE TITLE
Reopen SweetAlert

### ISSUE THREAD

**Issue by NicoEngler** [sweetalert2/sweetalert2#2103]
Hi, 

I'd like to **reopen** an alert to keep the (via ajax) modified state. 
But I couldn't find a function that covers that.

Here's some pseudo code on what I am trying to do:

Window.swalAlert = undefined;

if (Window.swalAlert !== undefined)
{
	// Window.swalAlert.open() ?
} else {
	Window.swalAlert = Swal.fire({
		html: htmlCode,
	});	
}

**Comment by limonte** [comment]
I do not understand the request, please try again by following the issue (or feature-request) template.
