### ISSUE TITLE
Confirm on click HTML didn't work with Sweetalert2 but it work with native browser confirm

### ISSUE THREAD

**Issue by pixieaka** [sweetalert2/sweetalert2#2105]
**When I use native confirm() it work fine but with Sweeetalert2 it didn't work can any one help ?**

`<button href="javascript:void(0)" onclick="confirm() && console.log('Deleted')">Delete</button>`

```
window.confirm = function () {
    swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#d33',
        cancelButtonColor: '#3085d6',
        confirmButtonText: 'Yes, delete it!',
        reverseButtons: true
    }).then((result) => {
        if (result.isConfirmed) {
            return true;
        }
    });
};
```

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask

**Comment by pixieaka** [comment]
@limonte I guess this is issue It work with native confirm but with Sweetalert2 didn't work.
