### ISSUE TITLE
Copy on Click functionality

### ISSUE THREAD

**Issue by relativelyrehan** [sweetalert2/sweetalert2#2106]
## New feature motivation

When we try to show some information like **_confirmation code_** to the user, there should be an option to copy the code on the alert window.

## New feature description

When we try to show some information like **_confirmation code_** to the user, there should be an option to copy the code on the alert window. This should be a default feature of the copy-alert type.

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by limonte** [comment]
https://github.com/zenorocha/clipboard.js + [willOpen](https://sweetalert2.github.io/#will-open)
