### ISSUE TITLE
Input with brmasker - Ionic4

### ISSUE THREAD

**Issue by damtaipu** [sweetalert2/sweetalert2#2108]
How to make br-masker in Input field's sweetalert2. 
I'm using ionic 4 and sweetalert2.

Please I need help.

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
