### ISSUE TITLE
Declarative Templates

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2111]
A really good feature-request by our sponsor @pomartel 

> This was quite important for me since I manage a multilingual app that is server-rendered in Rails. It was always a bit of a hassle to carry the actual content (title, message, button labels, etc...) to the javascript. Declarative templates have solved this problem for me and they also work quite nicely with declarative front-end frameworks. I personally use AlpineJS to add some reactivity logic to my alerts. Here is an example to show a basic example of what I'm doing:

```html
<template id='delete-alert'>
  <header icon='warning'>Are you sure?</header>
  <content>You won't be able to revert this!</content>
  <footer>
    <button data-confirm data-color='#3085d6'>Yes, delete it!</button>
    <button data-cancel data-color='#d33'>Cancel</button>
  </footer>
</template>

<script>
  Swal.fire({
    template: '#delete-alert',
  })
  // This will convert the alert to this: https://sweetalert2.github.io/#confirm-dialog
</script>


This is the same template but with Rails I18n and a reactive condition with AlpineJS:

<template id='delete-alert'>
  <header icon='warning'><%= I18n.translate('.are_you_sure') %></header>
  <content>
    <span x-show='cannotRevert === true'><%= I18n.translate('.cannot_revert') %></span>
  </content>
  <footer>
    <button data-confirm data-color='#3085d6'><%= I18n.translate('.delete') %></button>
    <button data-cancel data-color='#d33'><%= I18n.translate('.cancel') %></button>
  </footer>
</template>
```

**Comment by toverux** [comment]
Yay that would be nice! The motivation behind portals in ngx-sweetalert2 was the same, this opens lots of possibilities.
