### ISSUE TITLE
Ability to trigger the modal declaratively

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2118]
I want to throw in one more idea out there for your consideration. I also use [Micromodal.js](https://micromodal.now.sh/) in my projects and they have this nice little feature that lets you trigger the modal declaratively without any code. It's explained if you scroll to the third section. Here's what it could look like with SweetAlert:

```html
<button data-swal-trigger="hello-world-alert">Click me!</button>

<template id='hello-world-alert'>
    <swal-title>Hello world!</swal-title>
    <swal-html>Here I come...</swal-html>
</template>
```

I'm not familiar with the SweetAlert basecode so I don't know how hard this would be. I guess you would need a MutationObserver to bind a click event listenr to any tag with the `data-swal-trigger` attribute.

_Originally posted by @pomartel in https://github.com/sweetalert2/sweetalert2/issues/2112#issuecomment-734835853_

**Comment by zenflow** [comment]
I recommend leaving some imperative code up to the developer to trigger the binding of event handler(s) **at a certain point in time** and not just automatically bind them [event handlers] when the module loads.
Otherwise it will be impossible to apply defaults (with `.mixin`) or enhancers (like sweetalert2-react-content)

Possible API: 
```html
<button data-swal-trigger="hello-world-alert">Click me!</button>

<template id='hello-world-alert'>
    <swal-title>Hello world!</swal-title>
    <swal-html>Here I come...</swal-html>
</template>

<script>
  Swal.mixin({
    reverseButtons: true,
    customClass: {...},
  }).bindClickHandler()
</script>
```

**Comment by zenflow** [comment]
Also I recommend using [event delegation](https://dmitripavlutin.com/javascript-event-delegation/) so that a single event handler is bound, which handles click events from all `*[data-swal-trigger]` elements. This, as opposed to binding an event handler to each `*[data-swal-trigger]` element currently in the DOM.
This way the feature will still work when the html (containing element with `data-swal-trigger`) is added dynamically to the page after page load.

**Comment by limonte** [comment]
Great advice, thank you @zenflow

I'm also planning to add the `attributeName = 'data-swal-trigger'` argument to the `bindClickHandler()` method, so users will be able to do this:

```html
<button data-swal-trigger="hello-world-alert">Click me!</button>

<button data-swal-toast-trigger="hello-world-alert">Click me for a toast!</button>

<template id='hello-world-alert'>
    <swal-title>Hello world!</swal-title>
    <swal-html>Here I come...</swal-html>
</template>

<script>
  Swal.bindClickHandler() // data-swal-trigger will be used

  Swal.mixin({
    toast: true
  }).bindClickHandler('data-swal-toast-trigger')
</script>
```

**Comment by zenflow** [comment]
@limonte Nice! Love this API!

**Comment by zenflow** [comment]
Should it be `data-swal-template` instead of `data-swal-trigger`, since the value of the attribute is a template id?
Or if ergonomics is more important than explicit (& verbose) naming, maybe just `data-swal`?

```html
<!-- trigger -->
<button data-swal-trigger="hello-world-alert">Click me!</button>
<button data-swal-toast-trigger="hello-world-alert">Click me for a toast!</button>

<!-- template -->
<button data-swal-template="hello-world-alert">Click me!</button>
<button data-swal-toast-template="hello-world-alert">Click me for a toast!</button>

<!-- simple -->
<button data-swal="hello-world-alert">Click me!</button>
<button data-swal-toast="hello-world-alert">Click me for a toast!</button>
```

**Comment by limonte** [comment]
> Should it be `data-swal-template` instead of `data-swal-trigger`, since the value of the attribute is a template id?
> Or if ergonomics is more important than explicit (& verbose) naming, maybe just `data-swal`?
> 
> ```
> 
> <button data-swal-trigger="hello-world-alert">Click me!</button>
> <button data-swal-toast-trigger="hello-world-alert">Click me for a toast!</button>
> 
> 
> <button data-swal-template="hello-world-alert">Click me!</button>
> <button data-swal-toast-template="hello-world-alert">Click me for a toast!</button>
> 
> 
> <button data-swal="hello-world-alert">Click me!</button>
> <button data-swal-toast="hello-world-alert">Click me for a toast!</button>
> ```

My vote goes for `data-swal-template` 👍

**Comment by sbrow** [comment]
I may be an idiot, but when using this method to define your alerts, how are you supposed to capture/handle the `SweetAlertResult` object? My intuition says there should be an `onconfirm` or `data-is-confirmed` attribute somewhere for the handler code; but if I'm reading the code correctly, it appears there isn't any way to access the results at all.

**Comment by limonte** [comment]
> I may be an idiot, but when using this method to define your alerts, how are you supposed to capture/handle the `SweetAlertResult` object? My intuition says there should be an `onconfirm` or `data-is-confirmed` attribute somewhere for the handler code; but if I'm reading the code correctly, it appears there isn't any way to access the results at all.

```html
<template id="my-template">
  <swal-title>Hello!</swal-title>
</template>
```

```js
Swal.fire({
  template: '#my-template'
}).then(result => {
  // result is SweetAlertResult
})
```

**Comment by sbrow** [comment]
So the answer is no then?  What purpose does `data-swal-template` serve if the alert can't have logic attached to it? I realize that you can call `Swal.fire({template: '#my-template'})`, but if you do, wouldn't `data-swal-template="my-template"` just be overwritten?

**Comment by zenflow** [comment]
Purpose of `data-swal-template` is a shorthand if you don't need to do anything advanced, like dynamic options or doing something with the result. 
If you need to do something advanced like that, you will need to call `Swal.fire({template: '#my-template'})` yourself. You can still use templates, you just can't use the `data-swal-template` shorthand to bind an element's click event to fire the alert.
