### ISSUE TITLE
Ability to access inputted data easily on post page.

### ISSUE THREAD

**Issue by jamminjames** [sweetalert2/sweetalert2#2119]
## New feature motivation

I want to be able to use data submitted via `input: 'text'` in php. If I post via ajax, the data is shown in the console, but there seems to be no way to use it in php. It can also be shown in a div, but again, that seems to be useless as far as actually using the inputted data. I've tried posting as json as well. I've searched and searched, and maybe I missed something, but can find no solution.  If I am missing something, I hope someone can explain it to me.

## New feature description

Ability to access inputted data easily on post page.

## New feature implementation

---

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by limonte** [comment]
Unrelated to the library.
