### ISSUE TITLE
Prioritize template params over mixin params

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2125]
> I am working on migrating my home made templates to the official implementation and I'm running in a problem. I have global default params set in a `Swal.mixin`. I would like the template params to override the default params. Would there be a way to do that?

_Originally posted by @pomartel in https://github.com/sweetalert2/sweetalert2/issues/2112#issuecomment-740112679_

**Comment by zenflow** [comment]
I assumed that template params would take precedence over mixin params

**Comment by limonte** [comment]
I don't have any opinions about what should take precedence. Since there are 2 votes for the higher priority of template params, I'll just change it and release it as a bug-fix.

**Comment by pomartel** [comment]
Oops, I think there might be a bug there. Template params that are not set will override the `Swal.mixin`.

For example I am not setting an imageWidth in my template but I'm setting one in the mixin. Looks like the null value of the template will override the imageWidth value of the mixin:

https://github.com/sweetalert2/sweetalert2/blob/0b510ec49151674eab52819e6637813a409b0ad3/src/utils/getTemplateParams.js#L66
