### ISSUE TITLE
Null values from declarative template are overriding user params

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2127]
Oops, I think there might be a bug there. Template params that are not set will override the `Swal.mixin`.

For example I am not setting an imageWidth in my template but I'm setting one in the mixin. Looks like the null value of the template will override the imageWidth value of the mixin:

https://github.com/sweetalert2/sweetalert2/blob/0b510ec49151674eab52819e6637813a409b0ad3/src/utils/getTemplateParams.js#L66

_Originally posted by @pomartel in https://github.com/sweetalert2/sweetalert2/issues/2125#issuecomment-740159516_

**Comment by limonte** [comment]
Thank you @pomartel for testing the new feature out and reporting issues!

**Comment by pomartel** [comment]
You are fast! All good now, thanks a lot!
