### ISSUE TITLE
Template button text is not overriden by the confirmButtonText option

### ISSUE THREAD

**Issue by pomartel** [sweetalert2/sweetalert2#2131]
## Current behavior

An explicit option does not replace the template button text

## Expected behavior

The options should have precedence on the template

## Live demo 

https://codepen.io/pomartel/pen/JjRRPoL

**Comment by limonte** [comment]
Thanks for reporting @pomartel 

Do I understand correctly that your expectation of precedence is:

1. Params provided to `Swal.fire()` should have precedence over template params.
2. Both params provided to `Swal.fire()` and template params should have precedence over params in `Swal.mixin()` (as per https://github.com/sweetalert2/sweetalert2/pull/2112#issuecomment-740112679)

**Comment by pomartel** [comment]
> Params provided to Swal.fire() (highest priority)
Template params
Mixin params (lowest priority)

Yes, that's how I would like it to work! At least that's what makes most sense with my use cases.

**Comment by limonte** [comment]
@pomartel should be good now, please check it out.

**Comment by pomartel** [comment]
All good! Thanks a lot! 😄
