### ISSUE TITLE
Is there a way to not destroy content in the modal on close?

### ISSUE THREAD

**Issue by gfranko** [sweetalert2/sweetalert2#2132]
I have a particular use case where I want to not destroy the modal *html* content on close (I'm putting a JavaScript widget inside of the modal) and was curious if there would be a way to not destroy the html on close (I want to allow a user to still be able to open/close the modal).

Thank you for a great project!

**Comment by limonte** [comment]
Yes.

```html
<div id="my-content">my content</div>
```

```js
const myContent = document.querySelector('#my-content')

Swal.fire({
  html: myContent,
  willClose: () => {
    document.body.appendChild(myContent)
  }
})
```
