### ISSUE TITLE
Unit Test - appendChild of undefined when deep nested

### ISSUE THREAD

**Issue by argelj289** [sweetalert2/sweetalert2#2134]
## Current behavior

it causes error saying that it can't read the property 'appendChild' of undefined  when getting executed from a deep nested function inside component. but only happens in unit test (karma-jasmine)

## Expected behavior
it should continue to next line of codes without error

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
