### ISSUE TITLE
Dropdown menu opens upon sweetalert2 success

### ISSUE THREAD

**Issue by isrhedden** [sweetalert2/sweetalert2#2136]
## Current behavior
We are building a React web application using Semantic UI front-end elements. We have Semantic Dropdowns that call handler functions onChange. After an Axios call, we display a sweetalert2 alert. When the user closes the sweet alert (either by selecting "OK" or clicking outside of the alert) the dropdown opens up again unprompted. To be clear, the user does not want to expand the dropdown after selecting "OK" to close the pop-up, it happens automatically.

## Expected behavior
After the user closes the sweet alert, the dropdown should remain closed.

## Important note
This issue does not exist with sweetalert. It only exists with sweetalert2. I am forced to now use sweetalert instead of sweetalert2.

## Live demo 
I tried to replicate the issue with raw html but was unable to. [Here](https://codepen.io/rhedden/pen/abmBQjM?editors=1010) is my codepen.

I love this product but can't use it until this bug is fixed. I hope somebody finds the time to fix it.

Thanks for reading.

**Comment by limonte** [comment]
Hey @isrhedden! I have a clue what might be the issue could you maybe record the screen (gif/video) and share it here?

**Comment by limonte** [comment]
Also, this would help:

```js
Swal.fire(...) // your code here.
  .then(() => {
    setTimeout(() => console.log(document.activeElement), 2000)
  })
```

I believe the dropdown is getting opened because sweetalert2 will bring the focus back to whatever element had it before sweetalert2.

**Comment by isrhedden** [comment]
Wow! Thanks for the quick response!

I made a gif of the issue complete with your console.log. Let me know if you have any more requests/questions.

Thanks again!
![sweetalert2DropdownIssue](https://user-images.githubusercontent.com/75046578/101944101-2bd0eb80-3bba-11eb-9f00-82f777bac5c9.gif)

**Comment by limonte** [comment]
The dropdown you're using is implemented in a way that it'll reopen itself when the focus returned to it. SweetAlert2 after closing returns focus to the element which had focus before opening.

This will help:

```js
document.activeElement.blur() // remove focus from the dropdown before opening a popup
Swal.fire() // your code
```

**Comment by isrhedden** [comment]
@limonte that seems to do the trick. We'll use this workaround for now.

Thank you so much! I appreciate your speedy assistance.
