### ISSUE TITLE
Disable dropdown close of multiselect on click of a swal field inside multiselect dropdown in PrimeNG

### ISSUE THREAD

**Issue by chandelshashank** [sweetalert2/sweetalert2#2138]
## New feature motivation

I am working on a requirement in which I am using PrimeNG multiselect. This multiselect has checkboxes followed by some text and logo. On click of logo I am displaying some data in popup. On click of the ok button of popup the background multiselect closes, where in I need to disable closing of popup on click of logo. 
Stackblitz link as follows: [Click here for Demo](https://stackblitz.com/edit/customize-multiselect-withpopup-ic8wxh?file=src/app/app.component.html)

**Step 1: Open mutiselect and click on logo**

<img width="211" alt="Screenshot 2020-12-14 at 11 46 10 AM" src="https://user-images.githubusercontent.com/12397854/102065775-01339c80-3e1f-11eb-814e-7c8d2ec062ba.png">

**Step 2: Click ok of swal popup**

<img width="392" alt="Screenshot 2020-12-14 at 11 57 32 AM" src="https://user-images.githubusercontent.com/12397854/102065834-0f81b880-3e1f-11eb-91d1-956ed4ef19ad.png">

**Step 3: Multiselect Dropdwon closes**

<img width="284" alt="Screenshot 2020-12-14 at 11 58 21 AM" src="https://user-images.githubusercontent.com/12397854/102065885-1c061100-3e1f-11eb-9598-ed78b08ad416.png">

**Comment by limonte** [comment]
No idea why your dropdown works that way, you need to ask somewhere else about it. SweetAlert2 works correctly.

**Comment by chandelshashank** [comment]
The worst response I have ever come across :(
