### ISSUE TITLE
commonJS basic usage

### ISSUE THREAD

**Issue by michimau** [sweetalert2/sweetalert2#2139]
I struggle to make a very simple commonJS usage:

`
const Swal = require('sweetalert2');

Swal.fire('Hello world!');
`
What's wrong with it? if I run the code, nothing happens, no error it thrown either.

This is a fantastic library, thank you!

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by michimau** [comment]
https://stackoverflow.com/questions/65289239/sweetalet2-commonjs-basic-example :+1:
