### ISSUE TITLE
Syntax Error Appearing in sweetalert2.min.js

### ISSUE THREAD

**Issue by sarogersz** [sweetalert2/sweetalert2#2141]
Using Vue 2, I am seeing **"sweetalert2.min.js:3 Uncaught SyntaxError: Unexpected token '==='**" when I run Vue app.  Below this error on the console is a warning:
**Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:8080/@sweetalert2/theme-material-ui/material-ui.css".**

I'm not seeing functionality issues at the moment but I haven't stressed sweetalert yet.

What's this about?

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
