### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by BoldBigflank** [sweetalert2/sweetalert2#2142]
## Current behavior

I'm getting a lot of Sentry error reports on 3528:48
```
    _createClass(SweetAlert, [{
      key: "then",
      value: function then(onFulfilled) {
        var promise = privateProps.promise.get(this); // <-- This line, specifically the 'this'
        return promise.then(onFulfilled);
      }
    }, {
      key: "finally",
      value: function _finally(onFinally) {
```
I'm trying to reproduce it myself and so far have been unable to do so. It seems this crash can happen as soon as loading the page.

## Expected behavior

I would expect the code to handle when promise is undefined. Perhaps there's a race condition happening here?

## Live demo

I'll just note again I haven't been able to reproduce it myself, so I would love some advice on what I could do to perhaps test this part of the code and reproduce the issue I'm seeing.

**Comment by BoldBigflank** [comment]
I'll note that we're using v10.11.1

**Comment by BoldBigflank** [comment]
Got some extra help and found that the issue has something to do with the page's navigation messing with the weakmap promise implementation.

**Comment by limonte** [comment]
> Got some extra help and found that the issue has something to do with the page's navigation messing with the weakmap promise implementation.

I was suspecting this as well. Unfortunately, it's really hard to help you without any kind of working example to reproduce the issue.

**Comment by BoldBigflank** [comment]
Did it a little more and found that when our project navigates, it creates another of the same (Marionette) view with another set of event watchers, so one of the events was being called on a destroyed view, meaning swal was executing on a non-existant view.

**Comment by BoldBigflank** [comment]
Yeah I'll say the solution was to call the function only on views that exist and close this out.
