### ISSUE TITLE
loader display is none in minified version 10.12.5

### ISSUE THREAD

**Issue by NotNotMarshall** [sweetalert2/sweetalert2#2143]
.swal2-loader {
    display: none;
    align-items: center;
    justify-content: center;
    width: 2.2em;
    height: 2.2em;
    margin: 0 1.875em;
    -webkit-animation: swal2-rotate-loading 1.5s linear 0s infinite normal;
    animation: swal2-rotate-loading 1.5s linear 0s infinite normal;
    border-width: .25em;
    border-style: solid;
    border-radius: 100%;
    border-color: #2778c4 transparent #2778c4 transparent
}
I have extracted the above style which was defined in the below minified JS:
https://cdn.jsdelivr.net/npm/sweetalert2@10.12.5/dist/sweetalert2.min.js

And this makes the showLoading() not show any progress spinner. For the moment I have changed it to its proper and "should-be" attrib which is flex.

I hope you guys fix it

Have a nice time!

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
