### ISSUE TITLE
swal2-backdrop-show

### ISSUE THREAD

**Issue by linhdoan24** [sweetalert2/sweetalert2#2144]
swal2-backdrop-show rerun when call new swal in .then()
I need new option for holding backdrop for next Swal.fire()

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by linhdoan24** [comment]
![image](https://user-images.githubusercontent.com/24908232/103755190-ffd14a80-503f-11eb-8b79-c273907cc8a9.png)

👍 It is always flashes when calling in seconds time in .then() --> https://github.com/sweetalert2/sweetalert2/issues/2051
