### ISSUE TITLE
TypeError: Cannot read property 'running' of undefined

### ISSUE THREAD

**Issue by manukieli** [sweetalert2/sweetalert2#2147]
I'm using the version 10.12.6 with webpack, with the **toast** option, the script return this error: **Uncaught TypeError: Cannot read property 'running' of undefined**

I'm using this code:
```
        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
        })

        Toast.fire({
            icon: 'success',
            title: 'Signed in successfully'
        })
```
The console error return this:
![image](https://user-images.githubusercontent.com/14294794/103436547-141adf00-4c1d-11eb-8af1-a1d7398548d7.png)

Thank you so much.

**Comment by manukieli** [comment]
It return this error because I try to execute multiple alert, the first with toast option and the second none.

**Comment by manukieli** [comment]
I would like to run two consecutive sweet alert like this example:
https://jsfiddle.net/tryto/ohpu39r0/2/

To the console you can see the message error: **Uncaught TypeError: Cannot read property 'running' of undefined**

**Comment by manukieli** [comment]
Now they don't return error. Thank you.
But, how can I execute multiple alert like the code of this link: https://jsfiddle.net/tryto/ohpu39r0/8/

**Comment by limonte** [comment]
Unfortunately, multiple alerts aren't possible for now due to the plugin design which was built for modal popups.

Also, I don't have plans to implement multiple toasts in the near future so if you need that functionality please take a look at toasts-specific plugins such as Toastr, Izitoast or noty.
