### ISSUE TITLE
How to make trigger some event when swal destroy

### ISSUE THREAD

**Issue by Jhonlien** [sweetalert2/sweetalert2#2150]
`swal({
        title:"Sorry!",
        text: "Something Wrong!",
        icon: "warning",
        button: false,
        timer: 5000,
        didDestroy: (toast) => {
            window.location.replace("some url")
        }
    });`

how to i redirect to some url after event??

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
