### ISSUE TITLE
Tweaking `$swal2-icon-size` causes animated icons to be offset

### ISSUE THREAD

**Issue by Cherry** [sweetalert2/sweetalert2#2151]
## Current behavior

Tweaking `$swal2-icon-size` seems to only impact static icons. Animated ones such as the default `success` are offset from the box when tweaking this.

Example:
```
$swal2-icon-size: 3em;

// Dark theme
@import '~@sweetalert2/themes/dark/dark.scss';
```

## Expected behavior

All icons should use this variable as a relative point to calculate the other values from.

## Live demo

I forked the parcel demo so you can quickly see this: https://github.com/Cherry/sweetalert2-parcel-demo

Here's a quick demo using Netlify Drop: https://sweetalert2-icon-size-example.netlify.app/. It will pop open 2 alerts, the first showcasing the offset icon, and the second showcasing a correct icon.

**Comment by limonte** [comment]
Thank you for the detailed issue-report @Cherry! And sorry that it took me that long to tackle it, should be good now, please check it out 🚀

**Comment by Cherry** [comment]
Thanks very much - 7 days is an awesome turnaround! I can confirm everything looks good on my end now too! 👍
