### ISSUE TITLE
Template console warnings should not be displayed for valid html tags inside the template

### ISSUE THREAD

**Issue by pomartel** [sweetalert2/sweetalert2#2155]
The current behaviour with Templates is to allow only valid tags. However warning are thrown if markup is added inside the template html. For example this should be valid but it will throw a console warning for the `<a>` tag:

```html
<template>
<swal-html>Check out this <a>link</a>!</swal-html>
</template>
```

A solution might be to only validate the direct children of the template tag and not the descendents:
https://github.com/sweetalert2/sweetalert2/blob/0b510ec49151674eab52819e6637813a409b0ad3/src/utils/getTemplateParams.js#L130

By the way, this is really not an urgent bug as it's only a nagging console warning.

**Comment by limonte** [comment]
Thank you for the detailed issue report @pomartel!
