### ISSUE TITLE
focusConfirm does not work

### ISSUE THREAD

**Issue by bbonch** [sweetalert2/sweetalert2#2159]
## Current behavior

I set focusConfirm to false. Confirm button is focused.

## Expected behavior

Confirm button is not focused.

## Live demo 

https://codepen.io/bbonch/pen/qBaepOY

**Comment by limonte** [comment]
> **focusConfirm**
>
> Set to false if you want to focus the first element in tab order instead of "Confirm"-button by default.

Since the OK button is the only one button in your example it'll be focused. If you don't want any element to be focused:

```js
Swal.fire({
  didOpen: () => document.activeElement.blur()
})
```

**Comment by bbonch** [comment]
Issue is not resolved.
