### ISSUE TITLE
Promise module throws Uncaught ReferenceError

### ISSUE THREAD

**Issue by fluffy-unicorn-71** [sweetalert2/sweetalert2#2162]
## Current behavior

According to the documentation, we can optionally include a promise polyfill for ES6 Promises for compatibility with IE11: 

`<script defer src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>`

Since a few days, however, this produces an error in the browser console: Uncaught ReferenceError: module is not defined

The error appears to be on row 324 in index.js:

`module.exports = Promise;`

## Expected behavior

No Uncaught ReferenceError should be thrown.

## Live demo 

Just go to any website that uses sweetalert2 (e.g. https://www.appenhancer.com/) and the error should appear in the browser console.

**Comment by limonte** [comment]
Please re-read the docs: https://github.com/sweetalert2/sweetalert2#usage

**Comment by fluffy-unicorn-71** [comment]
Not sure what you mean. I read the docs on your homepage (see the attached image). I looked at the page you sent the link to; do you mean that that is the url to use (https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.js) instead of the one on your homepage?

<img width="775" alt="Screenshot 2021-02-09 at 09 22 58" src="https://user-images.githubusercontent.com/34483851/107335654-7ab2d880-6ab8-11eb-80c5-0f38bf937633.png">

**Comment by limonte** [comment]
Oops, sorry @fluffy-unicorn-71 you are right. For some reason the usage guide on https://sweetalert2.github.io/ wasn't syncronized with https://github.com/sweetalert2/sweetalert2#usage

Now it is, please include `promise-polyfill` this way:

```html
<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.js"></script>
```

**Comment by fluffy-unicorn-71** [comment]
No problems, glad I could help! :o)

**Comment by fluffy-unicorn-71** [comment]
By the way, found a visibility issue now that the link is longer (see attached image).
<img width="895" alt="Screenshot 2021-02-09 at 14 16 03" src="https://user-images.githubusercontent.com/34483851/107368923-6c2ce700-6ae1-11eb-8bcc-652ba7d57bcb.png">
