### ISSUE TITLE
Allow type-less icons only (without icon param)

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2165]
> Specifically swal.getIcon() returns null and it could be the sweetalert library doesn't support this out of the box

@mihaerzen Don't forget to set the `icon` option alongside `iconHtml`! It took me a while to realize that this is required to use `iconHtml` in sweetalert2. It will determine the color of the circle and the inner content.

_Originally posted by @zenflow in https://github.com/sweetalert2/sweetalert2-react-content/issues/146#issuecomment-778601283_

**Comment by zenflow** [comment]
@limonte Or perhaps the `iconHtml` option should still work when no `icon` option is provided 🤔 
Right now the `icon` option (when combined with `iconHtml`) only determines a color (to be used for the circle and the inner content). 
Would it make sense to just provide a default for that, like black?
