### ISSUE TITLE
Validation multiple input elements

### ISSUE THREAD

**Issue by Manicraft1001** [sweetalert2/sweetalert2#2167]
## New feature motivation

Using multiple form elements and custom inputs in swal is hard to do, especially if you want to validate them before closing the modal. You can create multiple input elements with a workaround, mentioned here: [https://sweetalert2.github.io/#multiple-inputs](https://sweetalert2.github.io/#multiple-inputs)
Validating them seems to be almost impossible or at least hard to do.

## New feature description

I would like to see a possibility to add unlimited custom input elements and validate them. If not enough people are interested in this change, we could also use a function to validate before returning the values instead of a bigger refactor.

## New feature implementation

It seems like this feature was already requested 2 years ago and demand is still here.
[This PR](https://github.com/sweetalert2/sweetalert2/pull/824) already created this behaviour, but it got canceled.
There is even an example, how you could use in the code: [Example](https://github.com/sweetalert2/sweetalert2/blob/06143789ebbda33a585a726c5acc156eb9cc5949/test/sandbox.html)

---

I think this feature would help people alot making forms faster, easier and more secure :).

**Comment by limonte** [comment]
Thank you for this feature request, I'll try to add the multiple inputs support in v11 because it'll most probably bring some breaking changes.

There's still a possibility that this request will be rejected because of the complexity which it might bring to the codebase.

**Comment by Manicraft1001** [comment]
This was just an idea i had in the last few days: Why remake the input system for Swal when we just could use our own components instead (and implement validation ourself)? This would also open the possibility to not just use form elements but whole components.
Maybe this is less effort and easier to do instead of remake most of the input system?

Let me show an example:```javascript
Swal.fire({
    icon: 'info',
    text: 'Hello world',
    customInput: {
        component: <Test />,
        componentValidation: someValidationLogic
    },
    showConfirmButton: true
}).then(response => {
    // This will stay open until componentValidation returns null
    if (response.isConfirmed) {
        foo();
    }
});```

**Comment by ChronicStone** [comment]
Hi, i dont know if this is pertinent to Say this here, but a two dans ago i releases a package entirely based on Sweetalert2 that that provides you highly customisable multiples formes inputs, multi steps, validation including custom validators.

It IS basically a kind of wrapper i made for Sweetalert2, to create complexe forms

Since this is exactly what you seems to bé loking for, you Can fond it here : 
https://github.com/ChronicStone/sweetforms

Ans this is a live examples of what u Can do
https://stackblitz.com/edit/sweetforms-multi-steps-example?file=index.js

**Comment by limonte** [comment]
@ChronicStone AMAZING WORK! And it seems that you did that only in 4 days! Wow!

1. I love the styling, your form controls (inputs, buttons) are sweeter than originals! Would you mind to contribute to this repo with styles that you're using in Sweetforms?

2. I wonder if you would be interested in becoming a member of SweetAlert2 organisation and move the sweetforms repo under the org. By doing that users will easily find the repo and enjoy using it! Also you will possibly get more valuable contributions from the community. You will continue to be the admin of that repo and make all the decisions about it's development.

Let me know what do you think.

**Comment by Manicraft1001** [comment]
@ChronicStone wow this looks awesome! I'm looking forward to this. There are many changes i missed in Swal. Keep up the good work!

**Comment by ChronicStone** [comment]
@limonte Oh my god, is this for real ? It would be really amazing for me, for both things
I don't know yet how to properly add the styles I made to Sweetalerts, but I'll be glad to do it. And as for becoming a member of Sweetalert2 organisation, I'd love to.

I'm still a beginer, I've been into javascript for a year now, and this the first package I ever made, so I'll probably need to be a little bit guided at the begining on how to work on open-sources projects. But I learn pretty fast and I am really involved in what I work on so this should not be a big issue 😄 

Anyway thanks a lot for your awnser it really made my day !!!


@Manicraft1001 Thanks ! Keep an eye on it, I have a lot of features that I'm planning to add the next few months, like server side  live data search for select inputs, and things I explained on my first message. And if you have any question or feature request, I'm open to it

**Comment by limonte** [comment]
@ChronicStone I'll be happy to have you onboard and guide on how to contribute to this repo! Here's the first issue for you: https://github.com/sweetalert2/sweetalert2/issues/2194

**Comment by Manicraft1001** [comment]
Wow this looks great. I'll close this issue in a few hours if nobody comments anymore, since we'll get a highly improved version of Swal. I'm looking forward to implement this in my application. If i find any bugs, i'll let you guys know. 🎉

@ChronicStone congratulations on your achivement. I think your Sweetforms looks very good and you should keep up the good work!
