### ISSUE TITLE
Allow Animation or CSS Class for allowOutsideClick = false

### ISSUE THREAD

**Issue by young-altair** [sweetalert2/sweetalert2#2172]
## Allow Animation or CSS Class for allowOutsideClick = false
This Vuetify Dialog may illustrate what I mean : [https://vuetifyjs.com/en/components/dialogs/#persistent](https://vuetifyjs.com/en/components/dialogs/#persistent)
Is there a way I can make an animation (for example a shake animation) when the user clicks outside the swal2-content?
Sometimes we need the user's attention that there is an unconfirmed Alert.

**Comment by limonte** [comment]
Very good feature request, thanks @young-altair! I was thinking about this, but it was never requested by anyone.

What do you and others think about this approach:

1. Add new optional param `shakeClass: string` which will have the default value `swal2-shake`
2. Add new method `Swal.shake()` which will add `swal2-shake` class to the popup container, wait for the animation and remove that class when the animation is done
3. When `allowOutsideClick = false` and user clicks the backdrop, call `Swal.shake()` by default

**Comment by young-altair** [comment]
I'm totally agree with you!

I'm trying to play around with this code for a temporary solution :
not very good on the eyes, but enough to attracting the user's attention.
```
const swalOptions = {
  allowOutsideClick: () => {
    let myEl = document.querySelector('.swal2-popup');
    let classes = myEl.classList;
    classes.remove('swal2-show');
    
    setTimeout(() => {
      classes.add('swal2-show');
    }, 200);

    return false
  }
};
```

**Comment by young-altair** [comment]
Sorry, I slipped clicking the close issue button. Even though other friends may have other brilliant ideas.

**Comment by limonte** [comment]
> Very good feature request, thanks @young-altair! I was thinking about this, but it was never requested by anyone.
> 
> What do you and others think about this approach:
> 
> 1. Add new optional param `shakeClass: string` which will have the default value `swal2-shake`. This will allow developers to change the animation or disable it if they want.
> 2. Add new method `Swal.shake()` which will add `shakeClass` class to the popup container, wait for the animation and remove that class when the animation is done. This method will allow developers to bring users' attention to popups in all custom cases.
> 3. When `allowOutsideClick = false` and user clicks the backdrop, call `Swal.shake()` by default

Or, maybe the better naming would be `attentionClass: string` and `Swa.drawAttention()` because the animation could be other than shaking.

**Comment by limonte** [comment]
> I'm totally agree with you!
> 
> I'm trying to play around with this code for a temporary solution :
> not very good on the eyes, but enough to attracting the user's attention.
> 
> ```
> const swalOptions = {
>   allowOutsideClick: () => {
>     let myEl = document.querySelector('.swal2-popup');
>     let classes = myEl.classList;
>     classes.remove('swal2-show');
>     
>     setTimeout(() => {
>       classes.add('swal2-show');
>     }, 200);
> 
>     return false
>   }
> };
> ```

This would be even better:

```js
Swal.fire({allowOutsideClick: () => {
    let myEl = document.querySelector('.swal2-popup');
    let classes = myEl.classList;
    classes.remove('swal2-show')
    classes.add('animate__animated')
    classes.add('animate__headShake');
    
    setTimeout(() => {
      classes.remove('animate__animated')
      classes.remove('animate__headShake');
    }, 1000);

    return false
  }
})
```

Try to use this in the console on https://sweetalert2.github.io/ (Animate.css is included there)

**Comment by limonte** [comment]
Or maybe I'm overthinking the whole thing and should be it, no need in complicating things 💥 

```js
Swal.fire({allowOutsideClick: () => {
    const popup = Swal.getPopup();
    popup.classList.remove('swal2-show', 'animate__animated', 'animate__headShake')
    setTimeout(() => {
        popup.classList.add('animate__animated', 'animate__headShake');
    })
    return false
  }
})
```

**Comment by limonte** [comment]
I added this to the recipe gallery: https://sweetalert2.github.io/recipe-gallery/draw-attention.html

Let's leave it like this for now, no need in the additional APIs.
