### ISSUE TITLE
is it no longer possible to click on the alert and close?

### ISSUE THREAD

**Issue by PH7-Jack** [sweetalert2/sweetalert2#2173]
Whenever I used it had the function of closing the alert as soon as I clicked it, but now it is not working anymore, have you removed this feature?

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
