### ISSUE TITLE
Button outline color doesn't change

### ISSUE THREAD

**Issue by iamludal** [sweetalert2/sweetalert2#2178]
## Current behavior

When you change the color of the confirm button (with `confirmButtonColor`), its outline color doesn't seem to change.

## Expected behavior

The outline color should be the same as the one defined in `confirmButtonColor`.

## Live demo 

![image](https://user-images.githubusercontent.com/44783088/108772351-2fd79d00-755d-11eb-98ed-19ab6d374226.png)

Here, I've set the `confirmButtonColor` value to `#ddd`, but the outline color is still bluish.

**Comment by limonte** [comment]
The expected behavior doesn't sound legit for me. The outline color is the same regardless of button background color both for native HTML buttons and for buttons in SweetAlert2.
