### ISSUE TITLE
Switch between themes

### ISSUE THREAD

**Issue by davidsu06** [sweetalert2/sweetalert2#2181]
Hi, how could I switch between light/dark theme using React and Redux? I've seen how to install and impor the dark theme but, how could I switch between those themes according to a state?

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
