### ISSUE TITLE
Types aren't available when importing Swal from 'sweetalert2/dist/sweetalert2.js'

### ISSUE THREAD

**Issue by SMAH1** [sweetalert2/sweetalert2#2187]
Types are not available for this code:

![image](https://user-images.githubusercontent.com/6059356/110821087-6a00a880-8298-11eb-8273-d7545e7cd982.png)

But they become available when 

![image](https://user-images.githubusercontent.com/6059356/110821175-800e6900-8298-11eb-9e79-76c67710a62a.png)

**Comment by limonte** [comment]
I created a repo with a minimal code to reproduce the issue: https://github.com/sweetalert2/issue-2187

**Comment by limonte** [comment]
The solution is to include `sweetalert2.d.ts` in `tsconfig.json`:

```js
{
  ...
  "include": [
    "node_modules/sweetalert2/sweetalert2.d.ts"
  ]
}
```

**Comment by vladluca** [comment]
I have the same issue, adding `node_modules/sweetalert2/sweetalert2.d.ts` to `tsconfig.json` does not solve the issue.

**Comment by mordechai-s** [comment]
I'm getting this error after updating to version 11.6.7

![image](https://user-images.githubusercontent.com/93929177/202292410-aab71307-15c2-4a2a-a867-98d98189b98f.png)

**Comment by limonte** [comment]
@mordechai-s what version of TS you're using in that project?

**Comment by mordechai-s** [comment]
> @mordechai-s what version of TS you're using in that project?

~4.7.2

**Comment by limonte** [comment]
Hello @mordechai-s 

Should be fixed in `11.6.9`, check it out.

**Comment by mordechai-s** [comment]
> Hello @mordechai-s
> 
> Should be fixed in `11.6.9`, check it out.

Now (version `11.6.9`) I get this: 
![image](https://user-images.githubusercontent.com/93929177/202492747-36021568-c3b1-4dd1-b1b9-8eacb34441fb.png)

**Comment by mordechai-s** [comment]
> @mordechai-s did you try [this suggestion](https://github.com/sweetalert2/sweetalert2/issues/2187#issuecomment-797714472)?

Not sure how to do it in angular, tsconfig.json or tsconfig.app.json?

**Comment by paxperscientiam** [comment]
> The solution is to include `sweetalert2.d.ts` in `tsconfig.json`:
> 
> ```js
> {
>   ...
>   "include": [
>     "node_modules/sweetalert2/sweetalert2.d.ts"
>   ]
> }
> ```

This works for me. Thank you!

**Comment by limonte** [comment]
Actually, it's better to use `"files"` instead of `"include"`:

```json
{
  ...
  "files": [
    "node_modules/sweetalert2/sweetalert2.d.ts"
  ]
}
```

More details about the reasoning here: https://github.com/sweetalert2/sweetalert2/issues/2752#issuecomment-2302129790

Related StackOverflow: https://stackoverflow.com/questions/51819184/best-practice-to-setup-tsconfig-files-vs-include
