### ISSUE TITLE
loaderHtml has no effect when popup is loading

### ISSUE THREAD

**Issue by fluffy-unicorn-71** [sweetalert2/sweetalert2#2190]
## Current behavior

I have the following code:

const SwalBase = Swal.mixin({
  buttonsStyling: false,
  showLoaderOnConfirm: false,
  showLoaderOnDeny: false,
  customClass: {
    confirmButton: "button-submit",
  },
  showClass: {
    popup: "swal2-noanimation",
    backdrop: "swal2-noanimation",
  },
  hideClass: {
    popup: "",
    backdrop: "",
  },
  loaderHtml: '<div class="css3-spinner"><div class="css3-spinner-bounce1"></div><div class="css3-spinner-bounce2"></div><div class="css3-spinner-bounce3"></div></div>'
});

When the popup loads, the default loader is displayed, not the one specified in loaderHtml. Please note that I mean the loader that is shown when the popup loads. The loader for confirm/deny is disabled in my code as you can see.

## Expected behavior

The loader that is specified in loaderHtml should be displayed when the popup loads.

## Live demo 

https://codepen.io/archer55/pen/yLVwGJy

The loader used in the codepen example comes from the site below but it is the same thing regardless of what loader you use.

https://projects.lukehaas.me/css-loaders/

---

**Comment by limonte** [comment]
https://sweetalert2.github.io/recipe-gallery/bootstrap.html

**Comment by fluffy-unicorn-71** [comment]
The example you are referring to only shows the loader when clicking the OK button. My ticket concerned the loader that is shown when the popup is loaded. Everything works as expected for the loader that shows when the confirm button is clicked. For that, your example is correct. However, the example you are referring to does not work for the loader that is shown when the popup is loaded. 

If you claim that the loader and loaderHtml works as expected for the loader shown at popup LOADING, please provide a working example for that.

**Comment by indrif** [comment]
I also want to know how to get this working. Don't know why this issue was closed?

**Comment by limonte** [comment]
@indrif please create a new issue **AND PLEASE FOLLOW THE ISSUE TEMPLATE**

**Comment by indrif** [comment]
But we already have this issue? You want another duplicate? 

No problem, I’ll create one.  

Skickat från min iPhone
