### ISSUE TITLE
Reopen issue #2190

### ISSUE THREAD

**Issue by fluffy-unicorn-71** [sweetalert2/sweetalert2#2192]
My previously opened issue #2190 was closed due to a misunderstanding. Since the issue was closed, I am not sure if you read the post I wrote and I therefore chose to create a new issue. Sorry about that.

Please read the last post I wrote in #2190. Your example referred to a customized loader when the confirm button is clicked, but my issue concerned  the loader that is shown when the popup is **loading**. In other words: the error I want to report is that the loader and htmlLoader attributes do not work for customizing the loader when the popup window is loading.

**Comment by limonte** [comment]
I do not understand you, sorry.
