### ISSUE TITLE
Transfer Sweetforms into SweetAlert2 organisation

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2194]
@ChronicStone After you accept the invitation to SweetAlert2 org, you'll be able to transfer the repo into the org. The transfer button is located in the repo settings.

After transferring please send a PR to this repo, in the PR add the link and description of Sweetforms here https://github.com/sweetalert2/sweetalert2#related-projects

**Comment by ChronicStone** [comment]
I've moved the repository and added the projects to the Related Projects section ✔️ 
PR : https://github.com/sweetalert2/sweetalert2/pull/2195

**Comment by limonte** [comment]
Done in #2195 

@ChronicStone FYI there are special keywords which will close the issue once the PR is merged: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
