### ISSUE TITLE
Copy colors for confirm/cancel/deny buttons from sweetforms

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2196]
I like the buttons' colors of sweetforms. @ChronicStone could you please copy the confirm button color from there. Also, copy the cancel button color to be the deny button color and also if you have a better color for the cancel button feel free to change it.

Thanks!

**Comment by ChronicStone** [comment]
@limonte  By copying, you mean providing you the colors HEX, or adding them somewhere on Sweetalert2 code ?

**Comment by limonte** [comment]
@ChronicStone Sorry about not being very clear in the issue description! I meant simple changing values of these variables:

- https://github.com/sweetalert2/sweetalert2/blob/master/src/variables.scss#L172
- https://github.com/sweetalert2/sweetalert2/blob/master/src/variables.scss#L180
- https://github.com/sweetalert2/sweetalert2/blob/master/src/variables.scss#L188

**Comment by ChronicStone** [comment]
#2199

**Comment by ChronicStone** [comment]
# #2199 #2199
