### ISSUE TITLE
[Vue warn]: Unknown custom element <swal-title> - did you register the component correctly?

### ISSUE THREAD

**Issue by helloCheng09** [sweetalert2/sweetalert2#2201]
Error: 
![image](https://user-images.githubusercontent.com/41097785/112244523-6bfc3b80-8c8a-11eb-9cce-1fdc1bfe6e48.png)

Code:
![image](https://user-images.githubusercontent.com/41097785/112244597-7ae2ee00-8c8a-11eb-9492-0ef2ea6ffe98.png)

**Comment by limonte** [comment]
Vue experts, help is needed here!

How to prevent Vue from throwing those warnings?

**Comment by leicaflorian** [comment]
Hi, i would like to help with this issue, but we should have a bit more details about it.

Some sample code?
Where is defined the component "swal-title"? Is imported globally or onply on that page?

**Comment by limonte** [comment]
After taking a closer look, I don't think that anythyng is wrong with SweetAlert2 or Vue. It's just a `<template>` inside a `<template>` which produces the unexpected behavior. I believe moving the SweetAlert2 template outside of Vue template will help.

If not, please report another issue WITH LIVE DEMO.
