### ISSUE TITLE
It would be great if this autofocus feature could be turned off.

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2206]
It would be great if this autofocus feature could be turned off.
I have an endless loop:
onFocus is calling swal, and swal is calling onFocus on input after closing. Over and over again ;)

_Originally posted by @PawelGIX in https://github.com/sweetalert2/sweetalert2/issues/133#issuecomment-812486699_

**Comment by ana-marcia** [comment]
still not solved for my case, even with the update of the version "sweetalert2": "^ 10.16.0" and returnFocus: false, use vue.js

**Comment by limonte** [comment]
> still not solved for my case, even with the update of the version "sweetalert2": "^ 10.16.0" and returnFocus: false, use vue.js

you need to open the new issue and provide the live example.
