### ISSUE TITLE
SweetAlert2: Unknown parameter "didOpen"

### ISSUE THREAD

**Issue by ninja71-mn** [sweetalert2/sweetalert2#2208]
Hi
I wanna use sweetalert2 toast like this :
_____________________________________________________________________________________
import Swal from 'sweetalert2'
const Toast = Swal.mixin({
    toast: true,
    position: 'top-end',
    showConfirmButton: false,
    timer: 3000,
    timerProgressBar: true,
    didOpen: function(toast) {
        toast.addEventListener('mouseenter', Swal.stopTimer)
        toast.addEventListener('mouseleave', Swal.resumeTimer)
    }
})
window.toast=Toast;

toast.fire({
            icon: 'error',
            title: 'Signed in successfully'
        });
_____________________________________________________________________________________

but I get warning on browser console " SweetAlert2: Unknown parameter "didOpen" " and stopTimer and resuneTimer not working.

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
