### ISSUE TITLE
SweetAlert2: Unknown parameter "didOpen"

### ISSUE THREAD

**Issue by ninja71-mn** [sweetalert2/sweetalert2#2209]
Hi
I wanna use sweetalert2 toast 

## Current behavior

import Swal from 'sweetalert2'
const Toast = Swal.mixin({
toast: true,
position: 'top-end',
showConfirmButton: false,
timer: 3000,
timerProgressBar: true,
didOpen: function(toast) {
toast.addEventListener('mouseenter', Swal.stopTimer)
toast.addEventListener('mouseleave', Swal.resumeTimer)
}
})
window.toast=Toast;

toast.fire({
icon: 'error',
title: 'Signed in successfully'
});

## Expected behavior

but I get warning on browser console " SweetAlert2: Unknown parameter "didOpen" " and stopTimer and resuneTimer not working.

**Comment by limonte** [comment]
You are using the outdated version, please upgrade to the latest version.
