### ISSUE TITLE
Popup box not showing with window full screen(f11). 

### ISSUE THREAD

**Issue by skdhayal** [sweetalert2/sweetalert2#2211]
## Live demo 

---

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by limonte** [comment]
Duplicate of #2025

**Comment by skdhayal** [comment]
Thanks @limonte
