### ISSUE TITLE
Custom place message and title

### ISSUE THREAD

**Issue by manukieli** [sweetalert2/sweetalert2#2213]
With this code:
`const Toast = Swal.mixin({
    toast: true,
    position: 'top-end',
    showConfirmButton: false,
    timer: 183000,
    timerProgressBar: true,
    didOpen: (toast) => {
        toast.addEventListener('mouseenter', Swal.stopTimer)
        toast.addEventListener('mouseleave', Swal.resumeTimer)
    }
})`

`Toast.fire({
    icon: 'success',
    title: 'Signed in successfully',
    html: 'This is the message description of the alert.<br>With some detaills.'
})`

I get this result:
![image](https://user-images.githubusercontent.com/14294794/114370309-a1a48e00-9b7f-11eb-9e3a-0040c79faaa7.png)

It's a very large alert.
What I realy need, it's this:
![image](https://user-images.githubusercontent.com/14294794/114370400-ba14a880-9b7f-11eb-8b20-e0082dfc46df.png)

This next image explain the detail of my need:
![image](https://user-images.githubusercontent.com/14294794/114370462-c862c480-9b7f-11eb-9f9c-4bc72825f6df.png)

How can I do it??

**Comment by limonte** [comment]
Thank you for this request @manukieli 

The expected outcome seems valid, let me see what I can do to achieve it. I'll get back to you this week with the solution.

**Comment by limonte** [comment]
The default look before:

![image](https://user-images.githubusercontent.com/6059356/114708347-e709bc80-9d33-11eb-87cc-129654131544.png)

The default look after #2215:

![image](https://user-images.githubusercontent.com/6059356/114708303-d78a7380-9d33-11eb-84cb-0430d298905c.png)

And bu using the `customClass` parameter you can achieve the requested styling with the centered icon: https://codepen.io/limonte/pen/XWpqROJ

![image](https://user-images.githubusercontent.com/6059356/114709751-a448e400-9d35-11eb-85a0-e24867926da3.png)

What do you think @manukieli?

**Comment by limonte** [comment]
I'm thinking about making the icon alignment the default behavior, because it looks much better.

**Comment by manukieli** [comment]
> The default look before:
> 
> ![image](https://user-images.githubusercontent.com/6059356/114708347-e709bc80-9d33-11eb-87cc-129654131544.png)
> 
> The default look after #2215:
> 
> ![image](https://user-images.githubusercontent.com/6059356/114708303-d78a7380-9d33-11eb-84cb-0430d298905c.png)
> 
> And bu using the `customClass` parameter you can achieve the requested styling with the centered icon: https://codepen.io/limonte/pen/XWpqROJ
> 
> ![image](https://user-images.githubusercontent.com/6059356/114709751-a448e400-9d35-11eb-85a0-e24867926da3.png)
> 
> What do you think @manukieli?

The last example it's GREAT, FANTASTIC, BEAUTIFUL.
Thank you so much. Good job.

**Comment by limonte** [comment]
If you're happy, I'll go ahead and close the issue.

Please don't hesitate to open new issues with styling requests.
