### ISSUE TITLE
Contrast style alert

### ISSUE THREAD

**Issue by manukieli** [sweetalert2/sweetalert2#2216]
I would like to have a style contrat according to the type of alert like this:

![image](https://user-images.githubusercontent.com/14294794/114789575-9d48c280-9d83-11eb-8f16-e1481737e8a4.png)

With the icon animation white color.
I need to use both type to the same page: normal style and contrast style.
It's possible??

**Comment by limonte** [comment]
Thanks for this feature-request @manukieli 

I'll think on the best approach and get back to you in a couple of days.

**Comment by limonte** [comment]
I added the recipe with colored toasts to the documentation page: https://sweetalert2.github.io/recipe-gallery/colored-toasts.html

**Comment by manukieli** [comment]
INCREDIBLE.
Very GOOD.
