### ISSUE TITLE
New release not found build dist folder 

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [sweetalert2/sweetalert2#2217]
Hello 
please make dist folder in all release build 

Thank you

**Comment by limonte** [comment]
Can you be more specific? **What exactly** is missing and **where exactly**?

**Comment by rajesh-smartwebtech** [comment]
@limonte  Thanks for replay 

production build  `dist` folder is not found is in last release version

Here all release has not finally compiled js files in `dist` folder  
![image](https://user-images.githubusercontent.com/35251001/115017728-967d9500-9ed4-11eb-9af7-25c034321a96.png)


I hope you will be understanding 

Thank you

**Comment by limonte** [comment]
Duplicate of #1606

**Comment by limonte** [comment]
Actually, it should be possible to include the `dist` folder into GitHub releases.

**Comment by rajesh-smartwebtech** [comment]
@limonte  I don't understand What exactly ?
with about last comment

**Comment by limonte** [comment]
🎉 All files from the `dist` folder are available on GitHub releases starting from  https://github.com/sweetalert2/sweetalert2/releases/tag/v10.16.3
