### ISSUE TITLE
Confirm by Enter key does not work in angular 11

### ISSUE THREAD

**Issue by mbabaei0** [sweetalert2/sweetalert2#2218]
"sweetalert2": "^10.9.0"
"@angular/compiler": "~11.0.5",
 "@angular/core": "~11.0.5",

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
