### ISSUE TITLE
Input in swal modal not usable, when bootstrap modal background

### ISSUE THREAD

**Issue by MiDniGG** [sweetalert2/sweetalert2#2220]
## Current behavior

If you open a swal prompt in front of a bootstrap modal, the input field is not usable, buttons are working.

## Expected behavior

I want to be able to insert data, as if the swal was opened without a bootstrap modal in the background.

## Live demo

To reproduce the error, click on the button to open a bootstrap modal. After that the swal will popup but the input is not usable.
https://codepen.io/midnigg/pen/qBRJPNo

I haven't found any errors.
The `z-index` of `swal2-content` is `1`, but the `z-index` of `swal2-actions` also and the buttons are working.
The `z-index` of `.swal2-container` is `1060` so 20 higher then the bootstrap modal.

**Comment by limonte** [comment]
Duplicate of #374

You need to use this workaround:

```js
$.fn.modal.Constructor.prototype._enforceFocus = function () {}
```

Live demo: https://sweetalert2.github.io/recipe-gallery/bootstrap-custom-loader.html

**Comment by benyaminl** [comment]
@limonte is there any workaround for bs5? seems the new bootstrap.Modal.constructor doesn't use _enforceFocus

Thanks
