### ISSUE TITLE
Block Swal Toast Titles Misalignment

### ISSUE THREAD

**Issue by zachduda** [sweetalert2/sweetalert2#2221]
## Current behavior
When firing a Swal toast, the title is set to "block".
(see this [commit](https://github.com/sweetalert2/sweetalert2/commit/27fa048d4e7b5aeb78d9622baa38704759160b38))

## Expected behavior
The title is supposed to be aligned with the icon and description, but now the description is forced downward.

## Live demo 
https://codepen.io/limonte/pen/JjoWRMx

**Comment by limonte** [comment]
> The title is supposed to be aligned with the icon and description

Why? Could you show the actual use-case?

**Comment by zachduda** [comment]
I'm using it on my parody empanada website to display errors when trying to submit a login form. They used to be formatted like this:
<img width="954" alt="beforeBlockToast-min" src="https://user-images.githubusercontent.com/10857265/115802887-bcf87000-a3ad-11eb-84bf-b2ce1b104597.png">

But they are now appearing like this:
<img width="957" alt="BlockToast-min" src="https://user-images.githubusercontent.com/10857265/115802940-d00b4000-a3ad-11eb-889e-bcffa464dfb9.png">

This wouldn't be so bad if it was more centered, but if the CSS is going to be block I think it ought to be set or overridden in a parameter. :)

[Old Behavior on Codepen](https://codepen.io/zestytoaster/pen/bGgOgKg)

**Comment by limonte** [comment]
Thank you for the provided details @zachduda 

This change was made in order for toasts to look good on moth desktop and mobile devices. The expected by you behavior (the first screenshot) will look bad on mobile devices.

Would something like this be good for your project?

![image](https://user-images.githubusercontent.com/6059356/114709751-a448e400-9d35-11eb-85a0-e24867926da3.png)

**Comment by limonte** [comment]
In order to test it for your project you can check this codepen an copy custom styles: https://codepen.io/limonte/pen/XWpqROJ

**Comment by zachduda** [comment]
Ooh! I really like how the custom one classes look in your codepen. I renamed the classes to: 
`.empanadasio-toast {max-width: 350px !important;} .empanadasio-toast-icon {position: absolute !important;top: 50%;margin-top: -20px !important;} .empanadasio-toast-gap {margin-left: 4em !important;}` and inserted them after all CSS and SweetAlerts via Javascript. I'm firing it using this: `Swal.fire({
    title: 'Title',
    html: 'This is an error message',
    icon: 'error',
    showConfirmButton: false,
    toast: true,
    position: 'top',
    customClass: {
        popup: 'empanadasio-toast',
        icon: 'empanadasio-toast-icon',
        title: 'empanadasio-toast-gap',
        content: 'empanadasio-toast-gap',
    },
    timer: 10000,
    timerProgressBar: false
    });`

It resolved some of the alignment issues but not completely. For some reason the gap class doesn't seem to be working and the text is being aligned to the center.

It's appearing as:
<img width="956" alt="blocktext2" src="https://user-images.githubusercontent.com/10857265/115934354-da394700-a45e-11eb-9062-904e9371c724.png">

You can view it live if you'd like: [empanadas.io/login](https://empanadas.io/server/login?s=1)

**Comment by zachduda** [comment]
Oops! Nevermind, for some reason it needed some encouragement. I added `text-align:left; float:left;` to the gap css and now it's working. Thank you so much for your help! :)

Out of curiosity, will the current non-custom class block appearance for toasts be the new default?

**Comment by limonte** [comment]
Glad that you liked the suggested solution! I'll make that layout as default in #2222 (subscribe to it to track the progress)
