### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by joshxyzhimself** [sweetalert2/sweetalert2#2225]
## Current behavior

Similar to https://github.com/sweetalert2/sweetalert2/issues/2142

Encountered this right now.

We got a react useEffect hook, and when the useEffect hook's dependency updates, the `await Swal.fire()` calls tend to throw this error.

```js
const success: (text, timer) => {
  AssertionError.assert(typeof text === 'string');
  AssertionError.assert(typeof timer === 'number' || timer === undefined);
  return Swal.fire({ text, timer, icon: 'success' });
};
```

```js
const [some_var, set_some_var] = useState(null);

useEffect(() => {
  const on_message = (message) => {
    try {
      AssertionError.assert(message instanceof Object);
      switch (message.type) {
        case 'test': {
          await success('test');
          break;
        }
        default: {
          break;
        }
      }
    } catch (e) {
      console.error(e);
    }
  };
  websocket.on('message', on_message);
  return () => {
    websocket.off('message', on_message);
  };
}, [some_var]);
```

If `some_var` happens to update while websocket receives a `{ type: 'test' }` message, we get the `Cannot read property 'then' of undefined` error.

```
ba4f4660c620bad1813c.js:2478 TypeError: Cannot read property 'then' of undefined
    at SweetAlert.then
```

```js
  // `catch` cannot be the name of a module export, so we define our thenable methods here instead
  then (onFulfilled) {
    const promise = _privateProps_js__WEBPACK_IMPORTED_MODULE_4__.default.promise.get(this) // This "promise" is undefined
    return promise.then(onFulfilled) // So it errors here when it tries to access "then" property
  }
```

## Expected behavior

`await success('test');` must work

**Comment by joshxyzhimself** [comment]
The scenario here is the websocket receives two messages from the server, one of them triggers a dialog, another triggers a separate data update on `some_var`

**Comment by joshxyzhimself** [comment]
Current workaround is avoid using `await Swal.fire()` calls inside that websocket listener hook, but it's weird when you wanna show a dialog first before reflecting other changes infront of the user lol

**Comment by joshxyzhimself** [comment]
Is the polyfill required now?

Like this issue https://github.com/sweetalert2/sweetalert2/issues/2162

**Comment by joshxyzhimself** [comment]
Possibly related https://github.com/sweetalert2/sweetalert2/issues/2098

**Comment by limonte** [comment]
Unfortunately, I'm not able to help here without a live demo. I will reopen the issue, if you can provide a repo with minimal working example which demonstrates the issue.
