### ISSUE TITLE
missing "dist" folder

### ISSUE THREAD

**Issue by ozimstudio** [sweetalert2/sweetalert2#2226]
there is no any dist folder inside :)

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/116681468-b3769580-a9b5-11eb-98f5-1c037f6e7a65.png)

**Comment by ozimstudio** [comment]
![Screenshot_2021-04-30-14-08-45-683_com android chrome](https://user-images.githubusercontent.com/10221490/116687431-d6a54300-a9bd-11eb-8b3d-4e155ae141ac.jpg)
