### ISSUE TITLE
How to use promise for single swal in queue chain using SweetAlert2

### ISSUE THREAD

**Issue by shurkanTwo** [sweetalert2/sweetalert2#2228]
hi everyone,

I have a question regarding queuing multiple swals.
How can I use the returned promise for each step separately? I only found the example which handles a .then(...) for the entire queue. But because I add items to the queue dynamically, I don't know how many items were in it and can not track back which return value belonged to which Swal.

https://stackoverflow.com/questions/67356099/how-to-use-promise-for-single-swal-in-queue-chain-using-sweetalert2

Thanks in advance!
Lucas

**Comment by limonte** [comment]
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await

**Comment by shurkanTwo** [comment]
Hey Limonte,
thanks for your help!

I had a look at async/await. Still I was not yet able to wait for the first Swal to open&close, before opening the second one.
You probably don't have time to look at my code below?

`
	async function firstSwal() {
		let response = await Swal.fire({
			title: "First swal?",
			icon: "question",
			buttons: true,
			dangerMode: true,
		});
		if (response) {
			checkinBooking(bookingId);
			return true;
		}
	}

	async function secondSwal() {
		let response = await Swal.fire({
			title: "Second swal?",
			icon: "question",
			buttons: true,
			dangerMode: true,
		});
		if (response) {
			checkinBooking(bookingId);
			return true;
		}
	}

	firstSwal();
	secondSwal();`

**Comment by shurkanTwo** [comment]
Okay my bad, I think I understand now.
I have converted the entire function that handles the consecutive opening of multiple Swals into an async function. For each of the Swal.fire(...) I use the await keyword.

Does that sound correct to you?

**Comment by limonte** [comment]
> Okay my bad, I think I understand now.
> I have converted the entire function that handles the consecutive opening of multiple Swals into an async function. For each of the Swal.fire(...) I use the await keyword.
> 
> Does that sound correct to you?

Yup, that's correct.

**Comment by shurkanTwo** [comment]
Okay, thanks a lot! :)

Hmm, that means I have to make all my functions within which I previously used `alert(...);` async.
Is there another way to avoid that? Because at the places where I call my own functions I rely on their execution being done before further code is run.
