### ISSUE TITLE
[BREAKING] Get rid of .queue(), .getQueueStep(), .insertQueueStep(), . deleteQueueStep()

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2229]
## Current behavior

The `.queue()` method was introduced a log time ago in https://github.com/sweetalert2/sweetalert2/pull/165

In v11 the IE11 support will be dropped and all modern browsers support `async/await`: https://caniuse.com/?search=await

`async/await` can perfectly replace all use-cases of `.queue()` and therefore there's no need in that old burden anymore.

**Comment by elbojoloco** [comment]
@limonte We're currently using version 10 because of the queue support. We would like to upgrade, but are having trouble using async/await to replicate the queue ease of use, do you have an example implementation for this?

**Comment by limonte** [comment]
https://sweetalert2.github.io/recipe-gallery/queue-with-progress-steps.html

**Comment by limonte** [comment]
> @limonte We're currently using version 10 because of the queue support. We would like to upgrade, but are having trouble using async/await to replicate the queue ease of use, do you have an example implementation for this?

https://sweetalert2.github.io/recipe-gallery/queue-with-progress-steps.html

**Comment by MumiaIrrequieta** [comment]
Unfortunately the async/await doesn't work for me. I tried but syncing all the app is not feasible.
I have an angular app with several components and, as normal, more than one active at a time and they do their validations and throw alerts if necessary, and without the queue, if more than one is fired only the last one is visible.

**Comment by mhutfield-Itrinegy** [comment]
for anyone else looking for an answer to this question this works:

```

  let q = ['a','b','c'];
  for (let i = 0; i < q.length; i++) {
      await Swal.fire(q[i]);
   }

```

**Comment by avimar** [comment]
The docs [1] show these options - these are no longer available?

progressSteps
[]	Progress steps, useful for queues.

currentProgressStep
undefined	Current active progress step.


progressStepsDistance
undefined


[1] https://sweetalert2.github.io/#configuration
