### ISSUE TITLE
How can I adjust the icon size of icons? I am having trouble with the success and error icons especially

### ISSUE THREAD

**Issue by shurkanTwo** [sweetalert2/sweetalert2#2230]
Hey everyone,

I would like to resize the icons to a smaller size.

I found that you can use a less property `$swal2-icon-size`. However I am using plain css.
How can I adjust the size in a simple manner?

Hopefully it is possible to avoid adjusting each value manually?

Thanks and regards,
Lucas

**Comment by limonte** [comment]
The Sass variable `$swal2-icon-size` is the only one way to achieve the icon resizing for all browsers.

`customClass` + `zoom` would also work, but not in Firefox.

Alternatively, you can use custom icons by using `iconHtml`: https://stackoverflow.com/a/67344910
