### ISSUE TITLE
Property 'getContent' does not exist on type 'typeof Swal'

### ISSUE THREAD

**Issue by Sanyaorg** [sweetalert2/sweetalert2#2245]
## Current behavior

Uncaught TypeError: Swal.getContent is not a function

Missing method on Swal object. Some Sweetalert examples are broken and show error (e.g. timer doesn't show countdown)

## Live demo 
<img width="1440" alt="Screen Shot 2021-05-14 at 3 03 12 PM" src="https://user-images.githubusercontent.com/13110421/118317489-1d1e9580-b4c6-11eb-8c26-066f0ab34ea3.png">

**Comment by Arenivar93** [comment]
I have the same problem. Uncaught TypeError: Swal.getContent is not a function.

![Screenshot_20210514_140744](https://user-images.githubusercontent.com/30383182/118323587-14c25c80-b4be-11eb-94a3-a2f04fc44981.png)

**Comment by Sanyaorg** [comment]
I fixed it with rollback to "sweetalert2": "10.16.7". The problem is I can't find any alternative methods for getContent() +  Sweetalert examples on website are broken. Will there be replacement?

**Comment by limonte** [comment]
The new major release has just been released, please read the breaking changes in the release notes: https://github.com/sweetalert2/sweetalert2/releases/tag/v11.0.0

Instead of the removed `.getContent()` method, please use `.getHtmlContainer()`.

**Comment by Sanyaorg** [comment]
> The new major release has just been released, please read the breaking changes in the release notes: https://github.com/sweetalert2/sweetalert2/releases/tag/v11.0.0
> 
> Instead of the removed `.getContent()` method, please use `.getHtmlContainer()`.

Was confused because `.getContent()` and `.getHtmlContainer()` were still present on web site. Thanks. Appreciate it

**Comment by limonte** [comment]
> > The new major release has just been released, please read the breaking changes in the release notes: https://github.com/sweetalert2/sweetalert2/releases/tag/v11.0.0
> > Instead of the removed `.getContent()` method, please use `.getHtmlContainer()`.
> 
> Was confused because `.getContent()` and `.getHtmlContainer()` were still present on web site. Thanks. Appreciate it

I'm working on it now, sorry for the confusion!
