### ISSUE TITLE
10.16.8 has popboxes no longer expand correctly to 100%

### ISSUE THREAD

**Issue by nobkins** [sweetalert2/sweetalert2#2246]
After the recent release of V11 and 10.16.8 we were linking to:
`<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>`

WE instantly got purple "save" buttons (a feature of V11) and our popup boxes broke if they are set to full screen as per the image below. Note that half the screen to the left is empty and the popup is expanding off the right of the full screen browser window.
![image](https://user-images.githubusercontent.com/6816570/118372588-55979f80-b5aa-11eb-810f-7b958bd6525c.png)

Downgrading to 10.16.7 fixes the issues for us.
`<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10.16.7"></script>`
![image](https://user-images.githubusercontent.com/6816570/118372613-7eb83000-b5aa-11eb-9aa3-a1e076da7009.png)

Not sure what 10.16.8 is all about as it has the new colour buttons of 11 and it broke popup boxes that are 100% in the same way that V11 does (I tested to see if upgrading to 11 fixed the issue).

**Comment by limonte** [comment]
Hey @nobkins and thank you for reporting this issue!

`v10.16.8` was published by mistake, it contains breaking changes from v11. I just published `v10.16.9` which is the same as `v10.16.7`. https://cdn.jsdelivr.net/npm/sweetalert2@10 should be good now.

**Comment by limonte** [comment]
Could you please provide the code to reproduce issue with 100% width in v11?

**Comment by limonte** [comment]
`Swal.fire({width: '100%'})` should be fixed now in v11 as well.
