### ISSUE TITLE
when i add inputAttributes and pass it onblur: 'this.focus()' it causes 'RangeError: Maximum call stack size exceeded.' error

### ISSUE THREAD

**Issue by levani-k** [sweetalert2/sweetalert2#2252]
## Current behavior

![image](https://user-images.githubusercontent.com/72494243/118661437-2aa68900-b800-11eb-94d9-829aac22ff1d.png)

when i add inputAttributes and pass it onblur: 'this.focus()' it causes this error, if it is possible to change this attribute with another attribute with this functionality or what should i do???

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
