### ISSUE TITLE
when i add inputAttributes and pass it onblur: 'this.focus()' it causes 'RangeError: Maximum call stack size exceeded.' error

### ISSUE THREAD

**Issue by levani-k** [sweetalert2/sweetalert2#2253]
## Current behavior

when I use inputAttributes and pass it onblur: 'this.focus()' focus happens on input element but it causes 'RangeError: Maximum call stack size exceeded.' error

## Expected behavior

when I use inputAttributes and pass it onblur: 'this.focus()'  it shoud focus on input element and do not cause any error

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
