### ISSUE TITLE
Can't focus to some input element

### ISSUE THREAD

**Issue by levani-k** [sweetalert2/sweetalert2#2254]
## Current behavior

I trying to focus on some input element after open sweetAlert, but it doesn't works, if i add inputAttributes with onblur: 'this.focus()'  
it causes 'RangeError: Maximum call stack size exceeded.' error
![image](https://user-images.githubusercontent.com/72494243/118686727-541ddf80-b815-11eb-9641-7f061317ec7f.png)

## Expected behavior

After open sweetAlert input element  should be focused

## Live demo 

![image](https://user-images.githubusercontent.com/72494243/118687000-98a97b00-b815-11eb-9c9a-7812a39896be.png)

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by levani-k** [comment]
thanks for help
