### ISSUE TITLE
Functions willOpen/didOpen/didRender/didDestroy having "this" undefined

### ISSUE THREAD

**Issue by Valentina16** [sweetalert2/sweetalert2#2255]
## Current behavior
Since the version 10.16.8, the "this" variable into willOpen/didOpen/didRender/didDestroy functions is undefined.

## Expected behavior
Until the version 10.16.7, the "this" variable into willOpen/didOpen/didRender/didDestroy functions was representing the SweetAlert configuration.

## Live demo 
This is the version which have the issue (using v.11): https://codepen.io/Viper16/pen/LYWxMBx
This is the working one (using v.10.16.7): https://codepen.io/Viper16/pen/ExWZGdK

---

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by limonte** [comment]
Thanks for reporting @Valentina16!

**Comment by Valentina16** [comment]
Thank you for the super speedy fix!! I'll download the new version asap!
