### ISSUE TITLE
backdrop: true destroy overflow-y of another div

### ISSUE THREAD

**Issue by xreider** [sweetalert2/sweetalert2#2262]
## Current behavior

backdrop: true destroy overflow-y of another div, and recover it after closing a modal.
But the result is that scrolledTo 0 of this div, but I needn-t to scroll to the top

## Expected behavior

I set backdrop: false, change css to 
```
html body.swal2-no-backdrop .swal2-container {
  pointer-events: all !important;
  background: rgba(0, 0, 0, 0.4) !important;
}
```
And it works as expected, but every time get `SweetAlert2: "allowOutsideClick" parameter requires `backdrop` parameter to be set to `true`` on console.log
**How to disable it?**

## Config -->

export default function (target) {
  let { modalConfig } = target.dataset;
  modalConfig = JSON.parse(modalConfig);
  const { sharable, api } = modalConfig;

  if (api) {
    Swal.fire({
      focusConfirm: false,
      html: '<div class="lds-ripple"><div></div><div></div></div>',
      confirmButtonText: t('Close'),
      backdrop: false,
      ...sharable,
      willOpen: () => {
        axios
          .get(api)
          .then(({ data }, ...rest) => {
            console.log(rest);
            Swal.update({ ...data });
          })
          .catch(error => {
            makeToast('error', 'makeModal API no request' + error.toString());
            console.log(error);
          });
      },
    });
  }
}

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
