### ISSUE TITLE
sweetalert version 11.0.12 error: Invalid CSS after "  @return math": expected expression (e.g. 1px, bold), was ".div($number, ($num"

### ISSUE THREAD

**Issue by lvnilesh** [sweetalert2/sweetalert2#2263]
## Current behavior

```
./node_modules/sweetalert2/src/sweetalert2.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./node_modules/sweetalert2/src/sweetalert2.scss)

SassError: Invalid CSS after "  @return math": expected expression (e.g. 1px, bold), was ".div($number, ($num"
        on line 515 of node_modules/sweetalert2/src/scss/_core.scss
        from line 8 of node_modules/sweetalert2/src/scss/_theming.scss
        from line 4 of node_modules/sweetalert2/src/sweetalert2.scss
>>   @return math.div($number, ($number * 0 + 1));

   --------------^
```

**Comment by limonte** [comment]
Use the latest version of `sass`, at least `1.33.0`.

**Comment by renemagiclog** [comment]
I had the same problem a few hours ago but I could already solve the detail is in:
node_modules/sweetalert2/src/scss/_core.scss

these lines have to be replaced 👍:
@function strip-units($number) {
  @return math.div($number, ($number * 0 + 1));
}
$icon-zoom: math.div(strip-units($swal2-icon-size), 5);

for:  

@function strip-units($number) {
  @return $number / ($number * 0 + 1);
}
$icon-zoom: strip-units($swal2-icon-size) / 5;

that helped me, greetings

**Comment by darrensw777** [comment]
This is SweetAlert2 dependencies and still has the error:

"devDependencies": {
    "@babel/core": "^7.14.3",
    "@babel/preset-env": "^7.14.2",
    "@rollup/plugin-json": "^4.0.2",
    "@sweetalert2/eslint-config": "^1.0.0",
    "@sweetalert2/execute": "^1.0.0",
    "@sweetalert2/stylelint-config": "^1.1.31",
    "browser-sync": "^2.26.14",
    "cypress": "^7.3.0",
    "eslint": "^7.28.0",
    "eslint-plugin-cypress": "^2.11.3",
    "eslint-plugin-no-unsanitized": "^3.1.5",
    "gulp": "^4.0.0",
    "gulp-autoprefixer": "^8.0.0",
    "gulp-clean-css": "^4.0.0",
    "gulp-concat": "^2.6.1",
    "gulp-css2js": "^1.1.2",
    "gulp-if": "^3.0.0",
    "gulp-rename": "^2.0.0",
    "gulp-rollup": "^2.16.2",
    "gulp-uglify": "^3.0.0",
    "jquery": "^3.6.0",
    "merge2": "^1.2.3",
    "replace-in-file": "^6.0.0",
    "rollup": "^2.50.6",
    "rollup-plugin-babel": "^4.3.2",
    "sass": "^1.34.1", <---------------- HERE
    "sinon": "^11.0.0",
    "stylelint": "^13.13.1",
    "typescript": "^4.2.3"
  },

**Comment by limonte** [comment]
Guys, instead of commenting with such comments, please put some effort in reporting a proper issue with the simple repo where the issue can be seen. Thanks.
