### ISSUE TITLE
Teaxtarea not scrollable on iOS

### ISSUE THREAD

**Issue by Apporix** [sweetalert2/sweetalert2#2266]
## Current behavior

On iOS, the textareas are not scrollable. This problem does not occur on Android or on Desktop.

This happens for the inbuild textarea as well as textareas added in HTML.

My guess is, that in `shouldPreventTouchMove()` of `iosFix.js` we check for `target.tagName !== 'INPUT'` but not for `target.tagName !== 'TEXTAREA'`.

## Expected behavior

The textarea should also scroll on iOS (when there is an overflow).

## Live demo 

The textarea example on the documentation page is a working example for the iOS bug: https://sweetalert2.github.io/#input-types

**Comment by limonte** [comment]
Thanks for reporting @Apporix!
