### ISSUE TITLE
using icons causes the width to be too wide

### ISSUE THREAD

**Issue by davidburson** [sweetalert2/sweetalert2#2272]
As explained in this SO question.  It works fine in version 10.16.9, but fails in version 11.0.16.

https://stackoverflow.com/questions/67843750/sweetalert2-content-is-wider-than-the-alert-by-the-width-of-the-icon

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
