### ISSUE TITLE
Removing .swal2-content broke aria-describedby

### ISSUE THREAD

**Issue by jcputney** [sweetalert2/sweetalert2#2273]
## Current behavior

`.swal2-content` was migrated to `.swal2-html-container`, which is now only used as a `class` instead of an `id`, breaking the `aria-describedby` attribute because it expects to find an element with the given `id`.

## Expected behavior

The alert should pass accessibility testing.

## Live demo 

https://codepen.io/jcputney/pen/NWpOdam

You'll need to allow pop-ups from CodePen. The `Invalid References` section at the bottom of the report shows the issue.

---

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by limonte** [comment]
Thanks for reporting @jcputney!
