### ISSUE TITLE
Sweet alert prevents clicking on parts of the screen

### ISSUE THREAD

**Issue by crazynds** [sweetalert2/sweetalert2#2277]
I've recently implemented sweet alert and I'm having a problem with it that when you fire it, it takes over the location of the quick action buttons and prevents you from triggering them during the alert.

![image](https://user-images.githubusercontent.com/36674096/122661122-83e63d00-d15d-11eb-9746-e377df86a798.png)

I thought about overwriting the css to get the heigth:100% from the sweetalert container but I don't think it's the best way to fix it.

I tried to use custom class parameter to get custom container but it didn't work because it doesn't overwrite the old class.
The only way i can do to work is to set in sass max-height: 100px !important to the class

**Comment by limonte** [comment]
thanks for reporting @crazynds!
