### ISSUE TITLE
v8 documentation disappeared.

### ISSUE THREAD

**Issue by pjebs** [sweetalert2/sweetalert2#2281]
I use the https://github.com/rocketlaunchr/electron-alert library.

It uses v8.19 API of swal2. The documentation for that has disappeared. How can I access it?

**Comment by limonte** [comment]
Unfortunately, there's no way to access v8 docs anymore. Please consider upgrading:

- v8 -> v9: https://github.com/sweetalert2/sweetalert2/releases/tag/v9.0.0
- v9 -> v10: https://github.com/sweetalert2/sweetalert2/releases/tag/v10.0.0
- v10 -> v11: https://github.com/sweetalert2/sweetalert2/releases/tag/v11.0.0
