### ISSUE TITLE
Popup not showing up properly after adding "forEach" function to Object prototype

### ISSUE THREAD

**Issue by mnadeaufbo** [sweetalert2/sweetalert2#2283]
## Current behavior

The popup just show up on the left of the page without any animations

## Expected behavior

The popup show up on the center with animations

## Live demo 

https://codepen.io/mnadeaufbo/pen/qBmByNb

**Comment by limonte** [comment]
Here's why you shouldn't extend the native object: https://stackoverflow.com/a/14034242

Here's what to do instead: https://stackoverflow.com/a/25896949
