### ISSUE TITLE
Sweetalert2 unexpected dark background in alert title

### ISSUE THREAD

**Issue by donmerlin** [sweetalert2/sweetalert2#2288]
## Current behavior
SweetAlert2 title is showing up with a dark background (dark on dark difficult to read).

I am using the default everything for sweetalert2, and in a static HTML document, the popups work exactly as expected. When I incorporate sweetalert2 into our CGI's, for some (currently unknown) reason, the title is showing up with a dark background. The text is also dark, so dark on dark is very difficult to read. I tried using themes to get rid of this issue, but that didn't help. It appears to be tied to my website's CSS definition for H2.  For some reason, it inherits H2's background, but not H2's text color (see live demo below).  If it inherited both, I can live with it, but since it only inherits the background, the popup titles are unreadable.

## Expected behavior
The title text in sweetalert2 popups should have the same background as the rest of the popup.

The title text in sweetalert2 popups should have the same background as the rest of the popup, or at least inherit both text color and background color from H2 element.

## Live demo 

https://codepen.io/donmerlin/pen/KKmgKWp

---

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by limonte** [comment]
```diff
h2 {
-  color: #FFFFFF;
+  color: #FFFFFF !important;
  background: #63727c;
}
``

**Comment by donmerlin** [comment]
What if I don't want the popup's to inherit my H2 element at all?   This seems more like a work around (and a painful one since our H2 element is defined differently in different themes).

**Comment by zenflow** [comment]
> What if I don't want the popup's to inherit my H2 element at all?

@donmerlin I think the only way for that is to make your selector more specific, since you don't want it to apply to **all** `h2` elements on the page (including sweetalert2 markup), only some of them.

For example

```diff
- h2 {
+ main h2 { 
    color: #FFFFFF;
    background: #63727c;
    font-size: 7em;
  }
```
... and wrap your html content in a `<main>` element

**Comment by zenflow** [comment]
@donmerlin Or use this as a css selector: `h2:not(.swal2-title)` (no changes to html needed) but the other suggestion is much cleaner since it's not coupled to sweetalert2

**Comment by donmerlin** [comment]
Most preferable would be that the H2 element was not tied to a sweetAlert popup; however, if that is cemented in, I would prefer to update the sweetAlert2 CSS file rather than update all of our theme files. What would be the suggested update to the sweetAlert .swal2-title element?  I used background: white, but is there a more generic way of doing it such that it would work in any of the themed CSS sweetalert2 files?

**Comment by donmerlin** [comment]
The other thing I would like to do is one (or both of the following):
1) when toast=true, how do i set the alert so that the rest of the page is disabled? (currently, I can click in other fields on the page)
2) how can I change the shape of the standard sweetalert popup so be more like the toast version?
