### ISSUE TITLE
Fire SweetAlert without any parameters

### ISSUE THREAD

**Issue by sandmann91** [sweetalert2/sweetalert2#2298]
With Mixins you can generate multiple SweetAlert configurations and thats awesome. You can also difine anything like title and text in this mixin. However you cannot run SweetAlert without any Arguments.

### Example 

```javascript

// Predefined
var app = {
    error: Swal.mixin({
        icon: 'error',
        title: 'Error!',
        text: 'Please Contact the Administrator'
    }),

    save: Swal.mixin({
        icon: 'question',
        title: 'Would you like to Save!',
        text: 'Click on save to save the document or click close to abort this',
        confirmButtonText: 'Confirm',
        cancelButtonText: 'Discard',
        showCancelButton: true
    })
}


// Call later
app.error.fire();
app.save.fire().then(...);
```

What you can to is 
```javascript
app.error.fire(false);
```
This will work but leaves you with in error in your console:
```
SweetAlert2: Unexpected type of title! Expected "string" or "Element", got boolean
```

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
