### ISSUE TITLE
Feature request: being able to update "pre" callbacks

### ISSUE THREAD

**Issue by tarockx** [sweetalert2/sweetalert2#2299]
## New feature description/motivation

It would be nice to be able to update the `preConfirm` and `preDeny` callback functions when calling `swal.update({...});`.
This would be useful because when initially setting the callback function, variables are captured in the lambda and there is no way (that I know of) to update them. 
Consider this simple function that updates a currently open swal dialog:
```
function updateSwal(newText, denyCallback){
	swal.update({
		text: newText,
		preDeny: () => {
			denyCallback();
                        return false;
		}
	});
}
```

This function doesn't work properly, because the "preDeny" parameter is never updated, so when the user clicks the deny button the callback is not invoked. 

This means that the only way to add or change a preConfirm or preDeny function is to close the currently open dialog and re-open it. This is inconvenient because it requires closing and re-opening the dialog.

## New feature implementation

`preConfirm` and `preDeny` parameters should be added to the list of accepted parameters in `swal.update({...});`.
Or, can someone suggest a workaround, if one exists?

Anyway, thanks for this amazing library, and for reading this, regardless of whether it will be implemented or not.

**Comment by limonte** [comment]
Done, thanks for the request @tarockx!

**Comment by tarockx** [comment]
Wow, that was fast, thank you very much for fulfilling my request!
