### ISSUE TITLE
Custom classes are ignored in some cases

### ISSUE THREAD

**Issue by plof27** [sweetalert2/sweetalert2#2308]
## Current behavior

I tried to add `customClass: { container: 'top-64' }` to one of my toast swals, but it didn't apply because the custom class is inserted later (at a lower priority) than the built in classes. Because of this, I can't customize the positioning without using `!important`, which is messy.

## Expected behavior

The custom class is given priority and applied appropriately. 

## Live demo 
https://codepen.io/plof27/pen/bGWmGEV

---

By the way, while I understand the need to provide an example, I think that requirement might end up deterring would-be bug reporters.

**Comment by limonte** [comment]
you need two fixes:

1. Apply the custom class to popup instead of container:
```diff
- customClass: { container: 'top-64' }
+ customClass: { popup: 'top-64' }
```

2. Set the `position` param to `top`
```js
Swal.fire({
  ...
  position: 'top'
})
```

**Comment by plof27** [comment]
I see. Thanks! Could a note about this be added to the documentation somewhere? I don't think I would've thought to try that without help.

**Comment by plof27** [comment]
A note to future devs: The above solution doesn't quite work. I had to also add `height: 100%;` (or similar) to the container, so the swal doesn't get hidden under a scroll bar.
