### ISSUE TITLE
It would be great if could enable/disable allowEnterKey based on other config options

### ISSUE THREAD

**Issue by Mintonne** [sweetalert2/sweetalert2#2311]
## New feature motivation

I am currently using a global mixin with a few defaults for my popups. Whenever I am displaying a popup with a cancel button, I would like to disable `allowEnterKey` in the `willOpen` hook, for example.

At the moment, only a few configuration options are accessible via methods.

## New feature description

Add  `Swal.isCancelEnabled()`, `Swal.allowEnterKey()` and `Swal.disableEnterKey()`

Alternatively, `Swal.update` should allow you to enable/disable `allowEnterKey` and other options that are currently not supported.

## New feature implementation

---

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by limonte** [comment]
Unfortunately, it's not possible to implement. `allowEnterKey` is kinda a legacy param for backward compatibility with old versions, it will not be updatable.

For your case this can be used:

```js
Swal.fire({
  ...
  didOpen: () => {
    document.activeElement.blur()
  }
})
```
