### ISSUE TITLE
Wrong property description

### ISSUE THREAD

**Issue by Msender** [sweetalert2/sweetalert2#2312]
## Current behavior

The description for the 'text' property is: If `text` and `html` parameters are provided in the same time, `text` will be used.

## Expected behavior

But, it's the opposite, the `html` will be used.

## Live demo 

[https://codepen.io/msender/pen/xxdvEjO](https://codepen.io/msender/pen/xxdvEjO)

**Comment by limonte** [comment]
Thank you @Msender 

Docs are fixed now: https://sweetalert2.github.io/#html

**Comment by Msender** [comment]
> Thank you @Msender
> 
> Docs are fixed now: https://sweetalert2.github.io/#html

Thanks @limonte
We also need to update sweetalert2.d.ts line 434.

**Comment by limonte** [comment]
> > Thank you @Msender
> > Docs are fixed now: https://sweetalert2.github.io/#html
> 
> Thanks @limonte
> We also need to update sweetalert2.d.ts line 434.

Already updated :)
