### ISSUE TITLE
Why the confirm button always has an outline style property? 

### ISSUE THREAD

**Issue by suruirui** [sweetalert2/sweetalert2#2318]
As title ,  it's almost unnecessary and redundant. Using customer class even cannot remove it.
What should I do? 
![image](https://user-images.githubusercontent.com/5047326/133021234-d433648e-2c01-4a43-953d-1f7004ee8b97.png)

**Comment by limonte** [comment]
I have no idea where did you take that screenshot from.

Here's how the online actually looks like:

<img width="226" alt="CleanShot 2021-09-13 at 13 38 05@2x" src="https://user-images.githubusercontent.com/6059356/133069726-7702d0f0-f948-43c3-9404-568c32bc64b6.png">

**Comment by suruirui** [comment]
> I have no idea where did you take that screenshot from.
> 
> Here's how the online actually looks like:
> 
> <img alt="CleanShot 2021-09-13 at 13 38 05@2x" width="226" src="https://user-images.githubusercontent.com/6059356/133069726-7702d0f0-f948-43c3-9404-568c32bc64b6.png">

I just outlined the border by my capture tool, like the left "OK" button in your image, why it always has an highlight border??Sometimes it can misleading the user.

**Comment by limonte** [comment]
[There's a reason for that ugly outline](https://stackoverflow.com/a/25298082/1331425)
