### ISSUE TITLE
Animation Delay

### ISSUE THREAD

**Issue by zachduda** [sweetalert2/sweetalert2#2320]
## Current behavior
When calling the event (Swal.fire), the prompt appears instantly for a few frames before eventually re-rendering itself with the animation. 

## Expected behavior
For the prompt to not appear until the animation is ready. This will avoid a jagged flicker.

Using:
`Swal.fire('Whoops', 'This might flicker!', 'error');`

## Live Example
https://user-images.githubusercontent.com/10857265/133658756-9b36cc60-6282-44c3-9aff-59f2f10b8544.MOV

## Notes
Unsure if other prompts apply (warning/success/info) but the error prompt most certainly does have this unwanted flicker. The browser in the example was on the DuckDuckGo browser for iPhone however the issue can be replicated on Safari.

**Comment by limonte** [comment]
The recorded video is NOT the same as the live demo. Live demo is the code, please follow the issue template.
