### ISSUE TITLE
Html removes id from input inside element

### ISSUE THREAD

**Issue by Wimmie** [sweetalert2/sweetalert2#2323]
| name                                     | about                                                                            | labels          |
|------------------------------------------|----------------------------------------------------------------------------------|-----------------|
| Html removes id from input inside element | Html removes id from input field, when the input field is inside another element | bug |

## Current behavior

The ID attribute will be removed from the input field, when the HTML below is passed to the HTML parameter.
```
<label for="swal-input1" class="swal2-checkbox" style="display: flex;">
      <input id="swal-input1" type="checkbox" />
      <span class="swal2-label">Checkbox</span>
</label>
```

## Expected behavior

The value of the input field should be able to be retrieved with the ID attribute, this is why the ID attribute should not be removed when this HTML is passed.

## Live demo

https://codepen.io/wimmie/pen/JjJvEyM

**Comment by limonte** [comment]
That is because you are using the internal `class="swal2-checkbox"` for your custom label, remove it and you'll be fine.
