### ISSUE TITLE
Examples mentioned for "inputValidator" option is incorrect or not working in Angular

### ISSUE THREAD

**Issue by Suresh-Kumar-A** [sweetalert2/sweetalert2#2324]
## Current behavior

If a user tries to add **inputValidator** with example provided in your code docs, It's throwing an error saying **Type 'false | "You need to select something!"' is not assignable to type 'SyncOrAsync<string | null>'.**
## Expected behavior
If a user tries to add **inputValidator** with example provided in your code docs it should work fine

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
