### ISSUE TITLE
When popup fade-out animation is active cannot read the values of custom embedded html

### ISSUE THREAD

**Issue by slear** [sweetalert2/sweetalert2#2330]
I have used sweetalert2 to gather some input from my users. I expect in the promise code to be able to read the value from two inputs embedded in custom html markup, but they comes out as undefined

            var wrapper = 
                '<div class="form-group row col-md-11">' +
                '<div class="col-md-4 text-start">' +
                '<label>Measure unit</label>' +
                '<select class="form-control" id="um" aria-expanded="false">' +
                '<option value="GR">Gramms</option>' +
                '<option value="LT">Liters</option>' +
                '<option value="NR">Pieces</option>' +
                '</select>' +
                '</div>' +
                '<div class="col-md-7 text-start">' +
                '<label>Quantity</label>' +
                '<input class="form-control" id="qty"/>' +
                '</div>' +
                '</div>';
            Swal.fire({
                title: 'Quantity',
                html: wrapper,
                allowOutsideClick: false,
                background: "palegreen",
                showCancelButton: true,
                confirmButtonText: "Confirm",
                cancelButtonText: "Exit",
                showCloseButton: true,
                confirmButtonColor: "#10633A",
                showClass: {
                    backdrop: 'swal2-noanimation', // disable backdrop animation
                    popup: '',                     // disable popup animation
                    icon: ''                       // disable icon animation
                },
                hideClass: {
                    popup: '',                     // disable popup fade-out animation
                },
            }).then((result) => {
                if (result.value === true) {
                    var um = $('#um').val();
                    var qt = $('#qty').val();
                    UM.text(um);  // some labels
                    QTY.text(qty);
                }
            });

If I comment out the lines about the fade-out animation then um and qt are set correctly, leaving the code as is the two variables are _undefined_

I am having difficulties to prepare a codepen example. I have one ready here https://jsfiddle.net/slear/hfn1sd45/16/

**Comment by limonte** [comment]
You need to use the `preConfirm` parameter, here's the example: https://sweetalert2.github.io/#multiple-inputs
