### ISSUE TITLE
Issue on calling swal from emit function on vue 3

### ISSUE THREAD

**Issue by salacsoft** [sweetalert2/sweetalert2#2332]
## Current behavior
I am using vue 3 with composition API
I have a component that emit action to parent component, upon calling the the sweet alert on the parent function it throws error 

## Expected behavior
Sweet alert should appear

## Live demo 

---

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
