### ISSUE TITLE
preConfirm & preDeny promise rejections could reject the main Swal.fire promise

### ISSUE THREAD

**Issue by jf-m** [sweetalert2/sweetalert2#2333]
## New feature motivation

I find the `preConfirm` and the new `preDeny` really handy, and sometimes when I use them, I use an arrow function like so :

```
Swal.fire({
  title: 'Sure ?',
  confirmButtonText: 'Yes !',
  showLoaderOnConfirm: true,
  preConfirm: () =>  fetch('//api.foo.com/bar')
})
```

This way I find it nice and clean, but when I need to handle an exception that my fetch might throw back, it gets trickier.

Here is how it's currently supposed to be done :

```
Swal.fire({
  title: 'Sure ?',
  confirmButtonText: 'Yes !',
  showLoaderOnConfirm: true,
  preConfirm: () =>  fetch('//api.foo.com/bar').catch(({status}) => {
         if (status == 404) {
            // Do Some Stuff.. Note that you'd have to close the swal manually, using Swal.close()
         }
      }))
}).catch(() => {
   // Not used, this piece of code is never triggered right now, the "main" promise is never rejected
}))
```

The thing is, the rejection of the `preConfirm` promise is not causing a rejection of the main `Swal.fire` returned promise. 

This means that if you happen to have a rejection in your `preConfirm` that you didnt `catch` inside the `preConfirm`, then the rejection error is lost and the `Swal` is just loading forever.

Example, this does not work right now, swal is not closed, and the loading animation is displayed forever:
```
Swal.fire({
  title: 'Sure ?',
  confirmButtonText: 'Yes !',
  showLoaderOnConfirm: true,
  preConfirm: () =>  fetch('//api.foo.com/bar')
}).catch(({status}) => {
         if (status == 404) {
            //Woops, wrong place ! This will never be triggered
         }
      }))
```

This is not a bug, it's intended that way, you just have to deal with the rejection inside the `preConfirm` yourself, which is fine.
I would just find it more clean and more nice to handle the rejection in the "main" promise returned by `Swal.fire`. 

It might be subject to discussion because I understand that it could be a subjective idea that wouldn't suit everyone... What do you think ?

## New feature description

I propose that any rejection of the promise sent in the `preDeny`/`preConfirm` are thrown back at the main promise that `Swal.fire` returns, causing it to be rejected as well with the original Error object as the parameter.

In this way, one could have a choice between handling the rejections within the `preConfirm`/`preDeny` like before (not a breaking change) OR handling it like so :

```
Swal.fire({
  title: 'Sure ?',
  confirmButtonText: 'Yes !',
  showLoaderOnConfirm: true,
  preConfirm: () =>  fetch('//api.foo.com/bar')
}).catch(({status}) => {
   if (status == 404) {
      // Do Some Stuff
   }
}))
```

If you use both deny and confirm, here is what it would look like : 

```
Swal.fire({
  title: 'Sure ?',
  confirmButtonText: 'Yes !',
  showLoaderOnDeny: true,
  preDeny: () =>  fetch('//api.foo.com/no').catch(() => console.error("Deny Specific Error")),
  preConfirm: () =>  fetch('//api.foo.com/yes').catch(() => console.error("Confirm Specific Error"))
}).catch((error) => {
  // Handle a "general" error of either deny or confirm
  console.error("Either a Confirm or a Deny Error Happened, let's close the swal."))
  Swal.close();
}))
```

## New feature implementation

The implementation is kind of easy I guess, thanks to your already existing `WeakMap` system `swalPromiseResolve`. I would just add another weakmap called `swalPromiseReject` and deal with it the same way as the `swalPromiseResolve`.
I could propose a pull request if you like this idea.

For this RFC not to be a breaking change, the reject of the main promise should NOT close the Swal instance.
To my opinion, whether to close swal or not should be the developer's decision within the implementation of the catch, so it would be fine.

For the people out there who uses `await`, this might be breaking though... Hence why maybe this functionality should be either implemented as a new parameter like `preConfirmRejectsPromise: true, preDenyRejectsPromise: true` or it must be flagged as a breaking change feature, I guess.

Thank you for this amazingly sweet repo !

**Comment by avimar** [comment]
@jf-m thanks!! I ran into this same issue - I was able to make it work but it resulted in a very non-standard javascript control flow.

I upgraded to v11 with your PR and it works great!
