### ISSUE TITLE
Show loading animation while you wait to image loaded

### ISSUE THREAD

**Issue by carloscr99** [sweetalert2/sweetalert2#2338]
i'm so pleased for using that amazing option since I discovered last year!
I'm just writing this issue to suggest, or ask if that option is already aviable, and my suggestion/question is:

Can I show a loading animation while I'm waiting to the image load at the current Swal?

Now I'm using the Swal in this way:

        Swal.fire({
			  title: descr,
			  imageUrl: url,
			  confirmButtonText: "Cerrar",
			})

Thanks for your amazing job!

**Comment by limonte** [comment]
A loader for images is not worth implementing. The better UX would be to preload the image before showing it.
