### ISSUE TITLE
Backdrop blink when queuing alerts

### ISSUE THREAD

**Issue by gestudio** [sweetalert2/sweetalert2#2339]
## Current behavior

When you queue SweetAlert, the backdrop blinks when switching to the next or previous instances.
Open the example, fill in the form and click next. When switching to step 2, the backdrop dissapears and appears again with the new instance on SweetAlert, creating a BLINK.

## Expected behavior

When queueing instances, SweetAlert should not destroy the backdrop, just the modal box.

## Live demo 

https://sweetalert2.github.io/recipe-gallery/queue-with-back-button.html

**Comment by limonte** [comment]
Good question @gestudio!

The blinking of backdrop can be disabled with this trick:

```js
const Queue = Swal.mixin({
  // Classes to avoid backdrop blinking between steps
  showClass: {
    backdrop: 'swal2-noanimation',
  },
  hideClass: {
    backdrop: 'swal2-noanimation',
  }
})
await Queue.fire({
  title: '1',
  // Class to show fade-in backdrop animation which was disabled in Queue mixin
  showClass: {
    backdrop: 'swal2-backdrop-show',
  },
});
await Queue.fire('2');
await Queue.fire({
  title: '3',
  // Class to show fade-out backdrop animation which was disabled in Queue mixin
  hideClass: {
    backdrop: 'swal2-backdrop-hide',
  },
});
```

I also added this trick to this recipe: https://sweetalert2.github.io/recipe-gallery/queue-with-progress-steps.html
