### ISSUE TITLE
Chaining modals with different inputs

### ISSUE THREAD

**Issue by soportehrm** [sweetalert2/sweetalert2#2347]
Hello everybody. 
I'm using and adapting the "Queue with a "Back" Button" example from the recipe gallery to have different modals with different inputs (Text, File, Select, number and email), the thing is that i'm having issues getting the values from the select and input files and i'm using ifs and else if (which i shouldn't since is bad practice). 
Does anyone recommend me which is the best approach to do this?

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
