### ISSUE TITLE
Close the toast by clicking outside of it & customize the size of the sweet alert 2 popups.

### ISSUE THREAD

**Issue by bbehera277** [sweetalert2/sweetalert2#2348]
Can someone please help me with below concerns :
1. How to close the toast of sweetalert 2 by clicking outside ?
2. Also how to customize the size of the alert popups & toast popups(As the size is too big and doesn't look good for all screen sizes) ?

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask

**Comment by maxkopych** [comment]
@bbehera277 did you find solution for #1?

**Comment by bbehera277** [comment]
> @bbehera277 did you find solution for #1?

No.
