### ISSUE TITLE
Old Browser Support

### ISSUE THREAD

**Issue by synologic** [sweetalert2/sweetalert2#2350]
Who doesn't love Sweetalert 2 v11.1.10

Everybody, except older browsers.
Chrome 38 for example, which Webos 3.0 runs, throws "Uncaught SyntaxError: Use of const in strict mode." and not only.

I understand the need to use modern syntax, but think about the Elders of the Internet ...

Would it be possible to do something about it ?

**Comment by limonte** [comment]
Hi @synologic 

The support for old browsers was discontinued in v11.0.0. If you need old browsers support please use v10:

```json
"sweetalert2": "^10.0.0"
```
