### ISSUE TITLE
The latest chromium-based browser updates, has caused emojis to turn "outline" in sweetalert2!

### ISSUE THREAD

**Issue by heltonricardo** [sweetalert2/sweetalert2#2352]

**Comment by limonte** [comment]
Hey, @heltonricardo could you provide more details, e.g. screenshots?

**Comment by heltonricardo** [comment]
Yes! Here:
![image](https://user-images.githubusercontent.com/50843386/142951054-b887da3f-11a2-4635-87a2-0ccf7dc731c5.png)

**Comment by limonte** [comment]
> Yes! Here: ![image](https://user-images.githubusercontent.com/50843386/142951054-b887da3f-11a2-4635-87a2-0ccf7dc731c5.png)

Thanks! What's the browser and its version?

**Comment by heltonricardo** [comment]
Microsoft Edge Version 96.0.1054.29 (Official build) (64-bit)
Google Chrome Version 96.0.4664.45 (Official build) 64 bits

**Comment by limonte** [comment]
Can't reproduce, most probably something has happened to system fonts on your machine. In the future please follow the issue template when reporting issues, thanks!
