### ISSUE TITLE
Sweetalert2 issue after visiting page with hotwired/turbo

### ISSUE THREAD

**Issue by dyanakiev** [sweetalert2/sweetalert2#2356]
When i visit page with `Turbo.visit('url...')` while Sweetalert is opened and then when i try to open Sweetalert again i get the following error:

```js
  Uncaught TypeError: Cannot read properties of undefined (reading 'removeEventListener')

  Function where the error is:
  function removePopupAndResetState(instance, container, returnFocus, didClose) {
    if (isToast()) {
      triggerDidCloseAndDispose(instance, didClose);
    } else {
      restoreActiveElement(returnFocus).then(() => triggerDidCloseAndDispose(instance, didClose));
      globalState.keydownTarget.removeEventListener('keydown', globalState.keydownHandler, {
        capture: globalState.keydownListenerCapture
      });
      globalState.keydownHandlerAdded = false;
    }
```

**Comment by limonte** [comment]
Thanks for reporting @dyanakiev!

Could you please provide the live demo demonstrating the issue?

**Comment by dyanakiev** [comment]
@limonte i think its something really specific that is happening i tried to replicate the issue in codepen but im failing.

**Comment by limonte** [comment]
Sorry @dyanakiev I can't help without the live demo.

**Comment by limonte** [comment]
@dyanakiev please test out the new release and let me know if the issue is fixed, thank you!

**Comment by dyanakiev** [comment]
Hello @limonte i forgot to monitor the issue, i will test later, thanks :)
