### ISSUE TITLE
Web page structure destroyed 

### ISSUE THREAD

**Issue by dicaccamovincenzo92** [sweetalert2/sweetalert2#2358]
Hello everybody,
on opening a swal, the structure of my web page is altered.
For example, when i press the red button in the first image, my page is altered like in the second image.
![image](https://user-images.githubusercontent.com/82500275/144239584-7b6877bf-8fe1-423d-917e-22aed6499df4.png)
![image](https://user-images.githubusercontent.com/82500275/144239870-cb105837-af28-45d8-91eb-6d249b5af4e5.png)

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
