### ISSUE TITLE
Nuxt Error Uncaught TypeError: Cannot read properties of undefined (reading 'removeEventListener')

### ISSUE THREAD

**Issue by akbarali1** [sweetalert2/sweetalert2#2359]
I am doing a project in Nuxt. I connected via VueJS Mixin. My code.

nuxt.config.js
```
 plugins: [
    '~/plugins/toast.js',
    '~/plugins/vue-dialog-loading.js',
    "~/plugins/axios.js",
  ],

``````
```

import Vue from 'vue'
import Swal from 'sweetalert2'

Vue.mixin({
  methods: {
    SwalMixin(message, status = 'success') {
      const Toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 4000,
        timerProgressBar: true,
        didOpen: (toast) => {
          toast.addEventListener('mouseenter', Swal.stopTimer)
          toast.addEventListener('mouseleave', Swal.resumeTimer)
        }
      })

      Toast.fire({
        icon: status,
        title: message
      })

    }
  }
})

```
Calling login.vue
`this.SwalMixin('Akkauntga muvaffaqiyatli kirdingiz!');`

`package.json`
`    "sweetalert2": "^11.2.1",
`

How can I fix the error?

Video: https://www.codegrepper.com/video_uploads/46693_vYEeDjMEERFGZ0vo9ycwB3JXeyKSpKws3FkbnsPCaTDcn9RyKBFMwJp.mp4

**Comment by limonte** [comment]
@akbarali1 please test out the new release and let me know if the issue is fixed, thank you!

**Comment by akbarali1** [comment]
> @akbarali1 please test out the new release and let me know if the issue is fixed, thank you!

There is no error. But it is located behind my right menu

https://www.codegrepper.com/video_uploads/46693_LnVc7Y6InVNlCpV7WOQQEf90chfqp8ubQAwhGk2JlPpufL2xAcGaqau.webm

**Comment by akbarali1** [comment]
The problem has been solved, thank you

**Comment by limonte** [comment]
That's another issue which I can't help without a proper issue report, there's probably something related to your app that breaks it.

**Comment by Hernancano98** [comment]
The same is happening in vue-sweetalert2 and is enetring in an infinite loop.
