### ISSUE TITLE
Install sweetalert2 (Vu3 + nuxt 3 + vite)

### ISSUE THREAD

**Issue by jihadadulrazaqjasim** [sweetalert2/sweetalert2#2364]
## Current behavior

Importing like below not working:
`import Swal from 'sweetalert2'`

and while importing js and css separately as mentioned in documentation, only the javascript worked:

```
import Swal from 'sweetalert2/dist/sweetalert2.js'
import 'sweetalert2/src/sweetalert2.scss'
```

## Expected behavior

While importing the files separately I solved the issue by changing the import for css as below:

`import 'sweetalert2/dist/sweetalert2.css'
`

**Comment by PMLS3** [comment]
> ## Current behavior
> Importing like below not working: `import Swal from 'sweetalert2'`
> 
> and while importing js and css separately as mentioned in documentation, only the javascript worked:
> 
> ```
> import Swal from 'sweetalert2/dist/sweetalert2.js'
> import 'sweetalert2/src/sweetalert2.scss'
> ```
> 
> ## Expected behavior
> While importing the files separately I solved the issue by changing the import for css as below:
> 
> `import 'sweetalert2/dist/sweetalert2.css' `

Hi, did you manage to get this working in Nuxt 3?
