### ISSUE TITLE
sweetalert2 toasts width auto according to text message

### ISSUE THREAD

**Issue by nitz333** [sweetalert2/sweetalert2#2366]
I´m using toasts from sweetalert2 library to show basic alert messages, but there are some messages more extend than others. As default behaviour the width is set to 360px, but I need a workaround to make it auto.

It’s possible to set the witdh of the alert container to auto, so the message fix in one line?

**Comment by limonte** [comment]
This is a bug indeed, sorry for missing this issue!

```js
Swal.fire({
  toast: true, 
  title: 'hi' , 
  showConfirmButton: false, 
  width: 'auto', 
  showCloseButton: true
})
```

<img width="551" alt="CleanShot 2022-10-26 at 11 55 57@2x" src="https://user-images.githubusercontent.com/6059356/197981880-e428dd6a-6cfa-4f7f-8a58-191cbde71ad7.png">

**Comment by limonte** [comment]
Sure, thank you!

**Comment by mani91g** [comment]
Created a PR to resolve this [2540](https://github.com/sweetalert2/sweetalert2/pull/2540)
