### ISSUE TITLE
\n(newline) in text property of Swal.fire not working its ignores newline

### ISSUE THREAD

**Issue by surendra-17** [sweetalert2/sweetalert2#2368]
## Current behavior

    Swal.fire({
        text: "Test\nHello World" ,
    })
Printing Test and Hello World on same line

## Expected behavior

Need to print Test and Hello World on different line if \n is provided

**Comment by Pokesi** [comment]
Use html: true, and use <br>

**Comment by limonte** [comment]
Replacing new-lines with `<br>` is the developer's responsibility because it maybe unexpected by some users.

```js
Swal.fire({
  html: "Test\nHello World".replace(/\n/g, '<br>'),
})

**Comment by surendra-17** [comment]
Thanks for help 👍

**Comment by surendra-17** [comment]
I want use this method with text attribute
