### ISSUE TITLE
Firing Prompt from Toast Present JS Error

### ISSUE THREAD

**Issue by zachduda** [sweetalert2/sweetalert2#2369]
## Current behavior
Visually all toasts appear fine, however a Javascript error is thrown after throwing a normal prompt from a confirm button within a toast.

## Expected behavior
Expected behavior is to have a confirm button that can open a normal prompt without error.

## Live demo 
[Live Codepen Example](https://codepen.io/zestytoaster/pen/MWEOGQZ)

**Comment by limonte** [comment]
The are no console errors in your codepen example.

**Comment by zachduda** [comment]
Im showing these errors on my console: 

Chrome: 96.0.4664.110 (Official Build) (64-bit) (cohort: Stable)
![JS_Error](https://user-images.githubusercontent.com/10857265/147525401-aee92e53-b2c9-4ec0-95f3-d35e4d484838.png)

**Comment by limonte** [comment]
This is weird, I can't get any errors in console. Could you try this one and let me know if any console errors appear https://codepen.io/limonte/pen/qBPpKNZ

**Comment by zachduda** [comment]
Sure thing. It shows this error instead:
![js_err](https://user-images.githubusercontent.com/10857265/147579762-e894f9c4-9cb3-4cec-9dc4-4680f98692ec.png)

**Comment by limonte** [comment]
Thank you @zachduda 

I am able to reproduce the error on Window, but on Mac there's no errors. Strange!
