### ISSUE TITLE
Giant icons

### ISSUE THREAD

**Issue by dujudini** [sweetalert2/sweetalert2#2371]
## Current behavior

All icons using font (warning, info, question), are showing 3x, 4x the size of "success" and "error" icons. 
This behavior can be seen in Chrome and Edge. Firefox is ok.

## Expected behavior

All icons should be the same size.

## Live demo
https://sweetalert2.github.io/#icons
![Capture](https://user-images.githubusercontent.com/58614190/147494908-cde40f8c-e646-470b-9029-f51936fea0a6.JPG)

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
