### ISSUE TITLE
Display multiple toasts?

### ISSUE THREAD

**Issue by vismutx** [sweetalert2/sweetalert2#2383]
Any possibility to display multiple toasts? I found on stackoverflow that some years ago it was not possible, but already 2022. 
Any solution?

**Comment by vismutx** [comment]
And another terrible case.
If I have a confirm modal with input, and system send notification, that should be shown with toast... Confirm modal will be closed? Strange UX..

**Comment by limonte** [comment]
Nothing has changed here, still only one popup at the time.

Duplicate of #770
