### ISSUE TITLE
Override default inline CSS?

### ISSUE THREAD

**Issue by borisdamevin** [sweetalert2/sweetalert2#2389]
Hi,

How we remove the default inline CSS for styles customization and use full custom HTML plz?

The custom Sass or themes don't work because of that.

Thanks.

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
