### ISSUE TITLE
Display dynamic table array content

### ISSUE THREAD

**Issue by anjumarypaul** [sweetalert2/sweetalert2#2390]
## Current behavior

currently showing table with  ",,,,". How to resolve this issue?

`<span>This assets has ${response.data.pendingFormsCount} pending copies of this form.</span>
            <table responsive border=1 class="w-100 scroll-table pendingform-details text-left">
              <thead>
                <tr>
                  <th class="width-50 p-2">Name</th>
                  <th class="width-20 p-2">Date</th>
                  <th class="width-5 text-center p-2">Action</th>
                </tr>
              </thead>
              <tbody>
                ${PENDINGFORMDETAILS.map(item =>
                  `<tr>
                    <td class="width-50 py-1 px-2">${item.user}</td>
                    <td class="width-20 py-1 px-2">${item.dateStarted}</td>
                    <td class="width-5 text-center py-1 px-2">
                      <button bssize="sm"
                        type="button"
                        onclick=${() => onResumeForm(item)}
                        class="m-2 btn btn-success">
                        Resume
                      </button>
                    </td>
                  </tr>`
                )}
              </tbody>
            </table>`

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
