### ISSUE TITLE
Select2

### ISSUE THREAD

**Issue by mi4ok** [sweetalert2/sweetalert2#2394]
Hi.
I use the select2 plugin in my script. If you perform an alert when loading a page, you get this situation
`Swal.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  type: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!'
}).then(function() {
  Swal.fire(
    'Deleted!',
    'Your file has been deleted.',
    'success'
  );`
![image](https://user-images.githubusercontent.com/6926906/150835454-9c99908b-6e99-4d56-bcbf-62ad0e441a04.png)

At the same time, if you use the button to display a notification, there is no such problem. How can this be solved?
< button id = " button " >SHOWMODAL< / button >
`<script>
    $('#button').click(() => {
Swal.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  type: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!'
}).then(function() {
  Swal.fire(
    'Deleted!',
    'Your file has been deleted.',
    'success'
  );
})
});
</script>`
![image](https://user-images.githubusercontent.com/6926906/150835952-a19b61a9-ac36-418b-8a5f-d601db9a41bf.png)

Thank you.

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
