### ISSUE TITLE
Sweet Alert includes all HTML inputs by default

### ISSUE THREAD

**Issue by nouphalpgs** [sweetalert2/sweetalert2#2395]
## Current behavior
We are using sweetalert only to show a ok cancel prompt. Since sweet alert injects all the HTML inputs by default and we are using chosen as global call, the selectbox becomes visible. 

## Expected behavior
If we are using only prompt, then there is no need for unwanted HTML inputs to be present in the popup.

![Swal](https://user-images.githubusercontent.com/94961359/150935640-788cf722-c7a8-4385-9ba7-9a7f249cd575.jpg)

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
