### ISSUE TITLE
ESM imports broken

### ISSUE THREAD

**Issue by aleho** [sweetalert2/sweetalert2#2396]
## Current behavior

```js
import Swal from 'sweetalert2';
```

Using ESM / Webpack building throws an error:
`export 'default' (imported as 'Swal') was not found in 'sweetalert2/dist/sweetalert2.js' (module has no exports)`

Using the source folder seems to work tough:
```js
import Swal from 'sweetalert2/src/sweetalert2';
```

I'm guessing the dist is broken?

## Live demo

Sorry, I've no idea how to demo modules importing in CodePen.

**Comment by PedroFumero** [comment]
I got the same issue, I've figured out a recent version was launched a few hours ago, so I assume it's a bug on the new version, just install a previous one, it will work just fine.

**Comment by limonte** [comment]
Oops, my bad, sorry guys 🤦  The fix is coming soon 🚀

**Comment by limonte** [comment]
Not my day today, sorry for the broken release and inconveniences that it caused. Should be fixed now.

**Comment by aleho** [comment]
No need to apologize! Thanks for your great work!

**Comment by PedroFumero** [comment]
> Not my day today, sorry for the broken release and inconveniences that it caused. Should be fixed now.

Thanks a lot @limonte, same as @aleho, thanks for your great work!
