### ISSUE TITLE
how to change   timerProgressBar color in Toast

### ISSUE THREAD

**Issue by myomyintaung1411** [sweetalert2/sweetalert2#2399]
#sweetalert2
here is my code

            Swal.fire({
                toast: true,
                position: "top",
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                icon: "error",
                grow: false,
                background: "#374151",
                color: "#fff",
                title: "sucess",
                animation:true
            })

**Comment by limonte** [comment]
Hello @myomyintaung1411 and thank you for the good question!

The new version with `customClass.timerProgressBar` was just released, so here's how you customize the color of timer progress bar:

```css
.my-progress-bar {
  background: red;
  height: 10px;
}
```

```js
Swal.fire({
  ...
  customClass: {
    timerProgressBar: 'my-progress-bar',
  }
})
```
