### ISSUE TITLE
Aria-hidden attribute is being removed incorrectly when using Swal.fire more than once

### ISSUE THREAD

**Issue by leftlion** [sweetalert2/sweetalert2#2404]
## Current behavior

I have a number of elements in my app that have aria-hidden already set to true. When I use Swal.fire more than once, the aria-hidden attribute is being removed completely from the elements in my app that have nothing to do with the popup.

Observations:
* Using Swal.fire once is ok.
* Putting a 1 second timeout between my Swal.fire calls works ok.

I know this issue has been raised a couple of times in the past. Most recently in https://github.com/sweetalert2/sweetalert2/issues/2303 which was marked as resolved in version 11.1.1, however, I have tried this version and the latest version (11.4.0) and I am still experiencing this problem.

## Expected behavior

The aria-hidden attributes should always be restored to their initial state for all elements when multiple Swal.fire calls are made.

## Live demo 
https://codepen.io/leftlion/pen/JjOyWYM

**Comment by limonte** [comment]
Thank you for the detailed issue report @leftlion!

I added the test which confirms the issue. I'll address the issue tomorrow 👍

**Comment by leftlion** [comment]
I've just re-tried my application using the new 11.4.1 release and the fix is working perfectly.

Thanks for the fast turnaround with this @limonte !
