### ISSUE TITLE
Can't focus to some input element after closing sweetAlert2

### ISSUE THREAD

**Issue by Ogiso-M** [sweetalert2/sweetalert2#2407]
## Current behavior

Hello.
I try to focus on some input element after closing sweetAlert2 but it doesn't happen.
The focus appears and immediately disappear.
I use sweetAlert2 (v. "11.4.0") .
And I found out the previous solution("#1604"), but it doesn't work.

## Expected behavior

After closing sweetAlert specific element should be focused

## Live demo 

        Swal.fire({
            icon: 'warning',
            title: 'Warning',
            text: "Please input the day."
        }).then((result) => {

            if (result.isConfirmed) {
                document.getElementById('a2').focus();
            }
        })

**Comment by limonte** [comment]
Hello @Ogiso-M 

I believe setting the `returnFocus` params to `false` will help you. Docs: https://sweetalert2.github.io/#returnFocus

**Comment by Ogiso-M** [comment]
Thank you for your quick and kind reply.
It worked well.
