### ISSUE TITLE
allowOutsideClick console warning

### ISSUE THREAD

**Issue by bytestream** [sweetalert2/sweetalert2#2410]
## Current behavior

The following is written as a warning to the browser console

```
SweetAlert2: "allowOutsideClick" parameter requires `backdrop` parameter to be set to `true`
```

## Expected behavior

No console warning because https://sweetalert2.github.io/ lists the `backdrop` configuration option with a default value of `true`

## Live demo 

Click the `Try me` button on https://sweetalert2.github.io/ for the "AJAX request" example

**Comment by qWici** [comment]
Move issue to [sweetalert2.github.io repo](https://github.com/sweetalert2/sweetalert2.github.io)

**Comment by priyangsubanerjee** [comment]
Can you please assign me this issue?
