### ISSUE TITLE
Incorrect Type Definition

### ISSUE THREAD

**Issue by graphemecluster** [sweetalert2/sweetalert2#2411]
https://github.com/sweetalert2/sweetalert2/blob/master/sweetalert2.d.ts#L679

> A custom CSS class for the popup.
> **If a string value is provided**, the classname will be applied to the popup.
> If an object is provided, the classnames will be applied to the corresponding fields:

```diff
- customClass?: SweetAlertCustomClass
+ customClass?: SweetAlertCustomClass | string
```

**Comment by rsrinivasan1** [comment]
Hi, I can try to resolve this as my first issue.
