### ISSUE TITLE
It does not work with Vite, what is the reason? Thanks!

### ISSUE THREAD

**Issue by anbreaker** [sweetalert2/sweetalert2#2414]
## Current behavior

Hi, I was testing sweetalert2 with a React application using Vite as a packager.
And it's not working properly with npm, but if you use cdn it's working.

![error](https://user-images.githubusercontent.com/6112820/156754886-60d66a9b-eb87-4a77-b742-48788b297e91.PNG)

## Live demo, this is a example than problem.

Working example in order for your to be able to reproduce the issue.
The live demo template: 

[Example](https://stackblitz.com/edit/vitejs-vite-4jxuhe?devtoolsheight=33&file=src/App.jsx)

https://stackblitz.com/edit/vitejs-vite-4jxuhe?devtoolsheight=33&file=src/App.jsx

**Comment by anbreaker** [comment]
The solution is in Documentacion, sorry.

https://github.com/sweetalert2/sweetalert2-react-content

It is working.

**Comment by limonte** [comment]
Hey @anbreaker

Could you please share what was the issue with your code?

**Comment by anbreaker** [comment]
I followed the instructions to make it work with React and I thought I commented the cdn, but I just checked that it is not working correctly, because what works is the cdn. Sorry.

What is the solution?

**Comment by anbreaker** [comment]
> ## Current behavior
> Hi, I was testing sweetalert2 with a React application using Vite as a packager. And it's not working properly with npm, but if you use cdn it's working.
> 
> ![error](https://user-images.githubusercontent.com/6112820/156754886-60d66a9b-eb87-4a77-b742-48788b297e91.PNG)
> 
> ## Live demo, this is a example than problem.
> Working example in order for your to be able to reproduce the issue. The live demo template:
> 
> [Example](https://stackblitz.com/edit/vitejs-vite-4jxuhe?devtoolsheight=33&file=src/App.jsx)
> 
> https://stackblitz.com/edit/vitejs-vite-4jxuhe?devtoolsheight=33&file=src/App.jsx

**Comment by limonte** [comment]
Vite utilises `<script type="module" src="...">`. By default, for ES modules `src/sweetalert2.js` is used, this file doesn't contain CSS styles.

There are 2 ways to make SweetAlert2 work for Vite:

1. Import SweetAlert2 from `dist/sweetalert2.all.js`:
```js
import Swal from 'sweetalert2/dist/sweetalert2.all.js'
```

2. Or import styles manually:
```js
import Swal from 'sweetalert2'
import 'sweetalert2/dist/sweetalert2.css'
```

I'd personally use the second way, it's a bit better.

**Comment by anbreaker** [comment]
Thanks, it's weird to bring you the css from the build, but it works.
