### ISSUE TITLE
Number input type with plus/minus buttons

### ISSUE THREAD

**Issue by martinmorenoc** [sweetalert2/sweetalert2#2417]
## New feature motivation

I know something similar can be done with _range_ input type, anyway, I think a plus/minus input counter would be nice.

Reference image:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/43624675/157059609-d3c4d58f-6746-4afe-977c-c90ff8d99ca6.png">

**Comment by schaldach** [comment]
Where exactly this plus/minus input counter would be? I can work on this.

**Comment by limonte** [comment]
This feature should be in the codebase. If `input: 'number'` isn't enough, the custom input number should be used, e.g. https://input-number.vercel.app/

**Comment by limonte** [comment]
Added the example here: https://sweetalert2.github.io/recipe-gallery/input-number-plus-minus-buttons.html
