### ISSUE TITLE
when closing popup appears a iframe that lock all window

### ISSUE THREAD

**Issue by devbitbcn** [sweetalert2/sweetalert2#2420]
## Current behavior

When close a dialog with close button appears at end of page a iframe thats lock de screen and controls are disabled.

![Captura1](https://user-images.githubusercontent.com/101809452/159550970-082ca192-0c0f-49e2-92b1-686f0b6697fa.PNG)

`<iframe style="position: fixed; top: 0px; left: 0px; width: 100%; height: 100%; border: none; z-index: 2147483647;"></iframe>`

![Captura2](https://user-images.githubusercontent.com/101809452/159551206-4212aa87-4335-4cfa-89db-4aa69841a913.PNG)

## Expected behavior

I don´t undestand why this iframe is added

![Captura2](https://user-images.githubusercontent.com/101809452/159551165-c889328d-94d6-4e11-afcb-70ee16caf4da.PNG)

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
