### ISSUE TITLE
HTML Input value only pulls first word of string

### ISSUE THREAD

**Issue by nicholasvperry** [sweetalert2/sweetalert2#2423]
I am using swal as an edit form and when I pull the value of a string from an object it only pulls the first word and not the whole string.
Here is the code I have written:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/90103179/160865675-0f90777a-4f4d-47a7-a722-35060353f0c6.png">

Here is the result:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/90103179/160865778-16632344-2007-4cc6-be94-90bfa9ca011a.png">

As you can see it only pulls the first word from both the subject and the content. 

Also if I am using a textarea instead of an input it pulls no value at all.

Code:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/90103179/160867963-2740bc5b-2ebc-4a87-b6f6-5541e4c155e2.png">

Result:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/90103179/160868129-39325fd8-9f8b-42d6-8c70-2fa26b0e29a4.png">

**Comment by limonte** [comment]
Wrap the value in quotes.
