### ISSUE TITLE
How to import css file for SweetAlert2 ?

### ISSUE THREAD

**Issue by hoahiep506** [sweetalert2/sweetalert2#2431]
I have a lot of css custom for sweetalert so I clone a  sweetalert2.css in nodemodules and customize it. Then I import it on a HOC wrote. 

```
import Swal from 'sweetalert2';
import 'assets/styles/sweetalert2.css';
import { t } from 'i18n';
import { TYPE_ALERT } from 'constant/toast';

const Toast = Swal.mixin({
  toast: true,
  position: 'top-end',
  showConfirmButton: false,
  timerProgressBar: true,
  timer: 3000,
  didOpen: (toast) => {
    toast.addEventListener('mouseenter', Swal.stopTimer);
    toast.addEventListener('mouseleave', Swal.resumeTimer);
  },
});
```

It work on local host but not work on prod build. How can I apply it for prod build ? Thanks you so much

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
