### ISSUE TITLE
Custom description alert will not show icon when property set "icon:"

### ISSUE THREAD

**Issue by civetcat** [sweetalert2/sweetalert2#2435]
## Current behavior
In https://sweetalert2.github.io/ sample write custom description alert like this format:

Swal.fire({
  title: '',
  icon: 'info',
  html:
}

## Expected behavior

Expected icon will shown in webpage, but is not.

## Live demo 

But when i change "icon" to "type", it works!

**Comment by limonte** [comment]
https://github.com/sweetalert2/sweetalert2/releases/tag/v9.0.0
