### ISSUE TITLE
Deprecation Warning - Upgrade SASS

### ISSUE THREAD

**Issue by marciocamello** [sweetalert2/sweetalert2#2445]
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($number, $number * 0 + 1) or calc($number / ($number * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div

![image](https://user-images.githubusercontent.com/4071580/169497979-5fb47c48-1026-4123-9435-a0959c4eb589.png)

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
