### ISSUE TITLE
It doesn't scroll to that id.

### ISSUE THREAD

**Issue by moa12gg** [sweetalert2/sweetalert2#2446]
Here is my a tag.
Pressing this will call test.
`<a onclick="test()" class="btn btn-success btn-lg" target="_blank">testbtn</a>`

And when I press cancel, I want to scroll to the id of mov.
`<script type="text/javascript">`
`  function test(){`
`    Swal.fire({`
`      title: 'test',`
`      text: "test",`
`      icon: 'info',`
`      showCancelButton: true,`
`      confirmButtonColor: '#3085d6',`
`      cancelButtonColor: '#0054FF',`
`      confirmButtonText: 'ok',`
`      cancelButtonText: 'cancel'`
`    }).then((result) => { if (result.value) { `
`    }else{`
`      window.location.href = "#mov";`
`    }`
`  })`
`}`
`</script>`

`<div id="mov">hi</div>`

But this doesn't really work.
Although scrolling goes down, the scroll does not move to the desired position... only a little from the current position.

It works for anything other than sweetalert2.

What's wrong?
I don't speak English, so I used a translator. I'm sorry.

**Comment by moa12gg** [comment]
I am using it temporarily.
_window.location.href = "#mov";_ 
->
**window.scrollTo(0, 450);**

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
