### ISSUE TITLE
Window dragged to focus when alert opens?

### ISSUE THREAD

**Issue by dimosmera** [sweetalert2/sweetalert2#2448]
## Current behavior
This weirdly started yesterday, but it seems the window is dragged to focus when a sweet alert opens.
Please see .gif on the live demo. Happens on both Chrome and Firefox (latest versions on Mac and Windows), but not on Safari or Edge

I am using `"sweetalert2": "^10.12.7"` and `"sweetalert2-react-content": "^3.2.2"` 

## Expected behavior
Until now, the window wasnt dragged to focus. The sweet alert on the gif is opened within an iframe on a page.

I am expecting the page to **not scroll** to the iframe that opens the sweet alert.

## Live demo 
![May-28-2022 16-25-20](https://user-images.githubusercontent.com/42207157/170827709-0d4cc011-a322-4137-8ff8-2b1cd706a1ca.gif)

**Comment by limonte** [comment]
sweetalert2@10 is unmaintained, please upgrade to the latest version.
