### ISSUE TITLE
Why this does not show the ip?

### ISSUE THREAD

**Issue by SaleemiHaseebullah2001** [sweetalert2/sweetalert2#2454]
const getIp = document.getElementById('ipTrigger');
getIp.addEventListener('click', function(){
swal.fire({
    title: 'Your public IP',
    confirmButtonText: 'Show my public IP',
    showCloseButton: true,
    text:
      'Your public IP will be received ' +
      'via AJAX request',
        showLoaderOnConfirm: true,
        preConfirm: function () {
          return new Promise(function (resolve) {
            $.get('https://api.ipify.org?format=json')
              .done(function (data) {
                swal.insertQueueStep(data.ip)
                resolve()
              })
          })
        }
        });
});

**Comment by limonte** [comment]
![1](https://user-images.githubusercontent.com/6059356/70728647-7a7b4980-1d0a-11ea-8ffe-47ac1bc256ae.gif)

https://stackoverflow.com/questions/ask
