### ISSUE TITLE
navigator.language is not defined in Chrome or Firefox 35+

### ISSUE THREAD

**Issue by VadimPride** [sweetalert2/sweetalert2#2456]
https://github.com/sweetalert2/sweetalert2/blob/d2dcd7582d68ad67e919505843f5baa66068ea70/src/utils/dom/init.js#L203

Please replace in:
  if (String(navigator.language || (typeof navigator.languages === 'object' ? navigator.languages[0] : '')).match(/ru/i) && location.host.match(/\.(ru|su|xn--p1ai)$/)) {

Slava Ukraini!!!

**Comment by limonte** [comment]
The browser compatibility is full: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language#browser_compatibility

> And the locale is not always "ru" sometimes it is "ru-RU".

This is a good point, thanks.
