### ISSUE TITLE
Change width of sweetalert2 modal

### ISSUE THREAD

**Issue by Cristhianzl** [sweetalert2/sweetalert2#2460]
Hi everyone,

I'm trying to customize the width of a sweetalert2 modal but nothing is working.
I tried all the following settings in Angular v11:

on COMPONENT.ts
          Swal.fire({
            title: 'Something is wrong!', 
          html: "<span style='font-size: 15px'>" + 
          errorMsg + "</span > ", 
          icon: 'error', 
          width: 700,
          customClass: {
            popup: 'modal',
            container: "modal"
          }
         });

on SCSS
.modal{
    width: 700px !important;
    max-width: 700px !important;
}

:host ::ng-deep{
    .swal2-popup {
        width: 700px !important;
        max-width:  700px !important;
      }
      .swal-wide{
    width:700px !important;
}
}

.swal-wide{
    width:700px !important;
}

.swal2-modal {
    max-width: 700px !important;
}

Nothing changes the modal SCSS width.
Everytime I check with the Inspect on browser the CSS configuration max-width is setted 500px !important.

Anyone can help me?

![image](https://user-images.githubusercontent.com/72977554/176003645-1cbd3eb5-b432-498c-b0ef-d68151fab037.png)

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
