### ISSUE TITLE
Feature: PreDismiss

### ISSUE THREAD

**Issue by NickSutton** [sweetalert2/sweetalert2#2463]
## New feature motivation

Wanting to be able to offer a confirmation / logic check when the user clicks the close icon

## New feature description

I can prevent a popup being closed by returning false when the user clicks the cancel button by using the preDeny option, but can not do the same when the user clicks the close button.

## New feature implementation

Mirror preDeny functionality for when the popup is dismissed with the close button.

**Comment by limonte** [comment]
I don't think it's a good idea from the UX perspective not to close the popup when a user clicks the close button. It's better not to show the close button and if needed show it by calling `Swal.update({showCloseButton: true})`

**Comment by NickSutton** [comment]
What I'm trying to do is confirm that the user does want to close the modal
