### ISSUE TITLE
SweetAlertCustomClass doesn't have content property as per docs

### ISSUE THREAD

**Issue by jongbonga** [sweetalert2/sweetalert2#2465]
## Current behavior

`SweetAlertCustomClass` doesn't have the content property anymore as per [documentation](https://sweetalert2.github.io/#customClass)

Not sure if it's a documentation issue or if the interface is actually missing it

**Comment by limonte** [comment]
It was a mistake in docs, thanks @jongbonga 

Most probably you're looking for `customClass.htmlContainer`

**Comment by jongbonga** [comment]
The class passed to `customClass.htmlContainer` is not being seen/applied.
I'm trying to style the `text` property.

how do I go about that?

**Comment by limonte** [comment]
> The class passed to `customClass.htmlContainer` is not being seen/applied.

This is not true.

```js
Swal.fire({
  text: 'hello',
  customClass: {htmlContainer: 'my-class'}, 
})
```

works as expected:

<img width="530" alt="CleanShot 2022-07-11 at 18 35 20@2x" src="https://user-images.githubusercontent.com/6059356/178301704-d0ed52a6-5343-4244-a26b-ec59a52154ba.png">

**Comment by jongbonga** [comment]
Very true!
My apologise, was inspecting the wrong swal.
