### ISSUE TITLE
Error in cdn

### ISSUE THREAD

**Issue by tltary** [sweetalert2/sweetalert2#2466]
Additional code is loaded when using cdn jsdeliver https://cdn.jsdelivr.net/npm/sweetalert2@11

A banner appears on the entire site

leave-russia-now-and-apply-your-skills-to-the-world

![Снимок экрана 2022-07-13 в 18 44 30](https://user-images.githubusercontent.com/6262642/178762297-76aec5a9-2fd5-4b66-8e5c-32d657a60cf6.png)

![telegram-cloud-photo-size-2-5366255581733699144-y](https://user-images.githubusercontent.com/6262642/178762389-65ab50ae-f20c-4aac-8f42-5414878a7450.jpg)

**Comment by kubo6472** [comment]
@tltary switch to neutral: https://github.com/lofcz/sweetalert2-neutral#sweetalert-2-neutral

**Comment by sanek20** [comment]
Я решил эту проблему просто прописав в function.php код к стилю который показывает это окно "display: none;". И все.
