### ISSUE TITLE
Sponsored ad showing

### ISSUE THREAD

**Issue by matvejs16** [sweetalert2/sweetalert2#2474]
Sweetalert2 (v11.4.24) downloaded by NPM

## Current behavior
Ads appear from time to time

## Expected behavior
There shouldn't be any ads

## Live demo
![image](https://user-images.githubusercontent.com/74150728/180649767-f92c9fbd-5c00-43d8-a0e5-26465da8e617.png)

**Comment by limonte** [comment]
That's intentional behavior, see https://github.com/sweetalert2/sweetalert2/pull/2462 for the details.

**Comment by kubo6472** [comment]
@matvejs16 use neutral: https://github.com/lofcz/sweetalert2-neutral#sweetalert-2-neutral
