### ISSUE TITLE
question for @limonte

### ISSUE THREAD

**Issue by afkvido** [sweetalert2/sweetalert2#2485]
Hi there, @limonte.

How come there are like 2x more sponsors selling sex toys (NSFW sponsors) than normal sponsors? Just a quick question, because it seems strange, I was expecting something the other way around.

**Comment by limonte** [comment]
Most of the sponsors including both "normal" and NSFW are here for SEO purposes. Backlinks from https://sweetalert2.github.io/ are valuable. There are more NSFW links because those websites need SEO more than "normal" sponsors for sustaining their businesses.

**Comment by afkvido** [comment]
Ah, ok. Thanks for answering!
