### ISSUE TITLE
Safari 14.1.2 not working

### ISSUE THREAD

**Issue by Simoneth** [sweetalert2/sweetalert2#2487]
Hi,
I'm working with Next JS (v12) + React JS (v17) and I noticed that in **Safari**, Sweet Alert 2 (v11.4.16) doesn't work at all (popup never shown, pictures shown on page).

My component:
```
import Swal from "sweetalert2/dist/sweetalert2.js";
import withReactContent from 'sweetalert2-react-content';

export const MySwal = withReactContent(Swal)

export const SwalAlert = (_icon = '', _title = '', _mex = '', _html = '', _footer = '') => {

    MySwal.fire({
        icon: _icon,
        title: _title,
        text: _mex,
        html: _html,
        footer: _footer,
    });

}
```
I tried to import CoreJS but it doesn't help

```
import Swal from "sweetalert2/dist/sweetalert2.js";
import withReactContent from 'sweetalert2-react-content';
import 'core-js/actual';
...

```

Could you please help me?

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
