### ISSUE TITLE
Swal fullscreen overlay

### ISSUE THREAD

**Issue by Marwanb10** [sweetalert2/sweetalert2#2488]
I have a problem when, when there is a fullscreen element on the page, the swal popup doesn't show up on top of the elements unless I trigger it twice, the first trigger, the swal popup shows up on top of all of the bodt children but under the fullscreen element, the second trigger shows it at the highest level (on top of everything even the fullscreen element which is how it should be from the start)

`<div id="planification-portal"></div>`
`document.getElementById('planification-portal').appendChild(document.querySelector('.swal-overlay--show-modal'));`

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by Marwanb10** [comment]
Current behavior 

I have a problem when, when there is a fullscreen element on the page, the swal popup doesn't show up on top of the elements unless I trigger it twice, the first trigger, the swal popup shows up on top of all of the body children but under the fullscreen element, the second trigger shows it at the highest level (on top of everything even the fullscreen element which is how it should be from the start)

Expected behavior

 the swal popup haveto show up on the body before i click 

Live demo 

`<div id="planification-portal"></div>`
`document.getElementById('planification-portal').appendChild(document.querySelector('.swal-overlay--show-modal'));`

the swal popp up i need this class swal-overlay--show-modal go to div id planification-portal first click not go to body after second click
