### ISSUE TITLE
Uncaught TypeError: Cannot set properties of undefined (setting 'oninput')

### ISSUE THREAD

**Issue by Geovanek** [sweetalert2/sweetalert2#2490]
I do not know what happened.
After performing an npm update today, all events with SweetAlert broke.

In the console this appears:
```app.js:14313 Uncaught TypeError: Cannot set properties of undefined (setting 'oninput')
    at addInputChangeListeners (app.js:14313:19)
    at init (app.js:14389:5)
    at setParameters (app.js:15648:5)
    at SweetAlert._main (app.js:17320:7)
    at new SweetAlert (app.js:17300:39)
    at SweetAlert.fire (app.js:17112:12)
    at livewireSweetAlert.js:7:8
    at MessageBus.js:17:13
    at Array.forEach (<anonymous>)
    at MessageBus.value (MessageBus.js:16:38)
```

If I click to go where the error appears, this appears:

![image](https://user-images.githubusercontent.com/7670960/188323007-5fdec6f1-aad5-45b2-9c7c-c4fac5000ea6.png)

Can anyone shed some light on this for me?

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by janakan22** [comment]
@Geovanek Did you find a solution for this problem. Struggling with this too at the moment
