### ISSUE TITLE
Support rem units for sizing

### ISSUE THREAD

**Issue by toadkicker** [sweetalert2/sweetalert2#25]
I started hacking on supporting rem units instead of pixels for the alert. I realize this could be a potentially risky endeavour, but I feel the payoff would benefit the project long-term. What's your thoughts on supporting dynamic resizing of the alert vs using pixels? I'll send a PR when I'm happy with the results, but I'm interested in knowing if its worth it or keeping my fork specific to the implementation I'm using.

**Comment by limonte** [comment]
I personally can't see benefit of using rem in this particular case. Can you please add more about WHY you want rem support? Thank you.

**Comment by toadkicker** [comment]
In my particular case we're concerned about scaling font sizes, line height, margins, borders, etc. using media queries. For example in our CSS:

```
html {
  line-height: 1.4;
  font-size: 13px;
}

@media screen and (min-width: 500px) {
  html {
    font-size: 12px;
  }
}

@media screen and (min-width: 570px) {
  html {
    font-size: 13px;
  }
}

@media screen and (min-width: 620px) {
  html {
    font-size: 14px;
  }
}

@media screen and (min-width: 680px) {
  html {
    font-size: 15px;
  }
}

@media screen and (min-width: 720px) {
  html {
    font-size: 16px;
  }
}

@media screen and (min-width: 800px) {
  html {
    font-size: 17px;
  }
}

@media screen and (min-width: 860px) {
  html {
    font-size: 18px;
  }
}

@media screen and (min-width: 920px) {
  html {
    font-size: 20px;
  }
}

section {
  padding: 3rem 10%;
  background: hsl(0, 0%, 98%);
}

section:nth-child(even) {
  background: hsl(0, 0%, 94%);
}

h1, h2 {
  line-height: 1.3rem;
}

h1 {
  font-size: 2rem;
  margin: 0 0 1rem;
}

h2 {
  font-size: 1.5rem;
  margin: 1rem 0 2rem;
}

p {
  font-size: 1rem;
  margin: 1rem 0;
}
```

That gives us pretty smooth transition of sizes between different resolutions. It looks a little strange when the UI's viewport is full screen and the font sizes, line height, etc. don't match up. Using rem's would make the alert fit the existing styling much easier.

**Comment by limonte** [comment]
@toadkicker After a little bit reading about rem, your suggestion makes sense for me. Can you please make pull request so we can test and discuss this feature. Thank you!

**Comment by mmethot** [comment]
That would definitely be using this. Good point!

**Comment by limonte** [comment]
`transform: scale()` can do the same as rem units

**Comment by limonte** [comment]
I'm re-opening this issue after 2.5 years. Sometimes it takes time to understand fundamental things.

**Comment by MattJLeach** [comment]
Hi @limonte 
I'll be happy to have a look at this over the next couple of days. I'm currently using Sweet Alert v1 for a project and will be upping to v2 soon so am more than happy with contributing.

**Comment by limonte** [comment]
Hi @MattJLeach!

Please do! I'm trying to make this project as much community-driven as possible. Every PR is very very welcome :beers:

**Comment by limonte** [comment]
I made it! After more than 2 years here's the release with rem support: https://github.com/sweetalert2/sweetalert2/releases/tag/v7.5.0

Please check it out and give your feedback. Thanks to all!

**Comment by KnowMoreIT** [comment]
Sizing did not look good on this at all when I upgrade:
![image](https://user-images.githubusercontent.com/5861587/35179337-fa9eb9ea-fd5d-11e7-80cf-20cb671839a2.png)

**Comment by limonte** [comment]
Thanks for reporting @KnowMoreIT! Could you please attach the code as well so I can reproduce the issue?

**Comment by limonte** [comment]
@KnowMoreIT I just pushed the patch release v7.5.1 with the gap between actions (buttons) and the content.

Could you please help me to figure out what happened to the font-size? For some reason it looks smaller on your first screenshot then on the second one. It should be the same, so you have non-default base font-size in your browser?

**Comment by acurrieclark** [comment]
I know that this has just been merged and released, but this wreaks havoc when the root font size has been set to anything other than 100%. 

A better option here might have been to use `em` with a higher element given an `rem` factor. This way it is easy to override the base value with one css setting.

This argument is laid out in this article and [when to use rem and em](https://css-tricks.com/rem-global-em-local/).

I wholeheartedly agree that allowing for accessibility is vital, I just think that perhaps it hasn't been achieved in the best way here.

**Comment by limonte** [comment]
> I know that this has just been merged and released, but this wreaks havoc when the root font size has been set to anything other than 100%.
> 
> A better option here might have been to use em with a higher element given an rem factor. This way it is easy to override the base value with one css setting.
> 
> This argument is laid out in this article and when to use rem and em.
> 
> I wholeheartedly agree that allowing for accessibility is vital, I just think that perhaps it hasn't been achieved in the best way here.

Many thanks @acurrieclark for your feedback and accept apologies for wreaking havoc.

I'll release the next version today in which I'll:

- set the `font-size: 1rem` on the popup itself
- change `rem` to `em` for all children

**Comment by limonte** [comment]
@acurrieclark please check out https://github.com/sweetalert2/sweetalert2/releases/tag/v7.6.0 :tata:

**Comment by acurrieclark** [comment]
@limonte this is the sweetest of music. A thousand thank yous for the swift turnaround.

Havoc averted!

**Comment by ThomHurks** [comment]
@limonte I have the same problem that @KnowMoreIT has, namely that after upgrading to v7.6.3 suddenly my alerts appear smaller, exactly like in his screenshots. They do look normal as in no squished buttons, but they are smaller or "scaled down" so they are now out-of-sync with the rest of the styling. The project I'm using SweetAlert2 in is a fairly standard Bootstrap-sass 3.3.7 project with no advanced CSS tweaks or anything. The only font-related scss that I'm using is:
```sass
$icon-font-path: "~bootstrap-sass/assets/fonts/bootstrap/";
$font-family-sans-serif: "Raleway", sans-serif;
```
Any idea why this is happening, as from your comment I interpret it probably shouldn't have changed? I can help with debugging if you give me some pointers.

**Comment by limonte** [comment]
Hello @ThomHurks and thank you for reporting!

I added `!default` to all SASS variables in [v7.7.0](https://github.com/sweetalert2/sweetalert2/releases/tag/v7.7.0)

Also, take a look on the related issue which might help you: https://github.com/sweetalert2/sweetalert2/issues/834#issuecomment-359237178

**Comment by ThomHurks** [comment]
@limonte Thanks a lot! 

I still don't understand why I can't just set
```SCSS
$swal2-font-size: 1.6rem;
```
as I think that should work. However, I just concatenate some extra plain old CSS now after the SASS step and add
```css
.swal2-popup {
  font-size: 1.6rem !important;
}
```
and that does work even though it's a bit hacky. 

Thanks again! :)

**Comment by limonte** [comment]
Good news everyone! The oldest SweetAlert2 issue can be closed now!

SweetAlert2 is fully flexible and customizable now :tada:

### Plain CSS way

```css
.swal2-popup {
  font-size: 1.25rem !important;
}
```

- live demo https://jsfiddle.net/ad3quksn/726/embedded/result/
- jsfiddle https://jsfiddle.net/ad3quksn/726/

### Overriding `$swal2-font-size` SASS variable

```scss
$swal2-font-size: 1.2rem;

@import './node_modules/sweetalert2/src/sweetalert2.scss';
```

- live demo https://sweetalert2.github.io/sweetalert2-parcel-demo/dist/
- source code https://github.com/sweetalert2/sweetalert2-parcel-demo

**Comment by toadkicker** [comment]
Fantastic. Thanks for putting this in!
