### ISSUE TITLE
Missing video control buttons on Safari when video is used in html template

### ISSUE THREAD

**Issue by f0enix** [sweetalert2/sweetalert2#2507]
## Current behavior
Placing a video tag inside the html template prevents the controls buttons like play/pause to be shown in Safari. The controls appear fine in Chrome and Edge.
SweetAlert2 version: 11.0
Safari version: 15.6.1
Mac version: 12.5.1
Chrome version: 105.0
Edge version: 105.0

```javascript
Swal.fire({
 html: `
   <video height="200px" controls src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4">
   </video>
`,
  showCloseButton: true,
  showCancelButton: false
}) 
```

## Expected behavior
The video controls button should always appear.

## Live demo 
https://codepen.io/f0enix/pen/VwxQjwb

Downgrading SweetAlert2 to version 8.0 makes the controls appear again in Safari. So it got broken in v9.

**Comment by kenara** [comment]
Opening the demo Codepen on my iPhone Xʀ (iOS 15.6.1), the alert is completely blank - no <video> tag at all...

**Comment by f0enix** [comment]
> Opening the demo Codepen on my iPhone Xʀ (iOS 15.6.1), the alert is completely blank - no video tag at all...

Yes because on ios safari does not display any video thumbnail image by default.

i just updated the video link to include media fragment `#t=0.001`to force a thumbnail. Now it should appear in your ios device.

**Comment by limonte** [comment]
Very interesting, thanks for reporting! 👍

**Comment by limonte** [comment]
The issue is related to safe HTML parsing which is done via `DOMParser`, I've asked the question on StackOverflow, hopefully, the community will be able to help

**Comment by limonte** [comment]
It is the webkit issue:

- [Here's a link to the webkit bug ticket](https://bugs.webkit.org/show_bug.cgi?id=222657)
- [comment \#6](https://bugs.webkit.org/show_bug.cgi?id=222657#c6) (2021-03-04 22:50:29 PST):
  > \[...\] media element not initialize its UA shadow root when it's created inside a document without a browsing context. The fix is to initialize the media element controls once it's inserted into a document with a browsing context.
- [comment \#12](https://bugs.webkit.org/show_bug.cgi?id=222657#c12) (2022-08-02 11:16:50 PDT): Pull request: https://github.com/WebKit/WebKit/pull/2955
- [comment \#13](https://bugs.webkit.org/show_bug.cgi?id=222657#c13) (2022-08-08 11:47:08 PDT): Committed `253225@main (f331cc98c1de)`: <https://commits.webkit.org/253225@main> Reviewed commits have been landed. Closing PR #2955 and removing active labels.
