### ISSUE TITLE
Is there any solution to prevent toast from dismissed when clicked inside it?

### ISSUE THREAD

**Issue by ichlasdev** [sweetalert2/sweetalert2#2508]
I just want toast to be shown and not click-to-dismiss by user.

Is there any configuration for it?

**Comment by limonte** [comment]
A toast will dismiss itself by internal click only if there are no other ways for users to dismiss it, e.g. no buttons are shown.

You can set `showCloseButton` to `true` to avoid click-to-dismiss feature.

If you really want to disable click-to-dismiss feature and not show any buttons (IMO this is poor UX and will annoy users), do this:

```css
.hidden {
  display: none !important;
}
```

```js
Swal.fire({
  toast: true,
  showCloseButton: true,
  ...
  customClass: {
    closeButton: 'hidden',
  },
})
```

**Comment by tomdav999** [comment]
Did something change?  Toasts do not close when clicked on, even with showCloseButton: false

To demonstrate, click on the toast example here:  https://sweetalert2.github.io/#methods

The toast does not close when clicked.  Now click to go to codepen and change version to 10.10.1 and voila, toast will close when clicked on.  Seems something is fubar in current version.
