### ISSUE TITLE
The warning, question and info icons are not show correctly.

### ISSUE THREAD

**Issue by IlayBokobza** [sweetalert2/sweetalert2#2510]
When every I try to use  warning, question or the info icons, they do not show correctly. I have no idea what causes it.
I was unable to create a live demo recreation. 
I am and vuejs v2.6.11.
I have tried the normal version (v11.4.35) and the vue version (v5.0.5), and neither work.

Here is how the icons look like.
![image](https://user-images.githubusercontent.com/66033426/193420777-636a0d61-eed4-412b-97be-dd4de12835f4.png)
![image](https://user-images.githubusercontent.com/66033426/193420783-e4b6f2f9-9703-428f-a3be-4860527b0d6b.png)
![image](https://user-images.githubusercontent.com/66033426/193420795-b032c613-708b-4b8f-a7a2-202920b79f56.png)

Thanks in advance.

**Comment by limonte** [comment]
I'd assume the custom font you're using doesn't support those characters. For more help please follow the issue template and provide live demo
