### ISSUE TITLE
Focus stay on the background, not on the "ok" button of my SweetAlert2

### ISSUE THREAD

**Issue by aPaK22** [sweetalert2/sweetalert2#2522]
Hello !!!

I got a problem with my SweetAlert2. (Can't JsFiddle for now)

I have a "modify" button wich open a Bootstrap Modal with some fields. I can modify on it and get the SweetAlert2 confirmation when done. Works pretty good !!

But the focus here is still in the background page (on my modify button). So, if i click on my "ok" button on the SweetAlert2 popup, everything is ok. But if i press "Enter" key instead, it opens the modal again (because the focus seems to be on my modify button) and don't go to the .then() of my SweetAlert2).

I've tried many things since 2 days but i d'ont find any answer. Can someone help me please?

Thank you in advance !!

**Comment by limonte** [comment]
You need to JsFiddle :) Open a new issue following the issue template.
