### ISSUE TITLE
Focus only at the end of the show animation 

### ISSUE THREAD

**Issue by plouf142** [sweetalert2/sweetalert2#2526]
## Current behavior

The focus is done at rendering, so before show animation is fired. 

This produces an issue when we enhances the popup (for example, with an [input enhanced by a datepicker](https://stackoverflow.com/questions/74066842/do-not-focus-swal-input), the datepicker picker is displayed at the input enhanced final position since popup is moving throw window...).

## Expected behavior

Make the focus only after the show animation is done. 

So the behavior enhanced is fired only when the popup is on its final position. 

## Live demo 

EDIT : The [live demo in codeopen](https://codepen.io/plouf142/pen/qBYwrZj).

The [StackOverflow example demo cited above](https://stackoverflow.com/questions/74066842/do-not-focus-swal-input)

```
Swal.fire({
  ...
  text: "legend",
  input: "text",
  customClass: { popup: "datepicker-container" },
  ...
  preConfirm: (inputValue) => {
    ...
  },
  willClose: () => {
    if (datepicker) datepicker.destroy();
  },
});

var field = document.querySelector(
  '.datepicker-container input[type="text"]'
);

datepicker = new Pikaday(
  extend({ field: field, ...},)
);

```

**Comment by limonte** [comment]
Thanks for reporting @plouf142, but the live demo is missing. My guess would be that you need this:

```diff
- input: "text"
+ html: '<input class="swal2-input">',
```

See the live demo here: https://sweetalert2.github.io/recipe-gallery/input-date-flatpickr.html

For any more help please put some effort into creating a live demo.

**Comment by plouf142** [comment]
Thanks for your quick response. I've edited a live demo. 

The solution provided by recipe _Date input powered by flatpickr_ is for me a imperfect workaround. For complex personnalized content, as the _multiple inputs_ sample, the html is necessary. But the the input parameter provide various useful functions (inputValue, inputValidator, direct value in result...). All this functions can be recoded, but I find it a shame to have to abandon these functions for simple focus-related behavior.

**Comment by limonte** [comment]
do I understand correctly that the issue is the day picker is shown before the animation ends and looks like it's detached from the input for some short time?

**Comment by limonte** [comment]
If so, the simple workaround would be 

```js
didOpen: () => {
  let field = Swal.getInput();
  setTimeout(() => {
    datepicker = new Pikaday( {field: field});
    datepicker.show()
  }, 300);
},
```

**Comment by plouf142** [comment]
Exactly. 

Sorry if it wasn't clear. 

In my production code, my actual workaround is to disable shown animation.

**Comment by plouf142** [comment]
I understand your workaround, 300 ms is the animation duration for default duration. But I uses custom Animate.css animation. So I will adapt with the real animation duration.

**Comment by limonte** [comment]
I've updated the datepicker example to use `input: 'text'`, since it's indeed better than custom html param with `<input class="swal2-input">`: https://sweetalert2.github.io/recipe-gallery/input-datepicker.html

**Comment by limonte** [comment]
> 1. `Swal.getPopup()` to get the HTML Swal popup (I found this function with GitHub search, it isn't in [user documentation](https://sweetalert2.github.io/#methods), normal?)

Not normal! 😆

**Comment by limonte** [comment]
Thanks for the feedback @plouf142 could you maybe share the code as well?

**Comment by plouf142** [comment]
Of course. I was doing some cleanup...

https://codepen.io/plouf142/pen/KKRYoVe
