### ISSUE TITLE
Can't make build, getting Error message

### ISSUE THREAD

**Issue by matvejs16** [sweetalert2/sweetalert2#2539]
## Current behavior
Getting console error when running yarn build:
![image](https://user-images.githubusercontent.com/74150728/197895226-f1668fd0-409d-4e56-80d3-c6b0ec289c0a.png)

## Expected behavior
Builds normally

## Live demo 
No demo required for this.

## Steps to reproduce:
```bash
git clone https://github.com/sweetalert2/sweetalert2.git
cd ./sweetalert2
yarn
yarn build
```

**Comment by mani91g** [comment]
Try npm install and npm start instead of yarn and yarn build

**Comment by limonte** [comment]
You don't need `npm run build` in dev environment, it's only used in CI for publishing purposes.

Use `npm start` or `yarn start` instead.

**Comment by matvejs16** [comment]
> You don't need `npm run build` in dev environment, it's only used in CI for publishing purposes.
> 
> Use `npm start` or `yarn start` instead.

That's why I need npm run build
I wan't to compile my own version of sweetalert with some changes.
How can I build it?
