### ISSUE TITLE
Newest type definitions breaks on TypeScript < 4.1

### ISSUE THREAD

**Issue by Guergeiro** [sweetalert2/sweetalert2#2547]
## Current behavior
Type definitions use template literal types introduced in [TypeScript 4.1](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/).

## Expected behavior

Should compile on TypeScript, at least, major version 4 since there's no requirement for a specific TypeScript version.

## Live demo 

**Note** Will use typescript playground for this.

Version [4.1.5](https://www.typescriptlang.org/play?ts=4.1.5#code/C4TwDgpgBAwgynAqgOwJbCgXigcjADxygB9cBjAWyNJwqpNwEVrdVkW8yOxgOAnCPRqCOANwDuYgBZiKbWQENCDHAFIcAKA0R8YAPZ8MoSLAQA1BQBsArhADq6KSnRYoAAwAkAb2TWKAIwg+AF9veCQ0YGC3Bl8AoKA)

Version [4.0.5](https://www.typescriptlang.org/play?ts=4.0.5#code/C4TwDgpgBAwgynAqgOwJbCgXigcjADxygB9cBjAWyNJwqpNwEVrdVkW8yOxgOAnCPRqCOANwDuYgBZiKbWQENCDHAFIcAKA0R8YAPZ8MoSLAQA1BQBsArhADq6KSnRYoAAwAkAb2TWKAIwg+AF9veCQ0YGC3Bl8AoKA)

**Comment by limonte** [comment]
Thanks for reporting @Guergeiro 🙏
