### ISSUE TITLE
swal.showValidationMessage() and click backdrop does not run swalPromiseResolve(resolveValue)

### ISSUE THREAD

**Issue by toky0s** [sweetalert2/sweetalert2#2550]
```
const html: string = "some html";
    let d:Promise<void | SweetAlertResult<any>> = swal.fire({
      html: html,
      confirmButtonText: 'OK',
      focusConfirm: false,
      icon: 'error',
      preConfirm: () => {
        const commentValue: string = "Text from comment textbox";
        if (commentValue.trim().length > 0) {
          return { 
            some properties here
          };
        } else{
          swal.showValidationMessage('Comments is a mandatory field');
        }
      }
    }).then((result) => {});
      // Was the user clicked the OK button
      if (result.isConfirmed) {
        // do update
      }
      // Was the user clicked outside
      else if (result.isDismissed || result.isDenied) {
        // do update with default value.
      }
    });
```

So, when I have not input in my comment textbox and click the OK button,  the preConfirm() run, the validation message will be shown. But then I click backdrop, my then() block it does not run.

When i investigate, i found this block code in your library:

![image](https://user-images.githubusercontent.com/42485703/200770250-a1eafecf-e535-43c6-b00a-83048fc9aa53.png)

The flow stop at
`!resolveValue.isDismissed`

But when i add some modification like this:

![image](https://user-images.githubusercontent.com/42485703/200770806-f05b81e7-2ee4-4850-869d-8eaec297ca80.png)

It work 🎉 , my then() block run.

I think you have some problem with **swal.showValidationMessage()**

**Comment by limonte** [comment]
Clicking backdrop indeed does not resolve, but reject/dismiss Swal promise. That won't be changed.
