### ISSUE TITLE
overflow touch scroll doesn't work on popup Safari iOS

### ISSUE THREAD

**Issue by mjbalutan** [sweetalert2/sweetalert2#2551]
## Current behavior

overflow touch scroll doesn't work on popup Safari iOS

## Expected behavior

overflow touch scroll works in Android as the SweetAlert2 container is fixed in height

## Live demo 
https://mysdaeligibility.com.au/
Click on the top nav "About" or "Help"

**Comment by limonte** [comment]
Thanks for reporting, there's no better solution for this case than removing `max-height` from `.sda-popup-content-container`
