### ISSUE TITLE
CustomIcon image instread of warning, success, and info

### ISSUE THREAD

**Issue by shuaibaslam2019** [sweetalert2/sweetalert2#2558]
I want to have a custom image in the swalfire function icon from my local directory. I am using "https://cdn.jsdelivr.net/npm/sweetalert2@9" but I can see I can show image using https://cdn.jsdelivr.net/npm/sweetalert2@11.

Is there any way to place a custom icon using **IconHtml** attribute in **2@9** version? I want to have the following:

https://stackoverflow.com/questions/67327505/change-icon-sweetalert-with-image

Thank you.

**Comment by limonte** [comment]
Yes, `iconHTML` was added in [v9.0.0](https://github.com/sweetalert2/sweetalert2/releases/tag/v9.0.0), you can use it with https://cdn.jsdelivr.net/npm/sweetalert2@9
