### ISSUE TITLE
IconHtml attribute is not working in v9.0.0

### ISSUE THREAD

**Issue by shuaibaslam2019** [sweetalert2/sweetalert2#2559]
I have tried the following script with v11.0.0 and v9.0.0, iconHtml attribute works with v11.0.0 but not with v9.0.0

`<html>

	<head> 
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" crossorigin="anonymous"></script>
	</head>

	<title> </title>

	<body>

		<button  class="surveyButton checkoutBtn hvr-grow fs15 t-medium border-lighb t-white bg-lighb w-100 mb-2 b-0">Show Alert</button>

		<script> 
			$('.surveyButton').click(function(){
							Swal.fire({
								title: `ABC`,
								text: `ABC`,
								iconHtml: '<img src="https://picsum.photos/100/100">',
								showCancelButton: true,
								allowOutsideClick: false,
								allowEscapeKey: false,
								confirmButtonText: `ABC`,
								cancelButtonText: `ABC`,
								reverseButtons: true,
							}).then((result) => {
								if (result.isConfirmed) {
									
								} else {
									
								}
							});
						});
		</script> 
			
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
	
	
					
	</body>`

**Comment by limonte** [comment]
Sorry but v9 isn't maintained anymore. Upgrade to v11.
