### ISSUE TITLE
hacked? plays the anthem of Ukraine

### ISSUE THREAD

**Issue by Complex138** [sweetalert2/sweetalert2#2561]
When the library is connected, the anthem of Ukraine plays, how to understand this?

**Comment by Complex138** [comment]
![2022-11-22_15-54-04](https://user-images.githubusercontent.com/35313522/203257108-b5a15536-ee1a-4cac-8e81-3e243436efee.png)

**Comment by limonte** [comment]
You can understand this as a response to acts of terrorism your country is doing every single day since February 24th.

**Comment by Complex138** [comment]
Okay, it's not a problem to remove it and save it, I'll take it into account.
I consider it low to use my own dissatisfaction in the IT field, political slogans and calls for something.

**Comment by limonte** [comment]
The only one slogan is: stop killing people and destructing critical infrastructure in other countries.

**Comment by Complex138** [comment]
I have already fixed the problem. It won't cause any more inconvenience.

**Comment by Complex138** [comment]
Now you understand how useless it was to dip yourself in shit and for what?

**Comment by limonte** [comment]
Luckily not all the websites will be fixed because many russian webdevs are (mob|util)ilized :)

**Comment by Complex138** [comment]
You understand, everything will end sooner or later, but your shitty reputation will always be at the level of the plinth as a developer, you make millions of people tense up with your bad actions, today you don’t like Russia, tomorrow another country.

**Comment by Vearodev** [comment]
Thank you. Put this plugin in the trash. The most stupid decision from the developer...


Racism at its finest. This is exactly what Russia is fighting in Ukraine...

**Comment by robaweb** [comment]
Guys, let's give a warm "thanks" to @limonte about his shitty [commit](https://github.com/sweetalert2/sweetalert2/commit/7de8f7af35f4b0067edc4a735c5b9550537925c4) 
and report to NPM https://www.npmjs.com/support?inquire=security&security-inquire=malware&package=sweetalert2&version=11.6.11

**Comment by Complex138** [comment]
Кстати, да... Спортлото - это тема)

**Comment by limonte** [comment]
Не ну серьезно, ты поляку и англичанину решил пожаловаться на мой плагин ))) Они ж враги великого русского народа, который в одиночку противостоит всему злу на планете. Или этим злом и является, тут уж история рассудит.

**Comment by Complex138** [comment]
Бля, я не собираюсь разводить дискуссию на политику, хочешь обсудить или пообщаться, пиши в лс. Мне пизды дали за твои приколы. И как сказало большинство, твой код - твои правила. Хорошо, но, я думаю, можно было же хоть как-то это выделить, предупреждением в консоли или еще чего, твой код просто в тихую парализовал управление сайтом и включил звук. Я решил проблему и выдохнул, думаю если покопаться в правилах гита, управу найти можно, но честно я уже не хочу, мне за это не платят. А cdn не могут на это повлиять.

**Comment by limonte** [comment]
## ⚠️ The usage of this software for `.ru`, `.su`, and `.рф` domain zones is now prohibited 
 https://github.com/sweetalert2/sweetalert2#important-notice-about-usage-of-this-software-for-ru-su-and-%D1%80%D1%84-domain-zones

**Comment by z639** [comment]
Learn to separate your development from your political views. Even after Ukraine fired a missile at Poland and tried to pin it on Russia, you are still virtue signalling. I'd sooner find alternative software to use.

**Comment by bezumkin** [comment]
> The usage of this software for .ru, .su, and .рф domain zones is now prohibited

@limonte How does this relate to the [MIT license under which your code is published](https://github.com/sweetalert2/sweetalert2/blob/main/LICENSE)?

**Comment by markusramsak** [comment]
Please stop using software as a political tool. Russians are people, Ukrainians are people, Americans are people, Austrians are people, ... we are all people. Please stop discriminating some people by using software. Software should unite and not separate people. I am against war. Nobody likes to die in war.

**Comment by Complex138** [comment]
> > Запрещено использование данного ПО для доменных зон .ru, .su и .рф.
> 
> @limonteКак это связано с [лицензией MIT, под которой опубликован ваш код](https://github.com/sweetalert2/sweetalert2/blob/main/LICENSE) ?

Он пока еще не придумал, занят был удалением своих и чужих комментариев.

**Comment by zavants** [comment]
There are many Russians who make an honest living and do not agree with the war. 
But it is easier to put them all in the same bag and punish them in this way, no matter if they agree or not, just because they live in Russia and speak Russian they are guilty of their sin.

It is exactly these attitudes that keep the hatred and wars alive.

**Comment by limonte** [comment]
You live in a [state sponsor of terrorism](https://www.europarl.europa.eu/news/en/press-room/20221118IPR55707/european-parliament-declares-russia-to-be-a-state-sponsor-of-terrorism). I don't want my software to be used for websites of a state sponsor of terrorism, simple as that.

What you said about the Russian language is a straight lie. I speak Russian, 60% of Ukrainians speak Russian as their primary language, and I have absolutely nothing against the language.

**Comment by luncan987** [comment]
@limonte 
As a danish, I DO NOT support the war, which I hope to be end hopefully soon! No child should raise with war memories! 
I really hate war! And we had enough of it! 

Also as you mentioned, if you have moral you would do the same for the countries who aggression others! Just an example of Iraqi war. Google it and read of what the US and the alllies has done, then talk here about moral. More than 1.2 civilians dead for a simple lie! They stole, raped and killed like never before. And you talk about moral? 

In the end, if you hate any other nation, keep it for yourself, don't spread hate, but spread love and be an example!
God dag!

**Comment by Whiskasin** [comment]
> You live in a [state sponsor of terrorism](https://www.europarl.europa.eu/news/en/press-room/20221118IPR55707/european-parliament-declares-russia-to-be-a-state-sponsor-of-terrorism). I don't want my software to be used for websites of a state sponsor of terrorism, simple as that. You can't dictate rules for my software, but you can ignore them and you probably will :) That's alright, but keep your moral teachings for your government.
> 
> What you said about the Russian language is a straight lie. I speak Russian, majority of Ukrainians speak Russian as their primary language, and I have absolutely nothing against the language.

stupid degenerate, who is for collective guilt, like the Nazis. Shove your app up your ass.

**Comment by limonte** [comment]
> > The usage of this software for .ru, .su, and .рф domain zones is now prohibited
> 
> @limonte How does this relate to the [MIT license under which your code is published](https://github.com/sweetalert2/sweetalert2/blob/main/LICENSE)?

@bezumkin https://github.com/sweetalert2/sweetalert2/issues/2573

**Comment by dragonfly-net** [comment]
> You live in a [state sponsor of terrorism](https://www.europarl.europa.eu/news/en/press-room/20221118IPR55707/european-parliament-declares-russia-to-be-a-state-sponsor-of-terrorism). I don't want my software to be used for websites of a state sponsor of terrorism, simple as that. You can't dictate rules for my software, but you can ignore them and you probably will :) That's alright, but keep your moral teachings for your government.
> 
> What you said about the Russian language is a straight lie. I speak Russian, majority of Ukrainians speak Russian as their primary language, and I have absolutely nothing against the language.

Main sponsor of terrorism is USA. All last wars sponsored by usa

**Comment by dragonfly-net** [comment]
You've just been brainwashed by propaganda. And every day Ukraine shoots exactly at civilians, schools, kindergartens, hospitals.

**Comment by Boglik** [comment]
Вот что я хочу сказать. Ни один программист в России, ни в каком состоянии, в отличии от украинского, не добавит гимн РОССИИ, чтобы насолить морально и как то этически украинским пользователям. Добавить гимн украины, чтобы потом оно пело сколько? 30 секунд до обнаружении, а потом просто вычислить за 3 щелчка проблемный код, и написать яростный пост сюда? Вы находитесь в наркотическом, алкогольном или каком состоянии? Вы адекватный? Все в порядке? Своими действиями было сделано следующее:
1) Дискридитирована система "sweetalert2". С приходом Cursor написать такую вообще не проблема. и даже лучше.
2) Дискридитировано отношение к Украине как к государству, а её жители переходят в разряд кого после этого? Программисты в Украине, которые адекватные,  из-за тебя попадают под подозрение в неадекватности. 

Насколько нужно быть недалеким, злым, ущербным, агрессивным, ненавидящим себя, чтобы так делать?
Ты же конченный. Ты упоролся на фоне того, что тебе орешником прилетело настолько, что вместо какого мифического возвеличивания в своей тупой башке, которая не способна к программированию, ты теряешь уважение даже среди своих коллег. 

После твоей выходки у меня возникает желание не код писать, не сотрудничать, обмениваясь опытом, а взять военный билет и пойти в военкомат, записаться по контракту и отдельным пунктом ОТ СЕБЯ написать - что пока до киева не дойду, с армии не уйду. 
А кой киев. До Львова нах.

Ты к этому стремишься, тупое ты создание? Ты этого хочешь и ты на это провоцируешь  и толкаешь обычный, русский народ? Помни, если поднять Русского Ивана с печи, то пизда вам. 

Ебаная тупая черепашка, проживающая в Финляндии. Ты сам собственноручно уничтожил свой же проект. 
Занавес. Без комментариев.

**Comment by limonte** [comment]
Ты чё там, ваня, прибухнул? Чё то погнал конкретно 😆

**Comment by limonte** [comment]
Сегодня праздник, круглую цифру отмечаем, а ты так гонишь.

<img src="https://github.com/user-attachments/assets/8a758fa2-dade-415b-ad8c-632e211b5161" width="200">

**Comment by Boglik** [comment]
Ты угораешь? Какого хера у тебя в коде ЭТО? Я тебе скриншоты могу прислать, ибот ты животное тупое вставляешь гимн страны которую назвать можно с натяжкой. Её между собой делять Россия и США причем в открытую. Подтерись своим гимном, а репорты, чтобы твой говнокод убрали из всех источников - будут.

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/a804f4b0-f68a-4752-8c2c-65473cf39552" />
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/639afe51-f32f-4c2e-b841-49ac5ac9aec6" />
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/a26c242f-9e10-4620-aafa-37a275b62aae" />
<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/ec9d887d-b395-4550-b835-bc0f1f6b7d29" />

**Comment by limonte** [comment]
Ваня, проспись, ваня. Это уже 3 года в коде. Ты опоздал на вечеринку ваня.

**Comment by Boglik** [comment]
3 года страну в открытую делят. Я не скрываю напрямую. Вас нахрен делят, страну твою Украину делят. К целям СВО теперь прибавился денежный интерес потому что много затрат произошло.  
А ты гимн добавляешь? Вот так ты развлекаешься 3 года? Нормально ты живешь. Ты проспал свою страну ментально и морально. Хуже того ты в глазах людей обсираешься как не в себя. 
3 года твоим продуктом никто не пользуется ,потребовалось мне скачать библиотеку и пожалуйста!  
Всем 3 года было плевать на то, что там происходит. 10 человек скачало, 1 человек гневнопост написал. 
Тоже мне, достижения. 
Засунь их сейчас туда, сам знаешь куда. 
Ни чести, ни морали, ничего у тебя нет. Абсолютно.

**Comment by limonte** [comment]
у меня есть твоя порвавшаяся жопа, это и была самоцель.

**Comment by Boglik** [comment]
Ты себе испортил рейтинг, статус, доверие РАДИ ЭТОГО?
Вы там с/на украине все такие упоротые? Знаю я одного президентика, который из-за упертости уничтожил своими приказами 2 ляма людей. Уничтожил все. Вообще все. Всю страну просрал. 

Ты же просрал свой проект, свою репутацию и свою значимость. 
Никто не будет  иметь с тобой дело если ты закладчик

**Comment by limonte** [comment]
Походу сильно тебе досталось от клиентов что твоя жопа так порвалась 😄 Че им не понравился перформанс? Не оценили? 😄

**Comment by aseleznev-powerbee** [comment]
> У меня есть твоя порвавшаяся жопа, это и была самоцель. Таков путь.

Срезу видно Квалифицированного IT-Специалиста из Свободной Европейской Страны.

Я собственно, присоединюсь к "Ване". 24го февраля я сам был сильно против этой войны. Я был первый на сваливание из страны и походы на митинги.
Спустя неделю когда я насмотрелся на поведение этих "несчастных обиженных и ни в чём не виновных" наших братьев, я полностью поменял своё мнение.

**Comment by limonte** [comment]
Дорогие друзья из россии, я выпилил гимн Украины из последних версий. Смело обновляйтесь.

Больше таких закладок не будет, честно слово 😄 

Вы спросите почему? Пытаюсь вот поправить свою репутацию которая была просто уничтожена после того как 0.1% юзеров перестали пользоваться плагином 😆  а может и того меньше юзеров в самой большой стране мира, я хз.

**Comment by Boglik** [comment]
О, великий limonte — мессия «протествара», чья карьера рухнула не от санкций, а от собственного кода, который ломает сборки, позорит DevOps и заставляет целые компании бежать к нейтральным форкам вроде sweetalert2-neutral 

Ты, видимо, всерьёз возомнил себя силой, способной «наказать» миллионы русскоязычных пользователей за грехи, в которых они не виноваты. Включил гимн Украины при любом navigator.language, содержащем ru 
 — гениально! А потом, когда твой «акт сопротивления» начал ломать логины в Bitwarden 
, блокировать админки в PHPMaker 
 и вызывать панику у QA-инженеров по всему миру, ты вдруг решил: «ой, а давайте я теперь честно слово больше не буду» 😄

Серьёзно? Ты испортил доверие к open-source, превратил библиотеку для модальных окон в политический манифест 
, а теперь улыбаешься, будто это была шутка на уровне «а у меня в коде Easter Egg!». Только вот твой «Easter Egg» звучал как гимн чужой страны на чужом сайте — без согласия, без опции отключения, без уважения к пользователям.

И да, твоя «самая большая и могущественная страна мира» — это, видимо, твой собственный эго-репозиторий, где ты — и царь, и суд, и прокурор. Жаль только, что в реальном мире твой код уже не обновляют, а форкают, чтобы избавиться от твоей «бусификации» — ведь настоящая сила не в том, чтобы вставить протест в npm, а в том, чтобы писать код, которому доверяют, а не от которого избавляются.

Так что наслаждайся своей «репутацией» — она теперь звучит громче любого гимна: как предупреждение новичкам:
_Не будь как limonte — не превращай свою библиотеку в мусорную корзину идеологии»_
