### ISSUE TITLE
npm "latest" tag points to 8.19.1

### ISSUE THREAD

**Issue by kai-dorschner-twinsity** [sweetalert2/sweetalert2#2565]
Attention: This is not a bug report in the code itself but in your release pipeline:
I looked for updates in my project and `npm outdated` reported sweetalert2 as outdated.

Mind this screenshot:
![image](https://user-images.githubusercontent.com/92744645/203549110-314f4a46-3f3b-4165-8bc1-b926c9ad0009.png)

After investigating I figured out the latest tag on npm points to an old version (`8.19.1`) instead of the newly built [11.6.12](https://www.npmjs.com/package/sweetalert2/v/11.6.12)

See npmjs.com for reference:
https://www.npmjs.com/package/sweetalert2?activeTab=versions

Cheers :)

**Comment by limonte** [comment]
oops, thanks for reporting!

**Comment by limonte** [comment]
fixed, thanks again for heads up!

**Comment by kai-dorschner-twinsity** [comment]
Great work guys :) Keep it up!
