### ISSUE TITLE
Anthem

### ISSUE THREAD

**Issue by vmstukalov** [sweetalert2/sweetalert2#2568]
## Current behavior

The Ukrainian anthem turns on and the site freezes.

## Expected behavior

The Ukrainian anthem is turned on and the site should not freeze.

## Live demo 

I already modified script, because it freezes my website.

**Comment by limonte** [comment]
https://github.com/sweetalert2/sweetalert2#important-notice-about-usage-of-this-software-for-ru-su-and-%D1%80%D1%84-domain-zones

<img width="877" alt="CleanShot 2022-11-28 at 16 04 00@2x" src="https://user-images.githubusercontent.com/6059356/204296916-d2217cbd-c0de-4c21-95bc-8a1c918f0c90.png">
