### ISSUE TITLE
sweetalert2 v11.4.9 and above contains hidden functionality

### ISSUE THREAD

**Issue by luizcmarin** [sweetalert2/sweetalert2#2574]
alert from github.   Please, update.

https://github.com/advisories/GHSA-qq6h-5g6j-q3cm

**Comment by limonte** [comment]
Good day Luiz,

As a consequence of the illegal war in Ukraine, SweetAlert2 behaves differently for websites in `.ru`, `.su`, and `.рф` domain zones.

Here's the README section about that: https://github.com/sweetalert2/sweetalert2#important-notice-about-usage-of-this-software-for-ru-su-and-%D1%80%D1%84-domain-zones

<img width="1065" alt="CleanShot 2022-12-12 at 10 16 26@2x" src="https://user-images.githubusercontent.com/6059356/206995146-7c9d7906-f993-4b2d-92b4-928943a94b9d.png">
