### ISSUE TITLE
Regression? Relative positioning recipe not working

### ISSUE THREAD

**Issue by fredcallaway** [sweetalert2/sweetalert2#2575]
## Current behavior

As far as I can tell, there is no way to position an alert relative to another div.

## Expected behavior

I expect the provided recipe to position the alert in the bottom right corner of the parent div

https://sweetalert2.github.io/recipe-gallery/toast-with-custom-target.html

## Live demo 

This is directly copying the html, css, and js from the recipe

https://codepen.io/fredcallaway/pen/LYropgd

**Comment by limonte** [comment]
CSS specificity is causing this. This will help:

```diff
.position-absolute {
-  position: absolute;
+  position: absolute !important;
}
```

I've also updated https://sweetalert2.github.io/recipe-gallery/toast-with-custom-target.html

Thanks for reporting!

**Comment by fredcallaway** [comment]
Awesome, thanks for the quick solution!
