### ISSUE TITLE
How to stop auto focus on text input?

### ISSUE THREAD

**Issue by Kaktushose** [sweetalert2/sweetalert2#2578]
When opening an alert with text input, the text input gets auto focused causing android clients to automatically opening the keyboard, which blocks part of the view. 

Using https://sweetalert2.github.io/#focusDeny did not fix this issue

**Comment by limonte** [comment]
https://sweetalert2.github.io/#inputAutoFocus

**Comment by rhyudek1** [comment]
@limonte I'm trying that option but it doesn't work
