### ISSUE TITLE
sweetalert2 >= v11.4.9 and above contains hidden functionality

### ISSUE THREAD

**Issue by theengineer0101** [sweetalert2/sweetalert2#2582]
## Current behavior

When running the command npm audit 
sweetalert2 v11.4.9 and above contains hidden functionality - https://github.com/advisories/GHSA-qq6h-5g6j-q3cm
## Expected behavior

This is not seen as hidden functionality which is seen as a vulnerability
## Live demo 

Just run the npm audit on any version >=11.4.9

**Comment by limonte** [comment]
duplicate of #2574
