### ISSUE TITLE
Warning 'sweetalert2'. CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by barrymolavenet** [sweetalert2/sweetalert2#2583]
Hi

I upgraded the angular 13 to 14 but when I run my project there is a warning.

Warning `sweetalert2`. CommonJS or AMD dependencies can cause optimization bailouts.

Can you help me to remove the warning in my angular project?
Thank you.

**Comment by limonte** [comment]
duplicate of #2467
