### ISSUE TITLE
takes time to pop up

### ISSUE THREAD

**Issue by kienth** [sweetalert2/sweetalert2#2584]
## Current behavior

After a couple of minutes of break, when I get back to my PC, when I click the button with sweetalert2, it takes time to popup, while in sweetalert is not.

## Expected behavior

It must be popup less than a second because I only showing the sweetalert without any process of data etc.

**Comment by zenflow** [comment]
Your live demo isn't a live demo. Please use the live demo template to create a **minimal** reproduction of the issue: https://codepen.io/limonte/pen/JjoWRMx

What's the difference between the popups that show immediately vs the one that takes a long time?

**Comment by limonte** [comment]
1. you're not using the latest version according to the attached screencast
2. when reporting issues please follow the issue template
