### ISSUE TITLE
Change theme dinamically  

### ISSUE THREAD

**Issue by Belingheri** [sweetalert2/sweetalert2#2586]
## New feature motivation

I use the new bootstrap `5.3` than can switch in easy way to dark and light mode, in the moment that it switch i want to switch sweet alter theme from light to dark or vice-versa.

## New feature description

A new option like 
``` js
 Swal2.fire({
    theme:"dark"
})
```

The theme values can be one of [these](https://github.com/sweetalert2/sweetalert2-themes#available-themes)

**Comment by limonte** [comment]
I think this will cover your use-case: https://github.com/sweetalert2/sweetalert2/issues/2469#issuecomment-1219975933
