### ISSUE TITLE
Icon not working

### ISSUE THREAD

**Issue by Ben-Mananya** [sweetalert2/sweetalert2#2588]
Swal.fire({
            title: 'Success',
            confirmButtonText: 'OK',
            icon: 'success',
          }).then( result => {
            window.location.href = '/user';
              });
            
If I use icon success, error is not working but when I use icon warning is working

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
