### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by taozhiyu** [sweetalert2/sweetalert2#2593]
## Current behavior

Importing Swal using typescript and calling `showLoading()` (no arguments) gives an error

## Expected behavior

Pass type test

The code here:

https://github.com/sweetalert2/sweetalert2/blob/49ecc95aad3fc5e0e9fe40144ef201c6eacee165/sweetalert2.d.ts#L183

 probably be

``` diff
-    function showLoading(buttonToReplace: HTMLButtonElement | null): void
+    function showLoading(buttonToReplace?: HTMLButtonElement): void
```

## Live demo 

typescript playground:

https://www.typescriptlang.org/zh/play?#code/JYWwDg9gTgLgBAZQO4EMA2cBmUIjgIgGckBTEmdE2AJnwG4AoB5dAOkIAsIkAZCFACbAAdgHMAFAEomQA

> BTW, consider using [form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) as an issue template, it would be more convenient

**Comment by limonte** [comment]
Thank you for reporting this issue @taozhiyu  🙌 

> BTW, consider using form as an issue template, it would be more convenient

Done, thanks 👍
