### ISSUE TITLE
Зачем блокировать работу страницы?

### ISSUE THREAD

**Issue by pravosleva** [sweetalert2/sweetalert2#2594]
https://github.com/sweetalert2/sweetalert2/blob/49ecc95aad3fc5e0e9fe40144ef201c6eacee165/src/SweetAlert.js#L261

**Comment by pravosleva** [comment]
Если бы автор не был долбоебом, он сделал бы то же самое, но не блокируя действия пользователя.

**Comment by limonte** [comment]
https://github.com/sweetalert2/sweetalert2/issues/2560#issuecomment-1323320761 😄

**Comment by pravosleva** [comment]
https://github.com/lofcz/sweetalert2-neutral

Не благодари )

![success-3-lock-stock-and-two-smoking-barrels](https://user-images.githubusercontent.com/19761493/214451507-5567ecfa-e38e-482a-8824-c73224b82cd9.gif)
