### ISSUE TITLE
Security alert Github - sweetalert2 v11.4.9 and above contains hidden functionality #119

### ISSUE THREAD

**Issue by gonzalochief** [sweetalert2/sweetalert2#2596]
### Current behavior

I got this dependency alert this week. There is a hidden functionality that needs to be fixed

sweetalert2 v11.4.9 and above contains hidden functionality #119

sweetalert2 versions 11.4.9 and above are vulnerable to hidden functionality that was introduced by the maintainer. The package outputs audio and/or video messages that do not pertain to the functionality of the package and is not included in versions 11.0.0 - 11.4.8.

### Expected behavior

Fix bug

### Live demo !!! THIS FIELD IS REQUIRED !!!

sweetalert2 versions 11.4.9 and above are vulnerable to hidden functionality that was introduced by the maintainer. The package outputs audio and/or video messages that do not pertain to the functionality of the package and is not included in versions 11.0.0 - 11.4.8.

**Comment by limonte** [comment]
duplicate of #2574
