### ISSUE TITLE
Sweetalert2 Tab Behaviour

### ISSUE THREAD

**Issue by JoelHiller** [sweetalert2/sweetalert2#2597]
Im currently trying to tab between Inputs inside my SweetAlert2. I have a custom Element that I load inside and i want to be able to tab between the loaded inputs of the table.

My Popup: 

`return new Promise((resolve) => {
            Swal.fire({
                title: '<strong>Neue Buchung</strong>',
                html:
                    '<add-coffee-for-all-list></add-coffee-for-all-list>',
                showCancelButton: true,
                confirmButtonText:
                    'Speichern',
                confirmButtonAriaLabel: 'Thumbs up, great!',
                cancelButtonText:
                    'Abbrechen',
                width: "600px",
                cancelButtonAriaLabel: 'Thumbs down',
                confirmButtonColor: '#33475D',
                cancelButtonColor: '#F18286',
                allowEnterKey: true,
                allowEscapeKey: true,
                focusConfirm: false,
                focusCancel: false,
                customClass: {
                    confirmButton: `confirm`,
                    cancelButton: `cancel`,
                }
            })
        })`

i tried to use Tabindex, but it only focuses the three Sweetalert2 Buttons (Exit, Confirm and Cancel) and not the loaded Element Child Inputs.

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
