### ISSUE TITLE
Wave errors in sweetalert popup

### ISSUE THREAD

**Issue by AMITHATHAMPY** [sweetalert2/sweetalert2#2599]
Errors showing in sweet alert popup when checked using wave tool for accessibility testing

![image](https://user-images.githubusercontent.com/63200139/216965811-e5280be6-4efa-4d73-b612-d9e8300b6074.png)

**Comment by limonte** [comment]
thank you for reporting @AMITHATHAMPY I will handle this 👍

**Comment by limonte** [comment]
It seems that the issue is on the Wave plugin side, it's reporting issues for elements that are hidden for screenreaders with `display: none`.
