### ISSUE TITLE
Appearing input file field. (I did not put)

### ISSUE THREAD

**Issue by tiagocaus** [sweetalert2/sweetalert2#2600]
### Current behavior

An input file field is appearing. But I didn't.

### Expected behavior

Appear without input file field.

### Live demo !!! THIS FIELD IS REQUIRED !!!

Code:

```
Swal.fire({
    text: 'Link de indicação copiado, só colar onde deseja usando CTRL+V',
    icon: 'warning'
})
```

Image: https://i.imgur.com/q5IN6ID.png
![image](https://user-images.githubusercontent.com/11445757/218546883-e7fc4988-4cb9-46db-803e-b241635a2ae6.png)

**Comment by limonte** [comment]
What operating system and browser are you using?

**Comment by limonte** [comment]
comment with more details for reopening this issue
