### ISSUE TITLE
Dont embed politics in this or any opensource project!

### ISSUE THREAD

**Issue by i-engy** [sweetalert2/sweetalert2#2601]
### New feature motivation

All wars happened so far, ongoing and will happen in future.

### New feature description

If you start blocking websites based on domain names, sooner than later this project will become useless to whole world. What about all the wars and aggression USA and its European allies has started over last few decades in name of freedom(Oil) and WMD(OIL). Oppose governments but don't impose this "blocking navigation" on common people.

Just create things. There are already enough people doing the "destruction" all over the world. Its  like woke bullshit all over again.

**Comment by limonte** [comment]
Don't tell me what to do with my software.

**Comment by HiggsWRX** [comment]
The audacity. @i-engy don't like his library just use another.
