### ISSUE TITLE
Calling other Swal - Cannot read properties of undefined (reading 'confirmButton')

### ISSUE THREAD

**Issue by Tragio** [sweetalert2/sweetalert2#2607]
### Current behavior

Thank you for your amazing work!! 🙂 I'm not sure what I'm doing wrong.

I have a Swal select, and when "Other Reason" is selected I'm calling another Swal. However, I get an error.

In reproduction select "Other Reason" and an error will appear on the console.

![CleanShot 2023-03-22 at 09 32 29](https://user-images.githubusercontent.com/5109593/226860757-562e4304-f7c8-406e-9d88-a898ee896b77.jpg)

### Expected behavior

Resolve the input validator without any error.

### Live demo !!! THIS FIELD IS REQUIRED !!!

https://codepen.io/Tragio/pen/wvEYOxz?editors=1111

**Comment by limonte** [comment]
Thanks for the kind words!

`inputValidator` is not designed to call other Swal, but to prevent closing the current one and show the validation message if needed.

You need to refactor your code and call another Swal outside of `inputValidator`
