### ISSUE TITLE
Update Swal and implementing new params

### ISSUE THREAD

**Issue by gernet-master** [sweetalert2/sweetalert2#2611]
```
swal.fire({
      icon: 'warning',
      text: 'test'           
});

let timerInterval
  Swal.update({
      title: 'Auto close alert!',
      html: 'I will close in <b></b> milliseconds.',
      timer: 2000,
      timerProgressBar: true,
      didOpen: () => {
          Swal.showLoading()
          const b = Swal.getHtmlContainer().querySelector('b')
          timerInterval = setInterval(() => {
              b.textContent = Swal.getTimerLeft()
          }, 100)
      },
      willClose: () => {
          clearInterval(timerInterval)
      }
  })
```

Errors:
SweetAlert2: Invalid parameter to update: timer
SweetAlert2: Invalid parameter to update: timerProgressBar
SweetAlert2: Invalid parameter to update: didOpen

**Comment by zenflow** [comment]
@gernet-master It is not usually a good idea to completely ignore the issue templates ........

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
