### ISSUE TITLE
Two "X" close buttons when showCloseButton true

### ISSUE THREAD

**Issue by tim330i** [sweetalert2/sweetalert2#2618]
### Current behavior

I am using SweetAlert2 from a CDN -

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11" ></script>

The code to create the alert is - 

```
  Swal.fire({
  title: '<strong>The Fundraiser is Over</strong>',
  icon: 'info',
  html:
  'The fundraising store for '+ urlParams.get('redirect') +' is close, BUT you can continue to shop at the Meadow Farms store.' + 
  '<br><br>' +
  'If this is your fundraising store, <a href="https://portal.meadowfarms.com" ><strong>SIGN UP</strong></a> for a new fundraiser to reactivate your store',
  showCloseButton: true,
  showCancelButton: false,
  focusConfirm: false,
  confirmButtonText:
    'Go Shopping!'
})
```

I have showCloseButton set to true.  The Alert shows two X buttons to close the alert -

![image](https://user-images.githubusercontent.com/17716168/233444799-3f1bed23-ee5a-48f5-9ded-00c289b92925.png)

### Expected behavior

There should only be one X to close the Alert

### Live demo !!! THIS FIELD IS REQUIRED !!!

https://shop.meadowfarms.com/meadow-farms-fundraising-100105?redirect=test

**Comment by limonte** [comment]
<img width="264" alt="CleanShot 2023-04-20 at 23 17 16@2x" src="https://user-images.githubusercontent.com/6059356/233478431-d886f9ee-9897-42cd-bd80-d8595900900b.png">

**Comment by tim330i** [comment]
Oh. I didn't realize there was a CSS conflict (I think that is what you're saying).

Thank you!
