### ISSUE TITLE
Syling broken after specificity changes

### ISSUE THREAD

**Issue by knd775** [sweetalert2/sweetalert2#2628]
### Current behavior

The following change appears to have broken styling: https://github.com/sweetalert2/sweetalert2/pull/2627

It allows the alerts to be affected by site styles in a way that was not an issue previously. In our case (and the example below), Bulma styles break the alert.

### Expected behavior

Styling to not break between minor releases 😄

### Live demo !!! THIS FIELD IS REQUIRED !!!

https://codepen.io/knd775/pen/yLRWwrV/1e941383478598b18d3578e667d38566

**Comment by wazzac** [comment]
Same issue here thanks.

Popup with drop-down select and `Confirm` `Cancel` button has broken styling. 
Worked at v11.7.8 ✅ 
Broken at v11.7.9 ⚠️ 

Thank you... 👋🏼

**Comment by deepydee** [comment]
It brokes at least .swal2-title and .swal2-title. If I change from :where to :is it works.
![alert](https://github.com/sweetalert2/sweetalert2/assets/35696895/8d11fca9-5969-4036-9bb9-4f97fb368171)

**Comment by limonte** [comment]
Sorry fellas for introducing this issue, I'm on it, the fix is coming very soon 🚀

**Comment by ArkaitzSKR** [comment]
I have same problem but on local work perfectly and on production no.

Production 
<img width="520" alt="irudia" src="https://github.com/sweetalert2/sweetalert2/assets/62140712/6525f4a7-5ec0-41b0-a819-6e9f29d9143f">

Local
<img width="533" alt="irudia" src="https://github.com/sweetalert2/sweetalert2/assets/62140712/3e50ec68-51ea-4554-ac60-412b0d6cfec4">

**Comment by limonte** [comment]
Should be good now, please check if everything is good on your side.

Thanks for reporting everyone 🙌
