### ISSUE TITLE
For complete beginners

### ISSUE THREAD

**Issue by diomed** [sweetalert2/sweetalert2#2630]
### New feature motivation

It would be nice if there was real life example of sweetalert2 embeded in examples page section

### New feature description

It would display how to use it for complete beginners: main thing, how to call a script in HTML, which IMO lacks proper explanation.
People who start wanna see how exactly is this applied via html

### New feature implementation

https://codepen.io/diomed/pen/WNaqXLN

**Comment by limonte** [comment]
Thank you for your feedback, but I don't think our docs is the right place for explaining how event handlers work.

**Comment by diomed** [comment]
maybe a wiki thread?
