### ISSUE TITLE
You bastards, why are you spoiling the plugin and adding Ukrainian songs

### ISSUE THREAD

**Issue by sh1man999** [sweetalert2/sweetalert2#2631]
Remove this shit plugin

**Comment by limonte** [comment]
Why are you so angry? 😆 Ukrainian songs are beautiful 🇺🇦

**Comment by temez** [comment]
> Why are you so angry? 😆 Ukrainian songs are beautiful 🇺🇦

This is not funny. I am Ukrainian, speak Russian, why should i listen this every time?

**Comment by limonte** [comment]
> > Why are you so angry? 😆 Ukrainian songs are beautiful 🇺🇦
> 
> This is not funny. I am Ukrainian, speak Russian, why should i listen this every time?

Just don't visit `.ru`zzian websites and you'll be fine.
