### ISSUE TITLE
Swal not defined

### ISSUE THREAD

**Issue by Bashamega** [sweetalert2/sweetalert2#2632]
### Current behavior

Hello
I love using the website and I added it to all me websites. I imported it from cdn.jsdeliver.net that I found on the website.
It was working until today it gave me Swal not defined, so I checked the lib and it give me a _**This site can’t be reached**_ error.
This is the link that I imported it from: 
https://cdn.jsdelivr.net/npm/sweetalert2@11

### Expected behavior

It should work

### Live demo !!! THIS FIELD IS REQUIRED !!!

This is one of the websites the problem occurred in [https://educpk.github.io/](https://educpk.github.io/), it should open a popup when you click login/signup.

**Comment by limonte** [comment]
https://educpk.github.io/ works fine, it was probably some issue on jsdelivr side.

**Comment by Bashamega** [comment]
It is still not solve.
It should open a popup when you click on log in.
![problem](https://github.com/sweetalert2/sweetalert2/assets/110662505/abc6013c-0a9e-4fe2-8117-326605de0b24)
