### ISSUE TITLE
vulnerablility 11.4.9

### ISSUE THREAD

**Issue by alex5956** [sweetalert2/sweetalert2#2637]
### Current behavior

hello i have this problem with sweetalert2 , vulnerabilities . so the message is:"sweetalert2  >=11.4.9
sweetalert2 v11.4.9 and above contains hidden functionality - https://github.com/advisories/GHSA-qq6h-5g6j-q3cm
fix available via `npm audit fix --force`
Will install sweetalert2@11.4.8, which is a breaking change
node_modules/sweetalert2"
could you fix it ? it's the 11.4.9
Cordially

### Expected behavior

fix the vulnerability 11.4.9 version

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/limonte/pen/JjoWRMx

**Comment by jupmorenor** [comment]
Check #2574
Try the latest 11.7.12 and if it still persist you can ignore the warning (maybe) securely.

**Comment by alex5956** [comment]
ok it's done thnaks you

**Comment by alex5956** [comment]
hello could you fix the security problem for the lastest version of sweet-alert2 ?
