### ISSUE TITLE
Protestware Implementation

### ISSUE THREAD

**Issue by robertmarney** [sweetalert2/sweetalert2#2643]
### Current behavior

Users using the latest release get an NPM Security Vulnerability warning during build, breaking CI  / CD processes in some cases.

The protest should be paused until such time that the main dependency manager treats the package as safe.

For my projects I am locking in 11.4.8 not because we are effected by the protest ware but because we must to avoid failing CI. This behavior will likely be followed by both people in .ru domains as well as people who utilize automatic CI / CD. If the bulk of users make the same decisions you will lose a large group of people who might be able to improve the library or highlight where there are legitimate issues.

### Expected behavior

The protest should be paused until such time that the main dependency manager treats the package as safe.

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/limonte/pen/JjoWRMx

**Comment by limonte** [comment]
Thanks for your input.
