### ISSUE TITLE
Width property not keeped when using promise as inputValue

### ISSUE THREAD

**Issue by dansleboby** [sweetalert2/sweetalert2#2653]
### Current behavior

When utilizing a promise as the inputValue for SweetAlert2, I'm noticing some inconsistent behavior in terms of the width property of the modal window. Initially, the window appears at the correct, specified width, but once the promise has been resolved and the value is loaded, the modal window seems to revert to its original width, not maintaining the width that was set initially. This behavior is unexpected as I anticipated that the modal window would keep the initial set width throughout its lifecycle, even when dealing with async actions such as promise resolution.

### Expected behavior

The expected behavior would be for the modal window to keep the custom width specified initially, even after the promise used for inputValue has been resolved and the value loaded into the modal. The width of the modal should not be affected by the resolution of a promise or any asynchronous actions.

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo: https://codepen.io/dansleboby/pen/WNYMMvG

**Comment by limonte** [comment]
your demo works fine:

![CleanShot 2023-07-14 at 11 33 09](https://github.com/sweetalert2/sweetalert2/assets/6059356/313c3ecb-f3ed-4612-ad03-89401d165dff)

**Comment by dansleboby** [comment]
It inconsistent I test multiple browser on browserstack (clean windows install, no plugin) first time Edge and Firefox are ok, rerun it and it was not good 

https://screenpal.com/watch/c0i2IGVg7RS

**Comment by limonte** [comment]
interesting, can reproduce in Safari, but not in Chrome, thanks for clarifying!

**Comment by dansleboby** [comment]
I narrow down the issue

If I use text input it fine, and if I remove this block no issue:

https://github.com/sweetalert2/sweetalert2/blob/674916a1c449b1c99c60e1c462693445decc2f3d/src/utils/dom/renderers/renderInput.js#L266-L283

**Comment by limonte** [comment]
yup, this looks like the source of the issue. I'll tackle it next week, but if you maybe have time to create a PR, I'd be happy to review, thanks again for your help 🙌

**Comment by dansleboby** [comment]
Also I found if hit "cancel" or click ouside to close the popup while loading you get an error in the console

![image](https://github.com/sweetalert2/sweetalert2/assets/4716382/3a9e3b46-2ec2-4977-a89e-3d8e00416140)

**Comment by limonte** [comment]
Thank you once again @dansleboby for reporting, investigating, and not giving up after I closed the issue 😆

**Comment by limonte** [comment]
> Also I found if hit "cancel" or click ouside to close the popup while loading you get an error in the console
> 
> ![image](https://user-images.githubusercontent.com/4716382/253599158-3a9e3b46-2ec2-4977-a89e-3d8e00416140.png)

Forgot about this comment, this is now also handled 🙌
