### ISSUE TITLE
check overflow-y before padding-right on tag body

### ISSUE THREAD

**Issue by not6248** [sweetalert2/sweetalert2#2663]
### New feature motivation

to fix the website page shifting problem when used in conjunction with

```
body {
   overflow-y: scroll;
}
```
Now, when using SweetAlert2, it will
padding-right as appropriate to replace the position of the website page scrollbar to make the page not move e.g. (padding-right: 12px;)
And when the page has content that fits on the website page (no slider)
SweetAlert2 will deactivate. padding-right

But the problem is, if I use
```
body {
    overflow-y: scroll;
}
```
The bootstrap modal will know that I've implemented overflow-y: scroll; to keep the slider open at all times. Even if the content fits on the website page.
Bootstrap modal will add padding-right in all cases when using overflow-y: scroll;

But SweetAlert2 will disable it. padding-right when content fits on a website page when SweetAlert2 is inactive padding-right
will cause the page to move because scrollbars are left open with overflow-y: scroll; at the body

may make it default
Alternatively, true false can be selected to cause padding right in all cases regardless of scrollbar or content.
```
 if (document.body.scrollHeight > window.innerHeight) {
    // add padding so the content doesn't shift after removal of scrollbar
    previousBodyPadding = parseInt(window.getComputedStyle(document.body).getPropertyValue('padding-right'))
    document.body.style.paddingRight = `${previousBodyPadding + measureScrollbar()}px`
  }
```
### New feature description

Make SweetAlert2 check for overflow like that of
Modal Bootstrap to keep the website page from moving.

**Comment by limonte** [comment]
thanks for reporting @not6248 

could you provide a live demo to demonstrate the issue? here's the template: https://codepen.io/limonte/pen/JjoWRMx

**Comment by not6248** [comment]
การตั้งค่า 
Usage
body {
     overflow-y: scroll;
}
will make the cat move
On pages where the content fits. (can't scroll up and down)
https://codepen.io/not6248/pen/rNoNMQZ

But if the content can scroll up and down padding-right will work normally
https://codepen.io/not6248/pen/YzdzGbX

I currently use the method
 ` if (document.body.scrollHeight > 1)`
to force this operation.

**Comment by limonte** [comment]
thanks for nice report @not6248 🙌
