### ISSUE TITLE
Cannot type in input field if sweetalert trigger in Offcanvas

### ISSUE THREAD

**Issue by jaimefuhr** [sweetalert2/sweetalert2#2667]
### Current behavior

Sweetalert2 11.7.27
Bootstrap 5.3.0-alpha3

I have an Offcanvas with a button that fires a Sweetalert with an Input type of 'text'.   The dialog is shown but the input field is disabled.   

Moving the same button outside of the Offcanvas works as expected.

### Expected behavior

Should be able to type in the Input field if Sweetalert is fired in an offcanvas.

### Live demo !!! THIS FIELD IS REQUIRED !!!

JSFiddle:

https://jsfiddle.net/jaimefuhr/v14qe7rp/4/

**Comment by limonte** [comment]
This issue is similar to https://github.com/sweetalert2/sweetalert2/issues/374

The solution for Bootstrap 5 offcanvas is:

```js
$.fn.offcanvas.Constructor.prototype._initializeFocusTrap = () => ({ activate: () => { }, deactivate: () => { } });
```

proof: https://jsfiddle.net/2fhbyn36/
