### ISSUE TITLE
Does not work on Android 10 

### ISSUE THREAD

**Issue by Digdemk** [sweetalert2/sweetalert2#2668]
### Current behavior

Hello. Popup appears at the bottom of the page on Android 10 devices.

https://github.com/sweetalert2/sweetalert2/assets/70605053/3b4f7ccd-40a5-45ca-b1c7-7b021c533723

### Expected behavior

I am expecting the popup opens as a popup not a text at the bottom of the page.

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/limonte/pen/JjoWRMx

This demo is not working on Android 10 devices too.

**Comment by limonte** [comment]
![CleanShot 2023-09-05 at 17 03 16@2x](https://github.com/sweetalert2/sweetalert2/assets/6059356/70ecd4d7-a761-4164-b336-01595dcd2829)
