### ISSUE TITLE
How to click outside without closing popup

### ISSUE THREAD

**Issue by khanhnam99** [sweetalert2/sweetalert2#2669]
### New feature motivation

How to click outside without closing popup

### New feature description

How to click outside without closing popup

![image](https://github.com/sweetalert2/sweetalert2/assets/575720/1c922a36-f2bd-4ad2-b1ed-fc5c62983b30)

like here https://getbootstrap.com/docs/5.3/components/modal/

![image](https://github.com/sweetalert2/sweetalert2/assets/575720/f304eb70-1edf-475c-aee9-6f69a881d213)

### New feature implementation

How to click outside without closing popup

**Comment by limonte** [comment]
https://sweetalert2.github.io/#allowOutsideClick

**Comment by khanhnam99** [comment]
thanks
