### ISSUE TITLE
I can't show SweetAlert over Native Dialog 

### ISSUE THREAD

**Issue by gzimbron** [sweetalert2/sweetalert2#2672]
### Current behavior

Hello, It's possible to show a SweetAlert  over native Dialog modal?

I was using sweet alert without problems in past with "html" positioned dialogs, adding:
```
.swal2-container {
				z-index: 9999999999999999999999999999999999999999999999999999;
			}
```

But now I'm using native dialog, and sweet modal shot under ntive dialog, I tested to use native dialog over dialog and it works fine.

### Expected behavior

Sweet alert showing "over" native html diablog that invokes Sweet alert

### Live demo !!! THIS FIELD IS REQUIRED !!!

Live Preview
https://codepen.io/gzimbron/pen/zYypMEp?editors=1111

**Comment by limonte** [comment]
The `<dialog>` element is added to the 'Top Layer' of the dom which has its own stacking order (z-index does not affect this -- it is set strictly by the order by which the elements are added)

So, the solution would be to add SweetAlert2 to the `<dialog>` node:

```js
Swal.fire({
  ...
  target: '#dialog'
});
```
