### ISSUE TITLE
Add possibility to disable opacity animation for easier snapshot testing

### ISSUE THREAD

**Issue by yuchiko** [sweetalert2/sweetalert2#2677]
### New feature motivation

I think it will be helpful for developers to have a possibility to disable popup's appearing animation with an option. As an example it could be `disableAnimations` option.

For now I have a special helper in tests to check is modal already fully visible on a screen or not. 

I need this to avoid flacky tests while snapshot testing & I think it will be helpful for everyone, cause right now this animation is hardcoded.

### New feature description

--

### New feature implementation

Add a condition for the rows where the animation is added: 
https://github.com/sweetalert2/sweetalert2/blob/main/src/utils/openPopup.js#L97

**Comment by limonte** [comment]
Hey @yuchiko and thanks for this question. Would [disabling animation](https://stackoverflow.com/a/58773084/1331425) work for your use case?

**Comment by yuchiko** [comment]
@limonte Hey :) Thank you for so fast response.
I testes this approach and looks like no. Because of this line:
`popup.style.setProperty('opacity', '0', 'important')`

https://github.com/sweetalert2/sweetalert2/blob/main/src/utils/openPopup.js#L100

**Comment by limonte** [comment]
thanks for the feedback, I need to think a bit about this.

Out of curiosity, what tool you're using for snapshot testing? Does it allow waiting/sleeping before taking a snapshop&

**Comment by yuchiko** [comment]
Your welcome & thank you for accepting the feedback !

We are using https://percy.io/  for testing & it allows waiting.

But for now we have more than 100+ modals in different tests & looks like it would be easier to remove opacity in all tests without this Waiter.

**Comment by limonte** [comment]
Hello @yuchiko and sorry for the delayed reply.

After upgrading to 11.10.0 you'll be able to mentioned workaround with opacity by doing this:

```js
Swal.fire({
  ...
  animation: false
})
```

**Comment by ctml91** [comment]
@limonte Did this update break the ability to disable animation via the showClass/hideClass backdrop? This is important for queue to work properly, as the first and last item need only one of the animations disabled while `animations: false` disables all animations. 

With the below config, the animations are still shown including the Queue examples shown under the recipe page. 

https://sweetalert2.github.io/recipe-gallery/queue-with-progress-steps.html

```
                showClass: {
                    backdrop: 'swal2-noanimation',
                },
                hideClass: {
                    backdrop: 'swal2-noanimation',
                },
```

**Comment by limonte** [comment]
@ctml91 no, this update isn't affecting `showClass/hideClass`, the linked recipe works well on my side

**Comment by ctml91** [comment]
> @ctml91 no, this update isn't affecting `showClass/hideClass`, the linked recipe works well on my side

Hmm okay thanks. I'm not sure if I have a different expectation of what the `swal2-noanimation` class should be doing. I am trying to stop all animations in between swal popups in a queue.

I'm running on MacOS and have the same experience on chrome and safari, the popup show/hide animation occurs where you see the popup bounce in/out.
