### ISSUE TITLE
Failed to execute 'parseFromString' on 'DOMParser': This document requires 'TrustedHTML' assignment (SweetAlert2/Google Sheets)

### ISSUE THREAD

**Issue by UserNewObject** [sweetalert2/sweetalert2#2678]
Hi, this is the post to my question in Stackoverflow: https://stackoverflow.com/questions/77371988/failed-to-execute-parsefromstring-on-domparser-this-document-requires-trus

I appreciate any help to get this working, I've spent many hours trying.. Thanks.

**Comment by limonte** [comment]
The issue is unrelated to SweetAlert2. SweetAlert2 is using DOMParser and unfortunately providing a parameter to use `element.innerHTML = ''` isn't possible due to https://github.com/sweetalert2/sweetalert2/issues/1926

**Comment by UserNewObject** [comment]
> The issue is unrelated to SweetAlert2. SweetAlert2 is using DOMParser and unfortunately providing a parameter to use `element.innerHTML = ''` isn't possible due to #1926

I'm not taking it as an actual issue, I'm just asking for help to get this working even if it is a workaround as I don't think I would find any help in other place, I read that link you provided but I still confused, is there an actual workaround to make this work for my use case in other way than `element.innerHTML = ''`?
