### ISSUE TITLE
If a Swal dialog is interrupted by a toast, promise never resolves or rejects

### ISSUE THREAD

**Issue by mifi** [sweetalert2/sweetalert2#2681]
### Current behavior

If I `await Swal.fire(...)` because I'm waiting for some user input, but then some other code triggers another `Swal.fire({ toast: true })`, the dialog disappears, and the toast is shown, however the first `Swal.fire`'s returned promise will neither reject nor resolve, so the `await` will just hang forever.

### Expected behavior

I would think that if a toast opens up, cancelling an existing dialog, the promise of the existing dialog should either reject with an error (maybe AbortError) or resolve with `{isConfirmed:false}`.

### Live demo !!! THIS FIELD IS REQUIRED !!!

https://codesandbox.io/s/bold-currying-tztv62

- If you press the dialog button and then press ok within 3 seconds, it will log `{isConfirmed: true}` as expected.
- However if you don't press the dialog button, the toast will show up, removing the dialog, but the dialog's promise is neither rejected or resolved.

**Comment by limonte** [comment]
Hello Mikael and thanks for reporting this!

First of all, the described case is quite a bad UX. As a user, I'd be disappointed if a modal is gone without my action.

But from the technical side, it's a valid point that the previous modal is just gone without its promise being rejected or resolved. That shouldn't happen.

The previous popup is definitely not confirmed, and I'm having trouble deciding it it was dismissed. IMO the dismissal is something that is also the result of a direct user action (clicking cancel or backdrop) or timer.

WDYT if in such cases the swal promise would be resolved with:

```js
{
  isConfirmed: false, 
  isDenied: false, 
  isDismissed: false
}

**Comment by mifi** [comment]
Hey man! thanks for your quick reply.

> The previous popup is definitely not confirmed, and I'm having trouble deciding if it was dismissed. IMO the dismissal is something that is also the result of a direct user action (clicking cancel or backdrop) or timer.

Hmm. Hard to say, but a timer timeout is also not a user action, so if a timer timeout leads to `isDismissed: true`, doesn't it also seem logical that a programmatic dismissal will lead to `isDismissed: true`?

When thinking about it more, I agree it's a quite bad UX. Maybe by default it should not be possible to create a new Swal (or toast Swal) when a modal Swal is already active? Maybe the Swal toast call could just silently return without doing anything, or throw an error (unless a flag like `force: true` is set on the toast call)?

Let me know what you think!

**Comment by limonte** [comment]
Fixed, thank you for reporting @mifi 🙌 

Docs are now also updated to reflect this change: https://sweetalert2.github.io/#handling-dismissals
