### ISSUE TITLE
Performance issue after upgrading from 6.9.0

### ISSUE THREAD

**Issue by No1e** [sweetalert2/sweetalert2#2683]
### Current behavior

I just upgraded sweetalert2 from 6.9.0 to the latest version, and I am seeing strange behavior. 
As soon as swal is shown, some part of my app is stop loading data and updating the page, until swal is closed. As soon as swal is closed, loading continues.

Is this known issue? What could be the issue here?

Thank you so much for helping.

Best regards, 
Nole

### Expected behavior

Swal should not affect other part of app functioning normally.

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/limonte/pen/JjoWRMxs

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
