### ISSUE TITLE
If you have the right to ask I have the right to ask back: Could you update your support from Ukraine to Palestine? 

### ISSUE THREAD

**Issue by sanxofon** [sweetalert2/sweetalert2#2685]
If you have the right to ask I have the right to ask back: 

Could you update your support from Ukraine to Palestine? 

More civilians have died in Palestine in a month than civilian ukranians in more than a year.
Thank you.

**Comment by limonte** [comment]
At least 18 Ukrainians were killed in Hamas attack on Israel.
