### ISSUE TITLE
Please drop your protest ware issue

### ISSUE THREAD

**Issue by zackees** [sweetalert2/sweetalert2#2688]
### Current behavior

Dude, wtf.

Do you not realize the US took over Ukraine during the maiden coup? And then bragged about it?

Do you not realize that US dollars funded the Azov battalion to kill 14k ethnic Russians over 8 years?

Do you not realize Ukraine signed a peace deal with Russia called the Minsk I & II agreements? THEN started slaughtering ethnic Russians in defiance of the peace agreement?

Do you not realize that Ukraine was about to invade the two autonomous zones when Putin swept in?

And now, after hundreds of thousands of Ukrainians died fighting Russia... they are now going to settle for LESS LAND than they had under the Minsk I & II agreements.

This entire war was a money laundering operation from the US tax payers into the coffers of the military-industrial complex.

All those lives lost. And what's crazy is that it was the US that blocked Russian/Ukranian peace.

None of this had to happen. The fact you spiked your program so that now it takes down our non profit website just by including your library in certain places in the world?

This is an absolute disgrace. Shame on you. Apparently, you haven't realized that the US is not the good guy in the world. Is your head stuck so far in the sand that you can't see how many countries we've destroyed? Iraq? Libya? The Balkans? No other country comes close!

And all this information is PUBLIC. You have the information super highway at your fingertips and still bought on to the policies of the murderous US hegemon. Shame on you.

### Expected behavior

fsdfsd

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/limonte/pen/JjoWRMx

**Comment by limonte** [comment]
It is literally hurtful to see how conspiracy theories invade people brains.

Dude, the country where I live just joined NATO and welcomes US troops warmly. Without the US we would be in serious trouble with that insane neighbor.

Relax and have a good weekend.

**Comment by limonte** [comment]
Oh, I checked your LinkedIn profile, and now everything is perfectly matching.

![CleanShot 2023-11-18 at 16 13 32@2x](https://github.com/sweetalert2/sweetalert2/assets/6059356/5654fedd-0e3f-44df-9ae3-52007907c75b)
