### ISSUE TITLE
Copy to clipboard content button

### ISSUE THREAD

**Issue by AlexVigogne** [sweetalert2/sweetalert2#2690]
### New feature motivation

Hello there ! 

We use Swal for a lot of thing in my company (thanks a lot for the work guys). And we use it for error message too. Often operations people don't know what to do when an error happens.

### New feature description

 It would be nice to add a copyContent button that allow the user to get all displayed data by default or overrided value in config to his clipboard. 

It would show to users that data can be copied and directly send to technical crew for investigations.

Thanks again,
Sincerely,
Alex.

**Comment by limonte** [comment]
Nope, this is custom functionality, that shouldn't be in the lib.
