### ISSUE TITLE
Autor - YOU NAZI

### ISSUE THREAD

**Issue by KovSer** [sweetalert2/sweetalert2#2691]
### Current behavior

Ukrain is killing tousend piple in Donbsss, but you and you goverment support him. You IDIOT. I cut out you stupid (ru|su|by) from your library and i fuck you and basters like you.

### Expected behavior

Ukrain is killing tousend piple in Donbsss, but you and you goverment support him. You IDIOT. I cut out you stupid (ru|su|by) from your library and i fuck you and basters like you.

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/limonte/pen/JjoWRMx

**Comment by zenflow** [comment]
@KovSer Get out of your propaganda machine for a moment and get real

**Comment by KovSer** [comment]
> @KovSer Get out of your propaganda machine for a moment and get real

@zenflow Propaganda it is your life! I seen deads children by my own eyes. You live in your dreams and lies, whose you goverment, you news channels and UA prorogandists tell you. And you trust him. UA start kill piple in 2014, UA use weapon to kill civilian piple every day. UA use masskill weapons to kill thiem. AND YOU, YOU SUPPORT IT!

**Comment by limonte** [comment]
Why are you so angry? Your client didn't appreciate the Ukrainian anthem on their website? 😆
