### ISSUE TITLE
In earlier versions of Chrome (e.g. Chrome87) pop-ups are not normal.

### ISSUE THREAD

**Issue by gzcapelin** [sweetalert2/sweetalert2#2694]
### Current behavior

In the process of using the earlier version of Chrome, the pop-up window was moved to the bottom right corner, and there was also an error in the style.But it works fine under higher versions of Chrome.

### Expected behavior

In the process of using the earlier version of Chrome, the pop-up window was moved to the bottom right corner, and there was also an error in the style.But it works fine under higher versions of Chrome.

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/limonte/pen/JjoWRMx

**Comment by limonte** [comment]
old chrome versions aren't supported, sorry
