### ISSUE TITLE
sweet alert break background layout.

### ISSUE THREAD

**Issue by hwoarang09** [sweetalert2/sweetalert2#2696]
before alert
![image](https://github.com/sweetalert2/sweetalert2/assets/62730797/67ec96f3-60de-48ac-afc9-6b81afc81f0f)
after alert
![image](https://github.com/sweetalert2/sweetalert2/assets/62730797/b53f24c0-7ec3-49db-9dee-1b7b230ded3e)

i think css conflict...how can i fix?

**Comment by hwoarang09** [comment]
sorry i solve error.

i add this style in top of ejs file.

<style>
  body.swal2-height-auto {
    height: 0 !important;
    max-height: 0 !important;
    overflow-y: hidden !important;
  }
</style>

**Comment by limonte** [comment]
https://sweetalert2.github.io/#heightAuto
