### ISSUE TITLE
Кастрюлеголовый?

### ISSUE THREAD

**Issue by lezhenkin** [sweetalert2/sweetalert2#2701]
Ты там нормально себя чувствуешь? На кой черт ты аудиофайл гимна Украины в свой сраный говнокод вставил? Развлечение у тебя такое? И ладно бы ты просто его в свой код вставлял, так этот гимн вставляется в код сайта, проигрывается пользователю и блокирует пользовательские действия. Ты на голову здоров?

![2024-01-21_21-47-43](https://github.com/sweetalert2/sweetalert2/assets/154676372/9dcb19be-d662-444a-b96d-686f9344c565)

**Comment by limonte** [comment]
Весело же, нет? Тебя на бутылку посадили за такие приколы? 😆
