### ISSUE TITLE
Icons invisible with colored-toast

### ISSUE THREAD

**Issue by ryanbadger** [sweetalert2/sweetalert2#2702]
### Current behavior

when using colored-toast, the icons are invisible for "success" and "error" the rest seem OK.

### Expected behavior

Icons should always be visible.

### Live demo !!! THIS FIELD IS REQUIRED !!!

you can see it in the swal2 demo sandbox: https://codesandbox.io/s/lrlgw9?file=%2FApp.ts&utm_medium=sandpack

**Comment by limonte** [comment]
Thanks for reporting @ryanbadger 🙌
