### ISSUE TITLE
Option for Page Scrolling 

### ISSUE THREAD

**Issue by wallythewebdev** [sweetalert2/sweetalert2#2710]
### New feature motivation

Ive found a need to be able to scroll when a Sweet Alert is open while also keeping the background blacked out - this is for when a Sweet alert needs to be displayed inside of a container, while the rest of the page should still be scrollable. 

Because the overflow is set to the body of the page and there is no way (that I could see from the docs) to append classes to the body of the page this means that you cannot have a Sweet alert open and also scroll. 

I found a way around this by adding the back drop to the div which the SWOL should live in 

HTML: 

`<div id="app_saved_check" style="position: absolute; inset:0; background: rgba(0,0,0,0.6); z-index: 999" class=""></div>`

JS: 

```
Swal.fire({
                    text: 'You need to save the Application to upload documents',
                    confirmButtonText: 'Save Application',
                    target: '#app_saved_check',
                    customClass: {                      // <------ customClass is an object!
                        container: 'position-absolute',
                        htmlContainer: 'overflow-auto'  // <------ I thought this would allow me to edit the body of the page that prevents scrolling - but it doesn't seem to.
                    },
                    allowOutsideClick: false,
                    backdrop: false    // <------ Allows me to scroll but I lose the back drop
                }).then((result) => {
                    /* Read more about isConfirmed, isDenied below */
                    if (result.isConfirmed) {
                        // DO STUFF
                        $('#app_saved_check').hide()
                    }
                });
```

### New feature description

Would be nice to add a Custom CSS class that can target the body of the page where the below css is added
```
body.swal2-shown:not(.swal2-no-backdrop):not(.swal2-toast-shown) {
    overflow: hidden;
}
```

Or - adding a option that would set the body overflow to scroll

allowGlobalScroll: true

**Comment by limonte** [comment]
This request sounds like too custom use-case, I don't think it should be in the lib.

**Comment by wallythewebdev** [comment]
@limonte thanks for taking the time to look at this request. 

Respectfully I disagree with this being a custom use case as the functionality to allow scrolling while a modal is on screen is already a feature of this lib which can be seen in this code pen: https://codepen.io/wally_theWebDev/pen/ExMdKJm

Having the ability to allow for scrolling while keeping the backdrop seemed to me like a useful option to have - as would having the ability to not have a backdrop and not allow scrolling. 

Maybe an option for "allow_page_scrolling" (defaults to false) is what I am suggesting. 

Maybe the above example makes the request a little clearer or maybe you still feel that this is a custom use case, either way I can code around it but it just stuck in my head as a somewhat obvious feature that was missing from the current array of options (which is a great btw, this lib is super useful and really well put together so i'm not knocking it at all). 

Thanks again - have a great weekend.

**Comment by limonte** [comment]
> Having the ability to allow for scrolling while keeping the backdrop seemed to me like a useful option to have - as would having the ability to not have a backdrop and not allow scrolling.

That'd go against the [definition of modal window](https://en.wikipedia.org/wiki/Modal_window):

> A modal window creates a mode that **disables user interaction with the main window** but keeps it visible, with the modal window as a child window in front of it. Users **must interact with the modal window before they can return to the parent window**. This avoids interrupting the workflow on the main window. Modal windows are sometimes called heavy windows or modal dialogs because they often display a dialog box.

Setting `backdrop: false` eventually makes SWAL work in [modeless mode](https://divimode.com/difference-between-modal-and-modeless-popups/#modeless).

**Comment by wallythewebdev** [comment]
@limonte thanks again for the reply and the links. 

So the debatable aspect of this request (_and why I think there is a use case for the feature_) is - what is to be considered the main window? In my instance (_self deprecating I know_) I am applying the modal to a section of content to be blocked, so that becomes the main window where user interaction should be blocked. I think it also comes down to how flexible the Library wants to be in terms of functionality (again - this is an amazing library, not implying anything negative against it).   

So I still do think there is a use case for this feature, however, if its just not inline with the libraries objectives then fair enough. 

Again thanks for taking the time to consider and reply its very appreciated.
