### ISSUE TITLE
.NET 8 Blazor - Error: There are multiple .NET runtimes present

### ISSUE THREAD

**Issue by Sushma58** [sweetalert2/sweetalert2#2712]
### Current behavior

We are using Sweet alert nuget package version 5.5.0 in our project. Recently after migrating project to .NET 8 version we are running Blazor pages in Hybrid mode (Web assembly + server side) and getting below error with all the popups

Error: There are multiple .NET runtimes present, so a default dispatcher could not be resolved. Use DotNetObject to invoke .NET instance methods.

![image](https://github.com/sweetalert2/sweetalert2/assets/78418507/c09b08c0-c4e3-485b-b1f2-bfb574415b65)

After debugging more i could see below is the point where its struggling to get correct .NET runtime
![image](https://github.com/sweetalert2/sweetalert2/assets/78418507/5a298535-7900-4865-ab77-f7c430538710)

Regards
Sushma

### Expected behavior

NA

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/limonte/pen/JjoWRMx

**Comment by limonte** [comment]
No idea, sorry

**Comment by Sushma58** [comment]
The library is struggling with .NET 8 Blazor interactive mode setup, please see below error which was reported with LightWeightCharts nuget. This is exactly similar issue I am getting.

https://github.com/mr-azazael/LightweightCharts.Blazor/issues/7

**Comment by Sushma58** [comment]
This is the suggestion from Microsoft end.

You have multiple runtimes running on the page, server and webassembly. Your library is using the global DotNet on window to invoke methods on .NET (probably static methods). That pattern is incompatible with scenarios where server and runtime are running on the same page (as the global DotNet object would not know if the call needs to go to the server runtime or to the webassembly runtime).

In this situation the recommendation is that as the library boots, it creates from .NET a dotnet object reference and sends that to JS so that JS can call back into the right .net runtime.
