### ISSUE TITLE
Input Types - Email

### ISSUE THREAD

**Issue by Speedy059** [sweetalert2/sweetalert2#2715]
### Current behavior

When create an alert with an input type of "email", it marks a valid email as invalid.
Example: jim.o'brien@domain.com
Error: Invalid email address

### Expected behavior

According to https://en.wikipedia.org/wiki/Email_address#Syntax and https://datatracker.ietf.org/doc/html/rfc5322#section-3.4.1 - That example email address is valid. You are allowed to have apostrophe's in your email address like that.

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo: https://codepen.io/David-Ellsworth/pen/qBwBEQB
Type in "whatever.o'test@domain.com" or "jim.o'brien@domain.com"

**Comment by zenflow** [comment]
https://github.com/sweetalert2/sweetalert2/blob/dcf568dd209a96b7761ae753c97c5f2d855a31ce/src/utils/defaultInputValidators.js#L7-L8

this shouldn't be changed without a semver major release though in my opinion

**Comment by limonte** [comment]
your request seems to be correct:

![CleanShot 2024-02-29 at 09 40 43@2x](https://github.com/sweetalert2/sweetalert2/assets/6059356/3eb40f06-e103-4e84-8674-16c8a3e85481)

I'd consider this as a bug-fix though
