### ISSUE TITLE
Wave Tool accessibility errors SweetAlert2 

### ISSUE THREAD

**Issue by KaziHasinRiceF** [sweetalert2/sweetalert2#2716]
### New feature motivation

![image](https://github.com/sweetalert2/sweetalert2/assets/157091955/6bd85518-3a1c-470e-b299-7dcc82e184da)
 Swal.fire({
            title: "Dashboard Card saved successfully!",
            icon: "success",
            confirmButtonColor: "#207958",
            confirmButtonText: "OK!",
            inputLabel: "Success",
            ariaLabel: "Dashboard Card saved successfully",
            ariaDescribedBy: "success-message",
            imageAlt: "Success",
          });

**Comment by limonte** [comment]
duplicate of #2599

**Comment by rajeshtulluri** [comment]
How to resolve these wave errors I am also getting this issues
