### ISSUE TITLE
Partial<SweetAlertOptions> not working when using spreading operator

### ISSUE THREAD

**Issue by FGO-LPCR** [sweetalert2/sweetalert2#2718]
### Current behavior

I have created some methods to simplify sweetalert calls and in previous versions (prior to 11.9.0), I was able to do:

```typescript
public displaySuccess(title: string, message: string, options: Partial<SweetAlertOptions> = {}): Promise<SweetAlertResult> {
  return this.displayAlert('success', title, message, {
    showCancelButton: false,
    ...options
  });
}

public displayAlert(type: AlertType, title: string, message: string, options: Partial<SweetAlertOptions> ={}): Promise<SweetAlertResult> {
  return Swal.fire({
    ...{
      title: title,
      text: message,
      icon: type,
      buttonsStyling: false,
      showConfirmButton: true,
      showCancelButton: true,
      allowOutsideClick: false
    },
    ...options
  });
}
```
After version [11.9.1](https://github.com/sweetalert2/sweetalert2/releases/tag/v11.9.1) I was not able to do this anymore. Might be cause of the `SweetAlertOptions` is now an intersection type with `SweetAlertInputValidator`, and cases the following error:

>  Overload 1 of 2, '(options: SweetAlertOptions): Promise<SweetAlertResult<any>>', gave the following error.
    Argument of type '{ input?: SweetAlertStringInput | undefined; inputValidator?: ((value: string) => SyncOrAsync<string | false | void | null>) | undefined; ... 78 more ...; scrollbarPadding?: boolean | undefined; } | { ...; }' is not assignable to parameter of type 'SweetAlertOptions'.

### Expected behavior

We should be able to pass options and use the spread operator. If it is not possible, is there any workaround to achieve this behavior?

### Live demo !!! THIS FIELD IS REQUIRED !!!

No demo

**Comment by FGO-LPCR** [comment]
Found a solution. It's not a bug with sweetalert, but more the way to work with partials and TypeScript.
Here is the solution:

```ts
public displayAlert(type: AlertType, title: string, message: string, options: Partial<SweetAlertOptions> = {}): Promise<SweetAlertResult> {
  return Swal.fire({
    ...Object.assign({}), // Create a default object first then applied your custom configuration
    ...{
      title: title,
      text: message,
      icon: type,
      buttonsStyling: false,
      showConfirmButton: true,
      showCancelButton: true,
      allowOutsideClick: false
    },
    ...options
  });
```

**Comment by selltool** [comment]
> Found a solution. It's not a bug with sweetalert, but more the way to work with partials and TypeScript. Here is the solution:
> 
> ```ts
> public displayAlert(type: AlertType, title: string, message: string, options: Partial<SweetAlertOptions> = {}): Promise<SweetAlertResult> {
>   return Swal.fire({
>     ...Object.assign({}), // Create a default object first then apply your custom configuration
>     ...{
>       title: title,
>       text: message,
>       icon: type,
>       buttonsStyling: false,
>       showConfirmButton: true,
>       showCancelButton: true,
>       allowOutsideClick: false
>     },
>     ...options
>   });
> ```

It work for me, but it is bad code :))))
