### ISSUE TITLE
Respond immediately to tap on option in inputOptions

### ISSUE THREAD

**Issue by peterlondon1** [sweetalert2/sweetalert2#2725]
### New feature motivation

Cut out one tap/click

### New feature description

Is there any way to respond to the tap/click on one of the choices in an inputOptions pulldown list **directly**, rather than when the OK (or cancel) buttons are tapped?

**Comment by limonte** [comment]
That'd be a bad UX, but here you go in case you want to annoy your users 😄 

```js
Swal.fire({
  input: 'select',
  inputOptions: {
    apples: 'Apples',
    bananas: 'Bananas',
  },
  didOpen: () => {
    const select = Swal.getInput()
    select.addEventListener('change', () => {
      Swal.clickConfirm()
    })
  },
})
```

**Comment by peterlondon1** [comment]
Thanks so much, but -why- would that be bad UI?  If the choice is non-destructive and the user is also allowed to tap outside the sweetalert box to cancel?

Peter
