### ISSUE TITLE
`autoSelect` option

### ISSUE THREAD

**Issue by mifi** [sweetalert2/sweetalert2#2729]
### New feature motivation

[someone using my app wants](https://github.com/mifi/lossless-cut/discussions/1988) to make it easier to clear a text input that is prefilled with text (`inputValue` set). If we could auto select all text automatically, then they can just pres backspace once.

### New feature description

would you be open for a new boolean option `autoSelect` (similar to the existing `autoFocus`)?

### New feature implementation

if the option is set, i think call `input.select()` also here: https://github.com/sweetalert2/sweetalert2/blob/c1d65d21cd9f691d2b821edba9e84b67be0533b3/src/utils/dom/domUtils.js#L122

see https://stackoverflow.com/questions/210761/how-to-auto-select-an-input-field-and-the-text-in-it-on-page-load

would probably have to disable the `place cursor at end of text in text input` logic here in case of `autoSelect` `true`:  https://github.com/sweetalert2/sweetalert2/blob/c1d65d21cd9f691d2b821edba9e84b67be0533b3/src/utils/dom/domUtils.js#L125

on a side note, I think the current implementation of `place cursor at end of text in text input` might be incorrect. it places cursor in case of `input.type !== 'file'`. so for HTMLSelectElement it also places the cursor, however I'm not sure that HTMLSelectElement has a cursor? shouldn't it be changed to something like `input.type === 'text' || input.type === 'textarea'`?

**Comment by limonte** [comment]
Just to clarify, are you asking about making this:

```js
Swal.fire({
  input: 'text',
  inputValue: 'test',
  didOpen: () => {
    Swal.getInput().select()
  },
})
```

a parameter?

**Comment by limonte** [comment]
>  it places cursor in case of input.type !== 'file'. so for HTMLSelectElement it also places the cursor, however I'm not sure that HTMLSelectElement has a cursor? shouldn't it be changed to something like input.type === 'text' || input.type === 'textarea'?

You're right. For HTMLSelectElement it probably just silently does nothing w/o any errors or warnings.

`input.type === 'text' || input.type === 'textarea'` wouldn't be enough because there are 'email', 'phone', 'password', 'search' and [many others](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types)

**Comment by mifi** [comment]
> a parameter?

Yes, although I didn't realise that it's actually *that* easy to do it 🙈 I can confirm that your code solves my problem too, thanks!

Anyways I thought it might be a common use case to have the text auto selected, but whether it needs to be an option or not.. your call.

> `input.type === 'text' || input.type === 'textarea'` wouldn't be enough because there are 'email', 'phone', 'password', 'search' and [many others](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types)

Right.. maybe it's still better to explicitly list all those types that actually support the cursor though, in order to avoid possible bugs/errors from occurring (in certain browsers)?

**Comment by limonte** [comment]
> Anyways I thought it might be a common use case to have the text auto selected, but whether it needs to be an option or not.. your call.

Nah, I don't think this small functionality deserves its own parameter 😄 

> Right.. maybe it's still better to explicitly list all those types that actually support the cursor though, in order to avoid possible bugs/errors from occurring (in certain browsers)?

Also nah, it has been like this several years already w/o any issue-reports. Listing all of them explicitly would create another place to keep in mind when [adding new input types](https://github.com/sweetalert2/sweetalert2/pull/2679) in future.
