### ISSUE TITLE
sweetAlert2  icons showing wrong

### ISSUE THREAD

**Issue by guiszytko** [sweetalert2/sweetalert2#2731]
### Current behavior

Using Macos with the Chrome browser, even on the sweetalerts website the warning, info and question icons appear as shown in the screenshot below
![Xnip2024-05-29_16-20-34](https://github.com/sweetalert2/sweetalert2/assets/15912751/2090dfb4-ed3b-411f-9e5a-917b077f0159)

### Expected behavior

the right thing was to look like the other icons

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/limonte/pen/JjoWRMx

**Comment by limonte** [comment]
Something is wrong with your browser settings

![CleanShot 2024-05-30 at 12 36 32@2x](https://github.com/sweetalert2/sweetalert2/assets/6059356/156c3ba2-c023-4fc3-9abb-bce5e0f4fa72)
