### ISSUE TITLE
IOS 17.6 - Safari - dropdown box is displayed in the popup which should not be there.

### ISSUE THREAD

**Issue by MrFurby** [sweetalert2/sweetalert2#2739]
### Current behavior

In the onload of the body if call the function after a return from an ajax page:

                    Swal.fire({
                        title: "WARNING",
                        text: "Er zijn foutmeldingen geconstateerd, check en neem gepaste maatregelen",
                        icon: "error",
                        footer: "To be or not to be, that's the question</a>"
                    });

Works fine in any browser on a pc but on Safari on an iphone I get a rogue dropdown box displayed.

Screenshot:
https://github.com/sweetalert2/sweetalert2/assets/37296540/fb831d05-d861-4d94-b2f1-273b3deeb11b

### Expected behavior

No dropdownbox should be there

### Live demo !!! THIS FIELD IS REQUIRED !!!

No able to replicate this in the live demo

**Comment by limonte** [comment]
can't reproduce, the screenshot doesn't look like iOS.

could you do the screen recording (video)?

**Comment by MrFurby** [comment]
This is on my iphone 14 MAX PRO
https://github.com/sweetalert2/sweetalert2/assets/37296540/e9b8b374-2329-45dd-a783-26ad865986b7

The funny thing is that if I clear my history. IT works correctly 1 time after which the selectbox appears again.

This image is the one from a laptop and has no issues.
https://github.com/sweetalert2/sweetalert2/assets/37296540/20ed2f03-fb35-49ff-b225-eaa21e920da4

**Comment by limonte** [comment]
are you able to reproduce the issue on you device visiting this codepen https://codepen.io/limonte/pen/abrYgWP ?
