### ISSUE TITLE
Missing button colors with tailwindCSS

### ISSUE THREAD

**Issue by hanisko** [sweetalert2/sweetalert2#2744]
### Current behavior

In combination with TailwindCSS, the default button color remains transparent.

### Expected behavior

Default button color will not be transparent. Problem is in CSS selector priority, commit https://github.com/sweetalert2/sweetalert2/pull/2741/commits/8491e44990ae4a8f37801fb731ff5b9cbb653883

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/spown/pen/wvLMBNR

Cancel button = transparent
Confirm button = OK (set color via. options)

**Comment by limonte** [comment]
Thanks for reporting @hanisko !

Is TailwindCSS really doing this?!

```css
button,
[type='button'],
[type='reset'],
[type='submit'] {
  background-color: transparent;
```

**Comment by hanisko** [comment]
Yes, it is in tailwindCSS https://tailwindcss.com/docs/preflight (include in @tailwind base)

 I found that i use older version https://unpkg.com/tailwindcss@3.4.1/src/css/preflight.css 

In next version they changed selector https://github.com/tailwindlabs/tailwindcss/pull/12735 = everything works fine with https://unpkg.com/tailwindcss@3.4.2/src/css/preflight.css 

So who have same issue, just update tailwind to version 3.4.2+

**Comment by limonte** [comment]
Exactly, it's the issue on tailwind side, which is already fixed.

**Comment by limonte** [comment]
TailwindCSS has a long way to go before it'll be any good to use 😆 making such a silly mistakes in CSS for resetting indicates the lack of their skills.
