### ISSUE TITLE
Combination of draw attention from sample gallery with entrance and exit of the modal

### ISSUE THREAD

**Issue by hilariondev** [sweetalert2/sweetalert2#2746]
Hey guys. just wondering if you could help me with my code. i am trying to combine the entrance and exit animation of the modal and it will shake when it clicks the background. the problem is that it has doing some weird animations and it doesn't trigger the shake effect when the background was clicked.

function showModal() {
    Swal.fire({
        title: 'Hi i am a title',
        text: 'I am Text',
        position: 'center',
        width: 960,
        padding: '30px 25px 10px 25px',
        color: '#000',
        backdrop: 'rgba(0, 0, 0, 0.67)',
        allowOutsideClick: () => {
            const popup = Swal.getPopup();
            if (popup) {
                popup.classList.remove('swal2-show');
                setTimeout(() => {
                    popup.classList.add('animate__animated', 'animate__headShake');
                }, 1); // Adjusted delay for better timing
                setTimeout(() => {
                    popup.classList.remove('animate__animated', 'animate__headShake');
                }, 500); // Adjust the duration as needed
            }
            return false;
        },
        allowEscapeKey: false,
        confirmButtonText: 'I Understand',

        didOpen: () => {
            // Ensure animation is ready when the popup opens
            const popup = Swal.getPopup();
            if (popup) {
                popup.classList.add('animate__animated', 'animate__fadeInUp', 'animate__faster');
            }
        },
        willClose: () => {
            // Ensure animation is applied when the popup closes
            const popup = Swal.getPopup();
            if (popup) {
                popup.classList.add('animate__animated', 'animate__fadeOutDown', 'animate__faster');
            }
        }

    }).then((result) => {
        // After modal is confirmed (accepted), unload animate.css
        if (result.isConfirmed) {
            unloadAnimateCSS();
        }
    });
}

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
