### ISSUE TITLE
Display position issue with dark mode

### ISSUE THREAD

**Issue by eminozlem** [sweetalert2/sweetalert2#2751]
### Current behavior

Swal displays on left when used with dark theme, regardless of the 'position' you specify.

Exists in the latest version 11.12.4,  Checked back until 11.10.4 and probably existed ever since dark mode was introduced.
Cause: dark.css does not use display:grid to apply grid props , it seems to use display:flex instead

### Expected behavior

Expected to open on right side with config position: 'top-end',

### Live demo !!! THIS FIELD IS REQUIRED !!!

https://codepen.io/eminozlem/pen/eYwGKeZ

**Comment by eminozlem** [comment]
Can be fixed by applying display:grid to .swal2-container and .swal2-popup

**Comment by limonte** [comment]
you were using the outdated version of dark theme:

```diff
- //cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@4/dark.css
+ //cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@5/dark.css
```

**Comment by eminozlem** [comment]
Oh, didnt notice, thanks

> you were using the outdated version of dark theme:
> 
> ```diff
> - //cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@4/dark.css
> + //cdn.jsdelivr.net/npm/@sweetalert2/theme-dark@5/dark.css
> ```
