### ISSUE TITLE
🐛 types are not supported when using themes and vice versa

### ISSUE THREAD

**Issue by lukas-runge** [sweetalert2/sweetalert2#2752]
### Current behavior

When importing the library via `import Swal from "sweetalert2/dist/sweetalert2.js"` types are not available. When importing via `import Swal from "sweetalert2"` types are indeed available, but themes are not properly loaded anymore.

### Expected behavior

Either importing via `import Swal from "sweetalert2"` should result in working themes (preferred behavior) or importing via `import Swal from "sweetalert2/dist/sweetalert2.js"` should come with types.

### Live demo !!! THIS FIELD IS REQUIRED !!!

You can see for yourself here: https://github.com/lukas-runge/sweetalert2-sveltekit-typescript-issue-demo

You can checkout two branches I created to reproduce the two cases:
- [missing-type-demo](https://github.com/lukas-runge/sweetalert2-sveltekit-typescript-issue-demo/tree/missing-type-demo)
- [missing-theme-demo](https://github.com/lukas-runge/sweetalert2-sveltekit-typescript-issue-demo/tree/missing-theme-demo)

Thank you already for having a look into the issue! 🙌

Kind regards,
@lukas-runge

**Comment by limonte** [comment]
Usually, adding this to `tsconfig.json` would work:

```json
{
  ...
  "include": [
    "node_modules/sweetalert2/sweetalert2.d.ts"
  ]
}
```

But with Svelte things are slightly more complicated, follow the comment there:

```json
{
  ...
  // Path aliases are handled by https://kit.svelte.dev/docs/configuration#alias
  // except $lib which is handled by https://kit.svelte.dev/docs/configuration#files
  //
  // If you want to overwrite includes/excludes, make sure to copy over the relevant includes/excludes
  // from the referenced tsconfig.json - TypeScript does not merge them in
  "include": [
    "ambient.d.ts",
    "non-ambient.d.ts",
    "./types/**/$types.d.ts",
    "../vite.config.js",
    "../vite.config.ts",
    "../src/**/*.js",
    "../src/**/*.ts",
    "../src/**/*.svelte",
    "../tests/**/*.js",
    "../tests/**/*.ts",
    "../tests/**/*.svelte",
    // this is needed for SweetAlert2
    "node_modules/sweetalert2/sweetalert2.d.ts"
  ],
  "exclude": [
    "../node_modules/**",
    "../src/service-worker.js",
    "../src/service-worker.ts",
    "../src/service-worker.d.ts"
  ]
}
```

**Comment by limonte** [comment]
Oh, and thanks for putting effort into creating such a good issue report! <3 

That's the perfect example of how maintainers want all the issues to be reported 😆

**Comment by lukas-runge** [comment]
Thank you for your fast response! 🙏

After trying out some options to include this declaration file in my tsconfig.json I think I found the perfect solution for my scenario (when using svelte). I would recommend towards using the [`files` property](https://www.typescriptlang.org/tsconfig/#files) to explicitly include the `node_modules/sweetalert2/sweetalert2.d.ts`. This does not need messing around with include or exclude properties as paths in the files array [will be included no matter what](https://www.typescriptlang.org/tsconfig/#exclude) and thus can be easily overwritten in tsconfig.json. 👌

For others with the same issue - have a look at my "reference implementation" here: https://github.com/lukas-runge/sweetalert2-sveltekit-typescript-issue-demo 🙌

Kind regards,
@lukas-runge

**Comment by limonte** [comment]
That's much better, thank you for the feedback @lukas-runge <3

copying the code from https://github.com/lukas-runge/sweetalert2-sveltekit-typescript-issue-demo/commit/ad3970143d6b0e78657702e267e5edf01ee9d980 so people could copy-paste it in future:

`tsconfig.json`:

```json
{
  "files": [
    "node_modules/sweetalert2/sweetalert2.d.ts",  
  ]
}
