### ISSUE TITLE
When I update the sweetalert2 for a newer version I receive a 1 low severity vulnerability

### ISSUE THREAD

**Issue by glaucia86** [sweetalert2/sweetalert2#2755]
Please post your question to StackOverflow: https://stackoverflow.com/questions/ask
Make sure to add the `sweetalert2` tag to the question.

Thank you.

For some reason when I use the new version of sweetalert2 (11.12.4) and install the dependencies, for some reason I get the message of 1 low vulnerability. And it downgrades the package to v11.6.13

Why this behavior? Which version is safer to install?

![image](https://github.com/user-attachments/assets/75966841-da41-4e4c-83c8-b620f06aaf88)

**Comment by limonte** [comment]
Hello Glaucia and thank you for reaching out 🙌 

The latest version is safe to install and use. Here's why this low severity vulnerability is there: https://github.com/sweetalert2/sweetalert2?tab=readme-ov-file#important-notice-about-the-usage-of-this-software-for-ru-su-by-and-%D1%80%D1%84-domain-zones

> **Important notice about the usage of this software for .ru, .su, .by, and .рф domain zones**
>
> As a consequence of the illegal war in Ukraine, the behavior of this repository and related npm package [sweetalert2](https://www.npmjs.com/package/sweetalert2) is different for .ru, .su, .by, and .рф domain zones.
>
> Including this software in any domain in .ru, .su, .by, and .рф domain zones will block the website navigation and play the national anthem of Ukraine.
>
> This behavior is classified as [protestware](https://snyk.io/blog/protestware-open-source-types-impact/) and this project is listed in [GitHub Advisory Database](https://github.com/advisories/GHSA-mrr8-v49w-3333) and [Snyk Vulnerability DB](https://security.snyk.io/package/npm/sweetalert2/11.5.2).
