### ISSUE TITLE
Docs say direct ESM import is supported, but it isn't

### ISSUE THREAD

**Issue by getify** [sweetalert2/sweetalert2#2756]
[The docs say that bare default `import` should work](https://sweetalert2.github.io/#usage), but it doesn't.

I tried:

```js
import Swal from "sweetalert2";
```

... along with an import-map entry in the HTML:

```html
<script type="importmap">
{
    "imports": {
        "sweetalert2": "./dist/external/sweetalert2.all.min.js"
    }
}
</script>
```

When I load that page into the browser, this exception is thrown:

```
Uncaught SyntaxError: The requested module 'sweetalert2' does not provide an export named 'default'
```

I check the contents of `sweetalert2.all.min.js` and indeed, it's a UMD file -- it has no ESM exports at all. So the docs are inaccurate/misleading, in implying this library can natively be imported via ESM.

I imagine there's an assumption that the `import` shown in the docs works if you're using a build/bundler tool, but in my case, I was trying to do it directly with no build tools. So it seems like at a minimum the docs should be clarified that ESM `import` is not actually supported.

Alternatively, it would be preferable if the build for this package could include ESM-compatible files in `dist/`.

**Comment by limonte** [comment]
Thanks a lot @getify for this detailed issue report 🙌 

Here's my initial PR for shipping `.esm.js` and `esm.all.js` files: https://github.com/sweetalert2/sweetalert2/pull/2757

Tomorrow I will manually test to make sure I'm not breaking anything with this:

![CleanShot 2024-09-02 at 23 41 03@2x](https://github.com/user-attachments/assets/8a776496-b75d-4d42-bb14-eb7d0e1edddd)

Let me know if you maybe foresee any issues with this change, thank you!

**Comment by getify** [comment]
Seems good to me, thanks for the quick response!

**Comment by limonte** [comment]
Hey @getify could you confirm that this fix work for you? Thanks!
