### ISSUE TITLE
Many helper functions due to babel settings

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [sweetalert2/sweetalert2#2758]
### Current behavior

In [this commit](https://github.com/sweetalert2/sweetalert2/commit/388fcd78c8076debef6b4199740cee9efec25cb0), first released in [v11.10.0](https://github.com/sweetalert2/sweetalert2/compare/v11.9.1...v11.10.0), the browser targets for babel were removed. Not specifying any targets causes babel to [target the oldest browsers it can](https://babeljs.io/docs/options#no-targets), which means that the distributed files contain a lot of helper functions to support post-ES5 features.

### Expected behavior

Explicitly specify browser targets. If the change was intentional, then it might make sense to explicitly target Internet Explorer 11 - if not, simply `targets: 'defaults'` might be enough, or you could choose something more deliberate (I don't know what browsers other users of this library need to support).

It might also make sense to choose different targets for the ESM bundle - clearly it won't be used on browsers without support for ES Modules, at least.

### Live demo !!! THIS FIELD IS REQUIRED !!!

This repository doesn't include the distributed files, but see for example [sweetalert2.esm.all.js](https://cdn.jsdelivr.net/npm/sweetalert2@11.13.1/dist/sweetalert2.esm.all.js).

**Comment by limonte** [comment]
Thank you so much for reporting this @ehoogeveen-medweb 🙌 

this looks alright:

![CleanShot 2024-09-04 at 09 40 59@2x](https://github.com/user-attachments/assets/3baba76c-4fb6-463c-940c-94cc624e5ef7)

![CleanShot 2024-09-04 at 09 42 18@2x](https://github.com/user-attachments/assets/8ab1d29b-8477-46fb-97e4-35f24db5919b)

Would you like to create a PR with that 1 LoC and become a contributor of this project? 😊
