### ISSUE TITLE
Fire global events that could be subscribed to

### ISSUE THREAD

**Issue by getify** [sweetalert2/sweetalert2#2760]
### New feature motivation

I am writing an automated test suite that, in part, covers code which uses swal2 to display modals. I wanted to capture a list of all the times the modal is opened and closed across the tests... a list of `[ "show", "hide", "show", ... ]` if you will. That way I could compare such a list to the expected number of shows and hides.

Unfortunately, I don't see any events being fired, which I can subscribe to, that let me know when the modal is shown or hidden -- from the outside, as opposed to injecting event handler (`willShow`, etc) into each `.fire(..)` call.

Here's the sorta hack/work-around I came up with:

```js
var events = [];

var observer = new MutationObserver(mutationList => {
    events.push(
        ...(
            mutationList.filter(mutation => (
                mutation.type == "attributes" &&
                mutation.attributeName == "class" &&
                mutation.target.matches(".swal2-show, .swal2-hide")
            ))
            .map(mutation => (
                mutation.target.className.match(/\bswal2-(show|hide)\b/)[1]
            ))
        )
    );
});

observer.observe(document.body,{ attributes: true, subtree: true, });

// later, after the test finishes, remove consecutive duplicates
events = events.reduce((list,v) => (
    list.length == 0 || list[list.length - 1] != v ?
        [ ...list, v ] :
        list
),[]);

events;   // [ "show", "hide", "show", ... ]
```

This seems to work for my usage, but... is far from ideal (especially the mutation observer part).

### New feature description

I'd love it if I could avoid the `MutationObserver`, and instead the `Swal` object was an event emitter (like `EventEmitter3`, etc), so that I could do:

```js
var events = [];

Swal.on("show",() => events.push("show"));
Swal.on("hide",() => events.push("hide"));

// later, after the test finishes, remove consecutive duplicates
events = events.reduce((list,v) => (
    list.length == 0 || list[list.length - 1] != v ?
        [ ...list, v ] :
        list
),[]);

events;   // [ "show", "hide", "show", ... ]
```

Of course, the methods could be `on()` / `off()`, or `addListener()` / `removeListener()`, or whatever naming is preferred.

### New feature implementation

At a minimum, I think you'd need to add two methods (again, named `on()` / `off()`, etc) for registering an event listener, and removing an event listener. You *could* add more sugar helpers, like `removeAll()`, etc... but I think that's optional as a minimal feature set here.

There are several OSS libraries that already do event-emitter interfaces well, such as [EventEmitter3](https://github.com/primus/eventemitter3). I think you could find one of those and either bundle it in and use out-of-the-box, or at least pull a subset of its implementation from and drop-in to `Swal`'s definition.

Then in each place internally where Swal is doing things like adding `swal2-show` / `swal2-hide` classes, that's where you'd need to also have `emit(..)` calls to emit the proper events to the interface. The arguments to pass along should probably match/mirror the other internal event handlers (`willShow`, etc).

Also TBD would be which events need to be published on the emitter. I need "show" and "hide" minimally, but there may be others that are useful.

----

I'd be happy to try my hand at a PR, if this feature is considered something useful in scope for the project.

**Comment by zenflow** [comment]
> [...] and instead the Swal object was an event emitter (like EventEmitter3, etc) [...]

@getify You want the class itself (`Swal`) to be an event emitter? Or the instance (returned by `Swal.fire()` to be an event emitter? Or both?

**Comment by getify** [comment]
@zenflow 

as far as I can tell, the instances already have the internal events (via `willOpen` callback, etc). That's not exactly how I would have preferred to do event handling -- event emitters and subscriptions are better, IMO -- but I don't see any need to augment (or replace!) that mechanism.

so I'm only talking about "global" events that would be emitted on the main class/object... the same one I do `Swal.close()` and such on.

**Comment by zenflow** [comment]
> so I'm only talking about "global" events that would be emitted on the main class/object... the same one I do Swal.close() and such on.

Swal can be subclassed to change or enhance behavior. Typically this is done with `Swal.mixin({...changesToDefaultParams})`.

If you're not doing that, then this suggestion makes no difference, but...

Maybe instead of "global" events, the events registered on a swal class should apply to instances of that class and subclasses, but none others.

E.g. 

```js
let yesNoSwalShowCount = 0
const YesNoSwal = Swal.mixin({ ... })
YesNoSwal.on('show', () => { yesNoSwalShowCount++ })

let textInputSwalShowCount = 0
const TextInputSwal = Swal.mixin({ ... })
TextInputSwal.on('show', () => { textInputSwalShowCount++ })
```

**Comment by getify** [comment]
My use-case, in an automated unit-test suite, is that I don't have access to the instances themselves (they're inside the library). The only thing I have access to, from the outside, is `Swal`. So I would need to be able to register events on that. That's why I refer to them as "global" events.

**Comment by zenflow** [comment]
Understood. My suggestion of how to implement event-emitter interface supports that.
IMO if this package is to implement event-emitter interface, it should be as flexible as the existing event interface.

Another solution for your use-case, which doesn't require any changes to this package and is a bit simpler than your current MutationObserver solution:

```diff
var events = [];

-Swal.on("show",() => events.push("show"));
-Swal.on("hide",() => events.push("hide"));
+window.Swal = window.Swal.mixin({ 
+    willShow: () => events.push("show"),
+    willHide: () => events.push("hide"),
+});
+// may need to use a library for mocking, instead of simply reassigning window.Swal, depending on your setup

// later, after the test finishes, remove consecutive duplicates
events = events.reduce((list,v) => (
    list.length == 0 || list[list.length - 1] != v ?
        [ ...list, v ] :
        list
),[]);

events;   // [ "show", "hide", "show", ... ]

**Comment by getify** [comment]
@zenflow

what happens if any of the library's `fire(..)` calls defines its own `willShow()` and `willHide()` functions? Are these "mixin" ones overridden? Or also called?

**Comment by zenflow** [comment]
@getify I actually thought they would be merged, not overridden, but I was wrong:

https://github.com/sweetalert2/sweetalert2/blob/401b7bb0aabc168ffb4ce63d1e89ddc77c5f647e/src/staticMethods/mixin.js#L20-L23

The would ideally be merged

**Comment by getify** [comment]
btw, FWIW, I think I'd need to listen to `didShow` and `didDestroy`.

the mixins thing is clever and I wouldn't have thought of that... but yeah, if they're overridden (not merged), that won't work in my case.

**Comment by zenflow** [comment]
I think the change of merging (instead of of overriding) these existing event handler params (though it would be a breaking change) would be more generally useful than a secondary interface for events.
@limonte What are your thoughts?

@getify With that you could use the mixins solution to your problem, 
or if an event-emitter interface was really needed, it could be implemented in a few lines of code:

```js
// enhance Swal
const EESwal = Swal.mixin({
  didOpen: () => EESwal.emit('open'),
  didClose: () => EESwal.emit('close'),
})
Object.assign(EESwal, EventEmitter3.prototype)
EventEmitter3.call(EESwal)

// listen to events
EESwal.on('open', () => console.log('open'))
EESwal.on('close', () => console.log('close'))

// listeners on EESwal apply to instances of EESwal or any subclass of it
const MySwal = EESwal.mixin({background: 'hotpink'})
MySwal.fire('hi')
```

https://jsfiddle.net/mjser53k/

**Comment by limonte** [comment]
Thank you both for this discussion 🙌 

I'd restrain from implementing global events for now as there's no big demand for that feature. I might change my mind in case this request will gather more votes.

For now I'd recommend mocking Swal in your tests, something like this (untested manually):

```js
import Swal from 'sweetalert2'

jest.mock('sweetalert2', () => class extends Swal {
  _main(params) {
    return super._main({
      ...params,
      didOpen: () => {
        params.didOpen && params.didOpen()
        events.push('show')
      },
      didDestroy: () => {
        params.didDestroy && params.didDestroy()
        events.push('hide')
      },
    })
  }
})
```

**Comment by limonte** [comment]
Now I don't follow 🙈  

If you're trying to test external `Swal` it's of course impossible to mock that. But it's also impossible to attach any `.on`/`. ` `addListener()` as well.

Maybe I misunderstood something, would you mind sharing some code? Not necessarily the actual code, but more a structure of what you're trying to test. Thanks!

**Comment by getify** [comment]
```js
// a.mjs:
import Swal from "sweetalert2";
export { runA };

async function runA() {
   setTimeout(() => { Swal.close(); },2000);
   await Swal.fire({ .. });
}
```

```js
// tests.mjs
import { runA } from "a.mjs";
import Swal from "sweetalert2";

async runATests() {
   // subclass to listen for some open/close events
   class mySwal extends Swal {
      _main() { .. }
   }

   // need to listen to the Swal dialog opening
   // and closing **inside the A module**
   await runA();

   // verify that the dialog opened and closed as expected.
   // ..
}
```

So, specifically, what I'm saying is, in `tests.mjs`, the `mySwal` subclass doesn't do anything to affect the `Swal` being used inside `a.mjs` module, so I don't think it's possibly going to "hear" any opening/closing events that went on inside of module "a.mjs".

Right?

----

By contrast, if the `Swal` class object was a static global event emitter as I'm proposing:

```js
// tests.mjs
import { runA } from "a.mjs";
import Swal from "sweetalert2";

async runATests() {
   // need to listen to the Swal dialog opening
   // and closing **inside the A module**
   Swal.on("open",() => { /*..*/ });
   Swal.on("close",() => { /*..*/ });

   await runA();

   // verify that "open" and "close" were fired
}
```

In the internals of sweetalert, any time *any* instance was about to open or close the dialog, they'd additionally do `SweetAlert2.emit("open", ..)` or `SweetAlert2.emit("close", ..)`... which would fire those events on the static main parent class object, not on any of its specific `this` instances.

**Comment by getify** [comment]
FWIW, I just verified my assumptions. The presence (or even use of) a subclass `mySwal` has no effect on registering event listeners in any parent-class instances inside of `a.mjs`.

So yeah, this approach is not a suitable workaround for me.

Moreover, `mixin()` doesn't set defaults for *all* instances... it creates and returns a new subclass instance, from which any of *its* instances will share those defaults. But if others are using the main parent class, none of those settings will apply.

**Comment by limonte** [comment]
@zenflow I might need your help to understand why extended swal isn't working as expected, here's the repo with the mock similar to the one above: https://github.com/sweetalert2/sweetalert2-extended

Run `bun test`.

What's happening there is that `_main` doesn't seem to be overriden. No errors. Is it maybe because `_main` is private?

**Comment by limonte** [comment]
@getify here you go with a working example of mocking Swal2 using Bun test runner: https://github.com/sweetalert2/sweetalert2-extended/blob/main/index.test.js

**Comment by getify** [comment]
OK, I didn't understand from before, but I finally do, what you're suggesting... you're suggesting using test runners (like jest or bun:test) which mock (forcibly inject) dependencies. So you're basically saying that the live module would think it was loading real swal but the test runner would force it to load a patched swal with the listeners in it.

I can't use bun:test because my test-bed runs inside plain ol' github-pages, which is just static web file servering... can't customize the webserver. (you can use bun during the github actions that *deploy* to gh-pages, but you can't AFAIK actually force bun to run *in* the gh-pages instance, you can only "upload" static files to gh-pages).

I'm not familiar with jest either, dunno if it requires a server to do its mocking magic, or if it somehow intercepts stuff purely on the client-side.

But in any case, I'm not using any test-runner framework on my test-bed. It's just plain vanilla JS. And I'd prefer to keep it that way.

Which means the only way I can accomplish similar mocking magic would be to override the `import .. from "sweetalert2"` using an HTML import-map, and force it *during the tests* to load a wrapped/mocked swal from a different file. I just tried, and this is far less convenient than the inline injection your snippets and test-runners allow -- which are able to close over the `results` variable to store the logs. It requires fiddling around with some other sort of shared state between my test module and the swal mock module.

I just played around with hacking something like that, and it sort of worked, except... one of my module's internal usages of Swal passes in its own `didDestroy`, which then overwrites the `didDestroy` setup by the mock -- it isn't called in that case, though it is called in others.

I think the overwriting vs merging was brought up earlier in the thread... I didn't understand fully what was being suggested then, but now I do. And now I see why it's a bit of a deal breaker.

In any case, this sort of rube-goldberg workaround is, IMO, much hackier and more brittle, than my `MutationObserver` approach I started with. So... I'm going to stick with that for now.

----

If you all reconsider and allow a PR to add static global event-emitter capability to the Swal parent class, I'm still happy in the future to come back and try a PR.

I'll leave it to you to decide if this issue should be closed now until that later time, or left open.

**Comment by zenflow** [comment]
> I think the overwriting vs merging was brought up earlier in the thread... I didn't understand fully what was being suggested then, but now I do. And now I see why it's a bit of a deal breaker.

By deal breaker you mean semver-major?
Not sure if that's why it was ignored.. or why that would be a reason to be ignored..

---

Anyways, as this package is, you can still create a EESwal with a small amount of code (just a bit clunkier than if existing event handlers were merged instead of overridden):

```js
// lib/EESwal.mjs
import Swal from "sweetalert2"
import EventEmitter3 from "eventemitter3"
export { EESwal }

class EESwal extends Swal {
  _main(params, priorityMixinParams) { // something breaks if you don't use priorityMixinParams but not sure what
    return super._main({
      ...params,
      didOpen: () => {
        params.didOpen?.()
        EESwal.emit('open')
      },
      didClose: () => {
        params.didClose?.()
        EESwal.emit('close')
      },
    })
  }
}
Object.assign(EESwal, EventEmitter3.prototype)
EventEmitter3.call(EESwal)
```

```js
// lib/a.mjs:
import { EESwal } from "./EESwal.mjs";
export { runA };

async function runA() {
   setTimeout(() => { EESwal.close(); },2000);
   await EESwal.fire({ .. });
}
```

```js
// tests/a.mjs
import { runA } from "../lib/a.mjs";
import { EESwal } from "../lib/EESwal.mjs";

async runATests() {
   // need to listen to the dialog opening
   // and closing **inside the A module**?
   // no problem!
   EESwal.on("open",() => { /*..*/ });
   EESwal.on("close",() => { /*..*/ });

   await runA();

   // verify that "open" and "close" were fired
}
```

**Comment by limonte** [comment]
Thank you for the detailed description of your environment and why mocking isn't possible in your case.

TIL 

> A Rube Goldberg machine, named after American cartoonist [Rube Goldberg](https://en.wikipedia.org/wiki/Rube_Goldberg), is a [chain reaction](https://en.wikipedia.org/wiki/Chain_reaction)–type machine or contraption intentionally designed to perform a simple task in an indirect and (impractically) overly complicated way.

It's just a habbit of a modern web developer 😆 

> Web developers have to create their own job security through useless complexity (c)

---

At the end of the day, I just can't say no to the author of YDKJS 😆  and try to find a time for implementing event emitter during this weekend. Will probably start with something simple like [this one](https://gist.github.com/mudge/5830382?permalink_comment_id=2691957#gistcomment-2691957).

@getify will you be fine with event names aligned with our lifecycle hooks? `willOpen`, `willOpen`, and so on [from here](https://sweetalert2.github.io/#willOpen).

**Comment by getify** [comment]
Thank you so much! Amazing!
