### ISSUE TITLE
If I'm using the CSS file why should I allow javascript to inject CSS into the header?

### ISSUE THREAD

**Issue by arcanisgk** [sweetalert2/sweetalert2#2764]
### Current behavior

I have noticed that despite using CDNs or including the sweet-alert CSS file locally, the javascript file on its own injects the CSS into the header again, duplicating it.

### Expected behavior

This should be up to the website developer/owner to decide how it should behave, and not do things like this on their own.

I propose to implement a data attribute:

`data-no-css`: the expectation is that if this attribute is found in the sweetalert link, the javascript will not automatically import the css on its own:

```js
if (typeof document !== "undefined") {
  // We look for the script that includes SweetAlert
  var sweetAlertScript = document.querySelector('script[src*="sweetalert"]');

  // If the script includes the data-no-css attribute, we do not load the CSS
  if (sweetAlertScript && sweetAlertScript.hasAttribute('data-no-css')) {
    console.log('CSS will not be loaded from SweetAlert JS due to data-no-css.');
  } else {
    // If the attribute is not present, we load the CSS as usual
    (function(e, t) {
      var n = e.createElement("style");
      e.getElementsByTagName("head")[0].appendChild(n);
      if (n.styleSheet) {
        if (!n.styleSheet.disabled) {
          n.styleSheet.cssText = t;
        }
      } else {
        try {
          n.innerHTML = t;
        } catch (e) {
          n.innerText = t;
        }
      }
    })(document, "/* SweetAlert CSS content would go here */");
  }
}
```

**Comment by limonte** [comment]
I propose RTFM: https://sweetalert2.github.io/#usage

**Comment by arcanisgk** [comment]
I suggest SFMUA or MYSE, their manual doesn't fix it... not everyone goes through it.
