### ISSUE TITLE
Sass Lighten Deprecation

### ISSUE THREAD

**Issue by xocialize** [sweetalert2/sweetalert2#2768]
### Current behavior

Getting the following console message when running the latest vue/vite with sweetalert2

Deprecation Warning: lighten() is deprecated. Suggestions:

color.scale($color, $lightness: 33%)
color.adjust($color, $lightness: 33%)

### Expected behavior

It's currently not really an issue as it's informational at this point but wanted to get it on the radar.

**Comment by limonte** [comment]
This was fixed yesterday in #2767 

Upgrade your `sweetalert2` dependency.
