### ISSUE TITLE
Check if delete method exists on destroy 

### ISSUE THREAD

**Issue by logitec** [sweetalert2/sweetalert2#2771]
### New feature motivation

when i add a feature through Object.prototype swal fails when close because 

`const unsetWeakMaps = (obj, instance) => {
  for (const i in obj) {      
    obj[i].delete(instance) 
  }
}`
should verify if method delete exists in the object ob[i]

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)
