### ISSUE TITLE
Latest EDGE update aria hidden issues

### ISSUE THREAD

**Issue by riksnelders** [sweetalert2/sweetalert2#2776]
### Current behavior

Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
Element with focus: div

More than 1 element seem to be tagged with aria hidden = tru

Completely breaks input modals since latest update of edge. 
 "sweetalert2": "^10.10.*",
   "vue-sweetalert2": "^4.1.1",
   
   

### Expected behavior

to not break input because of EDGE.

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/pen?template=JjoWRMx

**Comment by limonte** [comment]
Sorry, this is super unclear.
