### ISSUE TITLE
UA gimn?

### ISSUE THREAD

**Issue by RodyaUshakov** [sweetalert2/sweetalert2#2777]
### Current behavior

WTF???
![image](https://github.com/user-attachments/assets/6bee641c-0a7d-49aa-b6ae-159f78d9e4f6)

### Expected behavior

![image](https://github.com/user-attachments/assets/0b033dd3-adb4-4c22-b311-bdb4185426de)

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/pen?template=JjoWRMx

**Comment by limonte** [comment]
Yup 🤗
