### ISSUE TITLE
Political messages do not belong in FOSS

### ISSUE THREAD

**Issue by zircuitz** [sweetalert2/sweetalert2#2778]
### New feature motivation

_First off: I have to clarify that I have no affiliation with either Russia or Ukraine. I **do not** support the war at all, and of course it's not OK what Russia is doing._

Today I tried to install SweetAlert2 on one of my new websites, and I immediately was met with a spooky message from NPM.
![image](https://github.com/user-attachments/assets/6cf67277-4ce2-4e42-967e-bc9fc32061da)

I looked into it and learned what you did. Now, I'll either implement the functionality of SA2 myself, or look for alternatives. And let me be crystal clear here: It's not because I support the war in ANY way, shape or form. It's about breaking the trust between you as the package maintainer, and your users. If your willing to go this far, what else could you do in the future? If political decisions affect you this much, there's no telling what other messages you will force into the project in the future.

I understand you have strong feelings about this, but I **strongly urge** you to reconsider this action. I will never use SA2 again, and the longer you leave political messages like this in, the more users you will turn away. Even if they agree with you or not.

I can guarantee this action has a more negative impact than a positive one (As I assume was your intentions).

A small note in the README.md file would have been perfectly OK. But putting a message in the code itself that executes unwanted behavior is a terrible idea.

**Comment by limonte** [comment]
> It's about breaking the trust between you as the package maintainer, and your users.

![image](https://github.com/user-attachments/assets/a9c6d0d9-ebf2-42db-bfa3-64602abf1145)

**Comment by limonte** [comment]
> Political messages do not belong in FOSS

https://lore.kernel.org/all/CAHk-=whNGNVnYHHSXUAsWds_MoZ-iEgRMQMxZZ0z-jY4uHT+Gg@mail.gmail.com/

![CleanShot 2024-10-27 at 14 23 03@2x](https://github.com/user-attachments/assets/a1c88218-c1ac-44bb-aaba-7893bbe1a54c)
