### ISSUE TITLE
Suggest block il domains

### ISSUE THREAD

**Issue by 313ava** [sweetalert2/sweetalert2#2782]
Hi, I suggest block il domains as well as ru, because of genocide of Israel in Gaza strip and illegal occupation of Palestine and Golan in Syria.

**Comment by limonte** [comment]
Thank you for your suggestion. It's rejected.

**Comment by limonte** [comment]
Here's why: https://github.com/sweetalert2/sweetalert2/issues/2685#issuecomment-1807174344

**Comment by 313ava** [comment]
Thanks I read your reply. So, I understood that you do that for your own sense not for humanity. Israel's crimes since the Nakba (occupation of Palestine) have been unprecedented in history, and ignoring these crimes would mean encouraging them to commit more crimes. It is time to think about humanity instead of personal interests.

**Comment by limonte** [comment]
Let me be very clear here.

I stand with Israel 🇮🇱 

Now go and spread your nonsense to someone else, this isn't the right place for that.
