### ISSUE TITLE
change loader icon/button of "showLoaderOnConfirm"

### ISSUE THREAD

**Issue by fas3r** [sweetalert2/sweetalert2#534]
Hello, 

Is it possible to change the spinner when using "showLoaderOnConfirm" and reuse the previous loader from sweetalert ? ( button with 3 dots ). 
Thanks.

**Comment by fas3r** [comment]
Hello,

Any update?

**Comment by james-gould** [comment]
Also wondering about this.

**Comment by toverux** [comment]
It's... possible, but maybe not as flexible as you may want. For now, you can't set a custom class or element, for example to integrate with a CSS framework.
But you can customize the `.swal2-loading` class that displays the loader (it's defined in plain old CSS, no complex JavaScript, so yes that's possible) -
 here's how it's defined : https://github.com/limonte/sweetalert2/blob/9f55ef6bcdeb2a9a4a24af0daab88246633d954c/src/sweetalert2.scss#L80-L132

Looking to #537, it also seems that @limonte thinks about making it fully replaceable, but you can already achieve that with CSS.

**Comment by limonte** [comment]
It took me 3 years to implement this 🤦‍♂️ But finally it's done in [v10 ](https://github.com/sweetalert2/sweetalert2/releases/tag/v10.0.0)🎉 

Live demo: https://codepen.io/limonte/pen/bGpLNzV

```js
Swal.fire({
  loaderHtml: `<div class="spinner-grow text-primary" role="status"><span class="sr-only">Loading...</span></div>`
})
```
