### ISSUE TITLE
Add the Semantic UI integration example

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#537]
Particularly https://semantic-ui.com/elements/button.html (loading state)

Related to #534 and #410

**Comment by fas3r** [comment]
Hello, 

any update ?

**Comment by fas3r** [comment]
Hello,

Still no update ?

**Comment by limonte** [comment]
Semantic UI doesn't seem to be maintained anymore, closing this issue.

All themes are in https://github.com/sweetalert2/sweetalert2-themes
