### ISSUE TITLE
Dark Skin/Template/Css

### ISSUE THREAD

**Issue by bloor** [sweetalert2/sweetalert2#547]
I really found this as an issue, of not having available a dark version of the plugin.
Most of the places I used the plugin are Admin Panels/Dashboards. And it looks great ! But i had 3 times where i needed a dark version of the swal-box. 
**OR** 
As some other thread suggested: somehow make css variables easy to customize. Neat idea here , would be to make an online CSS generator. Where you specify your palette and get the CSS. ;D

For those project I did a on-the-spot conversion/fix of the css to match the dark theme. But would be nice to have it right out the box. 

Here's an example of a dark Dashboard that could use the benefits of such feature:
http://prntscr.com/fivqx4

**Kudos for the job so far!**

**Comment by limonte** [comment]
This issue has the most upvotes, so it's going to pinned issues and should get the top priority.

**Comment by gverni** [comment]
Thanks @limonte. Sorry I didn't get to work on the theme repo yet as we discussed. Are you planning to have this implemented as theme in https://github.com/sweetalert2/sweetalert2-themes or as an option in sweetalert?

**Comment by limonte** [comment]
> Are you planning to have this implemented as theme in https://github.com/sweetalert2/sweetalert2-themes or as an option in sweetalert?

In `sweetalert2-themes`. 

Will you have time to start playing with the dark theme? I didn't start it yet because I believe my skills in choosing color are terrible :D

**Comment by gverni** [comment]
> Will you have time to start playing with the dark theme? 

Sure, the sweetalert-examples is now in a better state (with html templating). I have a couple of low priority chores there, but it shouldn't take me too long. 

>  I didn't start it yet because I believe my skills in choosing color are terrible :D

Mine are probably even worse :smile: hence I wanted to copy the palette from Visual Studio Code, wich to me is a nice palette. What do you think? Do you have any other dark theme you like that we can use as inspiration?

**Comment by limonte** [comment]
> I wanted to copy the palette from Visual Studio Code, wich to me is a nice palette. What do you think? 

Agree, it matches my taste as well

**Comment by limonte** [comment]
A random repo that might maybe be useful here https://github.com/StylishThemes/GitHub-Dark

**Comment by limonte** [comment]
I'm happy to announce [`@sweetalert2/theme-black`](https://github.com/sweetalert2/sweetalert2-themes/tree/master/dark) which is the part of [`@sweetalert2/themes`](https://github.com/sweetalert2/sweetalert2-themes) :tada: :tada: :tada: 

Implementation credits are going to @gverni! He is the rock-star of SweetAlert2 project :rocket: 

Please try the dark theme out and repot any issues/wishes to https://github.com/sweetalert2/sweetalert2-themes/issues
