### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by KrunchMuffin** [sweetalert2/sweetalert2#747]
I posted a question to your answer on SO .
https://stackoverflow.com/a/39596153/112680

Figured I post here as well. But I am trying to figure out how to use jquery-localize with SWAL2.
You put this
`$(modal).find("[data-localize]").localize("modal", {language: "fr"})`

but no idea as to where it would read that attribute from? Or what we need to put for text, title etc?

Thanks

**Comment by acupajoe** [comment]
Sorry @KrunchMuffin for the lack of response on our part here. This issue is isolated to SO because of the nature of the question (how-to rather than a bug). I'm adding an additional response for clarity of @limonte's original answer.

```javascript
$(function() {
  swal({
    title: 'Hello',
    html: '<p data-localize="text"></p>',
    onOpen: function(modal) {
      $(modal).find("[data-localize]").localize('text', { language: 'fr' })
    }
  })
})
```

But I will go ahead and close the issue - hope that helped!
