### ISSUE TITLE
Animate closing

### ISSUE THREAD

**Issue by manix** [sweetalert2/sweetalert2#761]
It's cool I can use animate.css when the dialog is being shown via `customClass` (which is kind of hacky) however it disappears immediately when closed. Is there any way I could add custom closing animation as well?

**Comment by acupajoe** [comment]
References #654

**Comment by camaech** [comment]
I made a quick implementation of this, but it's probably not the best way to do it. How do I go about asking someone how it should actually be done?

**Comment by acurrieclark** [comment]
While far from a perfect solution, you can use the `onClose` callback to reenable the original "leave" animation. This at least removes the jarring lack of animation when the alert clears:

```js
Swal.fire({ 
      ...
      onOpen: (swal) => {
        swal.classList.remove("swal2-noanimation");
      },
      ...
    });
```
