### ISSUE TITLE
Add swal.isValidating() helper method

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#789]
This is the follow-up from https://github.com/limonte/sweetalert2/issues/782#issuecomment-353746553

In case the `inputValidator` is async, it would be nice to have `swal.isValidating()` helper method which will return a boolean value indicating the state.

**Comment by limonte** [comment]
@zenflow will you have time to implement this helper method?

**Comment by zenflow** [comment]
@limonte Should be able to around Thursday/Friday. (Still on vacation with the family at the moment)

Happy new year! 🎉

**Comment by limonte** [comment]
Awesome, thank you @zenflow! Wish you lot of success with your ideas and projects in 2018!

**Comment by limonte** [comment]
This helper wasn't requested by our users (almost two years), so I guess there's no need in it.
