### ISSUE TITLE
Can't disable backdrop when supplied with target element

### ISSUE THREAD

**Issue by nirdil** [sweetalert2/sweetalert2#791]
When I target the modal to a specific element, the backdrop cannot be disabled using the backdrop: false config option

**Comment by limonte** [comment]
Thanks for reporting @nirdil, I can reproduce the issue.

The jsfiddle: https://jsfiddle.net/limon/ad3quksn/272/

@acupajoe will you have time to take a look at this?

**Comment by acupajoe** [comment]
@limonte sorry, was moving towns and have been away. I'll take a look at this now!

**Comment by limonte** [comment]
Released :tada: 

https://github.com/sweetalert2/sweetalert2/releases/tag/v7.4.0
