### ISSUE TITLE
Accept functions for `allowEscapeKey` and `allowEnterKey`

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2#793]
This is a follow-up from #782.

In anticipation of similar user needs, and to make the API a wee bit more uniform, lets do the same with `allowEscapeKey` and `allowEnterKey` that we did with `allowOutsideClick`. That is, accept a boolean *or* a function with no arguments that returns a boolean.

Any objections? Or can I put this in my TODO list?

Did I overlook any other params that should have this feature?

**Comment by limonte** [comment]
No objections, go ahead, I'll be happy to review and merge your contributions :rocket:
