### ISSUE TITLE
Support for the multitude of UI frameworks

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2#798]
Continuing the discussion from PR #795 ...

@birjolaxew said:

>I think any integration with specific libraries should be in separate packages (e.g. sweetalert2-react and vue-sweetalert2). It would definitely be valuable for them to be officially supported (especially with how much work you put in!), but it doesn't belong in the main package.

I agree 100%. If we start to introduce support for specific frameworks in the core repo, we open ourselves up to a host of difficult problems/decisions. How many different frameworks should be supported? Which ones? How do we deal with the answers to the previous questions changing over time? To the degree of how many frameworks are supported, the focus (in terms of code, complexity, issues, PRs) on core functionality will be diluted. 

We should follow the timeless Unix philosophy and try our best to have this package "do one thing and do it well".

That said, framework integration seems very useful and important (in particular, for me, support for React components in the swal content), and is something I think would be best handled by this **team** (as opposed to this package). 

@birjolaxew suggests having officially supported framework-integration packages. I'd like to propose having a Github Organization to host this core package, plus the framework-integration packages (and possibly packages for other major features!) that are maintained by this team. We could list these packages as "Core Maintained", with another list of "Community Maintained" packages for those that are not under our Org for whatever reason.

@limonte @toverux @acupajoe @samturrell @birjolaxew @patrickhlauke @FinesseRus - What are your thoughts on this?

**Comment by FinesseRus** [comment]
I have the same apprehensions. I agree that the integration packages should be out of the core.

But who will create and support all this integration packages? I think that the core should get a robust API (without a problems like https://github.com/limonte/sweetalert2/issues/794), a simple manual for the API and the integrations will appear by themselves.

**Comment by zenflow** [comment]
> But who will create and support all this integration packages?
Whoever is interested in doing so. For example, I don't use Angular, so I don't have much interest in maintaining that integration directly, but @toverux and some other team members use Angular, so naturally they would maintain it. I use React, so I might soon create a `sweetalert2-react-content` package, and I suspect that @limonte and other team members who are React users would be interested in helping to maintain it.

I should have stated earlier: The advantage that I see of having a sweetalert2 org is having a unified team to look after all of these packages as a whole, and making that clear to consumers.

@toverux How would you feel about moving toverux/ngx-sweetalert2 to a sweetalert2 org? You would of course retain credit as the author.

**Comment by zenflow** [comment]
If we had a sweetalert2 org, it might make sense to move the documentation website to another repo under that org, and include documentation for the various framework integrations.

**Comment by toverux** [comment]
> @toverux How would you feel about moving toverux/ngx-sweetalert2 to a sweetalert2 org?

I'd be happy to do so if everyone do the same :)
I'm just wondering if the npm package should be re-scoped to `@sweetalert2/ngx-sweetalert2` (instead of `@toverux/`) but that would be the 2nd time I bother my users with a package name change.

**Comment by acupajoe** [comment]
I think an org would be the cleanest way to support all the frameworks! So I'll place my vote on that one.

**Comment by limonte** [comment]
I just created the org https://github.com/sweetalert2 and invited you all guys :tada: 

Also, the sweetalert2 repo is transferred to the org, read about transferring repos: 
https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by limonte** [comment]
> I'm just wondering if the npm package should then be re-scoped to @sweetalert2/ngx-sweetalert2 (instead of @toverux/) but that would be the 2nd time I bother my users with a package name change (npm does not support package renaming, so it would be a brand new package at the package manager level).

Let's not do that for now. The whole front-end ecosystem is so unstable, it would be better not to cause additional pain to our users without strong reasons for that.

**Comment by limonte** [comment]
Many thanks for bringing up this discussion @zenflow, it's the absolute necessity for our users to have "officially" supported integrations with different frameworks.

**Comment by limonte** [comment]
I granted the admin privilege to all of you guys, which means the ability to clone, pull, push, and add new collaborators to all repositories. 

This needed to eliminate the 1-human dependency, SweetAlert2 will be good even if a bus will hit me tomorrow.

**Comment by limonte** [comment]
Alright, the migration seems to be successful 

- https://www.npmjs.com/package/sweetalert2
- integrations with Travis, bundlesize and Greenkeeper: https://github.com/organizations/sweetalert2/settings/oauth_application_policy
- poor deprecated Bower seems to be :snail: https://github.com/sweetalert2/sweetalert2/issues/799

**Comment by zenflow** [comment]
@limonte It looks like a lot of links have broken due to the move of this repo to the org.. For example https://github.com/limonte/sweetalert2/blob/master/package.json does not redirect, and even issue/PR references made before the move (like the one at the top of the issue description) are broken..

I'm not seeing this issue with @toverux's repo (https://github.com/toverux/ngx-sweetalert2) .. Not sure how either repo was moved, but maybe removing the new repo at limonte/sweetalert2 would fix it?

**Comment by zenflow** [comment]
@limonte From https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/:

> If you create a new repository under your account with the same name as the transferred repository, existing redirects to the transferred repository will break. Instead, use a different name for the new repository.

**Comment by limonte** [comment]
@zenflow done, now https://limonte.github.io/sweetalert2/ won't work, but I guess the the less lost than all broken links to GitHub issues and files

**Comment by zenflow** [comment]
@limonte That's a shame. I had hoped Github would handle redirecting that as well 🙁. But yeah I agree it's better this way.

**Comment by zenflow** [comment]
Has anyone tried out [sweetalert2-react](https://github.com/alex-shamshurin/sweetalert2-react)?

The author is interested in transferring it to our org and joining our team: https://github.com/zenflow/sweetalert2-react/issues/2

**Comment by zenflow** [comment]
I think we can close this, since the strategy for adoption of new UI frameworks is (I think) pretty clear: implement support in a separate repository under the sweetalert2 org on GitHub.
