### ISSUE TITLE
Old docs are dead

### ISSUE THREAD

**Issue by mayeaux** [sweetalert2/sweetalert2#801]
Can you redirect the old url to the new docs? Google Search is returning only the old docs and it 404s atm

**Comment by limonte** [comment]
> Can you redirect the old url to the new docs?

Unfortunately, it's not possible, related comment: https://github.com/sweetalert2/sweetalert2/issues/798#issuecomment-355589282

**Comment by limonte** [comment]
Hopefully, Google will update the URL in a couple of days.
