### ISSUE TITLE
Nothing in docs about chaining modals in queue

### ISSUE THREAD

**Issue by mayeaux** [sweetalert2/sweetalert2#802]
Old docs had an example for chaining modals but it's no longer available in the new set of docs

**Comment by limonte** [comment]
https://sweetalert2.github.io/#chaining-modals

**Comment by daattali** [comment]
@limonte Looks like this doesn't exist again. The documentation does not have the word "chain" anywhere, and the above link doesn't work. Is chaining possible?

**Comment by limonte** [comment]
https://sweetalert2.github.io/recipe-gallery/queue-with-progress-steps.html
