### ISSUE TITLE
Scrooling background when sweetalert open

### ISSUE THREAD

**Issue by CesarBalzer** [sweetalert2/sweetalert2#807]
Hello @limonte , I'm having problems scrolling in the background, I created a new bootstrap project and I added its component, but it still gives the scrolling when the modal of the sweetalert is opened, I already made some overflow: hidden changes, I tried to force via javascript, but I did not succeed, follow the jsfiddle link where this project is. Thank you

[jsfiddle](https://jsfiddle.net/6x1jdeo3/3/)

**Comment by acupajoe** [comment]
@CesarBalzer this is part of what a 'modal' is defined to be. There have been a couple past issues about what the proper way to handle these are. The default functionality is to disable scrolling on a modal being open. 

You can do one of the following:

1. Use the `backdrop` option and set it to `false`
2. Use a (albeit nasty) `!important` css rule to always have the background scroll.
```
html.swal2-shown,
body.swal2-shown {
  overflow-y: auto !important;
}
```

**Comment by CesarBalzer** [comment]
@acupajoe  thanks for the tip, I did the steps as described, but unfortunately still scrolls, I put in the swal css file, bootstrap, and inline, my custom css nothing apparently changed.

**Comment by acupajoe** [comment]
Option 1: https://jsfiddle.net/6x1jdeo3/5/
Option 2: https://jsfiddle.net/6x1jdeo3/4/

**Comment by CesarBalzer** [comment]
I understand, or one or the other, but testing your example here @acupajoe , I noticed that scrolling still persists, for example, scroll the page to the end and click on the last button, when calling the modal, will scroll the same way. This is making me intrigued.

**Comment by acupajoe** [comment]
See #781 
You'll need to consume the prevent the default button event.

```
$(".btn").click(function(e) {
	e.preventDefault();
  swal({
    title: 'Hello world!'
  });
});
```

**Comment by CesarBalzer** [comment]
I apologize for forgetting button prevention, now it worked perfectly, thank you very much for the attention and the help with the problem.

**Comment by caleb87** [comment]
For those who have a bird brain like myself, I was using href="#" to fire swal. Suddenly I realized why it was scrolling to top of page. 

You should always use: href="javascript:void(0);"

**Comment by Mohamed-Ali7** [comment]
For anyone still experiencing this issue, I'm using SweetAlert2 version 12 and encountered the same problem—every time a SweetAlert was triggered, the page would scroll to the top slightly.

To resolve it, I did the following:

1. Prevent the default action (important)
Make sure you’re calling e.preventDefault(); in your event handler to stop any default browser behavior that might be causing scrolling.

2. Disable scrollbar adjustment by SweetAlert2
Set `scrollbarPadding: false` in your `Swal.fire()` options. This prevents SweetAlert2 from shifting the layout when the scrollbar is hidden

3. Preserve the scrollbar visibility in CSS
Add the following to your CSS to stop SweetAlert2 from forcibly hiding the scrollbar:

```
html.swal2-shown,
body.swal2-shown {
  overflow-y: auto !important;
}
```

These two changes together completely resolved the scrolling issue for me. Hope this helps others facing the same problem!

**Comment by Mohamed-Ali7** [comment]
html.swal2-shown,
body.swal2-shown {
  overflow-y: auto !important;
}

**Comment by Mohamed-Ali7** [comment]
For anyone still experiencing this issue, I'm using SweetAlert2 version 12 and encountered the same problem—every time a SweetAlert was triggered, the page would scroll to the top slightly.

To resolve it, I did the following:

1. Prevent the default action (important)
Make sure you’re calling `e.preventDefault();` in your event handler to stop any default browser behavior that might be causing scrolling.

2.Disable scrollbar adjustment by SweetAlert2
Set scrollbarPadding: false in your Swal.fire() options. This prevents SweetAlert2 from shifting the layout when the scrollbar is hidden

```javascript
Swal.fire({
      // other options
      scrollbarPadding: false
    });
``` 

3.Preserve the scrollbar visibility in CSS
Add the following to your CSS to stop SweetAlert2 from forcibly hiding the scrollbar:

```css
html.swal2-shown,
body.swal2-shown {
  overflow-y: auto !important;
}
``` 

These two changes together completely resolved the scrolling issue for me. Hope this helps others facing the same problem!
