### ISSUE TITLE
Multiple Sweet alerts with toast attribute

### ISSUE THREAD

**Issue by aadriann** [sweetalert2/sweetalert2#808]
Hi, i want show 'n' toast simultaneous.

I've a piece of code like this:
```
function xxx() {
    // ...
    var modals = [];
    modals.push({title: 't1', text: 'text1', toast:true})
    modals.push({title: 't2', text: 'text2', toast:true})
    swal.queue(modals);
    // ...
}
```
this execute all Sweet Alerts one by one, but not all at the same time.

how can i do it?

Thx.

**Comment by limonte** [comment]
Unfortunately, multiple modal/toasts aren't possible for now due to the plugin design which was built for modal popups.

Also, I don't have plans to implement multiple toasts in the near future so if you need that functionality please take a look on toasts specific plugin such as Toastr or Izitoast.

**Comment by aadriann** [comment]
Okey, thanks foe your answer :smile:

**Comment by aadriann** [comment]
Okey, thanks foe your answer :smile:

**Comment by aadriann** [comment]
Okey, thanks foe your answer :smile:

**Comment by aadriann** [comment]
Okey, thanks foe your answer :smile:

**Comment by aadriann** [comment]
Okey, thanks foe your answer :smile:

**Comment by aadriann** [comment]
Okey, thanks foe your answer :smile:

**Comment by aadriann** [comment]
Okey, thanks foe your answer :smile:

**Comment by aadriann** [comment]
Okey, thanks foe your answer :smile:

**Comment by aadriann** [comment]
Okey, thanks foe your answer :smile:

**Comment by aadriann** [comment]
Okey, thanks foe your answer :smile:

**Comment by aadriann** [comment]
Okey, thanks foe your answer :smile:

**Comment by zenflow** [comment]
@aadriann https://github.com/needim/noty also looks like a good option
