### ISSUE TITLE
Queue doesn't work properly with modal with timer

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#809]
```js
swal.queue([
  {title: 'Modal 1', timer: 2000},
  {title: 'Modal 2', timer: 2000}
])
```

jsfiddle: https://jsfiddle.net/ad3quksn/312/

expected: two modal are shown, one after another

actual: only the first modal is shown

reason: closing by timer is a dismissal and queue stops because of the first modal was dismissed. 

Is "two modal are shown, one after another" expected only by me or someone else also expecting that?

**Comment by toverux** [comment]
Oh, very interesting question.

In any case, `timer` does not deserves a special treatment in `.queue()`. _This_ would be unexpected and contrary to the Principle of least astonishment.

Either we :
 - Keep the current behavior, which may be a bit surprising at first but makes perfect sense ;
 - Change the behaviour of `queue()`. It could be a queue argument like "[`onDismissResumeNext`](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/on-error-statement#on-error-resume-next)" but meh ;
 - Make the queue not reacting [on the result of the modal](https://github.com/sweetalert2/sweetalert2/blob/master/src/sweetalert2.js#L1177), but on it's close event. The next modal would be shown when the current one is closed, for whatever reason.

In the first case, the user can still implement a timed queue by hand.

**Comment by aadriann** [comment]
You can use a promise:
`swal(
  {title: 'Modal 1', timer: 2000}).then(function(){
    swal({title: 'Modal 2', timer: 2000})
  })`

**Comment by limonte** [comment]
> Keep the current behavior, which may be a bit surprising at first but makes perfect sense ;

Sounds like a perfect option. I vote for doing nothing and keeping the perfect sense :+1:

**Comment by toverux** [comment]
@aadriann Yep, this is the simplest alternative. It's even simpler with async/await for those who need this:

```js
await swal({ title: 'Modal 1', timer: 2000 });
await swal({ title: 'Modal 2', timer: 2000 });
```

If the user wants to benefit from the queue system, it could also use its own `setInterval()` and take control on the queue with swal.* functions. We don't have the methods to go back/forth in a queue yet, though.

**Comment by limonte** [comment]
> We don't have the methods to go back/forth in a queue yet, though.

Technically it's possible to go forth by `swal.clickConfirm()`: https://jsfiddle.net/ad3quksn/322/

**Comment by aadriann** [comment]
Is not it better to use promises to control the execution of both modals, whether you press the button or if the defined time passes?

Using setInterval is not a bad practice when you want to do something in the future but do not know exactly when you will be able to do that?

Maybe we can use swal.clickConfirm or swal.onClose | swal.onOpen to define another swal.

Thanks for the answers, this helps me to know better this library :smile:
