### ISSUE TITLE
Register sweetalert2 in js.org

### ISSUE THREAD

**Issue by redochka** [sweetalert2/sweetalert2#814]
I noticed that original lib is registered as: https://sweetalert.js.org/

may be we could have: https://sweetalert2.js.org/

**Comment by limonte** [comment]
why?

**Comment by redochka** [comment]
pretty cname :)

**Comment by limonte** [comment]
https://sweetalert2.github.io/ is pretty enough :)

**Comment by redochka** [comment]
Great article about the "scary" deps. Thanks a lot. Lesson learned.
