### ISSUE TITLE
Proposal: New fp (functional programming) API for extending default params

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2#815]
Here is an idea that I've been wanting to propose for a while...

---

# The basic proposal

Currently we have `swal.setDefaults` for extending defaults, which only supports having **one set of defaults at a time**, and relies on global state (which can sometimes make it harder to determine which defaults will be used).

I propose a new `swal.extend(params)` method that returns a modified instance of `swal` that uses defaults extended with the given `params`.

mySwals.js
```js
import swal from 'sweetalert2'
// suppose I want to closely mimic the behavior of Chrome's `alert`, `confirm` & `prompt` ...
export const myAlert = swal.extend({ allowOutsideClick: false, showCloseButton: true })
export const myConfirm = myAlert.extend({ showCancelButton: true })
export const myPrompt = myConfirm.extend({ input: 'text' })
```

Then anywhere in the app, at any time, you could simply call `myAlert('Hi')`, `myConfirm('Are you sure?')`, or `myPrompt('Enter text:')`, without any extra setup.

---

# The inferior alternative

An alternative to both `swal.extend` and `swal.setDefaults` would be to use mixins (e.g. `swal({ ...mySwalPromptMixin, title: 'hiya' })`), which would fix the above mentioned downsides to `swal.setDefaults`, but:
1. I think many people wouldn't think of it
2. Object spread syntax is [still a stage 3 proposal](https://github.com/tc39/proposal-object-rest-spread#status-of-this-proposal) and [not yet implemented in Edge or Safari](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator#Browser_compatibility) (though it is finally in Chrome and Firefox, woohoo!) so for many users, the above example would become `swal(Object.assign({}, mySwalPromptMixin { title: 'hiya' })`
3. It wouldn't be possible to use the `swal(title, html, type)` shorthand (as opposed to passing a params object)
4. Even with the object spread syntax, `swal({ ...myMixin, ...paramsForThisSwal })` is slightly more code & complexity than `mySwal(paramsForThisSwal)`

---

# The extended proposal (no pun intended)

For more dynamic extensions, `swal.extend` could accept a function as it's argument. That function accepts a `params` object as it's first argument, which is the aggregation of the params of all the descendant extensions and of the actual call that fires the swal, and returns a new `params` object to be passed further up the chain.

It may seem confusing or counter-intuitive that the `params` passed to the function are from the descendants (rather than ancestors), but this is what makes it possible to control/determine the effective params based on the *given* params (i.e. the params given to the terminating call to `mySwal()`). Params from extended-with-object descendants still take precedence over params from [either type of] ancestors. Thus `{ text: 'foo' }` would be equivalent to `params => { text: 'foo', ...params }`.

Then, for an example, a robust and unintrusive `sweetalert2-react-content` could be implemented as simply as...

```js
const noop = () => {}
const mounts = [
    ['title', 'getTitle'],
    ['html', 'getContent'],
    ['confirmButtonText', 'getConfirmButton'],
    ['cancelButtonText', 'getCancelButton'],
]
function sweetalert2ReactContent(params) {
    // mutating `params` is fine, since it is a clone of the `params` returned by the descendent
    params.onOpen = params.onOpen || noop
    params.onClose = params.onClose || noop
    for (const [paramKey, getterKey] of mounts) {
        if (React.isValidElement(params[paramKey])) {
            const paramValue = params[paramKey]
            params[paramKey] = ' '
            const childOnOpen = params.onOpen
            params.onOpen = () => {
                ReactDOM.render(paramValue, swal[getterKey]())
                childOnOpen()
            }
            const childOnClose = params.onClose
            params.onClose = () => {
                childOnClose()
                ReactDOM.unmountComponentAtNode(swal[getterKey]())
            }
        }
    }
    return params
}
```

*(Note: I found that the naming of `confirmButtonText` and `cancelButtonText` is a little off, since swal renders them as html. Not sure how y'all want to address that.)*

... and used as simply as ...

```jsx
const mySwal = swal.extend(sweetalert2ReactContent)
mySwal(<div>Hello, React</div>)
```

**These extensions can be composed (!) whereas wrappers cannot.**

Another **simpler** example of an extension function, for **cleanly** adding advertisements to the footer of every (or just some) swal(s) (See https://github.com/sweetalert2/sweetalert2.github.io/pull/4 & https://github.com/sweetalert2/sweetalert2.github.io/commit/ce0604f8da098b7a5dd12e91fcba52981cdf03a5)...

```js
// insert advertisement initialization here
function withAdvertisementInFooter(params) {
    return {
        ...params,
        onOpen: () => {
            $('.bsa-cpc').clone().appendTo('.swal2-modal')
            if (params.onOpen) {
                params.onOpen()
            }
        }
    }
}
```

Finally...

```jsx
const mySwal = swal.extend(withAdvertisementInFooter).extend(sweetalert2ReactContent)
await mySwal({
	html: <div>Using both extensions together should work without complication</div>,
	onOpen: () => console.log('and I can still use `onOpen` without complication or repetition')
})

```

---

I hope this is all very clear. I look forward to getting feedback and or questions from all of you :)

**Comment by zenflow** [comment]
Jesus.. ok now I can code (other things)

**Comment by toverux** [comment]
> I think many people wouldn't think of it

Oh really ? :smile: https://github.com/sweetalert2/ngx-sweetalert2/blob/master/src/swal.component.ts#L176

More seriously, you're right - but it's also because it is a recent feature, and because JavaScript programmers aren't used to immutable/functional paradigms *yet*. Object spreading is soooo useful that I use it almost daily.

100% :+1: about `swalDefaults()`. My only use case is to set really global settings like this:

```js
// makes Swal2 looks like a Bootstrap modal...
// I rarely use more than one UI framework in the same app, nor I change the classes for fun :)
swal.setDefaults({
  customClass: 'modal-content',
  confirmButtonClass: 'btn btn-primary',
  cancelButtonClass: 'btn'
});
```

Then I prefer to use mixins to avoid mutating the global state.

So setDefaults is practical sometimes, in fact. With your proposal and given than setDefaults is removed, I'd need to create a new module that exports my custom mixin and then have imports like `import mySwal from '../../../ui/my-swal'` instead of `from 'sweetalert2'`.

Considering the naming now, it's a detail but I don't like `swal.extend()`. I think it recalls me the terrible epoch of OO programming in ES 5 with all those libraries with their custom `extend` helpers (like `$.extend` and so many others) :smile:

My overall impression is mitigated. First-class support for mixins is interesting and I like the fact that the mixins are functions that can react on their input, input that is coming from the descendants. I also appreciate the functional+immutable approach.

The other part I don't like is... well, it seems too "complex"/opinionated to me. It looks like a new addition to an API that I'd like to see "rethought" from ground zero someday (already had a lot of ideas... should have taken notes). Personnally, I'd prefer to maintain the status quo until something really new emerges and that we feel safe again about changing the API. And use object spreading for the time being. Not very exciting, I know.

But still, this is a good proposal considering the current state of the art on SweetAlert2 :)

**Comment by zenflow** [comment]
> So setDefaults is practical sometimes, in fact. With your proposal and given than setDefaults is removed, I'd need to create a new module that exports my custom mixin and then have imports like import mySwal from '../../../ui/my-swal' instead of from 'sweetalert2'.

I personally would not mind the extra `../`s that much. Really that is an issue with how we write module paths (always relative). If it bothers you i believe you can fix it [(maybe something like this?)](https://stackoverflow.com/a/35265643). 

If there is conceptually a `mySwal` (or more) in your codebase, it is better to place it in a local module, with an appropriate name, than to have it in the ether (unable to be found by tracing what `swal` is defined as). Where do you keep the mixins that you want to use in multiple modules?

---

> Considering the naming now, it's a detail but I don't like swal.extend(). I think it recalls me the terrible epoch of OO programming in ES 5 with all those libraries with their custom extend helpers (like $.extend and so many others) 

The sad reality is that we are in the same situation as those libraries; SweetAlert2 is **not** a proper ES6 `class` (or ES5 function+prototype) that can be `extend`ed. We would have to do a lot of reworking and creating breaking changes to fix this.

---

> [...] seems too "complex"/opinionated to me [...] Personnally, I'd prefer to maintain the status quo until something really new emerges and that we feel safe again about changing the API.

With the amount of gradually reworking and introducing breaking changes that it would take to create a nice standard/un-opinioned extensible interface, we (and the users) are better off if we look to a complete rewrite.

In the interest of this original project (started by @t4t5) I ask you to suppose that a standard `Class` API was not an option and tell me "Are there any parts of the API you find unnecessarily complex or opinionated?"

---

> And use object spreading for the time being. 

Object spread is a decent substitute for `swal.setDefaults`, but as it stands we don't have any kind of extensibility.

---

Last response:

> JavaScript programmers aren't used to immutable/functional paradigms yet

We could help this progress by introducing them to immutability and higher-order functions.

**Comment by zenflow** [comment]
Thank you @toverux for giving me things to think about. I will withdraw this proposal and submit a better one another soon. I have a bit of experimenting to do first.

It should solve the same problem of extensibility, but without the complex and non-standard API.

But it won't solve the problem of needing to import `../../../../somethingContainingMyProjectDefaults`. I still wonder: Where do you keep the mixins that you want to use in multiple modules?

**Comment by zenflow** [comment]
Note that it's more operations to apply a *mixin* that's located in it's own module ...

```js
import swal from 'sweetalert2'
import mySwalMixin from '../../../../my-swal-mixin'
(async () => {
  await swal({ ...mySwal, title: 'foo' })
  await swal({ ...mySwal, title: 'bar' })
})()
```

vs applying a *mySwal function* that's located in it's own module

```js
import mySwal from '../../../../my-swal'
(async () => {
  await mySwal({ title: 'foo' })
  await mySwal({ title: 'bar' })
})()
```

**Comment by zenflow** [comment]
I'll leave this issue open a bit longer in case others want to contribute to the discussion.

**Comment by toverux** [comment]
> I still wonder: Where do you keep the mixins that you want to use in multiple modules?

That's a very good question :) I tend to respect the target framework structure recommandations but they are documenting framework-specific features. Then, I organize things by group of features. That's easier in the backend than in the frontend. I would have difficulties to determine where to put a SweetAlert2 module, indeed. In those cases, I will generally find the "common ancestor" directory in the filesystem hierarchy (could be the application root). There I'd put a "sweetalert2.js" file I think.

I don't want to use Webpack aliases for this either, I don't think this is a legitimate use case. Even if I wanted to, the other tools won't like it (linters, TypeScript, and other static code analysis tools).

But don't get me wrong, I like your proposal for what it permits to do considering the current state of the things. It's just an opinionated move in a specific direction, and maybe this is not necessary considering the real-life needs of extensibility. In most case, some object spreading will do just fine.

-------------

I was also wondering about a new API based on modal instances. For now we have static functions that work at the modal level, and modal options that change the library behaviour.
OOP seems still quite adapted to short-lived modal objects and would permit to separate modal-related functions from the others.

For example (verbose version):

```js
import { queue, show, Modal, Toast } from 'sweetalert2';

const modal = new Modal({ title: 'Title', text: 'Text' });

// instance-specific props/methods
modal.title;
modal.isLoading; // getter
modal.showValidationError('Meh.');
modal.renderer.content; // getter
modal.onClose.subscribe(event => {}); // one day maybe

// modals don't handle their display on screen (there's no modal.show()), static functions do.
// static functions are responsible of handling lifecycle/scheduling, ex. show() will enforce only one modal at a time.
await show(modal);
await queue(modal, modalTwo);
```

For common use cases, there is still a swal() helper:

```js
import swal from 'sweetalert2';

// basically show(new Modal({ }))
await swal({ });
```

What I like here is that there is a better separation of concerns and we can play with our modal instance (reuse, change things, call methods on them and get the result for _that_ swal and _not the currently-displayed one_). A lot of actual uses cases/issues would benefit from that.

The part I don't like: it is mutable and does not (elegantly) solves the extensibility/composition problem.
But this solves other problems that we have with plain object parameters and static-functions that operate on a global state at a _t_ moment.

I'd like to have a best-of-both-worlds solution.

**Comment by zenflow** [comment]
I'm still working with the ideas discussed here, but like I stated in a comment above, I've withdrawn this proposal. Closing.
