### ISSUE TITLE
Two failing tests in my local dev environment

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2#816]
```
not ok 21 Chrome 63.0 - getters
    ---
        actual: >
            null
        stack: >
            TypeError: swal.getActions is not a function
                at Object.QUnit.test (http://localhost:7357/test/qunit/tests.js:53:21)
        message: >
            Died on test #4     at http://localhost:7357/test/qunit/tests.js:39:7: swal.getActions is not a function
        Log: |
    ...
```

```
not ok 35 Chrome 63.0 - showLoading and hideLoading
    ---
        actual: >
            false
        expected: >
            true
        stack: >
                at Object.QUnit.test (http://localhost:7357/test/qunit/tests.js:322:10)
        message: >
            failed, expected argument to be truthy, was: false
        Log: |
    ...
```

Same results for these tests in Firefox.

@limonte What are your results when you run the tests locally? I'm thinking the CI might be broken. Also, why do the CI logs say "118 tests complete" and not "118 tests passed"?

**Comment by zenflow** [comment]
OK, I found out why the tests were failing (PR #818 is a band-aid for that issue).. but doesn't the fact the tests are pointed at dist files mean the tests *should have* failed on CI, and therefore CI is broken?

https://github.com/sweetalert2/sweetalert2/blob/8377c3c4a0ae1eff99b22c654818391e862a5d82/testem.json#L3-L10

**Comment by zenflow** [comment]
Ok, I think the CI is working... I see in the CI logs that you're running `gulp` before doing checks

**Comment by zenflow** [comment]
I was confused about which source of truth the tests had, the source-code ("./src") or the build-code ("./dist").. another symptom of  #820

That `gulp` command is clearing the dist files committed in Git and rebuilding them from src, making the tests effectively use the src files and ignore the dist files (as it should). 👍

**Comment by zenflow** [comment]
Anyways, I guess all thats needed to close this issue is merge #818

**Comment by limonte** [comment]
CI is working because there's `gulp` step before `npm test`, you need to build the `dist` folder before running test, `gulp watch` should do that automatically.

**Comment by zenflow** [comment]
> CI is working because there's gulp step before npm test

Yup

> I see in the CI logs that you're running gulp before doing checks

**Comment by zenflow** [comment]
I guess this is covered by root/fundamental issues #820 and #821 so I'll close this issue
