### ISSUE TITLE
Simplify command-line procedures for developing

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2#821]
Combine these steps into one 
https://github.com/sweetalert2/sweetalert2/blob/8377c3c4a0ae1eff99b22c654818391e862a5d82/README.md#L292-L300

**Comment by acupajoe** [comment]
@zenflow shouldn't `npm test` be run separately from an active development (that's a lot of tests + browsers opening)? 

I'd push for adding `npm test` to be run as a `precommit` hook rather than every time a file is changed.

**Comment by limonte** [comment]
> Combine these steps into one

Well, steps 4 and 5 are already combined, so let's just drop step 5 from readme - #825

Step 6, tests, takes around 10 seconds to perform so I agree with @acupajoe that it's too much to trigger the expensive operation on each save. For me personally, it'll be annoying. Let's not do that.

Also, for some devs it's easier to run tests in browser instead of command line.
 
> I'd push for adding npm test to be run as a precommit hook rather than every time a file is changed.

Performing 10-seconds operation on every single commit could be very annoying and the first rule of ~~Fight Club~~ Git - "commit early, commit often" could become a nightmare :)

**Comment by zenflow** [comment]
I just realized that we are visiting different URLs for our tests. We have two different test harnesses (that look very similar) running our tests. This now explains #819.

When I'm developing locally I remove the `ci` bit from this line...

https://github.com/sweetalert2/sweetalert2/blob/52f2247f3fee9adae9c435e4bbc940d3a2185924/package.json#L68-L68

and do `npm test` and I get this: 

view-source:http://localhost:7357/9274

```html
<!doctype html>
<html>
<head>
<title>Test'em</title>
<script src="//code.jquery.com/qunit/qunit-1.20.0.js"></script>
<script src="/testem.js"></script>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script><script src="test\qunit\deprecated.js"></script><script src="test\qunit\outside-click.js"></script><script src="test\qunit\tests.js"></script><script src="test\qunit\toast.js"></script><script src="dist\sweetalert2.js"></script>
<link rel="stylesheet" href="//code.jquery.com/qunit/qunit-1.20.0.css"/>
<link rel="stylesheet" href="dist&#x2F;sweetalert2.css">
</head>
<body>
<div id="qunit"></div>
<div id="qunit-fixture"></div>
</body>
</html>
```

.. and it's very suitable for active development. The page is not launched automatically. You just visit it whenever you want to run your tests. It's faster than doing `testem ci`; It's telling me "Tests completed in 3457 milliseconds.". (Btw, there seems to be a lot of low-hanging fruit that would speed that up at least 1 or 2 orders of magnitude. All the `setTimeout(foo, 100)`)

I realize now the instructions lead you to something different:

view-source:http://localhost:8080/test/qunit/

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>SweetAlert2 Tests</title>
  <link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.1.1.css">
  <link rel="stylesheet" href="../../dist/sweetalert2.css">

  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
  <script src="https://code.jquery.com/qunit/qunit-2.1.1.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
  <script src="../../dist/sweetalert2.js"></script>

  <script src="./outside-click.js"></script>
  <script src="./deprecated.js"></script>
  <script src="./toast.js"></script>
  <script src="./tests.js"></script>
</head>
<body><script id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.js?v=2.23.5'><\/script>".replace("HOST", location.hostname));
//]]></script>

  <div id="qunit"></div>
  <div id="qunit-fixture"></div>
</body>
</html>
```

Let me try a PR to simplify and optimize things.

**Comment by zenflow** [comment]
@limonte wants to merge #844 which removes linting from the `gulp watch` task and adds step 5 back to the Contributing section of the README (moving away from resolving this issue).

**Comment by zenflow** [comment]
... because:

> it's slowing down the dev process and it's annoying when it crashes.

https://github.com/sweetalert2/sweetalert2/pull/842#issuecomment-360053440

Note that PR #842 fixes the "annoying when it crashes" issue, I think pretty simply. (The flag should be used in the "watch" (or "dev") package script when it's added)

**Comment by zenflow** [comment]
In regard to "it's slowing down the dev process", we could ...

1. have a flag to disable it (or have tasks "watch:build", "watch:lint", and then just "watch" which does both)
2. have it run after the build tasks complete

... but I think removing it from the "watch" task entirely and requiring contributors to constantly manually run another task is a deterioration.

**Comment by zenflow** [comment]
> If a developer really want to be alerted, he/she will set up the IDE properly. I am alerted without keeping an eye on the console https://github.com/sweetalert2/sweetalert2/pull/842#issuecomment-360113617 by @limonte 

It is possibly that a developer wants to be alerted, but has not set their IDE with eslint/standard integration, or their editor or IDE does not support it. @limonte Have you set up sass-lint & tslint integrations in your IDE? (I have not)

**Comment by zenflow** [comment]
Note that in #844 we decided to keep linting within the scope of the watch task

**Comment by limonte** [comment]
@zenflow do you think that we should include testing in `gulp watch`? IMO that would be too much.

If no, that I guess this issue could be closed.

**Comment by zenflow** [comment]
Lol I just prepared a PR to add a `gulp develop` task, with `watch` as a dependency, executing `karma start karma.conf.js --port 8080`... and change `package.scripts.start` to `gulp develop`.

**Comment by zenflow** [comment]
Hopefully you will try it out, and if you don't like using it we can just revert `package.scripts.start` to `gulp watch`?
