### ISSUE TITLE
IE11 onOpen: () syntax error

### ISSUE THREAD

**Issue by sigmatec** [sweetalert2/sweetalert2#829]
Using v7.4.0 and the polyfill for ES6 promises for IE11.  Attempting to use the `showLoading()` spinner example as per the docs, but the following line results in a syntax error and breaks the rest of my JS.

`onOpen: () => {`

I realise 'nobody uses IE' anymore.  Unfortunately some of our clients have no choice due to legacy software.

**Comment by samturrell** [comment]
Try `onOpen: function() {` instead.

**Comment by limonte** [comment]
In order to use arrow functions for IE11, you need to transpile them to ES5.

**Comment by sigmatec** [comment]
I wasn't aware IE didn't support that, so was searching for the 'wrong' things.  Using `onOpen: function() {` does fix it.
Sorry for any wasted time!

**Comment by venkymadurai** [comment]
Guys... please change the examples or add more examples that work in IE as well...

"=>" on IE gave a lot of headaches and was time consuming to find out the cause!

**Comment by gverni** [comment]
Hi @venkymadurai the lack of fat arrow functions support in IE doesn't have anything to do SweetAlert2. In our examples we just use the latest version of JS specification, and the browser compatibility should be part of background skills for a JS developer.

**Comment by limonte** [comment]
Agree with @gverni the lack of JS knowledge of a small number of developers shouldn't be the reason for us to use outdated JS syntax in docs and examples.

**Comment by sigma-technology** [comment]
As one of the noob JS developers you speak of...I still agree with @gverni and @limonte :-)
