### ISSUE TITLE
swal html -with multiple input and select

### ISSUE THREAD

**Issue by dvijai** [sweetalert2/sweetalert2#831]
HI,
i digged a lot but could not find the sweetalert with html param which includes two input and two select box.
anyone to guide and help please.

**Comment by limonte** [comment]
This feature is hopefully upcoming, subscribe to https://github.com/sweetalert2/sweetalert2/pull/824 to get be updated

**Comment by toverux** [comment]
You can define your own inputs in the `html` option and retrieve the inputs values yourself as shown here: https://sweetalert2.github.io/#multiple-inputs

**Comment by dvijai** [comment]
Yes But i want a html param with 2 input and 2 select box, total 4 element in one form working alltogether. seeking help for same with cheer and thanks

**Comment by Vlummy** [comment]
You can write your  html tags as String lines in the html attribute.  Doesnt  matter what you put there. 
![image](https://user-images.githubusercontent.com/32965426/52570462-be17d500-2e13-11e9-85c8-3cbd1ddda96b.png)

I have not tried with select tag, but i guess hat works too

**Comment by lukasmedia** [comment]
@Vlummy select doenst work, all other types do work. Suggestions?

**Comment by gverni** [comment]
Hi @lukasmedia, could you provide a code sample with the issue you are having with `select`?

**Comment by Vlummy** [comment]
> @Vlummy select doenst work, all other types do work. Suggestions?

![image](https://user-images.githubusercontent.com/32965426/53119212-3aff2900-354f-11e9-910d-71c500b33ca5.png)

![image](https://user-images.githubusercontent.com/32965426/53119237-48b4ae80-354f-11e9-9dbd-93250ceb52d9.png)

I can't say what the problem might be without your code, but as far as my attempt goes, it should work fine. I use SweetAlert2

**Comment by limonte** [comment]
@Vlummy you might want to RTFM better https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

**Comment by limonte** [comment]
I would love to have the form builder feature, but I suspect that it will inevitably bring complexity to the codebase and increase the bundle size.

The absence of upvotes on this issue means that the use-case isn't widely needed by devs.

Also, since I'm fighting for simplicity of SweetAlert2's usage and maintenance, I'm closing this issue.

**Comment by Rishgod** [comment]
can someone please fix this, this would be a life saver

**Comment by Stepos36** [comment]
If anyone is looking for a solution, here's how I resolved this:
1. Write a separate method to build the options list HTML like so (iterate through a given array of options assigning corresponding values and text to each HTML option and append it to the result string):
`private buildSelectHtml(optionsList: any[]): string {
let resultString = '';
for (let i = 0; i < optionsList.length; i++) {
                    resultString += `<option ${savedSearch.Quality === optionsList[i].Item.Id ? 'selected' : ''} value=${optionsList[i].Item.Id}>${
                        optionsList[i].Item.Name
                    }</option>`;
}
return resultString;
` 
As you can see, `optionsList` can be any Array.
2. Your Swal html property should look like this:

html: `
            <label for="qualityOptions">Quality: </label>
            <select name="qualityOptions" id="qualityOptions">
                ${this.buildSelectHtml([...this.qualityRatings])}
            </select>
`

With this solution I was able to insert 3 different dropdowns with different options in each one of them into my SweetAlert2 modal (I had a more complicated `buildSelectHtml` method). 
![image](https://user-images.githubusercontent.com/43854058/126555882-c39ab677-fca4-4bc1-9328-145ee7951c39.png)

**Comment by kclaka** [comment]
I ran into this issue today. If it can be fixed it will be very useful. Thanks

**Comment by limonte** [comment]
FWIW SweetAlert2 + Formik example: https://sweetalert2.github.io/recipe-gallery/sweetalert2-formik.html

**Comment by kclaka** [comment]
Thanks but I am using Vanilla JS + HTML
