### ISSUE TITLE
Firefox - ugly dotted outline inside buttons

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#832]
![peek 2018-01-20 13-04](https://user-images.githubusercontent.com/6059356/35182703-8057019e-fde2-11e7-9869-aa1db106d444.gif)

We don't need the default dotted outline since there's already nice indication of focused state.

There's the CSS rule for the outline removal, but it doesn't work as expected:

https://github.com/sweetalert2/sweetalert2/blob/ec991503a99c4bd9f22797ba458895c47986755d/src/sweetalert2.scss#L364

I need help, I can't figure out what Firefox needs to hide that ugliness.

**Comment by patrickhlauke** [comment]
Not tested this (sorry, short on time, so can't build locally etc), but give #833 a whirl
