### ISSUE TITLE
after update - dialogs tiny size (Bootstrap 3)

### ISSUE THREAD

**Issue by R00118189** [sweetalert2/sweetalert2#834]
I have updated package recently and found that all dialogs are now like half size 
is there a way to customise it, now ?
I suspect it conflicts with bootstrap.min.css text-size in html tag; when I untick 10px they render old way.

**Comment by limonte** [comment]
Oh, crap. Why Bootstrap 3 is setting `font-size: 10px;` for html?! How _this_ happened to be so popular?

jsfiddle demonstrating the issue: https://jsfiddle.net/ad3quksn/335/

Luckily, they stopped doing that in v4: https://jsfiddle.net/ad3quksn/336/

But, I guess the upgrade from v3 to v4 isn't an option :)

The solution is: set `font-size: 1rem` for the `html`: 

```css
html {
  font-size: 1rem;
}
```

jsfiddle example: https://jsfiddle.net/ad3quksn/337/

**Comment by limonte** [comment]
It looks like I broke a lot of Bootstrap 3 websites with releasing https://github.com/sweetalert2/sweetalert2/releases/tag/v7.5.0 as a minor and not as a major :man_facepalming: 

Any ideas how I can this would be very welcome :pray:

**Comment by acurrieclark** [comment]
The best solution to this is to add a

```css
.swal2-popup {
  font-size: 1.6rem !important;
}
```
to your css.

This resets the local `swal2` font size to 16px so that its new `em` sizing functions correctly.

This is a common css resizing technique [outlined by Jonathon Snook](https://snook.ca/archives/html_and_css/font-size-with-rem). It isn't required for more modern browsers, so is seeing less use, but is still present in a number of CSS frameworks.

**Comment by fefoweb** [comment]
the solution wrote by @acurrieclark is working!

**Comment by epexa** [comment]
my solution:
```css
.swal2-container {
  zoom: 1.5;
}
```

**Comment by lvalladares** [comment]
This is still happening with 7.15.1 and bootstrap 3

**Comment by limonte** [comment]
@lvalladares the issue is on Bootstrap's side, see the solution https://github.com/sweetalert2/sweetalert2/issues/834#issuecomment-359237178

**Comment by NLZK98** [comment]
> 
> 
> I have updated package recently and found that all dialogs are now like half size
> is there a way to customise it, now ?
> I suspect it conflicts with bootstrap.min.css text-size in html tag; when I untick 10px they render old way.

This really works BUT
.swal2-popup {
  font-size: 1.6rem !important;
}
since your changing the font size the problem is that when you call for an info or warning icon this changes its size too so is there any solution for this?
