### ISSUE TITLE
Create swal from existing container

### ISSUE THREAD

**Issue by Lunatig** [sweetalert2/sweetalert2#848]
Hello 
I'd like to create  swal from existing html container generated by backend.

i found only way 

     onOpen:(modal)=>{
       $('.swal2-content', modal).append( $('#anotherModal .modal-body')).show();
     },

But this way is inconvenient because i cannot use it from another place.

#anotherModal contains element that cannot be copied only moved. they are processed by another js
       html: $('#anotherModal  .modal-body').html(), woudnt work for me.

Does anyone know how to do this?
Thanks fo any help

**Comment by limonte** [comment]
Are you maybe looking for the `target` option?

```
swal{(
  target: $('#anotherModal .modal-body')[0]
})
```
