### ISSUE TITLE
Proposal: Add the ability to define modal FOOTER 

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#850]
Add the `footer` parameter which will work similar way to the `html`:

https://github.com/sweetalert2/sweetalert2/blob/master/src/sweetalert2.js#L99-L109

The appearance will be similar to this screenshot:
 
![](https://bootstrapbay.com/blog/wp-content/uploads/2017/02/image.png)

**Comment by limonte** [comment]
The implementation should be pretty straightforward but feel free to express your thoughts or suggestions.

**Comment by zenflow** [comment]
My only thought is Yes!

**Comment by toverux** [comment]
Nothing to add to what @zenflow said :smile:
