### ISSUE TITLE
IE11 broken

### ISSUE THREAD

**Issue by rskaarup** [sweetalert2/sweetalert2#858]
Anyone tell me why IE11 is not working? 

Fiddle not necessary, just browse to 

https://sweetalert2.github.io

IE11 shows:
SCRIPT1001: Syntax error

Apparently IE11 doesnt like the "=>" operator after ".then" - and javascript execution stops.

**Comment by zenflow** [comment]
Yes, thank you for reporting @rskaarup .. we are working on this in issue https://github.com/sweetalert2/sweetalert2.github.io/issues/3 and PR https://github.com/sweetalert2/sweetalert2.github.io/pull/6

SweetAlert2 is fully compatible with IE11, just the documentation site is not at this moment.

**Comment by limonte** [comment]
https://sweetalert2.github.io/ is now working for IE11, @rskaarup please check it out :tada:

**Comment by rskaarup** [comment]
Yes, it works now! Not sure what you did though. IE11 doesnt seem to care about the “=>”’s on your site now.

Changing

.then((result) => {

to

.then(function(result) {

worked for me.

Br
Rasmus
