### ISSUE TITLE
Got TypeError when title is null or undefined

### ISSUE THREAD

**Issue by haha02** [sweetalert2/sweetalert2#863]
Passing a `title` argument explicitly declared as `null` or `undefined` will cause a TypeError (something like `swal({ title:null })`).
The issue seems due to the code tries to invoke `split` function on `title ` in order to replace all `'\n'` character to `'<br>'` when the argument exists.

My use case is the title is returned by a function call, and that function returns `undefined` sometimes. Like this:
```js
swal({
  title: funcA(),
  ...
})
```
The document says the title argument defaults to `null`, so I think this little finding might worth reporting. Although it is very easy to avoid.

SweetAlert2 version: `7.8.2`
Browser: Chrome (63.0.3239.132, 64-bit) & FireFox (57.0.4, 64-bit)

**Comment by zenflow** [comment]
Thanks for reporting @haha02. Yes, I think `swal({ title:null })` should work without error. Another use case (in addition to yours) is when using `swal.setDefaults` you might want to set the title back to nothing/empty.

**Comment by toverux** [comment]
Yep, I've already had the problem, and @zenflow is right.

Suggestion: replacing `\n` with `<br>` is quite opinionated too. The library should not look at the content of the string and change it like this. I don't expect that, and probably most of our users aren't either.
If the user wants line breaks, it can be explicit and pass actual HTML.
I propose (if everyone agrees) to mark this issue with `next major` and remove that behaviour at this moment.

**Comment by limonte** [comment]
Let's just fix the null-value issue. I would not introduce the breaking change without strong reasons for that. Some people are expecting `\n` to `<br>` conversion and I don't see any reasons why we shouldn't meet their expectations, e.g. the argument from https://github.com/t4t5/sweetalert/pull/50 

> The default javascript's alert supports \n as line-break so sweetalert should too.

**Comment by toverux** [comment]
Hm, the original reson makes sense but I still don't like the idea. But this is not that problematic, otherwise I would already have opened an issue.

Love the new brute-force nulls test https://github.com/sweetalert2/sweetalert2/pull/866/files#diff-7da8a9cc3c2584ab7290b6527317d459R769, excellent idea 😄
