### ISSUE TITLE
Allow backdrop to take a css color as value

### ISSUE THREAD

**Issue by StephanBijzitter** [sweetalert2/sweetalert2#864]
This would be a backward compatible feature request:
`backdrop: true` would remain the same as it is and show the default backdrop. However, `backdrop: '#ff0000'` would show a red backdrop, for example.

The reason for this change is because I only have one sweetalert where I want a different backdrop, which would be `rgba(0, 0, 0, 0.05)`, but I cannot currently do this.

**Comment by limonte** [comment]
Released in [v7.9.0](https://github.com/sweetalert2/sweetalert2/releases/tag/v7.9.0)

Now you can use Nyan Cats as a backdrop https://jsfiddle.net/ad3quksn/368/ :unicorn:

**Comment by StephanBijzitter** [comment]
I'm seriously considering putting that nyancat on our application's 404 page, too bad it's not my call
