### ISSUE TITLE
Javascript inside the Html is not working at all

### ISSUE THREAD

**Issue by abuzuhri** [sweetalert2/sweetalert2#870]
Any javascript inside the Html not working , i need to add some event with the Html , any one have the same issue here ?

`swal({
              title: '<B>2018</B>',
              type: 'info',
              html:
                '<button type="button" onclick="alert("33")">Jan</button> ',
              showCloseButton: true,
              showCancelButton: true,
              focusConfirm: false,
              confirmButtonText:
                '<i class="fa fa-thumbs-up"></i> Great!',
              confirmButtonAriaLabel: 'Thumbs up, great!',
              cancelButtonText:
              '<i class="fa fa-thumbs-down"></i>',
              cancelButtonAriaLabel: 'Thumbs down',
            })`

**Comment by limonte** [comment]
https://stackoverflow.com/questions/ask

**Comment by abuzuhri** [comment]
Why you closed it's not general things it's only in the sweetalert2 ?

**Comment by acupajoe** [comment]
> If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our Gitter or submit it to StackOverflow instead of GitHub, and make sure you add the sweetalert tag to the question.

From [CONTRIBUTING.md](https://github.com/sweetalert2/sweetalert2/blob/master/.github/CONTRIBUTING.md)
