### ISSUE TITLE
Record a new gif for README

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#871]
The current one is outdated, it doesn't show the keyboard a11y (button outline).

Also, it would make sense to demonstrate multiple modals and multiple features in the single gif, not just the simplest one.

At the end, I will make a jsfiddle for the purpose of easy adding/changing the gif in the future. The initial jsfiddle: https://jsfiddle.net/ad3quksn/356/

Any suggestions are welcome.

**Comment by toverux** [comment]
From the website, the _"A message with custom width, padding and background"_ demo could be good to show. 

Input validation, too. We can merge it with the loader example.

But not much more, GIFs are slow to load. Too bad we can't do `<img src="demo.webm">`.

**Comment by limonte** [comment]
Something like this: https://jsfiddle.net/ad3quksn/358/ ?

![peek 2018-02-01 12-57](https://user-images.githubusercontent.com/6059356/35675122-90051dda-074f-11e8-9fc1-86233338ed83.gif)

What do you think?

**Comment by limonte** [comment]
What do you think about this one: https://jsfiddle.net/ad3quksn/360/ ?

Recorded gif:

![peek 2018-02-01 13-11](https://user-images.githubusercontent.com/6059356/35675675-945b3570-0751-11e8-9591-2fa688324762.gif)

**Comment by limonte** [comment]
What do you think about this one: https://jsfiddle.net/ad3quksn/360/

Recorded gif:

![peek 2018-02-01 13-171](https://user-images.githubusercontent.com/6059356/35676031-ee4b3eb2-0752-11e8-917f-b41b8d6814ff.gif)

**Comment by limonte** [comment]
What do you think about this one: https://jsfiddle.net/ad3quksn/361/

Recorded gif:

![peek 2018-02-01 13-29](https://user-images.githubusercontent.com/6059356/35676330-06c1e44a-0754-11e8-9bae-e1aa596cf072.gif)

**Comment by limonte** [comment]
What do you think about this one: https://jsfiddle.net/ad3quksn/363/

Recorded gif:

![peek 2018-02-01 13-34](https://user-images.githubusercontent.com/6059356/35676654-3e5d907e-0755-11e8-9dba-3e6f355ba8a1.gif)

**Comment by limonte** [comment]
`<offtopic>`

SweetAlert2 rocks! http://www.npmtrends.com/sweetalert-vs-sweetalert2

![](https://img.shields.io/npm/dm/sweetalert2.svg)

`</offtopic>`

**Comment by toverux** [comment]
Awesome !

It's much better than before!

 - Maybe the "Oops" one isn't necessary. People will quickly find out that there are more icons.
 - I think we can remove the success confirmation for the AJAX request and shorten the title.
 - Make the toast centered and maybe artificially bigger? I don't think it is important for the demo GIF to be a wysiwyg.
 - Remove the backdrop. We don't even see it's a backdrop here, however the gray is awful. A white background on the white background of GitHub will be magnificent.

(I'd like to try to implement my propositions now but I don't much have the time today :smile:)

**Comment by limonte** [comment]
> Maybe the "Oops" one isn't necessary. People will quickly find out that there are more icons.

Oops looks nice, I'd like to keep it, but I moved the success one to the end of the AJAX request example.

> I think we can remove the success confirmation for the AJAX request and shorten the title.

The title shortened. Success confirmation is useful IMO just to demonstrate that modals can pass data to each other. 

> Make the toast centered and maybe artificially bigger? I don't think it is important for the demo GIF to be a wysiwyg.

Good idea, the toast example is now bigger (`1.3rem`), but I think the position demonstration is also useful, let's keep it in `top-end` corner.

> Remove the backdrop. We don't even see it's a backdrop here, however the gray is awful. A white background on the white background of GitHub will be magnificent.

Yay! Magnificent indeed!

![peek 2018-02-01 14-20](https://user-images.githubusercontent.com/6059356/35678357-ab93d7e2-075b-11e8-8cee-054520494134.gif)

This is not the final version because there's the noticeable horizontal scrollbar in the ajax confirmation example. Reported: #872

**Comment by toverux** [comment]
Just wanted to say that it's perfect :)

**Comment by acupajoe** [comment]
@limonte what about that new footer feature?

**Comment by limonte** [comment]
> @limonte what about that new footer feature?

Hm, good point! I forgot to demonstrate it. Will do.

**Comment by acupajoe** [comment]
@limonte bump on the recording of a new gif - I'm happy to record one if need be!

**Comment by limonte** [comment]
Footer added: http://jsbin.com/cisinuyiyu/edit?html,css,js,output

Result gif:

![peek 2018-02-20 14-41](https://user-images.githubusercontent.com/6059356/36424531-433d944e-164c-11e8-9382-d98f94417125.gif)

**Comment by limonte** [comment]
I'll keep this open for, now. The result is good, but not perfect :rage: I'll try to do better.
