### ISSUE TITLE
Internet explorer doesn't accept syntax

### ISSUE THREAD

**Issue by valentindragan** [sweetalert2/sweetalert2#892]
then((result) => {

**Comment by limonte** [comment]
Indeed, arrow functions aren't supported by IE: https://caniuse.com/#feat=arrow-functions

You should either use old-school function syntax: `then(function (result) {` or use transpiler, e.g. Babel https://babeljs.io/docs/plugins/transform-es2015-arrow-functions/

**Comment by valentindragan** [comment]
Sorry I did not make myself understood in regards with where the problem stands.
Some of the examples used on Sweet Alert2 demo page include the arrow functions. That is the issue I wanted to report.
Thanks!

**Comment by limonte** [comment]
SweetAlert2 examples are transpiled with Babel: https://github.com/sweetalert2/sweetalert2.github.io/pull/6

**Comment by jamrsim** [comment]
> Indeed, arrow functions aren't supported by IE: https://caniuse.com/#feat=arrow-functions
> 
> You should either use old-school function syntax: `then(function (result) {` or use transpiler, e.g. Babel https://babeljs.io/docs/plugins/transform-es2015-arrow-functions/

It would be extremely helpful to link this comment to [https://github.com/sweetalert2/sweetalert2#browser-compatibility](url)
