### ISSUE TITLE
Access to SweetAlert2 analytics

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#893]
I just granted the access to SweetAlert2 Google Analytics to @zenflow because his @gmail is public.

@toverux @birjolaxew @samturrell @acupajoe if you want to have the access to Google Analytics as well, please send me an email from your Google account either in this thread or via email limon.monte@gmail.com :nerd_face:

**Comment by toverux** [comment]
I like statistics, so, why not :smile: 
Sending my email by email!
