### ISSUE TITLE
.then function doesn't work in iOS devices

### ISSUE THREAD

**Issue by RefinedSaltqwe** [sweetalert2/sweetalert2#895]
I'm working on a project right now and been using this awesome plugin. I have an issue with iOS devices. Everything works fine until I included the (then) function, it won't pop up when it's supposed to pop up. I tried 3 different iOS devices. Tried Chrome and Safari all have the same result. It works perfectly on Android devices. By the way, I'm using a local server xampp. I was wondering if there's an alternative for (.then) function. I hope someone can help me.

**Comment by zenflow** [comment]
@RefinedSaltqwe jsfiddle?

p.s. Does this not pop up when you (as a new contributor) go to open a new issue? https://github.com/sweetalert2/sweetalert2/blob/master/.github/CONTRIBUTING.md

**Comment by RefinedSaltqwe** [comment]
I was just using the examples here https://sweetalert2.github.io/ and then just add a button to trigger the swal. 
this one doesn't work on iOS devices: https://jsfiddle.net/ad3quksn/383/
this one works without the .then function: https://jsfiddle.net/ad3quksn/384/

**Comment by limonte** [comment]
Two options for you:

1. Recycle your old iOS device https://i.imgur.com/RdYRJ3w.png

2. Read the documentation about including the Promise polyfill for IE11 and old iOS devices: https://github.com/sweetalert2/sweetalert2#usage
