### ISSUE TITLE
Allow preConfirm to prevent dialog closing

### ISSUE THREAD

**Issue by dchekanov** [sweetalert2/sweetalert2#896]
It would be nice to be able to keep the dialog open if some condition is not met in preConfirm logic.

Previously it was possible by returning a rejected promise, but with v. 7 it looks like the only way to prevent closing is to call `swal.showValidationError`. 

Usage example, if I want user to confirm a destructive action:

```javascript
preConfirm: function() {
  if (!confirm('Are you sure?')) {
    // possible solution - a flag that would instruct swal to keep the dialog open
    swal.keepOpened = true;
    return;
  }
  // proceed otherwise
}
```

As a workaround I had to do this:

```javascript
onOpen: function(el) {
  var container = $(el);
  var originalConfirmButton = container.find('.swal2-confirm');
  var clonedConfirmButton = originalConfirmButton.clone();

  originalConfirmButton.hide();
  clonedConfirmButton.insertAfter(originalConfirmButton);

  clonedConfirmButton.on('click', function() {
    if (confirm('Are you sure?')) originalConfirmButton.click();
  });
}
```

**Comment by zenflow** [comment]
@dchekanov Thanks for opening this issue! 

Yes, I think you should be able to prevent the closing without showing a validation error. 

I think your proposed API would be acceptable.. but I am not a fan of communicating via global variables/state (yes, I know the method of calling swal.showValidationError has the same issue).. does anyone have any alternate suggestion?

**Comment by limonte** [comment]
How about

```js
preConfirm: function() {
  if (!confirm('Are you sure?')) {
    return false;
  }
  // proceed otherwise
}
```

Or even shorter with ES6:

```js
preConfirm: () => confirm('Are you sure?')
```

**Comment by dchekanov** [comment]
> How about returning false value?

I didn't suggest that initially because it would only work for sync. code. Could it also cause `result.value` to be falsy in `swal().then()`, making it look like user clicked "Cancel"?

Thank you for @zenflow and @limonte for responding so quickly.

**Comment by dchekanov** [comment]
Sorry, wrong button :)

**Comment by zenflow** [comment]
> I didn't suggest that initially because it would only work for sync. code. 

Not sure I understand this statement. Sync and async `preConfirm`s should work the same as of version 7.

> Could it also cause result.value to be falsy in swal().then(), making it look like user clicked "Cancel"?

Nope. I had a similar concern too, but if the result of `preConfirm` is falsy, then the original value passed to `preConfirm` is used. If there is no `input` option, `result.value` will be `true`.

https://github.com/sweetalert2/sweetalert2/blob/8cc05c8823a50589cd735cf00f16596556a1c5aa/src/sweetalert2.js#L576-L585

Besides, if `preConfirm` returns false, then there will be no `result` at all for that case, since the swal will not complete. My concern was that you would no longer be able to use `preConfirm` to make the `result.value` a boolean (possibly `false`), but this was never possible, for the above reason.

**Comment by dchekanov** [comment]
@zenflow Thank you for clarifying. Looks like a neat solution then 👍

**Comment by limonte** [comment]
:shipit: shipped in v7.11.0 :tada: 

https://jsfiddle.net/ad3quksn/386/

**Comment by josteph** [comment]
@limonte Doesn't seem to be working on my end. Clicking cancel button on `confirm` dialog will not trigger the else statement in `swal().then()`. Or am I missing something here?

**Comment by BMahabir** [comment]
Just found this yesterday.... this is exactly what I need, but it isn't working for me.  Whenever I have `return false;` in the preConfirm() section as the return value, I get this error thrown at me in Ember : ```sweetalert2.js:944 Uncaught TypeError: params.preConfirm(...).then is not a function```

**Comment by gverni** [comment]
@BMahabir can you provide a live example? BTW, if you want to see `preConfirn` _in action_ you can have a look to [this example](https://sweetalert2.github.io/sweetalert2-examples/forms/login/) (source code [here](https://github.com/sweetalert2/sweetalert2-examples/blob/master/src/forms/login/form-login.js))

**Comment by limonte** [comment]
@converseKarl https://sweetalert2.github.io/recipe-gallery/login-form.html
