### ISSUE TITLE
Dismiss with Enter, bubbles back to input[type=text] and retriggers

### ISSUE THREAD

**Issue by anionic** [sweetalert2/sweetalert2#900]
If I submit a bad text field value with the Enter key, which calls swal('bad input'), then dismiss the alert with the Enter key, the keyup event is also delivered to the original text input field, thus immediately retriggering the alert.  This doesn't happen with JavaScript alert().

This retriggering doesn't happen where a button with focus is activated by Enter.

**Comment by acupajoe** [comment]
@anionic please submit your issue with a jsfiddle demonstrating the issue as outlined in [CONTRIBUTING.md](https://github.com/sweetalert2/sweetalert2/blob/master/.github/CONTRIBUTING.md)

**Comment by anionic** [comment]
your link to CONTRIBUTING.md gives me a 404, but I get the idea ;-)

see https://jsfiddle.net/anionic/epewzkao/16/

**Comment by limonte** [comment]
> your link to CONTRIBUTING.md gives me a 404, but I get the idea ;-)

CONTRIBUTING.md has been renamed to ISSUE_TEMPLATE.md in  https://github.com/sweetalert2/sweetalert2/pull/904

> see https://jsfiddle.net/anionic/g4be1kxh/

Lovely jsfiddle,  thanks @anionic! Looks like a bug indeed.

**Comment by limonte** [comment]
I thought it's a trivial `stopPropagation` fix, but it's not. The help from JS events guru would be welcome!

**Comment by Kuzcoo** [comment]
Hey,

I took a look, I guess we could delay `states.previousActiveElement.focus()` by something like 100ms (too short to be noticeable but delayed enough to not catch the keyup event from the input again).
Actually in the fiddle above, with the native alert, if you keep "Enter key" pressed and release it after the focus is set back to the input, you got the same result.

**Comment by limonte** [comment]
Hey @Kuzcoo 

> I took a look, I guess we could delay states.previousActiveElement.focus() by something like 100ms (too short to be noticeable but delayed enough to not catch the keyup event from the input again).
Actually in the fiddle above, with the native alert, if you keep "Enter key" pressed and release it after the focus is set back to the input, you got the same result.

Sounds like a potentially working solution to me, could you please submit a PR with that change?

**Comment by zenflow** [comment]
I proposed a solution here https://github.com/sweetalert2/sweetalert2/pull/983#issuecomment-370278623 + https://github.com/sweetalert2/sweetalert2/pull/983#issuecomment-370350491

I'm not 100% it can be done safely (not causing problems with event listeners on that element), but it might be worth playing with.

Another solution would be to have an option/param to trigger success on keyup instead of keydown. That would be cleaner to implement. @anionic How do you feel about using this proposed option, vs the above idea of messing with your input's onkeyup handler?

**Comment by zenflow** [comment]
@Kuzcoo FYI I had an issue with the proposed solution of "delay states.previousActiveElement.focus() by something like 100ms"

See https://github.com/sweetalert2/sweetalert2/pull/983#issuecomment-370277177

**Comment by anionic** [comment]
Sorry if I opened a can of worms ;-)  I have a workaround which I'm happy with, using .keypress() instead of .keyup() for which swal behaves just like alert; if you hold the Enter key down for a long time, keyboard repeat hell breaks loose, as it should. To me, keypress seems higher-level that keyup, so it's less "workaround" and more "improved code style"?
