### ISSUE TITLE
Icon Color Options

### ISSUE THREAD

**Issue by emaildano** [sweetalert2/sweetalert2#901]
Is it possible to change the Icon Color? I see it's a CSS class, but not sure if it's able to be overridden.

Thanks!

**Comment by acupajoe** [comment]
@emaildano it can be overridden, it just requires that you use a selector that is equal or greater specificity see the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

For instance

Example: https://jsfiddle.net/ad3quksn/387/

**Comment by emaildano** [comment]
@acupajoe 

I'm looking more at the swal API options. It's possible to change the button colors with the options but not the icon color.

Something like this:

`iconColor: '#333',` since we have `confirmButtonColor: '#3085d6',`

```
swal({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  type: 'warning',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  iconColor: '#333',
  confirmButtonText: 'Yes, delete it!'
}).then((result) => {
  if (result.value) {
    swal(
      'Deleted!',
      'Your file has been deleted.',
      'success'
    )
  }
})
```

**Comment by emaildano** [comment]
I see this isn't a current feature but would it be open to it or a PR?

**Comment by acupajoe** [comment]
@emaildano Ah, this is a different issue then! I don't think this is a feasible addition to our API but I'll leave it up to other contributors to weigh in. 

The addition of API options would have to include color options for *all* icon types. Each icon would need to have their `border-color` and `color` attributes customizable. 

IMO, the better use case would be to use the `customClass` API variable and define your custom button styles using that class.

Thoughts @limonte, @toverux?

**Comment by limonte** [comment]
Icon colors are customizable with SASS variables: https://github.com/sweetalert2/sweetalert2/blob/master/src/variables.scss#L5-L10

It doesn't make sense to add more js params for styling.

**Comment by emaildano** [comment]
@limonte 

> It doesn't make sense to add more js params for styling

Correct me if I'm wrong but currently there are two options. This addition makes it 3, not a zillion. If all default params were able to be overridden it would be the following:

- Buttons Cancel
- Button Confirm
- Background Color
- Icons Color

4 < than a zillion

At any rate, thanks for the feedback!

**Comment by harri4007** [comment]
I know this is closed but I ran into this problem today using it for the first time.  I wanted to change icon to red.  Here's what I did with the css to make it work: 

.swal-icon--warning {
    border-color: red;
    -webkit-animation: none;
    animation: none;
}

**Comment by limonte** [comment]
Hm, the number of upvotes here tells me that I was wrong closing this issue, reopening.
