### ISSUE TITLE
[iOS] Modal with long text doesn’t scroll very fluidly

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#905]
Source: https://www.reddit.com/r/javascript/comments/7x0dpk/sweetalert2_a_beautiful_responsive_highly/du4tx43/

Anyone knows how to fix long text modals to have the native scrolling?

**Comment by samturrell** [comment]
```css  
overflow-y: scroll;
-webkit-overflow-scrolling: touch;
```

I believe.

**Comment by limonte** [comment]
Exactly, thanks @samturrell :beers:
