### ISSUE TITLE
1,000,000 downloads, the hottest post on r/javascript, the 3rd most popular JS repo on GitHub 🎉 🎉 🎉

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#906]
It looks like we made a :gem: from SweetAlert2 :rocket: :1st_place_medal: :tada:

Congratulations to all collaborators and contributors! :beers:

I would like to thank these brilliant minds for the significant help on this project:

 - @zenflow
 - @toverux
 - @acupajoe
 - @samturrell
 - @birjolaxew
 - @patrickhlauke

And I would like to thank @github for giving me the possibility to co-work with all of you! <3

<details>
  <summary>(Check your PayPal, there should be a small donation from SweetAlert2 for all of you)</summary>
  <img src="https://i.imgur.com/zSO12pQ.png">
</details>

---

My girlfriend is saying that I'm spending too much time on this project and don't get any comparable to my hourly rate money. My answer is:

> ### We are here not just to pay our bills, but to _make a difference_.

And we _are_ making difference by delivering one of the best libraries in the world for JS popups and we're improving it almost every day.

---

I don't have enough skills to make such an awesome plugin which is used in **thousands of real successful projects**. It's because of you guys, SweetAlert2 is so sweet and there are so many positive comments in my yesterday's post on Reddit: https://www.reddit.com/r/javascript/comments/7x0dpk/sweetalert2_a_beautiful_responsive_highly/

---

Because of upcoming 1,000,000 downloads (tomorrow), I made a simple tool for quickly checking the total number of npm downloads: https://limonte.github.io/total-npm-downloads/?package=sweetalert2

![](https://i.imgur.com/yTiEb4P.png)

---

And we did it [again](https://github.com/sweetalert2/sweetalert2/issues/498)!, SweetAlert2 is in the top (currently, the 3rd most popular) of [trending JS repositories on GitHub](https://github.com/trending/js):

![](https://i.imgur.com/fbddNdh.png)

---

Have a pleasant day guys and rock-n-roll!

**Comment by zenflow** [comment]
This truly is a triumphant moment!!!

**Comment by zenflow** [comment]
Hats off to @limonte for all the things he does to make this such a sweet project!!!

**Comment by ChriStef** [comment]
Well done, congratulations  to all, and a big thank you 👍

**Comment by User934903920432** [comment]
Congratulations! Been using it for a while now and really love it. Makes some websites so much cleaner.

**Comment by patrickhlauke** [comment]
Congrats. And, just like last time: your little gift was appreciated, but absolutely not necessary (particularly as i've been very inactive here for ages)

**Comment by zenflow** [comment]
> sweetalert2 was downloaded 1,005,075 times.

Woooooo Hooooo!!!

**Comment by zenflow** [comment]
We will probably break 5000 stars today too!

**Comment by limonte** [comment]
> We will probably break 5000 stars today too!

Easily, since we're in top of https://www.reddit.com/r/webdev/ :muscle:

**Comment by cassianomon** [comment]
Thank you @limonte @toverux and all the other guys, I mention you two because I see you answering questions and helping people everyday, even outside of sw2! ❤️

**Comment by limonte** [comment]
This tiny article about SweetAlert2 also got a lot of claps and brought some new happy users: https://codeburst.io/open-source-sweet-alert-2-c6bc8224d958

**Comment by limonte** [comment]
> We will probably break 5000 stars today too!

Let's aim 6,000, SweetAlert2 is the 2nd best today :sunglasses: 
 
![](https://i.imgur.com/UQ4VVqA.png)

**Comment by limonte** [comment]
JS daily tweeted about SweetAlert2:

[![image](https://user-images.githubusercontent.com/6059356/36343241-3b340ed6-1412-11e8-87a8-6f6e20bc625a.png)](https://twitter.com/JavaScriptDaily/status/964629969220620288)

**Comment by limonte** [comment]
SweetAlert2 in the latest JavaScript Weekly digest: http://javascriptweekly.com/issues/373 🎉

**Comment by limonte** [comment]
> sweetalert was downloaded 1,029,870 times.

> sweetalert2 was downloaded 1,030,109 times.

:rocket:

**Comment by toverux** [comment]
wow, perhaps the most symbolic milestone. This is not a shitty fork :)

**Comment by limonte** [comment]
[![](https://starcharts.herokuapp.com/sweetalert2/sweetalert2.svg)](https://starcharts.herokuapp.com/sweetalert2/sweetalert2)

**Comment by toverux** [comment]
I don't always look at the stargazers counter, but when I do...

![image](https://user-images.githubusercontent.com/1343250/36872191-b044bf72-1da4-11e8-86c0-8d3179d42b62.png)

**Comment by zenflow** [comment]
@limonte Where is your graph from?

**Comment by limonte** [comment]
https://starcharts.herokuapp.com/sweetalert2/sweetalert2
