### ISSUE TITLE
disable auto injection of CSS using NPM

### ISSUE THREAD

**Issue by Ragers** [sweetalert2/sweetalert2#907]
Hi when I include the sweetalert2 package with require('sweetalert2') it automatically adds the CSS to the footer of my page. I use SASS and my CSS is included in the header of my page, meaning I cannot adjust any of the sweetalert CSS. How do I prevent the plugin to not inject CSS but rather just use only the javascript and seperatly import the CSS into my SASS files?

**Comment by samturrell** [comment]
Hi @Ragers,

The default dist file auto-injects the styles for convenience, so you'll have to be more explicit with your imports. Try `require('sweetalert2/dist/sweetalert2.js');`

**Comment by Ragers** [comment]
@samturrell thanks, exactly what I needed.
