### ISSUE TITLE
Form inside Sweetalert

### ISSUE THREAD

**Issue by User934903920432** [sweetalert2/sweetalert2#908]
Hi,

I know that Sweetalert2 is ment to replace the browsers alert function, and not really as a modal.
But how save would it be to add a form into a SweetAlert ? 
e.g: https://codepen.io/anon/pen/oEeRXw

Obviously I could just use a bootstrap modal, but since I didn't use a single modal yet on my site and got plenty of SweetAlerts i'd like to stick to this because of consisity.

**Comment by samturrell** [comment]
Hi @User934903920432,

Keep an eye on #824 - form builder functionality and API is coming soon. Trying to find some time to finish off, but it's 80% there! Stay tuned.

**Comment by User934903920432** [comment]
Awesome, looks pretty cool. Think that this might be a really nice feature. I'll keep an eye on it.

**Comment by toverux** [comment]
@User934903920432 don't forget you can actually do what you want given the current state of the things
 🙂 
Take a look at this example: https://sweetalert2.github.io/#multiple-inputs

**Comment by zenflow** [comment]
@User934903920432 It would be really great to have some feedback on that PR #824 .. You can install it in your project with `npm install github:sweetalert2/sweetalert2#06143789ebbda33a585a726c5acc156eb9cc5949` (latest commit in that branch) and then import with `require('sweetalert2/src/sweetalert2')`

**Comment by AmjadIqbal** [comment]
Hey I hope you guyz like this laravel package which support forms https://amjadiqbal.github.io/sweetalert/forms.html .
 
 you can live chat with me also.
