### ISSUE TITLE
TypeError: Cannot read property 'unsubscribe' of undefined

### ISSUE THREAD

**Issue by mukeshgupta** [sweetalert2/sweetalert2#909]
Integrated Sweet alert 2 but getting below issue on application home page
![whatsapp image 2018-02-14 at 8 08 07 pm](https://user-images.githubusercontent.com/143001/36209846-e3a2609c-11c2-11e8-8d9c-d52c27759025.jpeg)

**Comment by mukeshgupta** [comment]
This error is on ngDestory function

**Comment by limonte** [comment]
THE BEST CODE SNIPPET I EVER SEEN!

**Comment by toverux** [comment]
Well at least there's code highlighting and indentation this time 😄 

@mukeshgupta This seems to be this problem : https://github.com/sweetalert2/ngx-sweetalert2/pull/42
As there's a second impacted user, I presume it's a real bug. But I've never reproduced it nor I have any idea of what's the problem. If you can provide help, a repro or anything...
