### ISSUE TITLE
FEATURE REQUEST: Ability to pass in function to animate parameter

### ISSUE THREAD

**Issue by tdeignan** [sweetalert2/sweetalert2#910]
Ideally, I would like to be able to do the following:

swal.setDefaults({
    animate: function() {return !swal.isVisible();}
});

This will make the transition between chained sweetalerts less jarring.

Thank you,
Tim

**Comment by acupajoe** [comment]
@tdeignan if you'd like to mess around with that PR, I believe that should cover the functionality you've requested!

**Comment by limonte** [comment]
Thanks for the nice feature-request, @tdeignan! Shipped in https://github.com/sweetalert2/sweetalert2/releases/tag/v7.12.0

**Comment by tdeignan** [comment]
Thank you!

**Comment by tdeignan** [comment]
Hi, it seems that swal.isVisible() is always returning true when this animation function is called
