### ISSUE TITLE
Implement the first theme, let's start with "Minimal"

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#922]
First of all, here's the screeshot answering the question "why?":

![image](https://user-images.githubusercontent.com/6059356/36300639-c3f3c86e-130a-11e8-9724-efc6b2bba4d7.png)

So I guess, it's time to start implementing sweet themes for SweetAlert2 :)

From https://www.reddit.com/r/webdev/comments/7xput6/sweetalert2_a_beautiful_responsive_highly/dubc28n/

> This is cool, but to my eye, most of these boxes look a little big for general purposes. I think, generally, if I'm being alerted about... whatever, , I have no need for a ton of negative space of fun animations or big text, I just want a small box that grabs my attention (mostly via the contrast), tells me what I need to know, and gets my conversation.
>
>Of course, browser based alerts suck, and your shit is more customizable with a better button and without invoking the horror most people feel when they're trying to kill an ad that just won't die... So yeah, it looks like your alerts are the shit, I'm just giving my two cents, maybe a smaller box by default would get the job did well.

---

I need your opinions about files structure and themes organization. This is how I see it, feel free to suggest other solutions:

1. Themes will be nothing more than additional SASS files, I think it makes sense to keep all themes in this repository, let's say in `src/themes` folder

2. The structure of SASS files will be something like:

```scss
@import '../variables';
// overriding SASS variables
@import '../sweetalert2';
```

3. Compiled themes (CSS) will be located in `dist/themes` folder.

I will implement the first "Minimal" theme without animations and shit to make old-school fellas happy :)

**Comment by toverux** [comment]
Yeah! Excellent idea.
Also answers https://github.com/sweetalert2/sweetalert2/issues/547 (7 :+1:)

It would be good if the themes are also provided on the dist/ version as standalone CSS files, not just SCSS files.

**Comment by limonte** [comment]
> It would be good if the themes are also provided on the dist/ version as standalone CSS files, not just SCSS files.

Agree, added to the PR description

**Comment by zenflow** [comment]
> I think it makes sense to keep all themes in this repository, let's say in src/themes folder

Not that I am intent on it, but why not take the modular approach? That way it would be more natural for people to copy the boilerplate and make their own themes, or fork themes into their own. Plus all of the other arguments for modularity (the focus of this repo would be diluted, and how many/which themes do we accept in the core?)

**Comment by acupajoe** [comment]
I agree with @zenflow's leaning, themes should be separated out of this repo and could be added into our organization. I'd much prefer issues, releases, etc regarding themes be specific to the theme themselves rather than having to push them out as part of the main package.

**Comment by zenflow** [comment]
Also consider that any theme is inherently very opinionated. It would be nice to keep as much of that out of the core as possible. Opinions/tastes in separate modules on the other hand are totally fine since they can be swapped out for another more customized one (a fork or a fresh repository), and used just as easily (i.e. none are "special"). Ok I think those are my best arguments.

**Comment by limonte** [comment]
After some thinking I must agree with @acupajoe and @zenflow 

Modularity <3

Please check out my PR for `sweetalert2-themes` repository: https://github.com/sweetalert2/sweetalert2-themes/pull/1

**Comment by davalapar** [comment]
This is gonna be lit.

Some two cents I'm an avid user of Material UI and one of the things that stood out for me is their theme styling approach, which is as simple as setting some primary / secondary color values. Code example below:

```js
import { createMuiTheme } from '@material-ui/core/styles';
import purple from '@material-ui/core/colors/purple';

const theme = createMuiTheme({
  palette: {
    primary: purple,
    secondary: {
      main: '#f44336',
    },
  },
});
```

at https://material-ui.com/style/color/ they also got color swatches which are fun to play with.

Imho to be able to configure basic colors to element css to animation stuff in one place in js at get to sync them easily with other ui frameworks like material ui would be lovely as hell.

**Comment by limonte** [comment]
The first theme is published: https://github.com/sweetalert2/sweetalert2-themes/tree/master/dark

The minimal theme will be implemented here: https://github.com/sweetalert2/sweetalert2-themes/issues/16

The Material UI theme will be implemented here: https://github.com/sweetalert2/sweetalert2-themes/issues/14

Please subscribe to the related issues to be on track.
