### ISSUE TITLE
Typo with Dynamic queue example

### ISSUE THREAD

**Issue by peterbenoit** [sweetalert2/sweetalert2#924]
![capture](https://user-images.githubusercontent.com/492000/36310784-1c78c4c6-12f7-11e8-9e1b-2ae2ad535195.PNG)
![capture1](https://user-images.githubusercontent.com/492000/36310786-1c8507c2-12f7-11e8-8ff1-bd5fdcabd78b.PNG)

The word "get" is missing on the alert.

**Comment by limonte** [comment]
Should be fixed by https://github.com/sweetalert2/sweetalert2.github.io/pull/9 and https://github.com/sweetalert2/sweetalert2.github.io/commit/8938f478ac567d99b1011e2817b63a112493091f

Thanks for reporting @peterbenoit !
