### ISSUE TITLE
[macOS] a dialog stutters a little when opening the first few times

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#927]
From https://www.reddit.com/r/webdev/comments/7xput6/sweetalert2_a_beautiful_responsive_highly/dub33b3/

Screen recording: https://i.imgur.com/5Htq6gk.mp4

Browser: Chrome 64.0.3282.167 
OS: 10.13.3

Does anyone who have mac OS (I'm the Linux nerd) able to reproduce this issue? If it's reproducible we need to fix it asap as the issue is quite nasty.

**Comment by acupajoe** [comment]
@limonte same browser, same OS version and am unable to reproduce, can provide a screen recording demonstrating if need be.

**Comment by limonte** [comment]
Thanks @acupajoe!

This seems to be the issue for that particular user, closing this issue for now.
