### ISSUE TITLE
Support the <dialog> HTML element?

### ISSUE THREAD

**Issue by verlok** [sweetalert2/sweetalert2#935]
Why don’t Use the native `dialog` element instead of using `<div role=“dialog” … >`?

**Comment by toverux** [comment]
`<dialog>` is really new and is supported almost nowhere: https://caniuse.com/#feat=dialog so it would require another polyfill, but not only on IE this time.
In the meantime, `role='dialog"` is a well-known ARIA attribute that works very well.
So, one day probably, but it seems premature now.
