### ISSUE TITLE
Inner Message getting outside from alert in IE

### ISSUE THREAD

**Issue by javaProgrammer44** [sweetalert2/sweetalert2#937]
Hi All 
I'm using SweetAlert in Angular 5 project all working fine but it's inner text getting out from alert dialog.
This only happening in IE 

![image](https://user-images.githubusercontent.com/9882047/36547179-0e55338a-180f-11e8-8623-2eb6b2d0fc66.png)

**Comment by zenflow** [comment]
Please don't just ignore the issue template. It's there for a reason.

https://github.com/sweetalert2/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by zenflow** [comment]
To be more direct, we need a JSFiddle

**Comment by limonte** [comment]
I can reproduce: https://jsfiddle.net/ad3quksn/549/

Thanks for reporting @javaProgrammer44, it'll be fixed asap.

**Comment by limonte** [comment]
Fixed in 7.12.14, https://jsfiddle.net/ad3quksn/549/

**Comment by Yasirmacrosoft** [comment]
Yesterday I also provide the solution of this issue and pushed the code also. 
But I couldn't see my name in list of collaboration

**Comment by limonte** [comment]
@Yasirmacrosoft 

![image](https://user-images.githubusercontent.com/6059356/36593901-78148376-18a4-11e8-9736-28e0767da225.png)

**Comment by javaProgrammer44** [comment]
This is Yasir Shabbir and  it's my other account which I provided solution of it.
Yesterday I also provide the solution of this issue and pushed the code also.
But I couldn't see my name in list of collaboration

**Comment by limonte** [comment]
The attack of clones :astonished:
