### ISSUE TITLE
Swal inside a Swal - Second swal closes both(Is this the expected behavior?)

### ISSUE THREAD

**Issue by vsspt** [sweetalert2/sweetalert2#939]
I have a scenario where i have a first swal, that allows opening a second swal.

Actual: When closing the second swal (by OK or cancel), both the second and the first swal are closed.

Expected: When closing the second swal, the first one should remain open until explicitly closed (by OK or cancel).

Live demo: https://jsfiddle.net/ad3quksn/529/

**Comment by limonte** [comment]
There can be only one swal instance at a time. Each call of `swal()` removes the current modal and makes a new one.

**Comment by vsspt** [comment]
Would it be possible to implement the behavior i was expecting using the Queue functionality?
