### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by neilmaledev** [sweetalert2/sweetalert2#940]
**Does it support htmlUrl (templateUrl)? like on the bootstrap modal?**

=================================================================

If your issue is focused more on 'how do I do this?' rather than 'this is a broken functionality', then either ask on our Gitter https://gitter.im/sweetalert2/lobby or submit it to StackOverflow https://stackoverflow.com/questions/ask instead of GitHub, and make sure you add the sweetalert2 tag to the question.

---

For bug reports, please include:

- a jsfiddle in order for us to be able to reproduce the issue
- expected behavior of the plugin
- actual behavior

JSFiddle template: https://jsfiddle.net/ad3quksn/462/

JSFiddle template for IE11 and other old browsers: https://jsfiddle.net/ad3quksn/463/

**Comment by limonte** [comment]
No.
