### ISSUE TITLE
Adding Custom Class

### ISSUE THREAD

**Issue by Praunda** [sweetalert2/sweetalert2#945]
I am trying to add an extra class for my modal so I can select it from less and turn it's bg to transparent. But customClass is not working. Is there any other way to do it. BTW I have already changed a lot with default classes so I need to do this for just one modal can not effect the global swal.

**Comment by limonte** [comment]
Please read https://github.com/sweetalert2/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md and try to report your issue properly.
