### ISSUE TITLE
Unit tests against IE11

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2#947]
Follow-up to PR #885

Now we're using Karma, which has a lot more options in terms of community plugins, so we should be able to run our unit tests against IE11. It's also likely possible to test against Safari and mobile browsers, but I am less concerned about those because they are not *as* different from Chrome and Firefox, whereas it is likely that running tests against IE11 will catch a lot of issues. 

Also now we are transpiling the tests to ES5, so they can run in IE11.

Enabling IE11 in the test harness
---

In a Windows environment it is simple.. just add karma-ie-launcher.. but this will fail on a non-Windows environment.

We need a portable solution for this. The same would run on all environments ideally, but that may not be possible or feasible. Maybe of use: [karma-virtualbox-ie11-launcher](https://github.com/chrisguttandin/karma-virtualbox-ie11-launcher), [karma-detect-browsers](https://github.com/litixsoft/karma-detect-browsers)

Anyone have a suggestion on how to proceed?

Fixing the code for IE11
---

There are lots of little issues like fc81b1252bb3805d458ca72e32f60acf3659c4de which need to be cleaned out. My intuition says it is mostly portability issues in the tests, but there may also be some more actual issues in the source-code, like #942.

**Comment by limonte** [comment]
> In a Windows environment it is simple.. just add karma-ie-launcher.. but this will fail on a non-Windows environment.
>
> We need a portable solution for this. The same would run on all environments ideally, but that may not be possible or feasible. Maybe of use: karma-virtualbox-ie11-launcher, karma-detect-browsers
> Anyone have a suggestion on how to proceed?

For now, let's not introduce any virtualbox magic, but rely on AppVeyor CI: https://github.com/sweetalert2/sweetalert2/pull/948

I believe that should be enough for now. In case any PR added a regression in IE11 AppVeyor will notify core maintainers about that and they will either suggest the fix for external contributor or fix the regression after merging external PR.

**Comment by zenflow** [comment]
I'm gonna reopen this until part 2 "Fixing the code for IE11" is covered.

Note that we already have part 1 "Enabling IE11 in the test harness" covered in PR #948
