### ISSUE TITLE
Icon wrong place

### ISSUE THREAD

**Issue by guitar9** [sweetalert2/sweetalert2#955]
hi, the icon is in the wrong position. Somebody has the same problem? In JS fiddle it works correctly. I use google chrome.
![bildschirmfoto_2018-02-26_13-25-27](https://user-images.githubusercontent.com/25721108/36670986-5edda98e-1afa-11e8-9971-9485c9063013.png)

**Comment by zenflow** [comment]
@guitar9 

What is your specific browser name and version?

Can you please try to reproduce on jsbin.com? Here is a template to start with: https://jsbin.com/rawacenuyu/1/edit?html,output

**Comment by guitar9** [comment]
i cant reproduce it with JSfiddle.
I use Version 61.0.3163.79 
This is my style output:

[animation-delay:
0s
;
animation-direction:
normal
;
animation-duration:
0.3s
;
animation-fill-mode:
none
;
animation-iteration-count:
1
;
animation-name:
swal2-show
;
animation-play-state:
running
;
animation-timing-function:
ease
;
background-attachment:
scroll
;
background-clip:
border-box
;
background-color:
rgb(255, 255, 255)
;
background-image:
none
;
background-origin:
padding-box
;
background-position-x:
0%
;
background-position-y:
0%
;
background-repeat-x:
;
background-repeat-y:
;
background-size:
auto
;
border-bottom-left-radius:
4.0625px
;
border-bottom-right-radius:
4.0625px
;
border-top-left-radius:
4.0625px
;
border-top-right-radius:
4.0625px
;
box-sizing:
border-box
;
color:
rgb(115, 135, 156)
;
display:
flex
;
flex-direction:
column
;
font-family:
"Helvetica Neue", Roboto, Arial, "Droid Sans", sans-serif
;
font-size:
13px
;
font-weight:
normal
;
height:
212.875px
;
justify-content:
center
;
line-height:
19.123px
;
max-width:
100%
;
overflow-x:
hidden
;
overflow-y:
auto
;
padding-bottom:
16.25px
;
padding-left:
16.25px
;
padding-right:
16.25px
;
padding-top:
16.25px
;
position:
relative
;
text-align:
center
;
text-size-adjust:
100%
;
width:
416px
;
32em.swal2-popup<style>…</style>
-webkit-box-direction:
normal
;
-webkit-box-orient:
vertical
;
-webkit-box-pack:
center
;
-webkit-tap-highlight-color:
rgba(0, 0, 0, 0)
;](url)

**Comment by guitar9** [comment]
had found my mistake. I have overwritten css span element. 
Can be closed

**Comment by limonte** [comment]
@zenflow I believe we should start being more strict with issue reports. 

No jsfiddle + doesn't look like a valid issue on the first sight = immediate closing with a [saved reply](https://github.com/blog/2135-saved-replies), something like:

>For bug reports, please include:
> - a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
> - expected behavior of the plugin
> - actual behavior
>
>JSFiddle template: https://jsfiddle.net/ad3quksn/249/
> 
>IE11 JSFiddle template: https://jsfiddle.net/ad3quksn/250/
> 
> See [ISSUE_TEMPLATE.md](https://github.com/limonte/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by zenflow** [comment]
@guitar9 I asked for a reproduction on __jsbin__, not jsfiddle.. Sometimes the environment in jsfiddle is not true to the normal IE11 environment.

**Comment by zenflow** [comment]
@limonte On first sight it looked like it might have been a valid issue. That's why I requested more information.

What should we do when on first sight when it looks like it _may or may not be_ a valid issue? Shouldn't we try to find out if it is valid or not?

Also, what if there is a jsfiddle but you see if it's a invalid issue? Would you say it should be moved to StackOverflow? In those cases it is really tempting to quickly let the developer know what they're doing wrong, since you already see it.

**Comment by limonte** [comment]
> What should we do when on first sight when it looks like it may or may not be a valid issue? Shouldn't we try to find out if it is valid or not?

I don't have any strong opinion or arguments here. I'm just saying that it's fine and not unpolite to close the issue if a reporter didn't put enough effort into an issue-report.

If your intuition says "the issue isn't related to SweetAlert2", feel free to close it with a standard reply.

PS. I like how Vue.js organized the issue reporting process:

 - https://github.com/vuejs/vue/issues/new
 - https://new-issue.vuejs.org/

**Comment by zenflow** [comment]
> I don't have any strong opinion or arguments here. I'm just saying that it's fine and not unpolite to close the issue if a reporter didn't put enough effort into an issue-report.

Yeah, I agree. Some people are just dumb though lol and I have a hard time differentiating so I err on the side of caution.
