### ISSUE TITLE
SweetAlertResult could accept an optional generic parameter

### ISSUE THREAD

**Issue by rafaelss95** [sweetalert2/sweetalert2#958]
https://github.com/sweetalert2/sweetalert2/blob/138b5c87e84cb73e917c2efb81a5578b17067391/sweetalert2.d.ts#L239-L242

could be:

```
 export interface SweetAlertResult<T = any> { 
     value?: T; 
     dismiss?: swal.DismissReason; 
 } 
```

It'd be really great to have a `type` for `value` instead of `any`.

In addition we could also pass a parameter for these methods:

https://github.com/sweetalert2/sweetalert2/blob/138b5c87e84cb73e917c2efb81a5578b17067391/sweetalert2.d.ts#L9-L23

The signature would be:

`function swal<T = any>(title: string, message?: string, type?: SweetAlertType): Promise<SweetAlertResult<T>>; `

<hr>

Please, note that optional generic parameters requires typescript >= 2.3 (not really a problem, since we're already on 2.7~2.8).

**Comment by toverux** [comment]
Yep, this has already been discussed recently here: https://github.com/sweetalert2/sweetalert2/pull/926
Sure this would be cool...

But this is not possible now are we're still supporting TypeScript 2.1. Maybe one day... maybe... :smile:
