### ISSUE TITLE
Stopper: Alert crash on confirm or cancel click

### ISSUE THREAD

**Issue by vladimirivahnov** [sweetalert2/sweetalert2#960]
- the jsfiddle to reproduce the issue:
https://jsfiddle.net/ad3quksn/616/
- expected behavior of the plugin:
check for availability of the validationError, if don't exist then don't hide it
- actual behavior:
alert crash on confirm or cancel click

> Uncaught TypeError: Cannot read property 'style' of null
>     at hide (sweetalert2.all.js:1963)
>     at Function.sweetAlert.resetValidationError (sweetalert2.all.js:1225)
>     at confirm (sweetalert2.all.js:846)
>     at HTMLButtonElement.onButtonEvent (sweetalert2.all.js:926)

function executed with null argument
```
var hide = function hide(elem) {
  elem.style.opacity = '';
  elem.style.display = 'none';
};
sweetAlert.resetValidationError = function () {
      var validationError = getValidationError();
      hide(validationError);
....
```

I have made my research, it was broken at @limonte commit on 8 Dec 2017
"Reset validation error before executing preConfirm"
https://github.com/sweetalert2/sweetalert2/commit/f0b04f0cb2b7b7aa4d0aa4032d42f58d26dfa39f

**Comment by limonte** [comment]
Fixed in the latest release, thanks for reporting @vladimirivahnov :v:
