### ISSUE TITLE
Toasts: Icon alignment

### ISSUE THREAD

**Issue by fklingler** [sweetalert2/sweetalert2#964]
Icons in the circle are not aligned correctly in the toast:

![image](https://user-images.githubusercontent.com/282439/36780413-37a42116-1c73-11e8-8217-690a68d653c7.png)

**Comment by limonte** [comment]
Close by mistake, I guess :) Reopening.

**Comment by toverux** [comment]
Not reopened by mistake I assume =D Reopening.

**Comment by zenflow** [comment]
Anyone know which browsers this affects?

**Comment by toverux** [comment]
Well @fklingler is a colleague of mine, and he works on Chrome :smile:

**Comment by limonte** [comment]
@fklingler could you please also specify the zoom level you are using? Is it different from 100%?

**Comment by fklingler** [comment]
Sorry, I can't seem to reproduce this issue. I'm closing this!
