### ISSUE TITLE
await is a reserved word 

### ISSUE THREAD

**Issue by Lunatig** [sweetalert2/sweetalert2#966]
when i try to use 

const {value: text} = await swal({
    input: 'textarea',
    inputPlaceholder: 'Type your message here',
    showCancelButton: true
})

if (text) {
    swal(text)
}

than get a error  Error: await is a reserved word

**Comment by acupajoe** [comment]
To use the `await` keyword, the function directly enclosing it has to be marked as `async` [see SO answer](https://stackoverflow.com/a/42299762/3629438).
