### ISSUE TITLE
swal with input in vue method

### ISSUE THREAD

**Issue by Lunatig** [sweetalert2/sweetalert2#967]
when i try to use swal in vue component method, i can not change input value typing. focus don't set on input. its look like disabled. only select and number fields can be changed by mouse.

but if i use it separately(outside of component method) or even on created(mounted) method all work well.

**Comment by limonte** [comment]
>For bug reports, please include:
- a [jsfiddle](https://jsfiddle.net/) in order for us to be able to reproduce the issue.
- expected behavior of the plugin
- actual behavior

>JSFiddle template: https://jsfiddle.net/ad3quksn/462/
> 
>IE11 JSFiddle template: https://jsfiddle.net/ad3quksn/463/

See [ISSUE_TEMPLATE.md](https://github.com/limonte/sweetalert2/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by Lunatig** [comment]
thank you i tried to reproduce error and found that its my falt. 
the reason was in tabindex="-1" attribute of parent container with button .
is it bag or not? if its bag a can write all code here. but if its normal thank for help.

**Comment by limonte** [comment]
Thanks for the feedback @Lunatig 

Nothing to fix here.
