### ISSUE TITLE
Enable and promote code reuse the fp way

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2#968]
Related to #815

## The wrapper pattern

To reuse swal configuration, the promoted way is currently to use `swal.setDefaults`, but that method
1. stores configuration in global state, often making it harder to determine (by reading code) what defaults will be used
2. only supports having one configuration at a time
3. cannot merge configurations intelligently/dynamically. For example, if your reusable configuration uses `onOpen` and your instance configuration does too, the instance's `onOpen` will take precedence and the reusable configuration will be effectively broken. 

A better way is to use mixins, e.g. `swal({ ...myPromptOptions, title: 'whats your name?' })` and `swal({ ...myToastOptions, title: 'this is a toast' })`. This does not have the 1st or 2nd issues from above, but it doesn't help with the 3rd. Also this method is a bit verbose and not ergonomic in environments without object spread syntax ([which is not yet implemented in Edge or Safari](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator#Browser_compatibility)) where it looks more like `swal(Object.assign({}, myPromptOptions, title: 'whats your name?' })`. 

Finally, if you want or need real extensibility, it is possible (almost! see Enable section). Behold:

```js
// withCopyrightInFooter.js
export default (swal) => {
  const fn = (params) => {
    ...params,
    footer: (params.footer ? params.footer + '<br/>' : '') + 'Copyright Rick Sanchez'
  }
  Object.assign(fn, swal}
  return fn
}

// app.js
import swal from 'sweetalert2'
import withCopyrightInFooter from './withCopyrightInFooter'
const mySwal = withCopyrightInFooter(swal)
mySwal({title: 'Look! ', footer: 'This doesnt erase the copyright text'})
```
*(edit: in the above code I changed `swal(withCopyrightInFooter)` to `withCopyrightInFooter(swal)`*

As you can see, with this simple pattern, we gain a very robust extensibility. Not only can we add configuration pre-processing logic (i.e. fixes the 3rd issue above; we can merge configurations intelligently/dynamically), we can also extend the static methods (e.g. `swal.enableButtons()`, etc.), and transform the result value

## Enable it

For the wrapper pattern to work, the `swal` function/object **must** have a consistent API/shape. Currently a bunch of methods are added after the first swal opens, but they don't exist beforehand. I would assume this is not compatible with our `.d.ts` file. It's a problem because these methods don't exist at initialization, and thus they don't get added to the child swal in the above example of the pattern. See PR #969.

Also it would be *really nice* if we could expose the currently internal logic for mapping shorthand arguments (i.e. `swal(title, html, type`) to a `params` object. This way we can use the shorthand with our composed `mySwal` objects and don't need to [duplicate the logic ourselves](https://github.com/zenflow/sweetalert2-react-content/blob/master/lib/toParams.js#L7-L16). Without this, the shorthand feature is likely to be discarded in many scenarios.

## Promote it

We should deprecate `swal.setDefaults` and `swal.clearDefaults` and promote using mixins, or when robust extensibility is needed, the wrapper pattern.

We could and should also make the wrapper pattern easier to discover and use by adding an unintrusive convenience method!

**Comment by zenflow** [comment]
For one awesome example of what you can do with this pattern (though there are endless awesome examples possible), check out my WIP https://github.com/zenflow/sweetalert2-react-content ! Please open an issue! I'd like to get lots of review before transferring it to the sweetalert2 org and releasing 1.0.0!

**Comment by toverux** [comment]
I like it! It's simple and elegant. It does not compromises other future improvements on the API as well.

If I get it right, `swal()` will not trigger an alert if it gets passed a function - in that case, it acts as a mixin factory.

I just don't get that line:

```js
Object.assign(fn, swal)
```

Why do you assign `swal` to the function?

**Comment by zenflow** [comment]
> If I get it right, swal() will not trigger an alert if it gets passed a function - in that case, it acts as a mixin factory? It's not explicit in the post :)

Ooops... Made a really confusing typo above... I corrected it, please check it out again. The pattern is just a pattern, so no changes to the source code are actually needed for it to work. Though some changes like PR #969 will help this pattern in various ways.

**Comment by zenflow** [comment]
>Can you expand a bit more on this:
>`Object.assign(fn, swal)`

This is to copy all the properties and methods of the parent swal to the child, so you can do e.g. `mySwal.clickConfirm()`.

The idea is that you can decorate the `swal` object (i.e. pass it through a number of wrapper functions) and have a drop-in replacement for your normal `swal`, but with the added behavior/functionality. I'll demonstrate in a PR in the documentation repo.

You can easily add and extend methods:

```js
Object.assign(fn, swal, {
  newMethod: () => {}
  extendedMethod: (input) => {
    // do something with input
    let output = swal.extendedMethod(arg)
    // do something with output
    return output
  }
})
```

**Comment by toverux** [comment]
Yeah, the new example makes much more sense indeed! And it's better.

**Comment by zenflow** [comment]
> I'll demonstrate in a PR in the documentation repo.

Ah, I don't know what's going on with the Carbon ads in the docs repo.. they still aren't showing up for me on sweetalert2.github.io.. That's what I was going to refactor but I can't really do that.

**Comment by zenflow** [comment]
I was just going to demonstrate what I meant by "drop-in replacement":

```js
// before 
import swal from 'sweetalert2'

swal('using shorthand')
swal.clickConfirm() // using swal method

// after adding extension
import baseSwal from 'sweetalert2'
import withCopyrightInFooter from './withCopyrightInFooter'
const swal = withCopyrightInFooter(baseSwal)
swal('using shorthand')
swal.clickConfirm() // using swal method
```

It has the same API as the original, possibly extended with more methods/options/etc..

**Comment by zenflow** [comment]
In sweetalert2/sweetalert2-react-content#14 we've come up with a better terminology for this than "extension" .. "mixin"!

**Comment by zenflow** [comment]
Mixin method now exists, and I believe oo (not fp) is the way for robust extensibility, so I'll close this issue
