### ISSUE TITLE
Improve our issue triaging workflow

### ISSUE THREAD

**Issue by toverux** [sweetalert2/sweetalert2#975]
Currently, we're not really leveraging GitHub issue/PR labels at their full potential.

Most of the time, they are not applied, or inconsistently, even though we've made progress on this. We're also using mostly GitHub default labels, which aren't really readable (when you have a rapid glance at the issues list) or meaningful. Also, the colors are poorly chosen.

However, labels can be practical to answer the following questions:
 - _"What are the most critical bugs to reproduce/solve?"_
 - _"What issues are in my preferred domain of competence?"_
 - _"I have time to kill, what cool features are left to implementation?"_
 - _"Oh, an interesting issue. Not sure if I have the time: what's the estimated effort to solve it?"_
 - _"I'd like to contribute a first time to this library. Where would my help be appreciated?"_

Although the need is not too strong (we're not triaging hundreds of issues, like other projects), we get more and more issues and it could be nice to have, without much efforts.

The following labels lists are heavily inspirated from Angular teams' issue and PR triaging, in all their projects. They do not use exactly the same labels on each projets, but the general idea is there.

 - https://github.com/angular/angular/labels (best example, but I can't find documentation about the labels)
 - https://github.com/angular/material/labels (a little bit more messy)
 - **https://github.com/angular/angular.js/blob/master/TRIAGING.md** (Angular.js **1.x** triaging documentation, similar to today's process, I recommend to read it diagonally)

I have taken only a little subset of Angular repo's labels because we don't need to have such an advanced and complex triaging system. So I kept the most important ones and reorganized them a bit.

Enough with smalltalking, here's what I propose:

(note: "issue" and "PR" terms are always interchangeable in this proposal)

### `Domain` labels

Preferably one label of that kind per issue, but not necessarily.

 - <kbd>domain: dom/css</kbd> – DOM and CSS-related
 - <kbd>domain: logic</kbd> – for JavaScript-related issues about the behaviour of swal()
 - <kbd>domain: package</kbd> – for package issues, npm-distributed archives issues...
 - <kbd>domain: devel</kbd> – for development-related issues (build scripts, publishing, etc)
 - <kbd>domain: accessibility</kbd> – close to `dom/css` domain, it's specialized in a11y issues

### `Type` labels

There _should_ be only one of that kind per issue, when applicable.

 - <kbd>type: bug/fix</kbd> – `bug` for bug reports (issues), `fix` for PRs  – if the bug is not reproducible, ask for clarifications, and close after a week if no news are given
 - <kbd>type: feature</kbd> – self-explanatory
 - <kbd>type: refactor</kbd> – self-explanatory
 - <kbd>type: chore</kbd> – self-explanatory
 - <kbd>type: docs</kbd> – self-explanatory

### `Need` labels

Rare labels that require special attention from core mainteners, and they can be mixed.

 - <kbd>needs: breaking change</kbd> – solving this issue/merging this PR would cause a breaking change
 - <kbd>needs: public api</kbd> – solving/merging would augment SweetAlert2's API
 - <kbd>needs: discussion</kbd> – this issue requires special attention from watchers, core mainteners or other people, because important decisions are about to be taken (otr not)

This one won't be rare (unfortunately):

 -  <kbd>needs: repro</kbd>  – the bug report is not reproducible based on the given informations

### `Resolution` labels

They are specific to _issues_, not PRs. Must/should be only one of that kind per issue. You'll recognize some default GitHub labels here.

 - <kbd>resolution: duplicate</kbd>
 - <kbd>resolution: fixed</kbd>
 - <kbd>resolution: invalid</kbd>
 - <kbd>resolution: won't fix</kbd>
 - <kbd>resolution: works as expected</kbd>

### `Severity` labels

Flag issues/PRs so they can be treated more quickly (...or less quickly) depending on their severity. _Must_ be only one labels of that kind per issue.

 - <kbd>severity1: inconvenience</kbd> – not too bad, workaround(s) exists, can be fixed at any time
 - <kbd>severity2: broken</kbd> – may require a rapid intervention (hours or days), depending on the broken feature.
 - <kbd>severity3: regression</kbd> – must be handled as soon as possible
 - <kbd>severity4: security</kbd> – no one wants a CVE on SweetAlert2

### `Effort` labels

How much estimated effort is needed to handle this issue. _Must_ be only one label of that kind per issue.

 - <kbd>effort1: minutes</kbd>
 - <kbd>effort2: hours</kbd>
 - <kbd>effort3: days</kbd>

------------------------

### "Help wanted"

I also propose to keep the GitHub-standard <kbd>help wanted</kbd> label that GitHub recognizes (as well as <kbd>good first issue</kbd>) untouched.

------------------------

I propose to take the same color organization as the angular/angular repo:

![capture du 2018-03-01 22-18-27](https://user-images.githubusercontent.com/1343250/36870248-be3a3e78-1d9e-11e8-8959-251f20b108de.png)

Nothing too flashy, one color per kind of label. We can make color gradients for some kinds of labels though (for example, severity labels).

**Comment by limonte** [comment]
Absolutely YES! I'll handle creating new labels.

PS. Recently I'm learning so much from both of you @toverux and @zenflow :clap: :clap: :clap:

**Comment by toverux** [comment]
Yeah! The new labels are looking great!

I forgot to mention it here yesteday, but `.d.ts` should be renamed into `domain: typescript`.

And thanks ^_^
