### ISSUE TITLE
Expose logic for mapping shorthand args to params object

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2#979]
Subissue of #968. From the issue:

> Also it would be really nice if we could expose the currently internal logic for mapping shorthand arguments (i.e. swal(title, html, type) to a params object. This way we can use the shorthand with our composed mySwal objects and don't need to duplicate the logic ourselves. Without this, the shorthand feature is likely to be discarded in many scenarios.

Waiting for PR #976 to be dealt with and then I can handle this

**Comment by toverux** [comment]
Would also be useful in different SweetAlert2 integrations. In ngx-sweetalert2, I [reimplemented it](https://github.com/sweetalert2/ngx-sweetalert2/blob/master/src/swal.directive.ts#L37), and [a similar-ish thing](https://github.com/sweetalert2/sweetalert2-guards/blob/master/src/decorator_factory.ts#L25) is implemented in Guards, altough not exactly the same.

**Comment by zenflow** [comment]
Released in version 7.14.0
