### ISSUE TITLE
Failed cron build because of SauceLabs

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#985]
![](https://i.imgur.com/bo2k4gy.png)

If SauceLabs will cause failed builds in future, we'll need to stop using it. For now, I'll restart the build turn the red Travis badge into the green one.

**Comment by zenflow** [comment]
@limonte Were they working before?

**Comment by limonte** [comment]
@zenflow yes. You can check that by going to [build history](https://travis-ci.org/sweetalert2/sweetalert2/builds) and open the previous green build with this icon ![](https://i.imgur.com/oLC5pGt.png), e.g. https://travis-ci.org/sweetalert2/sweetalert2/builds/348209127

**Comment by limonte** [comment]
My previous experience tells that SauceLabs isn't 100% reliable, I was hoping they made some improvements, but unfortunately, it seems that instabilities are still happening.

**Comment by zenflow** [comment]
Do you know anything about BrowserStack?

**Comment by limonte** [comment]
> Do you know anything about BrowserStack?

I know that that's the very good SauceLabs competitor, but I don't have any experience with it. Let's give a chance to SauceLabs, if it will continue to be unstable, then we should investigate BrowserStack.

**Comment by zenflow** [comment]
Ok, sounds good.

But it's really unbecoming of a CI service, which is to ensure stability, to be unstable itself. It fails when everything is ok, and I don't know if we can we trust it when it says everything is ok..

I think we should wait a bit and then give SauceLabs a final chance.

**Comment by limonte** [comment]
> But it's really unbecoming of a CI service, which is to ensure stability, to be unstable itself.

It's not a trivial task to make a CI service stable, there's a devil (at least on my left shoulder) which tells  to bring dirty tricks to the CI configuration, e.g. https://github.com/sweetalert2/sweetalert2/pull/987
