### ISSUE TITLE
Karma instability: Some of your tests did a full page reload!

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#986]
Failed builds: 
- https://travis-ci.org/sweetalert2/sweetalert2/builds/348713443
- https://travis-ci.org/sweetalert2/sweetalert2/builds/349583573

The related issue in karma repo (oh, shit, it's almost 4 years old!): https://github.com/karma-runner/karma/issues/1101

**Comment by limonte** [comment]
Another failed build with the same issue: https://travis-ci.org/sweetalert2/sweetalert2/builds/348713443

**Comment by limonte** [comment]
Information from those 2 failed builds:

- it happens in Chrome only, Firefox is :ok_hand: 
- it happens randomly, not related to the particular test case

**Comment by zenflow** [comment]
Shit.. I wish I had a clue of how to approach this.. Will think on it

**Comment by zenflow** [comment]
Hmm.. could this have something to do with it?

```
$ yarn
...
warning "karma-webpack > webpack-dev-middleware@1.12.2" has incorrect peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
...
```

We are on webpack `^4.0.0`.

Either way, this could potentially cause problems.

Upgrading karma-webpack might fix the incorrect peer dep.

**Comment by limonte** [comment]
Facing this instability almost every day. Needs to be prioritized as CI instability + Greenkeeper produce a lot of noise.

**Comment by limonte** [comment]
> Upgrading karma-webpack might fix the incorrect peer dep.

It set to the latest:
  
- https://github.com/webpack-contrib/karma-webpack/releases
- https://github.com/sweetalert2/sweetalert2/blob/master/yarn.lock#L4525 

but the issue is still happening.

**Comment by limonte** [comment]
But yeah, the issue is possibly in `karma-webpack` because it has the outdated `webpack-dev-middleware` dependency `^1.12.0`:

https://github.com/webpack-contrib/karma-webpack/blob/master/package.json#L36

The latest of `webpack-dev-middleware` is `3.0.1`: https://github.com/webpack/webpack-dev-middleware/releases

**Comment by limonte** [comment]
There's an opened issue about it: https://github.com/webpack-contrib/karma-webpack/issues/314

**Comment by limonte** [comment]
There are two PRs:

- https://github.com/webpack-contrib/karma-webpack/pull/315
- https://github.com/webpack-contrib/karma-webpack/pull/318

And maintainers of `karma-webpack` are aware of the issue and probably will do the release soon.

**Comment by limonte** [comment]
Maybe https://github.com/sweetalert2/sweetalert2/pull/1028 was the fix, let's check if random failures are still happening after updating `karma-webpack` to `^3.0.0` and so `webpack-dev-middleware` to `^2.0.0`

**Comment by limonte** [comment]
> Maybe #1028 was the fix, let's check if random failures are still happening after updating karma-webpack to ^3.0.0 and so webpack-dev-middleware to ^2.0.0

Nope, still happening. I'll try `karma-webpack` `^4.0.0-beta.0` and `webpack-dev-middleware` `^3.0.0`

**Comment by limonte** [comment]
Upgrading `karma-webpack` and `webpack-dev-middleware` didn't help.

Also, using the latest Chrome didn't help https://github.com/sweetalert2/sweetalert2/pull/1029

This issue is driving me crazy :angry: Unstable CI is one of my worst nightmares.

**Comment by limonte** [comment]
Looks like #1031 really fixed this issue :tada:

**Comment by sdebanik** [comment]
It will solve this Karma redirect error!

var html = '<script type="text/javascript">';
html += 'window.location = "' + urlToRedirect +'"';
html += '</script>';
$( '.wrapper' ).append( html );
