### ISSUE TITLE
"document is not defined" - server side rendering broke from version 7.13.1 to 7.13.2

### ISSUE THREAD

**Issue by firstdoit** [sweetalert2/sweetalert2#996]
Hi, all.

From version 7.13.2 onwards, merely importing `swal` breaks node environments with "document is not defined".

I tried to find here what could have caused this to come up with a PR, but I couldn't find anything strange. Sorry :/

https://github.com/sweetalert2/sweetalert2/compare/v7.13.1...v7.13.2

**Comment by limonte** [comment]
Confirmed: https://travis-ci.org/sweetalert2/sweetalert2-adonisjs-nuxtjs/builds/349593951

**Comment by limonte** [comment]
The issue is somewhere around https://github.com/sweetalert2/sweetalert2/blob/master/gulpfile.js#L80 - there no any check of `document` existing in https://github.com/tests-always-included/gulp-css2js/blob/master/assets/defaultWrapper.js

**Comment by limonte** [comment]
@zenflow could you please handle this since as I can see you're the contributor of css2js as well? :muscle:

**Comment by limonte** [comment]
@zenflow now I know how the help-me-to-understand-infinite-loop looks like :D

**Comment by limonte** [comment]
@firstdoit fixed in 7.15.1, sorry for this inconvinience. @zenflow added the test to prevent such regressions in future.

**Comment by firstdoit** [comment]
Thanks!!
